### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by JACKCHEN99** [cuiliang/QuickPadCn#1]
开发者你好, 我刚使用quicker, 很喜欢, 感谢.
可以添加获取焦点的子程序吗?非专业人员, 表述不知道是否准确. 不知道现在是不是已经可以做到了, 而我不知道, 或者是说不好实现. 
我的功能需求是: 获取文本->打开程序->**焦点移到当前窗口(需要的功能)**->快捷键(只在此程序有效). 但是好像不可以焦点对准刚打开的程序, 快捷键没作用. 我主要是使用vivaldi浏览器, 也使用irreader看rss, 有时候文章太长我会想复制网址到edge里朗读(ctrl+shift+g), 因为win平台好像也没有选中朗读功能或类似软件.

**Comment by cuiliang** [comment]
你好，不是特别明白。 目前有一个把进程窗口激活到前台的子程序。 但是因为启动软件需要一段时间，有可能程序还没启动起来，这时候也没办法把窗口变成焦点窗口。
你是希望用edge打开网址么？ 如果是的话，理想的办法是通过命令行参数的方式传递给edge。

你可以具体描述一下，希望在什么软件里获取文本，打开什么软件，然后调用什么快捷键。

**Comment by cuiliang** [comment]
可以试试这个动作 https://getquicker.net/sharedaction?code=514c5723-0d33-4367-61c4-08d640932b11  复制链接后在空白按钮上右键，选择“粘贴分享的动作”
