### ISSUE TITLE
更新版本后，鼠标挂钩莫名失灵

### ISSUE THREAD

**Issue by lazycat11** [cuiliang/QuickPadCn#1000]
版本：1.7.5 系统：win10 64位 Chrome版本：81.0.4044.138
启动方式：Ctrl+中键单击
可能与Chrome有关，目前发生两次均是在我尝试在Chrome中打开quicker时出现，重启鼠标挂钩即可恢复；也可能与CPU或内存过载有关

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Kb/Article/300  请参考这里启用自动挂钩丢失检测功能。

**Comment by lazycat11** [comment]
> https://getquicker.net/KC/Kb/Article/300 请参考这里启用自动挂钩丢失检测功能。

好的，感谢
