### ISSUE TITLE
quicker编辑的时候突然只能输入英文的问题

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1002]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
不知道为什么时不时就会出现这个问题，用着用着搜狗输入法突然就只能输入英文了，明明悬浮的那个工具栏显示的还是中文状态，怎么切换都不行，但是过一阵子又可以输入了，或者退出编辑状态再编辑才能输入中文。不知道怎么回事，这个问题老早就有了，更新了很多个版本但是问题一直都在的，没有上github反馈，今天突然想起来了，所以就提一下。是搜狗输入法程序的问题还是quicker的问题？有其他人有出现类似我这个的情况嘛？
![image](https://user-images.githubusercontent.com/44609485/82862118-73ab6080-9f51-11ea-91ee-208c7d7d82da.png)
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
希望某个版本的更新能够解决这个问题。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可能是编辑器的问题，不过这个问题可能太底层了，能力不足啊

**Comment by cuiliang** [comment]
没有找到很好的解决办法，只能先切换一下到别的窗口再切换回来。 先close了。
