### ISSUE TITLE
运行cmd命令时无法获取最新环境变量

### ISSUE THREAD

**Issue by jerryproo** [cuiliang/QuickPadCn#1003]
**描述BUG**
通过 *运行程序或打开文件* 创建的打开cmd的动作, 通过该cmd无法获取最新的环境变量,
重启 Quicker 之后再打开动作可以获取到最新的环境变量.

**重现步骤**
1. 打开Quicker,创建基础动作以打开cmd
![image-20200527113122405](https://user-images.githubusercontent.com/29764127/82978603-8d16e000-a017-11ea-8e75-c9c28d59f4d9.png)
2. 在系统中添加任意环境变量
3. 使用Quicker打开刚刚新建的cmd动作, 执行命令时无法获取到刚创建的环境变量值

**环境信息:**
 - 操作系统版本：win10 1909
 - Quicker版本：1.7.5.0

**Comment by cuiliang** [comment]
这是正常的，
子进程会继承父进程的环境变量；
进程在启动的时候得到环境变量。

**Comment by jerryproo** [comment]
明白了,  感谢回应~
