### ISSUE TITLE
关于天若OCR

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1004]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
在quicker的动作库搜天若，怎么会有这么多的结果？完全没有合并起来。
![image](https://user-images.githubusercontent.com/44609485/82991366-2225d300-a030-11ea-8d2b-35091e287a9f.png)
当初上传的4个动作，这4个应该归类到下面的这个里面去才对：
![image](https://user-images.githubusercontent.com/44609485/83010306-a422f580-a04a-11ea-8b2b-79a1a32906b7.png)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by kunpeng9** [comment]
都是用的天若识别这个软件会什么会有两个分类，甚至更多的，目前已经通过修改基本信息归类到一个了。
![image](https://user-images.githubusercontent.com/44609485/83010899-902bc380-a04b-11ea-9d7a-a38fcc90a183.png)

**Comment by cuiliang** [comment]
根据exe文件名判断的，有可能一个程序会有多个文件名。

**Comment by cuiliang** [comment]
归档
