### ISSUE TITLE
在软件中设定好动作的轮盘菜单为什么还会有默认轮盘里的动作？

### ISSUE THREAD

**Issue by falconliu** [cuiliang/QuickPadCn#1006]
如何取消显示通用轮盘里的动作？

**Comment by cuiliang** [comment]
“可以设置默认动作，也可以在特定的软件中（如Word、excel中）设置软件相关的动作覆盖默认动作。”
只有设置了动作才能覆盖默认动作。 

目的是为了让通用动作可以在任何软件中都可以使用。
