### ISSUE TITLE
关于锁定/解锁动作页自动切换

### ISSUE THREAD

**Issue by cgy233** [cuiliang/QuickPadCn#1008]
很多时候，在其他应用窗口时，想要打开自己设置好的动作页内的应用，都要切换回桌面，次数多了觉得有点繁琐。
提供了锁定动作页自动切换，但是这个功能在电脑重启后重置，每次启动都需要重新设置，推荐设置一个默认锁定动作页自动切换的开关。
![自动切换](https://user-images.githubusercontent.com/57333094/83137322-912c2600-a11b-11ea-8cdf-6ec1654dde3a.png)

**Comment by cuiliang** [comment]
Quicker的思想是自动切换动作页的。你可以把有些启动动作放在任务栏动作页上，需要的时候点任务栏弹开。另外也可以添加加载动作页的动作，设置快捷键，这样可以一键打开某个动作页。

**Comment by cuiliang** [comment]
新版支持在锁定图标上右键选择要加载哪个应用的动作页。
