### ISSUE TITLE
无法提取最新的HTML内容, 网页内容更新后提取的仍是原来的值

### ISSUE THREAD

**Issue by herohuyongtao** [cuiliang/QuickPadCn#1009]
**描述BUG**
无法提取最新的HTML内容, 网页内容更新后提取的仍是原来的值.

例如: 第一次提取某个HTML内的温度是15度, 等网页更新为25度时运行获取仍然是15度.

**环境信息:**
 - 操作系统版本：Win 10
 - Quicker版本：1.7.5.0

**Comment by cuiliang** [comment]
可能是缓存的原因。 在url中增加一个多的参数，可以用随机数或时间。
我下个版本也增加一个不缓存的选项试试。

**Comment by herohuyongtao** [comment]
@cuiliang 没太明白, 请问如何在url中增加参数?

**Comment by cuiliang** [comment]
需要使用变量，在网址后面添加 &tick=随机数 这样的部分。如果不是很清楚，请等1.8.1版本试一下。

**Comment by cuiliang** [comment]
动作可以分享一下我这里测试下看看

**Comment by herohuyongtao** [comment]
刚才测试后面&tick=随机数 (0-100)结果还是老的值, 我尝试把动作分享出来

**Comment by herohuyongtao** [comment]
@cuiliang 是需要分享到动作库? 有离线分享的方法吗?

**Comment by cuiliang** [comment]
没有，如果有私有信息就不要分享了。可以先截图看看里面的设计。

**Comment by herohuyongtao** [comment]
截图见下: 逻辑很简单, 就是从某个网页html中提取个数字显示出来 (也会对比上次保存是否有更新)

如果需要模拟的话, 可以尝试读取[这个网站](https://www.timeanddate.com/worldclock/)里面的秒数, 方便每次运行判断是否更新. 多谢!

![image](https://user-images.githubusercontent.com/1265400/83259705-1af6f480-a1eb-11ea-933a-16d201481584.png)

**Comment by cuiliang** [comment]
提取html内容那里是怎么定义的呢？ 可以试试用http模块下载内容后再提取html。 直接在html提取那个模块里，缓存是不受控制的。

**Comment by herohuyongtao** [comment]
提取html部分见下, 这里面如何设置可以下载html再提取?

![image](https://user-images.githubusercontent.com/1265400/83270919-b7c18e00-a1fb-11ea-930a-7f7001bd628e.png)

**Comment by cuiliang** [comment]
https://getquicker.net/kc/help/doc/http 使用这个模块先下载内容。

**Comment by herohuyongtao** [comment]
好的, 我先尝试用这个下载html再读取试下. 

不过, 如果直接在上面提取html内容窗口里有个选项支持每次重新读取就好了.

**Comment by herohuyongtao** [comment]
@cuiliang 刚才测试, 先下载再读取是可以的.

不过这样是不是就不能通过指定 html/body/div这样精确定位再读取了?

**Comment by cuiliang** [comment]
把下载到的内容作为输入通过“提取html内容模块”提取信息

**Comment by herohuyongtao** [comment]
好的, 这样也可以, 多谢!

**Comment by herohuyongtao** [comment]
@cuiliang 现在功能确实没问题了, 不过可能由于下载的原因速度比之前慢了不少.

**Comment by cuiliang** [comment]
好的。之前快可能确实是因为缓存的问题。😂
