### ISSUE TITLE
关于quicker手机客户端与anywhere

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1011]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
群主有了解过anywhere嘛？是否从这个APP里面吸收点东西到quicker 手机APP里面呢？手机版quicker的利用程度很浅，使用频率很低，酷安可以下载这个APP，也是滴答清单的程序员告诉我，我才知道这个，前几个月，之前还真不知道，以为只有苹果 ios才有那个，就是安卓的捷径。还要ROOT才能用好麻烦。一直想搞来着，但是精力不足，用这个又需要学习新东西，酷安下载人数也不是很多。
那个推送验证码还有长连接是连手机嘛？ 用的比较少，没有很搞明白，用的很少。
之前好像也说到过 FV悬浮球之类的工具的，目前重点不在那边所以就随缘了。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by kunpeng9** [comment]
quicker手机版使用频率很低，突然想到小米的传送门功能，虽然理念很不错，但是使用体验不是很好，主要是服务支持太有限了，选中一个词，例如微信，提供支持的还是啥金山词霸【无法切换】，自动打开自带的那个垃圾浏览器【无法更换，之前似乎卸载过一次，卸了之后有些服务例如传送门好好像就用不了】，quicker电脑端的，搜索动作着实不少【可以切换各种搜索引擎】，为什么不能搬到手机上？这样任一 一种安卓手机【不是MIUI的】都能使用quicker 来使用传送门功能了。还有锤子bigbang 也非常不错，不过后来 使用频率越来越低，就卸载了。酷安看了一下，它已经开源了，假如这个可以在电脑上实现的话，用来创作思维导图蛮不错的，将文字拆分开，可以随意编辑拖拽组合，从悬浮的词组中提取词语作为关键词。

**Comment by cuiliang** [comment]
暂时不考虑增强手机端了。
