### ISSUE TITLE
关于重启软件的模块

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1013]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
由这个动作想到的这个问题。[&#x1F388;-创建今日笔记 - 已分享的动作 - Quicker](https://getquicker.net/Sharedaction?code=29db9ecf-1605-4390-a960-08d7296fb043 )
![image](https://user-images.githubusercontent.com/44609485/83326875-edbd4b80-a2a9-11ea-84cc-63e41d962615.png)
老是得退出软件才能运行这个动作，要是有运行的时候自动退出软件然后弄完了再自启的模块就好了，一劳永逸的解决这个问题。调整快捷键的方式不太合适，最好还是能由quicker来解决，因为用习惯了那些个全局快捷键，而且调整了之后还是可能会冲突。换成其他的例如组合快捷键，按起来不太方便，还要另外的记忆或者创建动作来替代。
可以由文本指令来解决这个，但是这个搜索里面还没有：
![image](https://user-images.githubusercontent.com/44609485/83326964-e185be00-a2aa-11ea-957a-8904cd82720f.png)
安装不了。
扩展指令和文本热键也没有那个软件exe属性。
动作里面的F3用不了，还是要自己修改快捷键，搞那个文本指令，要是可以点击工具箱 全部直接安装就好了。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可以用taskkill 关闭进程。不过感觉可能不会很稳定，可以试试。
