### ISSUE TITLE
为什么没通过？这个测速动作。

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1014]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

比较简单的一个打开网址，对 v2rayn.exe 翻墙效果进行测速的网页，这样就不用 打开那个speedtest浏览器插件进行测速了。
![image](https://user-images.githubusercontent.com/44609485/83346353-20b91b00-a34e-11ea-94fc-af364adafa29.png)
---
![image](https://user-images.githubusercontent.com/44609485/83346357-29115600-a34e-11ea-9ecb-eeddc2b403af.png)
和那个长城防火墙还有政策有关系嘛？
我的分享里面还是只有上一夜，下一页，
![image](https://user-images.githubusercontent.com/44609485/83346445-ff0c6380-a34e-11ea-99e4-c2bcb7b773df.png)
排序也没有，搜索未通过也不行
![image](https://user-images.githubusercontent.com/44609485/83346454-0d5a7f80-a34f-11ea-93d5-75338f9073ec.png)
我记得之前也有不少动作没有通过，忘记处理了，现在不太好找了。分享的动作有点多。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
是的，国家不是不让fq么，小心为好。
