### ISSUE TITLE
运行或打开模块=不能播放视频的问题

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1015]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
试了好几次但是都不行。
![image](https://user-images.githubusercontent.com/44609485/83349952-19543a80-a36b-11ea-9cd8-497473d82e8a.png)
到底应该怎么写？
![image](https://user-images.githubusercontent.com/44609485/83349956-22dda280-a36b-11ea-92b4-7475904dd3b8.png)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
期望场景如下：点击动作，运行或打开模块就用 potplayer软件播放指定位置的视频。
试了小半会儿都不行，是本身模块没设置好，还是没有这个功能？

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/83351600-0b58e680-a378-11ea-8c25-7993d0a6a126.png)
目录不存在。直接去掉。

**Comment by kunpeng9** [comment]
@cuiliang  我还以为这个是填入打开视频用的软件的地址，那个地址存在啊，电脑上，但是提示是那样，目前是不支持设置打开视频之类的文件嘛？ 就是用打开模块，设置用potplayer播放指定地址的视频

**Comment by cuiliang** [comment]
工作目录是目录，可以搜一下Working Directory
https://en.wikipedia.org/wiki/Working_directory
