### ISSUE TITLE
【建议】将分享动作视为新动作

### ISSUE THREAD

**Issue by wssdll** [cuiliang/QuickPadCn#1018]
**需求描述**
1，来源动作更新后，分享动作也会提示更新，实际是不可更新的，更新会导致分享动作被覆盖
2，“打开分享的动作网页”和“打开动作网页”易混淆

**描述你想要的解决方案**
1，建议将分享动作视为新动作

**描述您考虑过的替代方案**
1，将分享动作和来源动作的更新区分开，来源动作的更新不影响分享动作

 **其他上下文**
![image](https://user-images.githubusercontent.com/12515588/83485073-d1ebbc80-a4d8-11ea-9e19-f0f30525a3aa.png)

**Comment by cuiliang** [comment]
看的不是很明白。
分享动作，是指从动作库安装的动作修改后重新分享到了动作库里么？可以在动作选项里选择跳过检查这个动作的更新。

**Comment by wssdll** [comment]
> 看的不是很明白。
> 分享动作，是指从动作库安装的动作修改后重新分享到了动作库里么？可以在动作选项里选择跳过检查这个动作的更新。

创建动作时，选择从已分享动作创建，等于切了一个branch，此时原动作更新时，会影响到该分支
![image](https://user-images.githubusercontent.com/12515588/83589937-4bda7f00-a587-11ea-84dd-9952abcb8bc4.png)
![image](https://user-images.githubusercontent.com/12515588/83590193-c3101300-a587-11ea-819e-3680a99527e6.png)

**Comment by cuiliang** [comment]
后来增加了选项，可以对单个动作忽略检查更新。
![image](https://user-images.githubusercontent.com/1972649/94640012-1d3f9b80-0310-11eb-8280-1824c34775cc.png)
