### ISSUE TITLE
BUG:找图后执行的顺序

### ISSUE THREAD

**Issue by aquihia** [cuiliang/QuickPadCn#1020]
**需求描述**
希望能改为从上至下，从左至右找图。

**描述想要的解决方案**
当前找到的图是从左至右，从上至下找图的，导致执行顺序颠倒。

**描述考虑过的替代方案**
或者循环执行变量列表时，能选择正序或倒序。

 **其他**
文字处理--去除空行，不怎么好用呢。

![BUGx2](https://user-images.githubusercontent.com/66299551/83494168-732e3f00-a4e8-11ea-9105-dcf3dd29fcda.gif)

**Comment by cuiliang** [comment]
ok，我改一下。 去除空行可以调试运行一下，看看输入和输出，粘贴到这里我测试下看看。

**Comment by aquihia** [comment]
去除空行这个功能，我觉得跟运行环境有关；在word中处理就没有问题，但在Acrobat DC编辑pdf文件时，就去不掉空行了，估计是pdf的空行中有什么特殊字符吧。

### 翻译前
•	Intel-based, or PowerPC G4 or G5 Macintosh computer.
•	At least 1GB of memory; 2GB is recommended.
•	Mac OS X 10.5 or later, including 10.6 (Snow Leopard).
•	A monitor running at 1024x768 or greater resolution.
•	QuickTime 6.0 or later.
•	Adobe After Effects CS3 or later and/or Apple Final Cut Pro 5.0 or later. For version requirements for other host software, please refer to our web site for the latest information.

### 翻译后
•基于Intel的或PowerPC G4或G5 Macintosh计算机。

•至少1GB的内存；建议2GB。

•Mac OS X 10.5或更高版本，包括10.6（Snow Leopard）。

•以1024x768或更高分辨率运行的监视器。

•QuickTime 6.0或更高版本。

•Adobe After Effects CS3或更高版本和/或Apple Final Cut Pro 5.0或更高版本。有关其他主机软件的版本要求，请访问我们的网站以获取最新信息。

**Comment by aquihia** [comment]
> ok，我改一下。去除空行可以调试运行一下，看看输入和输出，粘贴到这里我测试下看看。

空行问题已解决啦，我增加了个替换文本\r的动作后，发现OK了。

**Comment by cuiliang** [comment]
1.8.2 已更新
