### ISSUE TITLE
建议：用户选择访问子程序（参考文本窗口）

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1025]
用户选择有没有可能像文本窗口一样访问子程序呢，如果支持的话那么用户选择的用户体验会提升很多（因为不用循环开启用户选择），比如选择文件打开：

现在的操作时选择结束窗口就关闭了，如果需要多次打开还得多写一些步骤而且界面会被重置，如果选项列表很长的话重新定位选项真的是一件挺头疼的事；

而如果能够参考文本窗口访问子程序，那么一个用户选择可以重复利用，操作会更加自然，况且目前用户选择支持右键菜单，个人觉得这个设计搭配右键菜单作为多次进行的附属操作应该是很不错的。

![IU~`115 CWPXLYIIN)@`FHN](https://user-images.githubusercontent.com/50692082/83627948-523e1a80-a5ca-11ea-870b-1639ea5f779b.png)

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
这个应该可以用自定义操作窗达到目的。
