### ISSUE TITLE
当前程序已使用了 Window管理器对象的系统允许的所有句柄。

### ISSUE THREAD

**Issue by mingjinglyh** [cuiliang/QuickPadCn#1028]
经常用着用着就无法唤起鼠标右键菜单，任何窗口都无法唤起，任务管理器也打不开，quicker面板能唤起，但运行任何指令都会提示【已使用了 Window管理器对象的系统允许的所有句柄】

这个问题从我用quicker以来，几乎每天复现几次，我前段时候特意完全重装了系统，原来是win10 1909，现在是2004，也还是一直复现。之前不会有quicker的提交反馈窗口，现在新版的有了。

**环境信息:**
 - 操作系统版本：win10 64位 2004
 - Quicker版本：1.7.5

图片如下
![微信图片_20200604110114](https://user-images.githubusercontent.com/45187089/83710777-12237a00-a654-11ea-8325-2e0f5f34e976.png)

**Comment by cuiliang** [comment]
平时都使用哪些软件？ 可能是和你所使用的某个软件冲突。 
目前报这个问题的用户并不是很多， https://getquicker.net/Help/Versions 这里可以看到每个版本和所有的反馈报告。

**Comment by mingjinglyh** [comment]
主要是微信，cent 浏览器，各种运行库都已经正常安装了

**Comment by cuiliang** [comment]
电脑详细硬件配置是什么情况？ 有用优化工具对电脑做过优化么？平时都使用什么动作？什么触发方式？Quicker内存占用平时多少？ 出问题的适合大概多少？

**Comment by mingjinglyh** [comment]
amd 3600 CPU，8G内存，没有用过优化工具，前段时间刚重装的系统，罗技鼠标X1键触发，内存占用大概30MB左右，我出现的时候就直接用软件提反馈日志得了

**Comment by cuiliang** [comment]
qk正常大约80-200M左右的内存占用，感觉30M比较小了，是否有其他程序占用比较多的内存呢？平时剩余内存大约多少？
另外这个选项是否开启了，如果开启把它关掉测试一下。
![image](https://user-images.githubusercontent.com/1972649/83878566-eea12200-a76e-11ea-8abb-64820dae2821.png)

**Comment by cuiliang** [comment]
1.0版本之后，到目前只有您有报这个问题。 
猜测可能是和系统里某个软件冲突了，或者系统做过什么优化，更改了某些注册表参数。
![image](https://user-images.githubusercontent.com/1972649/84967208-02249380-b146-11ea-91e7-4691d0896d3a.png)
