### ISSUE TITLE
用户选择选项中，编辑时出现文字无法识别情况

### ISSUE THREAD

**Issue by wangchen697** [cuiliang/QuickPadCn#1038]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不太明白，请录屏一下看看

**Comment by wangchen697** [comment]
这些无法显示的是中文字符，
英文字符可以正常显示


2389126922@qq.com
 
发件人： CuiLiang
发送时间： 2020-06-09 11:03
收件人： cuiliang/Quicker
抄送： wangchen697; Author
主题： Re: [cuiliang/Quicker] 用户选择选项中，编辑时出现文字无法识别情况 (#1038)
不太明白，请录屏一下看看

**Comment by cuiliang** [comment]
请截图或录屏看一下

**Comment by wangchen697** [comment]
窗口内的文字为乱码
但是运行是可以正常显示
变量也是一样的



2389126922@qq.com
发件人： CuiLiang
发送时间： 2020-06-12 19:02
收件人： cuiliang/Quicker
抄送： wangchen697; Author
主题： Re: [cuiliang/Quicker] 用户选择选项中，编辑时出现文字无法识别情况 (#1038)
请截图或录屏看一下

**Comment by cuiliang** [comment]
可能你的电脑缺少什么字体或有字体损坏了。如果有改过windows主题，试试改回windows默认主题后重启一下电脑。
