### ISSUE TITLE
关于动作更新的分享

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1039]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
有时候改 动作，怎么知道哪个动作更新了，和以往的不同，之前更新了不少动作，但是第二天有事情，连续一些天没接着搞，中断了，忘记了之前更新了哪些动作，没有第一时间分享出去，后来搞忘记了怎么办?
quicker很多模块目前还没有学会 怎么组合与有效利用，时不时学一下教程，编辑一下动作，有时候写了有时候没有，断断续续的，加上分享的动作比较多，搞不清楚了。目前动作有更新，图标右上角会有提示，什么时候出那个自己编辑的动作的更新的提示？
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
更新动作提示
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
