### ISSUE TITLE
不能以管理员身份运行软件

### ISSUE THREAD

**Issue by GH184683673** [cuiliang/QuickPadCn#1042]
不能以管理员身份运行软件

**Comment by cuiliang** [comment]
请详细说明一下了

**Comment by GH184683673** [comment]
> 请详细说明一下了

我想以管理员身份运行软件，如同windows右键菜单里面的“以管理员身份运行”

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/84223701-2d3b3180-ab0d-11ea-9d13-ce661f18e4cf.png)

**Comment by GH184683673** [comment]
3ky
