### ISSUE TITLE
增加双击任务栏启动或显示主窗体的功能

### ISSUE THREAD

**Issue by leizher** [cuiliang/QuickPadCn#1046]
**需求描述**
因为有些鼠标，中键不是很好操作，画圈也容易出现误判。

**描述你想要的解决方案**
建议可以增加双击任务栏空白区域，用来激活窗体或隐藏成体

**描述您考虑过的替代方案**
暂无

 **其他上下文**
暂无

**Comment by cuiliang** [comment]
会改变焦点影响动作，是不可行的。
