### ISSUE TITLE
能否批量添加已安装软件

### ISSUE THREAD

**Issue by CPCer** [cuiliang/QuickPadCn#1049]
Bug10的开始菜单搜索进程 `SearchUI`太卡了，想用 `Quicker` 替换。
请问能不能批量把所有程序都加进来？
或者直接内置这个功能嘛~

配图里也不能多选，只能一个一个拖进去……
![image](https://user-images.githubusercontent.com/8787958/84571615-ec6e4180-adc6-11ea-95ef-8ae30bf0cf3e.png)

**Comment by cuiliang** [comment]
截图这个状态下，可以从右边的窗口拖动到面板的空白按钮上。

**Comment by CPCer** [comment]
大佬好，是的，我想问的是，能不能批量添加……一个一个加太累了……
@cuiliang

**Comment by cuiliang** [comment]
哦，目前没有的，后期增加应用搜索启动。

**Comment by CPCer** [comment]
期待！
