### ISSUE TITLE
优化等待按键的提示

### ISSUE THREAD

**Issue by kanglade** [cuiliang/QuickPadCn#1051]
有时使用等待按键的动作可能需要常驻一段时间（比如WSAD键代替上下左右键），这时等待按键的提示的体验确实不太好，但考虑到安全问题又不得不提示，我这里想到了两种改进方案：
- 类似截图，屏幕的四条边一直出现线条（有的软件是蚂蚁线，TIM是蓝色实线），鼠标移到边上时显示提示信息
- 类似文本悬浮按钮，一个圆形悬浮在前端，鼠标移上去显示提示信息

另外看能不能做到：等待按键可能放在一个循环中多次使用，第一次自动弹出提示信息，而第二次等后面的循环时则不弹出提示信息，而只出现上面提到的两种正在使用等待按键的标识。

**Comment by guoranjun2** [comment]
好想法👍，那我也说一下其他想法，1是提供小一点的提示栏样式，2是生成托盘图标（这一种没有提示信息，主要就是警示用户按键正处于拦截状态）

**Comment by cuiliang** [comment]
1.9.10  已改为首次无提示的时候显示，后续空提示的时候不显示。
