### ISSUE TITLE
希望能更好的支持4K或更高分辨率显示器

### ISSUE THREAD

**Issue by ynqjwsm** [cuiliang/QuickPadCn#1054]
**需求描述**
4K下界面模糊

**描述你想要的解决方案**
希望能完美支持4K屏幕，图标矢量化

**Comment by cuiliang** [comment]
我一直都是用4k的屏幕，没有发现有模糊的情况。 软件本身的图标基本都是矢量图标的。请截图看下哪个地方模糊。

**Comment by cuiliang** [comment]
归档
