### ISSUE TITLE
同步异常

### ISSUE THREAD

**Issue by yougnut** [cuiliang/QuickPadCn#1056]
**描述BUG**
同步异常：發生一或多項錯誤。 傳送要求時發生錯誤。 無法連接至遠端伺服器 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應

**重现步骤**
1.启动
2.同步异常

**相关截图**
![Snipaste_2020-06-17_22-36-33](https://user-images.githubusercontent.com/67062125/84911844-4cc4f200-b0eb-11ea-95ad-932dec7ac9e5.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：18.5

**附加信息**
我人不在中国，挂了梯之后才能同步，想请问一下这是作者这边的正设吗?

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/84959918-fa0f2880-b132-11ea-93d2-a8491db53aff.png)
你的代理没有正常开启，或代理没法访问Quicker的服务器。

**Comment by yougnut** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/84959918-fa0f2880-b132-11ea-93d2-a8491db53aff.png)
> 你的代理没有正常开启，或代理没法访问Quicker的服务器。

感谢你，重新设定后正常了
