### ISSUE TITLE
轮盘菜单触发动作时显示自定义的右键菜单项

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1057]
如何触发？

**Comment by cuiliang** [comment]
治钧 17:50:03
@CL-北京 嗯，还想到了一个思路，唤出轮盘后点击左键，此时将轮盘悬浮，相当于面板了，可以点击执行，也可以右击打开菜单，Esc取消

**Comment by kanglade** [comment]
- 单击左键
- 双击左键
- 按住左键1秒
- 停顿几秒
- 键盘某个按键

**Comment by cuiliang** [comment]
释放时按ctrl弹右键菜单。
