### ISSUE TITLE
动作编辑窗口显示动作名称

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1060]
编辑窗口的标题可以把动作的名字加上去吗
有的动作有子程序，点击去的时候就看不到动作名字了
这样的话，当有多个较复杂动作编辑窗口打开的时候，就有点不好分辨哪个是哪个了

**Comment by kanglade** [comment]
最好任务栏上也能看得出来是编辑的什么动作
![image](https://user-images.githubusercontent.com/24608004/85189958-48185d80-b2e6-11ea-89d5-43f19c27cae6.png)

**Comment by cuiliang** [comment]
1.9.2
