### ISSUE TITLE
potplayer对应的quicker面板无法切换的问题

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1061]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
其他面板的没有发现问题但是就是potplayer，不知道为啥老是只显示第一个面板第二个面板不显示，滑轮还有点击那个面板中间的小点切换都没有反应。
![image](https://user-images.githubusercontent.com/44609485/85194818-f9c48800-b300-11ea-93f8-865ceb395220.png)
![image](https://user-images.githubusercontent.com/44609485/85194887-36907f00-b301-11ea-9c55-155fa7fca3b5.png)
![image](https://user-images.githubusercontent.com/44609485/85194891-3ee8ba00-b301-11ea-99fa-9b4ebd7558e2.png)
不知道是啥问题导致，不知道从哪几个版本开始有这个问题的，搞忘记反馈了，反正有好久了。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
测试了一下，本地是正常的，滚轮切换不过去么？
有没有使用手势软件？
![image](https://user-images.githubusercontent.com/1972649/85195406-c08e1700-b304-11ea-95ac-85801db10518.png)

**Comment by kunpeng9** [comment]
![image](https://user-images.githubusercontent.com/44609485/85195387-815fc600-b304-11ea-92c1-38e348bf97e3.png)
用screengif录了gif结果发现有300多，也没录很久啊，就几十秒，太大了，传不上来。

**Comment by cuiliang** [comment]
帧率设置成5，录制的区域小一点

**Comment by kunpeng9** [comment]
> 测试了一下，本地是正常的，滚轮切换不过去么？
> 有没有使用手势软件？
> ![image](https://user-images.githubusercontent.com/1972649/85195406-c08e1700-b304-11ea-95ac-85801db10518.png)

对，滚轮切换不过去。有使用手势软件啊，但是其他的都没问题啊，要是出问题不应该所有的都不能切换面板的吗？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
