### ISSUE TITLE
经常出现鼠标右键不能用的情况

### ISSUE THREAD

**Issue by adminil** [cuiliang/QuickPadCn#1067]
如题，唤出软件界面后鼠标就失灵了，之前一直没找到问题，刚刚试着退出软件，发现问题没了，退出软件后右键失灵的问题就没了，麻烦修复一下，不然这个软件都不能保持后台运行了。谢谢

**Comment by cuiliang** [comment]
需要提供尽量多的信息才能判断问题。

需要详细描述现象、发生的频率、复现的方法。

提供环境信息：

- Windows版本、32位还是64位操作系统 (可以运行winver命令查看)
- Quicker版本
- 使用的动作
- 同时运行的其他软件
- 其他可能相关的信息


排除可能影响Quicker运行的因素后再次测试。

- 彻底退出或卸载360软件。桌面日历软件。
- 请关闭可能使用剪贴板的软件以排除影响。
- 尝试排除其他可能造成影响的因素。
- 升级到最新的Quicker版本。



-

**Comment by laoli987** [comment]
我这边也出现过  特别是这几天 
用了ditto以及有效日历
