### ISSUE TITLE
执行autohotkey脚本速度特别慢

### ISSUE THREAD

**Issue by Sheldonchen76** [cuiliang/QuickPadCn#1069]
**描述BUG**
执行autohotkey脚本速度特别慢

**重现步骤**
1.执行脚本
2.选取.ahk脚本
3、输入脚本内容：run,notepad.exe,c:\windows\
      非常简单的脚本，运行记事本   
4、点击图标运行时，需等待1-5秒才启动记事本，而直接运行记事本则秒开

**环境信息:**
 - 操作系统版本：Win10 64位
 - Quicker版本：1.8.5

**Comment by cuiliang** [comment]
![temp_ahk启动notepad](https://user-images.githubusercontent.com/1972649/85238913-a9b20680-b463-11ea-840b-b697be22cf0f.gif)
测试了一下，没用你说的问题。 可能是你电脑磁盘有问题。 
脚本动作的实现是将脚本内容写入到临时文件，然后启动这个临时文件。

**Comment by Sheldonchen76** [comment]
![20200622_090701](https://user-images.githubusercontent.com/67232777/85239758-e7b12980-b467-11ea-988b-f4fab5f2fab7.gif)

启动确实很慢
华为Matebook X pro，SDD硬盘，使用其他程序都没有问题
在公司内网使用，有可能是临时文件需要用到管理员权限造成
能否更改临时文件的路径，或者允许自定临时文件路径测试下

**Comment by cuiliang** [comment]
临时文件夹是windows的，quicker里没法修改。 你可以试试直接启动ahk脚本文件

**Comment by Sheldonchen76** [comment]
直接在临时文件资料夹运行速度正常
我又仔细测试了一下，任何通过Quicker启动的程序，都比直接启动要慢1-2秒，不知道什么原因

**Comment by cuiliang** [comment]
不太清楚，可能windows有什么问题，可以试试重装一下看看
