### ISSUE TITLE
程序使用过程中触摸板双指滑动的“上下翻页”变成“放大缩小”

### ISSUE THREAD

**Issue by apreyX** [cuiliang/QuickPadCn#1074]
在使用quicker的沙拉查词翻译查词功能过程中，出现了触摸板双指滑动的“上下翻页”效果变成“页面放大缩小”的现象，时好时坏。退出quicker程序后重启电脑恢复正常。

**Comment by cuiliang** [comment]
开启沙拉查词的时候，根据动作里的设计，可能是在持续复制选择内容到剪贴板。
复制的原理就是发送ctrl+c，所以有时候ctrl是按下状态，这时候如果用触控板就会有你说的效果了。
