### ISSUE TITLE
列表作为状态保存的问题

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1075]
**描述BUG**
如果一个列表的某一项中含有回车，那么作为状态使用后再次运行动作，会发现原来的回车被识别成了列表项。具体如下：

现存列表：
0:123
1:123\r\n123

下一次运行动作
列表变为：
0:123
1:123
2:123

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10
 - Quicker版本：1.8.5

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
列表在quicker里主要是表示单行文本，所以很多地方都是直接通过换行来转换列表和多行文本的。

存储状态的时候也是将列表转换为文本保存，欢迎的时候再通过换行拆分。

所以这个估计不是很好解决😂，尽量不要在列表里保存换行的内容。或者使用其他字符代表换行，在需要的时候替换回去。

**Comment by cesaryuan** [comment]
> 列表在quicker里主要是表示单行文本，所以很多地方都是直接通过换行来转换列表和多行文本的。
> 
> 存储状态的时候也是将列表转换为文本保存，欢迎的时候再通过换行拆分。
> 
> 所以这个估计不是很好解决😂，尽量不要在列表里保存换行的内容。或者使用其他字符代表换行，在需要的时候替换回去。

可不可以在quicker软件层面自己实现而不是用户自己实现，比如换一个列表分隔符，假如换成&&，在输入时候自动把回车转换为&&保存，输出的时候把&&转换成回车。
我个人觉得作为一个列表，却只能存储单行文本有点别扭，哈哈。

**Comment by cuiliang** [comment]
这个倒是不难，主要是怕修改之后影响之前的数据。后期有理想解决方案的时候再修改

**Comment by cuiliang** [comment]
1.9.2 已改为json方式保存，支持换行了。
