### ISSUE TITLE
全局快捷键、触发角功能在黑名单程序中禁用

### ISSUE THREAD

**Issue by mgdreamingstar** [cuiliang/QuickPadCn#1076]
**需求描述**
虽然有黑名单，但是只是针对 quicker 呼出的黑名单，触发角还是会出发快捷键并呼出我设置的程序。

**描述你想要的解决方案**
能否提供 quicker 的全局禁用、开启的快捷键，或者触发角功能对全屏、黑名单中的程序自动禁用和恢复。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/85665891-68815700-b6ee-11ea-8192-2c2922688e52.png)

**Comment by cuiliang** [comment]
游戏的时候最好用这个暂停quicker

**Comment by mgdreamingstar** [comment]
谢谢，之前不知道有这个快捷键，没什么问题了。
