### ISSUE TITLE
每次更新之后在状态栏的图标都会变成白板，已经好多次了

### ISSUE THREAD

**Issue by zeyu-vehicle** [cuiliang/QuickPadCn#1077]
上传 文件失败
不懂，
你们可以自己试一下，先安装一个旧版，固定到状态栏，更新到新版之后，在状态栏的图标就会变成白板，需要重新固定才会恢复正常
自使用以来，每次更新都有这个情况，
望解决

**Comment by cuiliang** [comment]
不明白，请截图后粘贴到框里。

**Comment by cuiliang** [comment]
也可以用手机录制视频后传到网盘上发链接。 目前quicker里的没用”固定到xxx“的这种操作，钉住/锁定动作页等都是临时使用的。所以不是很清楚你说的具体是哪个操作。

**Comment by zeyu-vehicle** [comment]
链接：https://pan.baidu.com/s/1qk6KtnK-a75eNHMGv_al_w 
提取码：hnro 
复制这段内容后打开百度网盘手机App，操作更方便哦
是个截图，
是吧这个软件固定到任务栏，之后升级之后就会出问题
图里那个白色的就是quicker的标志

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/85819868-9b3b5600-b7a7-11ea-8044-12246bcc5f8c.png)
这个是您windows的问题，可能需要刷新一下图标缓存。

**Comment by zeyu-vehicle** [comment]
没道理呀，上面一排图标都没问题，就只有quicker有问题，
而且这样不是偶然，每次更新之后都有这个问题
在笔记本和台式机上都有这个问题，
那显然不能都是windows的问题呀

**Comment by cuiliang** [comment]
这就不好判断了。 也可能安装的其他软件影响。目前装机数量x万，暂时还没有其他朋友反馈。
另外这个快捷方式是什么时候使用呢？quicker一般不需要这样的快捷方式吧

**Comment by zeyu-vehicle** [comment]
用的时候才会打开，就把quicker软件固定到任务栏了
![image](https://user-images.githubusercontent.com/58206139/85962560-ec378e00-b9e3-11ea-98a3-d5193d21f082.png)
