### ISSUE TITLE
鼠标滚轮无法进行面板翻页

### ISSUE THREAD

**Issue by WangShanpeng** [cuiliang/QuickPadCn#1078]
**描述BUG**
鼠标滚轮无法进行面板翻页（已充会员）

**重现步骤**
1.鼠标中键唤起面板
2.滚轮无法进行面板翻页

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win10 LTSC 1809 17763.1282
 - Quicker版本：1.8.5.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
已经添加更多的页面了么？有没有显示翻页的小点？
使用了手势软件了么？ 可能手势软件拦截了滚轮消息。
另外可以试试换个鼠标确认一下硬件没有损坏。

**Comment by WangShanpeng** [comment]
> 已经添加更多的页面了么？有没有显示翻页的小点？
> 使用了手势软件了么？ 可能手势软件拦截了滚轮消息。
> 另外可以试试换个鼠标确认一下硬件没有损坏。

刚看了一下和StrokesPlus冲突了，谢谢，我再想办法设置一下

**Comment by cuiliang** [comment]
StrokesPlus里应该可以加黑名单
