### ISSUE TITLE
有没有mac版的开发计划啊

### ISSUE THREAD

**Issue by gZDJCVcH** [cuiliang/QuickPadCn#1079]
最近换到了mac，没有一款软件能够替代quicker，难受

**Comment by cuiliang** [comment]
mac有很多效率软件alfred什么的，可以试试。可能刚换mac不是很习惯。

**Comment by kunpeng9** [comment]
mac已经有那么多很好用的应用了，我在少数派看到的各种自动化啊，羡慕用的起Mac 苹果设备的人，目前开发人数太少了，多一个平台精力分散了到时候哪个都做不好【用Mac的人 你们已经够爽了，还想要跑来侵占win的便利，知足吧。。。】
