### ISSUE TITLE
群主是否需要使用同步圈？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1082]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
同步圈APP，可以试用一下。[应用详情 - 应用宝官网](https://android.myapp.com/myapp/detail.htm?apkName=com.gootile.tongbuquan&ADTAG=mobile )
微信发朋友圈会自动同步到微博，然后可以使用IFTTT，[Sina Weibo works better with IFTTT](https://ifttt.com/sina_weibo )，可以将自己发过的朋友圈【一次输出，可使用费曼技巧】通过微博的服务归档到印象笔记【必须国际版】或其他软件，可以发送到telegram、推特、脸书。同步圈我是从小熊熊学院 陈华伟的课程那里知道的，也可以去在行，[陈华伟 - 译者，CPA，小能熊OS创始人 | 到「在行」来约见我](https://www.zaih.com/falcon/mentors/2bj1yxdo7r2 )
[Sina Visitor System](https://weibo.com/u/6521700716?profile_ftype=1&is_all=1#_0 ) 发现陈华伟的微博页面一条微博都没有，可能他自己课程之后弃用了。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
可以使用一些自动化服务进一步优化发布信息的流程。
![image](https://user-images.githubusercontent.com/44609485/85924399-a9cb5f80-b8c4-11ea-9374-fc31e4dbc29a.png)
![image](https://user-images.githubusercontent.com/44609485/85924496-54dc1900-b8c5-11ea-8dac-94634180e8fd.png)
![image](https://user-images.githubusercontent.com/44609485/85924508-66bdbc00-b8c5-11ea-90d8-270e56bec547.png)
wei微博关注的人不多。
同步圈还有那个涨粉的部分，我靠，发现这个也太贵了吧，还得会员才能同步，有个试用会员只有30天，一年快100块，太贵了吧，还有终生的 198。
有兴趣的，可以试试。
![image](https://user-images.githubusercontent.com/44609485/85924680-6eca2b80-b8c6-11ea-963a-2dcca56d5492.png)
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by kunpeng9** [comment]
![image](https://user-images.githubusercontent.com/44609485/85924864-91a90f80-b8c7-11ea-9c1f-d9962fdf3b16.png)
试了一下朋友圈发送然后同步到微博，没有问题。
![image](https://user-images.githubusercontent.com/44609485/85924840-5c9cbd00-b8c7-11ea-95b8-1fc25f7d55c7.png)
这个更新内容为什么微博又要发一遍【手动发的？】？ 语雀不是发过了吗？
语雀写好了更新内容介绍→inoreader【要买会员才能用IFTTT】→IFTTT【自己写个动作】→微博，这样可行吗？

**Comment by cuiliang** [comment]
感谢分享，不过朋友圈我基本没发过所以用不上了。
