### ISSUE TITLE
获取网址可选择模式

### ISSUE THREAD

**Issue by Yaklo** [cuiliang/QuickPadCn#1083]
**需求描述**
网页存图

**描述你想要的解决方案**
将以前的网址获取方式添加为一个新的可选项

**描述您考虑过的替代方案**
无

 **其他上下文**
我自从更新后发现了也修改了动作，但有大概率第二个网页获取不了网址，显示无法获取粘贴板但是粘贴板是正常的，不知道是不是哪里冲突了
当我安装回1.8.0后使用原来的动作和获取方式一切正常

**Comment by cuiliang** [comment]
新版本改为ctrl+l跳转到地址栏获取文本了。 请检查一下是否在别的地方有使用这个快捷键组合。另外原来的方式也不稳定而且得不到协议头了。后期会增加chrome插件来完成这个工作。

**Comment by Yaklo** [comment]
能打开网址栏，能复制到剪贴板，就是会报错。之前的方式就没有这种问题

**Comment by cuiliang** [comment]
已发布浏览器插件，请安装插件后，使用quicker 1.9.4+ 版本，会先尝试通过插件获取网址。
