### ISSUE TITLE
小白发布需求，购买动作

### ISSUE THREAD

**Issue by 3425435** [cuiliang/QuickPadCn#1084]
**需求描述**
编程0基础小白，不想花时间看帮助文档

**描述你想要的解决方案**
小白发布需求，提供购买方案

**Comment by cuiliang** [comment]
在讨论区发帖https://getquicker.net/QA?order=createTimeUtc&p=1&category=6，
选合适的类型。
详细描述清楚需求和预算。如果有人愿意做会回复的，做完直接联系私下付款给对方就可以了。
