### ISSUE TITLE
设置-其他-「在以下进程中使用Ctrl+Insert作为复制快捷键」功能无效

### ISSUE THREAD

**Issue by ZaneCJP** [cuiliang/QuickPadCn#1085]
设置了「xshellcore」之后，依然无法复制（还是使用了Ctrl+C），动作无法获取到文本 和无法使用「按住左键点右复制或粘贴」功能

**Comment by cuiliang** [comment]
xshell是有多个进程，不一定检测到的哪个，可以试试把其他进程也加进去

**Comment by ZaneCJP** [comment]
已解决
