### ISSUE TITLE
关于轮盘功能的建议

### ISSUE THREAD

**Issue by bancqh** [cuiliang/QuickPadCn#1087]
我只是一个普通用户，也非程序开发人员。
只是对轮盘功能有个建议，不知是否适用。
轮盘作为快捷操作，应该便捷，准确，迅速。
目前轮盘3*8个功能区，个人感觉太多，用不上，而且面积大小一致没有主次，如果可以自定义区域大小和数量的话，把最常用的功能设置再区域大的地方，偶尔用的功能用在区域小的地方，我觉得更为方便

**Comment by cuiliang** [comment]
实现起来比较困难，暂不考虑了。
