### ISSUE TITLE
左键+右击：增加提示是否复制成功；

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1088]
https://getquicker.net/QA/Question/2224

考虑增加自定义其操作功能。

**Comment by guoranjun2** [comment]
建议再增加关闭左键+右击粘贴(未选中文本)的选项，有些编辑器（例，mindmanager）在一些情况下用前文的方式选中并返回文本的s等待时间比较长，此时quicker会判断为未选中文本而导致复制失败启用粘贴功能，而原本是打算复制的，但最后结果却变成粘贴了，所以个人认为增加一个选项比较稳妥，对于鼠标有侧键的用户来说，右键复制，X键粘贴的失误率最低

**Comment by cuiliang** [comment]
1.9.6 增加提示。
