### ISSUE TITLE
动态更新动作的右键菜单

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1089]
from 治钧
 关于动作的右键菜单，我一直有个痛点，没提是感觉可能不太好解决，不知道老大有办法么：举个例子，剪库全局菜单有「启用连续粘贴」，点击后会保存状态，下次菜单中则是「禁用连续粘贴」，这个菜单中的选项是动态的。现在我蛮希望动作的右键菜单也能有这个效果，不知道老大有办法实现么？点击右键菜单前可不可以先访问状态？

考虑使用一个特定的状态保存菜单override参数，显示菜单前先读取状态。 不过因为涉及到文件操作，可能有一定的性能影响。

**Comment by kanglade** [comment]
有了一个思路，让右键菜单定义栏里面支持插值，比如：
[fa:Light_Cog]{[某状态名]}|{[某状态名]}
这里借鉴了剪贴板插值的语法，我觉得取状态的话也可以再创一个语法，相信状态插值语法在其他地方也用得上。
就不用单独使用一个特定的状态了。

**Comment by cuiliang** [comment]
1.9.13 使用状态存取模块更新。
