### ISSUE TITLE
quick动作图标为空白

### ISSUE THREAD

**Issue by CharisLee** [cuiliang/QuickPadCn#1090]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.打开quick图标显示空白
2.编辑动作更改图标也是留白，有图标占位

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows 10
 - Quicker版本：1.8.5.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这通常是windows 临时文件目录无法访问造成的，在以前的版本里是直接崩溃的，后来的版本可能表现是图标显示不了。
可以参考：https://getquicker.net/kc/help/doc/error_0x80072ee4
https://getquicker.net/KC/Kb/Article/202
里面的方法解决。

**Comment by CharisLee** [comment]
> 这通常是windows 临时文件目录无法访问造成的，在以前的版本里是直接崩溃的，后来的版本可能表现是图标显示不了。
> 可以参考：https://getquicker.net/kc/help/doc/error_0x80072ee4
> https://getquicker.net/KC/Kb/Article/202
> 里面的方法解决。

可以了，非常感谢！
