### ISSUE TITLE
将系统字体替换为[新宋体]后，软件界面字体模糊

### ISSUE THREAD

**Issue by zsneala** [cuiliang/QuickPadCn#1095]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.使用noMeiryoUI.exe将系统字体换为新宋体
2.安装并打开Quicker

**相关截图**
![image](https://user-images.githubusercontent.com/50451654/87039901-707ae400-c222-11ea-93f9-03d3b9ef0998.png)

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.8.5.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈。 配置窗口的字体问题解决了，在1.9.6中更新。
面板窗口的文字可以在外观中设置字体，另外在分辨率比较低的情况下，放大缩小对字体的显示有比较明显的影响（要计算并且对齐像素，整数就会清楚，小数就会模糊了）
在低于4k分辨率的屏幕上，应该还是系统默认字体会效果好一些。
