### ISSUE TITLE
打开个别文件时显示没有应用程序与此操作的指定文件有关联

### ISSUE THREAD

**Issue by 1873879388** [cuiliang/QuickPadCn#1103]
**描述BUG**
使用打开文件命令时，通过路径打开某些文件时候，会出现“没有应用程序与此操作的指定文件有关联”报错，直接复制文件到空白按钮上粘贴这样是ok的

**附加信息**
https://www.yuque.com/quicker/help/open-file
就是说这个教程里面的方法一有时候会报错，方法二是没问题的

**Comment by cuiliang** [comment]
找一个有问题的，截图看一下配置

**Comment by 1873879388** [comment]
目前问题已经解决
原因大概是部分文件未指定默认打开方式，或者同个文件有多个程序可以打开
