### ISSUE TITLE
用户自己创建的动作，等待按键提示内容为空时不显示提示窗。

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1113]

**Comment by kanglade** [comment]
还是希望这样：
不管是不是自己创建的动作，
- 如果等待按键在循环体中，第一次时弹出提示，从第二次循环开始不再弹出提示，也就是一个动作实例只提示一次。
- 等待按键模块中，可以有个「不弹出提示窗」选项，或者为空时干脆不提示，不管是不是自己创建的动作。感觉安全风险还好，要不先试试？

**Comment by cuiliang** [comment]
@kanglade 再考虑一下。
一般什么情况下会需要循环等待按键并且不显示提示呢？

**Comment by kanglade** [comment]
举个典型例子（目前的话可能用扩展热键会比较合适，只是举个例子）：用WASD四个按键控制鼠标方向。等待按键放循环体中，第一次时提示，用户知晓后，后面进行上下左右的按键操作时就没必要提示了，如果还提示的话，每次按键提示窗都会闪一下，体验很不好，而且还会有遮挡。

**Comment by cuiliang** [comment]
1.9.10 重复的时候如果提示内容为空只在第一次显示。
