### ISSUE TITLE
输出值到词典的某个key、列表的某个序号？

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1115]
需要考虑：变量重命名

**Comment by kanglade** [comment]
这个期待👍

**Comment by kanglade** [comment]
![image](https://user-images.githubusercontent.com/24608004/87914638-851d6e80-caa3-11ea-9263-6bb32399d0de.png)
一个想法，供参考

**Comment by cuiliang** [comment]
主要问题是目前没有地方存键的信息😂 最初设计的时候没有考虑这种情况只保留了保存变量名的地方。

**Comment by kanglade** [comment]
是指动作定义中的「OutputParams」只存输出的变量名吗？
我有一个想法，可不可以创建新的语法，比如
{{词典变量.键A}}
在输出中允许输入以上内容，表示将值存入到「词典变量」的「键A」中。
不知道妥不妥当，会不会增加复杂度，或者今后重构或想到更好方式后再说？

**Comment by cuiliang** [comment]
嗯，目前估计只能通过这种方式。主要问题是编辑定义和更改变量名的时候比较麻烦，不过应该是可以实现的。

**Comment by kanglade** [comment]
嗯，又想了想，其实可以不用特殊的语法，直接写「变量名」或者「词典变量名.键名」或者「列表变量.序号」即可，如下：
词典变量.键A
只允许以上这些写法

**Comment by kanglade** [comment]
![image](https://user-images.githubusercontent.com/24608004/88005423-f90b5580-cb3b-11ea-9736-0bdc8f452997.png)
界面还是这样，保存用「词典变量名.键名」的方式实现，好像不错

**Comment by cuiliang** [comment]
1.9.10
