### ISSUE TITLE
调整图标太小会有bug

### ISSUE THREAD

**Issue by bafenfangliugeiher** [cuiliang/QuickPadCn#1118]
<img width="242" alt="20200721164108" src="https://user-images.githubusercontent.com/58677275/88033002-4c76a700-cb2e-11ea-920f-f7bcfdaee7ea.png">

**Comment by bafenfangliugeiher** [comment]
<img width="242" alt="20200721164108" src="https://user-images.githubusercontent.com/58677275/88033068-644e2b00-cb2e-11ea-9cdf-0f155a872158.png">

**Comment by bafenfangliugeiher** [comment]
![image](https://user-images.githubusercontent.com/58677275/88033175-8ba4f800-cb2e-11ea-8412-28397cb73d0a.png)

**Comment by bafenfangliugeiher** [comment]
害 图片好像不会发...

**Comment by cuiliang** [comment]
图标大小是根据按钮尺寸自动调整的。

**Comment by bafenfangliugeiher** [comment]
旁边会多出灰色的一块
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 下午5:27
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"米龙"<1371944268@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 调整图标太小会有bug (#1118)





 
图标大小是根据按钮尺寸自动调整的。

**Comment by cuiliang** [comment]
把边框宽度调整到0试试。

**Comment by bafenfangliugeiher** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 下午5:30
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"米龙"<1371944268@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 调整图标太小会有bug (#1118)





 
把边框宽度调整到0试试。

**Comment by bafenfangliugeiher** [comment]
从稳定版升级到1.9.9就正常了&nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 下午5:30
收件人:&nbsp;"cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送:&nbsp;"米龙"<1371944268@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 调整图标太小会有bug (#1118)





 
把边框宽度调整到0试试。

**Comment by cuiliang** [comment]
好的。
