### ISSUE TITLE
词典默认使用原始值

### ISSUE THREAD

**Issue by kanglade** [cuiliang/QuickPadCn#1122]
词典的话，我觉得默认使用原始值比较好，感觉原始值比较规范，表达式好处理。
后面的Quicker版本，在涉及词典的地方，可以考虑就全部用词典原始值。
再考虑到对原来文本形式的支持，可以加个选项：「使用文本形式」，
今后的版本默认不勾选这个选项，但考虑到兼容性，之前的动作默认是勾选上的。

注：因为原始值是主流，所以加的选项是「使用文本形式」，而不是「使用原始值」

**Comment by cuiliang** [comment]
除了设置值，其它还有什么操作使用到原始值的地方不？ 目前赋值已经区分原始值和文本值了。

**Comment by kanglade** [comment]
有种感觉，干脆全部采用原始值（取消文本值好了），应该没啥副作用吧
我词典用的很多，直接操作词典的文本值几乎没有（好像有过一次，后来放弃了），几乎都是用的「词典操作」模块
要不先出一版改成只有原始值的试试？看看反馈再说？

关于涉及到的操作，我想只要是更新词典的地方都会用到的吧，「词典操作」模块中的操作、「赋值」模块、变量管理中的词典默认赋值、还有各种输出到词典？

还有一个在意的问题，词典原始值保存在状态中是什么形式呢？对象的某种编码吗？

**Comment by kanglade** [comment]
想到还是有一个问题，原来保存在状态中的词典数据是文本值形式，改成原始值后，取状态估计有兼容性的问题吧

**Comment by kanglade** [comment]
> 想到还是有一个问题，原来保存在状态中的词典数据是文本值形式，改成原始值后，取状态估计有兼容性的问题吧

取状态的时候，自动识别转换成原始值怎么样呢？状态的话兼容一下，动作模块中就全部使用原始值。

**Comment by kanglade** [comment]
![image](https://user-images.githubusercontent.com/24608004/88353795-724fb600-cd91-11ea-9ea3-6a0702676113.png)
这样似乎挺好，没啥问题，状态的存储也没变化
