### ISSUE TITLE
鼠标辅助的“左键+字母”Bug

### ISSUE THREAD

**Issue by dk-angela** [cuiliang/QuickPadCn#1125]
**描述BUG**
鼠标辅助的“左键+字母”是个很好用很有创意的功能，但是能不能考虑给个开关？最新版加入“空格”变回车的功能之后，导致一个 Bug。设计师在使用 Photoshop 或者 Illustrator 软件的时候，非常频繁地需要按住空格键来移动画布，但是现在如果不关闭这个辅助功能，就会导致我们在移动画布的时候会突然停下来，因为先按住空格再用鼠标移动，同样会触发“空格变回车”。

恳请解决先按住空格再按住鼠标也会触发的 bug，或者给个小项的独立开关，万分感谢。

**重现步骤**
1.打开 Illustrator 或 Photoshop 文件。
2.按住空格，再使用鼠标移动画布。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
升级到1.9.11版本，已经去掉空格了。
另外配置里有选项可以关闭整个功能。
![image](https://user-images.githubusercontent.com/1972649/88401872-e1162900-cdfc-11ea-9edf-443bd8e504ae.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
