### ISSUE TITLE
动作运行出错时，提示出错的表达式原文

### ISSUE THREAD

**Issue by marcusxx** [cuiliang/QuickPadCn#1127]
有时一些非语法性的错误，并不能每次都出现，如果仅仅运行途中提示出错，难以定位。

想要弹窗消息展示出错原因之外，再附带显示出错语句表达式原文，如果能再展示子程序名称就更好了。

远期的愿景是希望能自动记录下出错的log，如：当前使用了哪些变量，值分别是多少。

实现效果如图：
![image](https://user-images.githubusercontent.com/48142413/88462895-72f76200-cee1-11ea-97c2-21988a118af6.png)
![image](https://user-images.githubusercontent.com/48142413/88462958-edc07d00-cee1-11ea-9b97-3d8f59f50168.png)

**Comment by cuiliang** [comment]
目前表达式会先使用新版引擎尝试解析，出错后再使用旧引擎解析。最后报错的是旧引擎的错误消息。
另外因为层级比较深，最后报错的时候可能已经无法获得原始错误信息了。 
下一个版本我在表达式解析出错的时候写一个quicker日志，在quicker.log中记录详细的错误信息，等看看效果。

**Comment by cuiliang** [comment]
已增加。另外quicker.log中也保存了一份。
