### ISSUE TITLE
Quicker网页对已分享动作“修改基本信息”后无法提交

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#1129]
**描述BUG**
Quicker网页 对已分享动作“修改基本信息”后无法提交

**重现步骤**
1.修改基本信息
2.修改了
（1）在什么软件下有效，
（2）分类标签 ，
（3）备注。
3.保存
4.网页错误（“Error.An error occurred while processing your request.”）

**Comment by cuiliang** [comment]
可能某个数据太长超过了数据库的限制，或者指定的exe文件不存在。

**Comment by cuiliang** [comment]
已增加exe是否合法的验证。
