### ISSUE TITLE
方便的添加和删除复杂词典项或 JSON 的项

### ISSUE THREAD

**Issue by mgdreamingstar** [cuiliang/QuickPadCn#1135]
**需求描述**
对于词典来说，好像不支持复杂的值类型。
对于 JSON，好像又没有方便添加新项的功能。

**描述你想要的解决方案**
对于 JSON，能否添加功能使得新增或删去一项更方便一些。

**Comment by cuiliang** [comment]
新版中支持将自定义类型的值写入词典中。
![image](https://user-images.githubusercontent.com/1972649/88776114-239e8380-d1b8-11ea-88f3-fd646d0dabad.png)

**Comment by cesaryuan** [comment]
> **需求描述**
> 对于词典来说，好像不支持复杂的值类型。
> 对于 JSON，好像又没有方便添加新项的功能。
> 
> **描述你想要的解决方案**
> 对于 JSON，能否添加功能使得新增或删去一项更方便一些。

可以使用js模块，非常方便

**Comment by mgdreamingstar** [comment]
> > **需求描述**
> > 对于词典来说，好像不支持复杂的值类型。
> > 对于 JSON，好像又没有方便添加新项的功能。
> > **描述你想要的解决方案**
> > 对于 JSON，能否添加功能使得新增或删去一项更方便一些。
> 
> 可以使用js模块，非常方便

好的，没学过 js，我去试试。

**Comment by mgdreamingstar** [comment]
> > **需求描述**
> > 对于词典来说，好像不支持复杂的值类型。
> > 对于 JSON，好像又没有方便添加新项的功能。
> > **描述你想要的解决方案**
> > 对于 JSON，能否添加功能使得新增或删去一项更方便一些。
> 
> 可以使用js模块，非常方便

好的，没学过 js，我去试试。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
