### ISSUE TITLE
标签形式的多面板

### ISSUE THREAD

**Issue by capedghost** [cuiliang/QuickPadCn#1136]
Quicker的单面板装不下太多东西，建议在Quicker面板中，使用标签形式来设置多面板，就像浏览器的网页标签一样。
Quicker的标签可以是纯图标外观，放在面板的左侧或右侧垂直排列。

这样就能大大增加Quicker面板的容量了，可以装下更多动作和应用。

**Comment by crawlingsnail9** [comment]
现在是用滚轮来切换不同的面板，换成标签形式好像并不会增加承载动作的能力吧。
