### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by ilovewish** [cuiliang/QuickPadCn#1138]
**描述BUG**
对bug的清晰简洁描述。
运行异常结束之后,会弹出异常提交信息窗口,这时候会卡住整个窗口,任何点击都无法响应,必须使用命令行进行强制关闭进程
**重现步骤**
异常突发得,我无法复现,不过这情况不知一次发生,遇到过两次,间隔一周左右

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 企业版
 - Quicker版本：1.6.7.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
请升级到新版。 1.6.7 有一个bug会比较容易造成崩溃。

**Comment by cuiliang** [comment]
1.9.18版本已发布到慢速通道，请测试看看。如果还出问题请再reopen此问题。
