### ISSUE TITLE
选择日期、时间的模块

### ISSUE THREAD

**Issue by mgdreamingstar** [cuiliang/QuickPadCn#1139]
**需求描述**
有时会有选择日期的需求，现在的获取时间动作不太直观，可否实现一个 ui 可以用鼠标点选日期？

**描述你想要的解决方案**
弹出一个界面，可以选择某一天的某个时间；或者选择几天后、一周后等。

**Comment by cuiliang** [comment]
用在什么地方呢？ 目前用户输入有一个输入日期的方式。
![image](https://user-images.githubusercontent.com/1972649/89154195-ffb4b680-d598-11ea-9c4d-004344b08e15.png)

**Comment by mgdreamingstar** [comment]
做了一个记录项目起止时间的动作，有时会忘了记录。在补记的时候，过去某天的日期选择不是很方便。

**Comment by cuiliang** [comment]
归档
