### ISSUE TITLE
建议可以让用户插入一个全新的面板；提供可以将桌面快捷方式直接拖动quicker之中；

### ISSUE THREAD

**Issue by YeWeiJu99** [cuiliang/QuickPadCn#1143]
**需求描述**
quicker的面板固然好用；但是满足的需求不够，例如，我在使用Chrome时，需要打开一个软件，但是我调用出的面板是Chrome独有的动作，这时我需要回到桌面，再调出面板打开软件；其次，全新的面板，看用户需求自主添加什么时候可以调用；例如alt+空格调用全新的面板，我可以将我桌面的程序快捷方式，直接拖动其中，这样就能快速运行我的动作。

**描述你想要的解决方案**
参考Rolan3的动作；目前本电脑Rolan3和quicker一同使用，但内存占用较高。觉得quicker完全可以加入rolan3快速启动的动作；

**描述您考虑过的替代方案**
若考虑到其可能会对rolan3造成巨大的经济损害，因此，只是提议；

 **其他上下文**
![image](https://user-images.githubusercontent.com/46995510/89121629-0688ee00-d4f3-11ea-86a5-898b1edc3831.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/89134832-e3922480-d55a-11ea-9844-6de16d33b293.png)

因为权限的原因，是无法将文件/快捷方式拖到面板上的。
目前有几个方法：
1. 将启动动作添加到任务栏动作页上，这样需要的时候点击任务栏就可以了。
2. 如上图，添加加载动作页的动作，这样不需要切换到桌面也可以打开相应的动作页。

**Comment by YeWeiJu99** [comment]
添加动作页我也考虑到了，但是至少不能直接一步到位。因为一开始我是rolan3的粉丝，不过rolan3的功能局限在了快速启动的功能上；所以比较期待quicker能完成这一举动。貌似在吾爱破解的虚拟机中，使用的大多数面板工具都可以直接拖动快捷方式。如果真的是不行，那么我也感谢您的回答。这个软件是真的好用，现在我把rolan丢了。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: CuiLiang<mailto:notifications@github.com>
发送时间: 2020年8月3日 7:30
收件人: cuiliang/Quicker<mailto:Quicker@noreply.github.com>
抄送: 你若在天则晴<mailto:jimo520jimo@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [cuiliang/Quicker] 建议可以让用户插入一个全新的面板；提供可以将桌面快捷方式直接拖动quicker之中； (#1143)


[image]<https://user-images.githubusercontent.com/1972649/89134832-e3922480-d55a-11ea-9844-6de16d33b293.png>

因为权限的原因，是无法将文件/快捷方式拖到面板上的。
目前有几个方法：

  1.  将启动动作添加到任务栏动作页上，这样需要的时候点击任务栏就可以了。
  2.  如上图，添加加载动作页的动作，这样不需要切换到桌面也可以打开相应的动作页。

―

**Comment by cuiliang** [comment]
先关闭了。
目前windows的开始菜单也比较好用，再加上权限因素很难有良好的用户体验，quicker里暂不考虑再增加类似功能了。
