### ISSUE TITLE
子程序相关改进需求

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1144]
- 更新子程序版本
- 本地收藏和管理子程序
- 转换为子程序后，批量设置变量的输入输出标记；
- 下拉方式指定子程序的可选值； #891
- 多行类型子程序参数；
- 提供类似消除未用变量的功能，可以一键删除未使用的子程序
另外在删除已使用的子程序时，也给出提示
- 创建变量时，不显示“请勿更改变量名”的告警提示。

![image](https://user-images.githubusercontent.com/1972649/90408349-4a2a4d00-e0da-11ea-8da7-a572813896d6.png)

**Comment by cesaryuan** [comment]
终于提上日程了

**Comment by kanglade** [comment]
- 左侧新增标签页来管理子程序
- 子程序A中使用其他子程序B时，右键「编辑子程序：B」时，可以跳转到子程序B，并且提示是否保存子程序A
- 转换为子程序更加智能：将外部没用到的变量不作为输入和输出

**Comment by crawlingsnail9** [comment]
希望后续在网站能预览子程序的定义。
然后python中那种if __name__ == '__main__' 的机制加在子程序上会不会有用呢？
一个好处是：便于查看子程序效果，现在得下载到本地，然后提供它需要的输入，再用其他模块来输出。

**Comment by cuiliang** [comment]
#1206  在这里整理了。
