### ISSUE TITLE
表单相关需求

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1146]
- 检查框增加文字标签显示位置的选项
![image](https://user-images.githubusercontent.com/1972649/89155793-1dcfe600-d59c-11ea-9c26-8fa4cbaa16a0.png)

- 支持词编辑

**Comment by marcusxx** [comment]
我也来提需求：
- 增加表单选项卡，实现类似Quicker设置的功能：
![image](https://user-images.githubusercontent.com/48142413/89200424-96f22c00-d5e2-11ea-9e69-27e6a7eee695.png)


- 增加动态表单，实现类似文本处理时选择不同的处理功能：
![image](https://user-images.githubusercontent.com/48142413/89201005-6eb6fd00-d5e3-11ea-9a9b-63514e49c9f1.png)

**Comment by marcusxx** [comment]
迫切需要能使用变量的动态表单。
解决方案想法：整个表单通过状态数据来生成，这样不仅内容，连表单字段、标题、输入方式等等都可以随时变更。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
