### ISSUE TITLE
方便解决一下使用手势时任务栏闪烁的问题吗？

### ISSUE THREAD

**Issue by marcusxx** [cuiliang/QuickPadCn#1147]
平时每次使用鼠标手势任务栏都会短暂闪一下，今天发现不松开鼠标任务栏就一直不出现，实在太影响使用体验了。

想到一种解决方案，不知是否有效：如果鼠标手势功能是通过创建一个全屏透明窗口实现的，那能否把窗口尺寸限定在一个范围内，不要覆盖任务栏，这样是否就看不到任务栏变化了。

![image](https://files.getquicker.net/_actionDemos/b33bc59e-723f-45ba-e64e-08d77ecf5668/shoushiBug.gif)

**Comment by cuiliang** [comment]
今天测试了一下没有出现变透明的情况，但是如果有一个窗口是在任务栏的位置后面，在它上面画手势的时候，它会跑任务栏前面。
改成工作区大小了，等下一版试下看看。

**Comment by cuiliang** [comment]
22版这个现象有改善么？透明窗口已经改成只显示在桌面工作区域了。 @marcusxx

**Comment by marcusxx** [comment]
问题已解决
