### ISSUE TITLE
quicker大数据显示

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1151]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
[Quicker 大数据 2020年7月 - Quicker](https://getquicker.net/QA/Question/2250 )图片是不是太小了。
太难看了吧？不能生成网页结果或者其他的结果吗？字特别小，方大了之后仍然很难看。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
能否换成其他的格式的文件来显示。其实可以分几份来发的，合成一份图片，里面的内容查看起来很麻烦。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by marcusxx** [comment]
这个是我做的，不是官方的某项服务，如果你觉得差，可以忽略，有啥意见可以在帖子里评论，不适合发在Issue里吧。
有请@CL关闭此Issue。

**Comment by kunpeng9** [comment]
> 这个是我做的，不是官方的某项服务，如果你觉得差，可以忽略，有啥意见可以在帖子里评论，不适合发在Issue里吧。
> 有请@cl关闭此Issue。

我也不清楚。。。。
