### ISSUE TITLE
增加全局第一页的栏数，减少当前软件第一页的栏数

### ISSUE THREAD

**Issue by loveless1999** [cuiliang/QuickPadCn#1152]
**需求描述**
软件全局第一页的栏数太少了，希望能多一些，因为这部分才是最高效的。次要的才会放到第二页。

相对可以减少当前软件第一页的栏数，这部分占用了全局的位置真的会很不方便。

**Comment by cuiliang** [comment]
那样会比较丑（腿太短了）。 参考下图：
![image](https://user-images.githubusercontent.com/1972649/89365889-2f360100-d708-11ea-9d20-d758b415bde2.png)
用滚轮翻页速度应该还是很快的。

**Comment by loveless1999** [comment]
第一页意味着第一眼处理信息，更高效。毕竟第二页要翻要找，降低效率。

本来我是想使用不同软件的捷径的，但是更多的想要翻我的文件，所以我现在如果要不同软件不同功能，我就每个不同软件都展示了我的文档。也就是我的文档×n界面。
![搜狗截图20200805105907](https://user-images.githubusercontent.com/69227451/89367358-61952d80-d70b-11ea-9859-c64dcb95f42c.png)
![image](https://user-images.githubusercontent.com/69227451/89367325-4cb89a00-d70b-11ea-9728-7c6708b88bae.png)

**Comment by cuiliang** [comment]
也可以利用一下任务栏的动作页，因为一般任务栏是一直可见的，可以随时点击触发，相对于另一块全局面板了。
