### ISSUE TITLE
希望可以设置徽标的文字大小

### ISSUE THREAD

**Issue by lusirnoman** [cuiliang/QuickPadCn#1157]
![235035_32293_image](https://user-images.githubusercontent.com/20045729/89437348-09494480-d77a-11ea-9a97-1ec003ca51f8.png)
![QQ截图20200806001534](https://user-images.githubusercontent.com/20045729/89437359-0b130800-d77a-11ea-918f-ee7e82a6f1e0.png)
![QQ截图20200806001555](https://user-images.githubusercontent.com/20045729/89437362-0b130800-d77a-11ea-99d2-52b345f984b6.png)
徽标文字的大小有些偏小了，很难第一眼就标识出内容
很多时候徽标的内容远比图标重要
希望能够设置徽标字体的大小

**Comment by cuiliang** [comment]
😂这里设计考虑是显示一个简单信息的，不太适合放多行文字。
