### ISSUE TITLE
不能自动删除轮盘里的动作吗？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1158]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
最近编辑了一下动作，把以往的动作页里的一些动作删除了。发现轮盘里面那个还在。
![image](https://user-images.githubusercontent.com/44609485/89543041-08281e00-d833-11ea-8d78-0835e43d1be2.png)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
轮盘上的动作需要手动删除的，两个不同的保存数据的地方，无法直接修改。
