### ISSUE TITLE
关于少数派 Tron计划

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1163]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
有一阵没访问少数派了，不知道啥时候突然多出了这个【好像可能早就有，但是我没注意到】。群主参加了吗？[少数派 Tron 计划](https://sspai.com/page/tron )。显示已有 100+ 开发者加入了 Tron 计划
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
Tron 计划从支持软件开发者起步，比如小工具白描，重工具 MarginNote 等。
Tron 计划扶持案例里面怎么没有quicker?我记得好像少数派好早之前就有quicker的文章、产品啊。刚刚仔细看了下，没有，之前记错了，quicker是在数码荔枝卖的。
![image](https://user-images.githubusercontent.com/44609485/89614897-f76dbb80-d8b7-11ea-8c9d-c3050479f476.png)
是因为不是ios生态下的吗？发现少数派苹果生态下的东西好多，应用、文章各种。。
![image](https://user-images.githubusercontent.com/44609485/89614967-1bc99800-d8b8-11ea-990e-2a1385514aaf.png)
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
Quicker最初就是在少数派启动的，少数派网站给了很多支持。
不过因为开发quicker没有时间写文章了，文笔又不好，所以很久没在上面发文章了😂。
后期有精力再说了。

**Comment by kunpeng9** [comment]
[少数派 - 高效工作，品质生活](https://sspai.com/apply/writing )老早就想申请个Matrix 写作权限的，无奈写作水平太差了，实在想不到有啥东西好让我通过那个审核。
