### ISSUE TITLE
quick导致ubuntu 20.04虚拟机鼠标右键后菜单马上消失

### ISSUE THREAD

**Issue by linszx** [cuiliang/QuickPadCn#1166]
**描述BUG**
quick导致ubuntu 20.04虚拟机鼠标右键后菜单马上消失，关闭后恢复正常

**环境信息:**
 - 操作系统版本：Ubunut 20.04虚拟机 Vmware
 - Quicker版本：1.8.5.0

**Comment by cuiliang** [comment]
加黑名单试下看看

**Comment by linszx** [comment]
> 加黑名单试下看看

1、添加黑名单没有效果
2、测试发现鼠标右键长按1s菜单就不会消失
3、关闭轮盘后右键菜单不会消失

推测是不是轮盘右键捕捉冲突了

**Comment by cuiliang** [comment]
vmware是由多个进程构成的，把这些进程都加黑名单试试，参考https://github.com/cuiliang/Quicker/issues/71。 
另外轮盘可以对单个应用单独设置是不是启用，也可以关闭试试。
我这边没有vmware的环境可以测试

**Comment by linszx** [comment]
已解决 谢谢

**Comment by SyberRabbit** [comment]
> 已解决 谢谢

怎么解决的，我也出现这问题了，乌班图22，给vm加黑名单没用，但关闭鼠标手势就没问题

**Comment by SyberRabbit** [comment]
> > 已解决 谢谢
> 
> 怎么解决的，我也出现这问题了，乌班图22，给vm加黑名单没用，但关闭鼠标手势就没问题

解决了，禁用\VMware\x64\vmware-vmx.exe
