### ISSUE TITLE
截图问题

### ISSUE THREAD

**Issue by LZW0123** [cuiliang/QuickPadCn#1167]
**描述BUG**
对bug的清晰简洁描述。
在截图的过程中，十字区域与放大的区域不重合
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
有几个屏幕？ 缩放比例都是多少呢？有办法截图或拍照看看啥效果不？

**Comment by LZW0123** [comment]
两个十字中心区域，内容不一样





---原始邮件---
发件人: "CuiLiang"<notifications@github.com&gt;
发送时间: 2020年8月9日(周日) 晚上8:11
收件人: "cuiliang/Quicker"<Quicker@noreply.github.com&gt;;
抄送: "LZW0123"<1589598459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [cuiliang/Quicker] 截图问题 (#1167)




 
有几个屏幕？ 缩放比例都是多少呢？有办法截图或拍照看看啥效果不？

**Comment by cuiliang** [comment]
有几个屏幕？ 缩放比例都是多少呢？

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions/Version?version=1.11.1.0    请测试下这个版本看看是否还有问题。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
