### ISSUE TITLE
变量合并？

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1170]
from @cesaryuan
在收藏的步骤片段添加到动作时，解决变量冲突：
假设步骤片段中有变量A，动作中有变量B，变量A和B的含义是一样的，如果我们想要将其合并为一个变量，只能把步骤片段里使用A的地方换成B，然后把变量A删掉。但是如果我们在粘贴上步骤之前，就通过一个全局替换将变量A的名称改成B，就省去上面说的麻烦的步骤了

要不就提供一个变量合并功能，因为有时候除去步骤收藏这一情况，也会出现前面创建了变量A，后来时间久了就忘了，又创建了一个变量B，但是这两个变量含义是一样的，以至于即使后来发现了也很难纠正了，因为有很多的地方引用了变量A和B。如果可以将变量B的名称改成A，然后修改之前提示【已经存在相同变量名，是否确认合并】，就是一个比较好的方案了@CL-北京

**Comment by kanglade** [comment]
还有一个问题，动作中有变量A，步骤片段中也有变量A，但是两个变量代表不同的含义，遇到这种情况又该怎么办呢？
