### ISSUE TITLE
考虑加入全局变量

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1176]
**需求描述**

为什么需要全局变量：
- 我的应用场景是这样的，有好几个变量是全局配置，这些全局配置需要能够记住状态（不然叫什么配置），还需要能够在任何子程序里访问。

想要达到这种效果有两种：
- 一是把每个需要的全局变量当做子程序的输入和输出参数，然后在主动作里将变量设置为作为状态使用。
- 二是频繁的状态存取。

两种方法的缺点：
- 一、当我子程序比较多的时候，如果没有在最初想好以后可能会用到的全局配置变量有哪些，那么当我后期想要添加一个全局配置变量的时候，就需要在所有使用子程序的地方修改输入输出参数，非常麻烦
- 二、频繁状态存取损耗性能，因为我需要在每个用到全局配置的地方设置写入和读取状态

**描述你想要的解决方案**

1. 弄一个类似于全局变量的东西，在任何子程序里可以访问
1. 提升状态存取性能（这个应该是计划中了）

**Comment by cesaryuan** [comment]
最好还是不要局限于不能分享，毕竟子程序还有一个大功能就是方便开发，可以分享出去只是另一个功能。就像我自己写程序使用函数也不是因为函数是从其他人那里复制过来可以直接使用，而是因为方便代码复用

**Comment by cuiliang** [comment]
note：
- 为子程序添加一个是否允许访问主程序变量的标记。
- 更改变量名时，需要一同更改这类子程序的变量；
- 检查变量是否使用时，需要一同检查子程序的变量；
- 子程序变量命名时，需要避免与主程序冲突；

**Comment by cuiliang** [comment]
Marcus ：
全局变量我是这么用的，用一个词典，专门存储变量，输入子程序再取值，随时可以加词典值

治钧：
大家看我的动作可能知道，关于全局变量和状态存取，我是这样设计的：
整个动作只有一个状态变量，起名叫「状态」，是一个词典，
所有需要存取状态的内容都放到这个词典中，
使用子程序时，只需将这个词典作为输入即可，
甚至不用将词典作为输出，因为这个词典估计是引用的方式来操作的
 
以上这种方式能应付90%的情况，只有少数有多实例的动作可能需要另外的方式处理

**Comment by cesaryuan** [comment]
@cuiliang 想了一下，全局变量这种方法有一个缺点，那就是不同的实例之间不能互相访问，所以还是提升状态存取的性能比较重要

**Comment by cuiliang** [comment]
整理issues
