### ISSUE TITLE
动作页根据触发次数进行自动排序

### ISSUE THREAD

**Issue by WangShanpeng** [cuiliang/QuickPadCn#1179]
**需求描述**
全局动作页面，动作会根据触发次数进行排序。

**描述你想要的解决方案**
将常用的动作自动移植最前面。

**Comment by cuiliang** [comment]
感谢建议。不过目前暂不考虑这种方式。
1. 有时候动作和位置是有逻辑关系的。
2. 靠近中间的位置距离鼠标更近。
3. 手动调整位置也比较方便，只要按住拖动就可以了。
