### ISSUE TITLE
建议提供可视化的动作开发界面

### ISSUE THREAD

**Issue by firestarman-james** [cuiliang/QuickPadCn#1180]
建议参考arcgis modelbuilder（[](https://blog.csdn.net/liyuanxiang1984/article/details/52774286)） 等，提供可视化的动作开发界面。

modelbuilder的部分优点：

1. 
可视化拖放设置运行流程，
2. 
大部分中间变量不用自己主动去定义、命名，
3. 
模型搭建好以后可以导出成python脚本然后通过python运行（运行前可进一步完善python脚本）。
4. 
在模型搭建界面可实时调试。

**Comment by firestarman-james** [comment]
上面的点edit没反应，只能在评论里重发。

建议参考arcgis modelbuilder（https://blog.csdn.net/liyuanxiang1984/article/details/52774286） 等，提供可视化的动作开发界面。

modelbuilder的部分优点：

1. 可视化拖放设置运行流程，
2. 大部分中间变量不用自己主动去定义、命名，
3. 模型搭建好以后可以导出成python脚本然后通过python运行（运行前可进一步完善python脚本）。
4. 在模型搭建界面可实时调试。

**Comment by firestarman-james** [comment]
上面的点edit没反应，只能在评论里重发。

建议参考arcgis modelbuilder（https://blog.csdn.net/liyuanxiang1984/article/details/52774286） 等，提供可视化的动作开发界面。

modelbuilder的部分优点：

1. 可视化拖放设置运行流程，
2. 大部分中间变量不用自己主动去定义、命名，
3. 模型搭建好以后可以导出成python脚本然后通过python运行（运行前可进一步完善python脚本）。
4. 在模型搭建界面可实时调试。

**Comment by cuiliang** [comment]
1. 实现这样的界面有点超出能力范围了。除非有可用的第三方组件。
2. quicker模块变量比较多，连线无法断定输出什么输入什么。
综上所述，暂不考虑了😂
