### ISSUE TITLE
弹出面板和鼠标轮盘可以单独开关

### ISSUE THREAD

**Issue by QinJiojio** [cuiliang/QuickPadCn#1182]
许多建模、图像处理软件使用鼠标中键拖拽或旋转视角，与quicker弹出面板冲突，需要经常手动开关，而轮盘也会同时关掉，在这类软件中轮盘使用频率也很高。
希望可以给轮盘和弹出面板设置独立的两个开关键。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/90215773-52129480-de2f-11ea-9b2a-a38479418ec0.png)
可以在这里控制一下。

**Comment by QinJiojio** [comment]
不是，我的意思是按F3关掉之后轮盘就不能用了，但是我有时候想禁用弹窗，只要轮盘，我希望能有两个单独的快捷键分别开关弹窗和轮盘，

**Comment by cuiliang** [comment]
面板窗口也可以修改一下触发方式避免冲突。 目前只能单独关轮盘，没法单独关面板。
