### ISSUE TITLE
关闭【获取剪切板文本】模块自定义格式的获取失败时的提示

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1186]
**需求描述**
![image](https://user-images.githubusercontent.com/35998162/90324455-b2c1de80-dfa1-11ea-8781-f9a623043603.png)

**Comment by cuiliang** [comment]
测试没有这个问题。 版本1.10.2  
可能在动作里多个地方使用了这个模块，其中另外的一个没有取消“失败后中止动作”的选项。
