### ISSUE TITLE
安装时出现：无法访问你试图使用的功能所在的网络位置

### ISSUE THREAD

**Issue by dingtom** [cuiliang/QuickPadCn#1187]
能否公开更早期版本下载链接
![image](https://user-images.githubusercontent.com/35419759/90324997-8cec0800-dfa8-11ea-98eb-1508b39ef247.png)

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Help/Doc/install#EL8DU

**Comment by dingtom** [comment]
> https://getquicker.net/KC/Help/Doc/install#EL8DU

微软下载工具无法下载，百度云没有20年之前的版本😂

**Comment by cuiliang** [comment]
哦，不知道微软的工具为啥404了。 使用第三方的卸载工具卸载一下试试了。 
旧版本太多了，不定期清除掉了。

**Comment by dingtom** [comment]
> 哦，不知道微软的工具为啥404了。 使用第三方的卸载工具卸载一下试试了。
> 旧版本太多了，不定期清除掉了。

我试试，谢谢啦！
