### ISSUE TITLE
搜索框功能优化

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1189]
- [ ] 历史记录重启不清空
![image](https://user-images.githubusercontent.com/35998162/90348675-a0ab7300-e069-11ea-8229-ba04693da575.png)

- [ ] 支持鼠标拖动移动位置
- [ ] 支持鼠标按住右侧调整宽度
- [ ] 动作备注也支持拼音搜索
- [ ] 显示在鼠标所在的屏幕上

另外，选择动作id的窗口自动获得焦点。

**Comment by cuiliang** [comment]
选项：最近使用的动作只显示从搜索框启动的。

**Comment by cuiliang** [comment]
关闭历史issue中，感谢！
