### ISSUE TITLE
文本窗口相关需求整理

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1192]
- [x] 调用子程序，获取和更新选择的行（类似于注释/取消注释的操作）
![获取当前行](https://user-images.githubusercontent.com/1972649/91124590-1b136d00-e6d2-11ea-8770-1f5b04fb9f8c.gif)

- [ ] 开放一些编辑器本身的接口给命令调用。
- [x] 考虑是否通过选项控制：不选择时是否复制整行。

**Comment by kanglade** [comment]
- [x] 如何实现：下次开启时，使用上次的窗口大小和位置

**Comment by cuiliang** [comment]
1.10.5 设置唯一标识的，在同一个动作运行期间自动使用上一次的显示位置。
