### ISSUE TITLE
步骤编辑相关需求建议

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1194]
- 改善自动生成的注释
![image](https://user-images.githubusercontent.com/1972649/90406560-ed2d9780-e0d7-11ea-89d4-37870c897704.png)
- 输入框右边的选择菜单根据输入框的内容只显示一部分适用的。
- 对参数进行验证。
-

**Comment by marcusxx** [comment]
类似的需要在外面显示参数的步骤还有：
-获取时间
-计算时间
-列表操作

另外希望能把那些没显示输入输出信息的步骤也改成能显示，现在做得很好的是“文本处理”，输入输出和处理类型都能看到
![image](https://user-images.githubusercontent.com/48142413/90857396-a4ffc500-e3b6-11ea-865e-3a6aa8f7bf9f.png)

其他步骤也需要显示的比如：
-赋值模块的输入内容
-计算模块使用的表达式

**Comment by cesaryuan** [comment]
![image](https://user-images.githubusercontent.com/35998162/106241834-a70d6000-6241-11eb-8ed7-147fd6e5387c.png)
