### ISSUE TITLE
发送文本设置字符间隔

### ISSUE THREAD

**Issue by 1013801464** [cuiliang/QuickPadCn#1196]
**描述BUG**
我写了一个发送文本的动作, 如下
![image](https://user-images.githubusercontent.com/20624289/90477403-eba6b280-e15d-11ea-8c65-283442315947.png)
但是执行结果却会输出错的字符串:
![image](https://user-images.githubusercontent.com/20624289/90477497-14c74300-e15e-11ea-8a6a-6f6e66093d51.png)

**重现步骤**
1. 我重复执行了脚本6次, 结果如上图所示

**环境信息:**
 - 操作系统版本：Win10 1909 64位
 - Quicker版本：1.9.22.0和1.9.18.0均有此问题

**Comment by 1013801464** [comment]
(不用提醒我泄露密码, 图中的密码是假的)

**Comment by cuiliang** [comment]
这种一般是输入法影响的，可以换到别的输入法试试。

**Comment by 1013801464** [comment]
> 这种一般是输入法影响的，可以换到别的输入法试试。

我关掉输入法果然没事了。搜狗拼音和搜狗五笔都有问题。

**Comment by 1013801464** [comment]
> 这种一般是输入法影响的，可以换到别的输入法试试。

但是旧版本的Quicker没有出现过问题。

**Comment by cuiliang** [comment]
搜狗原来就有这个问题。但是不清楚什么情况下会触发。可能有什么不确定的bug。

**Comment by cesaryuan** [comment]
> > 这种一般是输入法影响的，可以换到别的输入法试试。
> 
> 我关掉输入法果然没事了。搜狗拼音和搜狗五笔都有问题。

用复制粘贴模式可以吗

**Comment by 1013801464** [comment]
有的控件窗口不让粘贴

**Comment by 1013801464** [comment]
> 搜狗原来就有这个问题。但是不清楚什么情况下会触发。可能有什么不确定的bug。

我现在只能把字符串拆了, 逐个字符输入, 这样可以指定输入字符的间隔时间, 间隔100毫秒是不会出现异常的. 

![image](https://user-images.githubusercontent.com/20624289/90479318-10e8f000-e161-11ea-80e9-c5ea29d3c652.png)

要是"发送文本"功能也能指定输入字符的时间间隔就好了.

**Comment by cuiliang** [comment]
> 要是"发送文本"功能也能指定输入字符的时间间隔就好了.

等研究一下能不能实现。

**Comment by cuiliang** [comment]
1.10.6 增加延迟参数。
