### ISSUE TITLE
表单需求整理

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1200]
？增加全局菜单
![image](https://user-images.githubusercontent.com/1972649/90712313-53cbd480-e2d5-11ea-80b3-f367822e8f3c.png)
在表单这里设置用户选择的全局菜单咋样，可以快速加载不同的配置组

---
？根据一个字段的值更新其它字段的可见性

**Comment by marcusxx** [comment]
这个地方太隐蔽了，没有详细了解过的话，估计很少人会使用
