### ISSUE TITLE
能否增加执行数据库动作

### ISSUE THREAD

**Issue by renovrtio** [cuiliang/QuickPadCn#1202]
增加执行数据库语句执行返回结果

**Comment by cuiliang** [comment]
目前不太可行，没有合适的方式表示结果集。 
可以考虑使用c#代码模块来实现相关需求试试。

**Comment by renovrtio** [comment]
谢谢你的回复，我现在使用cmd脚本写的，返回的结果用列表处理的，有点不是特别方便。可以看下我做的动作：https://getquicker.net/sharedaction?code=6c994f3a-3786-42e2-93ff-08d844cb7f48

**Comment by cuiliang** [comment]
归档
