### ISSUE TITLE
提示框未设置焦点

### ISSUE THREAD

**Issue by leeyaunlong** [cuiliang/QuickPadCn#1203]
提示框未设置焦点
代码:
1.前一步是 用户选择, 并启用筛选过滤后
2.当前步是 提示框(Yes/No).

**重现步骤**
1.用户选择中,选中一个选项, (选择框自动关闭).
2.弹出了  提示框(Yes/No), 但这时焦点跳回了原来触发的窗体去了, 但是提示框还是显示最顶部.
期待是: 焦点在提示框上.

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.9.18

**Comment by cuiliang** [comment]
方便截个图么？ 不是很明白哪个位置。

**Comment by leeyaunlong** [comment]
> 方便截个图么？ 不是很明白哪个位置。

如下截图
或者使用我分享的动作 https://getquicker.net/sharedaction?code=5000ca24-ad21-4abe-b966-08d8482d85a9(在资源管理器中选中一个文件)


![snipaste20200825_151548](https://user-images.githubusercontent.com/19405648/91144698-fc6ba100-e6e6-11ea-8dc4-07bdc11f0316.png)

![snipaste20200825_151959](https://user-images.githubusercontent.com/19405648/91144731-07263600-e6e7-11ea-9c49-e18566ab8f25.png)

![snipaste20200825_152303](https://user-images.githubusercontent.com/19405648/91144755-0ee5da80-e6e7-11ea-82a9-888039cf15b4.png)

**Comment by cuiliang** [comment]
感谢反馈，我处理一下。

**Comment by cuiliang** [comment]
1.10.1 已经处理
