### ISSUE TITLE
轮盘和弹出菜单建议不共享软件黑名单

### ISSUE THREAD

**Issue by yabhit** [cuiliang/QuickPadCn#1205]
我用中键呼出弹出面板，因为在浏览器里中键有定义导致冲突，所以我关闭了浏览器里的面板呼出
（实际上我仍然有弹出的需求，只是因为呼出弹出的快捷键都不太合用，所以干脆禁掉了）

然后现在推出了轮盘功能，按下X1键滑动的方式，在浏览器里没有冲突，所以我可以打开轮盘来使用

但是同时因为弹出面板的快捷键冲突问题，我希望关闭弹出面板快捷键，于是设置了黑名单的情况下无法用轮盘
不设置黑名单，又会产生弹出面板的快捷键冲突

所以希望轮盘和弹出面板的黑名单能够分开

**Comment by cesaryuan** [comment]
还是用X1触发面板舒服

**Comment by yabhit** [comment]
> 还是用X1触发面板舒服

在文件夹里操作，X1是有定义的啊

**Comment by cesaryuan** [comment]
> > 还是用X1触发面板舒服
> 
> 在文件夹里操作，X1是有定义的啊

什么定义？（我非官方，只是个人建议😂）

**Comment by yabhit** [comment]
> > > 还是用X1触发面板舒服
> > 
> > 
> > 在文件夹里操作，X1是有定义的啊
> 
> 什么定义？（我非官方，只是个人建议😂）

返回上一层文件啊
说来说去，貌似还是快捷键和软件冲突的问题啊

**Comment by cuiliang** [comment]
区分不同的黑名单实现起来太复杂。请尽量使用相同的没有冲突的触发方式了。
