### ISSUE TITLE
快速通道 1.9.22安装不上。

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1207]
**描述BUG**
对bug的清晰简洁描述。
![image](https://user-images.githubusercontent.com/44609485/90999536-76256100-e5f9-11ea-9301-9ae7aed9af17.png)
试了好些回了，都不行，安装不了更新。刚刚卸载的时候居然卸载不了，也提示说有问题，然后我强制删除了软件，再安装结果还是出现这个提示，到底啥问题。
![image](https://user-images.githubusercontent.com/44609485/90999571-96edb680-e5f9-11ea-82e7-dc67e4ee39b6.png)
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/44609485/90999714-ec29c800-e5f9-11ea-81f0-f96b5d97401c.png)
把程度放到桌面之后点击安装还是不行。
![image](https://user-images.githubusercontent.com/44609485/90999751-095e9680-e5fa-11ea-86d7-6d53ad76c35f.png)
好麻烦，一直安装不上。
**环境信息:**
 - 操作系统版本：win10  1903
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。
之前似乎看到有人也在github报告过类似的问题，是我记错了吗？

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions/Version?version=1.9.17.0  右边有下载链接，下载后，截图里的选择框选择到这个文件再继续卸载。

**Comment by cuiliang** [comment]
尽量不要用清理工具清理windows。

**Comment by kunpeng9** [comment]
![image](https://user-images.githubusercontent.com/44609485/91013532-68340800-e61a-11ea-95be-91c06125fece.png)。出现过这个错误。
安装成功了之后，发现没有快捷方式出现
刚刚又尝试了几次，没问题了。可以安装，问题已解决。先安装的17然后再安装的22

**Comment by cuiliang** [comment]
本身没有桌面快捷方式的，开始菜单里有。
