### ISSUE TITLE
可以支持批量编辑动作页名称吗？添加到轮盘里面的动作页面上的动作是否可以凸显出来呢

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1209]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
想将GTD任务管理引入quicker，但是编辑的时候又很不方便【动作稍微有点多了，断舍离，删掉的话又舍不得。】。
![image](https://user-images.githubusercontent.com/44609485/91186775-01017b00-e722-11ea-8ce8-989d8bb04543.png)
---
![image](https://user-images.githubusercontent.com/44609485/91186833-14144b00-e722-11ea-9f98-7b42372cf43d.png)
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
我把以下的内容输入之后动作页名称就都自动命名好，不需要一个个点击到里面进行编辑【有了以下体系的话就可以体验更多的动作，有点头疼，动作多了的话，不知道怎么放置动作好，假如只有页面的话还好，主要就盯着前4页就好了，但是多了轮盘功能，我得考虑更多的东西，不知道怎么安排好】。
写到这里突然想到一个，添加到轮盘里面的动作页面上的动作是否可以凸显出来呢？我记得有更新的动作右下角是会有颜色显示的把，类似于这个。
01=每日收集箱
02=下一步行动
03=等待事项
04=执行项目
05=将来可能
06=归档资料
07=历史=每日收集箱
07=历史=资料
08=共享繁华
---
有的时候我想进行断舍离，减少动作的安装数量，我发现应用程序设置对应的页面上的动作，不能直接发送到其他的应用程序设置动作页的轮盘，必须复制一个，例如把网易所属的一个动作页的动作移动到anki的动作轮盘上就不行。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by kunpeng9** [comment]
quick面板是否可以支持归档关闭功能？我用的时候就想到这个问题了。搞忘记了，没有提交这个。类似于滴答清单，可以关闭清单。不然的话面板太多，面板转一圈的话，时间稍微长了一点。
![image](https://user-images.githubusercontent.com/44609485/91252237-c59d9580-e78f-11ea-9f18-caf66e31e93c.png)

**Comment by cuiliang** [comment]
Quicker不太适合这个场景。主要还是给常用操作建立捷径使用比较好的。

**Comment by kunpeng9** [comment]
> Quicker不太适合这个场景。主要还是给常用操作建立捷径使用比较好的。

那你的想法具体一点说，是什么？上面我提到的想法有可能实现吗？能实现还是不能实现或者部分实现？
