### ISSUE TITLE
笔电使用触控板双指滑动时，动作页无法翻页

### ISSUE THREAD

**Issue by ruandongcheng** [cuiliang/QuickPadCn#1213]
**描述BUG**
当使用鼠标操作时，动作页可以通过鼠标滚轮翻页，但是用笔电的触控手势，双指滚动无法使动作页翻页，只能点击动作页下方的小点点切换，不太方便。

**重现步骤**
1.使用触控板的双指滑动手势在动作页上滑动
2.无法滑动

**相关截图**
图片无法上传

**环境信息:**
 - 操作系统版本：WIN10家庭中文版 1909     版本号：18363.1016
 - Quicker版本：1.9.18.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
没有鼠标的时候，可以使用键盘激活然后使用方向键翻页。 触控方式很多时候检测不到鼠标消息。

**Comment by ruandongcheng** [comment]
好的谢谢开发大大回复
