### ISSUE TITLE
【想法】ctrl+点击锁图标：选择锁定的应用面板

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1215]
![image](https://user-images.githubusercontent.com/50692082/91511604-a24f2380-e912-11ea-831b-bf5fc4af0ab9.png)

有时候想临时锁定一个面板，通常的做法是先打开应用，等加载完成后激活且锁定面板，但是有些应用开启等待时间很长而且占用内存大，浪费电脑性能。我想到的措施就是通过ctrl+点击锁图标激活应用菜单，类似上图所示，不知是否可行呢？

**Comment by kanglade** [comment]
确实有这个需求，有时我需要锁定一个「虚拟应用」面板，真是没有什么好办法，有这么个想法，不知好不好：

在「动作页管理」，面板菜单中增加「锁定到主界面」

![image](https://user-images.githubusercontent.com/24608004/91517743-198bb400-e921-11ea-9f6f-88448b34834c.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/91578136-5769f600-e97c-11ea-8e8b-1514fa0e4b32.png)

**Comment by cuiliang** [comment]
1.10.2
