### ISSUE TITLE
模拟按键Escape同截图在同一个动作中不停弹窗

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#1216]
使用悬浮按钮时不停触发弹窗
示例与截图在
https://getquicker.net/sharedaction?code=5da64163-7f4d-4aa5-66ca-08d84b01d3db

**Comment by cuiliang** [comment]
测试没有出现这个现象。
正在截图的时候再次使用截图功能会出现这个现象。检查下看看是不是有其它截图操作在进行

**Comment by Hefang2000** [comment]
没有其它截图-------- 原始邮件 --------发件人： CuiLiang <notifications@github.com>日期： 2020年8月28日周五 13:37收件人： cuiliang/Quicker <Quicker@noreply.github.com>抄送： Hefang2000 <K20163355@126.com>, Author <author@noreply.github.com>主    题： Re: [cuiliang/Quicker] 模拟按键Escape同截图在同一个动作中不停弹窗 (#1216)

测试没有出现这个现象。

正在截图的时候再次使用截图功能会出现这个现象。检查下看看是不是有其它截图操作在进行

**Comment by cuiliang** [comment]
因为动作里第一步使用了鼠标点击，这时候鼠标还在按钮上，它又点击了动作，然后动作里又点击，又触发了动作。。。
![image](https://user-images.githubusercontent.com/1972649/91549072-f4b33300-e958-11ea-8d47-53214eb8dd36.png)

**Comment by Hefang2000** [comment]
不使用悬浮按钮就没有事，一旦使用悬浮按钮就废了，是不是和焦点有关



发送自 Windows 10 版邮件应用

发件人: CuiLiang
发送时间: 2020年8月28日 18:05
收件人: cuiliang/Quicker
抄送: Hefang2000; Author
主题: Re: [cuiliang/Quicker] 模拟按键Escape同截图在同一个动作中不停弹窗 (#1216)

因为动作里第一步使用了鼠标点击，这时候鼠标还在按钮上，它又点击了动作，然后动作里又点击，又触发了动作。。。

**Comment by cuiliang** [comment]
面板会自动关掉，所以你动作里的点击不会点击到面板的按钮上。 悬浮是按钮一直在那里，动作里的点击会点击到悬浮按钮。

**Comment by Hefang2000** [comment]
明白了是导致了悬浮按按钮交替式触发常中对吗，为何会持续触发，并没有设计无穷循环，纳闷

发送自 Windows 10 版邮件应用

发件人: CuiLiang
发送时间: 2020年8月28日 18:05
主题: Re: [cuiliang/Quicker] 模拟按键Escape同截图在同一个动作中不停弹窗 (#1216)

因为动作里第一步使用了鼠标点击，这时候鼠标还在按钮上，它又点击了动作，然后动作里又点击，又触发了动作。。。

**Comment by Hefang2000** [comment]
懂了懂了，多谢指教，就和裂变似的，点击就是是那个多出来的中子，还好这次只是个直链，并没有产生信号放大效应（庆幸）

发送自 Windows 10 版邮件应用

发件人: CuiLiang
发送时间: 2020年8月28日 18:05
主题: Re: [cuiliang/Quicker] 模拟按键Escape同截图在同一个动作中不停弹窗 (#1216)

因为动作里第一步使用了鼠标点击，这时候鼠标还在按钮上，它又点击了动作，然后动作里又点击，又触发了动作。。。

**Comment by cuiliang** [comment]
😁
