### ISSUE TITLE
旧版本无法卸载，用了msrt还是不行

### ISSUE THREAD

**Issue by JasonXIIA** [cuiliang/QuickPadCn#1218]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.我自己删了注册表 才发现怎么处理旧版本的方法，下了微软的软件
2.全盘扫描完成还是不行 提示我相同问题

**相关截图**

![image](https://user-images.githubusercontent.com/68836464/91626534-7b602280-e9e2-11ea-9dc8-262d7dd8f8c0.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：quicker_install_20190825191801

**附加信息**
其实找到版本感觉也能解决，但是你pan里面的版本跟上面版本号不一样啊。

**Comment by cuiliang** [comment]
看看软件里的版本号，找到对应版本号的安装包。 或者用第三方的卸载工具卸载一下试试。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
