### ISSUE TITLE
鼠标输入，定位不准。

### ISSUE THREAD

**Issue by caosimin75** [cuiliang/QuickPadCn#1219]
**描述BUG**
多屏显示状态下，鼠标输入，移动到（x，y一同指定）定位不准。

**重现步骤**
1.多屏显示状态
2.鼠标输入
3.移动到（x，y一同指定）
4.窗口坐标（拖动选择）
5.输入后保存-执行

**相关截图**

**环境信息: 
 - 操作系统版本：10.0.19041.0
 - Quicker版本：1009018

**附加信息**
实际执行后，只能定位到主屏的边缘，希望修复。同时希望增加，定位坐标值与移动后操作之间增加一个延时参数。

**Comment by cuiliang** [comment]
不太明白，怎么不准？ 应该到多少实际到多少？ 延时可以自行添加等待时间模块实现。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by caosimin75** [comment]
> 先关了，如果还有问题，请再reopen

就是超出主屏部分，鼠标的走位不准。

**Comment by cuiliang** [comment]
鼠标指针无法移动到超出屏幕的位置的。

2020-08-30 17:07 GMT+08:00, caosimin75 <notifications@github.com>:
