### ISSUE TITLE
关于markdown动作的更新

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1228]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
![image](https://user-images.githubusercontent.com/44609485/91920960-ee2c0f00-ecfc-11ea-9283-1f7304cdf5f3.png)
希望群主可以更新一下那个动作，分享出去好久没更新了。
https://getquicker.net/sharedaction?code=1db6af71-552c-45ad-90a9-08d7cf2c9c84 我的这个动作经常用，会调用你的那个动作，[生成MarkDown链接 - 已分享的动作 - Quicker](https://getquicker.net/sharedaction?code=bf4e796f-e1a5-41ba-1925-08d7b02d7fd4 )
但是有的网页可以，有的网页就不行【啥链接也没有，出现各种报错】。
![image](https://user-images.githubusercontent.com/44609485/91921069-35b29b00-ecfd-11ea-8e62-ba56e9323064.png)
![image](https://user-images.githubusercontent.com/44609485/91921206-832f0800-ecfd-11ea-9f05-b299f1e182fd.png)
能不能把无力更新的动作，更新权转移给别人或者类似github的拉请求，通过请求，合并分支这种操作【可能没有描述清楚，虽然注册github好几年了，但是使用上还是稀烂，虽然有教程但是没有咋实践】。
然后不用动作里面写注释，源动作来自哪里哪里，直接在网页就像github这样自动显示出来。
https://github.com/DIYgod/RSSHub/issues/5460
以前我的脑子里就有过这个念头，但是没有提交issues，搞忘记inbox，markdown动作使用频率很高。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
[搜索：markdown - Quicker](https://getquicker.net/Search?keyword=markdown )虽然搜索出来的动作有一堆但实际上我并不知道哪个比较好。
不同网页的提取出来的链接不一样，我尽量把出现的各种情况记录完全=
腾讯文档的是这样的，有多余的空格我要删除=
[
        腾讯文档
    ](https://docs.qq.com/doc/DQ2ViRVVod3ZFZkpQ )
幕布网页=
[](https://mubu.com/doc5f00H6X3tTH )
![image](https://user-images.githubusercontent.com/44609485/91921641-8ecefe80-ecfe-11ea-9d11-eee662851eab.png)[]里面没有内容。
![image](https://user-images.githubusercontent.com/44609485/91921689-ac9c6380-ecfe-11ea-988f-bf07fd883f99.png)
啥都没有。
![image](https://user-images.githubusercontent.com/44609485/91921756-d9e91180-ecfe-11ea-9dac-684df27ca016.png)
github编辑的时候和预览显示的是不一样的，注意。
京东=
![image](https://user-images.githubusercontent.com/44609485/91921824-09981980-ecff-11ea-9e91-7a93511afc59.png)
我想录入那个商品名称+价格+链接添加到待买。
![image](https://user-images.githubusercontent.com/44609485/91921930-46641080-ecff-11ea-9594-668ee6f4f9c7.png)
淘宝=不知道为啥就一直很顺利。
![image](https://user-images.githubusercontent.com/44609485/91921974-5ed42b00-ecff-11ea-8eb7-8012334fc557.png)
有品=
![image](https://user-images.githubusercontent.com/44609485/91922000-74495500-ecff-11ea-97c1-b0e492d4ffe0.png)
[小米有品-坚持做感动人心，价格厚道的好产品](https://www.xiaomiyoupin.com/detail?gid=116816&spmref=YouPinPC.$SearchFilter$1.search_list.4.56368423 )
![image](https://user-images.githubusercontent.com/44609485/91922036-875c2500-ecff-11ea-9a99-0d850c639e73.png)描述不对。
知乎书店=
![image](https://user-images.githubusercontent.com/44609485/91922126-bbcfe100-ecff-11ea-8c45-ce037b099f89.png)
知乎=[下一个天坑会是哪个专业? - 知乎](https://www.zhihu.com/question/402480681 )
生成的是问题的链接![image](https://user-images.githubusercontent.com/44609485/91922227-06515d80-ed00-11ea-9b60-1a23a8b02ea0.png)获取的不是我看的那个文章回答的链接。
![image](https://user-images.githubusercontent.com/44609485/91922265-1ec17800-ed00-11ea-8c40-6479cf33e4b2.png)
下一个天坑会是哪个专业? - 我真的是伙鸡的回答 - 知乎
https://www.zhihu.com/question/402480681/answer/1302710617，怎么把这个快速方便的转换成markdwon。
印象笔记插件剪藏书签还没有我这个滴答清单的动作的使用频率高。简阅插件虽然安装了很久，但是使用上还是稀烂，体验不是很好，仍然有问题，过阵子去反馈。剪藏插件安装不少，用的都不好。过阵子整理一下inbox思维导图，把插件的内容加上，之前没想起来。
或许可以参考一下这个，这个
https://chrome.google.com/webstore/detail/mhfbofiokmppgdliakminbgdgcmbhbac
![image](https://user-images.githubusercontent.com/44609485/91922870-9f34a880-ed01-11ea-8406-d5d4d42605f5.png)
突然想起来滴答清单的插件，之前疏忽了。
![image](https://user-images.githubusercontent.com/44609485/91922959-ce4b1a00-ed01-11ea-8fab-ea2866e2d1c3.png)【使用体验也不好，有问题，反馈过，官方说暂时一段时间不更新插件。】
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
呃呃，看不太明白啊

**Comment by kunpeng9** [comment]
> 呃呃，看不太明白啊
![image](https://user-images.githubusercontent.com/44609485/94145793-a9336c80-fea5-11ea-83d4-ddbe8154ad6a.png)
还是buxing不行，那个markdown动作有时候经常失效。就是这个动作[生成MarkDown链接 - 已分享的动作 - Quicker](https://getquicker.net/sharedaction?code=bf4e796f-e1a5-41ba-1925-08d7b02d7fd4 ) @cuiliang

**Comment by kunpeng9** [comment]
没事了，已经找到了替代的动作了。[链接.md - 已分享的动作 - Quicker](https://getquicker.net/Sharedaction?code=c183f484-4774-4510-317a-08d79a301df0) @cuiliang
