### ISSUE TITLE
在win7系统下经常出现焦点被锁定在当前窗口无法操作的问题

### ISSUE THREAD

**Issue by sakurairsora** [cuiliang/QuickPadCn#1235]
**描述BUG**
很难描述，我也不清楚这个bug具体是什么回事，只知道它会使得除了当前窗口可以操作以外，其他窗口一律无法选取跟操作。
比如说，我现在开了一个文件夹，然后出现这个bug，那么我可以在这个文件夹里左键右键打开文件刷新等，但是，要是我打开新文件，那么这个新窗口则无法进行操作。就是怎么点鼠标，哪怕按键盘ctrl+w，它都不会有反应，反而会出现一种失去焦点一般的样子。可以呼出任务管理器，但无法操作。
可以使用alt+tab切换，但并没意义，除非切换到当时呼出quicker的窗口，不然其他窗口完全无法操作。
quicker可以呼出，但上面一切按钮皆不可以按。
关闭聚焦的窗口以后，这个焦点会切换到当前打开的窗口。
当时打开了任务管理器，于是可以操作任务管理器。关掉quicker后，依然处于这种奇怪的状况。
关掉任务管理器后，因为没有呼出的活动窗口，所以焦点变成了任务栏。可以做任务栏的一切动作，回到桌面等（此前不能回到），也能控制开始菜单。
因为没办法复原所以只能注销。
注销后再次呼出quicker，依然有概率如此。

除此以外，还有分为连当前窗口都无法控制，最后只得强制重启的情况；又有按右键后恢复正常的情况。

除了以上恶性bug外，还有按右键而非中键也会弹出窗口的问题。

**重现步骤**
1.在某种情况下按中键。可能是拖移中按，可能是系统很卡的时候按，目前仍不明确
2.发生如上bug

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win7 64位
 - Quicker版本：1.9.18，但1.7还是1.6开始就有这种情况

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感觉有点像鼠标消息不匹配了（一直按下没有变成抬起），但是一般这种情况打开任务管理器会正常。
弹出方式是可以设置的，也有可能设置了长按右键之类的。
如果有360，卸载360测试看看有没有改善。 如果有手势软件，关掉手势软件看看有没有改善。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
