### ISSUE TITLE
ctrl加滚轮调节亮度

### ISSUE THREAD

**Issue by LH123sq** [cuiliang/QuickPadCn#1237]

**Comment by cuiliang** [comment]
此功能需硬件支持。 提示这个信息表示硬件不支持。 一般只有台式机显示器支持这个功能。

**Comment by LH123sq** [comment]
> 利用设置自带的ctrl加滚轮调节屏幕亮度失败，显示如下信息
> 调整屏幕亮度失败，可能是硬件不支持DDCC接口。详细信息：操作失败，原因是DDCC消息的命令字段中的值无效
