### ISSUE TITLE
考虑：专业版功能改为限量而非禁用

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1239]
限量可以满足基本使用同时可以了解软件功能。
- 扩展鼠标操作5条；
- 悬浮动作按钮：1个；
- 轮盘菜单：锁定扩展圈。免费版可用2圈。
- 扩展热键：10
- 文本指令： 10
- 仪表盘视图：
- 动作快捷键：3
- 鼠标手势：10

**Comment by kanglade** [comment]
这主意感觉不错，关键在于量的把握，可以满足基本需求，但如果有更频繁的高级需求则需要购买专业版。

**Comment by cesaryuan** [comment]
数量有点多了，我作为专业版10个文本指令和扩展热键感觉都够了，建议全都改成3个

**Comment by PotoTan** [comment]
反对。
请不要将软件的付费与免费搞得复杂化。功能直接部分就好，减少维护成本。

如果按照你的思路，以后每次新功能迭代都要纠结应该怎么定义免费版的可使用次数，浪费时间精力在不重要的事情上。

直接禁用功能就好了。软件本身的年付不贵呀，如果费用高昂得让每个人都直嚷贵，那么可以考虑你这个方案。可现在的问题是年付50元上下，但是高频强依赖的软件特性完全值得。在这种情况下，如何尽量转化免费用户为付费用户才是关键。如果 CL 讲究点，做良心的独立软件开发商，通过软件的边际成本低廉与用户的持续增长摊薄费用，还可能降低价格。这种情况下才是用户和开发者的共赢。因此，CL 作为开发者不应该在免费版上继续浪费时间，而是专注如何持续开发 Quicker 和有效降低成本。通过直接禁用高级功能来转化用户。
