### ISSUE TITLE
有关于同步的问题

### ISSUE THREAD

**Issue by LongMan98** [cuiliang/QuickPadCn#1242]
**需求描述**
希望同步能够不完全同步

**描述你想要的解决方案**
例如同步启动某个软件，但是在不同电脑上软件的位置可能不同从而导致同步出问题

**描述您考虑过的替代方案**
添加选项，或者自动判断

**Comment by cuiliang** [comment]
请参考这里：
https://getquicker.net/KC/Help/Doc/data-sync#ThGPb
