### ISSUE TITLE
同步的设计目前有问题

### ISSUE THREAD

**Issue by orangeseasun** [cuiliang/QuickPadCn#1243]
**需求描述**
免费账户可以同步两个设备，共享设置好的动作页，但是如果在动作页里设置了app启动项，由于两个设备（pc）的app路径不一致，导致有一个设备同步以后，另一个设备由于app路径不一致用不了，还得重新设置。

**描述你想要的解决方案**
能不能只同步app启动项的布局设置，而不同步路径，由用户自己指定路径，然后路径保存在本地。

**描述您考虑过的替代方案**
能不能只同步app启动项的布局设置，而不同步路径，由用户自己指定路径，然后路径保存在本地。

 **其他上下文**
没有截图。

**Comment by cuiliang** [comment]
请参考这里：
https://getquicker.net/KC/Help/Doc/data-sync#ThGPb

**Comment by cuiliang** [comment]
免费版的话，可以使用备用路径参数，或者使用组合动作在里面判断主机名。
