### ISSUE TITLE
隐藏右下角任务栏图标

### ISSUE THREAD

**Issue by nocease** [cuiliang/QuickPadCn#1245]
希望设置里添加隐藏右下角任务栏图标的选项

**Comment by cuiliang** [comment]
建议拖放到win10的隐藏区。 托盘右键有一些功能菜单的，不适合关闭掉。
![image](https://user-images.githubusercontent.com/1972649/93354050-2d1aa280-f86f-11ea-85f1-843e6eba9c2d.png)
