### ISSUE TITLE
“为某程序添加面板”的字样有碍审美和使用，期待被看到

### ISSUE THREAD

**Issue by QingW-7023** [cuiliang/QuickPadCn#1246]
**需求描述**
“为某程序添加面板”字样的颜色不能跟随外观设置的文字颜色主题，例如：我将面板的透明度拉的很低，颜色也很淡，故此将字色设置为深黑，但上述的字样仍然保持着灰色，于是成了整个最不和谐的地方。为此，我还为某些程序设置了新的界面，这样的不会显示那几个字了，但却要随时保持和“通用”的面板保持一致，增加了工作量。

非常期待这个小tip的字色能跟随设置主题走呢，感谢提供优秀的软件的贵团队。

**Comment by QingW-7023** [comment]
请求考虑为“动作页管理与应用程序设置”里的“编辑应用程序信息”添加功能设置。
目前可作操作的是路径、程序名称、关联其他程序，希望能添加一项图标的管理设置，选择自定义的图标，或者不要图标。
感谢，以上。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/95181963-8f275180-07f6-11eb-9dc5-d745ffb07dde.png)
取消这个。
图标后期再考虑了，目前是根据路径去找exe后提取的。
