### ISSUE TITLE
分享子程序时自动嵌套内部使用的其他子程序

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1247]

**Comment by cuiliang** [comment]
实际是嵌入了的. 但是将这个子程序安装到本地之后, 因为本地的动作不支持子程序内的子程序,所以会提示找不到.

可能的方案
支持子程序内的子程序。界面开发比较困难。
区分动作内的其他子程序和子程序内的子程序，这样虽然不能编辑，但是可以正常运行动作。
下载时，自动将子程序内的子程序转换为动作内子程序。 可能会有名称冲突，而且可能会比较多。

**Comment by kanglade** [comment]
- 目前我个人感觉子程序的定义，就现在这样，在子程序列表中统一管理就很好（不分层级），一来方便管理（子程序中管理其下子程序容易造成子程序实现的遗漏，这应该与我的动作开发习惯有关，后面说明），二来不增加复杂度。
- 我不推荐分享的子程序中包含其他子程序，如果分享的子程序含有其他子程序，动作开发者应该将其分解成步骤组。我子程序中包含其他子程序的情况非常多，但都仅针对单个动作，都不适合分享。
- 如果一定要分享嵌套子程序的子程序的话，将嵌套的子程序自动「转换成步骤组」或许也是个可以考虑的方法。
***
附我的开发习惯：
①想好动作的整个思路以及数据结构；
②设计好子程序（仅设计输入输出，具体实现不管）；
③按思路进行开发，将子程序作为组件嵌入；
④逐个实现子程序。
***
未实现的子程序，我会在其名称后面标个\*号，比如「某子程序\*」，如上面步骤，我动作开发的最后一步，逐个实现子程序的时候，专找标\*的子程序，实现完毕后，就将\*号去掉，表示实现完毕。
所以，如果就像现在这样，所有子程序的定义线性排列，我逐个实现子程序的时候就一目了然，非常方便，当去掉所有子程序\*号的时候，就是我动作开发完毕的时候。
所以，如果子程序中管理子程序的话，我就不太好知晓还有哪些子程序没有实现。
***
当然，这只是我个人的习惯，虽然我自己觉得比较科学 ^_^
老大酌情考虑吧，仅供参考~

**Comment by kanglade** [comment]
由此想到，如果Quicker本身就支持给子程序打「未完成」标记的话就会很方便，老大也可以考虑一下这个功能。

**Comment by cesaryuan** [comment]
> * 目前我个人感觉子程序的定义，就现在这样，在子程序列表中统一管理就很好（不分层级），一来方便管理（子程序中管理其下子程序容易造成子程序实现的遗漏，这应该与我的动作开发习惯有关，后面说明），二来不增加复杂度。
> * 我不推荐分享的子程序中包含其他子程序，如果分享的子程序含有其他子程序，动作开发者应该将其分解成步骤组。我子程序中包含其他子程序的情况非常多，但都仅针对单个动作，都不适合分享。
> * 如果一定要分享嵌套子程序的子程序的话，将嵌套的子程序自动「转换成步骤组」或许也是个可以考虑的方法。
> 
> 附我的开发习惯：
> ①想好动作的整个思路以及数据结构；
> ②设计好子程序（仅设计输入输出，具体实现不管）；
> ③按思路进行开发，将子程序作为组件嵌入；
> ④逐个实现子程序。
> 
> 未实现的子程序，我会在其名称后面标个*号，比如「某子程序*」，如上面步骤，我动作开发的最后一步，逐个实现子程序的时候，专找标*的子程序，实现完毕后，就将*号去掉，表示实现完毕。
> 所以，如果就像现在这样，所有子程序的定义线性排列，我逐个实现子程序的时候就一目了然，非常方便，当去掉所有子程序*号的时候，就是我动作开发完毕的时候。
> 所以，如果子程序中管理子程序的话，我就不太好知晓还有哪些子程序没有实现。
> 
> 当然，这只是我个人的习惯，虽然我自己觉得比较科学 ^_^
> 老大酌情考虑吧，仅供参考~

![image](https://user-images.githubusercontent.com/35998162/93693577-1ce71980-fb34-11ea-9da2-c8072837a124.png)

**Comment by kanglade** [comment]
@cesaryuan 你说的有道理，子程序内容越来越高级的趋势无法避免，子程序内使用子程序也很正常，现在的使用方式我使用下来体验也还不错。现在问题主要是分享时，子程序中使用的子程序如何处理。现在的话，我比较倾向于 @cuiliang 的第三种方式：下载后，将所有子程序转换成「动作内子程序」。
