### ISSUE TITLE
右键辅助

### ISSUE THREAD

**Issue by kanglade** [cuiliang/QuickPadCn#1248]
将鼠标右键作为修饰键（类比扩展热键）进行拦截，按住右键后点击键盘上某个按键触发操作（包含动作在内的各类操作）。

**Comment by kanglade** [comment]
鼠标的X1、X2键作为引导键进行拦截好像也不错（个人感觉右键的体验最好）

**Comment by kanglade** [comment]
有个主意：让「扩展热键」的「引导键」支持鼠标按键，由用户自己决定是否使用（启用）。
比如，用户可以设置右键作为引导键，那么其他相关功能则禁用（例如长按激活面板），由用户自己来选择右键拦截后的操作。

**Comment by kanglade** [comment]
我觉得，「鼠标右键+其他按键」是「快速激活操作/动作」体验最好的方式，非常期待实现~

**Comment by cuiliang** [comment]
右键或x键+键盘 = 扩展热键.  要想与长按触发面板等操作兼容, 需要将超时时间设置的长一些, 或者取消超时后原有按键消息的选项(变成持续拦截)

**Comment by kanglade** [comment]
是的是的，本质就是扩展热键，不妨就在扩展热键里面支持就好。
兼容的话，一个是增加超时时间，另外一个是取消原长按的功能。

**Comment by cuiliang** [comment]
1.10.14
