### ISSUE TITLE
自从购买会员后, 时不时就出现激活主窗口后, 主窗口透明屏幕问题

### ISSUE THREAD

**Issue by xcl-net** [cuiliang/QuickPadCn#1249]
**描述BUG**
自从购买会员后, 时不时就出现激活主窗口后, 主窗口透明屏幕问题, 免费版本则没有这个问题;

**重现步骤**
1. 鼠标中建激活的窗口, 之前免费时候也是用的这个;
2. 激活之后主面板是透明的;

**相关截图**
![image](https://user-images.githubusercontent.com/15728845/93839861-ceb35100-fcc0-11ea-9595-34a4090a9716.png)

**环境信息:**
 - 操作系统版本：
OS 名称:          Microsoft Windows 10 教育版
OS 版本:          10.0.17763 暂缺 Build 17763
OS 制造商:        Microsoft Corporation
 - Quicker版本：
![image](https://user-images.githubusercontent.com/15728845/93839959-3d90aa00-fcc1-11ea-8292-1ff1fab81e5d.png)

**Comment by cuiliang** [comment]
这个和是否免费版没有关系，可以试试更新windows后，更新一下显卡驱动。 我了解有几个用户有这个现象。另外如果是笔记本，可以试试关闭核显只留独显模式。

**Comment by kunpeng9** [comment]
> 这个和是否免费版没有关系，可以试试更新windows后，更新一下显卡驱动。 我了解有几个用户有这个现象。另外如果是笔记本，可以试试关闭核显只留独显模式。
 @cuiliang 我也出现过类似的情况，但是和他这个有所不同，就是显示quicker界面后面的内容，不显示界面内容，编辑动作有时候会出现，导致我无法保存动作。

**Comment by cuiliang** [comment]
哪个版本出现过? 最近的版本还出过么?

kunpeng9 <notifications@github.com> 于2020年9月29日周二 下午7:10写道：

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
