### ISSUE TITLE
界面BUG问题

### ISSUE THREAD

**Issue by cainf** [cuiliang/QuickPadCn#1250]
**描述BUG**
如果对Quicker的外观-尺寸（如按钮大小、间隙和宽度）作了调整后，
点击Win10右下角Quicker图标激活打开的主界面，与定义界面不符，
而在桌面中键激活主界面则是正确的。
这个BUG连续持续存在多个版本。

**重现步骤**
1.Quicker中设置-尺寸-按钮大小：48；间隙：1；边框宽度：5；保存
2.在桌面激活主界面，上述1的配置生效；
3.在Win10工具条右下角图标点击打开，主界面瞬间拉宽

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win10 10.0.19041.508
 - Quicker版本：1.10.10.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
方便录个屏么？中键和托盘打开的是同一个窗口，应该不会出现2个界面。

**Comment by cainf** [comment]
请见附件，两种打开方式下，界面胖一圈。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: CuiLiang <notifications@github.com>
发送时间: Tuesday, September 22, 2020 2:42:00 PM
收件人: cuiliang/Quicker <Quicker@noreply.github.com>
抄送: cainf <qczy@msn.com>; Author <author@noreply.github.com>
主题: Re: [cuiliang/Quicker] 界面BUG问题 (#1250)


方便录个屏么？中键和托盘打开的是同一个窗口，应该不会出现2个界面。

―

**Comment by cuiliang** [comment]
@cainf 看不到附件。估计需要在网页里粘贴才行。

**Comment by cainf** [comment]
请见附件，解压后Mp4
[Uploading bug.mp4.zip…]()

**Comment by cuiliang** [comment]
等它上传完再提交😂

**Comment by cainf** [comment]
[bug.zip](https://github.com/cuiliang/Quicker/files/5265567/bug.zip)
应该可以了吧，github上传文件真心不好用

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/93971129-12ca5280-fda2-11ea-82f5-cd9c34d91926.png)
因为检测到资源管理器进程，这里显示提示文字把窗口撑开了。
可以取消这个选项：
![image](https://user-images.githubusercontent.com/1972649/93971193-2d9cc700-fda2-11ea-92b6-2e73e363570c.png)
