### ISSUE TITLE
黑名单全屏软件禁用增加白名单

### ISSUE THREAD

**Issue by kamen-exaid** [cuiliang/QuickPadCn#1254]
**需求描述**
家用pc在打游戏的时候设置了全屏禁用会同步到公司pc上，这样会导致公司的一部分软件无法呼出quicker

**描述你想要的解决方案**
增加一个白名单设置

**描述您考虑过的替代方案**
在设置全屏禁用后，白名单中的应用依然可以呼出quicker

 **其他上下文**
![image](https://user-images.githubusercontent.com/52849005/94327261-47c1e980-ffdc-11ea-8537-ac5171f34e47.png)

**Comment by cuiliang** [comment]
这样太复杂了。 
可以将所有游戏加入黑名单，取消这个选项。 或者玩游戏之前使用快捷键暂停Quicker。

**Comment by kamen-exaid** [comment]
好的吧，我试试看

**Comment by kamen-exaid** [comment]
以LOL国服为例，我在选取拖动禁用窗口上无法选择到游戏窗口，在添加中增加了游戏exe，还是会激活quicker窗口
快捷键方式有个问题，在游戏中使用快捷键无法暂停quicker，需要切换窗口出来才

**Comment by cuiliang** [comment]
后来加了。
