### ISSUE TITLE
锁定动作页切换时，进程绑定的快捷键无法更新识别当前进程

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1255]
如题

**Comment by guoranjun2** [comment]
![image](https://user-images.githubusercontent.com/50692082/94347698-f01d8f80-0068-11eb-8cd9-4e059c12b662.png)
老大，发现一个bug，好像右键锁定通用和任务栏这两个面板时程序会崩溃

**Comment by guoranjun2** [comment]
我知道了，没有创建面板的话才会崩溃
