### ISSUE TITLE
webview2启动后空白

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1257]
https://getquicker.net/sharedaction?code=af3916f5-c75c-461c-944a-08d859ddd946

![bug](https://user-images.githubusercontent.com/35998162/94341138-c13bf500-0039-11eb-84b3-3f81ba2e6b55.gif)

**Comment by cuiliang** [comment]
测试发现窗口置顶的时候会出这个现象。
已提交到MS。
https://github.com/MicrosoftEdge/WebView2Feedback/issues/486

**Comment by kanglade** [comment]
![image](https://user-images.githubusercontent.com/24608004/94357917-753b8f80-00cf-11eb-9408-0dad4be8532b.png)
![image](https://user-images.githubusercontent.com/24608004/94357928-884e5f80-00cf-11eb-9a5a-911650b60376.png)
没成功过，是不是哪里不对（没有勾选置顶）

**Comment by cuiliang** [comment]
@kanglade  安装Canary预览版。https://www.microsoftedgeinsider.com/zh-cn/download
