### ISSUE TITLE
无法的移动的安装窗口导致我无法安装quicker更新

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1258]
**描述BUG**
对bug的清晰简洁描述。
我确定这个bug一直存在【只不过之前搞忘记反馈这个，】，没有随着版本更新被修复【时不时就出现，不知道这个情况为啥有的版本出现，有的版本不出现】。不知道为啥安装之后他那个窗口就是这样，搞得我无法安装更新版本，只能点x取消安装，以前试过好些次安装都不行，窗口就是出现在很里面的位置，我并没有移动它啊。
**重现步骤**
1.安装更新
2.弹出窗口
3.只能点x取消安装

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/44609485/94551272-aced3780-0287-11eb-970e-6ae0841eb8d4.png)
**环境信息:**
 - 操作系统版本：Windows规格
版本=Windows10专业版
版本号=1903
安装日期=2019/9/14
操作系统版本=18362.1082
 - Quicker版本：1.10.13.0
**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个可能是windows的bug, 因为安装过程是在软件里没法控制的,是windows的安装服务处理的. 你可以试试更新一下windows看看.

**Comment by kunpeng9** [comment]
@cuiliang 刚刚安装试了一下，
![image](https://user-images.githubusercontent.com/44609485/94554256-664e0c00-028c-11eb-9417-ea66846555da.png)
![image](https://user-images.githubusercontent.com/44609485/94554265-6a7a2980-028c-11eb-9227-a9689b088adc.png)
![image](https://user-images.githubusercontent.com/44609485/94554348-87aef800-028c-11eb-911a-e57071f456f6.png)
一直点是，电脑重启之后，看了一下软件版本号，显示软件已经更新成功。
没有更新系统，就是一直点quicker的那个提示

**Comment by cuiliang** [comment]
我的意思是那个窗口位置的问题，是quicker不能控制的，需要更新windows试试解决。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
