### ISSUE TITLE
徽标文字仅在鼠标移动到动作上再显示

### ISSUE THREAD

**Issue by hqyyqh** [cuiliang/QuickPadCn#1259]
**需求描述**

使用`状态存取`的`设置徽标文字`功能，会一直在动作上显示，有点类似消息提醒，可能会对一些用户造成困扰。

![image](https://user-images.githubusercontent.com/38676455/94798808-b9eb6180-0414-11eb-9168-e67850410c87.png)

**描述你想要的解决方案**

当鼠标移动到动作上再显示徽标文字，类似于动作的备注。

优势：

1. 可以仅在需要查看的时候显示，在视觉上不会太打扰用户。
2. 鼠标点击面板动作这个过程，肯定要把鼠标放在动作上，因此并不会带来额外的操作问题。

![image](https://user-images.githubusercontent.com/38676455/94799099-32eab900-0415-11eb-8fb9-500aab872bd1.png)

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
这个有点难哈，放弃了😂。
