### ISSUE TITLE
想要自定义不同软件中  左键加某个鼠标键   的功能（现在左键加某个鼠标键是全局操作状态）

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1263]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by qiu-cool** [comment]
想要自定义不同软件中 左键加某个鼠标键 的功能（现在左键加某个鼠标键是全局操作状态），我在单独设置某软件的左键辅助时无法键入鼠标键来覆盖全局的设置

**Comment by cuiliang** [comment]
已实现，下一版更新。
