### ISSUE TITLE
用quicker调用中国工程科技中心的api

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1264]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
我记得以往有不少人写过那个调用API的动作，也有计划自己搞一个，但是计划一拖再拖。
[API](http://mall.ckcest.cn/application/index_api.html?f=api)中国工程科技知识中心=特色资源=资源列表提供了不少api大家可以去试一下
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
用quicker调用中国工程科技中心的api
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
还有替代方案？可以让我比较方便的调用各种api，没搞明白，以前稍微看过学了一下，没学懂。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/95019872-743fca80-069a-11eb-80b8-b25b5704d958.png)

**Comment by cuiliang** [comment]
这个用HTTP模块调用就行了，需要自行了解API和HTTP请求相关知识。 这个API好像需要付费的。
