### ISSUE TITLE
需求：软件支持动作分组

### ISSUE THREAD

**Issue by debbbbie** [cuiliang/QuickPadCn#1265]
**需求描述**
比如我用vscode，打开项目A时需要几个bat定制命令；打开项目B时需要另外几个bat定制命令。
如果没有分组的概念，那么A和B的命令会在一起，但他们并不需要显示。

vscode的title可以显示出当前是哪个项目，进而可以实现这个简单的需求。
场景的其他IDE，比如VS、Jetbrains等都需要这个需求

**描述你想要的解决方案**
根据当前应用的标题来进行分组设置动作。

**Comment by cuiliang** [comment]
方法1：通过分页将他们分别放在不通的动作页上，使用滚轮快速翻页（键盘激活可以左右键切换）。
方法2：可以做一个动作，根据窗口标题来分别显示两个用户选择，根据选择的选项执行bat命令。可以绑定动作到快捷键或扩展热键来触发这个动作。
