### ISSUE TITLE
添加动作api

### ISSUE THREAD

**Issue by liquidhelium** [cuiliang/QuickPadCn#1268]
**需求描述**

制作一个api，使得可以在其他地方调用quicker的单条指令，比如:(python)

```python
import quicker #导入(假象的)quicker库
quicker.showtext("Hello World!")
```

```python
import quicker
if quicker.some_thing(): #如果某事发生
    quicker.showtext("something happend")
```
不需要懂其他编程语言，只要做一个网络api就可以了。

**描述你想要的解决方案**

可以使用xml-rpc或类似的方案来跨编程语言调用.

**描述您考虑过的替代方案**

还可以使用RESTapi之类的，或者是http

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可以使用外部启动传递参数: https://getquicker.net/kc/help/doc/quicker-starter

API 短期不太有希望了, 后期再考虑. 这个case先关掉了,压力太大😂

**Comment by liquidhelium** [comment]
啊这
