### ISSUE TITLE
是否可以在鼠标手势里面添加类似于MouseInc软件里面的贴图功能？

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1270]
**需求描述**
quicker的动作库里面有类似于贴图的动作，但是还是要依赖于其它软件，不能直接用手势来实现，我看到MouseInc软件里面的逆时针画一个方框的手势，就可以直接达到贴图的功能，很是方便实用，不知道quicker的手势里面是否可以添加一下此功能？

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
Quicker自带截图模块，可以不依赖第三方的。
你可以直接用这个动作试一下 https://getquicker.net/sharedaction?code=9bfc34fb-b7f7-40bd-6d0c-08d6c304e16e
也可以用组合动作，截图后得到图片变量，再使用显示图片模块。
不考虑在手势里增加单独的功能了。

**Comment by cuiliang** [comment]
请安装[1.11.1版本](https://getquicker.net/Help/Versions) 后使用此动作：https://getquicker.net/sharedaction?code=3d9f7fbb-752a-40f5-d827-08d86cbb0005
