### ISSUE TITLE
半透明的界面在遇到黑色桌面时系统按钮可视性很差

### ISSUE THREAD

**Issue by EX-XD** [cuiliang/QuickPadCn#1271]
**描述BUG**
RT

**重现步骤**
1.桌面背景设置为黑色
2.在桌面呼出软件

**相关截图**
![Snipaste_2020-10-09_16-33-27](https://user-images.githubusercontent.com/55660754/95562035-29cd9d80-0a4e-11eb-98d9-2a6599105491.png)

**环境信息:**
 - 操作系统版本：WIN10 PRO 1909
 - Quicker版本：1.10.15.0

**Comment by cuiliang** [comment]
可以在外观里调整一下按钮的颜色。
![image](https://user-images.githubusercontent.com/1972649/95581007-d6b61380-0a6a-11eb-983b-cb5c8b5875b3.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
