### ISSUE TITLE
关于“左键辅助”的问题和建议

### ISSUE THREAD

**Issue by QingW-7023** [cuiliang/QuickPadCn#1274]
设计软件CorelDraw中左键拖动对象再单击右键会复制一个指定对象到目标地点。如果我设置左键辅助里的“鼠标右键”为关闭窗口，那CDR里的操作就被覆盖了。

希望有解决办法。比如我想到：可以单独在设置CorelDraw的专属左键辅助的时候，可以在辅助键里选择右键、侧键等键的操作。

如果解决这个难题，操作顺利度肯定得到很大的提升。请求了。呼求关注这个问题！感谢！

**Comment by cuiliang** [comment]
请升级到最新版https://getquicker.net/Help/Versions    ，可以选。
![image](https://user-images.githubusercontent.com/1972649/95693041-bbaaf580-0c5c-11eb-89bb-24c687ea243d.png)
