### ISSUE TITLE
电脑卡死死机

### ISSUE THREAD

**Issue by skycityzy** [cuiliang/QuickPadCn#1275]
**描述BUG**
第一次安装quicker之后打开设置界面的时候卡死，按键无反应，只能强制重启电脑。然后打开设置界面之后正常，设置轮盘卡死，按键无反应，鼠标无反应，强制重启后轮盘正常。今天自己设置组合动作的时候，卡死，按键无反应，强制重启后问题没有得到解决，还是卡死。

**重现步骤**
不知道是不是我的电脑的问题，但我电脑运行其他软件没有出现类似情况，运行quicker以前没有使用过的功能，比如说第一次使用自定义右键、设置轮盘的时候都会卡死，键盘鼠标全部无反应。只能强制重启。

**相关截图**
无截图，都是卡死了。

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.11.1.0

**附加信息**
![Snipaste_2020-10-14_14-11-21](https://user-images.githubusercontent.com/71860806/95950485-332c8080-0e27-11eb-815f-871e3ea8f8af.png)
![Snipaste_2020-10-14_14-10-52](https://user-images.githubusercontent.com/71860806/95950487-345dad80-0e27-11eb-80c8-02b3a5a17330.png)

**Comment by cuiliang** [comment]
有没有使用其它手势类软件？

**Comment by cuiliang** [comment]
如果需要请加qq 联系远程看看。

**Comment by skycityzy** [comment]
好的，你加我吗？

**Comment by skycityzy** [comment]
2250569288

**Comment by skycityzy** [comment]
> 如果需要请加qq联系远程看看。

--

**Comment by cuiliang** [comment]
已定位，输入法问题：搜狗智慧版2
