### ISSUE TITLE
印象笔记的quicker面板识别问题

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1276]
**描述BUG**
对bug的清晰简洁描述。
印象笔记国际版和国内版正式分家了，这个面板识别的有问题，还是共用的
一些动作也失效了，我已联系几个动作的作者了，ever，ty他们
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/44609485/96208797-dd7be380-0fa0-11eb-8efd-d0f9e4556f2b.png)
**环境信息:**
 - 操作系统版本：以前汇报过，win10【具体几搞忘了，好像19还是几来着，总之比较新】
 - Quicker版本：当前版本：1.11.1

**附加信息**
在此添加有关此问题的任何其他上下文。
[2020/10/07|02 = 下一步行动 | evernote 更新以及后续影响 - 知乎](https://zhuanlan.zhihu.com/p/262751279) 我的知乎文章，持续记录，更新中【目前还没有确定，总共有哪些动作失效】

**Comment by cuiliang** [comment]
很早就分家了吧，识别有什么问题？

**Comment by kunpeng9** [comment]
@cuiliang 很早就分家了【这个图片，两个软件能同时安装了，以前不行的】【两个软件现在有很大不同，算是两个软件了，识别上还是一个】我那个文章里面记录的比较详细

**Comment by cuiliang** [comment]
Quicker目前是根据进程名（exe的名称去掉扩展名）来识别的，他们两个估计是使用相的evernote.exe作为主程序的，所以会出现你说的那个情况。目前还没有很好的办法，另外同时使用国内版和国际版的情况应该也不是很多的，所以暂且不考虑做进一步的处理。
