### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by batman-1** [cuiliang/QuickPadCn#1278]
**描述BUG**
在WPS里轮盘只能识别全局中设置的快捷动作。

**重现步骤**
1.只能顶部才能识别WPS的动作，其余位置识别的都是全局的动作设置
2.截图1是在表格顶部蓝色条框中跳出的轮盘，上面就有合并单元格的设置
3.截图2是在表格里跳出的轮盘，上面只有我在全局设置的快捷动作。

**相关截图**
![111](https://user-images.githubusercontent.com/22445319/96405781-9c8a0600-1210-11eb-94cc-e90cd114d663.png)
![222](https://user-images.githubusercontent.com/22445319/96405793-a14eba00-1210-11eb-9228-1151f2d1aaaa.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.10.15

**Comment by cuiliang** [comment]
WPS 是多进程软件，要把相关的进程都添加进来。 https://getquicker.net/KC/Help/Doc/profiles#0Og5g

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
