### ISSUE TITLE
副显示器无法使用左键辅助快捷复制粘贴功能

### ISSUE THREAD

**Issue by LunarianCubed** [cuiliang/QuickPadCn#1279]
**描述BUG**
主显示器上，长按左键同时按右键进行复制粘贴功能正常，副屏幕复制粘贴皆无法使用

1.重新加载鼠标挂钩，再次尝试，无效。
2.重设左键辅助为默认，再次尝试，无效。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows10家庭中文版18363.1139
 - Quicker版本：1.10.15

**Comment by cuiliang** [comment]
请更新到快速通道最新版本测试一下看看

**Comment by LunarianCubed** [comment]
已更新为快速通道最新版本 1.11.5
目前在副屏窗口最大化时，仍然无法复制/粘贴（测试了记事本，word和浏览器）
在桌面或者非最大化窗口都可以正常使用

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/97066190-fcecbf00-15e5-11eb-812e-356627574e8a.png)
这是因为开启了全屏禁用了。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
