### ISSUE TITLE
quicker的中文名？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1281]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
刚刚编辑整理b站视频的时候突然想到的，quicker的中文是啥？
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
确定了吗？目前，要不叫快点？【用捷径好像和别的重复了，感觉快点好】
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
anki有个中文名叫暗记【因为b站的视频管理需要搜索，有时候根本搜不到【有的大写，有英文的好像就不太好搜到，有时候可以有时候不行】】
![image](https://user-images.githubusercontent.com/44609485/97079299-56c0a980-1625-11eb-943f-5a9badb563eb.png)=
![image](https://user-images.githubusercontent.com/44609485/97079340-a4d5ad00-1625-11eb-81e1-fda62bcfdcc8.png)
刚刚看了一下好像可以了，之前反馈过，不知道啥时候b站改进了

**Comment by cuiliang** [comment]
没有合适的中文名

**Comment by kunpeng9** [comment]
@cuiliang 网页我的分享可以增加排序吗？
![image](https://user-images.githubusercontent.com/44609485/97111436-b9936d00-1719-11eb-8257-a15da98b74fa.png)目前ji简陋了一点，有不少动作没有通过审核，不好查看；希望可以排序一下；

**Comment by cuiliang** [comment]
整理issues
