### ISSUE TITLE
无法识别Mouselnc

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1282]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
![image](https://user-images.githubusercontent.com/44609485/97102008-d1003500-16dc-11eb-86c0-f1225e907f42.png)
weisha为啥这个只能识别为chrome；Mouselnc 2.10.21A
地址在https://github.com/shuax/MouseInc.Settings
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
可以识别
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
以前也用过一些开源软件，发现它们有的被识别为java，不知道怎么回事；当初搞忘记记录了；所以没有细节和图片；

**Comment by cuiliang** [comment]
因为它的配置界面是用chrome做的，当前进程是chrome。
