### ISSUE TITLE
PWA应用单独设置面板

### ISSUE THREAD

**Issue by nanmao** [cuiliang/QuickPadCn#1284]
**需求描述**
我用Chrome把`Notion`, `Roam Research`, `Grammarly` 等网页用PWA打开, 但是这些PWA应用和Chrome共用一个面板, 
我希望能为PWA应用提供独立的面板, 以避免触发动作冲突/快捷键不够用/轮盘不够用. 

**描述你想要的解决方案**
为PWA应用提供单独的quicker面板.

**描述您考虑过的替代方案**
无.

 **其他上下文**
无.

**Comment by cuiliang** [comment]
后来可以给网址设置动作页了。 时间过的真快。
