### ISSUE TITLE
输入法切换有时不工作

### ISSUE THREAD

**Issue by dk-angela** [cuiliang/QuickPadCn#1285]
**描述BUG**
“文本指令”里设置的命令，快速操作为“输入法：”相关选项时，不能顺利切换，始终只能切换成中文。但是在“左键辅助”里设置的输入法中英文切换是正常的。
设置为切换为英文时无效，设置为“中文”时能生效，设置为“输入法：切换中英文”时，始终只会切换成中文。

**重现步骤**
1.在“文本指令”里添加命令，并指定为“快速操作”-“输入法”相关选项
2.输入文本指令使用·

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 专业版 64 位 19041.264
 - Quicker版本：1.11.5.0

**Comment by cuiliang** [comment]
输入法的API确实有时候会有不稳定的现象，不过也没有其它API可以控制输入法了。
可以换一个输入法试试有没有改善。

**Comment by dk-angela** [comment]
可是用鼠标的“左键辅助”功能来触发就是正常的呢…

**Comment by cuiliang** [comment]
难道是正在输入文字影响的？

**Comment by dk-angela** [comment]
应该不是吧，只有“文本命令”会有问题，可以在英文状态下切换到中文输入法，但是中文输入状态下就不能切到英文了。如果用鼠标的左键辅助的话，有没有在输入文字都可以正常使用，无比顺畅。
