### ISSUE TITLE
右击桌面任务栏图标-中止动作-无法选择想要停止的动作

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1287]
**描述BUG**
在桌面任务栏QUCIKER右边的图标较少，而动作的名称较长时。右击桌面任务栏图标-中止动作-具体的动作名称会显示在左边，无法选择想要停止的动作

**重现步骤**
1.右击桌面任务栏图标
2.单击中止动作
3.具体的动作名称会显示在左边，无法选择想要停止的动作
**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/64642209/97435400-5002a100-195b-11eb-9cab-23db3b30b9cc.png)

**环境信息:**
 - 操作系统版本：
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎4/‎11
操作系统版本	19042.572
体验	Windows Feature Experience Pack 120.2212.31.0

 - Quicker版本：
1.11.1.0
**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
动作是在一个步骤结束的时候才判断是不是要停止。 
看下动作定义中，有没有需要耗时比较长时间才能结束的模块步骤。

**Comment by ghost** [comment]
> 动作是在一个步骤结束的时候才判断是不是要停止。
> 看下动作定义中，有没有需要耗时比较长时间才能结束的模块步骤。
感谢您的回答！这不是选中点击后动作无法停止的问题，就很单纯是他这个“循环2”显示在左边的时候，鼠标移动过去（离开显示主窗口这一大菜单的时候），整个菜单都会消失，我点不到那个“循环2”。“循环2”显示在右边的时候，鼠标能选到就能停止动作

**Comment by cuiliang** [comment]
哦，是这个问题啊。 
这个不清楚是.Net的还是Windows的问题，Quicker里无法进行控制。 可以尝试这里的方法看看：https://github.com/cuiliang/Quicker/issues/1287
