### ISSUE TITLE
能否支持 Linux ？

### ISSUE THREAD

**Issue by sherlocknieh** [cuiliang/QuickPadCn#1288]

**Comment by cuiliang** [comment]
目前没有计划的，人力不足，能力有限

**Comment by asukaminato0721** [comment]
https://github.com/asukaminato0721/quicker-rs I begin work on it now.

**Comment by asukaminato0721** [comment]
https://github.com/asukaminato0721/quicker-rs/issues/2 screenshot, although gui on linux is horrible.
