### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1291]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
为啥显示成这样的？
![image](https://user-images.githubusercontent.com/44609485/97589438-73e7e480-1a38-11eb-9283-df6921bdef06.png)
-
![image](https://user-images.githubusercontent.com/44609485/97589463-7a765c00-1a38-11eb-9c31-bcc14c3bab11.png)
之前就想到了，但是搞忘记说了，今天突然想起来就汇报一下
邮件客户端是mailbird
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
随缘吧；不紧急，这个；
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
它这个是怎么显示的啊？peng9.se。不是kunpeng9.serious【不是应该先k吗？之前quicker昵称叫鲲鹏九万里，没注意到有这个问题】【为了和我的知乎账号名一致所以才改成这个的，之前各个账号都是不同的昵称、名字，都是瞎几把取的，没有统一，各大平台账号差不多都改成一样的了【好像增加了被人肉的风险】【有的账号改不了，没办法，顶个每次登陆之后看着难受死的昵称，怪我当初注册账号的时候急躁，没注意】】

**Comment by XuCpeng** [comment]
建议删除issue模板的注释文字，只保留标题即可。不需要过多的语气词和没有意义的个人想法，专注描述问题，这不是写个人博客。不然描述的不清楚，别人也没法帮你。

**Comment by cuiliang** [comment]
邮箱网页里有乱码么？ 也可能是email客户端的问题

**Comment by kunpeng9** [comment]
@XuCpeng 我是因为想要把各个账号统一昵称  一下所以才改那个quicker昵称的；要是删除了注释，使用场景不就不完整了，一般反馈我都会尽量说清楚；很快就解决了，问题就关闭了，怕什么；

**Comment by kunpeng9** [comment]
![image](https://user-images.githubusercontent.com/44609485/97833166-b434b480-1d0f-11eb-8018-0527f61c53ef.png)
搞错了，看了一下确实是；网页显示没问题；
![image](https://user-images.githubusercontent.com/44609485/97833262-f8c05000-1d0f-11eb-8328-55067d8813ba.png)
一个以往忽略的细节；
![image](https://user-images.githubusercontent.com/44609485/97833292-04137b80-1d10-11eb-8ef8-dddf7df781e5.png)
邮件客户端才显示网址，网页不显示，点击跳转不了；
等下我发邮件给mailbird的人； @cuiliang
