### ISSUE TITLE
右键快捷键截图的问题

### ISSUE THREAD

**Issue by wesley1910** [cuiliang/QuickPadCn#1302]
开启这个功能会导致我玩某些游戏的时候右键功能缺失。如果要游戏名称可以联系我，

**Comment by cuiliang** [comment]
测试了一下，是支持黑名单的。把游戏进程添加到黑名单就可以了。
另外可以开启全屏禁用选项。
也可以游戏前请使用快捷键暂停Quicker。

**Comment by wesley1910** [comment]
好的，谢谢你们的及时回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CuiLiang <notifications@github.com&gt;
发送时间: 2020年11月9日 08:23
收件人: cuiliang/Quicker <Quicker@noreply.github.com&gt;
抄送: cyczq3 <402385994@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cuiliang/Quicker] 右键快捷键截图的问题 (#1302)





 
此功能暂无选项控制是否使用黑名单。 游戏前请使用快捷键暂停Quicker以避免干扰。
