### ISSUE TITLE
win10英文系统环境下quicker无法启动

### ISSUE THREAD

**Issue by JadeYu3F** [cuiliang/QuickPadCn#1306]
win10英文系统环境下quicker无法正常启动，打开后无任何提示，不会弹出面板，任务栏图标过几秒关闭。

**环境信息:**
 - 操作系统版本：windows 10 专业版 1903 18362.30
 - Quicker版本：1.11.80

**附加信息**
重装系统后首次安装quicker时可正常打开，但电脑重启后开始出现上述问题，之后删除log, db或重装quicker都无法解决，偶然把显示语言设置为中文后可正常打开，但正常工作需要显示语言为英文，是否有其他有解决办法

**Comment by cuiliang** [comment]
检查Windows事件查看器，看看里面有没有什么相关的报错信息。

**Comment by JadeYu3F** [comment]
介于电脑实在小白，打开事件查看器十分茫然
除了 quicker 以外，后来还发现其他软件的闪退情况，联想到刚重装系统，考虑可能是系统原因
重新升级 win10 到 20H2 版本后，所有软件（包括 quicker）都可正常使用了，证明应与英文环境无关，具体原因不得而知，不过当前问题算解决了
感谢您的及时回复，非常喜欢 quicker，希望越来越好
