### ISSUE TITLE
定时重新加载鼠标挂钩

### ISSUE THREAD

**Issue by PianoPrince** [cuiliang/QuickPadCn#1309]
**需求描述**
使用右键移动一段距离的方式触发quicker，但是鼠标移动到选项上会出现菜单栏而不是执行该动作（1.7.5以上的版本试过好几个了，一直有这个问题）
勾选了自动恢复丢失鼠标挂钩还是没有用，得一直重新恢复鼠标挂钩，非常麻烦，希望有一个功能能够每隔很短一段时间就自动重新加载鼠标挂钩（这个时间可以自己调整当然更好）

**描述您考虑过的替代方案**
暂时只能用画圈等方式暂时替代了，希望能解决这个bug或者添加这个定时加载鼠标挂钩的功能

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/74518377/99327498-08fe3080-28b5-11eb-94f6-480ada49e094.png)

**Comment by cuiliang** [comment]
是每次都出现还是偶尔？
如果使用了手势软件，先退出手势软件测试。 另外可以换个鼠标测试一下看看，也有可能接触不良。

**Comment by PianoPrince** [comment]
每隔几分钟就会出现挂钩丢失的情况，重启电脑或者软件也是一样的情况。另外电脑比较新，也没安装手势软件。使用电脑触摸板右键结果相同，所以应该能排除鼠标的问题

**Comment by cuiliang** [comment]
确定是挂钩丢失了么？怎么判断是挂钩丢失的？
电脑CPU占用高么？ 什么硬件配置？
目前这个功能应该还是比较稳定的，没有很多人报告类似问题。建议先观察一下具体是什么规律，换个鼠标测试一下是否有硬件问题。

**Comment by PianoPrince** [comment]
目前的情况是：如果一直不停的使用quicker并不会出现问题，一两分钟不使用再次使用quicker就会出现同样的问题。
CPU的占用在30%甚至20%以下，硬件配置如下：
![image](https://user-images.githubusercontent.com/74518377/99337710-c0974080-28bd-11eb-9bd6-91f5ea283c89.png)
个人也觉得比较奇怪，因为旧电脑之前用的是挺好的，没有出现任何鼠标挂钩丢失的情况。如果无法解决此问题，之后继续观察规律再来评论，谢谢！

**Comment by cuiliang** [comment]
没有什么思路。
请尝试升级windows到最新版，可能bug少一些。 企业版，LTS，都是比较容易出问题的系统。

**Comment by PianoPrince** [comment]
好的谢谢！
