### ISSUE TITLE
如何实现等到等待鼠标左键抬起时间

### ISSUE THREAD

**Issue by B664577** [cuiliang/QuickPadCn#1314]

**Comment by cuiliang** [comment]
可以循环判断按键状态 https://getquicker.net/kc/help/doc/keyoperation 左键对应的键名是LButton

**Comment by B664577** [comment]
收到，谢谢，今晚试下，主要是想偷懒，复制粘贴自动进行，只需要选中文本即可，但是尝试时候始终都要按一个建，哈哈。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: CuiLiang<mailto:notifications@github.com>
发送时间: 2020年11月25日 17:31
收件人: cuiliang/Quicker<mailto:Quicker@noreply.github.com>
抄送: B664577<mailto:b664577@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [cuiliang/Quicker] 如何实现等到等待鼠标左键抬起时间 (#1314)


可以循环判断按键状态 https://getquicker.net/kc/help/doc/keyoperation 左键对应的键名是LButton

―

**Comment by cuiliang** [comment]
复制粘贴还是直接通过左键+右键等方式指示一下可能更好一些。

**Comment by B664577** [comment]
Windows两个窗口，这边选中，另一边就自动粘贴，可能是我需要大批量处理这种问题的原因，谢谢指导/龇牙

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: CuiLiang<mailto:notifications@github.com>
发送时间: 2020年11月25日 17:38
收件人: cuiliang/Quicker<mailto:Quicker@noreply.github.com>
抄送: B664577<mailto:b664577@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [cuiliang/Quicker] 如何实现等到等待鼠标左键抬起时间 (#1314)


复制粘贴还是直接通过左键+右键等方式指示一下可能更好一些。

―
