### ISSUE TITLE
换种面板？或者其他形式？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1315]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
只有第一个、第二个面板的动作用的计较多；是不是要用那种收藏动作的动作？感觉又有点麻烦；是不是要换种面板，其他类型的，目前这种，面板稍微多了一点其他的面板就不怎么用了；居然少于10次；
要用这个动作收藏 管理一下吗？感觉有点麻烦，安装之后没怎么用过；
咦，这个动作单已经被删掉了嘛；找不到了；
![image](https://user-images.githubusercontent.com/44609485/100233554-de6f4000-2f64-11eb-9bad-752e170fcca0.png)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/100233415-b089fb80-2f64-11eb-9e95-b4700c7d42fb.png)

**Comment by cesaryuan** [comment]
《阅读理解》

**Comment by kunpeng9** [comment]
> 《阅读理解》【不好意思啊。。。我语文成绩一直不好，阅读理解题经常一分都得不到；高考语文好像刚过100；每次写作文都非常头疼】
@cesaryuan  我也不知道具体怎么说好；就有个大致的模糊的念头、想法，前几天晚上睡觉时候，拿起手机加到的滴答的【一直有，但是我忘记了收集，有时候没有及时收集起来】，昨天完成了这个任务，就提了一个问题，issues；

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
