### ISSUE TITLE
专注模式（编辑动作界面）

### ISSUE THREAD

**Issue by kanglade** [cuiliang/QuickPadCn#1317]
可以专注（进入）某个步骤组，而暂时不关心该步骤组以外的内容，参考下图：
![演示专注模式](https://user-images.githubusercontent.com/24608004/100317134-ca741e80-2ff6-11eb-808f-83005e3f3664.gif)

**Comment by cesaryuan** [comment]
> 可以专注（进入）某个步骤组，而暂时不关心该步骤组以外的内容，参考下图：
> ![演示专注模式](https://user-images.githubusercontent.com/24608004/100317134-ca741e80-2ff6-11eb-808f-83005e3f3664.gif)

幕布是吧😂

**Comment by kanglade** [comment]
嗯，用幕布演示的

**Comment by kunpeng9** [comment]
我觉得不是特别紧要吧，而且功能加多了，会不会变得臃肿卡顿，像印象笔记国内版那样？
漫游研究者带火了双链功能之后，连飞书都出双链，幕布也出了，各个软件都出，这个专注功能也有人在滴答清单提过，过了阵子后加上了这个功能。是不是重复劳动了？

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！ 太复杂了以至于难以实现😂
