### ISSUE TITLE
用户选择界面拖动拉伸时，界面元素无法适应调整

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1319]
![image](https://user-images.githubusercontent.com/50692082/100405327-568d5100-309e-11eb-912f-43666693d5d2.png)
用户选择界面拖动拉伸时，界面元素无法适应调整

**Comment by cuiliang** [comment]
这个问题还存在不？ 我测试了一下似乎没问题了。

**Comment by guoranjun2** [comment]
问题已解决，（好像之前的版本就已经解决了），那这个issue还是由我来关闭把
