### ISSUE TITLE
图标右下角可设置角标图片。实用于比如同是Excel文件，但是一眼区分什么内容。

### ISSUE THREAD

**Issue by loveless1999** [cuiliang/QuickPadCn#1321]
**需求描述**
希望图标能设置角标图标，用于区分两个相同图标的内容。因为图标比文字直接，反应更快。

 **截图**
所述位置：
![搜狗截图20201127143248](https://user-images.githubusercontent.com/69227451/100418286-7bdd8780-30bd-11eb-95fc-93f2fa548c85.png)
案例：
![搜狗截图20201127143212](https://user-images.githubusercontent.com/69227451/100418311-8730b300-30bd-11eb-83e1-4c1723343ff0.png)

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
