### ISSUE TITLE
提示第一行不要重复显示标题，因为界面上有。

### ISSUE THREAD

**Issue by loveless1999** [cuiliang/QuickPadCn#1322]
**需求描述**
悬停在应用上，标题出现两次：界面上、提示第一行。
当没有写标题时，提示第一行空着。

**描述你想要的解决方案**
悬停提示第一行不要显示标题。

 **截图**
标题在界面和提示上重复出现：
![搜狗截图20201127144528](https://user-images.githubusercontent.com/69227451/100419470-94e73800-30bf-11eb-9d09-40a4a92c9699.png)
![搜狗截图20201127144849](https://user-images.githubusercontent.com/69227451/100419531-acbebc00-30bf-11eb-88b1-b4e0c646f089.png)

没有标题时，提示第一行空着：
![搜狗截图20201127144725](https://user-images.githubusercontent.com/69227451/100419472-96186500-30bf-11eb-9203-541efded1c8b.png)

**Comment by cuiliang** [comment]
这个主要是解决有时候动作标题太长显示不完或看不清的问题，
所以动作名称和提示都会显示的。
