### ISSUE TITLE
两台设备，其中一台新增动作页并删除，这个动作页在两台设备间反反复复出现。

### ISSUE THREAD

**Issue by loveless1999** [cuiliang/QuickPadCn#1324]
**描述BUG**
删除动作页，同步问题。

**重现步骤**
两台Win10，A设备创建了动作页，并删除。B设备首先没自动同步，手动同步后，删除的动作页出现了。B设备删除此页。打开A设备又出现此页。来回很多次，此页终于两设备都不出现了。这种情况出现多次（不同的动作页）。

**环境信息:**
 - 操作系统版本：Win10
 - Quicker版本：1.11.8.0

**Comment by cuiliang** [comment]
感谢反馈，我研究下。
设备只有在启动的时候才会自动同步，一个电脑修改后，另一个电脑是不知道的，不会自动拉取。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  1.24.1解决了此问题
