### ISSUE TITLE
是否可以分享快点用户手册的opml版【详细的】

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1325]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
markdown版本也行啊；不过最好是opml比较好；通用性比较高；我好导入幕布【幕布精选可以搜到我分享的内容，不过。。没有详细内容，图片里也可以看到，只有一个标题。】；
![image](https://user-images.githubusercontent.com/44609485/100499027-55911800-31a1-11eb-8938-07b1a567ea3c.png)
这个是我当初手动，一点点复制到幕布里面去的；
![image](https://user-images.githubusercontent.com/44609485/100499045-7c4f4e80-31a1-11eb-973e-db482028d78f.png)
之前有想过，也用过liner在文档上面直接标记，发现不是太好用；
![image](https://user-images.githubusercontent.com/44609485/100499065-9e48d100-31a1-11eb-806f-4f045580d23a.png)
701 页面
4,698 亮点
一直搁置，没有怎么处理过这个高亮。。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
试了几个插件，还是不行。。。
![image](https://user-images.githubusercontent.com/44609485/100498961-e1567480-31a0-11eb-838b-37517bc5cea7.png)
![image](https://user-images.githubu
![image](https://user-images.githubusercontent.com/44609485/100498982-f9c68f00-31a0-11eb-87d6-21e30212b47a.png)
sercontent.com/44609485/100498977-ef0bfa00-31a0-11eb-9bdf-b37d22adcd5d.png)
语雀上也剪藏不了；
![image](https://user-images.githubusercontent.com/44609485/100499006-2ed2e180-31a1-11eb-9257-e05d10549d67.png)

**Comment by cuiliang** [comment]
目前没办法导出这样的格式哦

**Comment by kunpeng9** [comment]
> 目前没办法导出这样的格式哦

那可以导出其他的格式吗？任意的其他的格式都行。只要能导出的。。不强求说opml @cuiliang  markdown也行的；
我看到github上有项目可以把markdown转化为opml；
