### ISSUE TITLE
轮盘能否增加 多一些模式选择

### ISSUE THREAD

**Issue by zhuyanghuan** [cuiliang/QuickPadCn#1332]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by zhuyanghuan** [comment]
比如我在用 建模软件的时候，能否用一种轮盘是建模用的，我在渲染的时候，轮盘可以调掉渲染模式。简单说就是一个软件，可以用多个轮盘。根据自己写需求去调整

**Comment by kunpeng9** [comment]
@zhuyanghuan  我也早有这样的想法，好像也在github提过。问题=怎么判断切换，还有就是就是手动还是快捷键还是用图片识别之类的自动切换轮盘？一个软件里面只能用一个轮盘确实有点难受。

**Comment by cuiliang** [comment]
后来可以通过引导键触发不同场景的轮盘了。
