### ISSUE TITLE
为操作界面添加提示

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1333]
建议在各交互界面增加信息图标，指上去会有悬浮提示，见下图：
![image](https://user-images.githubusercontent.com/1972649/100748119-e542fa80-341d-11eb-9ae4-92360ee4d07f.png)

这样既避免将大段说明写在界面上巨影响美观，也可以给该界面提供必要的说明。

文字和图片都考虑下图片比文字更好反应

悬停体验好点，点击鼠标多一次点击，多消耗了能量

支持图片那就有意思了
现在都是通过第三方软件预览

**Comment by kanglade** [comment]
建议采用Markdown渲染

**Comment by kanglade** [comment]
关于Markdown，JSBox作者的新作品[Taio的介绍](https://sspai.com/post/63729)中提到：

> 如果达成一个目标有多种方法，我们选择经过验证后最可靠的一种。例如，我们遵循 CommonMark 标准构建 Markdown 编辑器，没有引入任何「非标准」的私有格式。这让你在迁移至其它产品或是同时使用多个产品时，不会有兼容问题。

可供参考。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/100968796-fbab9c00-356c-11eb-8636-95cb82d1565c.png)

**Comment by kanglade** [comment]
这些可以统一用![image](https://user-images.githubusercontent.com/24608004/100973410-78427880-3575-11eb-9043-0196477418aa.png)的悬停提示，指上去展示Markdown的渲染，如果悬停提示里面有链接，最好还可以在悬停提示中点击链接。

不要点击界面上的图标或链接之后跳转，这样体验不好。
