### ISSUE TITLE
右键托盘图标里的一些操作可以优化下么

### ISSUE THREAD

**Issue by aLIEz-xue** [cuiliang/QuickPadCn#1336]
鼠标很难移动到子列表
![GIF 2020-12-3 15-05-23](https://user-images.githubusercontent.com/59567929/100975962-bb312b80-3536-11eb-88cd-130bf43d0df9.gif)

**Comment by aLIEz-xue** [comment]
补一张录制到鼠标的动图
![GIF 2020-12-3 15-15-48](https://user-images.githubusercontent.com/59567929/100976499-82de1d00-3537-11eb-81d6-0de513e12f9c.gif)

**Comment by cesaryuan** [comment]
[https://getquicker.net/QA/Question/2619](https://getquicker.net/QA/Question/2619) 可以参考一下这个帖子
