### ISSUE TITLE
多选下拉选择支持编辑

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1339]
![image](https://user-images.githubusercontent.com/50692082/101244862-cc9b5300-3743-11eb-86ed-04b412249f89.png)
这个多选框改进很不错，移除选项方便了很多，唯一不足的是增设项目还是比较困难无法直接在表单完成，如果能加上这个设置应该会好一些。

**Comment by cuiliang** [comment]
感觉不是很可行，编辑框修改后是直接保存内容到输入框的，不会涉及存储。 多选项如果要编辑选项，就需要在编辑后保存到哪里，不是很好定义。
