### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by YanJbehappy** [cuiliang/QuickPadCn#1342]
**描述BUG**
切换双桌面这个动作删除之后依然生效

**重现步骤**
1.工具箱添加：切换双桌面
2.删除动作
3.鼠标移动到桌面左右边缘停靠依然会切换桌面

**环境信息:**
 - 操作系统版本：WINDOWS10 20H2
 - Quicker版本：1.11.8.0

**附加信息**
此动作识别不灵敏，成功率不高，但是偶尔的突然触发很影响工作

**Comment by cuiliang** [comment]
重启一下quicker，或右键点击托盘图标，中止运行中的动作。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/101361062-76601880-38d9-11eb-9e15-7e890b223cde.png)
