### ISSUE TITLE
禁用网络以后，所有动作失效

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1343]
**描述BUG**
如标题所示，禁用网络以后，除了打开本地软件的动作可以用，其它动作全部失效了
**重现步骤**
1.
2.

**相关截图**

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.11.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
怎么失效的现象？
如果动作本身需要网络，肯定是用不了的。
如果从动作库安装的动作，第一次运行的时候会下载动作定义，之后就不需要网络了。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
