### ISSUE TITLE
使用mathpix动作时，发生问题

### ISSUE THREAD

**Issue by ShuichiLi** [cuiliang/QuickPadCn#1345]
**描述BUG**
使用mathpix动作截取公式识别时，出现提示“发送网络请求出错：发送请求时出错。基础连接已经关闭：发送时发生错误。无法从传输连接中读取数据：远程主机强迫关闭了一个现有的连接。远程主机强迫关闭了一个现有的连接。”
**重现步骤**
1.选择mathpix动作
2.截取公式

**相关截图**

**环境信息:**
 - 操作系统版本：Windows 10 2004
 - Quicker版本：1.11.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
从你的电脑到mathpix
服务器的网路不通。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
