### ISSUE TITLE
组合动作-弹窗提示功能无效

### ISSUE THREAD

**Issue by zuijiaosy** [cuiliang/QuickPadCn#1346]
**描述BUG**
组合动作-提示信息功能无效

**重现步骤**
1.新增组合动作
2.拖入提示信息
3. 点击保存

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
[https://s3.ax1x.com/2020/12/16/rlW8hD.gif](https://s3.ax1x.com/2020/12/16/rlW8hD.gif)
**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.11.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可以先重启一下电脑看看是不是仍然有问题。如果还有问题，请截图一下动作定义。

**Comment by cuiliang** [comment]
后来又出现了么？

**Comment by zuijiaosy** [comment]
刚才测试 现在可以弹出来了
![image](https://user-images.githubusercontent.com/49388302/102686476-016ad800-4223-11eb-84fe-e3663dbfeedb.png)

**Comment by cuiliang** [comment]
这个组件在极个别情况下有类似现象，好在出现的机率不高。

**Comment by zuijiaosy** [comment]
偶尔不行; 我现在改成信息框弹出了
