### ISSUE TITLE
移动控制端添加「双击」才可执行的动作

### ISSUE THREAD

**Issue by Gparl** [cuiliang/QuickPadCn#1347]
**需求描述**
移动端太容误触了，quicker运行动作还这么迅速，在手机手指一滑，电脑运行了好几个动作。🤐

**描述你想要的解决方案**
把移动端的动作执行添加一个可「双击」执行的设置选项

**描述您考虑过的替代方案**
没有。

 **其他上下文**
![image_20201217111146](https://user-images.githubusercontent.com/57856401/102439145-9f895300-4015-11eb-9cb5-517100efd55c.png)

**Comment by cuiliang** [comment]
试下这个版本了，有网友加了误触处理。
另外app是开源的，有兴趣可以搞一下，我实在没时间了，感觉用的人也不多，暂时放弃。
[quicker_cn1.0-1-debug.apk.zip](https://github.com/cuiliang/Quicker/files/5742824/quicker_cn1.0-1-debug.apk.zip)
