### ISSUE TITLE
多用户支持

### ISSUE THREAD

**Issue by Yumin-Zhan** [cuiliang/QuickPadCn#1348]
**需求描述**

一个系统可能有多个希望使用 Quicker 的账户。当 Quicker 在一个账户中启动了之后就不能再在另一个账户中使用，必须先在原账户退出再在新账户里手动启动，这样对多账户系统太不友好了。

**描述你想要的解决方案**

支持在不同账户中并行运行；

**描述您考虑过的替代方案**

安装时让用户选择“仅为当前账户安装”或“为所有账户安装”

**其他上下文**

无

**Comment by cuiliang** [comment]
Quicker使用挂钩这种系统级别的资源，无法支持同时启动多个实例。

**Comment by cuiliang** [comment]
整理issues
