### ISSUE TITLE
搜索框输出内容

### ISSUE THREAD

**Issue by WangYH195** [cuiliang/QuickPadCn#1349]
使用qk的搜索框，然后输入内容直接输出到变量，比用户输入那个好看多了
![IMG_20201220_195315](https://user-images.githubusercontent.com/47978351/102712572-3b101180-42fd-11eb-949a-98a698cda1c6.jpg)
![IMG_20201220_195353](https://user-images.githubusercontent.com/47978351/102712578-3ea39880-42fd-11eb-9102-df74aef2c3a3.jpg)

**Comment by cuiliang** [comment]
新版已支持搜索框传参。
