### ISSUE TITLE
希望可以推出一个功能，可以让我可以在某些软件里自动将笔记本的多媒体键恢复成F1 F2等本来的功能

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1351]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

现实生活中我们对功能键（F1F2）和多媒体键（笔记本上有）的使用需求都不是那么绝对的，不会一直不用也不会一直都用。
比如我在一些建模软件编程软件内，功能键是某些快捷键，我希望能够只按一下就实现它的功能，而不用按住Fn，所以每当Quicker检测到我进入这些软件后就自动给我关闭多媒体键那我会很高兴的。而当我退出这些软件去浏览网页时，Quicker能自动为我打开多媒体键，我就能方便的控制音量与屏幕亮度，我会很开心。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

切换多媒体键与功能键的快捷键是 Fn+ESC ，所以要是Quicker能够在检测到我的焦点在特定界面时自动执行这个动作（Fn+ESC）就能解决这个问题吧。
总的来说就是希望Quicker能根据当前焦点软件来自动执行某些动作

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

也许用个AHK的脚本能实现，但我不会。并且Quicker要是能实现这样的功能会让Quicker更强大，所以希望考虑一下

**Comment by cuiliang** [comment]
无法实现哦，是底层硬件控制的。

**Comment by qiu-cool** [comment]
“希望Quicker能根据当前焦点软件来自动执行某些动作”
这能实现吗？
