### ISSUE TITLE
为一动作设置全局快捷键，快捷键所对应的按键功能会被触发

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1352]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
比如我想让 shift+capslock 映射为 enter 键，我新建一个基础动作为按下enter键，并将其全局快捷键设置为 shift+capslock 
结果我每次按下 shift+capslock 大写锁就会打开或关闭，我希望它不变。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
AHK有专门解决这种情况的办法的（加个修饰符），但用AHK来完成这个映射在某些场景下会失效（按enter有效，按shift+capslock 无效），用Quicker就不会出现这种状况，所以希望Quicker能给用户们提供这个选择

**Comment by cuiliang** [comment]
用扩展热键，caps+shift。caps作为引导键。

**Comment by qiu-cool** [comment]
这样就必须先按caps再按shift，不习惯，还是算了

**Comment by cuiliang** [comment]
这个没办法的，因为没有拦截按键消息，键盘会自动切换caps的状态。要想不切换caps，只能使用拦截的方式解决，比如扩展热键。
另外你也可以试下左键辅助，可以把左键+caps映射成回车。
