### ISSUE TITLE
希望Quicker可以根据当前窗口焦点的不同自动执行某些动作

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1353]
比如我设置一个动作是 Fn+Esc（多媒体键和功能键之间切换），当我进入某些软件时，Quicker就自动执行这个动作，将多媒体键换成功能键

**Comment by cuiliang** [comment]
Fn无法识别的，是硬件底层的，对windows不可见。 
自动运行动作，可以写一个组合动作，循环识别前台进程信息，并根据这个信息做操作就可以了。
