### ISSUE TITLE
无法给鼠标中键设置全局快捷键

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1354]
鼠标按中键太累，我希望将键盘按键映射到鼠标中键，于是先新建一个基础按键动作，选择鼠标中键，然后设置全局快捷键，先后尝试了各种快捷键都无法起到单击中键的效果

**Comment by cuiliang** [comment]
实际按键对模拟的状态会有影响。建议换个鼠标比较好。
