### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by TodaLovErika** [cuiliang/QuickPadCn#1355]
**描述BUG**
错误的加载了全局面板

**重现步骤**
1.我只是清空了任务栏，因为我不会用，每次用滚轮任务栏就会去到一页空白页面然后又回不去，就把任务栏的快捷方式都搬到上面那一栏了，详情请见图，我不会用什么高深功能，就简单把它当作一个快接起动器而已
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win7 X64
 - Quicker版本：1.11.80

**附加信息**
在此添加有关此问题的
![捕获](https://user-images.githubusercontent.com/76555503/103082421-052c9f00-4615-11eb-9a59-4511c252518e.JPG)
![捕获2](https://user-images.githubusercontent.com/76555503/103082425-06f66280-4615-11eb-88a2-1c323289c8db.JPG)
![捕获3](https://user-images.githubusercontent.com/76555503/103082428-078ef900-4615-11eb-9a8b-68837aa83e57.JPG)
![捕获4](https://user-images.githubusercontent.com/76555503/103082431-0958bc80-4615-11eb-9f90-efd1c4028620.JPG)
![捕获5](https://user-images.githubusercontent.com/76555503/103082434-09f15300-4615-11eb-9092-ec0be7bc8b2a.JPG)
![捕获6](https://user-images.githubusercontent.com/76555503/103082435-0a89e980-4615-11eb-94ad-849b6254b315.JPG)

任何其他上下文。

**Comment by cuiliang** [comment]
不是特别明白，目前除了这个提示，还有其他不正常的地方么？

**Comment by TodaLovErika** [comment]
> 不是特别明白，目前除了这个提示，还有其他不正常的地方么？

目前我的设置就是像截图那样，简单来讲就像最后一张图那样，底下那栏我完全不放任何东西，卸载重新安装只要登录账户同步之后依然会有这样的提示，有时候会不能呼出主窗口，就是右下角图标点了没反应，左右键都不行，任务管理器结束进程然后重新打开才可以

**Comment by cuiliang** [comment]
这个提示像是把全局的动作页搞到上下文区域去了. 这个提示不影响其他功能,只是发现有这个情况的时候一个提示. 

可以先了解一下面板的结构和动作页是如何自动切换的:
https://getquicker.net/KC/Help/Doc/glossary

https://getquicker.net/KC/Help/Doc/profiles#qDWMO
