### ISSUE TITLE
软件状态保存

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1357]
保存一些软件本身的状态。

- [x] - 搜索框宽度
- [x] - 最后设置的扩展热键引导键
- [ ] -  设置窗口的位置和尺寸
- [x] -  最近使用的设置页；

- [x] 不显示更新动作确认窗口
- [ ] 图标选择窗口尺寸

**Comment by cuiliang** [comment]
保存搜索选项的展开状态
![image](https://user-images.githubusercontent.com/1972649/104536471-1df80580-5653-11eb-9c7e-e44e71c01906.png)

**Comment by cesaryuan** [comment]
不显示更新动作确认窗口

**Comment by cuiliang** [comment]
图标选择窗口尺寸

**Comment by kanglade** [comment]
数据在本地么？上下文菜单中的「移动到」路径是不是也可以加到这里呢
