### ISSUE TITLE
手机app无法扫码连电脑端

### ISSUE THREAD

**Issue by p2i** [cuiliang/QuickPadCn#1358]
**描述BUG**
手机app扫码连接电脑相同局域网失败

**重现步骤**
1.在电脑上点击“连接手机app”按钮
2.在手机上打开app扫码连接后出现截图提示
> 换小米八爪鱼路由器后出现这种情况

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![quickerq](https://user-images.githubusercontent.com/44310187/103163342-d93d3380-4837-11eb-95fd-79ad43d6780a.jpg)

**环境信息:**
 - 操作系统版本：Win10
 - Quicker版本：1.11.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Help/Doc/mobile-app 请参考文档排查。
