### ISSUE TITLE
截图优化建议

### ISSUE THREAD

**Issue by marcusxx** [cuiliang/QuickPadCn#1359]
1. 截图交互：
左键框选直接截图；
右键框选可调整范围；
截图前或左键框选时直接点右键则取消截图；

2. 截图框放大比例有点高，反而导致看不清楚位置了，平时截图不需要那么高的精度，建议缩小一倍，测试QQ截图的比例大概是这个的1/3，Snipaste大概是1/2。
![image](https://user-images.githubusercontent.com/48142413/103167413-f983e700-4865-11eb-84b6-71f8652c90a4.png)

3. 取消截图不需要提示。
![image](https://user-images.githubusercontent.com/48142413/103167466-49fb4480-4866-11eb-9a5b-3f0ed631034d.png)

**Comment by cuiliang** [comment]
done
