### ISSUE TITLE
Mac支持

### ISSUE THREAD

**Issue by menhuan** [cuiliang/QuickPadCn#1360]
**需求描述**
求对Mac的支持。

**Comment by cuiliang** [comment]
短期没有精力了。
如果要支持mac，你需要quicker里哪些部分的功能？

**Comment by menhuan** [comment]
捷径和跨软件的自动化

**Comment by menhuan** [comment]
> 短期没有精力了。
> 如果要支持mac，你需要quicker里哪些部分的功能？
捷径和跨软件的自动化

**Comment by menhuan** [comment]
捷径.跨软件的自动化,鼠标的面板

**Comment by cuiliang** [comment]
整理issues
