### ISSUE TITLE
子选项能不能设置快捷键？

### ISSUE THREAD

**Issue by lmf1468** [cuiliang/QuickPadCn#1361]
![Snipaste_2020-12-28_12-15-03](https://user-images.githubusercontent.com/59329800/103189271-d6f5da80-4906-11eb-8b11-3a106c5c9a96.png)

**Comment by cuiliang** [comment]
不能的。 
不过有一个略微复杂的变通方式：新建一个组合动作，在里面使用运行其他动作的模块，这时候可以传递参数。右键菜单也一样是传递参数，只要参数一样效果是一样的。
