### ISSUE TITLE
进行重放键鼠操作时，如果遇到图片所示内容，重放就会停止。如何保证这种情况时，重放也正常进行。（我不想关闭这个Windows提示）

### ISSUE THREAD

**Issue by lmf1468** [cuiliang/QuickPadCn#1362]
![Snipaste_2020-12-29_11-44-55](https://user-images.githubusercontent.com/59329800/103257226-4a612000-49cb-11eb-96f4-3b64d3b1d66b.png)

**Comment by cuiliang** [comment]
这个窗口权限高，是没法通过quicker操作的。
通常关闭UAC可以避免，不过对一般用户来说不建议这样做，有一定 的安全风险。

**Comment by 1468507695** [comment]
谢谢Thanks♪(･ω･)ﾉ

**Comment by lmf1468** [comment]
谢谢Thanks♪(･ω･)ﾉ
