### ISSUE TITLE
软件自动更新一直是1.11.8版本

### ISSUE THREAD

**Issue by anycall** [cuiliang/QuickPadCn#1364]
**描述BUG**
Quicker客户端一直无法获取到最新的1.12.7版本。

**重现步骤**
1.点击检查更新
2.暂无新版本：慢速通道：1.11.8，快速通道1.11.8

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/1912363/103296049-38659880-4a30-11eb-86d0-ea3b55a79943.png)

**环境信息:**
 - 操作系统版本：windows 10
 - Quicker版本：1.11.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
新版改动比较大，还没定型，没有推送。

**Comment by cuiliang** [comment]
快速通道已更新1.12.15
