### ISSUE TITLE
睡眠后，滚轮调节系统音量，会失效，重启软件才能恢复

### ISSUE THREAD

**Issue by ZardarD** [cuiliang/QuickPadCn#1365]
**描述BUG**
睡眠后，滚轮调节系统音量，会失效，重启软件才能恢复
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：20h2
 - Quicker版本：1.11.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
挂钩丢了，可以用快捷键或托盘菜单重新加载一下挂钩。也可以在配置里选一下自动检测挂钩丢失的选项。
另外如果同时使用了手势软件，也会有类似现象，和软件的挂钩顺序有关。
