### ISSUE TITLE
用户选择界面筛选框支持传输变量

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1366]
如果是循环调用用户选择界面，第一次辛苦筛选的内容会被消除，
比如我要从一个很长的文件列表打开一个文件，筛选到文件后想先打开确认一下是不是我想要的，所以我用到了循环，
但是在第一次选择结束后窗口就关闭了，第二次要锁定目标文件范围又得重复一次输入，这个步骤有点多余，极大降低了使用筛选的体验，如果支持传输变量的话，第一次筛选后可以记录下来并用于下次筛选，我相信会有很大帮助

**Comment by cuiliang** [comment]
1.22.32 已支持。
