### ISSUE TITLE
电脑端部分图标不显示

### ISSUE THREAD

**Issue by drunk-bird** [cuiliang/QuickPadCn#1368]
**描述BUG**
部分图标如快搜，二维码工具等等都没有图标显示

**重现步骤**
1.安装完打开就不显示
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:** 
 - 操作系统版本：win10 64位
 - Quicker版本：1.12.15 老版本也一样

**附加信息**
在此添加有关此问题的任何其他上下文。
![Snipaste_2021-01-05_22-19-13](https://user-images.githubusercontent.com/28821255/103656832-0e6a2400-4fa4-11eb-98ec-fa66d49c9f96.png)

**Comment by cesaryuan** [comment]
网络问题吧

**Comment by drunk-bird** [comment]
其他都是正常的，只有这个软件图标加载不出，而且icons8进去也没问题，自己手动添加也不显示

> 网络问题吧

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/103723443-0abeb780-500d-11eb-8036-41917cc91b49.png)
应该是网络问题的，同步都有问题。

**Comment by drunk-bird** [comment]
> 网络问题吧
> ![image](https://user-images.githubusercontent.com/1972649/103723443-0abeb780-500d-11eb-8036-41917cc91b49.png)
> 应该是网络问题的，同步都有问题。

同步是因为没有登陆账号的原因，而且安装时候提示 ：警告1946。无法设置快捷方式"quicker.Ink"的属性"System.AppUserModel.ID"，重新换了几个版本都一样。

网络我改过dns也没用

**Comment by cuiliang** [comment]
1946 这个提示没关系。 
不过总体上来说，这个肯定是系统问题的，需要自己想办法解决了。
建议不要使用第三方精简系统，不要使用所谓的优化工具优化系统...

**Comment by drunk-bird** [comment]
> 1946 这个提示没关系。
> 不过总体上来说，这个肯定是系统问题的，需要自己想办法解决了。
> 建议不要使用第三方精简系统，不要使用所谓的优化工具优化系统...

好的，谢谢
