### ISSUE TITLE
为快捷键（动作）添加按下松开只执行一次动作的选项

### ISSUE THREAD

**Issue by tshanli** [cuiliang/QuickPadCn#1369]
**需求描述**
为动作设置的对应快捷键直到松开应当只执行一次，否则会出现很多意想不到的后果，如：我昨天不小心按住自己设置的某个的操作文本的动作5秒就在一瞬间打开了几十个浏览器窗口导致电脑崩溃。

**描述你想要的解决方案**
为 “快捷键（动作）” 添加 **非递归（Non-Recursive）** 选项并推荐为默认设置。在用户设置成 **递归** 的选项时应警告用户 _可能会造成不可预料且不可挽回的后果_

**描述您考虑过的替代方案**
无

 **其他上下文**
意外示例：
![unexpection](https://i.imgur.com/1Tou8QU.gif)

**Comment by cuiliang** [comment]
动作本身可以设置禁止多个实例同时运行的选项。
键盘的连续触发是windows的工作方式，这个行为应该是合理的。
https://www.xstui.com/read/870

**Comment by tshanli** [comment]
我知道这是合理的。我只是希望您增加个便民的选项，能让Quicker监听所设置的快捷键。与这情况类似的就是vim，它专门给按键绑定做了递归与非递归的区分

**Comment by cuiliang** [comment]
这个不可行的。
快捷键的实现原理是在Windows里注册，windows检测到按键后触发消息，然后触发动作。Quicker没法拦截。
Quicker也没法判断一个动作是用户希望重复，还是不希望重复。

所以只能由用户在动作里去设置的。
![image](https://user-images.githubusercontent.com/1972649/103837036-d1964e00-50c5-11eb-932d-82dcc5f1da44.png)
