### ISSUE TITLE
动作触发按键在翻页后消失

### ISSUE THREAD

**Issue by onlyesterday** [cuiliang/QuickPadCn#1370]
**描述BUG**
成功设置好动作触发按键，面板出现后可以正常显示。但如果功能区有多页的情况，在翻页后，触发键就消失了，指定的按键也不能触发对应的快捷动作。

**重现步骤**
1. 设定动作触发按键。
2. 唤出Quicker面板。
3. 切换功能页，此时触发按键丢失，无法正常显示。另外发现如果钉住窗口后，触发键也会丢失不起作用。

**相关截图**
初始触发键显示正常。
![image](https://user-images.githubusercontent.com/15660569/103850154-358c2880-506c-11eb-88ae-8a95f13cdedc.png)
切换功能面页后，触发键丢失，也不再起作用。
![image](https://user-images.githubusercontent.com/15660569/103850258-72f0b600-506c-11eb-943b-396dab610a00.png)

**环境信息:**
 - 操作系统版本：Windows 10 20H2 19042.685
 - Quicker版本：1.12.15

**附加信息**
另外，看Quicker的设置描述中，说明可以使用方向键进行翻页操作，我试了一下，没有成功，不确定是什么问题。
![image](https://user-images.githubusercontent.com/15660569/103850394-bd723280-506c-11eb-89cb-75f1c00a6314.png)

**Comment by cuiliang** [comment]
测试没问题。
切换功能页使用方向键或鼠标滚轮都是正常的。全局区使用上下键，上下文区使用左右键翻页。

**Comment by onlyesterday** [comment]
多谢回复。又试了一下，应该是由于我是通过点击面板上的页面指示圆点进行翻页的，这种情况下，触发键就消失了。其它象鼠标焦点放在面板上，或者钉住Quicker面板之类的操作，触发键也会丢失而不起作用。
纯键盘方向键和滚轮操作，不改变焦点，看上去是没问题的。
![image](https://user-images.githubusercontent.com/15660569/103863730-f61f0580-5086-11eb-95e0-404e60a9d769.png)

**Comment by cuiliang** [comment]
不要使用点击白点的方式翻页，有鼠标点击会让按键触发失效的。
