### ISSUE TITLE
搜索框搜索功能优化

### ISSUE THREAD

**Issue by chenyu-01** [cuiliang/QuickPadCn#1371]
**需求描述**
1. 输入搜索框时，搜出来的动作来源不一，需要更精准搜出动作。
2. 调出搜索框没有输入时，希望调整动作排列顺序。目前只能看出上一次使用过的动作被优先排到第一个位置。

**描述你想要的解决方案**
1. 希望能采用命令方式来定位动作 比如 - jsb(记事本）（空格）动作缩写.
2. 希望能根据当前激活的窗口优先排列动作，比如第一优先级是当前窗口下的动作，第二优先级是使用频率，第三优先级是全局动作页的动作。

 **其他上下文**
![image](https://user-images.githubusercontent.com/63953834/103898068-58334580-512f-11eb-8bd0-1df431d679b8.png)

-  如图，比如第二个动作被优先排到第一个位置（因为我当前是在chrome激活的情况下调用的）
- 我希望调用第二个动作 输入 `-chr sett` (前面是 `Chrome` 的前三个字母 后面是动作名`setting`的前三个字母。
- 上一条的补充，输入-chr 后希望在输入框里同步显示待选动作页 比如下图中的，更加方便。
![image](https://user-images.githubusercontent.com/63953834/103898752-5cac2e00-5130-11eb-8c6e-f62c703b746d.png)

后记
*其实我是根据listary软件的使用经验提出的建议。* 强烈安利，太方便了。

**Comment by cuiliang** [comment]
感谢建议！我可能完全忽略了这条，非常抱歉，后面我再试试。
