### ISSUE TITLE
多线程里面获取文本总是失败

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1373]
无论是获取文本模块还是模拟按键复制后再获取剪贴板文本都是如此

**Comment by guoranjun2** [comment]
![image](https://user-images.githubusercontent.com/50692082/104168530-2674f400-5439-11eb-871d-0b3908ad78e2.png)
![image](https://user-images.githubusercontent.com/50692082/104168577-38569700-5439-11eb-87bd-91f6d8a7f1db.png)

**Comment by cuiliang** [comment]
剪贴板不支持多线程操作的。

**Comment by guoranjun2** [comment]
这样啊，那我取消多线程操作好了
