### ISSUE TITLE
隐藏任务栏间接导致无法呼出面板

### ISSUE THREAD

**Issue by HaoranWang2000** [cuiliang/QuickPadCn#1374]
**描述BUG**
开启windows任务栏设置中的“桌面模式自动隐藏任务栏”后，当任务栏处于隐藏状态时，部分最大化的软件窗口将被windows视为全屏，如sublime text 3、QOwnnotes等，甚至包括quicker自己的设置界面，因此若开启了quicker设置中的全屏禁用选项将导致非预期的无法唤出面板

**环境信息:**
 - 操作系统版本：Windows 10 Professional (Build 18363)
 - Quicker版本：1.12.22

**Comment by cuiliang** [comment]
全屏是根据窗口尺寸和屏幕尺寸判断的，所以这种情况下会识别为全屏使用。
可以对全屏禁用的功能添加白名单。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
