### ISSUE TITLE
反转切换虚拟桌面

### ISSUE THREAD

**Issue by tony956** [cuiliang/QuickPadCn#1375]
<img width="268" alt="Snipaste_2021-01-18_08-01-02" src="https://user-images.githubusercontent.com/74848354/104859908-5a817500-5963-11eb-8f06-d2a4dfcaae78.png">
反转切换虚拟桌面，个人使用习惯问题

**Comment by cuiliang** [comment]
可以通过高级鼠标触发自行设置。 
这个功能内部也是使用高级鼠标触发实现的。
