### ISSUE TITLE
内存占用过大

### ISSUE THREAD

**Issue by kelukeka** [cuiliang/QuickPadCn#1376]
**描述BUG**
使用过程中，发现内存逐渐升高，一直到3900M甚至更多，且在不停增长

**重现步骤**
1. 安装快速通道最新版本quicker
2. 安装最新版本沙拉查词并开启触边翻译

**相关截图**
![image](https://user-images.githubusercontent.com/77624197/104921494-5b9eba80-59d4-11eb-9c04-768ecd12ef8b.png)

**环境信息:**
 - 操作系统版本：版本	Windows 10 家庭中文版
版本号	20H2
操作系统版本	19042.746
序列号	YN0092CN
体验	Windows Feature Experience Pack 120.2212.551.0
 - Quicker版本：1.12.22

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能是动作里循环持续，没有时间释放内存导致的。 https://getquicker.net/KC/Kb/Article/336
还有同时开启其他动作么？

**Comment by cuiliang** [comment]
可以在进程上右键，创建转储文件，然后压缩一下发给我（通过网盘等方式），我这里分析一下看看

**Comment by cuiliang** [comment]
本地可以复现，不用发文件了。 我先研究一下看看

**Comment by kelukeka** [comment]
链接：https://pan.baidu.com/s/1hrtVGFeocQ6Sq6zXvuM1_Q 
提取码：1234 
复制这段内容后打开百度网盘手机App，操作更方便哦




这是转储文件。


另反馈一个bug，未更新之前即存在：沙拉查词右下角的浮窗会经常性无反应，需要点击任务栏使之最小化再还原后，点击才有响应。


另提供一个建议：
沙拉查词触边翻译希望设置延时起效，有时候仅仅是鼠标接触边缘（比如点击开始菜单），便激发了截屏翻译功能，误触率极高。

**Comment by cuiliang** [comment]
感谢反馈，基本定位问题了。
请在https://getquicker.net/Help/Versions/Version?version=1.22.26.0 右侧点击下载新版本。

悬浮窗口无反应的问题倒是首次看到，下次有遇到还请录屏一下。

可以在这里设置延迟，我试了一下是正常生效的， 你可以再试试。
![image](https://user-images.githubusercontent.com/1972649/104929603-1338ca00-59df-11eb-983c-de5aedeabde5.png)

**Comment by cuiliang** [comment]
新版有试过么？ 有没有再次出现这么高的问题呢

**Comment by kelukeka** [comment]
您好，新版安装后没有出现内存不断增加的问题，但内存占用依旧很大，虽然不知道以前版本内存占用如何，因为没有关注。
以及请问下，上次邮件咨询设置沙拉查词触边翻译延迟的问题，您有回复一张图片，但我无法打开（可能是内容来自GitHub原因），还烦请再次发送，谢谢！


| |

**Comment by cuiliang** [comment]
一般100-200M是比较正常的。（使用状态，编辑动作会更高一些）
动作上右键，动作设置--设置面板，打开后选中高级设置的选项，确认，会打开高级设置的界面。里面有个触发边延时参数。

**Comment by kelukeka** [comment]
已退回1.12.22版本，确认该版本内存占用约150M左右，1.22.26版本尽管没有不断增高的内存占用问题，但依然有900-1100M的内存占用，可能需要注意此问题。设置延迟已经找到，感谢作者。

**Comment by cuiliang** [comment]
900-1000 应该是不正常的，开启就这么高么？ 还是运行了什么动作？ 
另外尽量不要直接回Email，你的email签名里有邮件地址，会泄露隐私。

**Comment by kelukeka** [comment]
发现回退后版本使用一段时间后依然会占用约1000M内存，开启时没这么搞，运行沙拉查词动作时发生改现象。
![image](https://user-images.githubusercontent.com/77624197/105043958-20b68880-5aa1-11eb-91f3-9722e857d791.png)

**Comment by cuiliang** [comment]
旧版本肯定会的。26版本不应该只在使用动作的情况下就有这么高。 如果再用1.22.26版本，到时候可以再创建个转储文件发来看下。

**Comment by cuiliang** [comment]
reopen

**Comment by kelukeka** [comment]
作者你好，现在quicker依然有问题如下：
版本：1.22.26
沙拉查词动作最新。
使用过程中，内存不断上升，越来越高，但上升不是很剧烈。
在托盘图表右键退出quicker后，任务管理器依然有quicker进程，且内存占用和耗电量极高。
![image](https://user-images.githubusercontent.com/77624197/105436181-b1f04f80-5c99-11eb-9644-4b1bd6d07c8a.png)

**Comment by cuiliang** [comment]
方便的话麻烦再创建一个转储文件我这里找工具分析一下，谢谢

**Comment by kelukeka** [comment]
打开quicker时，内存占用约80M, 启用沙拉查词动作后，占用约140M，随后随着时间和触边翻译使用次数增加，内存如充电营养占用率缓慢上升。使用约3h后，内存占用约500M。下面是此时内存转储文件，看是否有用。
链接：https://pan.baidu.com/s/1FbuSBkWGqkZX2FcXTmVQ-A 
提取码：1234 
复制这段内容后打开百度网盘手机App，操作更方便哦

quicker版本：1.22.26
沙拉查词插件地址：https://getquicker.net/Sharedaction?code=b0d1a134-8284-4a44-d1be-08d746da5869
系统版本： win 10 1909  18363.1316

打完上述文字时，quicker内存占用由502增加至525.8M
![image](https://user-images.githubusercontent.com/77624197/105450810-3e107000-5cb6-11eb-8e3a-75e387599262.png)

**Comment by cuiliang** [comment]
感谢。 这时候还有别的动作在运行么？

**Comment by kelukeka** [comment]
> 感谢。 这时候还有别的动作在运行么？

没有运行其他动作，仅此一个

**Comment by cuiliang** [comment]
定位到原因了，和一个第三方的组件有关，目前已经将问题提交给组件作者，看看能不能解决。 https://github.com/zzzprojects/Eval-Expression.NET/issues/94
如果最后不能的话，需要quicker里使用另外的一个方式规避一下。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  
请下载1.22.30版本试下看看，组件作者提供了一个解决方法，已参照修改。
![image](https://user-images.githubusercontent.com/1972649/105503011-067ae580-5d01-11eb-8107-3b74b44b9036.png)

**Comment by kelukeka** [comment]
内存占用已正常。感谢！
