### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by jiutianliminwang** [cuiliang/QuickPadCn#1377]
**描述BUG**
截图拖拽电脑蓝屏

**重现步骤**
1.多屏幕，在一个屏幕的网页上截屏后拖拽到另一个屏幕（可能和分辨率差距大有关系）

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 version 1909
 - Quicker版本：免费版 1.11.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个和Quicker好像没用关系吧

**Comment by jiutianliminwang** [comment]
是Quicker的截图

**Comment by cuiliang** [comment]
可以升级windows+ 升级显卡驱动试试。 我这边都是多屏使用的，没有遇到过类似问题。

**Comment by jiutianliminwang** [comment]
可能又是window的bug吧

**Comment by cuiliang** [comment]
win版本太老了，bug老多了。
