### ISSUE TITLE
"将黑名单与全屏禁用设置用于扩展热键"功能有时工作不完全

### ISSUE THREAD

**Issue by HaoranWang2000** [cuiliang/QuickPadCn#1378]
**描述BUG**
在开启设置中的"开启全屏禁用功能"与"将黑名单与全屏禁用设置用于扩展热键"之后，即使在已加入"这些进程即使全屏也启用Quicker"名单的进程中仍然无法使用扩展热键。
值得注意的是，每当在Quicker设置中改动任意配置项并应用设置后该问题不再出现，即全屏禁用白名单对扩展热键重新生效，但每次重启Quicker后该问题都会再次出现。（包括开启电脑后第一次启动、关闭后手动重新启动、直接使用重启选项或运行重启Quicker动作步骤）

**环境信息:**
 - 操作系统版本：Windows 10 Professional 10.0 (Build 18363)
 - Quicker版本：1.22.26

**Comment by cuiliang** [comment]
感谢反馈，已解决待下一版1.22.33更新。
