### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1379]
![image](https://user-images.githubusercontent.com/63406787/105661655-ee75b280-5f08-11eb-8e4c-268122d9bb59.png)
在xx软件里一按 ESC 键就弹出这个消息
我记得以前在这个软件里为一个动作设置过一个快捷键，但现在我已经将这个动作页删了，他还是会弹出这个信息

**Comment by cuiliang** [comment]
在配置里找下动作快捷键设置，删掉对应的条目。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
