### ISSUE TITLE
将quicker 自带截图设置微信截图，取消截图再截图会提示正在截图中

### ISSUE THREAD

**Issue by tangchi88588** [cuiliang/QuickPadCn#1380]
![image](https://user-images.githubusercontent.com/17637902/105800761-74a9fb80-5fd2-11eb-9506-f76f234966af.png)

**Comment by cuiliang** [comment]
第三方截图要等超时以后才能知道截图取消。这期间不能进行其它截图操作。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
