### ISSUE TITLE
图片显示蓝屏

### ISSUE THREAD

**Issue by dashuai945** [cuiliang/QuickPadCn#1381]
**描述BUG**
我最近使用截图的时候发现电脑蓝屏死机，经测试，电脑win10，主显示器分辨率1366*768，副显示器1920*1080，使用截图后，如果跨显示器托动截图，会发生蓝屏死机，蓝屏代码unexpected kernel mode trap；
，后发现，钉在桌面上的图片移动都会出现蓝屏，测试过截图动作，ID：313727e7-b7a3-4a0a-852e-c6cedb82ec71 、测试过I like，ID：daa1e524-6067-4390-af3a-69b3904159b4 

**重现步骤**
1. 使用截图或者I like使屏幕出现一张图片
2. 将图片在拖入另一个显示器（分辨率不一样的 主显示器分辨率1366*768，副显示器1920*1080）
3. 蓝屏死机

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 2004
 - Quicker版本：1.22.31快速版

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
蓝屏通常是驱动问题，可以升级或更换一下显卡驱动版本试试。 这种情况quicker里也没法调试的。

**Comment by dashuai945** [comment]
好的，谢谢啦

**Comment by cuiliang** [comment]
使用的哪种显卡？ 笔记本还是台式机呢？如果是笔记本，有没有使用双显卡自动切换的模式？ 
可以留一些信息，以便有类似现象的朋友一起发现看看有没有什么共同点。

**Comment by dashuai945** [comment]
> 使用的哪种显卡？ 笔记本还是台式机呢？如果是笔记本，有没有使用双显卡自动切换的模式？
> 可以留一些信息，以便有类似现象的朋友一起发现看看有没有什么共同点。

 英特尔 HD Graphics 5500+ Nvidia GeForce GTX 850M

**Comment by cuiliang** [comment]
> > 使用的哪种显卡？ 笔记本还是台式机呢？如果是笔记本，有没有使用双显卡自动切换的模式？
> > 可以留一些信息，以便有类似现象的朋友一起发现看看有没有什么共同点。
> 
> 英特尔 HD Graphics 5500+ Nvidia GeForce GTX 850M

可以在bios里关闭一下核显试试，可能就好了。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
