### ISSUE TITLE
无法正确识别WIN10内置输入法的状态

### ISSUE THREAD

**Issue by EX-XD** [cuiliang/QuickPadCn#1382]
**描述BUG**
文本指令功能需要对输入法状态进行判断，但软件在WIN10内置的输入法下无法正确判断当前状态导致错误响应。

**重现步骤**
0.前置条件：
0.1.纯英文字母指令，操作类型为【键入内容】，未勾选【输入法开启时，使用退格方式消除缩写词】
0.2.QQ对话窗口下测试（ESC键会关闭QQ窗口）
1.WIN10拼音：
1.1.中文输入模式正常录入
1.2.英文输入模式按下触发字符后QQ窗口关闭
2.WIN10日语：
2.1.日语输入模式和英文输入模式均正常录入
3.WIN10英语
3.1.按下触发字符后不会删除文本指令，会直接在文本指令后录入设定的【键入内容】

**环境信息:**
 - 操作系统版本：
版本： Windows10专业版
版本号：2004
操作系统版本：19041.746
体验： Windows Feature Experience Pack 120.2212.551.0
 - Quicker版本：1.12.15

**附加信息**
华宇拼音V7.1测试无问题

**Comment by cuiliang** [comment]
现在的win10版本已经不支持之前的一个未公开的API，导致无法识别和更新输入法状态了。
研究了很长时间，目前没啥办法。 微软官方目前没有可以使用的API了。

**Comment by EX-XD** [comment]
> 现在的win10版本已经不支持之前的一个未公开的API，导致无法识别和更新输入法状态了。
> 研究了很长时间，目前没啥办法。 微软官方目前没有可以使用的API了。

好吧，目前勾选【输入法开启时，使用退格方式消除缩写词】倒是还能用……那只能先这样了

**Comment by lyscop** [comment]
> 现在的win10版本已经不支持之前的一个未公开的API，导致无法识别和更新输入法状态了。
> 研究了很长时间，目前没啥办法。 微软官方目前没有可以使用的API了。

发现还是可以识别搜狗的输入法中英文的状态呀
可否告知是否是内置ImmGetConversionStatus()呀

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.42.6 改进了输入法支持，目前应该可以支持普通模式了。
