### ISSUE TITLE
【讨论贴】步骤编辑器改进

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#1383]
当动作特别复杂的时候，嵌套太深的时候，不太容易定位。

方案1：
高亮正在编辑的步骤列表。

方案2：
增加书签；

方案3：
。。。。

**Comment by kanglade** [comment]
书签 https://github.com/cuiliang/Quicker/issues/688

**Comment by kanglade** [comment]
专注模式 https://github.com/cuiliang/Quicker/issues/1317

**Comment by kanglade** [comment]
步骤可以自定义颜色

**Comment by pengjiaxu1999** [comment]
![「16614」「ろるあ／Rolua」「78492607」「EMERGENCE」「オリジナル,C97,オリジナル10000users入り」](https://user-images.githubusercontent.com/75591994/106728796-c5ab9680-6647-11eb-872c-36f061733068.jpg)
背景支持看妹子。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/106736328-48d0ea80-6650-11eb-9080-821315f8e26b.png)
