### ISSUE TITLE
捕获耳机按键事件

### ISSUE THREAD

**Issue by PaperStrike** [cuiliang/QuickPadCn#1384]
**需求描述**
现在大多数的蓝牙耳机和有线耳机上边会有按键，一个到四个不等。希望 Quicker 可以拦截捕获这些按键事件，包括点击、双击、三击、长按之类的。

**描述你想要的解决方案**
对于有线耳机，一直很少有 PC 厂商支持按键，但大多数新电脑的耳机接口已经实现了和手机一致，TRRS 耳麦一体，有一定的捕获按键事件的硬件基础。[Hacking in Android headset button support for Windows](http://www.roligheten.no/blog/programming/2018/07/02/media-controls-windows.html) 提供了一种详细的几乎不占 CPU 资源的可以全 OEM 平台捕获有线耳机按键事件的方法。值得注意的是，有线耳机上任一按键对波形图的影响几乎一致，考虑误差后看不出区别，所以可能只能解析一种按键。另外，程序里的 `PRESS_SAMPLE_THRESHOLD` 建议改为 0.6。

蓝牙耳机的按键事件在 Linux 上有专门的 KeyCode 和 API，不知道 Windows 有没有。

**描述您考虑过的替代方案**
[上述链接](http://www.roligheten.no/blog/programming/2018/07/02/media-controls-windows.html)里的 Python 程序配合 Quicker。

 **其他上下文**
有线耳机长按时的波形图：
![有线耳机长按时的波形图](https://user-images.githubusercontent.com/22674396/107063522-71eea800-6815-11eb-9bc5-fa97d6e37dfd.png)
按下瞬间，跳到 -1 再跳到 1 再变为负数后逐渐正常。
松开瞬间，跳到 1 再跳到 -1 再变为正数后后逐渐正常。

有线耳机短按时的波形图：
![有线耳机短按时的波形图](https://user-images.githubusercontent.com/22674396/107063852-d14cb800-6815-11eb-9863-ab3218e98d0d.png)
跳到 -1 再跳到 1 再变为负数再变为正数后逐渐正常。

**Comment by PaperStrike** [comment]
似乎有一种全新的方法可以捕获有线耳机的不同按键事件。https://github.com/roligheten/AndroidMediaControlsWindows/issues/2

**Comment by cuiliang** [comment]
这个估计比较难，用的人也不多，而且这个用在音乐软件里比较好，quicker似乎没有很强的用途，暂不考虑了。
