### ISSUE TITLE
鼠标中键 和鼠标左键单击quicker图标唤醒的面板 显示内容不同

### ISSUE THREAD

**Issue by 619620297** [cuiliang/QuickPadCn#1385]
**描述BUG**
鼠标中键和键盘CTRL唤醒的面板
和鼠标左键单击quicker图标唤醒的面板
显示内容不同

**重现步骤**
1.
2.

**相关截图**
![image](https://user-images.githubusercontent.com/78713082/107171101-e7689d00-69fc-11eb-93a7-d6c3c0f0f8e0.png)
鼠标中键唤醒
![image](https://user-images.githubusercontent.com/78713082/107171120-f64f4f80-69fc-11eb-8ade-63f6bb956c27.png)
鼠标左键单击quicker图标唤醒如图

**环境信息:**
 - 操作系统版本：Windows10家庭中文版 1909  ；操作系统版本18363.1316
 - Quicker版本：1.11.8.0 专业版

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
quicker是根据当前活动的窗口来自动加载动作页的。

https://getquicker.net/KC/Help/Doc/profiles 

托盘图标只在某些情况下使用。使用它弹出面板会让你正在操作的软件丢失焦点。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
