### ISSUE TITLE
图片处理的Resize，不支持这几个参数吗

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1387]
![image](https://user-images.githubusercontent.com/35998162/107482185-4aebf980-6bba-11eb-8615-812a0966309a.png)

图片处理的Resize，不支持这几个参数吗

**Comment by cuiliang** [comment]
嗯，有些简化。需要的话再加上

**Comment by cesaryuan** [comment]
> 嗯，有些简化。需要的话再加上

个人觉得还挺有用的参数

**Comment by cuiliang** [comment]
1.22.40 增加ResizeEx
