### ISSUE TITLE
快捷输入时间，内容错误

### ISSUE THREAD

**Issue by DanielDu87** [cuiliang/QuickPadCn#1390]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.使用文本指令指定了sj为{0:yyyy-mm-dd HH:mm:ss}
2.今天2021年2月18日，输入结果为2021-40-18 15:40:02

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/19722567/108321786-98421980-71ff-11eb-9ac1-36224e9f57b5.png)

**环境信息:**
 - 操作系统版本：win10 20H2 企业版
 - Quicker版本：1.22.39

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
月份用MM，要大写。
