### ISSUE TITLE
v1.22.39 #1203 的提示框未设置焦点问题又出现了 

### ISSUE THREAD

**Issue by leeyaunlong** [cuiliang/QuickPadCn#1391]
v1.22.39 #1203 的提示框未设置焦点问题又出现了 
麻烦请再修复一下.

**Comment by cuiliang** [comment]
是弹窗提示得不到焦点么？

**Comment by leeyaunlong** [comment]
> 是弹窗提示得不到焦点么？

是的, 跟上次提的bug一样, 弹出的确认框没有焦点, 焦点还在最初的totalcommand上.

**Comment by cuiliang** [comment]
ok，刚加了一个设置焦点，等下一版更新上。1.22.43
