### ISSUE TITLE
组件 "用户输入" ,预先设置一些内容,当执行时 存在一些问题

### ISSUE THREAD

**Issue by leeyaunlong** [cuiliang/QuickPadCn#1392]
**描述BUG**
组件 "用户输入" ,预先设置一些内容,当执行时 存在一些问题

### 1. 默认是里面的内容全选了 , 期望是只设置输入焦点到输入框而不是全选(或者有选项来实现)
一个场景: 
用户输入我设置一个文本模板,每次执行时,只需要改动或者添加一点内容即可.
按现在的方式,每次都要先想办法取消全选的内容,然后再手动移动焦点.

### 2. v1.22.x~ last版本中, 用户输入,输入法存在不能切换问题.
1. 用户输入中,似乎不能切换输入法 (win+space), 
我只能用quicker的扩展快捷键定义了一个切换输入法的宏来切换.

2. 用户输入中, 当前输入法的状态不能切换.
比如我用的百度输入法, (中英文状态,单击ctrl切换).
在用户输入框中,ctrl键似乎被屏蔽了, 换别的热键shift等,似乎也屏蔽了.导致当前输入法不能中英文或者全半角状态.

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：v1.22.39

**Comment by cuiliang** [comment]
按向右方向键可以将光标移动到最后。默认全选的行为，可以避免要修改全部内容的时候比较麻烦的操作。
输入法切换刚测试了一下是正常的。试试换到别的输入法下看看？ 另外输入法切换一遍默认是ctrl+space或单击shift吧，单击ctrl的话，看一下quicker里有没有使用单击ctrl弹出面板。

**Comment by leeyaunlong** [comment]
仔细检查了一下 和listary, 百度输入法等叠加到一起的时候,似乎有逻辑冲突.
似乎是用户输入框默认全选的 触发逻辑导致的.
能搞个不全选的选项或者搞个临时版本我测一下吗?

**Comment by cuiliang** [comment]
直接按方向键取消选择就可以了，效果是一样的

**Comment by cuiliang** [comment]
归档
