### ISSUE TITLE
编码状态,用户输入等窗体的滚动条无法被鼠标滚轮控制, 只能手工拖动.

### ISSUE THREAD

**Issue by leeyaunlong** [cuiliang/QuickPadCn#1393]
**描述BUG**
编码状态,用户输入等窗体的滚动条无法被鼠标滚轮控制, 只能手工拖动.

几乎所有quicker的窗体都不能鼠标滚动滚动条, 本次大改版外观前是没有问题的.
比如:
- quciker 设置页面 窗体
- 定义的动作编码页面
- 执行中的列表滚动条
- 执行中的 用户输入 页面

**环境信息:**
 - 操作系统版本：win10 2020H2 update
 - Quicker版本：v1.22.x

**Comment by cuiliang** [comment]
目前没有遇到类似问题，也暂无其他用户反馈。
如果有别的电脑，可以试试在别的电脑上有无类似现象。 或者退出其他所有软件判断一下是否有干扰。 Quicker里也检查一下是否在高级鼠标触发里使用了鼠标滚轮消息。

**Comment by leeyaunlong** [comment]
刚才查了一下, 应该是跟logictech的设置冲突
必须关闭logi的滚轮2项设置才行.
请考虑看能不能兼容一下logi这个滚轮设置, 
因为已经习惯了mac的自然滚动方式, 且用的logi的flow鼠标,会在win和mac上同时切换,滚轮方向希望保持一致. 

![image](https://user-images.githubusercontent.com/19405648/108576929-4c57b780-735a-11eb-8ed6-36076841872e.png)

**Comment by cuiliang** [comment]
> 刚才查了一下, 应该是跟logictech的设置冲突
> 必须关闭logi的滚轮2项设置才行.
> 请考虑看能不能兼容一下logi这个滚轮设置,
> 因为已经习惯了mac的自然滚动方式, 且用的logi的flow鼠标,会在win和mac上同时切换,滚轮方向希望保持一致.

Quicker 是使用的windows标准消息。Logi的这个驱动，不是很了解具体的原理。 
Logi的这个驱动不是很清楚具体的原理。
手里暂时也没有Logi的鼠标

**Comment by leeyaunlong** [comment]
> > 刚才查了一下, 应该是跟logictech的设置冲突
> > 必须关闭logi的滚轮2项设置才行.
> > 请考虑看能不能兼容一下logi这个滚轮设置,
> > 因为已经习惯了mac的自然滚动方式, 且用的logi的flow鼠标,会在win和mac上同时切换,滚轮方向希望保持一致.
> 
> Quicker 是使用的windows标准消息。Logi的这个驱动，不是很了解具体的原理。
> Logi的这个驱动不是很清楚具体的原理。
> 手里暂时也没有Logi的鼠标

那能否quicker 去全局控制 鼠标的滚轮, 可以设置成鼠标滚轮反向滚动?

**Comment by cuiliang** [comment]
可能是可以的，我等试试

**Comment by leeyaunlong** [comment]
> 可能是可以的，我等试试


我找到了一个解决办法, 在罗技鼠标的设置中可以对quicker单独设置鼠标滚轮的配置.
目前滚动条问题已经解决.

当然如果 quicker有个选项可以直接控制鼠标滚轮反向滚动, 也是quicker的新功能. 也可以吸引更多同时使用mac的用户.
