### ISSUE TITLE
用户选择 的 过滤器 匹配问题

### ISSUE THREAD

**Issue by leeyaunlong** [cuiliang/QuickPadCn#1394]
**描述BUG**
用户选择 的 过滤器 匹配问题
过滤器中输入字母可以过滤,但存在输入的单词后输入空格直接确认问题

**重现步骤**
1. 假设选项有
```
abc_foo
afoo bbc
afoo view
doo-12foo
```
2. 计划过滤后,需要选中或者手工辅助 第三条 "afoo view"
3. 过滤中输入 foo, 此时如果输入空格, quicker 会直接结束当前选择对话框, quicker使用第一条 "abc_foo"为选中的值,并执行下一步动作.

** 如果刚才的列表没有第一条"abc_foo", 则 输入 过滤条件foo加一个空格, 还可以继续过滤**

因此存在两个问题:
1. quicker如果遇到当前 过滤词 结尾匹配后,就直接完成了过滤逻辑
2. 如果存在多个结尾匹配,quicker 也不会给用户选择机会,直接已第一条结束.

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：v1.22.42

**Comment by cuiliang** [comment]
空格是作为提交处理的；可以使用上下键来选择选项。
对于英文单词，可以使用这样的方式（从单词的开始）
![image](https://user-images.githubusercontent.com/1972649/108579619-ca1fc100-7362-11eb-9744-8227264aac38.png)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.23.0 测试了一下，目前加空格不会提交，可以继续过滤。
