### ISSUE TITLE
简单修改增加多线程的可能性

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1395]
![image](https://user-images.githubusercontent.com/35998162/108590682-cf4f3100-739f-11eb-872e-d19d22bdff93.png)

**Comment by cuiliang** [comment]
好的

**Comment by cuiliang** [comment]
搞到一半，发现这个问题比想象的复杂。 
虽然等待可以超时，或者WaitAny只等待一个，但是其他进行中的任务并不会自动取消。它们仍然会继续运行，并且可能在后面的步骤里去更改变量内容，造成一定程度的混乱和不可预知性。

**Comment by cesaryuan** [comment]
> 搞到一半，发现这个问题比想象的复杂。
> 虽然等待可以超时，或者WaitAny只等待一个，但是其他进行中的任务并不会自动取消。它们仍然会继续运行，并且可能在后面的步骤里去更改变量内容，造成一定程度的混乱和不可预知性。

其他任务不会自动停止吗？那有点难搞哦

**Comment by cesaryuan** [comment]
@cuiliang   好像可以通过 CancellationTokenSource 来停止任务

**Comment by cuiliang** [comment]
> @cuiliang 好像可以通过 CancellationTokenSource 来停止任务

嗯，不过这个改动有点大，非常多的地方都要处理，包括模块里的，等再考察一下

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
