### ISSUE TITLE
在这里写需求摘要

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1396]
希望在为某个动作设置全局快捷键时可以将Delete设为快捷键
应用场景：
我在某些软件内按delete键删除东西时，它会弹出一个小框问我“是否要删除”，我一直都是选的“yes”，所以希望能借助Quicker将Delete键映射为delete+y

**Comment by cesaryuan** [comment]
可以通过扩展热键来实现

**Comment by cuiliang** [comment]
用扩展热键比较好
