### ISSUE TITLE
多字段表单增加按键输入类型

### ISSUE THREAD

**Issue by huasio** [cuiliang/QuickPadCn#1400]
**需求描述**
【多字段表单】目前没有按键输入类型，如若想给【动作右键菜单】设置快捷键或者【动作】运行过程中根据用户意愿可以自行操作按键来达到终止、启动某些逻辑走向。

**描述你想要的解决方案**
查看了功能库，仅有一个等待按键能略微满足需求，但是有遮罩层，并且这并不友好。

**Comment by cuiliang** [comment]
自己编写的动作，在等待按键模块里去除提示内容，应该就不会显示遮罩层了。

这个估计不是输入按键的问题，而是输入进去之后如何触发的问题。

**Comment by huasio** [comment]
> 自己编写的动作，在等待按键模块里去除提示内容，应该就不会显示遮罩层了。
> 
> 这个估计不是输入按键的问题，而是输入进去之后如何触发的问题。

我用另外方法实现了，就是扩展热键，可以实现动作内部快捷操作。

**Comment by cuiliang** [comment]
👍
