### ISSUE TITLE
信息形式转换的模块或动作

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1401]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

目前转换的动作太少了吧！我搜索了一下视频、音频、文本动作，基本上搜索结果，动作大致都看了。

这个文本转语音不错，但是好像只能生成一次，再选中文本生成语音就不行，必须把之前文件夹里的音频文件删掉才行。https://getquicker.net/sharedaction?code=6f01e0a7-51ff-425c-bdcf-08d78cdfb917
![image](https://user-images.githubusercontent.com/44609485/110111028-a17bda80-7dea-11eb-8d68-763e153d0f5c.png)

数量从多到少。文本【各种ocr、数学公式类动作，语言技术里的机器翻译，但是这个也是文本处理】>音频>视频
[阿里云AI平台-阿里云](https://ai.aliyun.com/?spm=5176.19720258.J_8058803260.41.5b392c4aVzUzBP)这个里面提供的能力，文本最多，等于说只用到了一个视觉图像里面的文本识别能力。图像→文本目前很方便，文本→音频动作太少了【知乎的生成视频功能好像没怎么优化了，以前时不时催盐选客服后来终于出了生成功能，降低了视频制作的门槛】

[Quick Cut: 轻量、强大、好用的音视频处理、下载工具！](https://gitee.com/haujet/QuickCut)之前尝试安装没搞成功。
我知道了 FFmpeg 这个神级开源工具，它的功能之强大、应用之广泛到惊掉了我的下巴！但它是个命令行工具
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

[API](http://mall.ckcest.cn/application/index_api.html?f=api) 这个中国工程知识中心有好多api，[特色资源 - 中国工程科技知识中心](http://mall.ckcest.cn/application/index.html?p=detailApi&i=2c91f70a6ec9b01b01723b22e7ae0023)、[特色资源 - 中国工程科技知识中心](http://mall.ckcest.cn/application/index.html?p=detailApi&i=2c91f8ba727aca57017321a1323101b2)、

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

这个pandoc项目应该怎么用好呢？
[jgm/pandoc at 2.11.4](https://github.com/jgm/pandoc/tree/2.11.4)
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
例子 前阵子搬运的 [第3→4次工业革命=水思维=信息的界限被打破、形式随意转换_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://www.bilibili.com/video/BV1iy4y1h7G3?p=4&spm_id_from=pageDriver)
=这个也是一个例子，可供参考

分享一个视频笔记学习神器『十行笔记』，一杯咖啡的时间就可以将视频自动生成 AI 笔记，点击链接加入并输入邀请码SHB3PYWZM可获得额外200咖啡豆！https://videoai.perspectivar.com/toExchange/SHB3PYWZM

2019 年事情又往前推进了一步。谷歌开始尝试在涉及 Youtube 的英文视频搜索中直接显示视频中段的相关内容。Engadget 的报道称，这意味着如果你要搜索某支曲子，搜索结果会显示某场包含这首曲子的音乐会，并且进度条直接拉到这首曲子的位置。
但这项技术目前仍然依赖上传者在视频中手动添加时间标记。并且这样的技术本质上仍然是将其他模态形式的信息转译成文本，并没有动摇传统搜索模式以文字输入为基础的基本形态。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
