### ISSUE TITLE
win10休眠后启动，自动运行动作失效

### ISSUE THREAD

**Issue by shkero** [cuiliang/QuickPadCn#1402]
**描述BUG**
win10休眠后启动，自动运行动作失效。

**重现步骤**
1.win10休眠。
2.启动之后，设置的自动运行动作都无效。定时运行，或者启动后运行的都没有运行。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.22.42

**附加信息**
休眠后启动运行动作不生效是正常的，但是定时运行动作应该生效。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.23.0版本中解决了。
