### ISSUE TITLE
建议改成像按键精灵一样的，代码段，所有代码可以一次性编写，而不是单独写，单独太累了

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1405]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
这个是个很大的工程，后期再考虑了。
目前你也可以写c#或其他脚本，放在quicker里运行。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
