### ISSUE TITLE
纯鼠标动作为什么不能录制呢

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1406]
纯鼠标动作为什么不能录制呢，就是不点击，只移动鼠标无法录制

**Comment by cuiliang** [comment]
因为移动过程会产生大量数据，通常没有具体的作用，所以这里有一个简化处理，只会记录点击位置，中间的移动过程会自动生成。

**Comment by cuiliang** [comment]
归档
