### ISSUE TITLE
问题摘要 用quicker选取繁体文字进行“用百度搜”时，百度结果非选中文字，而是乱码。

### ISSUE THREAD

**Issue by mileiniya7** [cuiliang/QuickPadCn#1407]
**描述BUG**
对bug的清晰简洁描述。
用quicker选取繁体文字进行“用百度搜”时，百度结果非选中文字，而是乱码。
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
参数URL编码一下试试。获取选中文本有一个编码后的输出。

**Comment by cuiliang** [comment]
这个是旧版组合动作，建议使用“快搜” https://getquicker.net/sharedaction?code=06bc3199-955a-41f7-138f-08d738459453
