### ISSUE TITLE
左键辅助失效

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1410]
有时候左键辅助会失效（按了没反应，只是输入了按的字母），已经遇到过好几次了， 重启quicker也没用

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/111422166-33f47600-8729-11eb-9af3-85888b1a7ad3.png)

出现的时候，打开这个，重置按下状态的按键。

**Comment by cuiliang** [comment]
解决了么？

**Comment by qiu-cool** [comment]
> 解决了么？
嗯嗯\(^o^)/
非常感谢，但是为什么会这样呢，因为总是遇到这样的情况每次都这样操作还是有点麻烦

**Comment by cuiliang** [comment]
可以开着那个窗口观察一下什么情况下会触发这个现象。
