### ISSUE TITLE
需要 mac版本，新的笔记本和系统希望能支持

### ISSUE THREAD

**Issue by 501175** [cuiliang/QuickPadCn#1411]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
精力所限，暂无考虑。

**Comment by 501175** [comment]
因为我是用win和mac的 之前考虑要入永久的 mac 没有也就意味着我win用的舒服了但是不能把工作流搬到mac 这个是阻止我买永久的最大问题，如果你这个全平台，那我会推荐每一人用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 需要 mac版本，新的笔记本和系统希望能支持 (#1411)





 
精力所限，暂无考虑。
