### ISSUE TITLE
Quicker安装向导提前结束

### ISSUE THREAD

**Issue by 657061450** [cuiliang/QuickPadCn#1412]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
在同意阅读协议，点击安装之后弹出

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/50694409/111427615-54283300-8731-11eb-8c2e-eb8a2ac303a8.png)

**环境信息:**
 - 操作系统版本：win10专业版 版本号:18363.1256
 - Quicker版本：1.11.8 X64

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
系统环境有些问题。
确保当前用户有管理员权限，然后先退出所有安全、管家之类的软件重试。
如果还不行，
可以查看一下Windows时间查看器里有没有什么相关消息。 
如果还不行，请百度一下报错信息看看。

**Comment by 657061450** [comment]
![image](https://user-images.githubusercontent.com/50694409/111430339-32c94600-8735-11eb-8d28-811e50262120.png)
百度找了~  这里提示说已经安装，但是我没安装~ 
与此同时，插件也提示未连接，尝试过换edge 也不行
![image](https://user-images.githubusercontent.com/50694409/111430505-715f0080-8735-11eb-9531-2bde5c36ab6c.png)

**Comment by cuiliang** [comment]
好像没有安装成功的。 可以再重现试试：
1. 停止360等所有安全、杀毒软件、管家软件
2. 确保当前用户有管理员权限
3. 如果之前有残余安装，从windows设置-》应用程序管理里卸载旧版
4. 重新安装。
如果还不行，就是您的电脑系统有啥问题了，我也没啥办法的，如果方便可以用官方镜像重新安装一遍系统。

**Comment by cuiliang** [comment]
https://docs.microsoft.com/zh-cn/troubleshoot/windows-server/application-management/msi-installation-error-1603
这里有一个1603错误的信息可以参考。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
