### ISSUE TITLE
开机无法自启动

### ISSUE THREAD

**Issue by tupodaodi** [cuiliang/QuickPadCn#1413]
无法将值Quicker写入注册表项\SOFTWARE\Microsoft\Windows\CurrentVersion\Run。请确认你有足够的权限访问注册表项，或者与你的技术人员联系。

**Comment by cuiliang** [comment]
如果是安装的时候：
确保当前用户有管理员权限；
彻底退出所有的管家、安全类软件；

如果已经安装完：
找到管家或安全软件里的启动管理功能，在里面允许quicker自动启动。

**Comment by tupodaodi** [comment]
已经是管理员组了，安全软件没有显示这软件的启动项，它一直都是禁用不了的。
昨晚无脑全部解禁启动项也没用啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 开机无法自启动 (#1413)





 
如果是安装的时候：
 确保当前用户有管理员权限；
 彻底退出所有的管家、安全类软件；
 
如果已经安装完：
 找到管家或安全软件里的启动管理功能，在里面允许quicker自动启动。

**Comment by cuiliang** [comment]
卸载安全软件试试能不能解决。 这个只能自己研究下了，自启动就是很简单的要写一个注册表，或者权限不够或者被拦截了。不会有别的原因了。

**Comment by cuiliang** [comment]
成功了么？ 这里也有一个可以参考试试：https://blog.csdn.net/qq_41216048/article/details/106231678

**Comment by tupodaodi** [comment]
谢谢你的参考，刚刚试过了，没有解决；昨天百度上的都试过了。
我决定还是手动启动好了（笑哭）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 开机无法自启动 (#1413)





 
成功了么？ 这里也有一个可以参考试试：https://blog.csdn.net/qq_41216048/article/details/106231678

**Comment by cuiliang** [comment]
是已经装上了但是开不了自启动嘛？ 等加我qq 197906，找时间远程我给远程看看。

**Comment by cuiliang** [comment]
联想电脑管家的问题。 
![image](https://user-images.githubusercontent.com/1972649/111765991-f8e87300-88df-11eb-9d8e-a3dffa62cd90.png)
