### ISSUE TITLE
微软出了 电源自动化桌面【Power Automate Desktop】希望quicker参考一下

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1414]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
这是原来的flow，以前试过一点，白给折腾了一阵时间之后，一无所获，最近大幅更新了，变成这个。

[Power Automate Desktop | Microsoft Power Automate](https://flow.microsoft.com/en-us/desktop/)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
RPA的微软方案
或许可以满足绝大部分quicker的需求。还是免费的
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/111728851-b5264700-88a8-11eb-9fd0-6c3422f5aa78.png)

![image](https://user-images.githubusercontent.com/44609485/111728911-d7b86000-88a8-11eb-9592-0595c12821e2.png)
和微软自家的可以结合的不错，复杂一点的还是要自己撸代码。
这玩意放到服务器上，进行简单处理，舒服了。

![image](https://user-images.githubusercontent.com/44609485/111756824-9db18300-88d5-11eb-86f9-38167956587d.png)

还是在一个群里知道的这个已经了更新的，之前尝试过，但是是全英文的，尝试以惨败结束【现在有中文方便多了】。

![image](https://user-images.githubusercontent.com/44609485/111756960-c46fb980-88d5-11eb-9451-9f3831631ce9.png)
[青源 LIVE 第 8 期 | 哈工大倪旻恒：多任务、多语言、多模态的预训练模型](https://hub.baai.ac.cn/activity/details/138)
发到智源社区的微信群了，但是还没动静。

**Comment by cuiliang** [comment]
厉害了！

**Comment by maodouzi123** [comment]
研究一下

**Comment by Mirrorgo** [comment]
这个不是免费的,但确实可以参考下
![image](https://user-images.githubusercontent.com/55936306/133254752-ab5d3f98-550d-40ec-8d1d-03283475b592.png)

有试用时间

还没用过,改天可以试试

**Comment by cuiliang** [comment]
归档
