### ISSUE TITLE
希望悬浮动作可以直接将动作方块拖到面板外完成悬浮，而不需要右键点悬浮。关闭悬浮动作按钮时可以在屏幕上设置一个回收区域，直接将这个悬浮动作块拖到相应区域即可

### ISSUE THREAD

**Issue by eliaszon** [cuiliang/QuickPadCn#1415]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
需求的场景：当我只想悬浮一两个动作时，解决的问题：悬浮单个动作不方便，关闭已悬浮的动作按钮不方便

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
如题：希望悬浮动作可以直接将动作方块拖到面板外完成悬浮，而不需要右键点悬浮。关闭悬浮动作按钮时可以在屏幕上设置一个回收区域，直接将这个悬浮动作块拖到相应区域即可

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
替代方案：Quickeruu有个”动作面板“的动作，可以做到直接拖入多个动作做到类悬浮，这是需要悬浮多个动作时比较快捷的一种方法，当我只需要悬浮一两个动作时，我更希望可以直接将动作方块直接拖到屏幕上完成悬浮，更方便、快捷、直观、符合操作习惯。同时在关闭悬浮动作按钮时可以在屏幕上设置一个回收小区域，直接将这个悬浮动作块拖到相应区域即可

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
先看下文档？里面有说明方法的
https://getquicker.net/Search?keyword=%E6%82%AC%E6%B5%AE%E6%8C%89%E9%92%AE
