### ISSUE TITLE
chrome，提示消息代理：未连接

### ISSUE THREAD

**Issue by vale8023** [cuiliang/QuickPadCn#1416]
**描述BUG**
通过chrome商城安装，启用权限一直提示消息代理：未连接

**重现步骤**
安装就有

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/35561410/112237983-bd9ec900-8c7e-11eb-8c63-f59de195ca82.png)
![image](https://user-images.githubusercontent.com/35561410/112238007-c68f9a80-8c7e-11eb-996c-c26488f10ed1.png)

**环境信息:**
 - 操作系统版本：mcOS 11.2.3 
 - Quicker版本：0.5.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
chrome更新到最新版。然后试试这个
![image](https://user-images.githubusercontent.com/1972649/112258963-63affa80-8ca2-11eb-9d41-e93c15cb055f.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
