### ISSUE TITLE
希望支持国产操作系统 例如麒麟

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1417]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
例如麒麟，当然其他的国产操作系统也行【反正支持一个主流的国产操作系统就行了】，打破美国佬的垄断。今天突然想到这个，就记录一下。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
[国产操作系统 - Magi](https://magi.com/search?q=%E5%9B%BD%E4%BA%A7%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F)
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
[国产操作系统浮沉录：半个世纪的演进史_微机](https://www.sohu.com/a/346847452_649045)

**Comment by cuiliang** [comment]
先不考虑了，国产都linux，运行不了.NET
