### ISSUE TITLE
APP连接的设置不了

### ISSUE THREAD

**Issue by zhangyu-ch** [cuiliang/QuickPadCn#1418]
**描述BUG**
APP连接设置并保存后，自动关闭

**重现步骤**
1.打开APP连接设置
2.保存设置
3.切换出去
4.再回到APP设置

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![bug展示](https://user-images.githubusercontent.com/66257271/112602960-301bc000-8dc9-11eb-87f1-7525bea91274.gif)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.23.7

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈，我研究一下。之前有这个现象么？

**Comment by zhangyu-ch** [comment]
> 感谢反馈，我研究一下。之前有这个现象么？

第一次用这个功能，不太清楚。

**Comment by cuiliang** [comment]
> > 感谢反馈，我研究一下。之前有这个现象么？
> 
> 第一次用这个功能，不太清楚。

重启Quicker之后仍然这样么？

**Comment by zhangyu-ch** [comment]
> > > 感谢反馈，我研究一下。之前有这个现象么？
> > 
> > 
> > 第一次用这个功能，不太清楚。
> 
> 重启 Quicker 之后仍然这样么？

重启了5次，突然可以了。

**Comment by cuiliang** [comment]
哦哦，好的，我再研究下。

**Comment by zhangyu-ch** [comment]
> 哦哦，好的，我再研究下。

对了，最后成功的一次唤出了Windows的防火墙设置，之前没有提醒设置防火墙权限。

**Comment by cuiliang** [comment]
开APP需要监听端口，应该会触发防火墙询问。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
