### ISSUE TITLE
使用从屏幕选择颜色、选择区域、选择窗口等选择工具时，自动最小化当前窗口。→：这个功能截图后图片点保存，但是没有文件，最新版本

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1420]
使用从屏幕选择颜色、选择区域、选择窗口等选择工具时，自动最小化当前窗口。

**Comment by cuiliang** [comment]
没有保存文件的问题在最新版已经修复了 https://getquicker.net/Help/Versions 
最小化已经加上待下一版。
