### ISSUE TITLE
移动到图片文件，选择图片时有个截图，选择保存到桌面，图片保存，确没有图片，找图也提示没有图片文件，桌面也没有文件

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1421]
移动到图片文件，选择图片时有个截图，选择保存到桌面，图片保存，确没有图片，找图也提示没有图片文件，桌面也没有文件

**Comment by cuiliang** [comment]
已经解决了。 https://getquicker.net/Help/Versions 下载 .8 版本。
