### ISSUE TITLE
扩展热键——操作类型 中没有“发送文本”这个选项，希望能增加

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1422]
背景：
“新建基础动作” 中有个操作叫“发送文本”，通过这个动作发送到电脑的文本不会受当前输入状态的影响，也不会先将文本复制到剪贴板后再粘贴，我很喜欢这个功能
但在“扩展热建”中没这个动作，要想发送文本只能用“键入文本”或“粘贴纯文本”，
“键入文本”会受当前输入状态的影响导致键入的文本大小写不对，
“粘贴纯文本”会将文本复制到剪贴板，而我在用ditto，将这些信息增加到剪贴板会影响我的操作，让我的剪贴板中存在了无意义的内容，
虽然我可以设置让“扩展热键”运行动作，动作中用“发送文本”，但这样太麻烦了，并且又增加了无意义的动作，所以想反馈看看能不能解决这个问题

**Comment by cuiliang** [comment]
可以做一个动作，接收参数，然后在扩展热键里调用这个动作，传递参数给动作。

**Comment by qiu-cool** [comment]
恕我菜鸡，能不能再说详细一点呢——我不太懂这个(><")....

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/112853336-5306e680-90df-11eb-8738-df98f8002de7.png)
扩展热键设置里给动作传递参数。 然后在动作里读取参数后随便用什么方法发送都可以了。

**Comment by qiu-cool** [comment]
实在抱歉，我仔细研读了你的话后还是没能搞定，你能不能完整的说一遍我具体要怎么操作呢 (/ω＼)

**Comment by qiu-cool** [comment]
“可以做一个动作，接收参数” 这要怎么做啊.......

**Comment by cuiliang** [comment]
https://getquicker.net/Search?keyword=%E5%8A%A8%E4%BD%9C+%E5%8F%82%E6%95%B0

**Comment by qiu-cool** [comment]
蟹蟹你  ≡[。。]≡

**Comment by qiu-cool** [comment]
终于搞定了，为后来人(如果有的话)留个笔记吧
1、先新建一个组合动作，只有一个步骤“发送文本到窗口”
2、内容选“动作命令参数”
3、方法选“模拟输入”
4、扩展热键中调用这个组合动作
剩下的按CL说的操作就好了

**Comment by cuiliang** [comment]
增加了一篇知识库文章 https://getquicker.net/KC/Kb/Article/882
