### ISSUE TITLE
“通过复制粘贴的方式”发送成文本后，能不能自动清除掉刚刚写入剪贴板的内容    

### ISSUE THREAD

**Issue by qiu-cool** [cuiliang/QuickPadCn#1423]
因为我在用ditto，剪贴板中会存放一些待用的内容，“通过复制粘贴的方式”发送成文本后，会往剪贴板里增加干扰信息，所以希望能自动清除刚刚写入剪贴板的内容

**Comment by cuiliang** [comment]
自动清除会产生别的问题。因为接收文本的程序从剪贴板读取的时间不是确定的，动作里清除可能会造成目标程序读取不到内容。
如果确实需要清除，在动作里增加一个“写入剪贴板”的模块，操作类型选择清空剪贴板。 不过这并不影响ditto里会记录内容，ditto也没法区分那内容是临时的还是要保留的。
