### ISSUE TITLE
WPS按键录制失灵

### ISSUE THREAD

**Issue by Jehaovah** [cuiliang/QuickPadCn#1424]
**描述BUG**
目前使用的版本是1.23.7，更新了新版本之后，wps中的动作录制就有点失灵了，比如alt加↓，通过模拟按键A或模拟按键B，都会出现失灵情况

**环境信息:**
 - 操作系统版本：windows10 64位
 - Quicker版本：1.23.7

**Comment by cuiliang** [comment]
这部分代码没有改过，应该和版本没有关系。
检查一下有没有什么地方使用了Alt键作为快捷键？输入法切换一下、还有试试把其它所有软件都关掉看看。

**Comment by cuiliang** [comment]
这个问题还存在么？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by Jehaovah** [comment]
> 先关了，如果还有问题，请再reopen

现在的情况是这样的：相同动作在Excel里面可以用，但wps就是无法实现。如果是手工按这些按键的话，在wps中也能正常实现功能。输入法切换到英文状态下，也还是存在这样的问题。

**Comment by cuiliang** [comment]
wps多少版本？

**Comment by Jehaovah** [comment]
> wps多少版本？

WPS版本为：个人版 11.1.0.10356- release

**Comment by cuiliang** [comment]
安装了wps最新版，试了几个模拟按键的操作，没有遇到问题。不过Alt+下这个我直接按也没效果，不清楚它的功能是啥？

**Comment by Jehaovah** [comment]
ctrl+方向键 应该也是失效的，这个功能是快速移动，比如ctrl+上(就是快速向上移动)。然后alt+下，主要在表格处于自动筛选状态，弹出下拉菜单。具体可以看下我录制的这个gif https://z3.ax1x.com/2021/04/09/cNLnte.gif

**Comment by cuiliang** [comment]
试了一下ctrl+↑，模拟出来往上走了一格，没有跳到最上面。 手按会跳最上面。
似乎WPS对按键有特殊的处理。
把按键改成分步骤模拟，并且按下Ctrl和↑之间增加一些延时就成功了。

我看看能不能加一个全局的选项，模拟按键时中间增加一点延迟。

https://user-images.githubusercontent.com/1972649/114162091-57db5e00-995b-11eb-90d0-af001ddd95ae.mp4

**Comment by Jehaovah** [comment]
嗯嗯，非常感谢解答，我去试试。赞

**Comment by cuiliang** [comment]
1.24.0 增加了一个设置，可以试试。
我这里测试改成1ms就可以正常触发功能了。
![image](https://user-images.githubusercontent.com/1972649/114572948-84b8a980-9caa-11eb-862f-7f2e2e57e6e5.png)

**Comment by Jehaovah** [comment]
成功了，非常感谢
