### ISSUE TITLE
更新动作时能不能不更改自定义的图标

### ISSUE THREAD

**Issue by yosiga0417** [cuiliang/QuickPadCn#1425]
**需求描述**
更新动作时能不能不更改自定义的图标

**描述你想要的解决方案**
增加一个更新选项，更新不更改已经自定义的图标

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/113125215-f58ea900-9248-11eb-980d-11746f091ff3.png)
下载快速通道版本，设置第一页最下面。
