### ISSUE TITLE
删除的动作页和动作重复回来

### ISSUE THREAD

**Issue by LJpLJ** [cuiliang/QuickPadCn#1426]
**描述BUG**
1.三方应用以及上面动作页和动作会重复回来
2.通用、全局页面由于不能删除，但是动作页和动作会重复回来
大概重现了有10次了，每次删除了过段时间就会复现

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/1617882/113432625-4997ba00-9410-11eb-9ea0-22f37610dc59.png)
删除前
![image](https://user-images.githubusercontent.com/1617882/113432869-bb700380-9410-11eb-909f-d3a0da54a5bf.png)
删除后
**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：最近半年的版本陆续都有

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
hi， 有几个电脑同步？ 请把账号email发我197906@qq邮箱我检查一下后台分析一下看看.

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  1.24.1解决了此问题
