### ISSUE TITLE
增加配置分享

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#1427]
目前的动作启动方式已经很多了，然而能够分享的配置只有扩展热键，希望能增加其他配置方式的分享，或许将来能够推出quicker的默认配置包，引导用户高效利用quicker。

**Comment by guoranjun2** [comment]
> 目前的动作启动方式已经很多了，然而能够分享的配置只有扩展热键，希望能增加其他配置方式的分享，或许将来能够推出quicker的默认配置包，引导用户高效利用quicker。
纠正：左键辅助、和高级鼠标触发，这两个无法分享（高级鼠标触发，分享方式不太一致）

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
后来大都增加了导出功能。因为很多是调用动作，分享的意义有些不大。
