### ISSUE TITLE
推送到电脑bug，用户没有连接

### ISSUE THREAD

**Issue by ruandongcheng** [cuiliang/QuickPadCn#1428]
**描述BUG**
按网页提示操作，但是一直显示用户没有连接，不知为何

**重现步骤**
1.按网页提示手机扫码
2.客户端也开启了推送服务

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![Screenshot_20210406_161501_com microsoft emmx](https://user-images.githubusercontent.com/60881081/113680651-ad153680-96f3-11eb-8e7b-d77eb74d040f.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
客户端多少版本？ 要更新到快速通道版本才行

**Comment by ruandongcheng** [comment]
我用的是1.11.8，刚才更新到快速通道版本就可以用了，谢谢大佬答复！

**Comment by ruandongcheng** [comment]
我用的是1.11.8，刚才更新到快速通道版本就可以正常用了，谢谢大佬答复！

发件人: ***@***.***>
发送时间: 2021年4月6日 17:04
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cuiliang/Quicker] 推送到电脑bug，用户没有连接 (#1428)


客户端多少版本？ 要更新到快速通道版本才行

―
