### ISSUE TITLE
【想法】 在推送页面增加一个粘贴按钮

### ISSUE THREAD

**Issue by ruandongcheng** [cuiliang/QuickPadCn#1430]
**需求描述**
原本的操作一共需要四个步骤：点击输入框，点击剪贴板，粘贴，发送。稍微有点繁琐。不知道能不能在手机推送页面增加一个粘贴按钮，直接读取剪贴板写入到上面的输入框中，如下图所示。
我真的很喜欢这个功能，手机电脑联动很方便，希望可以帮助改进这个功能，谢谢崔亮大大

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
![image](https://user-images.githubusercontent.com/60881081/114208776-727bfa00-9990-11eb-9842-3fe227f54bc8.png)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
加了一个。
