### ISSUE TITLE
[Questions][提问] 关于 Quicker 的运行权限问题

### ISSUE THREAD

**Issue by janjin123** [cuiliang/QuickPadCn#1432]
从旧版本更新后，发现被 Quicker 启动的程序不再主动请求 Windows 管理员权限，例如 Everything 。
同时发现，被启动的程序 似乎 自动享有管理员权限。

请问开发者这是 Feature 吗？
如果是，可否有选项可以关闭这种特性，
因为不希望被唤起的任意程序在用户完全不知觉间就 都 享有了管理员权限。

以上

**Comment by cuiliang** [comment]
没有这个功能，如果有的话Windows就有BUG了。 
如果Quicker没有管理员权限，它启动的程序是不会有的。Quicker虽然可以提权，但是仅限和别的程序交互（比如模拟按键消息到管理员权限的窗口）。不会有把别的软件提权的功能。

检查一下是不是关闭了Windows的UAC设置看看。

**Comment by janjin123** [comment]
收到回复，我去检查下自己的系统配置。

致谢

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
