### ISSUE TITLE
①我的账号为何不能在讨论区提问？②如何关闭提示消息？

### ISSUE THREAD

**Issue by SheenkhunWong** [cuiliang/QuickPadCn#1433]
**描述BUG**
①我的账号为何不能在讨论区提问？
是因为我提问了一次关于v2rayNG的问题吗？我又不知道那是违规词，能不能给出一些违规关键词提示？不允许提问也请发信提醒ok？

②如何关闭提示消息？
鼠标放在图标上总是会有提示，如下图红色框：
![image](https://user-images.githubusercontent.com/51428752/114662737-ca698680-9d2b-11eb-8da5-c4e8fd2f16f6.png)
基本上每次截图都会把这个提示截进去：
![image](https://user-images.githubusercontent.com/51428752/114662807-e705be80-9d2b-11eb-8964-28aef662c244.png)
很影响使用体验和效率。请问如何关闭这种提示？

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.23.19

**Comment by cuiliang** [comment]
在国内的网站不要发敏感内容，这是每个人都知道的。
至于哪些内容敏感，要问国家主管部门。
对于一个不太清楚会不会发送敏感内容的用户，我也不敢让他在讨论区发言的，万一出点事，网站就完蛋了，请你理解。不是店大欺客，是店小怕事。

是不是可以在讨论区发言和专业版也没有关系，免费用户发言也没收费不是。

这个提示会在鼠标停留2秒钟左右开始出现，可以弹出后立即截图或者移开鼠标后截图。

**Comment by cuiliang** [comment]
如果已经了解了发帖原则，可以email我取消限制，因为限制的时候我也没看是哪个账号，不好定位。

**Comment by SheenkhunWong** [comment]
谢谢，抱歉我的语气可能有点冲，因为实在是被这个提示给搞烦了，在设置里面来来回回找了挺久，然后在讨论区又求助无门。

【这个提示会在鼠标停留2秒钟左右开始出现，可以弹出后立即截图或者移开鼠标后截图。】可以在设置中给个开关么？感觉既有名称又有提示，有点儿画蛇添足。

**Comment by cuiliang** [comment]
额，这个我主要是感觉不是很必要，因为只有停住2秒才会出提示。你大概是什么样的操作过程呢？可以录个屏看看。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
