### ISSUE TITLE
单独动作可以绑定电脑吗，有时几台电脑需要同样的动作，但是需要单独电脑修改一点点，运行时的快捷键就会运行不对的那个，这样每次运行都要改一下，适合当前电脑的动作的快捷键

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1436]
单独动作可以绑定电脑吗，有时几台电脑需要同样的动作，但是需要单独电脑修改一点点，运行时的快捷键就会运行不对的那个，这样每次运行都要改一下，（适合当前电脑的动作）   的快捷键

**Comment by cuiliang** [comment]
同步的数据都是一样的。
用组合动作，获取当前电脑主机名，然后根据主机名执行不同的操作。
专业版也可以把动作页绑定到主机名（主机名不匹配的时候自动隐藏）。
