### ISSUE TITLE
截图后拖动图片至扩展屏幕，系统蓝屏重启

### ISSUE THREAD

**Issue by Mr-Gabriel** [cuiliang/QuickPadCn#1437]
**描述BUG**
截图后拖动图片至扩展屏幕，导致系统蓝屏重启，本机环境可多次复现

**重现步骤**
1.点击截图动作，截取任意图片
2.将图片由笔记本屏幕拖动至扩展屏幕，图片闪烁几次后系统蓝屏重启

**Bug重现操作录像**
https://b23.tv/A93CL8

**环境信息:**
截图动作：https://getquicker.net/sharedaction?code=9bfc34fb-b7f7-40bd-6d0c-08d6c304e16e
Quicker版本：1.23.19
操作系统：Windows10家庭中文版 20H2
笔记本硬件信息：联想拯救者R7000 2020
扩展屏幕：联想 LS2033WA

**Comment by cuiliang** [comment]
本地测试没有能复现问题。可以试试bios里关闭内置显卡，直接使用独立显卡。如果是双显卡，切换屏幕的时候dpi转换可能会额外的处理。

**Comment by Mr-Gabriel** [comment]
> 本地测试没有能复现问题。可以试试bios里关闭内置显卡，直接使用独立显卡。如果是双显卡，切换屏幕的时候dpi转换可能会额外的处理。

我这边重新测试了下面几种情况：
1.只用独立显卡，还是存在同样问题
![2-禁用集成显卡-有问题](https://user-images.githubusercontent.com/49147819/116176651-13b2d080-a745-11eb-9731-3722547d2d9e.png)

2.禁用集成显卡驱动，不再出现蓝屏
![1-禁用集成显卡驱动-无问题](https://user-images.githubusercontent.com/49147819/116177296-224db780-a746-11eb-8390-e8518e37b029.png)

3.禁用独立显卡驱动，此时无法使用扩展屏幕

另外，我这边测试时候发现一个新问题：
在**扩展屏幕**截图，截图时提示框的文字显示不全，而且会有拖影的情况。将图片由扩展屏拖动至笔记本屏幕，也会蓝屏。
**操作录像**：https://b23.tv/U0TbId

**Comment by cuiliang** [comment]
这个主要是和dpi切换有关系，两个屏幕dpi不一致，在窗口移动到不同的屏幕上时，dpi变化了。如果又存在两个显卡的切换，情况就会更复杂。可能windows或者显卡驱动在处理这种情况的时候有些问题。
我通常时3个4k显示器一起使用没有遇到过类似问题，即使将它们调整到不同的dpi，也不会有问题。
我等找R7000测试看看。

**Comment by cuiliang** [comment]
再次确认下，两个屏幕的分辨率和缩放都设置的多少来着？

**Comment by Mr-Gabriel** [comment]
> 再次确认下，两个屏幕的分辨率和缩放都设置的多少来着？

笔记本屏幕：分辨率：1920 x 1080    缩放：125%
扩展屏幕： 分辨率：1600 x 900    缩放：100%

都是系统的推荐配置

![1](https://user-images.githubusercontent.com/49147819/116179565-2a0f5b00-a74a-11eb-9d40-f3d41b82d036.png)
![2](https://user-images.githubusercontent.com/49147819/116179581-2ed40f00-a74a-11eb-833c-5b938f965ba5.png)

**Comment by Mr-Gabriel** [comment]
> 这个主要是和dpi切换有关系，两个屏幕dpi不一致，在窗口移动到不同的屏幕上时，dpi变化了。如果又存在两个显卡的切换，情况就会更复杂。可能windows或者显卡驱动在处理这种情况的时候有些问题。
> 我通常时3个4k显示器一起使用没有遇到过类似问题，即使将它们调整到不同的dpi，也不会有问题。
> 我等找R7000测试看看。

在扩展屏幕截图，提示框文字会有拖影也是因为dpi的问题吗？
我还发现一个有意思的地方，只要拖动到扩展屏幕的部分不超过整个图片的1/2就不会蓝屏。
大佬辛苦了orz

**Comment by cuiliang** [comment]
拖动残影应该也是和dpi有关，还需重现诊断一下。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 
改了一版。1.24.5 试下看看

**Comment by Mr-Gabriel** [comment]
> https://getquicker.net/Help/Versions
> 改了一版。1.24.5 试下看看

我试了下，已经没问题了。大佬🐂🍺
👍👍👍👍👍👍👍👍👍

**Comment by cuiliang** [comment]
好，之前版本在dpi切换以后有一个重新计算尺寸的过程，可能重新计算尺寸后又回到了前一个屏幕，又重新计算尺寸。。。😂
去掉这个过程了

**Comment by cuiliang** [comment]
这个版本有个bug，请升级到.7版本。
