### ISSUE TITLE
手机远程连接PC后，弹出面板分辨率异常

### ISSUE THREAD

**Issue by MichaelHan20** [cuiliang/QuickPadCn#1438]
**描述**
手机通过软件 Remote Desktop 远程连接计算机，断开后登录本地计算机时出现弹出面板分辨率异常，面板能正常弹出，但尺寸非常大。退出 Quicker 程序再启动，故障消失。

**环境**
Quicker 版本：1.23.19
计算机系统：Windows 10 专业版
手机：华为 Mate 20 Pro
Microsoft Remote Desktop 版本：10.0.9.1122

**Comment by cuiliang** [comment]
使用微软RDClient（iOS）测试，没有出现类似问题。win10版本：
![image](https://user-images.githubusercontent.com/1972649/115998347-65f6d300-a619-11eb-8abe-e0ace8ff074e.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by MichaelHan20** [comment]
异常复现：计算机开机后先使用RDClient（Android）登录，等待Quicker启动后退出，然后从计算机登录系统。
![image](https://user-images.githubusercontent.com/58125794/117242649-4016cd00-ae68-11eb-8254-df20cf148f54.png)

![Snipaste_2021-05-06_12-33-15](https://user-images.githubusercontent.com/58125794/117242463-e7dfcb00-ae67-11eb-96bf-e68cfb2693ce.png)

**Comment by cuiliang** [comment]
@MichaelHan20 测试没出现类似现象。
客户端RD Client, Pixel2
不知道是不是windows版本里的bug，可以试试更新windows到最新版。
