### ISSUE TITLE
分屏情况下将quicker截图从A屏幕拖拽至B屏幕 系统崩溃蓝屏

### ISSUE THREAD

**Issue by B14ckNo0b** [cuiliang/QuickPadCn#1439]
两个显示器情况下将quicker截图从A屏幕拖拽至B屏幕 系统崩溃蓝屏
系统：win 10 专业版 版本18363
CPU：I5 - 4210M
8G内存
quicker版本1.23.19

**Comment by cuiliang** [comment]
建议先升级Win10到目前主流的20H2版本测试。如果双显卡，先关闭内置显卡，改成独立显卡模式测试。
因为Quicker是基于.Net的托管代码，不直接和硬件交互。蓝屏问题都是系统底层或显卡驱动的问题。

**Comment by cuiliang** [comment]
#1437

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions
改了一版。1.24.5 试下看看
