### ISSUE TITLE
新版步骤编辑界面建议汇总

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#1440]
- [x] 字体模糊
![image](https://user-images.githubusercontent.com/35998162/116333331-d6fade00-a805-11eb-9c33-a7c4ce43b4e6.png)
- [x] 边框粗一点
![image](https://user-images.githubusercontent.com/35998162/116333353-e11cdc80-a805-11eb-8ffc-c5312ab77abe.png)
- [x] 遮挡
 ![image](https://user-images.githubusercontent.com/35998162/116390899-1995d800-a851-11eb-9106-052eae0d1e41.png)

**Comment by cuiliang** [comment]
整理issues
