### ISSUE TITLE
软件使用记录

### ISSUE THREAD

**Issue by qidanges** [cuiliang/QuickPadCn#1441]
**需求描述**
现阶段各种软件功能强大，但是使用繁琐、功能不容易查找、快捷键过多不容易记录。

**描述你想要的解决方案**
针对指定软件进行记录笔记，每打开一个软件其中打开的笔记都不同，让用户可以针对当前软件记录其功能与临时记录数据

**描述您考虑过的替代方案**
在电脑中设置指定目录，保存txt文件，针对不同软件打开不同txt文件

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可以用组合动作得到当前进程信息。
使用这个信息你可以关联到一个特定文件，启动该动作的时候，判断文件在不在，在的话就打开，不在的话就复制模板文件创建一个然后打开。
