### ISSUE TITLE
左键辅助增加黑名单

### ISSUE THREAD

**Issue by wlioi** [cuiliang/QuickPadCn#1442]
比如画画的时候,会出现设置为左键辅助的按键复制粘贴删除,贴边动作等功能,
如果用软件黑名单,轮盘就不能用了

改进建议:
如果可以在黑名单设置分别对应的功能:
左键辅助,扩展热键,鼠标手势等,是更好的方案

**Comment by cuiliang** [comment]
“ 画画的时候,会出现设置为左键辅助的按键复制粘贴删除,贴边动作等功能,”  这个是怎么样被触发的呢？

**Comment by wlioi** [comment]
> “ 画画的时候,会出现设置为左键辅助的按键复制粘贴删除,贴边动作等功能,” 这个是怎么样被触发的呢？

比如橡皮e,画笔按下上下滑动调节橡皮大小.
而在左键辅助里,我把左键e设为了窗口上贴边的动作

**Comment by cuiliang** [comment]
不太熟悉这方面啊，这个具体的操作过程是什么样呢？ 画笔相当于左键，e是在画笔移动的时候按下的么？

**Comment by wlioi** [comment]
是的,而且调节e的时候要不断的按左键好几次

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 发了一版1.24.8，试下看看。

**Comment by wlioi** [comment]
> https://getquicker.net/Help/Versions 发了一版1.24.8，试下看看。
这样很好好用了,感谢
