### ISSUE TITLE
使用扩展热键B语法触发大写锁，大写锁闪烁一下，状态不变

### ISSUE THREAD

**Issue by BiHong-Yang** [cuiliang/QuickPadCn#1443]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.设立引导键"`"下"H"键的触发指令，指令内容为B语法输入大写锁{CAPSLOCK}
2.使用该扩展热键，大写锁闪烁一下，依然保持原先状态。

**相关截图**
![image](https://user-images.githubusercontent.com/61420495/116849271-0902aa80-ac21-11eb-8524-cda21da02504.png)

**环境信息:**
 - 操作系统版本：Windows 10 家庭中文版 20H2
 - Quicker版本：1.24.7

**Comment by cuiliang** [comment]
这个是要发送什么内容呢？ Caps不是一个可以输入的键。在这里是没法实现按下状态的。

**Comment by cuiliang** [comment]
无法实现此需求。 如需进一步帮助，请详细说明所要达到的最终目的。
