### ISSUE TITLE
未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by SheenkhunWong** [cuiliang/QuickPadCn#1446]
**描述BUG**
动作【动作面板】（https://getquicker.net/Sharedaction?code=d6a48e4e-4afb-4346-6dee-08d887b8882d）
无法使用，总是弹出“内部问题：未将对象引用设置到对象的实例”。
没学过C#，搞不懂出了啥问题。我在官网无法评论、求助。

**重现步骤**
1. 弹出Quicker面板
2. 点击【动作面板】动作

**相关截图**
![image](https://user-images.githubusercontent.com/51428752/117527946-49d43800-b002-11eb-93b9-cf1175bc6529.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.24.7

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
删除一下动作状态，再启动动作试试。

**Comment by SheenkhunWong** [comment]
删除并且重新安装过动作了，也删除过quicker.db并重启Quicker了，还是老样子

**Comment by cuiliang** [comment]
quicker试试也更新到最新版， https://getquicker.net/Help/Versions

**Comment by SheenkhunWong** [comment]
quicker升级到最新版本，动作也更新到最新版本，还是不行
![quicker20210508](https://user-images.githubusercontent.com/51428752/117531934-91b18a00-b017-11eb-944e-211af267e18c.gif)

**Comment by cuiliang** [comment]
已可以正常留言，请务必文明理性发言。不要发表敏感内容。
这个问题看起来不是很有思路。

**Comment by SheenkhunWong** [comment]
好的，谢谢

**Comment by cuiliang** [comment]
https://getquicker.net/QA/Question/3323
