### ISSUE TITLE
开启quicker后，影响win10多窗口的”当我调整某个贴靠窗口的大小时,也调整任何相邻贴靠窗口的大小”

### ISSUE THREAD

**Issue by Leexiaolong** [cuiliang/QuickPadCn#1447]
开启quicker后，当我调整某个贴靠窗口的大小时,也调整任何相邻贴靠窗口的大小，这个无法正常使用了。关闭后就可以了，望作者修复

**Comment by cuiliang** [comment]
不太了解这个功能，能否动图演示一下？

**Comment by cuiliang** [comment]
如果你是说两个窗口并排全屏的时候，托中间位置可以同时调整两边窗口的大小，应该和quicker没有关系。

**Comment by Leexiaolong** [comment]
是的，就是并排时两个窗口这个。应该是有关系，我自己关了quicker就可以了，打开就不行了。不知是否是有冲突。
![打开quicker](https://user-images.githubusercontent.com/24725706/117656602-227c9700-b1cb-11eb-98c3-c6c2bb2cd7b0.gif)
![关闭quicker](https://user-images.githubusercontent.com/24725706/117656608-23adc400-b1cb-11eb-8884-16b55435f077.gif)

**Comment by cuiliang** [comment]
![test](https://user-images.githubusercontent.com/1972649/117660300-9456df80-b1cf-11eb-8e9d-7e4ac6a0ac53.gif)

**Comment by cuiliang** [comment]
Windows详细版本是多少？

**Comment by Leexiaolong** [comment]
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎3/‎13/‎周六
操作系统内部版本	19042.928
体验	Windows Feature Experience Pack 120.2212.551.0

**Comment by Leexiaolong** [comment]
之前没想到是quicker的原因，我是最近刚开始用quicker，发现双开窗口无法自动调整，尝试关闭quicker后确实就可以了。开着quicker大概率是不行，极偶尔才能。但是看你的好像没问题0.0

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/117672539-85c2f500-b1dc-11eb-8901-c9c9329e5ba3.png)
我也是这个版本。

**Comment by Leexiaolong** [comment]
咦，这就搞不懂了，我公司和家里两个笔记本都不行。关了quicker重启刚开始还可以，一会就不行了。。有没有可能是鼠标手势的原因呢？我开了鼠标手势

**Comment by cuiliang** [comment]
可能确实和手势有关，我研究下

**Comment by Leexiaolong** [comment]
大概率是了，我关了鼠标手势，重启quicker后就可以了，应该是鼠标手势有影响。不过影响不大，这个就是需要手动调节两个窗口，不能一个随着另一个变。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 你好，可以试试1.24.12版本看看有没有改善。

**Comment by cuiliang** [comment]
试过新版了么？ 我这里测试似乎没问题了
先关了，如果还有问题，请再reopen

**Comment by Leexiaolong** [comment]
> https://getquicker.net/Help/Versions你好，可以试试1.24.12版本看看有没有改善。

不好意思，前几天忙，今天试了下没问题了，棒，完全可以了
