### ISSUE TITLE
辅助功能鼠标左右键复制粘贴

### ISSUE THREAD

**Issue by LuckyGirlLjy** [cuiliang/QuickPadCn#1448]
之前的版本具有一个辅助功能，即鼠标左右键同时按下实现复制粘贴！这个功能很方便，但是新版本没有了！请恢复以该功能！

**Comment by cuiliang** [comment]
不仅有，而且更强大。
https://getquicker.net/Search?keyword=%E5%B7%A6%E9%94%AE%E8%BE%85%E5%8A%A9
