### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by shkero** [cuiliang/QuickPadCn#1449]
**描述BUG**
左键辅助修改后不生效。
我之前设定的左键辅助，现在把设定删除或者修改都不生效，操作后还是最早定义的效果。
不确定是哪次更新后产生的。

**环境信息:**
 - 操作系统版本：win10 
 - Quicker版本：1.24.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
是保存不进去么？ 
可以试试退出账号重新登录一下（建议先备份一下quicker.db文件）：
![image](https://user-images.githubusercontent.com/1972649/118423628-0b243900-b6f8-11eb-8ffa-4c840a984c03.png)

**Comment by shkero** [comment]
> 是保存不进去么？
> 可以试试退出账号重新登录一下（建议先备份一下quicker.db文件）：
> ![image](https://user-images.githubusercontent.com/1972649/118423628-0b243900-b6f8-11eb-8ffa-4c840a984c03.png)

退出账号重新登录一下，试过了还是一样。
我设定了一个Y键的左键辅助，现在把这个设置删除。按Y键还是有左键辅助的效果。

**Comment by cuiliang** [comment]
配置项还在列表里么？有没有在场景设置里添加过操作？还不行的话远程一下，我qq 197906
![image](https://user-images.githubusercontent.com/1972649/118424450-de712100-b6f9-11eb-9ccc-f8276de54a4e.png)

**Comment by shkero** [comment]
场景设置里有设置。抱歉，把这个给忘了。😭😭😭
