### ISSUE TITLE
quicker图标缺失

### ISSUE THREAD

**Issue by ElegantSatori** [cuiliang/QuickPadCn#1450]
![image](https://user-images.githubusercontent.com/66898076/118750891-f203bf80-b892-11eb-9885-3a30829b7a59.png)

**Comment by cuiliang** [comment]
您的Windows有点问题了。可能是用工具优化或修改系统设置造成的。
可以参考这些试试：
https://getquicker.net/QA/Question/2683

之前是否正常？什么时候开始的呢？

**Comment by ElegantSatori** [comment]
> 您的Windows有点问题了。可能是用工具优化或修改系统设置造成的。
> 可以参考这些试试：
> https://getquicker.net/QA/Question/2683
> 
> 之前是否正常？什么时候开始的呢？

是在换用另外一台电脑时出现的，在原来的电脑上图标显示是正常的，软件重装过也没有用。你刚才提到的方法我试了，感谢，但也还是不行，请问还有没有其他解决方法。

**Comment by cuiliang** [comment]
其他就不清楚了，可以试试修复一下windows
https://support.microsoft.com/zh-cn/topic/%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E6%96%87%E4%BB%B6%E6%A3%80%E6%9F%A5%E5%99%A8%E5%B7%A5%E5%85%B7%E4%BF%AE%E5%A4%8D%E4%B8%A2%E5%A4%B1%E6%88%96%E6%8D%9F%E5%9D%8F%E7%9A%84%E7%B3%BB%E7%BB%9F%E6%96%87%E4%BB%B6-79aa86cb-ca52-166a-92a3-966e85d4094e

**Comment by ElegantSatori** [comment]
> 其他就不清楚了，可以试试修复一下windows
> https://support.microsoft.com/zh-cn/topic/%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E6%96%87%E4%BB%B6%E6%A3%80%E6%9F%A5%E5%99%A8%E5%B7%A5%E5%85%B7%E4%BF%AE%E5%A4%8D%E4%B8%A2%E5%A4%B1%E6%88%96%E6%8D%9F%E5%9D%8F%E7%9A%84%E7%B3%BB%E7%BB%9F%E6%96%87%E4%BB%B6-79aa86cb-ca52-166a-92a3-966e85d4094e

嗯嗯，好的，谢谢，我试试这个方法是否可行

**Comment by cuiliang** [comment]
@ElegantSatori 后来解决了么？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
