### ISSUE TITLE
用户选择的选项定义图标无效

### ISSUE THREAD

**Issue by shkero** [cuiliang/QuickPadCn#1452]
**描述BUG**
用户选择的选项定义图标无效，直接显示原本的内容。但同样的定义复制到右键菜单却正常。

**相关截图**
![image](https://user-images.githubusercontent.com/20251994/119104764-376cec00-ba4f-11eb-8768-e9552ffbe9b9.png)
![image](https://user-images.githubusercontent.com/20251994/119104826-4ce21600-ba4f-11eb-8e77-efa0fbc7fc68.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.24.16

**Comment by cuiliang** [comment]
`[图标]标题|值`
使用图标时，后面的`|值`不可缺少。

**Comment by shkero** [comment]
好的

> `[图标]标题|值`
> 使用图标时，后面的`|值`不可缺少。

好的。文档这里建议说明一下。
![image](https://user-images.githubusercontent.com/20251994/119106141-9da63e80-ba50-11eb-9f68-d3d5335a6473.png)

**Comment by cuiliang** [comment]
感谢提醒，文档已修改。
