### ISSUE TITLE
软件对按键录制的实现是不是有一些问题

### ISSUE THREAD

**Issue by zhangyu-ch** [cuiliang/QuickPadCn#1453]
**描述BUG**
在AxMath中，我简单编写了一个动作，方便编写公式。但是好像会有问题。在到了alt+F4（关闭软件窗口）这一步的时候，总是会跳出“用户自定义符号”这个界面，导致无法退出，出现bug，复现率极高几乎99%。但是手动实现这一过程则没有任何问题。经过我在用户手册中查询，发现ctrl+F4也是一个快捷键，这个快捷键就是调出用户自定义符号的。所以我怀疑是不是quicker在实现alt+F4时有一些bug？

**相关截图**
![image](https://user-images.githubusercontent.com/66257271/119259469-0b916800-bc01-11eb-8376-32e8f1e2d8ce.png)

**环境信息:**
 - 操作系统版本：win10 1909
 - Quicker版本：1.24.15

**Comment by zhangyu-ch** [comment]
![12](https://user-images.githubusercontent.com/66257271/119259745-3f20c200-bc02-11eb-9fe5-6a6983e5b6f6.gif)

**Comment by cuiliang** [comment]
用Quicker模拟Alt+F4，当然也是调用自定义符号了。 这个符合预期呀。
你可以试试改成模拟Esc来关闭窗口。

**Comment by zhangyu-ch** [comment]
> 用Quicker模拟Alt+F4，当然也是调用自定义符号了。 这个符合预期呀。
> 你可以试试改成模拟Esc来关闭窗口。

不符合预期啊，您没看清，那个快捷键是ctrl+F4，模拟的是alt+F4，一个是alt，一个是ctrl。用手动键盘操作就是没有问题的。 @cuiliang

**Comment by zhangyu-ch** [comment]
请教一下怎么通过模拟esc关闭窗口呢。对关闭窗口只会鼠标点击，还是看了您分享的动作，才知道alt+F4的。

**Comment by cuiliang** [comment]
oo, 看错了。 
在别的窗口模拟Alt+F4能不能关闭窗口呢？
还有试试手动在那个窗口Alt+F4能不能关闭窗口，Esc能不能关闭窗口。 如果都不行的话，可以用鼠标操作，移动到相对于窗口右上角的位置后，点击鼠标左键。

**Comment by zhangyu-ch** [comment]
/(ㄒoㄒ)/~~
手动一点问题都没有。别的窗口也没啥问题。

**Comment by cuiliang** [comment]
可以用这个工具试下，在模拟Alt+F4的时候有ctrl被按下的记录不。

[键盘显示CastOW 2.0.2.5 中文绿色汉化版.exe.zip](https://github.com/cuiliang/Quicker/files/6528080/CastOW.2.0.2.5.exe.zip)

还有一个可以测试的地方，把这里改成1：
![image](https://user-images.githubusercontent.com/1972649/119261181-dab53100-bc08-11eb-9248-119d33ffd125.png)

**Comment by zhangyu-ch** [comment]
谢谢大佬，把那个按键间隔改了就ok了。
我当初过设置的时候还是潦草了一点。（不过这个是不是可以改成默认有1ms的间隔）

**Comment by cuiliang** [comment]
嗯，我也在考虑这个问题。按理说不应该存在这样的现象，可能是底层的bug😂
