### ISSUE TITLE
启动quicker后会导致拖动任何窗口（界面）的速度很慢，跟不上鼠标速度

### ISSUE THREAD

**Issue by Jzhnakui** [cuiliang/QuickPadCn#1455]
**描述BUG**
打开quicker后没啥，只要使用任何一个动作后，就马上会导致我光标想要移动任何窗口的时候，移动的窗口速度很慢，跟不上鼠标速度。肯定是quicker导致的，我关掉quicker马上就恢复正常了。也尝试换鼠标，更新驱动，删除quicker的所有动作，都不行。只要一关掉quicker就好了。

**重现步骤**
这个重现步骤的话
第一步：开quicker
第二步：任意使用一个动作

**相关截图**
如题

**环境信息:**
 - 操作系统版本：win10
 - 1.23.19还有Quick-1.3.4，还有我试了很多版本，试了7个版本吧。。。。

**附加信息**
quicker和我绑定太深了，我不想卸掉，但是已经浪费我2个小时了，我真的无法解决这个问题，而且重启没用啊，，，啊啊啊啊啊！

**Comment by cuiliang** [comment]
WIndows详细版本号是多少？之前有用预览版Windows出现显示面板的时候拖动其它窗口慢的问题。
另外看看慢的时候cpu有没有变化，最好录个屏。

**Comment by Jzhnakui** [comment]
> WIndows详细版本号是多少？之前有用预览版Windows出现显示面板的时候拖动其它窗口慢的问题。
> 另外看看慢的时候cpu有没有变化，最好录个屏。

回复 CL : 20天前是正常的，我一直没有排查出来是quicker是因为我一直在忙着写毕业论文，在写论文呢的过程中，拖拽窗口的时候就发生这种现象。
当慢的时候，桌面窗口管理器（dwm.exe；C:\Windows\System32）会突然增加20-40％的cpu占用，以及会增加10％的GPU占用率。

我已经录好视频了，放在了b站，这是链接，麻烦大佬看一下：

quicker导致鼠标拖拽的软件界面移动速度跟不上真实的鼠标移动速度_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili

https://www.bilibili.com/video/BV1T5411g7bZ

**Comment by tshanli** [comment]
属于Windows 10的传统问题了，详细请参考该推特：https://twitter.com/ADeltaXForce/status/1354155322101870594?s=20

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by Jzhnakui** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    okok ,作者辛苦问题呢还是没解决, 但是我准备等一波win11, 年底发布的时候估计这个UI的问题会好吧
    
        
        

        
    

    在2021年6月29日 ***@***.***> 写道： 




先关了，如果还有问题，请再reopen

**Comment by cuiliang** [comment]
建议先升级win10到最新版。 如果电脑是双显卡的笔记本，在bios里关闭CPU内置显卡。
