### ISSUE TITLE
运行过程任务栏闪动（文件资源管理器重启），任务栏图标错乱

### ISSUE THREAD

**Issue by Empyrealty** [cuiliang/QuickPadCn#1456]
**描述BUG**
对bug的清晰简洁描述。
运行过程任务栏闪动（文件资源管理器重启），任务栏图标错乱
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不是很明白，请录屏看一下具体现象。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
