### ISSUE TITLE
窗口操作移动窗口，宽度和高度改成-1，代表不改变窗口大小移动就完美了，不然一定要重新获取原来大小，比较麻烦

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1457]
![image](https://user-images.githubusercontent.com/80558299/120886366-23fd7b80-c620-11eb-94ef-ed505a943ae4.png)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.24.28版已支持。
