### ISSUE TITLE
从工业革命角度看quicker 可能会有帮助的一些书

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1458]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
一直在搜集的，或者说看过一部分的 一些关于工业革命的书

科学革命→技术革命→工程革命

[元科学【Metascience】研讨会系列=科学过程研究的新兴领域【2019年】_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1CU4y1b79f)
[第0→？次工业革命=科学革命的结构_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1gy4y1s7gM/)

[什么是技术革命_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1sK411c77p)
[第？次工业革命=技术革命与周期特征_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1n84y1F7ia)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
技术的本质 布莱恩 阿瑟写的非常有意思，可供参考。【微信读书就可以看】【上传不了epub的附件】
还有 科技想要什么  凯文凯利的一些书写的也不错。有点读不动

技术的本质尤其好！！！ 第2章 组合和结构 为什么要模块化
将技术的构件模块化可以更好地预防不可预知的变动，同时还简化了设计过程。但只有当模块被反复使用且使用的次数足够多时，才值得付出代价将技术分割为功能单元。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
《特斯拉模式：从丰田主义到特斯拉主义，埃隆 · 马斯克的工业颠覆》
《工业4.0：第四次工业革命全景图》【日】尾木藏人
《特斯拉模式：从丰田主义到特斯拉主义，埃隆 · 马斯克的工业颠覆》
无边界的新工业革命 乌尔里希·森德勒
《智能化浪潮(正在爆发的第四次工业革命)》 张江健
《迎接第四次工业革命》 沈阳
《第四次工业革命》Klaus Schwab
《第四次工业革命》《日经商务周刊》
《第四次工业革命转型的力量》作者: 克劳斯·施瓦布
《第四次工业革命 打造创新路线图》作者: 克劳斯·施瓦布
《第四次革命》作者: [意]卢西亚诺•弗洛里迪（Luciano Floridi）著
《第四次工业革命》作者: [日]藤原洋
《第四次工业革命》作者: 李克 朱新月
《第四次革命》作者: 扎克•林奇
《从互联到新工业革命》刘云浩
《工业4.0大革命》水木然
《工业4.0》乌尔里希•森德勒

科学革命与工业革命 (英)约翰·德斯蒙德·贝尔纳(J.D.Bernal), 伍况甫, 彭家礼
中国的文化大革命与工业组织 夏尔•贝特兰
后疫情时代：大重构 施瓦布
硅谷革命：成就苹果公司的疯狂往事 [美] 安迪·赫兹菲尔德 (Andy Hertzfeld)
微革命:微小的创新颠覆世界 金错刀
混合式学习：用颠覆式创新推动教育革命 （美）霍恩（Horn, M.B） & 斯泰克（Staker, H.） 著
新工业革命（精编图文版）Peter Marsh作者: 彼得·马什
工业革命：历史、理论与诠释 陈文佳 严鹏
政治秩序与政治衰败：从工业革命到民主全球化 弗朗西斯·福山
伟大的中国工业革命：“发展政治经济学”一般原理批判纲要
中国制造2025：产业互联网开启新工业革命 夏妍娜 赵胜
第三次工业革命 杰里米里夫金
数字李生体：第四次工业革命的通用目的技术 胡权
创客：新工业革命 克里斯-安德森
智能化浪潮：正在爆发的第四次工业革命 张江健
能源工业革命：全球能源互联网简史 陈富强
3D打印：正在到来的工业革命（第2版)Christopher Barnatt 克里斯多夫
迎面而来：从人类文明发展看第三次工业革命 黎雨 李新
从互联到新工业革命 刘云浩
新工业革命：理论逻辑与战略视野 黄群慧 贺俊等
英国史新探：工业革命的新视角 钱乘旦 高岱主编
马克思主义箴言：资本来到人间·工业革命 王立柱 张伟
智能爆发：新工业革命与新产品创造浪潮 杨青峰
工业4.0：智能制造与治理革命 陈潭等
一本书读懂工业4.0革命 海天电商金融研究中心
未来制造：人工智能与工业互联网驱动的制造范式革命 杨青峰
工业物联网革命：企业战略转型的思考与实践 柯建东
未来呼啸而来 彼得·戴曼迪斯史蒂芬科特勒
科学：无尽的前沿 范内瓦·布什拉什-D.霍尔特
百年流水线：一部工业技术进步史 大卫E. 奈(David E. Nye)
工业4.0时代的盈利模式  韦康博
从雇佣到自由人：新经济模式下的分工3.0革命 
统治史 早期现代政府和西方的突破——从民族国家到工业革命 萨缪尔•E•芬纳
工业人的未来 彼得·德鲁克
通往工业革命的漫长道路:全球视野下的欧洲经济 扬·卢滕·范赞登, 隋福民中国的经济革命：二十世纪的乡村工业 [日]顾琳 著 王玉茹 张玮 李进霞 译
工业文明的社会问题 乔治·埃尔顿·梅奥
智能革命：迎接人工智能时代的社会、经济与文化变革 李彦宏
数字孪生体：第四次工业革命的通用目的技术
后工业社会的来临 丹尼尔贝尔
未来制造：人工智能与工业互联网驱动的制造范式革命
第四次革命 卢西亚诺弗洛里迪 王文革
第二次机器革命
低成本创新 彭志强
YC陆奇：Al本质与创业创新 奇绩创坛 【被下架】
工业革命（1760-1830）（英）T.S.阿什顿著
通往工业革命的漫长道路作者：[荷]扬·卢滕范赞登
工业革命前的欧洲社会与经济 作者：[意]卡洛M.奇波拉
天才透纳：工业革命的描绘者 The Genius of Turner: Painting the Industrial Revolution (2013)  导演: 克莱尔·比温
第三次工业革命与当代中国作者: 周洪宇 / 徐莉
第五次工业革命 作者 段诗闻
工业革命的科技奇迹 作者：吕宁
第三次工业革命与中国选择 作者：芮明杰
英国工业革命中的资本投资和社会机制 徐滨
新工业革命的中国战略（国务院发展研究中心研究丛书

**Comment by RainYang-RY** [comment]
与软件无关，更接近广告。建议删除。

**Comment by kunpeng9** [comment]
思维像2极管一样，极端工具人？ @wz1765

**Comment by cuiliang** [comment]
不太能理解。很久没有时间看书了😂
