### ISSUE TITLE
登录Quicker时的代理问题

### ISSUE THREAD

**Issue by HiIcy** [cuiliang/QuickPadCn#1462]
在公司内网，走的全局代理
chrome上是可以的
但是client上，使用系统代理无法登录
> 无法登录！发送请求时出错

尝试按照https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/kd3cf2ex(v=vs.90)?redirectedfrom=MSDN

修改代理还是不行

**Comment by cuiliang** [comment]
关于代理的问题，我了解的也不是很深入。全局代理的时候IE能浏览网页么？ 
如果IE也正常，quicker开启系统代理选项理论上应该是可以的。
另外可以试试能不能ping通api.getquicker.net ，观察一下是不是稳定。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
