### ISSUE TITLE
希望软件可以识别“长按中键”与“短按中键”

### ISSUE THREAD

**Issue by jierme** [cuiliang/QuickPadCn#1463]
**需求描述**
目前使用的鼠标是MX Master3，默认长按中键在部分绘图软件中是平移功能。但是Quicker只能识别按下中键。

**描述你想要的解决方案**
能够让我设置，短按中键时调出Quicker面板，长按中键则不调出。

**描述您考虑过的替代方案**
无。

 **其他上下文**
![image](https://user-images.githubusercontent.com/57268924/122145811-865c4480-ce88-11eb-8ad0-f540f093869a.png)

**Comment by cuiliang** [comment]
Quicker1.24.37 + 版本。
在高级鼠标触发里设置。

![image](https://user-images.githubusercontent.com/1972649/122150607-9f68f380-ce90-11eb-99c6-08424985467b.png)

可以复制这段文字，在高级鼠标触发设置右上角点粘贴按钮。
```
[{"Id":"025121da-a7c0-4449-a05d-1fc536e2b618","MouseActionType":3,"ControlKey":null,"AdornKey":null,"MouseButton":4194304,"DisableInFullScreen":false,"TriggerDistance":0,"Location":0,"LimitOnPrimaryScreen":false,"BlackList":[],"WhiteList":[],"Description":"点击中键","IsEnabled":true,"Operation":4,"TriggerActionWhenMouseUp":false,"LastEditTimeUtc":null,"DebounceMs":0,"ActionType":11,"Data":"quicker_show_main_win_auto_activate"}]
```
