### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by Faceky** [cuiliang/QuickPadCn#1465]
**描述BUG**![image](https://user-images.githubusercontent.com/68587814/122694794-22af8e00-d271-11eb-9f11-2dd5efbe3fbc.png)对bug的清晰简洁描述。
文本截图翻译，写入剪切板失败，写入剪切板内容为空

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
删掉动作重新安装一下，之前的ocr 账号失效了。
