### ISSUE TITLE
quicker面板control+右键会在屏幕留下彩色圆圈

### ISSUE THREAD

**Issue by zydhhh** [cuiliang/QuickPadCn#1466]
在弹出的quicker面板，按住control键，在面板的任意部位右键，会在屏幕留下一个彩色的圆圈，且这个圆圈会浮在最顶层。当把鼠标移动到这个圆圈上，会弹出刚刚右键时的面板（一开始唤出quicker面板分为上下两部分，默认全局和默认，如果右键时鼠标在上面的默认全局部分，这个圆圈就会弹出默认全局面板；下半部分同理），这个圆圈是bug吗？还是什么功能？如果是功能该怎么消除这个圈圈呢

![image](https://user-images.githubusercontent.com/25688118/122748982-60d39e80-d2bf-11eb-876f-407be964c86f.png)
![image](https://user-images.githubusercontent.com/25688118/122749014-6cbf6080-d2bf-11eb-8636-2d3004bb8af7.png)

 - 操作系统版本：Windows 10 20H2
 - Quicker版本：1.23.19

**Comment by cuiliang** [comment]
https://getquicker.net/Search?keyword=%E6%82%AC%E6%B5%AE%E5%8A%A8%E4%BD%9C%E9%A1%B5

**Comment by cuiliang** [comment]
另外也可以在托盘图标的右键菜单里一键清除所有悬浮。
