### ISSUE TITLE
多屏移动截屏贴图的图片时触发蓝屏

### ISSUE THREAD

**Issue by FLAGLORD** [cuiliang/QuickPadCn#1467]
**描述BUG**
多屏时，移动Quicker自带截屏功能中的贴屏图片从主显示器到副显示器会触发蓝屏

**重现步骤**
1.Quicker 截图并贴屏到桌面
2.移动贴屏图片从主显示器到副显示器
3. 副显示器屏幕闪动，并在 1 s后触发蓝屏

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.23.19

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
你好，此问题应该已经修复。请升级到最新版测试一下看看。

**Comment by FLAGLORD** [comment]
测试了一下，确实是解决了，感谢
