### ISSUE TITLE
更新到1.24.34后，截图OCR（91d18611-a525-48c7-b744-0613645aa8d6）在点击“截图”后不能及时弹出截图页面

### ISSUE THREAD

**Issue by whittes** [cuiliang/QuickPadCn#1468]

**Comment by cuiliang** [comment]
检查是不是开启了第三方截图的快捷键。如果开启了，取消掉它才会使用系统内置截图。

![image](https://user-images.githubusercontent.com/1972649/123103250-63bdc300-d468-11eb-9b97-9ad3e52fd9ce.png)

**Comment by cuiliang** [comment]
解决了么？

**Comment by whittes** [comment]
并没有开启
目前的话比反馈的时候好一点，在点击“截图”后有大约1-2秒的间隙，然后弹出“混合取图”页面，反馈的时候是不会弹出。

**Comment by cuiliang** [comment]
"混合取图”页面 是啥样截个图看看？ @whittes

**Comment by whittes** [comment]
"混合取图"又变回去了，就是截图设置成混合取图，然后运行动作，然后屏幕中下部出现一个页面，上面有“截图”和“提交”两个按钮，点了截图之后，什么都不发生

**Comment by cuiliang** [comment]
"混合取图" quicker里没用这个功能的，能截个图么？

**Comment by whittes** [comment]
![1](https://user-images.githubusercontent.com/17637563/125151469-f18ff280-e178-11eb-82ec-122afc958be0.png)

这个是插件，到这里反馈的原因是，在更新到1.24.34前，是能正常用的，更新到1.24.34后，就不正常了
