### ISSUE TITLE
虚拟机VMware下弹出菜单无法屏蔽

### ISSUE THREAD

**Issue by JianbangWu** [cuiliang/QuickPadCn#1469]
**需求描述**
我用虚拟机的时候用鼠标右键总是会弹出quicker的菜单，且无法添加屏蔽

**描述你想要的解决方案**
针对VMware优化一下吧，作者大大

**描述您考虑过的替代方案**
无

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/60055566/123216004-aa103200-d4fb-11eb-99f5-4110dae737e6.png)

**Comment by cuiliang** [comment]
如果quicker不是最新版，先升级到最新版。然后添加黑名单
![image](https://user-images.githubusercontent.com/1972649/123216257-eb084680-d4fb-11eb-8061-cb15a133f26a.png)

**Comment by JianbangWu** [comment]
已升级到最新版本 1.24.34 
但仍然存在右键菜单装在虚拟机窗口被调用，已根据您的描述进行修改并添加黑名单
![image](https://user-images.githubusercontent.com/60055566/123578217-ea2b2980-d807-11eb-863e-8e62a83ccd11.png)
![image](https://user-images.githubusercontent.com/60055566/123578268-075ff800-d808-11eb-982b-fc85bee121e4.png)
可以看到，我在虚拟机的vscode中用右键时，虚拟机中的右键菜单和Quicker的弹出面板被一并开启了

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/123578441-72a9ca00-d808-11eb-99da-7eb54b4346bf.png)
你的这个里咋没有这个呢，已经添加过了么？
点击这里有效果么？
![image](https://user-images.githubusercontent.com/1972649/123578493-9240f280-d808-11eb-8acb-5f5bca176c50.png)

**Comment by JianbangWu** [comment]
我又确认了一下，无法识别的应用这个按钮出现了，点击后问题得到解决，感谢

**Comment by cuiliang** [comment]
好
