### ISSUE TITLE
软件登陆账号后无法退出登录

### ISSUE THREAD

**Issue by bbs526** [cuiliang/QuickPadCn#1470]
账号登陆错了，使用了微信扫码登陆，登陆后，右键只有退出选项，没有退出登录选项。导致无法切换账号。
软件版本：1.24.34
系统：win10 64位
![image](https://user-images.githubusercontent.com/48689272/123646342-b37dff00-d859-11eb-9b50-e8de2d011fd8.png)

**Comment by cuiliang** [comment]
在面板窗口的菜单里。
https://getquicker.net/KC/Manual/Doc/reg#0QV7i
