### ISSUE TITLE
文件夹内无法呼出

### ISSUE THREAD

**Issue by saber0126** [cuiliang/QuickPadCn#1471]
**描述BUG**
更新后文件夹内无法呼出quciker
桌面上依然可以，但是文件夹内无法呼出

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果设置了任务栏自动隐藏，检查是不是开启了全屏禁用。
然后检查一下黑名单设置。

**Comment by cuiliang** [comment]
解决了么？

**Comment by saber0126** [comment]
解决了，不知道更新后为什么进了黑名单，导致界面出不来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月1日(周四) 下午3:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiliang/Quicker] 文件夹内无法呼出 (#1471)




 
解决了么？

**Comment by cuiliang** [comment]
好
