### ISSUE TITLE
在使用贴图功能时，快捷面板依然在桌面显示

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1472]
**描述BUG**
如图，呼出面板，点击贴图工具，但是这个时候面板没有自动隐藏，请问这个是bug还是要怎样设置呢？因为这是偶尔现象，有的时候面板会自动隐藏。

**重现步骤**
1.
2.

**相关截图**
![image_4](https://user-images.githubusercontent.com/57392772/124078495-7d6b9580-da7a-11eb-9ee2-f58f5837f3e7.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
截图通常会自动得到向前一些时间的图像。可以在动作里截图之前的步骤上加上150ms的延迟解决。
如果使用快捷键或别的方式触发，就不需要加延迟了。
![image](https://user-images.githubusercontent.com/1972649/124079004-2dd99980-da7b-11eb-9455-a1a7d7752a7a.png)

**Comment by baileichao** [comment]
已解决，非常感谢！
