### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by whutBing** [cuiliang/QuickPadCn#1473]
**描述BUG**
window11自启动失效

**重现步骤**
1.
2.

**相关截图**
![image](https://user-images.githubusercontent.com/56247427/124212097-ea396b00-db20-11eb-8b42-72d3e1b28b7c.png)
![image](https://user-images.githubusercontent.com/56247427/124212140-02a98580-db21-11eb-8d0b-d47ab478c370.png)

**环境信息:**
 - 操作系统版本：
 - windows 11
 - Quicker版本：
 - 1.24.34

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Windows11的BUG，等微软修复。
