### ISSUE TITLE
窗口界面控制不支持第二屏幕

### ISSUE THREAD

**Issue by HawnHan** [cuiliang/QuickPadCn#1474]
**描述BUG**
窗口界面控制操作不支持第二屏幕(该屏幕为竖屏，设置在主屏幕(横屏)左边，竖屏在系统中标识为1。主屏幕标识为2)，在执行之后鼠标移动到第二屏幕的边缘执行，导致无法继续后续步骤。但在主屏幕时可正常执行。

**重现步骤**
1.模拟按键A(录入)——LeftAlt+L,V(打开Microsoft Visual Basic for Applications宏编辑器)
2.等待时间300ms(等待窗口打开)
3.窗口界面控制(FlaUI)
![窗口界面控制参数(FlaUI)](https://user-images.githubusercontent.com/38370450/124372667-9b293c80-dcbe-11eb-8bee-446ef7d76494.jpg)
4.等待时间100ms(等待下级菜单)
5.窗口界面控制(FlaUI)
![5窗口界面控制参数(FlaUI)](https://user-images.githubusercontent.com/38370450/124372692-ce6bcb80-dcbe-11eb-8b4b-033166b7f0b3.jpg)

**相关截图**
![屏幕排列Screen alignment](https://user-images.githubusercontent.com/38370450/124372647-6b7a3480-dcbe-11eb-8aa0-4bedf9332a75.jpg)
![系统版本System info](https://user-images.githubusercontent.com/38370450/124372658-80ef5e80-dcbe-11eb-8762-f344f6ed685a.jpg)
![步骤](https://user-images.githubusercontent.com/38370450/124372697-d4fa4300-dcbe-11eb-8038-b1ec37968f92.jpg)

**环境信息:**
 - 操作系统版本：Windows 10 专业版 21H1 19043.1052
 - Quicker版本：2021-06-01

**附加信息**
主副屏作为当前常见的配置，不应当出现不适配的情况，希望尽快有解决办法，quicker深得我心。

**Comment by cuiliang** [comment]
另外的那个界面控制模块可以么？

**Comment by HawnHan** [comment]
都是一样的结果，第一次尝试的就是不带FlaUI的，失败了

**Comment by cuiliang** [comment]
今天测试了几个窗口，似乎都没有问题。
![image](https://user-images.githubusercontent.com/1972649/125870927-462e410b-b115-4453-848d-c7fc3f02d11a.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/125870967-84a6774e-d265-43ac-a127-6f39604604be.png)

**Comment by HawnHan** [comment]
好的，我再试试，看是不是我这边有问题

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
