### ISSUE TITLE
适配更多的鼠标按键

### ISSUE THREAD

**Issue by Gladtbam** [cuiliang/QuickPadCn#1476]
**需求描述**
能否适配更多的鼠标按键，像罗技G502这类鼠标，除了常见的左右键，滚轮和G4(X1)，G5(X2)，还有G7，G8，G9等键，这些键位在不玩游戏时很少用到，用来触发Quicker非常合适

 **其他上下文**
众多在非游戏时很少用到的按键
![image](https://user-images.githubusercontent.com/49943258/124612265-c40b2680-dea4-11eb-9c6d-744755dbdc08.png)

**Comment by cuiliang** [comment]
Windows本身只支持5个键，其它都需要鼠标自身的驱动处理。
可以在logi驱动里把多余的按键映射成快捷键来触发动作。

**Comment by Gladtbam** [comment]
原来如此，谢谢
