### ISSUE TITLE
弹出面板修改保存后自动恢复默认

### ISSUE THREAD

**Issue by jiahhuang** [cuiliang/QuickPadCn#1477]
**描述BUG**
弹出画面鼠标方式改为长按右键不弹出。鼠标确认应用设置以后，并没有设置成功；重新回到此设置页面，依然显示弹出方式为长按右键。

**重现步骤**
1.Quicker设置
2.弹出画面
3.去除勾选’长按右键‘
4.应用设置

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows 10.0.19043 Build 19043

 - Quicker版本：1.24.34

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
有一个bug因为本地没法复现所以一直没有解决。
可以退出账号重新登录一下通常就可以正常了。
![image](https://user-images.githubusercontent.com/1972649/124840391-7209f400-dfbd-11eb-8530-4c974513ad0f.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
