### ISSUE TITLE
Quicker搜索建议

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1478]
1.希望Quicker搜索框的宽度可以自定义，如搜索文件时，文件名很长，无法查看完整的文件名；
2.希望可以自定义默认的搜索模式，如设置打开Quicker搜索，输入关键词即可以搜索文件，而不是每次都要输入“f+空格+关键字”；
3.希望加入搜索文件内容的功能，everything只能按标题搜索文件；

**Comment by cuiliang** [comment]
感谢建议。后期增加一些设置。
不过搜索内容估计困难，需要有相应的索引

**Comment by cesaryuan** [comment]
关于第二条可以试试「智搜」动作

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
