### ISSUE TITLE
创建文本窗口时报错

### ISSUE THREAD

**Issue by lovelystrange** [cuiliang/QuickPadCn#1479]
*描述BUG**
  “朱近野的万能卡片”动作在升级quicker后，执行新建文本窗口步骤时报错
  
  **重现步骤**
  1. 在vivaldi浏览器（或其他浏览器）下选中文本，运行该动作的选单1
  2.出现错误提示：
  无法初始化等待窗口。您的电脑可能缺少文字转语音组件。”-864“不是属性”Width“的有效值。
  
  **相关截图**
  如果适用，请添加屏幕截图以帮助解释您的问题。
  
  
  **环境信息:**
   - 操作系统版本：Win10 家庭版
   - Quicker版本：1.25.5
  
  
  **附加信息**
  报错后，脚本不会停止。
重要补充：在双显示器竖屏4k分辨率工况下，浏览器窗口位于显示器1（左）出现此bug的几率远高于显示器2(右）

**Comment by cuiliang** [comment]
在动作上右键，调试运行一下。然后调试文件作为附件上传一下看看。
另外也请把动作网址发一下，库里似乎搜不到这个动作。

**Comment by lovelystrange** [comment]
> 在动作上右键，调试运行一下。然后调试文件作为附件上传一下看看。
> 另外也请把动作网址发一下，库里似乎搜不到这个动作。

发生故障时，动作无法自动结束，因此无法看到调试log。请问应该怎么处理。
https://getquicker.net/Sharedaction?code=68f66829-bb4c-4cb3-a05f-08d886bcc6c5&fromMyShare=true

**Comment by cuiliang** [comment]
先试下在动作上右键，清除状态和修饰，还不行的话远程看下。
![image](https://user-images.githubusercontent.com/1972649/125371119-a95c1480-e3b2-11eb-879c-124800b857b3.png)

另外看看计算机系统最近有没有做什么硬件或者配置、系统的变更。

**Comment by lovelystrange** [comment]
系统最近可能做了一次Win10更新安装，除此之外没有变化。
刚才重新清理了动作状态，再运行一次后，制定了”工作目录“，并在主菜单选择”查看卡片“，没有成功执行，但是获得了log文件，其中也如上所述的报错信息。
[quicker_朱近野的万能卡片_113508-154_log.zip](https://github.com/cuiliang/Quicker/files/6810077/quicker_._113508-154_log.zip)

**Comment by lovelystrange** [comment]
同样地，在显示器2上面做这个操作，就一切正常。

**Comment by cuiliang** [comment]
> 同样地，在显示器2上面做这个操作，就一切正常。

大概知道原因了，我处理一下试试。

**Comment by lovelystrange** [comment]
> > 同样地，在显示器2上面做这个操作，就一切正常。
> 
> 大概知道原因了，我处理一下试试。

赞一个！

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 
试下1.25.7 版本看看

**Comment by lovelystrange** [comment]
> https://getquicker.net/Help/Versions
> 试下1.25.7 版本看看

  完美解决。感谢！
