### ISSUE TITLE
希望Quicker搜索中可以集成更多搜索工具

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1480]
如题，当前Quicker中可以调用everything进行文件搜索，希望可以加入更多搜索工具，如AnyTxt Searcher等

**Comment by cuiliang** [comment]
需要对方有接口才行。 目前everything提供了SDK可以调用。 
另外也可以通过动作来实现搜索功能：参考 https://getquicker.net/KC/Help/Doc/search-adv
