### ISSUE TITLE
关于技术的本质以及如何度量技术复杂性？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1481]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
今天突然想到一篇以前读到过的文章，我也看不太懂，不过或许会有帮助也说不定
[创新技术如何识别？通过结构多样性度量技术及其影响 - 知乎](https://zhuanlan.zhihu.com/p/128041547)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
虽然对技术的本体追问难有结果，但大多数学者基本都同意，技术本身是一个层级结构，它来自更低一级技术的组合。
对复杂经济学者布莱恩 · 阿瑟来说，最元初技术是对自然现象及其效应的捕获 [1] 。因此将技术视为某种复杂网络，甚至不存在还原过度，真正要解决的只是如何对网络结构进行有效度量。然而，这却是一个很难的问题。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
https://knower.info/s/bc31a4a6
![image](https://user-images.githubusercontent.com/44609485/125620308-7cf9a9af-70aa-4259-95d0-a76712399946.png)
我觉得目前只有这个大小的可视化，类似于xyploer的这个，还不够，或许有更大的优化空间。

另外这个也可供参考 科学网络
[我们分析了100多年来的8.8万篇《自然》论文，这是它们构成的世界](https://mp.weixin.qq.com/s?__biz=MzAwNTAyMDY0MQ==&mid=2652565187&idx=1&sn=a76cd52cef4507ec0a696f54cab68ba3&chksm=80cd404db7bac95b74e3705a3c019ee07b34af506541f168b485be253567d9bc7b0a0a496f97&token=281513620&lang=zh_CN&scene=156&subscene=10001&clicktime=1618901639&enterid=1618901639&ascene=0&devicetype=android-28&version=280002c1&nettype=ctnet&abtest_cookie=AAACAA%3D%3D&exportkey=AfB3Y8drnssLo68%2B4OtSgEs%3D&pass_ticket=uFHz9iLAdzp9ki%2BSQdX7eDUgsHqQt6QBok0EecDIvMLfWUfNV2y3CrHmuzSqZC%2FX&wx_header=1)

[A network of science: 150 years of Nature papers - YouTube](https://www.youtube.com/watch?v=GW4s58u8PZo&t=10s)

**Comment by cuiliang** [comment]
归档
