### ISSUE TITLE
新增竖排字识别且翻译

### ISSUE THREAD

**Issue by ryousein** [cuiliang/QuickPadCn#1482]

**Comment by marcusxx** [comment]
截图OCR是支持的：https://getquicker.net/sharedaction?code=ba82e11a-f845-4ca3-44ee-08d690b5076c
![image](https://user-images.githubusercontent.com/48142413/126068127-dd6a7093-455d-4361-9932-d92e46d76b45.png)

**Comment by ryousein** [comment]
是否可以新增一个功能，识别竖排文字后，选择从左或是从右排列。目前识别出竖排文字，默认从左排列。
