### ISSUE TITLE
关于mysql连接与操作的功能

### ISSUE THREAD

**Issue by 1404276788** [cuiliang/QuickPadCn#1484]
**需求描述**
有时候工作的时候需要测试批量接口请求，或者网站文章关键词组合的功能，一些数据都存放在数据库中，每次手动去数据库中取出数据整理，操作完后，还需要写入数据，非常麻烦，希望Quicker能支持mysql的操作功能

**描述你想要的解决方案**
1. 能够支持填写要操作的数据库
2. 支持 增、删、改、查等操作
3. 查询的数据能够方便的进行遍历，处理，比如json格式

**描述您考虑过的替代方案**
使用其他程序开发一个接口，通过Quicker发送请求来执行需要的mysql操作，但是这样需要安装程序，每次都要去启动程序才能访问接口。

**Comment by cuiliang** [comment]
mysql需要大量的库，会造成软件体积扩大，而且大部分人是用不到的，所以暂时不考虑。 
如果需要可以自己使用c#模块引入相关dll后使用。
可以参考下这个子程序 https://getquicker.net/SubProgram?id=0396cfbd-b023-4c72-b3e8-08d93d2ba26c

**Comment by cuiliang** [comment]
后来有了数据库连接功能。
