### ISSUE TITLE
文本截取能否添加以特定文本做参考的部分截取

### ISSUE THREAD

**Issue by Ghd-0802** [cuiliang/QuickPadCn#1485]
**需求描述**
在易语言模块中有个很适合新手使用的文本截取功能

**描述你想要的解决方案**
  示例文本: a = "我是一段示例文本来演示功能"

  取文本左边(被取的文本,参照的文本,取的长度)
     示例: 取文本左边(a,"示例文本",2) 
     输出:"一段"
  取文本右边(被取的文本,参照的文本,取的长度)
     示例: 取文本右边(a,"示例文本",2) 
     输出:"来演"
  取文本中间((被取的文本,参照文本的左边,参照文本的右边)
     示例: 取文本中间(a,"示例","演示") 
     输出:"文本来"

![image](https://user-images.githubusercontent.com/38886687/127794617-ad13156a-881c-4591-9c91-2aa65501b173.png)

**Comment by cesaryuan** [comment]
可以用子程序 [https://getquicker.net/SubProgram?id=48c53f5b-d321-4b04-a2a2-08d9548d1780](https://getquicker.net/SubProgram?id=48c53f5b-d321-4b04-a2a2-08d9548d1780)
