### ISSUE TITLE
无法取消鼠标中键打开方式

### ISSUE THREAD

**Issue by vzcrab** [cuiliang/QuickPadCn#1486]
请问这是只有专业版才支持的吗？对比页面描述是

> 附加的交互方式 / 动作触发方式

连取消也不行吗，是否有点流氓行为？鼠标中键对我而言还是有很大用处的，望回复

**Comment by cuiliang** [comment]
如果是取消之后保存仍然存在，可以退出账号重新登录一下解决。
![image](https://user-images.githubusercontent.com/1972649/127799142-74bab38c-2fd5-4063-bfb8-2ce5e7317878.png)

**Comment by vzcrab** [comment]
感谢，已解决

**Comment by cuiliang** [comment]
嗯，一直以来有这个bug，不过本地没法复现一直没有能修复。如果能找到复现方法，可以赠送专业版兑换码。
