### ISSUE TITLE
在第二个屏幕下 VScode 里无法触发 Quicker

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [cuiliang/QuickPadCn#1487]
**描述BUG**
在第二个屏幕下 VScode 里无法触发 Quicker

**重现步骤**

1. 打开 VScode 
2. 放到第二个屏幕上(我的屏幕是竖屏显示的)，并且最大化 VScode 
2. 无法右键滑手势也无法触发 Quicker 弹出

**相关截图**
![image](https://user-images.githubusercontent.com/40897360/128285432-d354382c-2aa0-40d4-a566-a1fdd4674522.png)
并没有设置 VScode 的黑名单

![01](https://user-images.githubusercontent.com/40897360/128285472-4b6703c4-18f6-46d2-a37f-e86c8acd2186.gif)

没有鼠标手势，也无法弹出 quicker 

**环境信息:**
 - 操作系统版本：Windows10 专业版
 - Quicker版本：1.25.15

**附加信息**
目前只发现 VScode 有这样的问题，其他软件最大化是正常的
VScode 如果没有最大化也是正常的

**Comment by cuiliang** [comment]
关掉全屏禁用就可以了，或者开启副屏幕的任务栏。如果没有任务栏，会判断为全屏情况。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/128286134-f1dd6130-140b-4d48-bcca-b28689e3dc60.png)

**Comment by FXTD-ODYSSEY** [comment]
好的👌🏻️
