### ISSUE TITLE
一个按钮上，保存两个动作，循环顺序执行

### ISSUE THREAD

**Issue by xxxxha** [cuiliang/QuickPadCn#1488]
**需求描述**
我在使用金山PDF阅读文档时，在“批注”模式下，经常需要在“抓手”和“选择”两种工具之间来回切换。软件原有的工具栏菜单，这个两个操作的图标很小，使用起来也不方便。我用Quicker定义两个操作按钮，分别绑定了这两个操作的快捷键动作，悬浮在软件界面上，算是解决了这个问题。

**描述你想要的解决方案**
但目前来说，我想只用一个悬浮按钮看能否解决这个需求。PDF软件的“抓手”和“选择”两种操作，实际上可以视为一组操作。我想用一个悬浮按钮来解决。一个悬浮按钮，保存两个快捷操作，点一次执行“抓手”操作，再点一次执行“选择”操作，这样循环顺序执行，同时悬浮按钮的图片也跟着有所变化。也许Quicker原有的功能就能解决这种需求，但我确实不知道该怎么弄。

**Comment by xxxxha** [comment]
类似开关按钮的概念，点一次打开，再点一次关闭，再点一次又打开，这样循环执行。这是一个非常基础的需求，希望以最简单的方式实现。比如，在“基础动作”修改界面，“”动作类型“如果是“模拟按键”，“输入序列”如果有两个以上键盘输入动作时，额外再增加一个勾选框（名称：循环执行），如果勾上这个选项，那么“输入序列”列表框里的动作，就是循环执行的。

**Comment by cuiliang** [comment]
这个需要使用组合动作，在动作中使用状态存取。
https://getquicker.net/kc/help/doc/statestorage

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
