### ISSUE TITLE
Quicker中搜索，调用everything，如何屏蔽某个文件夹？

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1489]
如题，Quicker搜索，f+空格，调用everything搜索时，如何自定义屏蔽某个文件夹？

**Comment by cuiliang** [comment]
可以参考一下everything官方的文档
https://www.everythingsearch.cn/479.html
https://www.voidtools.com/forum/viewtopic.php?t=4494

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
