### ISSUE TITLE
悬浮图标

### ISSUE THREAD

**Issue by qjh9527** [cuiliang/QuickPadCn#1490]
**需求描述**
希望在桌面有一个悬浮的quicker图标，点击后弹出主窗口。
虽然已有的<弹出面板>功能的选项很多，但是我还是喜欢这种，类似迅雷那种悬浮图标。
此图标可调节透明度，可设置是否自动停靠，可调整大小。这些都可通过右键菜单栏设置。

**Comment by cuiliang** [comment]
https://getquicker.net/kc/manual/doc/float-trigger
