### ISSUE TITLE
升级1.26.3后，使用快速截图，截图后没有贴图显示

### ISSUE THREAD

**Issue by raycao-git** [cuiliang/QuickPadCn#1491]
**描述BUG**
对bug的清晰简洁描述。
升级1.26.3后，使用快速截图，截图后没有贴图显示，只在任务栏有图标显示。设置中已经开启了贴图显示。
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：1.26.3

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
请试下 1.26.4 版本 https://getquicker.net/Help/Versions

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by raycao-git** [comment]
已更新1.26.4，正常了
