### ISSUE TITLE
希望增加多套配置文件同步

### ISSUE THREAD

**Issue by lsy6129** [cuiliang/QuickPadCn#1493]
因为我办公电脑和家里电脑安装的软件不太一样，而且相同软件安装的路径也不太一样，这样办公电脑先同步之后，在家里电脑上的快捷面板的 软件基本都不能用，如果在家里修改了怕 又会影响办公电脑。希望增加不同电脑可以选择是否新建一个配置文件用于同步

**Comment by cuiliang** [comment]
参考：https://getquicker.net/kc/manual/doc/data-sync#ThGPb

**Comment by tweee1234** [comment]
补充建议：当前仅能进行动作页和主机的绑定，我个人更喜欢使用轮盘菜单，希望能让轮盘菜单也能与主机绑定。我知道可以通过组合动作实现不同主机的轮盘菜单指向同样的软件，但毕竟设置较为麻烦。希望可以增加此功能，我觉得可以同一个场景设置多个轮盘菜单，但对于一台主机，某个场景下只能启用一个菜单，其他菜单禁用，不知道这样是否可以实现。

**Comment by cuiliang** [comment]
归档
