### ISSUE TITLE
在步骤编辑界面能够方便查看配置里与动作关联的信息

### ISSUE THREAD

**Issue by LJpLJ** [cuiliang/QuickPadCn#1494]
**需求描述**
例如, 在配置扩展热键等时, 需要经常切换查看配置的菜单, 以及步骤编辑界面

**描述你想要的解决方案**
步骤编辑界面有个菜单可以把与这个动作id关联的信息列出来, 尤其是扩展热键等触发操作的配置

**描述您考虑过的替代方案**
步骤编辑界面有菜单可以快速跳转到相应设置里

**Comment by cuiliang** [comment]
后期考虑下。 目前这个信息提取有些困难。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
下个版本增加编辑和悬浮目标动作的两个按钮。
![image](https://github.com/cuiliang/Quicker/assets/1972649/2dde26c5-6dbd-4e32-940e-29118134663a)
