### ISSUE TITLE
capslock 修饰按键配合滚轮 无法调整窗口透明度

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [cuiliang/QuickPadCn#1495]
**描述BUG**
使用 capslock 作为修饰键配置滚轮控制 窗口透明度 没有效果
改为 alt 键可以

**重现步骤**
1. 去到高级键鼠触发界面
2. 添加 capslock 修饰键控制屏幕透明度

**相关截图**

![image](https://user-images.githubusercontent.com/40897360/130383200-7acdeab7-a223-4b52-a9c9-fc3e34e3f52a.png)

![image](https://user-images.githubusercontent.com/40897360/130383549-1cd79354-e477-47d8-9fd7-1585a52e2c9a.png)

**环境信息:**
 - 操作系统版本：windows10 专业版
 - Quicker版本：1.26.6

**附加信息**

**Comment by cuiliang** [comment]
确认在“扩展热键” 设置中已开启Caps引导键

**Comment by FXTD-ODYSSEY** [comment]
> 确认在“扩展热键” 设置中已开启Caps引导键

好的，重启 quicker 就好了
