### ISSUE TITLE
软件冲突

### ISSUE THREAD

**Issue by tiankong1014** [cuiliang/QuickPadCn#1496]
**描述BUG**
同时运行capslock+时，左键辅助功能会出现bug，左右键粘贴时失败，只会输出V键，提示已粘贴。

**重现步骤**
1.运行capslock+
2.左右键粘贴失败，只输出V键，提示已粘贴。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

- [ ] 

**环境信息:**
 - windows10
 - Quicker版本：1.25.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
此问题Quicker这边无法处理。
capslock+和Quicker都会使用挂钩，不清楚这种情况下capslock+做了什么处理拦截了按键消息。
如果capslock+里有功能选项，可以全部关闭后依次开启，观察一下是哪个功能影响的。

**Comment by tiankong1014** [comment]
> 此问题更快这边无法处理。
> 大写锁+和更快都会使用挂钩，不清楚这种情况下的CapsLock +做了什么处理拦截了按键消息。
> 如果的CapsLock +里有功能选项，可以全部关闭后依次开启，观察一下是哪个功能影响的。

找到冲突的功能了，独立剪贴板功能，关闭独立剪贴板功能就正常了。

**Comment by cuiliang** [comment]
好的，感谢告知！
