### ISSUE TITLE
可否增加一个安全解锁的选项，检测鼠标几分钟没动静， Quicker界面自动锁定，避免其他人乱动

### ISSUE THREAD

**Issue by 149072056** [cuiliang/QuickPadCn#1497]
可否增加一个安全解锁的选项，检测鼠标几分钟没动静， Quicker界面就自动锁定，避免其他人乱动！是为了在办公室场景下面使用的，我已经购买了专业版，感觉有上述使用缺陷。

**Comment by cuiliang** [comment]
建议自动锁定计算机。 可以百度一下在Windows中的设置方法或者使用这个动作 https://getquicker.net/sharedaction?code=dedad670-fd2c-4fa0-153d-08d9678c9b7c
