### ISSUE TITLE
左键辅助在失效

### ISSUE THREAD

**Issue by 754932057** [cuiliang/QuickPadCn#1498]
当使用左键辅助，复制粘贴文本，同时手势软件（WGestures 1.8.4.0）也打开的情况下，左键辅助的快捷复制粘贴会偶然性失效，请大神能修复下这个bug，希望能同时兼容手势软件的使用，谢谢。
[](url)
![image](https://user-images.githubusercontent.com/78536760/130936394-a4855626-c408-487d-a96f-86f40afa5735.png)

**Comment by cuiliang** [comment]
https://getquicker.net/QA/Question/3812 已有帖子不用两边都创建。
