### ISSUE TITLE
扩展热键 capslock + space + D 无法触发

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [cuiliang/QuickPadCn#1499]
**描述BUG**
扩展热键 capslock + space + D 无法触发
(capslock + tab + A 也有同样的问题)
**重现步骤**
1. 添加 capslock + space + D
2. 实测无法触发

**相关截图**

![image](https://user-images.githubusercontent.com/40897360/131205945-5d5d2606-6786-4b47-ae8b-44ab51af3349.png)

**环境信息:**
 - 操作系统版本：win10 专业版
 - Quicker版本：1.26.6

**附加信息**
WASD 键只有 D 键触发不了

**Comment by cuiliang** [comment]
有些键盘不是全键无冲突的，就会有一下键之间存在硬件本身的冲突。如果仅仅是这个键的话，可能是这个原因。

**Comment by FXTD-ODYSSEY** [comment]
确实是键盘的问题的
