### ISSUE TITLE
添加【长按按键松手触发主面板】的选项

### ISSUE THREAD

**Issue by w6lc** [cuiliang/QuickPadCn#1500]
**需求描述**
对于quicker，目前个人主要使用右键拖动触发轮盘（不使用中键，因为很多软件有其默认功能），使用右键长按触发quicker主面板。但这有点不方便，当我想要触发轮盘时，往往因为长按的时候没有及时拖动而打开了主面板。

**描述你想要的解决方案**
添加长按松手后触发主面板的选项。这样在长按右键后，若没有拖动，那么松手时将会出现
![image](https://user-images.githubusercontent.com/49556918/131216528-5f5d3091-c923-4b26-8af7-262f12474ada.png)
现在的功能只有长按直接触发

**描述您考虑过的替代方案**
考虑过使用鼠标的其他按键触发主面板，但本人目前鼠标是99块的小鼠标，没有多余的按键，而且觉得同按键触发两种quicker面板很coooooooooooooool...

 **其他上下文**
目前个人的轮盘设置
![image](https://user-images.githubusercontent.com/49556918/131216409-1c2503ec-8158-4649-b893-d9d122fdfc3a.png)

**Comment by cuiliang** [comment]
可以调整一下参数
![image](https://user-images.githubusercontent.com/1972649/131219199-9da670d6-6056-442a-b29d-0f15c751f68c.png)

**Comment by w6lc** [comment]
> 可以调整一下参数
> ![image](https://user-images.githubusercontent.com/1972649/131219199-9da670d6-6056-442a-b29d-0f15c751f68c.png)

不是完全一致的功能，但也能做到一定的替代吧

**Comment by cuiliang** [comment]
长按抬起是一个不好的触发方式，因为会很难判断按的时间是不是足够长，每次触发都需要过数数的。

**Comment by w6lc** [comment]
好的，谢谢解答！
________________________________
发件人: CuiLiang ***@***.***>
发送时间: 2021年8月29日 21:12
收件人: cuiliang/Quicker ***@***.***>
抄送: wielice ***@***.***>; Author ***@***.***>
主题: Re: [cuiliang/Quicker] 添加【长按按键松手触发主面板】的选项 (#1500)


长按抬起是一个不好的触发方式，因为会很难判断按的时间是不是足够长，每次触发都需要过数数的。

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcuiliang%2FQuicker%2Fissues%2F1500%23issuecomment-907789507&data=04%7C01%7C%7Cf5c8d076ae23453f880108d96aeeae59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658395620023447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7YKdyMH9RedUgl1Z%2BcSh7Q6%2Fb445xgPr0XF9ttkVlRU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL2C3NV2YXVNVR2PQYU2EZTT7IW4RANCNFSM5C7A37IA&data=04%7C01%7C%7Cf5c8d076ae23453f880108d96aeeae59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658395620033441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nRDblnm8lmmE9ydvG%2FhhmELaHw8%2BVD4H2mnU5sjOMyA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf5c8d076ae23453f880108d96aeeae59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658395620033441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NHe%2FBISgXf%2B7M0CzeAhj80RJGkIQR0ofyt4TXJE2g4c%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf5c8d076ae23453f880108d96aeeae59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658395620043432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qFVNewaCeRACx%2BREzCkHCJT2%2F%2FBYdeGa%2B4kTr3%2FGi0c%3D&reserved=0>.
