### ISSUE TITLE
能否添加一个quicker设置或者修改动作的密码保护.

### ISSUE THREAD

**Issue by leeyaunlong** [cuiliang/QuickPadCn#1503]
能否添加一个quicker设置或者修改动作的密码保护.
有的时候电脑会让其他人使用一下, quicker里面动作当然可以给操作者用.
但是不希望有被其他人修改quicker设置或者动作内容被修改的情况发生.
能否添加一些安全性设置
- 进入quicker控制面板,可以设置密码保护,没有密码不能修改动作面板,以及修改quicker系统设置.
- 修改动作内容的密码保护.
- 以上密码应该是本地quicker独立的(多台电脑可以设置不同的密码).
- 对于遗忘密码得情况. quicker官网的用户管理中,用户可以对列出的设备 发出清空本地密码指令. 设备同步后清空密码.

**Comment by cuiliang** [comment]
虽然这是一个不错的功能，不过开发成本太高了，不考虑了。
如果Quicker里有比较重要的东西，还是在给别人使用之前先关掉比较好。或者和他说好不要乱动。
