### ISSUE TITLE
软件本身图标被篡改无法恢复

### ISSUE THREAD

**Issue by iuiuu-qiu** [cuiliang/QuickPadCn#1504]
**描述BUG**
添加了启动软件的动作，但是发现软件本身的图标被修改了，无法恢复

**重现步骤**
1.添加启动软件动作
2.修改动作图标
3.修改完动作图标还是默认的图标，无法修改为我自己选择的图标，并且任务的图标也变成了quicker的图标，无法修改

**相关截图**
![image](https://user-images.githubusercontent.com/71259835/131948523-4521c448-218e-4983-acc8-4dd5f10c5ebf.png)
![image](https://user-images.githubusercontent.com/71259835/131948623-380475e6-c025-4fec-a192-972d0b6948d4.png)
![image](https://user-images.githubusercontent.com/71259835/131948667-9b06a2af-ca18-4f3f-914e-8794313b96c9.png)

**环境信息:**
 - 操作系统版本：Windows 10 家庭中文版  21H1
 - Quicker版本：1.25.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
windows里显示的图标和quicker没有关系。可以试试用刷新图标缓存的动作刷一下。
https://getquicker.net/sharedaction?code=1bd785e7-9c16-4462-4c54-08d69498663d

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
