### ISSUE TITLE
希望能提供除系统代理外的代理方式，如http代理

### ISSUE THREAD

**Issue by pickalexrener** [cuiliang/QuickPadCn#1505]
**需求描述**
最近使用一个telegram的动作，其中调用tg的api发送http请求，需要使用代理。
我知道quicker可以使用系统代理，但我个人的使用场景（v2rayN）是不接管系统代理的。
所以浏览器通过插件switchyomega指定http代理，tg指定socks5代理。
希望quicker能提供http（socks）代理方式。
![image](https://user-images.githubusercontent.com/51726771/132125882-4922c189-f20c-48b1-b28e-11f3fb0261ef.png)

![image](https://user-images.githubusercontent.com/51726771/132125926-d06c6139-ff6c-4cc1-8209-9144b2321dae.png)

**描述你想要的解决方案**
可以是全局的http代理，当然最好的是http请求模块里可以指定代理方式。
![image](https://user-images.githubusercontent.com/51726771/132126029-651c58c2-75be-4641-9e4a-015de4d5b3c2.png)

![image](https://user-images.githubusercontent.com/51726771/132125989-4472ad7b-aec9-4668-9e71-60cb50e1381e.png)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by MrChinR** [comment]
同上，希望添加http代理选项。公司内网需要验证用户名和密码，单纯windows系统默认代理的话无法验证用户名和密码，quicker还是无法链接网络。
搜论坛看到有大佬说修改Quicker.exe.config在system.net里加入proxy解释，但试了试不太行。其他软件例如python的pycharm在设置里就有proxy选项，可以输入ip地址端口和用户名密码等信息，实现公司内网链接网络。
![image](https://user-images.githubusercontent.com/55696381/172125750-6e52230e-436e-455f-9248-8c53e28698c4.png)
相信quicker这种十分优秀生产力工具有不少人是在工作中去使用，公司内网问题应该也不少，希望作者可以考虑添加http代理功能。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
目前http模块中可以设置强制使用quicker中设置的代理。
