### ISSUE TITLE
鼠标手势支持多个按键，简化手势

### ISSUE THREAD

**Issue by tlwf** [cuiliang/QuickPadCn#1506]
**需求描述**
希望鼠标手势支持多个按键，类似Wgestures。手势集中在一个按键上，操作时长、记忆成本、误操作概率都会更高。

**描述你想要的解决方案**
多个按键支持手势，通过分散到多个按键，简化手势，如每个按键上下左右4个方向，或米字8个方向。现在是用的wgestures手势+quicker的轮盘和动作；但是wgestures没有同步功能，多机器比较麻烦。

quicker预定义手势，就，就不太行懂吧
![image](https://user-images.githubusercontent.com/40683029/132129778-9e70be86-7dfb-4d22-b5e9-825a1894bffe.png)

wgestures多键分散手势：
![image](https://user-images.githubusercontent.com/40683029/132129681-8d97c9f8-1445-45d2-8a98-cd296ae894d4.png)
![image](https://user-images.githubusercontent.com/40683029/132129690-bd65a663-2fdd-45a0-9608-11b4f2578858.png)
![image](https://user-images.githubusercontent.com/40683029/132129700-0f68a0ae-c082-4577-8a09-37e7c0f9b51b.png)
![image](https://user-images.githubusercontent.com/40683029/132129710-23ec2fea-8ae1-48d2-a47a-f721f8a35b1e.png)

**Comment by cuiliang** [comment]
目前手势支持在识别到之后按下一个键，并把这个键作为参数传递给触发的动作，在动作中根据按键触发不同的操作。
不过这个确实有点麻烦，等后期再研究一下了。

**Comment by cuiliang** [comment]
后来增加了按键触发、引导键触发特定场景手势等。
关闭古老issue中，感谢！
