### ISSUE TITLE
4k显示器下菜单太小

### ISSUE THREAD

**Issue by jiangqi323** [cuiliang/QuickPadCn#1507]
**描述问题**
在使用4k显示器的时候因为放大了300%，界面放大后是一个适合的大小但是在界面上右键的时候菜单变得非常小
**重现步骤**
打开quicker界面
然后鼠标右键

**相关截图**
![image](https://user-images.githubusercontent.com/50327688/132334616-bd0c4d1b-8e29-4f15-9770-3b7aa68c1134.png)

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.25.15

**Comment by cuiliang** [comment]
是有多个显示器么？主显示器分辨率和dpi是多少？ 有没有重启电脑试一下？

**Comment by jiangqi323** [comment]
主显示器24寸分辨率1920x1080缩放100%，副显示器15.6寸分辨率3840x2160缩放300%
主界面上大小是合适的右键后菜单界面很小，但是右键菜单的次一级大小又是合适的
![image](https://user-images.githubusercontent.com/50327688/132338273-a7346105-4903-4325-a7fc-4544041c40cf.png)

**Comment by cuiliang** [comment]
试了一下，没法解决。 这个是底层的问题，这里可以看到一个类似的：https://stackoverflow.com/questions/56936098/use-current-display-scale-in-wpf-contextmenu 
我试了里面的方法，会造成子菜单更大，而且错位。

**Comment by cuiliang** [comment]
后来解决了。
