### ISSUE TITLE
高级鼠标触发的长按，没有触发时间的设置。

### ISSUE THREAD

**Issue by Anlv-max** [cuiliang/QuickPadCn#1508]
# 高级鼠标触发
没有找到长按触发时间的相关设置，当设置了弹出面板触发时间和上下文指令触发时间后，长按时触发的时间过快/过慢，都会使体验感受下降。

----

## 弹出面板的触发时间设置
![Image](https://raw.githubusercontent.com/Anlv-max/Markdown_Image/main/Snipaste_2021-09-08_16-49-06.jpg)

## 上下文菜单的触发时间设置
![Image](https://raw.githubusercontent.com/Anlv-max/Markdown_Image/main/Snipaste_2021-09-08_16-49-24.jpg)

### 没有找到触发时间的相关设置
![Image](https://raw.githubusercontent.com/Anlv-max/Markdown_Image/main/Snipaste_2021-09-08_16-50-25.jpg)

**Comment by cuiliang** [comment]
第一个截图里的长按触发时间参数就是的。

**Comment by Anlv-max** [comment]
> 第一个截图里的长按触发时间参数就是的。

十分感谢。
