### ISSUE TITLE
全局快捷键附带参数

### ISSUE THREAD

**Issue by OriginBo** [cuiliang/QuickPadCn#1509]
**需求描述**
希望能够在给动作绑定全局快捷键的时候，能同时传递一个参数给动作。这样就能把多个相似功能集成在一个动作里面，通过不同的快捷键触发

**描述你想要的解决方案**
绑定全局快捷键时，新增参数选项

**Comment by cuiliang** [comment]
已经有了。升级快速通道版本。
![image](https://user-images.githubusercontent.com/1972649/132630998-7ee55d27-f1ff-4b10-b9b2-bbdd20f7f3b3.png)
