### ISSUE TITLE
win11 quicker引起的窗口拖动bug

### ISSUE THREAD

**Issue by g999666** [cuiliang/QuickPadCn#1511]
**描述BUG**
win11 只要打开quicker 然后再打开文件资源管理器 再进行窗口拖动 鼠标指针会出现问题

**重现步骤**
1.打开quicker主页面
2.打开文件资源管理器
2.拖动Windows任何一个软件的窗口
3.你会发现你的鼠标会不受控制
4.重启quicker可以解决问题，但是再重复上面的步骤又会继续

**相关截图**
设置还出现了两个鼠标
![Uploading 0909_1.jpg…]()

**环境信息:**
 - 操作系统版本：
 - 
![image](https://user-images.githubusercontent.com/50013927/132718571-22001831-4888-4b0f-87dc-3e419356d9af.png)

 - Quicker版本：
1.25.7

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by g999666** [comment]
![0909_1](https://user-images.githubusercontent.com/50013927/132718827-ac8e31f3-c674-426b-a17a-65198b4ae285.jpg)
shen'zh 甚至出现了两鼠标

**Comment by cuiliang** [comment]
Windows11最新dev版本解决了这个问题，更新一下就可以了。

**Comment by cuiliang** [comment]
也可以升级quicker到最新版，里面会有判断，如果是win11的22000版本会禁用背景模糊。也可以直接外观设置里去除背景模糊的选项。
