### ISSUE TITLE
添加 轮盘菜单 快捷键禁用功能

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [cuiliang/QuickPadCn#1512]
**需求描述**
目前 quicker 只能用快捷键全局禁用功能
无法对单个模块的功能进行禁用

**描述你想要的解决方案**
希望能够开放出来相应的禁用功能，比如说用动作来禁用部分功能或者快捷键禁用部分功能，这样可以极大减少禁用 quicker 全部功能带来的麻烦。

**Comment by cuiliang** [comment]
对每个功能增加额外的禁用会造成程序配置和使用更为复杂，目前不考虑了。

**Comment by cuiliang** [comment]
什么情况会需要单独禁用轮盘呢？

**Comment by FXTD-ODYSSEY** [comment]
> 什么情况会需要单独禁用轮盘呢？

我配置了快捷短语，有时候操作三维软件需要禁用 轮盘菜单 ，但是快捷短语又希望能够生效期

**Comment by cuiliang** [comment]
可以在场景设置里单独在某个软件下单独禁用轮盘功能。
![image](https://user-images.githubusercontent.com/1972649/133347045-4c832450-1253-4505-a333-a5ffa1796c94.png)

**Comment by FXTD-ODYSSEY** [comment]
好的
