### ISSUE TITLE
在文本窗口中获取选中文本失败

### ISSUE THREAD

**Issue by zyufstudio** [cuiliang/QuickPadCn#1513]
**描述BUG**
弹出文本窗口后，选中需要的文本后再打开quicker的动作库时，提示获取文本失败

**相关截图**
![image](https://user-images.githubusercontent.com/52726576/133365640-d1ee2d05-4f5d-4cf7-b4b6-1c016e3ad385.png)

**环境信息:**
 - 操作系统版本：Windows 10 专业版21H1
 - Quicker版本：1.25.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
升级到快速通道最新版试试。 另外同一个程序里的窗口会互相抢占焦点，也会有一定的影响。
