### ISSUE TITLE
quicker 搜索框有时需要键入两次，才能输入命令

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1515]
如题，快捷键打开Quicker搜索框后，有时需要输入两次，才能在搜索框中键入命令。

比如进行google搜索，需要键入两次"g"，“g”才会出现在搜索框中。

**Comment by cuiliang** [comment]
版本多少？ 有没有办法复现呢？

**Comment by DogeFlow** [comment]
版本为 1.25.15，可以复现，快捷键打开Quicker后，经常第一次输入无效，需要再次键入，才能将命令输入搜索框

**Comment by cuiliang** [comment]
打开之后稍等一点再输入会有这个现象么？方便的话录个屏看看。 有可能刚开始输入框还没有焦点。
另外试试使用英文输入法。

**Comment by DogeFlow** [comment]
我已经设置“搜索框输入法状态为  关闭”，没使用中文。有时候等待一会儿也需要键入两次。
![动画](https://user-images.githubusercontent.com/34650487/133534678-09139c67-711d-4855-acfc-436dfa97a1f4.gif)

**Comment by DogeFlow** [comment]
感觉是焦点的获取问题，需要键盘键入一下，才能将焦点对准输入框

**Comment by cuiliang** [comment]
试一下更新到 1.26.19 版本  https://getquicker.net/Help/Versions 
楼上的动图里有几次没有第一项就成功呢

**Comment by DogeFlow** [comment]
更新到1.26.19后还是有这个问题，重启电脑及quicker也还存在问题

**Comment by cuiliang** [comment]
方便的话换个输入法试一下看看。 目前用的什么输入法？

**Comment by DogeFlow** [comment]
用的就是win10自带的输入法，没有安装其他输入法

**Comment by DogeFlow** [comment]
倒是不太影响使用，如果后面能找到修复办法最好了

**Comment by cuiliang** [comment]
好的。 目前还没有其他用户反馈类似问题，暂时也没法确定到底是什么原因。机器是什么样的配置呢？

**Comment by DogeFlow** [comment]
机器应该没问题，不卡顿
![image](https://user-images.githubusercontent.com/34650487/133536958-9edac8c5-8cb6-4f93-a4e4-6fcbd5c46a7e.png)

**Comment by DogeFlow** [comment]
我再观察观察吧，看看有没有什么规律

**Comment by cuiliang** [comment]
这个后来（很晚才）解决了，目前的版本应该可以了。
