### ISSUE TITLE
移动窗口时跟着鼠标走

### ISSUE THREAD

**Issue by mangoriver** [cuiliang/QuickPadCn#1518]
**需求描述**
现在 移动quicker的所有窗口时, 在鼠标松开时窗口才移动到目的地.
需要 移动quicker的所有窗口时,能和移动普通窗口一样,比如 notepad.exe, 窗口立即跟着鼠标动,在鼠标还未松开时就跟着动.
另外, 总觉得quicker窗口的移动有点迟滞,延迟,反应不灵敏, 你看看吧.

**Comment by cuiliang** [comment]
没有遇到过你说的现象。
检查一下显卡驱动是否正常安装，然后在Windows性能选项中开启“调整为最佳外观”试试（具体设置可搜索百度）。

**Comment by cuiliang** [comment]
另外可以录屏一下以便准确理解你说的现象。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
