### ISSUE TITLE
手势动作突然不起作用了。

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1520]
**描述BUG**
其它的手势动作都起作用呢，但是在Edge浏览器里面，先向下划再向右划的手势动作设置的是关闭当前页面，以前都是起作用呢，但是今天不知道为什么突然不起作用了。

**重现步骤**
见截图

**相关截图**
![Uploading image.png…]()

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.26.17

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能你在别的地方使用了那个快捷键。 检查一下是什么快捷键（关闭标签一般是ctrl+w），有没有在quicker里或别的软件里用了这个快捷键。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
