### ISSUE TITLE
请问本地和远程都开了本软件，怎么触发远程的那个？

### ISSUE THREAD

**Issue by dlgcy** [cuiliang/QuickPadCn#1521]
**需求描述**
 mstsc 远程桌面，本地和远程都开了本软件，想要触发远程的那个而不是本地的。

**描述你想要的解决方案**
触发远程的而不是本地的。

**描述您考虑过的替代方案**
可以通过点击状态栏图标弹出面板，能满足部分场景，但是有些是要针对特定软件的，就难以满足了。

**Comment by cuiliang** [comment]
把远程软件加入黑名单。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
