### ISSUE TITLE
上下文动作页名称显示不全

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1522]
**描述BUG**
上下文动作页名称显示不全。

**重现步骤**
1. 随便打开一个名字稍微长点的动作页即可。

**相关截图**
![image](https://user-images.githubusercontent.com/23332018/134610146-3643e422-3655-4f4c-a5d0-7160419764d4.png)
![image](https://user-images.githubusercontent.com/23332018/134610191-f39c86ee-e096-4099-80a7-0c113a4db944.png)

**环境信息:**
 - 操作系统版本：window 10，21H1
 - Quicker版本：1.26.17

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这是正常的，会限制宽度给翻页指示预留空间。
![image](https://user-images.githubusercontent.com/1972649/134617145-82dca437-3213-4c34-a4e7-11158252ef10.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
