### ISSUE TITLE
Colemak cannot be activated

### ISSUE THREAD

**Issue by Extraordinaritarian** [cuiliang/QuickPadCn#1523]
![image](https://user-images.githubusercontent.com/86732413/134687901-2d4b4271-c3eb-452c-8ea3-ba583e746023.png)
It automated turns to qwerty even colemak is installed

**Comment by cuiliang** [comment]
估计是那个东东权限不足，用管理员身份运行它看看。 
另外估计它也是用键盘挂钩实现的，Quicker也是，根据挂钩的先后，结果可能不同。

**Comment by Extraordinaritarian** [comment]
谢谢你

CuiLiang ***@***.***> 于 2021年9月24日周五 22:11写道：

**Comment by cuiliang** [comment]
解决了么？ @Extraordinaritarian

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
