### ISSUE TITLE
关联到当前进程，Quicker重启后失效

### ISSUE THREAD

**Issue by Duoluozhijkhshang** [cuiliang/QuickPadCn#1524]
**描述BUG**
关联到当前进程，Quicker重启后失效

**重现步骤**
1.选择悬浮此动作，并且关联到某个程序
2.Quiker重启后，关联就会失效，需要重新设置

**环境信息:**
 - 操作系统版本：20H2，19042.1237
 - Quicker版本：1.25.15

如果这不是bug，就变成需求了

**Comment by cuiliang** [comment]
重启后悬浮会自动开启么？ 
自动开启的情况下，我测试是没问题的。

**Comment by Duoluozhijkhshang** [comment]
> 重启后悬浮会自动开启么？ 自动开启的情况下，我测试是没问题的。

奥，找到了，原来需要设置一下，谢谢了
