### ISSUE TITLE
触屏模式下，文本窗口支持双指拖拽滚动

### ISSUE THREAD

**Issue by Duoluozhijkhshang** [cuiliang/QuickPadCn#1525]
**需求描述**
平板触屏模式下，文本窗口需要展示较多文本时，能够支持双指滚动

**描述你想要的解决方案**
加强平板模式下，文本窗口浏览体验

**描述您考虑过的替代方案**
或者对文本窗口增加选项，将一旁的滚动条加粗

**Comment by cuiliang** [comment]
是用触控板还是触摸屏？目前是啥反应呢？手头暂时没有设备

**Comment by Duoluozhijkhshang** [comment]
> 是用触控板还是触摸屏？目前是啥反应呢？手头暂时没有设备

使用teamvier远程控制时，对比默认的记事本，文本窗口拖拽只会选中文本，无法滚动

**Comment by cuiliang** [comment]
可能远程控制软件本身不支持触摸消息的传递的。需要在本地设备上试验

**Comment by Duoluozhijkhshang** [comment]
> 可能远程控制软件本身不支持触摸消息的传递的。需要在本地设备上试验

teamvier应该支持双指手势，因为Acrobat DC Pdf阅读，可以设置为双指拖动，单指选中。不过也有可能，是远控更复杂的原因，请作者多注意一下吧
