### ISSUE TITLE
全屏游戏的时候，提供鼠标的十字辅助

### ISSUE THREAD

**Issue by chucklu** [cuiliang/QuickPadCn#1527]
**需求描述**
游戏团战的时候，需要快速找到鼠标的位置

**描述你想要的解决方案**
基于鼠标所在的位置，构建十字

**描述您考虑过的替代方案**
没有替代方案

 **其他上下文**
类似于下图，在玩游戏的时候，始终有一个根据鼠标位置构建的十字。十字的颜色，粗细，虚实都可以进行调整
![image](https://user-images.githubusercontent.com/3004057/135605815-44235bac-48d0-44f6-a18e-7e877037b4b0.png)

**Comment by chucklu** [comment]
其他人也有类似的困扰，[ 常年青铜段位，打团找不到自己，对战找不到鼠标的人]( https://www.zhihu.com/question/320876997)

**Comment by cuiliang** [comment]
这个，不太懂，功能也不太适合quicker本身。 你可以试试clickshow 开启位置提示看看能不能检测到鼠标位置。 https://github.com/cuiliang/ClickShow

**Comment by chucklu** [comment]
@cuiliang  不好意思，是我搞错了。我看别人直播的时候有这个，以为是什么辅助软件。
后来发帖问了一下，发现是游戏内置的功能，但是我从来没用过。《风暴英雄》使我快乐！
