### ISSUE TITLE
在WPS Spreadsheets 下点击加载动作页，会自动弹出默认动作页

### ISSUE THREAD

**Issue by Tang-Tel** [cuiliang/QuickPadCn#1528]
**描述BUG**
在WPS Spreadsheets 下点击加载动作页，会自动弹出默认动作页

**重现步骤**
1.在WPS Spreadsheets 下弹出quicker面板
2.选择一个创建好的加载动作页
3.如果未出现，则重复几次

**相关截图**

**环境信息:**
 - 操作系统版本：Win10专业版21H1 19043.1237
 - Quicker版本：1.26.23

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
WPS 里不同位置是不同进程。如果要在表格里和其他位置显示一样的，可以在WPS场景设置里添加关联程序：
![image](https://user-images.githubusercontent.com/1972649/135801253-a9e5eb05-aa8a-4d6d-a532-3365523d4b7d.png)

如果不一样，可以给et.exe单独创建场景。

**Comment by Tang-Tel** [comment]
> WPS 里不同位置是不同进程。如果要在表格里和其他位置显示一样的，可以在WPS场景设置里添加关联程序： ![image](https://user-images.githubusercontent.com/1972649/135801253-a9e5eb05-aa8a-4d6d-a532-3365523d4b7d.png)
> 
> 如果不一样，可以给et.exe单独创建场景。

哦，我没有描述清楚，我已经给Spreadsheets单独创建了场景，然后在场景里面，我有一个动作是加载动作页，但是我点击之后，没有跳转到我指定的动作页，而是弹出了默认的动作页。

**Comment by cuiliang** [comment]
先试试1.26.23 有没有问题。https://getquicker.net/Help/Versions
如果仍然有问题，录个屏我看下具体现象。

**Comment by Tang-Tel** [comment]
> 先试试1.26.23 有没有问题。https://getquicker.net/Help/Versions 如果仍然有问题，录个屏我看下具体现象。


从1.24.34.0开始后面的版本，都有问题了。1.26.23 也有问题
下面是视频测试链接：
https://v.youku.com/v_show/id_XNTgxMDk3MzEyNA==.html

**Comment by cuiliang** [comment]
录屏可以直接在Github帖子里上传。 优酷打开要放广告😂

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/135815045-ca90461c-501d-42eb-a983-2b3071161478.png)
测试了一下确实会这样。目前可以先锁定一下再切换。

**Comment by Tang-Tel** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/135815045-ca90461c-501d-42eb-a983-2b3071161478.png) 测试了一下确实会这样。目前可以先锁定一下再切换。

哈哈，好的，下次直接在Github帖子里上传，那我先锁定，先用，等后面修复了再更新

**Comment by cuiliang** [comment]
嗯，也可以考虑用excel，wps具有奇怪的窗口结构，一个窗口好几个进程，容易产生各种奇怪的问题。

**Comment by Tang-Tel** [comment]
> 嗯，也可以考虑用excel，wps具有奇怪的窗口结构，一个窗口好几个进程，容易产生各种奇怪的问题。

嗯嗯，主要我设置了一系列公式，excel里面字符长度受限，只能在wps里面用。
比如evaluate，excel只能支持255以内的字符，wps则没有这个限制

**Comment by cuiliang** [comment]
方便的时候试下 1.26.24 版本 https://getquicker.net/Help/Versions 应该解决了这个问题。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
