### ISSUE TITLE
quicker内置矢量图标为啥全是英文的啊？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1529]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
有点不习惯，希望可以翻译一下，机器翻译的也行啊，后面更新版本的时候再调整。
有点不习惯，降低了我使用矢量图标的频率。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20214204114219](https://user-images.githubusercontent.com/44609485/135881757-89d65787-e6f4-4839-a30e-32709bba3203.png)

**Comment by cuiliang** [comment]
因为是用的老外的图标库， Fontawesome
