### ISSUE TITLE
正则匹配不成功

### ISSUE THREAD

**Issue by noharae** [cuiliang/QuickPadCn#1530]
**描述BUG**
不知道什么时候就出现了，经常会有正则匹配不成功的提示，然后无法运行，有些动作以前是可以正常运行的

**重现步骤**
普通的打开一个动作，然后就会显示不成功
![Screenshot_1.jpg](https://i.loli.net/2021/10/07/uvd8DmTIFY64WLV.jpg)

**相关截图**
不知道怎么上传附件……就找了两个动作截了个图
![2021-10-07_093521.png](https://i.loli.net/2021/10/07/KHWEPSts6e2RLDr.png)
![2021-10-07_093245.png](https://i.loli.net/2021/10/07/UBDhTQEvzsHCe3A.png)

**环境信息:**
 - 操作系统版本：Win-10.0.19043.0 
 - Quicker版本：1.26.23.0 

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/136309510-4dc88ed0-47c2-424b-b0d0-57c6196853af.png)
虽然我不是很懂正则，但是这个正则看起来确实不匹配的。

**Comment by noharae** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/136309510-4dc88ed0-47c2-424b-b0d0-57c6196853af.png) 虽然我不是很懂正则，但是这个正则看起来确实不匹配的。

诶那就是这几个动作的问题嘛？get，谢谢了，差点以为我电脑有啥问题运行不了_(:з」∠)_

**Comment by cuiliang** [comment]
估计是动作的问题。 从状态里读取的股票代码是纯数字，应该不需要再通过正则提取了。
