### ISSUE TITLE
【选择文件】模块中修改默认扩展名，不起作用

### ISSUE THREAD

**Issue by puwei7788** [cuiliang/QuickPadCn#1533]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/29268907/136899083-66ae3654-ff46-4d01-b99d-2c1dcdb50142.png)

**环境信息:**
 - 操作系统版本：
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2020/‎05/‎28
操作系统内部版本	19043.1266
体验	Windows Feature Experience Pack 120.2212.3920.0

 - Quicker版本：
![image](https://user-images.githubusercontent.com/29268907/136899450-1dad1066-c17d-476d-abc6-baa1f37cbcd5.png)

**附加信息**
另外，对话框中的默认文件名也会显示不全？
![L)QU)M@0` (3CN(X9461J$G](https://user-images.githubusercontent.com/29268907/136899182-8f8a1ff9-b300-47f1-a02f-e6971b00891f.png)
要点一下才能显示完整
![WFBV5IW~~LVAK$SKW28NPH5](https://user-images.githubusercontent.com/29268907/136899210-1aba342e-536a-4a8b-976d-6d49b21aeec5.png)

**Comment by cuiliang** [comment]
感谢反馈我研究一下。

**Comment by cuiliang** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.defaultext?view=windowsdesktop-5.0#System_Windows_Forms_FileDialog_DefaultExt
又看了一下默认扩展名的文档，这里并不是默认选择文件类型的意思。大概是在保存文件的时候如果没有输入扩展名，会自动添加的扩展名（如果后面文件类型筛选器是选的*.*的情况下）。
对话框有另外一个属性FilterIndex，用来指定默认选择的筛选器，这个在Quicker中没有封装。目前还是直接调整筛选器的顺序来选择默认的那个吧。

**Comment by puwei7788** [comment]
收到，理解了，多谢指导发自我的华为手机-------- 原始邮件 --------发件人： CuiLiang ***@***.***>日期： 2021年10月13日周三 08:45收件人： cuiliang/Quicker ***@***.***>抄送： puwei7788 ***@***.***>, Author ***@***.***>主    题： Re: [cuiliang/Quicker] 【选择文件】模块中修改默认扩展名，不起作用 (#1533)
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.defaultext?view=windowsdesktop-5.0#System_Windows_Forms_FileDialog_DefaultExt
又看了一下默认扩展名的文档，这里并不是默认选择文件类型的意思。大概是在保存文件的时候如果没有输入扩展名，会自动添加的扩展名（如果后面文件类型筛选器是选的*.*的情况下）。
对话框有另外一个属性FilterIndex，用来指定默认选择的筛选器，这个在Quicker中没有封装。目前还是直接调整筛选器的顺序来选择默认的那个吧。

**Comment by cuiliang** [comment]
在程序里做了个判断，根据默认扩展名自动更新筛选，等后续版本更新。

**Comment by puwei7788** [comment]
做了个折中，基本满足需求了
















At 2021-10-13 09:20:33, "CuiLiang" ***@***.***> wrote:

Closed #1533.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
