### ISSUE TITLE
窗口界面控制(flaUI) 找不到控件

### ISSUE THREAD

**Issue by hclwsyw** [cuiliang/QuickPadCn#1536]
**描述BUG**
我想在ddnsto网站进行签到，利用窗口界面控制(flaUI)模块，但总说找不到控件，很难受。
浏览器：edge
经测试以下两种情况能顺利执行：
1、将窗口界面控制(flaUI)的几个模块（即签到部分）单独提取出来放入一个新动作。提前打开网站，仅执行“签到”动作顺利完成签到。
2、当动作执行时，打开的网页是浏览器的第二个（或者以上）网页时，能成功找到控件。

**重现步骤**
1.打开ddnsto网址
2.触发签到相关控件

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.26.21

**附加信息**

**Comment by cuiliang** [comment]
找控件需要确保控件所在的窗口结构和控件路径不变。
网页里的建议试试使用js脚本结合浏览器控制模块。或者找下看看有没有油猴脚本。

**Comment by hclwsyw** [comment]
好的，谢谢大佬
