### ISSUE TITLE
希望键盘弹出面板，增加“双击Ctrl”选项

### ISSUE THREAD

**Issue by roulen100** [cuiliang/QuickPadCn#1537]
**需求描述**
希望能键盘弹出主界面，设置“双击Ctrl”选项，因为单击容易和很多快捷键冲突。

键盘方式：

- [ ] 单击Ctrl    - [ ] **双击Ctrl**

**Comment by lenks-124** [comment]
加一

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Manual/Doc/settings-keyactionmanagepage 
已增加双击触发功能。
