### ISSUE TITLE
希望轮盘菜单可以自主关闭外圈，还是太大了

### ISSUE THREAD

**Issue by hujie12306** [cuiliang/QuickPadCn#1538]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/137489714-4f89daf2-d2fa-404f-af81-641f72abae87.png)

**Comment by hujie12306** [comment]
问题是，有时候这一圈没用，留着干嘛

<img width="215" alt="image_6" src="https://user-images.githubusercontent.com/61086637/137492328-896f93ff-ebea-4533-bdf9-40e42b6d8bd6.png">
而且轮盘调小后，图标和字都变小了，不如只留内圈，把轮盘调大一些

<img width="951" alt="image_7" src="https://user-images.githubusercontent.com/61086637/137492350-8172f667-339d-4edb-84f1-a493327c7314.png">
而且轮盘调小后，图标和字都变小了，不如只留内圈，把轮盘调大一些



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 晚上8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 希望轮盘菜单可以自主关闭外圈，还是太大了 (#1538)





 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiliang** [comment]
后期考虑下。 目前可以放一些全局操作在上面。很多人会觉得位置不够用而不是多余😂

**Comment by hujie12306** [comment]
好的，谢谢回复
目前感觉还是比较需要的，原因可能如下：
1.笔记本屏幕太小了
2.刚开始用，需要的动作不多，空着觉得别扭
酌情开发吧
[无需回复]






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 希望轮盘菜单可以自主关闭外圈，还是太大了 (#1538)





 
后期考虑下。 目前可以放一些全局操作在上面。很多人会觉得位置不够用而不是多余😂
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
