### ISSUE TITLE
禁用单个动作快捷键

### ISSUE THREAD

**Issue by zhangym** [cuiliang/QuickPadCn#1539]
**需求描述**
禁用单个动作快捷键。

**描述你想要的解决方案**
在某些特定场景下，为了处理方面往往希望设置简单的快捷键（有时习惯甚至为单键）。但一旦不需要时，需要取消。但下次遇到同样场景，又得设置一遍，非常麻烦。

**Comment by cuiliang** [comment]
做一个动作，运行命令`quicker://settings:ActionHotkeysSettingPage` 然后给它设置一个快捷键。需要的时候按这个快捷键快速打开快捷键设置界面，删掉不需要的快捷键就可以了。
对于设置窗口的每个界面，可以右键单击右上角的问号图标复制一个命令，用这个命令可以快速打开对应的设置界面。

**Comment by cuiliang** [comment]
归档
