### ISSUE TITLE
开机启动 Quicker 经常失效

### ISSUE THREAD

**Issue by kamner** [cuiliang/QuickPadCn#1540]
**描述BUG**
勾选了开机启动选项，安全软件也已经允许了，有时候开机就是不启动，任然需要手动打开

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

![image](https://user-images.githubusercontent.com/37998226/138012590-991e9552-794c-4be2-bb0b-96fc09b935ef.png)

**环境信息:**
 - 操作系统版本：win 7 64bit
 - Quicker版本：1.26.23

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果有安装管家或带有启动管理的软件，大概率是这些管家拦截了。
如果没有，可以看一下quicker.log文件还有Windows事件查看器里是不是有报错，也有可能程序在启动的时候遇到了问题。
另外也可以升级到快速通道版本试一下看看。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
