### ISSUE TITLE
Quicker启动后，鼠标单击拖动任意窗口时肉眼可见非常卡顿，同时任务管理器中“桌面窗口管理器”进程CPU占用飙升。

### ISSUE THREAD

**Issue by Rain2Cloud** [cuiliang/QuickPadCn#1542]
**描述BUG**
Quicker启动后，鼠标单击拖动任意窗口时肉眼可见非常卡顿，同时任务管理器中“桌面窗口管理器”进程CPU占用飙升。
测试关闭Quicker后再重复上述动作，卡顿消失。

**重现步骤**
1.启动Quicker
2.打开任意窗口，鼠标单击拖动窗口，稳定复现

**相关截图**
拖动窗口前：![image](https://user-images.githubusercontent.com/35256378/138793866-6ceb4a31-094c-4493-a926-88bd963c849e.png)
拖动窗口时：![image](https://user-images.githubusercontent.com/35256378/138794130-d4ed5863-259d-4805-bb48-350107d2fb5b.png)

**环境信息:**
 - 操作系统版本：Windows 11 Insider Preview 22483.1011
 - Quicker版本：1.27.5

**附加信息**
在我安装使用Quicker之前，没有出现这种情况，安装使用Quicker后，只要一拖动窗口明显感觉卡顿，遂关闭Quicker测试，关闭后，拖动卡顿消失。再打开Quicker，卡顿复现。如此反复测试，卡顿稳定复现。
以上。
维护不易，亮哥辛苦。

**Comment by cuiliang** [comment]
这个大约是显卡驱动的问题。可以在Quicker外观设置中关闭模糊选项。
![image](https://user-images.githubusercontent.com/1972649/138795621-b208555c-2d23-4f1e-afea-e523e42b0be6.png)

**Comment by Rain2Cloud** [comment]
解决了，感谢亮哥！
