### ISSUE TITLE
问题摘要：打开“用户输入”窗口后，其他窗口不能点击

### ISSUE THREAD

**Issue by likeTianDian** [cuiliang/QuickPadCn#1543]
**描述BUG**
在打开“用户输入窗口”后，在此之前已经悬浮的窗口都不能点击。

**重现步骤**
1.一个动作打开“用户选择”
2.另一个动作打开“用户输入”或者“文本窗口”
3.此时无法点击“用户选择”或“文本窗口”，包括像“悬浮此动作”已经悬浮到桌面的也点不了

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10专业版 21H1 19043.1288
 - Quicker版本：1.26.21

**附加信息**
在朋友电脑上用朋友的quicker帐号试了下，是一样的问题

**Comment by cuiliang** [comment]
这是正常的，Windows的模态窗口会阻止访问同一个进程的其他窗口。 用户输入是一个模态窗口，要关闭以后才能操作别的位置。

**Comment by likeTianDian** [comment]
好的，既然不是bug就没事了
