### ISSUE TITLE
鼠标点击失效

### ISSUE THREAD

**Issue by likeTianDian** [cuiliang/QuickPadCn#1544]
**描述BUG**
在使用quicker时，有时电脑会卡住，此时鼠标所有点击无效，但quicker的快捷键能按（如：中键唤出，右键拖动），并且能点击唤出的quicker面板，但其他所有的地方都点不了，键盘正常。
目前我的解决方法是中键弹出面板后，点击菜单关闭quicker，再按一下中键（关了quicker不按中键，直接打开的话，有时还是卡住的状态）。

**重现步骤**
似乎是随机出现的，目前没有找到重现步骤

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 专业版 21H1 19043.1288
 - Quicker版本：1.26.21

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈~

这个现象原因是某个窗口（可能是Quicker自己的）锁定了鼠标（在一个窗口上有按下鼠标的事件，但是没有抬起鼠标的事件），
可以尝试按Ctrl+Alt+Delete打开任务管理器窗口，一般可以释放。

如果能复现最好了，这个现象确实偶尔会发生，一直没已找到稳定复现的方法。

**Comment by zhch25** [comment]
你好，我最近一直出现这个bug，出现之后鼠标点击不了任何窗口，按Ctrl+Alt+Delete打开任务管理器窗口就好了。版本回退了好几个也会出现，经过不懈努力我找到复现的方法了，请问怎么给你呢

**Comment by cuiliang** [comment]
@zhch25 可以邮件到197906@qq.com 邮箱。
