### ISSUE TITLE
屏幕左上角出现一条白色线

### ISSUE THREAD

**Issue by hclwsyw** [cuiliang/QuickPadCn#1545]
**描述BUG**
屏幕左上角出现一条白色线
重启quicker之后白色的线暂时消失

**相关截图**

![quicker bug](https://user-images.githubusercontent.com/45456256/139170652-80f8a465-fd99-40b5-a136-1095ad9e944c.png)

**环境信息:**
 - win10
 - Quicker版本：1.26.21

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
白线一直存在么？试一下在托盘菜单里 “关闭所有悬浮按钮” 看看能不能消除。

**Comment by JohnnyWoong** [comment]
...原来这是quicker导致的? 我一直不知道是什么东西引起的

**Comment by cuiliang** [comment]
> ...原来这是quicker导致的? 我一直不知道是什么东西引起的

现在还有么？ 用最新版本，我记得修复了。 https://getquicker.net/Help/Versions

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by hclwsyw** [comment]
已经没有问题了，大佬辛苦，爱你，么么~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 屏幕左上角出现一条白色线 (Issue #1545)





 
先关了，如果还有问题，请再reopen
