### ISSUE TITLE
鼠标手势, 如果手势第一划拉的很长, 那第二划同样需要拉很长才能识别

### ISSUE THREAD

**Issue by zsneala** [cuiliang/QuickPadCn#1547]
**需求描述**
想用此功能代替chrome插件SmartUp的手势功能, 因为chrome插件在一些页面是无法工作的

**描述你想要的解决方案**
手势识别是否可以改为SmartUp那样的逻辑

**描述您考虑过的替代方案**
识别的时候忽略过长的部分?

 **其他上下文**
SmartUp:
![SmartUp](https://user-images.githubusercontent.com/50451654/139571825-2dba1695-0abf-4fa4-ab9f-c0fa5cf9c4f1.gif)
Quicker:
![Quicker](https://user-images.githubusercontent.com/50451654/139571852-3d6dde90-63c9-4c9d-8865-141eb9ab60a6.gif)

**Comment by cuiliang** [comment]
是的，这是两种不同的手势识别算法。 一种是按整体图形，一种是按折线顺序，各有优缺点吧。

**Comment by zsneala** [comment]
可以新增这种识别算法吗

返回顶部的操作经常被识别为到下一个标签页

**Comment by cuiliang** [comment]
todo 清单比较长，短期不考虑增加这种了。

**Comment by cuiliang** [comment]
归档
