### ISSUE TITLE
win11 系统自带计算器启动失败

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1548]
升级了win11，quicker中固定了系统自带的计算器，启动时偶尔会失败，重新添加动作也偶尔会出现这个问题
![image](https://user-images.githubusercontent.com/34650487/139648530-2263fb83-5bac-4086-bb49-749bd1a4e165.png)

**Comment by cuiliang** [comment]
截图看下动作定义

**Comment by DogeFlow** [comment]
> 截图看下动作定义

![image](https://user-images.githubusercontent.com/34650487/139759447-e6c0879e-58d0-4a32-b976-4dcfa8c05d72.png)

**Comment by cuiliang** [comment]
之前默认应该是calc命令吧，也会有类似的现象？
看起来是系统问题，出错的时候看看windows是不是在更新之类的。

**Comment by DogeFlow** [comment]
> 之前默认应该是calc命令吧，也会有类似的现象？ 看起来是系统问题，出错的时候看看windows是不是在更新之类的。

重启quicker就可以了，好像是和系统更新有关。10月更新至win11后，大概出现过三次这种情况。

**Comment by cuiliang** [comment]
嗯，这个应该和quicker没有关系，quicker只是告诉系统运行calc这个命令，如果这时候正好windows在更新计算器程序就会出错。 改成UWP以后，计算器更新的比较频繁了。
