### ISSUE TITLE
有方法删除下面的窗口么？

### ISSUE THREAD

**Issue by billowssun** [cuiliang/QuickPadCn#1549]
我的需求很简单，只有几个通用的功能，所以上面的格子已经够用了，下面的没有任何应用，空着看起来很不舒服，发现好像不能删除，请问下官方有添加此功能的想法吗？

**Comment by cuiliang** [comment]
你可以试试这个动作 https://getquicker.net/Sharedaction?code=d6a48e4e-4afb-4346-6dee-08d887b8882d 
或者也可以使用轮盘。
目前还没有修改布局的计划，后期可能会有。

**Comment by billowssun** [comment]
好的，了解，谢谢。

发件人: ***@***.***>
发送时间: 2021年11月2日 22:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cuiliang/Quicker] 有方法删除下面的窗口么？ (Issue #1549)


你可以试试这个动作 https://getquicker.net/Sharedaction?code=d6a48e4e-4afb-4346-6dee-08d887b8882d
或者也可以使用轮盘。

―
