### ISSUE TITLE
"用户选择"的搜索界面, 高亮不准确, 搜索结果不准确, 打开有点延迟

### ISSUE THREAD

**Issue by andy1990zx** [cuiliang/QuickPadCn#1550]
**描述BUG**
"用户选择"的搜索界面:
问题1: 高亮不准确
问题2: 搜索结果不准确
问题3: 按下热键之后, 感受到有大约不到一秒的延迟, 能否减少呢?

**重现步骤**
打开"用户选择"的搜索界面

**相关截图**

问题1: 高亮不准确
![image](https://user-images.githubusercontent.com/37032134/140014730-e7512fc0-a22c-488b-830d-6808397e5d07.png)

问题2: 搜索结果不准确
![image](https://user-images.githubusercontent.com/37032134/140014866-9bdc41fd-f5f2-4b29-83aa-3cf09cf501b4.png)
第二行的内容就是图片中|后面的部分 (我的文件格式是A|B|||B的形式, 分隔符用的|||, 例如: 电话号码|13888888888|||1388888888)

问题3没有截图

**环境信息:**
 - 操作系统版本：Win10
 - Quicker版本：1.27.2

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
高亮不准确是正常的，因为要支持拼音匹配，一个文本有很多可能的匹配方式。
结果不准确，不是很明白。另外如果一个选项之前选择了（通过默认值参数），筛序的时候会保留。
动作快捷键？为了避免动作里模拟的快捷键和当前按下的键组合成新的快捷键组合，所以要抬起之后才会触发动作。后来的版本已经可以设置是不是按下就立即触发了，如果动作里没有可能产生冲突的操作，可以开启一下。

![image](https://user-images.githubusercontent.com/1972649/140016891-c96cf36c-c82e-4668-afc2-3dce8572f048.png)

**Comment by andy1990zx** [comment]
> 高亮不准确是正常的，因为要支持拼音匹配，一个文本有很多可能的匹配方式。 结果不准确，不是很明白。另外如果一个选项之前选择了（通过默认值参数），筛序的时候会保留。 动作快捷键？为了避免动作里模拟的快捷键和当前按下的键组合成新的快捷键组合，所以要抬起之后才会触发动作。后来的版本已经可以设置是不是按下就立即触发了，如果动作里没有可能产生冲突的操作，可以开启一下。
> 
> ![image](https://user-images.githubusercontent.com/1972649/140016891-c96cf36c-c82e-4668-afc2-3dce8572f048.png)

1. 高亮不准确, 主要是说候选里面有完整符合os这两个字母的内容 (第一行的close3, 连大小写都一样, 第二行和第三行都有大小写不一样的os), 可是也没有被高亮, 这个不能用多种匹配方式来解释吧?
2. 结果不准确, 我搜索RAMOS, 它给出的第二行跟RAMOS一点关系都没有... Redfish地址|一堆数字, 这个是怎么匹配上RAMOS的?
3. 设置之后也一样, 主要是按键之后到窗口弹出, 有一个不到一秒的延迟, 不知道是故意设计还是软件消耗了太多时间去运行

**Comment by cuiliang** [comment]
1. 英文的匹配 最初是按单词拆分的   hello world => 可以用hw匹配， ello这种其实不应该匹配上，因为一般人输入不会从中间开始。但是有些情况匹配不上，所以把contains的结果也显示了。 
2. 上面说了，预先选择的项会保留，不然选择状态就丢失了，不能回车直接确认了。
3.  有可能。可以试试直接从面板运行动作看看有没有什么差别。如果面板上和快捷键反应差不多，应该就是其他因素了。

**Comment by andy1990zx** [comment]
> 1. 英文的匹配 最初是按单词拆分的   hello world => 可以用hw匹配， ello这种其实不应该匹配上，因为一般人输入不会从中间开始。但是有些情况匹配不上，所以把contains的结果也显示了。
> 2. 上面说了，预先选择的项会保留，不然选择状态就丢失了，不能回车直接确认了。
> 3. 有可能。可以试试直接从面板运行动作看看有没有什么差别。如果面板上和快捷键反应差不多，应该就是其他因素了。

1. 从中间输入也很常见, 比如电话号码, 我输入号码, 或者hm, 建议这个可以优化一下
2. 基本上是你说的这样, 但是随着输入的变多, 匹配不符之后就要删掉才合理. 另外发现输入RAMOS关键字, 速度快或速度慢, 结果就有差异, 暂时没搞清规律
3. 面板运行时间也差不多

**Comment by cuiliang** [comment]
嗯，这个匹配算法比较复杂，要支持中英文和拼音，等有时间再研究研究，现在坑太多了😂

弹出时间差不多说明不是快捷键的原因，可能电脑比较累。
