### ISSUE TITLE
动作标题显示-纯文本不要图标情况下放大显示，当前字有点小

### ISSUE THREAD

**Issue by 760985933** [cuiliang/QuickPadCn#1551]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
纯文本不要图标情况下，字大小可以放大显示，当前字有点小

 **其他上下文**
![image](https://user-images.githubusercontent.com/23353564/140462517-dcc61d7d-901b-4a50-bf0c-21826f57ef8b.png)

**Comment by cuiliang** [comment]
格子就那么大，或者缩小，或者显示不全，或者使用\n插入换行。
配置里有个选项可以改成不缩小。

**Comment by cuiliang** [comment]
在这里：
![image](https://user-images.githubusercontent.com/1972649/140528786-5db96203-1aff-4922-9ca6-0d0f9c708f37.png)
先关了，如果还有问题，请再reopen
