### ISSUE TITLE
Volume2导致动作页无法用鼠标滚轮切换

### ISSUE THREAD

**Issue by lnf920** [cuiliang/QuickPadCn#1552]
Volume2导致动作页无法用鼠标滚轮切换。
不知道这是为何，翻了volume2的选项，也没有找到与之相关的开关。
不知道有没有朋友遇到过和我一样的问题，你们又是怎样解决的？望不吝分享。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/140631514-c363783e-64bd-48c3-b45f-cd8317bd4fdf.png)
禁用鼠标试试。

**Comment by lnf920** [comment]
搞定了，在选项“滚轮控制非活动窗口”里添加并禁用quicker.exe就好了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月7日(星期天) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] Volume2导致动作页无法用鼠标滚轮切换 (Issue #1552)





 

 禁用鼠标试试。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiliang** [comment]
好的
