### ISSUE TITLE
问题摘要:鼠标来回滑动，quicker界面花屏

### ISSUE THREAD

**Issue by Xiayuno11** [cuiliang/QuickPadCn#1553]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.鼠标滑动，滑过的区域跟随出现花屏现象
2.来回滑动会重复出现

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win10
 - Quicker版本：1.27.13

**附加信息**
在此添加有关此问题的任何其他上下文。
![huale](https://user-images.githubusercontent.com/92721254/140677300-f2eb17ce-de5c-4412-a63b-20c271f9595a.jpg)
![huale2](https://user-images.githubusercontent.com/92721254/140677362-d5523528-7bca-4414-a4af-1e78e802071e.jpg)

https://user-images.githubusercontent.com/92721254/140677483-bff5be54-ecc8-4754-862a-71f859e7191b.mp4

**Comment by cuiliang** [comment]
这个估计是一个显卡有关的问题，可以试试更换一下显卡驱动版本。

**Comment by cuiliang** [comment]
请参考这个链接试试里面的解决方法：
https://blog.walterlv.com/post/wpf-renders-wrong-because-of-nahimicosd.html#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95

**Comment by Xiayuno11** [comment]
感谢 将组件更完名之后重启确实不糊了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 晚上9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 问题摘要:鼠标来回滑动，quicker界面花屏 (Issue #1553)





 
请参考这个链接试试里面的解决方法：
 https://blog.walterlv.com/post/wpf-renders-wrong-because-of-nahimicosd.html#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
