### ISSUE TITLE
面板窗口翻页

### ISSUE THREAD

**Issue by TMDW** [cuiliang/QuickPadCn#1554]
**面板窗口翻页**
有多个面板窗口时，不同面板窗口之间切换的按钮太小，换页不方便，是否可以在设计ui时将换页的点改大一点，或者通过其他设置按钮，使得换页更便捷

![image](https://user-images.githubusercontent.com/74757345/140683499-9f530ffd-2fc0-4660-96ce-516d0204bf2e.png)

**Comment by cuiliang** [comment]
直接使用鼠标滚轮翻页，那个点只是附加的可以点击方便使用触控笔。

**Comment by TMDW** [comment]
好的好的，谢谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CuiLiang ***@***.***&gt;
发送时间: 2021年11月8日 12:18
收件人: cuiliang/Quicker ***@***.***&gt;
抄送: TMDW ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [cuiliang/Quicker] 面板窗口翻页 (Issue #1554)
