### ISSUE TITLE
在桌面上利用鼠标手势向右上划动，为关闭文档，但是直接导致桌面图标隐藏了，而且右键菜单也没有了。

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1555]
**描述BUG**
在桌面上利用鼠标手势向右上划动，为关闭文档，但是直接导致桌面图标隐藏了，而且右键菜单也没有了。

**环境信息:**
 - 操作系统版本：10
 - Quicker版本：最新版

**Comment by cuiliang** [comment]
请截图看下手势里的设置，是出发的什么操作？另外请写详细版本号，最新版有好几个

**Comment by baileichao** [comment]
![QQ拼音截图20211114112338](https://user-images.githubusercontent.com/57392772/141666201-a2d76a34-9b3d-46f7-b118-b0ebd844b8f2.png)

**Comment by baileichao** [comment]
版本号：1.27.13

**Comment by baileichao** [comment]
以前在桌面上直接用这个手势，直接弹出来的是关闭电脑的界面，但是现在的版本是直接将桌面图标给隐藏了，当再次用这个手势的时候，才会弹出关闭电脑的界面。
![QQ拼音截图20211114113211](https://user-images.githubusercontent.com/57392772/141666322-5e83b959-ade3-4698-8353-6048e25e8d3e.png)

**Comment by cuiliang** [comment]
有安装什么第三方桌面插件软件么？ 原来是发送Alt_F4，现在改为发送给WM_CLOSE消息了。 这个消息对系统原生的桌面效果是一样的，也是这个关闭Windows的界面，但如果是第三方的桌面插件，可能效果就是关掉了那个插件的窗口。

**Comment by baileichao** [comment]
没有安装任何的第三方插件，那可能就是WM_CLOSE消息关闭了windows界面吧，主要是桌面的图标都隐藏了，还没法再显示出来了，必须重新启动电脑才行。以前在桌面用这个手势，直接就是弹出关闭windows的界面，感觉很方便的，现在好像是会出现如上的问题了。

**Comment by cuiliang** [comment]
@baileichao Windows详细版本号是多少？ 可以winver命令查看一下。

**Comment by baileichao** [comment]
![image](https://user-images.githubusercontent.com/57392772/141709146-592808cf-3bf7-425c-8962-0c091feb68bd.png)

**Comment by cuiliang** [comment]
哦，看起来版本还挺新的，但是企业版又比较少见。 可以把这里改成一个发送模拟Alt+F4的操作。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/141709300-fa70796d-9d88-468b-b204-3304437929da.png)

**Comment by baileichao** [comment]
好的，非常感谢。

**Comment by cuiliang** [comment]
这个现象方便录个屏么？ 我再看看有没有别的线索，本地在win10专业版和win11下都没有这个问题。

**Comment by baileichao** [comment]
![动画](https://user-images.githubusercontent.com/57392772/141883818-4b5ccc58-8361-4364-b5a6-3905102126bb.gif)
![QQ拼音截图20211116100931](https://user-images.githubusercontent.com/57392772/141883832-61fa7da0-a97d-4c9a-a4f8-a8d37597239b.png)
如动画所示，实际上第一次的这个手势是隐藏了桌面图标，第二次没有反应，第三次的时候，才会调出关机界面。

**Comment by cuiliang** [comment]
感谢。 1.27.24 版本已修复了这个问题 https://getquicker.net/Help/Versions
