### ISSUE TITLE
excel格式变化

### ISSUE THREAD

**Issue by changyu230** [cuiliang/QuickPadCn#1557]
**描述BUG**
使用了Quicker后，excel的背景主题格式发生了变化，且无法更改,怎么可以恢复到以前？

**相关截图**
![1637140143(1)](https://user-images.githubusercontent.com/94524529/142170960-eba74b46-bdb7-42b6-932d-d6ca756133a7.jpg)

- 

**环境信息:**
 - 操作系统版本：Windows11 专业版 21H2
 - Quicker版本：1.27.20

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个和Quicker应该没有关系的，Quicker里没有更改Excel主题的功能。

**Comment by changyu230** [comment]
可是确实是在下午安装Quicker后就这样了啊？

**Comment by cuiliang** [comment]
可能是巧合吧，你再找找其他原因看看。
看起来像是office 365升级了。 我这里也变了。
![image](https://user-images.githubusercontent.com/1972649/142171787-5a987834-ce22-4b0c-8517-4f5562729a96.png)

**Comment by changyu230** [comment]
你那个是升级成365了，我这个不是啊，
![image](https://user-images.githubusercontent.com/94524529/142172597-98832fcf-42c3-4024-afb7-d1a037bf2c6f.png)
ye'zhi也只添加了这几个动作啊，就变成这样了

**Comment by cuiliang** [comment]
@changyu230 可以确定和Quicker没有关系的。它是会自动升级的。
