### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by changyu230** [cuiliang/QuickPadCn#1558]
**描述BUG**
笔记本在盒盖休眠/不盒盖黑屏休眠后一段时间内（一小时左右）风扇会突然唤醒狂转，而且不是一直转，是有规律的一下一下的转动，声音特别大，以为会转几分钟就不转了，但是一直会持续十几分钟还在转，这时都会受不了打开盖子，风扇会最大声音转动 1 分钟左右，就又安静了。
此种情况在10月7日升级win11之后出现，当时还没有安装Quicker，使用得是uTools，且在win10的时候正常使用均没出现过上述情况。后来经过自己排查是uTools得问题，遂卸载，又换回使用Quicker，但是这种情况又出现了，在测试排查过盒盖休眠之前退出Quicker，没有发生上述情况。
不知道是我个例原因还是共性原因，后台第三方程序有 微信、TIM、网易邮箱、WGestures 1.8.4.0、MacType、TrafficMonitor、OneQuick、Everything，请教知道是什么设置会唤醒win11的风扇或者和Quicker某个功能冲突。

**重现步骤**
1.
2.

**相关截图**
Quicker动作页截图
![image](https://user-images.githubusercontent.com/94524529/142578694-3980976e-5c44-4e29-bcd5-14e98e495a4a.png)

**环境信息:**
 - 操作系统版本：戴尔 XPS 15 7590 i5 版本，系统Windows 11 21H2 专业版，
 - Quicker版本：1.27.20

**附加信息**

**Comment by cuiliang** [comment]
如果休眠成功了，Quicker是没有办法唤醒Windows的。 
可以看一下Windows的事件查看器中唤醒的那个时间有没有什么记录。

我猜测可能是睡眠到休眠的转换发生了。 刚开始只是睡眠，数据没有写入磁盘，到一定时间内如果没有开机，windows会转换为休眠模式，这时候会需要把内存数据写入磁盘。

====
https://zhuanlan.zhihu.com/p/26804876
睡眠模式，电脑是通电待机状态，桌面状态保存到内存中，唤醒快速，中途断电数据会丢失。 休眠模式，电源关闭，桌面状态保存到硬盘中，唤醒慢，断电数据会保留。 从保护数据和省电的角度，工作力建议使用休眠模式。

**Comment by changyu230** [comment]
麻烦了，win11好像默认只有睡眠模式了，没有休眠了
![image](https://user-images.githubusercontent.com/94524529/142587863-70ac64c8-5354-4cfa-9174-18ecb216c3f3.png)
![image](https://user-images.githubusercontent.com/94524529/142587968-c9e4314a-7903-4fc7-8987-548bc188835a.png)

**Comment by changyu230** [comment]
14:21----14:26左右发生的盒盖情况下风扇转动，看不出具体错误
![image](https://user-images.githubusercontent.com/94524529/142588100-50209e05-02b5-4a65-9bfe-cf0e5fb7a276.png)

**Comment by cuiliang** [comment]
可以点开开详细信息的。第二行是个windows更新相关的，下面的再详细看看，百度一下。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
