### ISSUE TITLE
用搜狗浏览器的网页右键无法使用

### ISSUE THREAD

**Issue by wangang1008** [cuiliang/QuickPadCn#1560]
**用搜狗浏览器的网页右键无法使用**
quicker设置的是长按右键弹出面板，在用搜狗浏览器的时候，单击右键没有反应。
其他的浏览器都没有问题。
请问如何解决
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
关闭搜狗浏览器的鼠标手势功能就可以了。
![image](https://user-images.githubusercontent.com/1972649/143526201-5815dba2-d9e0-4b7c-87e4-a3e505c3cf0f.png)

**Comment by wangang1008** [comment]
可是我想要鼠标手势的功能，qq浏览器就开启鼠标手势也可以正常点右键。

**Comment by cuiliang** [comment]
这个情况需要搜狗那边处理才行，quicker里没有办法处理。 或者不在搜狗上用Quicker，把搜狗加到Quicker的后面的里。

wangang1008 ***@***.***> 于2021年11月26日周五 下午12:23写道：

**Comment by cuiliang** [comment]
另外Quicker本身也有手势功能。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions
似乎找到了这个问题的原因，刚更新了一版可以试下是否解决。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
