### ISSUE TITLE
文本指令可否增加立即触发的选项

### ISSUE THREAD

**Issue by pythonlouvre** [cuiliang/QuickPadCn#1561]
类似于PhraseExpress里面是可以设置输入完指令，就会立即触发替换的动作，希望增加此选项，因为我的指令很少有不去替换的情况，这样可以少按一次键盘。

**Comment by cuiliang** [comment]
虽然可以实现，但是感觉有点太容易误触发了。您在PhraseExpress里一般都是用的什么样的指令字符来避免误触发的问题呢？

**Comment by pythonlouvre** [comment]
> 虽然可以实现，但是感觉有点太容易误触发了。您在PhraseExpress里一般都是用的什么样的指令字符来避免误触发的问题呢？

sdate：简单的日期格式，ddate：复杂的日期格式，qqmail：我的邮箱地址之类，这个误不误触发我觉得让用户决定吧，对于这几个关键字，我用到现在正常输入都不会输这几个关键字。

**Comment by cuiliang** [comment]
将在1.33.17版本中加入。
