### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by liuzheng0577** [cuiliang/QuickPadCn#1562]
**描述BUG**
沙拉查词复制翻译 当出现fi或fl时无法识别
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/52264439/144955301-f3e59a2a-91a4-44d9-8c4d-f2cb06c11d88.png)

![屏幕截图 2021-12-07 103008](https://user-images.githubusercontent.com/52264439/144955672-4a6c3e88-8e9d-4a1b-8592-02fe5dc6d152.png)

**环境信息:**
 - 操作系统版本：windows10
 - Quicker版本：1.27.13

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
OCR么？ 这个应该是正常的，OCR本身也会遇到识别错误的情况。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
