### ISSUE TITLE
动作库失焦

### ISSUE THREAD

**Issue by StudentWeis** [cuiliang/QuickPadCn#1563]
**描述BUG**
在特定软件场景中，点开动作库之后会出现**失焦**的情况。场景功能中的表格会切回“默认”，这导致无法向特定场景添加动作。

**重现步骤**
1. 打开特定软件，比如 Typora；
2. 弹出 Quicker 面板；
3. 打开工具箱；
4. 点击 Quicker 面板；
5. 这时，当我们点击工具箱中的动作时，会自动切换到“默认”场景，而不是所希望的特定场景。

**相关截图**
![Quicker Issue-动作库失焦](https://s2.loli.net/2021/12/07/cQi6pn2hH7WlUa3.gif)

**环境信息:**
 - 操作系统版本：Windows 10 21H1
 - Quicker版本：1.28.4

**Comment by cuiliang** [comment]
感谢反馈！
另外，目前更建议在网页查看动作，信息会比较全面。

**Comment by StudentWeis** [comment]
好的，谢谢！

**Comment by cuiliang** [comment]
1.28.16 修改为打开工具箱时锁定切换动作页。
