### ISSUE TITLE
悬浮按钮支持可否支持贴边收缩

### ISSUE THREAD

**Issue by pythonlouvre** [cuiliang/QuickPadCn#1564]
我是将整个页悬浮了。

然后这个按钮如果不贴边，会影响按钮下面的操作，能否将这个按钮贴边，同时能完整弹出所有的内容。

![image](https://user-images.githubusercontent.com/651199/145225154-6f8adde7-5679-4187-bdc3-f49b8fec73c3.png)

**Comment by cuiliang** [comment]
这个实现起来比较困难。悬浮主要是临时使用的考虑，避免放到可能影响操作的地方。
也可以试下“捷径面板”动作，是支持贴边隐藏的。https://getquicker.net/Sharedaction?code=d6a48e4e-4afb-4346-6dee-08d887b8882d

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
