### ISSUE TITLE
鼠标手势卡顿

### ISSUE THREAD

**Issue by pythonlouvre** [cuiliang/QuickPadCn#1565]
从strokeitplus.net转过来的，右键绘制手势的时候会卡顿，没有s流畅。

**Comment by cuiliang** [comment]
电脑是什么配置呢？方便的话可以录个屏对比一下。
另外两个实现技术可能不太一样，Quicker是基于WPF、stroke可能是基于WINFORM。 WPF会对显卡要求高一点

**Comment by pythonlouvre** [comment]
小米air 13
CPU i7-7500U 2.7GHZ
内存 8G
集成显卡
配置稍微有点老，但应该还不算太差吧。因为也不是经常出现，但确实用过strokeit之后转到quicker还是感觉很明显，我又试了几次，感觉可能跟右键拖动的识别有关，quicker有时候在手势刚开始的时候如果画的比较慢，就有可能不会触发手势识别。

> 电脑是什么配置呢？方便的话可以录个屏对比一下。 另外两个实现技术可能不太一样，Quicker是基于WPF、stroke可能是基于WINFORM。 WPF会对显卡要求高一点

**Comment by cuiliang** [comment]
方便的时候可以录个屏或手机录一下对比看看，我自己电脑性能比较强，比较难以复现这样的情况，不太有感性认识😂。

**Comment by pythonlouvre** [comment]
![动画](https://user-images.githubusercontent.com/651199/145927441-bed744e4-42b7-4a5c-a5ee-be43ced7906f.gif)

就是不是性能的问题，是右键拖动如果速度较慢，就不会触发手势的问题，见上面动画。

**Comment by cuiliang** [comment]
我这里测试没有这个现象额。 看一下这两个参数设置的多少。
![image](https://user-images.githubusercontent.com/1972649/145932159-3abfbe06-c31a-467d-b0b7-abb0062de76b.png)

**Comment by pythonlouvre** [comment]
![image](https://user-images.githubusercontent.com/651199/145934302-d3cf9b49-390f-481e-9458-161039dcfe8a.png)

**Comment by pythonlouvre** [comment]
可以了，自动检测鼠标挂钩丢失勾上就可以了

**Comment by cuiliang** [comment]
试一下把其它软件（特别是手势之类的使用挂钩的软件）都退出看看有没有影响的。

https://user-images.githubusercontent.com/1972649/145934580-5e81ed64-0469-46bb-b2fc-c743da6d0004.mp4
