### ISSUE TITLE
知网研学内触发软件边框异常

### ISSUE THREAD

**Issue by ACE220284Luffy** [cuiliang/QuickPadCn#1566]
**描述BUG**
win10专业版，知网研学（原E-Study）5.5.3 Build@2021-09-09版本，使用Quicker版本1.27.24时，Quicker界面边框发生变宽现象

**重现步骤**
1.打开知网研学
2.打开Quicker，Quicker边框变宽

**相关截图**
正常界面：
![image](https://user-images.githubusercontent.com/87253240/145551198-9333d63f-1bb6-4da5-8969-4381d74b6a13.png)
知网研学内非正常界面：
![image](https://user-images.githubusercontent.com/87253240/145551363-3bd5cfc3-22d9-409c-b1df-a2e2b3265443.png)

**环境信息:**
 - 操作系统版本：Windows 10 专业版  20H2
 - Quicker版本：1.27.24

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这是因为底下的提示文字把窗口撑开了一些。
可以开启这个选项不再显示提示。
![image](https://user-images.githubusercontent.com/1972649/145567532-ff5ab571-43dd-40a9-8d97-38be5e1f5987.png)
