### ISSUE TITLE
vmware虚拟机里鼠标中键按一下是触发两次

### ISSUE THREAD

**Issue by lhtuling** [cuiliang/QuickPadCn#1567]
**描述BUG**
https://getquicker.net/QA/Question/1958
在论坛上看到有同样问题  现在我也碰到了

**重现步骤**
1.本机上安装quicker 并开启   vm虚拟机正常安装windows 无特殊环境   虚拟机不安装quicker
2.本机quicker开启情况下  在虚拟机中操作  鼠标中键单击变双击   
3.本机quicker关闭    在虚拟机中操作  鼠标中键单击正常

**相关截图**
![image](https://user-images.githubusercontent.com/44140500/145700655-3fecf14c-cef6-4be7-946f-4b702847c641.png)

**环境信息:**
 - 操作系统版本：主机win11  虚拟机win11
 - Quicker版本：1.27.24

**附加信息**
希望解决一下不然需要频繁关闭quicker

**Comment by cuiliang** [comment]
VMWare的几个进程全都加一下黑名单，还有一个无法识别的那个也加一下。
![image](https://user-images.githubusercontent.com/1972649/145703220-5e457ec3-8b68-4495-b1d9-e383a37d3102.png)

**Comment by lhtuling** [comment]
好的  我试试看

**Comment by lhtuling** [comment]
> VMWare的几个进程全都加一下黑名单，还有一个无法识别的那个也加一下。 ![image](https://user-images.githubusercontent.com/1972649/145703220-5e457ec3-8b68-4495-b1d9-e383a37d3102.png)

这样是解决了不过不算根本解决吧~~    我如果虚拟机用还要再虚拟机里单独装一个~~

**Comment by lhtuling** [comment]
找到解决方法了就先关闭了！

**Comment by Demante** [comment]
截至2024年4月14号，该问题还尚未修复；打开quicker后，操作Ubuntu时，右键出现双击，解决方法就是关闭quicker；

**Comment by cuiliang** [comment]
@Demante 参考第二个回帖，以及这个文档里 https://getquicker.net/KC/Kb/Article/986

**Comment by Demante** [comment]
> @Demante 参考第二个回帖，以及这个文档里 https://getquicker.net/KC/Kb/Article/986

谢谢，这个我尝试过还是不生效；我这边的解决方法尝试出两个，方法一：关闭quicker；方法二：按该方法添加Vmware.exe黑名单+再添加无法识别的应用+添加vmware的安装目录，即可解决该问题；

**Comment by cuiliang** [comment]
@Demante 好 👍

**Comment by 745028848** [comment]
有用，解决了！
