### ISSUE TITLE
希望可以增加“鼠标滚轮自然滚动”的功能

### ISSUE THREAD

**Issue by soulans** [cuiliang/QuickPadCn#1568]
Windows 和 Mac 天生对鼠标滚动滚轮这一操作有着不同的理解，希望 Quicker 可以增加一个”自然滚动“的功能，使得 Windows 的滚轮可以模拟 Mac 上那种，鼠标滚轮滚动的是页面，而不是滚动滚动条的效果。
谢谢！

**Comment by cuiliang** [comment]
可以试试这个
![image](https://user-images.githubusercontent.com/1972649/146105760-643f7f50-ef68-49a4-9462-25cec0282527.png)

**Comment by soulans** [comment]
> 

原来是这个按钮！谢谢！！
另外增加一个小建议，这里可以增加一个黑白名单的设置吗？虽然感觉用”高级鼠标触发“也能实现，但是还是这里实现更方便吗。
再次谢谢~

**Comment by cuiliang** [comment]
那样就太复杂了，你想每个参数其实都可以加黑名单，最后整个软件就是到处充满各种设置，也容易出问题。结果就是没法用了。。。

soulans ***@***.***> 于2021年12月15日周三 09:36写道：
