### ISSUE TITLE
鼠标手势页面里的动作希望可以增加拖动排序功能（甚至可以搞一个分组功能？）

### ISSUE THREAD

**Issue by soulans** [cuiliang/QuickPadCn#1569]
鼠标手势这个功能真的太强大了，但是随着增加的手势越来越多，管理上的需求就自然而然的萌生了。
希望能增加一个拖动排序的功能，最好再支持一个分组功能就更好了！
谢谢！

**Comment by cuiliang** [comment]
目前是按轨迹名称排序的。 
其它管理方式会带来额外的复杂性，暂时不太考虑了。另外手势图形也不建议太多，感觉可能会想不起来😶‍🌫️

**Comment by soulans** [comment]
> 目前是按轨迹名称排序的。 其它管理方式会带来额外的复杂性，暂时不太考虑了。另外手势图形也不建议太多，感觉可能会想不起来😶‍🌫️

嗯嗯！了解啦~
