### ISSUE TITLE
文本窗口的json格式加入数组级别的折叠

### ISSUE THREAD

**Issue by zyufstudio** [cuiliang/QuickPadCn#1570]
**需求描述**
文本窗口显示json时，数组不能折叠，不很方便

**描述你想要的解决方案**
数组像对象那样可以折叠

 **其他上下文**
![image](https://user-images.githubusercontent.com/52726576/146137302-3fbbe03e-bc7e-4cb1-8f6c-12a797209376.png)

**Comment by cuiliang** [comment]
控件不支持这个功能 :(
