### ISSUE TITLE
可以借鉴或者尝试pandoc

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1571]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
[Pandoc - About pandoc](https://pandoc.org/)
About pandoc关于 pandoc
If you need to convert files from one markup format into another, pandoc is your swiss-army knife. Pandoc can convert between the following formats:
如果您需要将文件从一种标记格式转换为另一种标记格式，pandoc 就是您的瑞士军刀。可以在以下格式之间进行转换:
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
之前发文件还有翻译文件被群管理撤回了

**Comment by cuiliang** [comment]
没太明白，借鉴哪方面呢？ 往群里发文件最好事先说一下，还有打个包发，不然会被认为是机器人或者盗号的。
