### ISSUE TITLE
quick快捷键响应问题

### ISSUE THREAD

**Issue by amaoo** [cuiliang/QuickPadCn#1572]
**需求描述**
笔记本和另一台电脑都装有quicker，并且都已登录账号，当通过笔记本远程（微软远程桌面）到另一台电脑时，按快捷键调出quicker，响应的是笔记本的quicker，会导致一些操作无法进行。比如翻译等。

**描述你想要的解决方案**
是否可以给同步数据功能加个开关，笔记本和远程设备采用不同快捷键，应该可以避免这类问题。

**描述您考虑过的替代方案**

 **其他上下文**

**Comment by cuiliang** [comment]
可以使用单击Ctrl激活的方式，如果全屏方式远程，左Ctrl激活远程的，右Ctrl激活本地的。

**Comment by amaoo** [comment]
@cuiliang 由于两台电脑采用的是同一个账号，修改一个另一个不是也就同步了吗？

**Comment by cuiliang** [comment]
远程的时候为什么会需要激活本机的quicker呢？ 翻译也可以直接在远程的电脑上翻译的吧？
我之前遇到的情况都是在远程的时候禁用本机的quicker，可以添加黑名单或全屏禁用的方式实现。
数据同步很难加特别详细的选项，不能这个设置同步那个设置不同步，那样太复杂了不太有可行性。

**Comment by amaoo** [comment]
@cuiliang 
> 我之前遇到的情况都是在远程的时候禁用本机的quicker，可以添加黑名单或全屏禁用的方式实现。


可能是我没有表述清楚，就是说的这个，谢谢
