### ISSUE TITLE
问题摘要：扩展热键的反应有点慢

### ISSUE THREAD

**Issue by remoon1991** [cuiliang/QuickPadCn#1574]
**描述BUG**
我用ctrl+Space替换Caps实现大小写切换，类似于开发者自己开发的Caps2CtrlSpace软件。能明显感觉quicker扩展热键在快速输入时存在延迟，尤其是在一些软件中（欧路词典）。我将扩展热键 设置中的间隔和延迟都调整过，但似乎依然很慢。
比如Cap和A连续反复敲击，Caps2CtrlSpace依然能输出aaaaa，但quicker会卡主一个字母也打不出来。

**相关截图**
![image](https://user-images.githubusercontent.com/35791556/147877114-80e880e5-cd1b-47b4-8e19-902eb011e1f7.png)

**环境信息:**
 - 操作系统版本：win10 21H2最新版
 - Quicker版本：1.27.24

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
https://getquicker.net/QA/Question/8939 已在这里回复。

**Comment by remoon1991** [comment]
谢谢您
Best wishes
