### ISSUE TITLE
部分动作图标异常

### ISSUE THREAD

**Issue by cyber-dogy** [cuiliang/QuickPadCn#1575]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.打开任意动作
2.鼠标在动作上移动后会出现图标异常（图1）
3.软件界面内也存在类似问题，例如帮助与反馈（图2）

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/92865186/149073028-a4ab4245-181d-4628-8830-9d044a966f06.png)
![image](https://user-images.githubusercontent.com/92865186/149073204-6cd9dadf-3919-48f0-b01f-e6fc8038178a.png)

**环境信息:**
 - 操作系统版本：windows 10
 - Quicker版本：1.28.14

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Kb/Article/973 
https://blog.walterlv.com/post/wpf-renders-wrong-because-of-nahimicosd.html#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by cyber-dogy** [comment]
收到，问题已解决，按照教程修改了戴尔外星人电脑中的NahimicOSD.dll文件名后问题消失，感谢您的帮助！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 部分动作图标异常 (Issue #1575)





 
Closed #1575.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
