### ISSUE TITLE
搜索框匹配太模糊了, bug严重

### ISSUE THREAD

**Issue by andy1990zx** [cuiliang/QuickPadCn#1576]
![image](https://user-images.githubusercontent.com/37032134/149306807-a793bb64-f4c7-4eee-a954-094a55bca97a.png)
![image](https://user-images.githubusercontent.com/37032134/149307128-927f129a-a722-4db1-9401-41641e74ac06.png)
![image](https://user-images.githubusercontent.com/37032134/149307188-61093c1a-5834-4b11-849a-b36695da366f.png)

**Comment by cuiliang** [comment]
选项的值是什么？

**Comment by cuiliang** [comment]
另外选中的项会直接显示不受筛选的。
这个界面看起来是第一个选项已经选上了，所以不会被隐藏掉。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
