### ISSUE TITLE
动作库失焦修复带来的新问题

### ISSUE THREAD

**Issue by StudentWeis** [cuiliang/QuickPadCn#1577]
**需求描述**
#1563 动作库失焦 Bug 修复带来的新问题，打开工具箱时锁定切换动作页，但关掉工具箱之后依然是锁定的。即打开一次工具箱之后，动作页被锁定在上一次打开的应用中，无法切换，需要手动解锁。

**描述你想要的解决方案**
关掉工具箱时自动解锁。

**环境信息:**
- 操作系统版本：Windows 10 21H1
- Quicker版本：1.28.18

**Comment by cuiliang** [comment]
好，下一版加一个自动解锁。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 已更新1.28.19版本
