### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by TINKOUBUN** [cuiliang/QuickPadCn#1578]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.我的两台电脑现在在顶部滚动鼠标滚轮调节音量的时候都会造成任务栏刷新

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![local](https://user-images.githubusercontent.com/81556885/150068070-6df58dda-7816-48be-8983-d1b519ab4d63.gif)
**环境信息:**
 - 操作系统版本：
 - ![image](https://user-images.githubusercontent.com/81556885/150068117-05ffc169-8813-4a30-af66-07d0295d1558.png)
 - ![image](https://user-images.githubusercontent.com/81556885/150068171-443a13e1-0e89-4dda-8f43-55bc4cb871ca.png)

 - Quicker版本：
 - ![image](https://user-images.githubusercontent.com/81556885/150068131-85d9f953-3a73-47ab-8c75-11f8bafcd9cb.png)
 - ![image](https://user-images.githubusercontent.com/81556885/150068255-30c570a5-d72f-47f0-b8d4-0c96b2a02f31.png)

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Windows 11 的问题，需要等MS修复。

**Comment by TINKOUBUN** [comment]
> Windows 11 的问题，需要等MS修复。

hhh好快 我还说我图贴错了准备换一下 感谢回复

**Comment by cuiliang** [comment]
似乎已经修复了。 
![image](https://user-images.githubusercontent.com/1972649/150638819-2c763ac5-5ec4-47e6-b7cc-c9c49d8f0e14.png)
