### ISSUE TITLE
浏览器控制→对标签页执行脚本对onchange()事件不响应

### ISSUE THREAD

**Issue by BaldStrong** [cuiliang/QuickPadCn#1579]
我在开发一款操作网页元素的动作时，发现在浏览器控制→对标签页执行以下脚本时
```javascript
$('.input').trigger("onchange")
document.querySelector("#id").onchange()
// 两句话均无效
```
无效，网页的一个input，输入金额，会触发onchange事件，另一个只读input变成对应的大写金额，不知道是quicker的问题还是浏览器内核的问题。控制台执行是有效的。

目前的解决方式：onchange事件作为一个脚本，quicker主动手动执行该脚本。

环境信息：
Windows 10、11
Quicker版本：1.27.24
浏览器：edge 97.0.1072.62 (官方内部版本) (64 位)

**Comment by cuiliang** [comment]
在这里讨论了， https://getquicker.net/QA/Question/9172
