### ISSUE TITLE
不能删除手势场景

### ISSUE THREAD

**Issue by YandLiu** [cuiliang/QuickPadCn#1580]
刚发现Quicker居然只能添加新的手势场景，不能删除已有的
有的曾经添加的不想再用了，想删掉
![image](https://user-images.githubusercontent.com/26127104/150708632-9c94d96a-be6a-401c-bbd9-35d8a5297155.png)

**Comment by cuiliang** [comment]
这里是禁止删除的，避免有动作页什么的数据看不到。 
在动作和场景设置窗口中删除。
