### ISSUE TITLE
弹出菜单触发方式为长按右键，导致 VMware Workstation Linux虚拟机中右键失灵

### ISSUE THREAD

**Issue by LovelyQuantum** [cuiliang/QuickPadCn#1581]
**描述BUG**
弹出菜单触发方式为长按右键，导致 VMware Workstation Linux虚拟机中右键失灵，关闭quicker后恢复正常

**重现步骤**
1.打开 quicker
2.在 VMware Workstation 中打开Centos或Ubuntu虚拟机并在桌面上点击右键

**相关截图**
无

**环境信息:**
 - 操作系统版本：win11(build 22000.438)
 - Quicker版本：1.28.20
 - VMware Workstation版本：16.2.2

**附加信息**
无

**Comment by cuiliang** [comment]
添加黑名单，参考这里：https://getquicker.net/KC/Kb/Article/986

**Comment by LovelyQuantum** [comment]
> 添加黑名单，参考这里：https://getquicker.net/KC/Kb/Article/986

添加后问题依然存在

**Comment by cuiliang** [comment]
添加了几项？ 截图看下目前添加的

**Comment by cuiliang** [comment]
解决了么？
