### ISSUE TITLE
转盘第三层不存在动作时仍然会显示

### ISSUE THREAD

**Issue by xiayaopai** [cuiliang/QuickPadCn#1582]
**描述BUG**

转盘第三层(最外层)不存在动作时仍然会显示, 老版本会隐藏第三层

**重现步骤**
1. 进入设置->辅助功能->轮盘菜单->轮盘动作管理页面
2. 移除第三层(最外层)所有动作并保存更改
3. 呼出轮盘, 发现第三层不存在动作但仍然显示

**相关截图**
![image](https://user-images.githubusercontent.com/98437820/151089590-9950a707-0aa7-4b92-8791-17718cd8560c.png)

**环境信息:**
 - 操作系统版本：Windows 11 企业版 21H2 (22000.434)
 - Quicker版本：1.28.20

**附加信息**
- 无

**Comment by cuiliang** [comment]
用的什么方式触发的轮盘呢？ 
如果使用动作弹出的会显示第三圈，正常使用鼠标滑动方式触发的会隐藏。

**Comment by xiayaopai** [comment]
使用的动作弹出, 因为没用鼠标, 平时都使用触摸板, 我将触摸板的三指点击设置为呼出轮盘.

**Comment by xiayaopai** [comment]
有办法让动作弹出也不显示第三圈么? 以前版本没有这个问题, 没有动作显示出来感觉很突兀

**Comment by cuiliang** [comment]
以前不显示第三圈的，导致扩展圈的动作无法触发，所以最新的加上了。我等试试判断一下看看，如果扩展圈没有动作就不显示。
