### ISSUE TITLE
自动运行动作里设置的启动后运行的动作都不能在启动后相应时间运行，设置的定时运行的动作可以运行

### ISSUE THREAD

**Issue by xznwood** [cuiliang/QuickPadCn#1583]
**描述BUG**
自动运行动作里设置的启动后运行的动作都不能在启动后相应时间运行，设置的定时运行的动作可以运行
版本是1.28.20。

**Comment by cuiliang** [comment]
具体是什么设置？
组合动作的话，在动作中第一行加上“提示消息”以判断到底是没有触发，还是触发了动作没有达到目的。

**Comment by cuiliang** [comment]
另外检查一下有没有设置绑定主机。。

**Comment by xznwood** [comment]
> 另外检查一下有没有设置绑定主机。。

具体就是动作库的日记模板动作：https://getquicker.net/Sharedaction?code=9640dc6a-d637-4c24-2a60-08d69553d63a

没有绑定主机，我有三个电脑都在用quicker，我认为不绑定主机应该是默认都使用啊，难道还要绑定三个主机吗？
![Snipaste_2022-01-26_13-42-34](https://user-images.githubusercontent.com/46956044/151110019-f8a3b69f-7b82-4bf1-b21e-641266b92fa6.png)

**Comment by xznwood** [comment]
我的按时间自动运行的动作就没绑定主机，在不同电脑上都可以运行，但是设置为 启动后运行的动作就不能自动运行，搞不懂。

**Comment by cuiliang** [comment]
不绑定就都生效的。我是怕绑定了主机所以不生效。 
把延迟秒数改少点看看是不是能启动呢。
动作里加上提示消息。

**Comment by xznwood** [comment]
延迟秒数也改小了，另一个也是开机启动的隐藏窗口的动作里有提示消息，但是开机后到时间了还是一点反应没有，奇怪不。
![Snipaste_2022-01-28_08-43-12](https://user-images.githubusercontent.com/46956044/151467545-0491f663-dd2b-4053-9c8b-582ee0a1cce4.png)

**Comment by xznwood** [comment]
> 不绑定就都生效的。我是怕绑定了主机所以不生效。 把延迟秒数改少点看看是不是能启动呢。 动作里加上提示消息。
希望下个版本能解决一下啊

**Comment by cuiliang** [comment]
@xznwood  延迟数改成10，确认它不会自动启动么？方便远程看一下么？ 目前我还不是很确定到底什么问题。

**Comment by cuiliang** [comment]
在动作前两行增加提示消息和写入log文件，以确定到底是不是没有执行。我刚测试了一下是正常的。
![image](https://user-images.githubusercontent.com/1972649/151468464-0a9ec254-69f7-4149-a2ea-c1cc08024337.png)

**Comment by xznwood** [comment]
> 

我刚按照你说的，把启动时间都调到20秒以内重启后，都可以启动了，但是我想的是200秒左右启动比较适合我，是不是秒数大了就不启动了啊

**Comment by cuiliang** [comment]
本地测试200秒没有问题，请按上面的设置添加提示和log文件，以确认到底是否没有触发。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
