### ISSUE TITLE
设置页面显示卡屏、白屏

### ISSUE THREAD

**Issue by mt2022** [cuiliang/QuickPadCn#1584]
**描述BUG**
设置页面显示卡屏、白屏

![image](https://user-images.githubusercontent.com/86895409/151104154-1ee35168-2a08-4a91-80c3-bc1969a7459e.png)

**相关截图**
![image](https://user-images.githubusercontent.com/86895409/151104154-1ee35168-2a08-4a91-80c3-bc1969a7459e.png)

**环境信息:**
 - 操作系统版本：Windows 10
 - Quicker版本： 1.28.20

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
参考这里：https://getquicker.net/KC/Kb/Article/973

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
