### ISSUE TITLE
到底什么时候有黑夜模式？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1585]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
以前也在群里 论坛 github好像都提到过。晚上编辑动作有点刺眼！很多软件或者网站早都有了啊，为什么quicker这个基本设置没后呢
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
已有
