### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by dashuai945** [cuiliang/QuickPadCn#1587]
**描述BUG**
qicker软件本身及动作无法联网。但是电脑其他联网都ok

**重现步骤**
1.立即同步失败
2.动作更新失败
3.软件更新失败

**相关截图**
![20220128_071653](https://user-images.githubusercontent.com/42255798/151659405-2a021151-87d0-455e-92c7-bc6ea233f241.png)
![20220128_071706](https://user-images.githubusercontent.com/42255798/151659414-17c4795b-b2e0-42fe-8a05-2f4d5a7ecf0b.png)
![20220128_071847](https://user-images.githubusercontent.com/42255798/151659420-da821130-0da3-4954-923f-8c18637834b1.png)

**环境信息:**
 - 操作系统版本：
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎12/‎24 ‎星期五
操作系统版本	22000.376
体验	Windows 功能体验包 1000.22000.376.0

 - Quicker版本：
开始是1.28.4.0，后来发现无法更新，就手动下载更新到了1.28.20

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
之前正常么？ 什么时候开始了呢？ 中间有修改过windows什么设置么？ 安装或更新过什么软件么？
有使用代理么？

**Comment by cuiliang** [comment]
目前服务器端没有什么变化，也没有其它用户有类似现象。 估计是您电脑上网络设置被修改了，特别是和ssl连接有关的。
![image](https://user-images.githubusercontent.com/1972649/151660146-b561f2fa-4b06-489b-8281-df912668b0be.png)

**Comment by dashuai945** [comment]
刚刚我的ssl3.0未勾选，我现在勾选了重启还是这样

**Comment by cuiliang** [comment]
这个情况我也不是很好判断。 如果还记得上次什么时候正常的，可以尝试恢复一下windows到这个时间看看。 回忆一下这期间有没有安装更新过什么软件...

**Comment by dashuai945** [comment]
勾选了重启我的windows 安全中心提示   威胁服务已经停止。立即启动

**Comment by dashuai945** [comment]
![20220129_091504](https://user-images.githubusercontent.com/42255798/151662372-be103519-2167-4f5c-ba0b-6a3c1cb08593.png)
xian'z现在变成这样了

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
