### ISSUE TITLE
工具箱 只能点击下1页查看动作有点不方便

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1588]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
现在和以往不一样了，有的软件动作很多，页数多，点下一步 看不过来。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
为什么和网页的体验不一样？论坛网页查看动作可以看首页 末页但是客户端不行？
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20225202095235](https://user-images.githubusercontent.com/44609485/152166951-3f8a6216-97e3-4d49-8a26-770ed17fba71.png)

**Comment by cuiliang** [comment]
工具箱显示的信息有限，目前建议是通过网页搜索查看了。
