### ISSUE TITLE
在这里写需求摘要

### ISSUE THREAD

**Issue by lbgws2** [cuiliang/QuickPadCn#1589]
**需求描述**
文本指令功能很赞!!与其它文本扩展软件相比,建议在"编辑文本指令"界面中增加"立即触发"的选项

**描述你想要的解决方案**
对于常用的文本扩展,在输入缩略词后,还要再按一下触发键,显得有点麻烦

**Comment by cuiliang** [comment]
这样难道不会误触发影响输入么？
