### ISSUE TITLE
显示动作使用次数步骤有点长

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1590]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
步骤太长=
点击鼠标中键唤出quicker面板→点击。。。→点击场景与动作→点击显示使用次数
就查看1个使用次数居然要点击4次
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
这是隐藏功能，对服务器压力也比较大，一般不建议经常使用。

**Comment by cuiliang** [comment]
要减少步骤的话，可以做一个动作快速打开场景窗口，绑定到快捷键。 这样只有用快捷键+右键两次就可以了。🤦‍♂️
