### ISSUE TITLE
蓝牙鼠标休眠后重连后滚轮不能滚动菜单

### ISSUE THREAD

**Issue by 2362** [cuiliang/QuickPadCn#1591]
**描述BUG**
蓝牙鼠标休眠或断电后再重连，鼠标滚轮不能滚动菜单，右键托盘图标重新加载键鼠挂钩后可以恢复正常

**重现步骤**
1.关闭蓝牙鼠标电源
2.打开蓝牙鼠标电源
3.唤出窗口后滚轮不能正常使用

**相关截图**
无

**环境信息:**
 - 操作系统版本：win10专业版、win11专业版
 - Quicker版本：1.28.20 

**附加信息**
注：Quicke以前的版本也有此问题，不清楚是否只有我一人有这情况。
我公司与私人电脑都出现了此问题，都是笔记本但电脑型号、操作系统、鼠标型号均不相同

**Comment by cuiliang** [comment]
可能是两个原因：1）挂钩丢失 2）被其他软件先抢占了挂钩（如第三方手势软件）。

可以在设置中开启自动检测挂钩丢失。
![image](https://user-images.githubusercontent.com/1972649/152719960-6b834523-5f7d-4d67-8f1d-f37a2bb9f31c.png)

**Comment by 2362** [comment]
谢谢，确实是软件冲突，把另外一个软件退出之后就可以了

**Comment by 2362** [comment]
我再描述一下，方便有人搜索到这个回答，我另外使用的软件是X-mouse Button Control，该软件中有一个选项在“设置”-“高级”-“CPU优先级”，将其改为“正常”也可以恢复Quicker的正常使用
![图片](https://user-images.githubusercontent.com/22723486/152721389-0f6ef7c2-41a0-4c83-bbf0-93222716aa73.png)
