### ISSUE TITLE
“翻译”这个动作在更新后就不好用了，我想使用先前的版本，请问如何操作？

### ISSUE THREAD

**Issue by gttwork** [cuiliang/QuickPadCn#1593]
**需求描述**
需要能够下载历史版本。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
抱歉，目前没有下载历史版本的功能。 
具体是怎么不好用？ 如果使用的是免费接口，可能接口本身会失效造成无法翻译的。 
如果有Q豆，可以试试这个 https://getquicker.net/Sharedaction?code=2376e6a5-b5d9-4afb-7655-08d950c2afd2

**Comment by gttwork** [comment]
经常只返回一两个结果，先前版本一般都能够返回四五个结果。推荐的是挺好的，但收费太贵了。

**Comment by cuiliang** [comment]
这是比较明显的接口失效问题。回退版本也没法解决的。
免费的东西谁都没法保证，本身就是白嫖的接口，人家稍微一限制就不行了。
