### ISSUE TITLE
锁定页面自动解锁

### ISSUE THREAD

**Issue by pjw20911** [cuiliang/QuickPadCn#1596]
**描述BUG**
锁定页面自动解锁

**重现步骤**
1.Ctrl+滚轮中键调出界面，点软件界面中间的“锁”图标，此时可正常锁定无法翻页。
2. 重启电脑，Ctrl+滚轮中键调出界面，可以看到已经被自动解锁

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10专业版10.0.18363
 - Quicker版本：1.29.3

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
没有自动锁定功能。
如果锁定了，看下是不是设置了自动运行动作，在动作里锁定了切换

**Comment by pjw20911** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的邮件，尽快给您回复。

**Comment by pjw20911** [comment]
> 没有自动锁定功能。 如果锁定了，看下是不是设置了自动运行动作，在动作里锁定了切换

如图，我只想永久锁定，但每次都会被解锁。可以添加这个功能吗。

https://ae03.alicdn.com/kf/H22f9e64e79554b09a50a863007a6d8cbt.png

**Comment by cuiliang** [comment]
Quicker的设计思想是要根据当前程序自动切换下面的，不是固定的。你可以把除了“通用”之外的所有场景里的动作页都删除，场景也都删除，就会自动加载“通用”动作页了。详情参考文档说明。
