### ISSUE TITLE
毛玻璃特效使用导致窗口拖动极卡

### ISSUE THREAD

**Issue by shiyunjie45** [cuiliang/QuickPadCn#1597]
WIN11使用毛玻璃特效会导致窗口拖动极卡，严重的时候像慢动作一样

**Comment by cuiliang** [comment]
这是您使用的Windows版本的bug，Quicker这边没有什么能做的。
请升级windows到合适的版本或者关掉毛玻璃了。

**Comment by shiyunjie45** [comment]
> 这是您使用的Windows版本的bug，Quicker这边没有什么能做的。 请升级windows到合适的版本或者关掉毛玻璃了。
实际我直接使用WIN11没事，但是win11开启quicker的毛玻璃特效就极卡

**Comment by cuiliang** [comment]
> > 这是您使用的Windows版本的bug，Quicker这边没有什么能做的。 请升级windows到合适的版本或者关掉毛玻璃了。
> > 实际我直接使用WIN11没事，但是win11开启quicker的毛玻璃特效就极卡

我也用的win11的，没有这个现象。你的win11多少版本？
![image](https://user-images.githubusercontent.com/1972649/154873453-87aec851-02c1-49de-b0f8-f58c5cd3ff35.png)

**Comment by shiyunjie45** [comment]
![image](https://user-images.githubusercontent.com/17060545/154873532-00f4f703-332e-4ab8-97ff-14f446961275.png)
有趣的是，我使用的也是这个版本，但是我是教育版

**Comment by cuiliang** [comment]
😂 那估计只能先关掉模糊了。 电脑是什么显卡？

**Comment by shiyunjie45** [comment]
GTX1060,我之前试过，关掉毛玻璃就好了，刚刚我试了一下，升级成专业版就不卡了，这是个有趣的问题，看起来有点歧视教育版

**Comment by cuiliang** [comment]
歧视应该不至于，有可能是bug没有同步修改

**Comment by shiyunjie45** [comment]
在我重启后故障恢复，可能和我的鼠标DPI很高有关系，最好的办法看起来还是关闭毛玻璃特效

**Comment by Cloud370** [comment]
哈哈哈 刚开始我直接3080Ti指定高性能硬刚 后边刷到知乎有人说才知道是毛玻璃的锅
