### ISSUE TITLE
长时间使用quicker时，可能出现quick所有页面都无法正常显示的问题

### ISSUE THREAD

**Issue by WhoIsU** [cuiliang/QuickPadCn#1598]
**描述BUG**
win10 21H1 19043.1526（该BUG已经至少存在于最近2个版本） 在长时间使用之后，经常性出现quicker所有页面无法显示，但是部分功能仍然有效的状况，以轮盘为例，BUG触发时，轮盘整体没有显示，但是仍然将鼠标移至左下角使用最小化功能，在快捷栏中的右键单击quick图标也不能显示菜单（此时右键单击其他应用图标还是有菜单弹出的，如QQ、CHROME），只有在任务管理器中强制结束quicker进程之后手动重启才能恢复正常。
**重现步骤**
1.在WIN10上长时间使用quicker（至少一天以上）
2.等待BUG触发

**相关截图**
没法截图

**环境信息:**
 - 操作系统版本：win10 21H1 19043.1526
 - Quicker版本：1.29.3

**Comment by cuiliang** [comment]
我也遇到过休眠后显示不正常的情况。这个从调试环境看状态都是正常的，有可能是windows或.net底层的显示bug，目前没有什么办法只能重启quicker一下了。

**Comment by WhoIsU** [comment]
> 我也遇到过休眠后显示不正常的情况。这个从调试环境看状态都是正常的，有可能是windows或.net底层的显示bug，目前没有什么办法只能重启quicker一下了。

还真有可能是windows的锅，之前我经常遇见过Listary和quicker一起出现这样的状况，不过最近listay好像修复了这个问题，前几次就只有quicker不能显示。

**Comment by WhoIsU** [comment]
> 我也遇到过休眠后显示不正常的情况。这个从调试环境看状态都是正常的，有可能是windows或.net底层的显示bug，目前没有什么办法只能重启quicker一下了。

复现这个bug的话可能需要挂机很久，一般三天左右就会出现一次，有时候挂机一个星期才会出现一次。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
