### ISSUE TITLE
希望能优化下同步

### ISSUE THREAD

**Issue by ladia** [cuiliang/QuickPadCn#1599]
**需求描述**
两个设备- -鼠标不太一样，有一个鼠标有侧键，设置侧键调出quicker 另一个鼠标没有设置键位不一样，同步之后很尴尬

**描述你想要的解决方案**
希望能设置个同步忽略列表，分类忽略一些设置不同步。方便不同设备设置不同

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
处理起来太复杂了，有的地方想同步有的地方不想，每个选项都有可能存在这种分裂。 所以基本不太可行。
建议更换为一样的鼠标，或者挑选两边鼠标都有的键来触发，这样才能保持习惯和高效。
比如我就是单位和家里都用的Master3鼠标。
