### ISSUE TITLE
Quicker导致Windows 11 窗口界面拖拽黏滞，不跟随鼠标运动

### ISSUE THREAD

**Issue by EVANGELION-Air** [cuiliang/QuickPadCn#1600]
**描述BUG**
Quicker导致Windows 11 窗口界面拖拽黏滞，不跟随鼠标运动

**重现步骤**
1.保持Quicker后台打开状态(无论是否暂停Quicker都可以复现)
2.打开一个文件资源管理器窗口，保持前台，不要最小化
3.打开任务管理器窗口，鼠标快速拖拽移动任务管理器窗口的位置，任务管理器窗口明显出现不跟随鼠标的黏滞运动
4.实际上不止任务管理器窗口，如果Windows存在多个程序陈列状态(并且不处于后台最小化状态)，均会出现画面撕裂与不跟随鼠标的黏滞运动，这些窗口大多都是基于Windows Explorer的
5.完全退出Quicler后该问题消失

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
无法截图

**环境信息:**
 - 操作系统版本：Windows11 22000.527
 - Quicker版本：目前两个更新通道的Quicker均存在该Bug

**附加信息**
据我所知，Wox也曾出现过类似Bug：
[https://github.com/Wox-launcher/Wox/issues/3550](url)
后来查明当开启Wox的透明玻璃效果后会导致本问题所描述的，Windows窗口出现不跟随鼠标的黏滞运动——即便用户仅让Wox后台保持运行而没有唤醒Wox的窗口
我的Quicker的面板也有透明效果，我认为可以从这个角度去排查问题，当然这可能也是Windows目前对所有涉及Blur效果的程序都有的Bug

**Comment by cuiliang** [comment]
https://getquicker.net/QA/Question/9585 请参考这里。 
必要的情况下关闭背景模糊选项，等微软修复。
也可以尝试升级显卡驱动之类的。
![image](https://user-images.githubusercontent.com/1972649/155882412-0e3246b4-27a9-4190-821b-3adec4576fd5.png)
