### ISSUE TITLE
列表插入元素，序号为 -1 时，感觉插到末尾更合适

### ISSUE THREAD

**Issue by kanglade** [cuiliang/QuickPadCn#1601]
列表操作模块中，
插入元素：将元素插入到“序号”指定的位置，
当序号为 -1 时，插到末尾是不是更合理，而不是插到倒数第二，
这样我可以用灵活用序号实现各种插入，
现在的话，我如果要插入到末尾，通过传入序号变量的方式实现不了，还得进行一次判断，然后调用模块中的「添加元素到末尾」

比如，子程序有个输入：索引，
子程序内部进行插入操作，
这时如果希望插入到列表末尾，很不方便

**Comment by cuiliang** [comment]
到末尾直接用添加比较好。
现在已经不适合修改这个行为了，会影响已有的动作😂

**Comment by kanglade** [comment]
😂

**Comment by cuiliang** [comment]
插入序号是指插入以后元素的位置，可以把序号设定为列表长度，它就会在最后一个了。
![image](https://user-images.githubusercontent.com/1972649/155979582-2106ce03-1d1c-4245-8359-0da5b126c089.png)
