### ISSUE TITLE
quicker的文本框和输入框中ahk实现的快捷键失效+文本窗口置顶时会遮挡输入法

### ISSUE THREAD

**Issue by Mirrorgo** [cuiliang/QuickPadCn#1602]
**描述BUG**
1. quicker的文本框和输入框中ahk实现的快捷键失效
2. 文本窗口置顶时会遮挡输入法
**重现步骤**
1.用ahk将capslock替换为了回车键,但是,在quicker的很多输入框以及文本窗口(比如截图2)中,快捷键替换会失效
2.见截图
**相关截图**
2.
![image](https://user-images.githubusercontent.com/55936306/156008326-234aa977-ba7c-4169-b304-da5b0322780d.png)

**环境信息:**
 - 操作系统版本：win11最新正式版
 - Quicker版本：1.29.3

**Comment by cuiliang** [comment]
Quicker的窗口权限比较高，需要AHK用管理员身份运行才能有效。

**Comment by cuiliang** [comment]
输入法遮挡也是类似原因，有的输入法会比较正常。
