### ISSUE TITLE
为什么不能导出quicker使用数据？使用数据没有显示在场景与动作面板

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1603]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
目前的使用统计太简陋了。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
我想导出表格然后导入可视化工具里面看一下。
目前显示的数据量太少了。只有个使用次数，也没有列出属于哪个软件的面板。
很多动作没有得到充分的运用。安装后不小心被忽视了。
为什么各个软件面板的总量？不能显示在这里吗？
![image](https://user-images.githubusercontent.com/44609485/156922874-c06f0de7-70fa-4445-af32-d41ce7a40c03.png)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/156922764-84ccb614-b373-4df1-8877-529abdf4d1f5.png)

**Comment by cuiliang** [comment]
这个数据查询很耗费资源的，只是偶尔查询一下比较合适，所以隐藏的深一些。
动作页上的数字主要是方便整理动作的时候方便删除不常用的动作的。
