### ISSUE TITLE
在 quicker 网页的动作讨论区下，往回复评论的输入框内粘贴长链接会把提交评论的按钮顶不见

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1604]
**描述BUG**
![image](https://user-images.githubusercontent.com/48246272/157405457-93e00dce-5b98-45be-88b3-079b8d84fd09.png)

**重现步骤**
1.点击回复这条评论
2.粘贴以下内容：https://www.mediafire.com/file/zux3x3glmvqdydc/quicker_%25E5%2588%259B%25E5%25BB%25BA%25E9%2597%25AE%25E7%25AD%2594%25E5%258D%25A1_043531-545_log.htm/file

**环境信息:**
 - 操作系统版本：win10 企业版 20H2
 - 浏览器版本：Chrome 99.0.4844.51（正式版本） （64 位）

**Comment by cuiliang** [comment]
感谢反馈，我处理一下。

**Comment by cuiliang** [comment]
已处理。
