### ISSUE TITLE
WIndows11 Insider  版本 截图时鼠标会消失

### ISSUE THREAD

**Issue by pzcn** [cuiliang/QuickPadCn#1605]
**描述BUG**
WIndows11 Insider Dev 22567 22572 版本 截图时鼠标会消失

**重现步骤**
1. 使用WIndows11 Insider Dev 22567 或 22572 版本
2. 使用截图相关操作

**相关截图**
https://getquicker.net/QA/Question/9686

**环境信息:**
 - 操作系统版本：WIndows11 Insider Dev 22567 22572
 - Quicker版本：1.30.12

**附加信息**
今天22572修复了一些其他bug，但是这个依然没有被修复。别是新版本添加的新的api限制

**Comment by cuiliang** [comment]
嗯，我研究一下，确实是这两版win11更新出现的问题，不知道有没有规避的方法。

**Comment by pzcn** [comment]
感谢 发现已修复
