### ISSUE TITLE
双屏情况下移动截图会导致电脑卡机 qiucker卡死退出

### ISSUE THREAD

**Issue by ltymh** [cuiliang/QuickPadCn#1606]
**描述BUG**
双屏情况下移动截图会导致电脑卡顿 qiucker卡死退出

**重现步骤**
1.截图
2.将截图移动到另外的屏幕

**相关截图**
无

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.24.27

**附加信息**
两个屏幕分辨率不同

**Comment by cuiliang** [comment]
请升级到quicker最新版测试。
如果仍有问题，请提供一下两个显示器的布局、分辨率和windows缩放比例设置，我这里测试一下。

**Comment by ltymh** [comment]
更新到最新版本后可以了，谢谢
