### ISSUE TITLE
获取新版 win 10 输入法状态 

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#1609]
“​​在最新版的Windows10中，此功能所依赖的Windows接口已经失效。已无法获取和设置输入法状态。“
输入法状态无法获取很让人困扰啊

**Comment by cuiliang** [comment]
尝试这里的方法 https://getquicker.net/KC/Kb/Article/920 
![image](https://user-images.githubusercontent.com/1972649/158399541-21290f66-bb36-4680-b65e-290eb92dc5b5.png)

**Comment by Hefang2000** [comment]
谢谢

**Comment by Hefang2000** [comment]
谢谢，不过新版比较好用，跳回旧版有些自废武功

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.42.6 改进了输入法支持，目前应该可以支持普通模式了。
