### ISSUE TITLE
调用Everything搜索

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#1610]
可不可以将
![image](https://user-images.githubusercontent.com/63462588/158732353-e6387636-a7cd-41be-8a88-2b4ed969facd.png)
高级搜索，正则以及筛选器融合进去

**Comment by cuiliang** [comment]
有一些可以在搜索内容中添加参数，具体可以参考everything的官方文档。 一直文件类型“音频、图片”这一类是不支持的。文件扩展是支持的，比如ext:.txt 这样的。

**Comment by LaoshuBaby** [comment]
> 一直文件类型“音频、图片”这一类是不支持的。

![图片](https://user-images.githubusercontent.com/42690037/158788858-16ba96cc-9650-4829-9d8e-2d56c1de0dff.png)

**Comment by cuiliang** [comment]
已支持自定义扩展名参数。（实际只是程序自动往里面拼接内容，和自己在搜索内容里添加效果一样）
![image](https://user-images.githubusercontent.com/1972649/166674882-99105edf-2a98-45e4-91fc-7852a33dd714.png)
