### ISSUE TITLE
重复模块的循环间隔实际上是在内容末尾插入延时，这导致最后一次循环结束后依然要等待”循环间隔“的时间

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1611]
**描述BUG**
让我用组合动作的形式具体说明一下
![image](https://user-images.githubusercontent.com/48246272/159158698-b9559080-ba94-46b0-a27b-7b964f2a1718.png)

**相关截图**
![image](https://user-images.githubusercontent.com/48246272/159158667-ab9e3e3d-ebaf-4b79-bb9b-e30b84764930.png)

间隔就应该是间隔，只应该在重复之间出现，不应该在最后一次重复后出现

**环境信息:**
 - 操作系统版本：Windows 10 企业版 20H2
 - Quicker版本：1.30.18

**Comment by cuiliang** [comment]
有道理，我处理一下

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 更新了1.31.1 试下看看。

**Comment by ghost** [comment]
测试了 1.31.1 版本对此 bug 的修复情况，没有发现什么问题
