### ISSUE TITLE
【小问题】用户的智熄操作可能导致按键死循环

### ISSUE THREAD

**Issue by CPCer** [cuiliang/QuickPadCn#1612]
**描述BUG**
使用【动作快捷键】时，如果快捷键与动作内的快捷键一致，似乎会一直循环执行，且“停止运行中的动作”无法达到理想中的效果——我的意思是，只能停止运行动作，但是快捷键会一直发送。

**重现步骤**
1.![image](https://user-images.githubusercontent.com/8787958/159167822-4612767e-33b5-45a7-ac3c-d12b97ccfa9f.png)
2.
![image](https://user-images.githubusercontent.com/8787958/159167847-44be4ac3-d907-449a-8c32-53a313363110.png)
我傻了，本来是要设置成Windows+空格的。

强制停止quicker可以结束此死循环。

**环境信息:**
 - 操作系统版本：win10 2004
 - Quicker版本：

**附加信息**
本来想添加在论坛的[bug反馈专区](https://getquicker.net/QA/Question/3197)的，但是没找到新建帖子的地方……

**Comment by cuiliang** [comment]
这种是正常现象了，动作本身没法判断自己使用的什么快捷键触发的。
如果动作里模拟了触发自己的快捷键，就会产生循环。
类似的还有动作里模拟左键点击，在悬浮的情况下也会重复触发自己。
