### ISSUE TITLE
Excel自动生成目录乱码

### ISSUE THREAD

**Issue by deli123456** [cuiliang/QuickPadCn#1613]
**描述BUG**
打开Excel，执行生成目录动作，自动生成的目录sheet页上 “目录”两字显示乱码

**重现步骤**
1.打开excel，创建多个sheet页
2.执行 自动生成目录 

**相关截图**
![image](https://user-images.githubusercontent.com/60722605/159395453-ad085837-d53f-4161-8a80-5c9b39dc360c.png)
![image](https://user-images.githubusercontent.com/60722605/159395534-edfebbee-2d41-46f3-9c07-a45b91a1f7c2.png)

**环境信息:**
 - 操作系统版本：Microsoft Windows11家庭中文版
 - Excel版本：Microsoft Office家庭和学生版 2016
 - Quicker版本：版本1.30.18

**附加信息**

**Comment by cuiliang** [comment]
尝试修改动作里写入脚本步骤的编码类型参数，改成unicode或者gb2312测试一下看看。

![image](https://user-images.githubusercontent.com/1972649/159396398-ac52e0d0-e77b-47f5-b0ba-2ede06b66e34.png)

**Comment by cuiliang** [comment]
最新版的quicker增加了自动处理编码的功能，可以更新试试。 如果还有问题请反馈。https://getquicker.net/Help/Versions
