### ISSUE TITLE
从文件导入的文本指令将丢失分组信息

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1614]
**描述BUG**
![image](https://user-images.githubusercontent.com/48246272/159842778-44b27e19-d21e-446c-a6c7-0f6cdbdb1dec.png)
此框为空，应是为了方便用户将勾选的文本指令重新分到一个组里
但若空着此框导入，分组信息将直接丢失，全部变为未分组状态
![image](https://user-images.githubusercontent.com/48246272/159844474-14ccc227-edba-499d-b33e-beb6cd79aa35.png)
理想情况下，不进行额外操作时应将所有设置好分组的文本指令分到对应分组下

**环境信息:**
 - Quicker版本：1.32.3

**Comment by cuiliang** [comment]
是这样设计的，分组应该在导入的时候指定，否则认为是不设置分组。
因为假设是别人导出的来导入到自己的里面，保留原有分组不是太好。

**Comment by cuiliang** [comment]
将在 1.33.17 版本中增加保持分组选项。
