### ISSUE TITLE
可否增加不同软件中轮盘菜单使用不同触发键

### ISSUE THREAD

**Issue by xccy** [cuiliang/QuickPadCn#1615]
**需求描述**
现在的轮盘菜单能自定义触发键，但是只能全局使用一个，但是在一些应用场景下这可能导致冲突。比如我把轮盘菜单触发设置在右键，那么在xmind，catra等软件中就不能使用软件自身的右键拖拽页面功能，将触发设置在中键，同样会在edge的某些使用场景下冲突，而冲突的往往都是这些软件中十分常用的功能，这导致在这些软件中不得不把quicker或者轮盘菜单关闭。

**描述你想要的解决方案**
对于轮盘菜单，可以对不同软件自定义不同的触发方式，以避免与软件本身的按键冲突。

**描述您考虑过的替代方案**
关闭quicker，或者关闭特定软件的轮盘菜单。

**Comment by cuiliang** [comment]
兼容的方法：先按住右键保持不动，等过一会儿长按超时了，再拖动就可以了。
轮盘本身可以在特定软件里禁用。
设置比较多的触发方式不是合理的解决办法，会增加软件的复杂程度，使用的思考时间和使用难度。
理想的是找一个不会冲突的方法。
