### ISSUE TITLE
Quicker中的功能：获取文件扩展信息时，无法对目标路径后的代码进行返回。

### ISSUE THREAD

**Issue by Zhuoershang** [cuiliang/QuickPadCn#1616]
**需求描述**
win11中的WSA的快捷方式均提供了一个目标地址+APP包名，通过包名启动不同的App，但是在获取此类快捷方式扩展信息时，没有返回App包名，无法识别到底是哪个应用的快捷方式。
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\WsaClient.exe /launch wsa://com.coolapk.market
WSA应用的快捷方式示例目标如上所示。

**描述你想要的解决方案**
在返回的文件扩展信息中包含exe后面的启动代码 /launch wsa://com.coolapk.market 。

<img width="936" alt="Snipaste_2022-03-25_23-43-21" src="https://user-images.githubusercontent.com/79759438/160153968-e850c526-2f12-4441-8fdd-0be698e47153.png">

**描述您考虑过的替代方案**
无

 **其他上下文**
无

**Comment by cuiliang** [comment]
感谢反馈，等研究一下

**Comment by cuiliang** [comment]
下个版本会增加一个单独的输出。
![image](https://user-images.githubusercontent.com/1972649/161905892-fc46160d-86ae-4f1d-a8f7-22642811bad9.png)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 已发布1.32.7
