### ISSUE TITLE
手动新手教程

### ISSUE THREAD

**Issue by yunayj** [cuiliang/QuickPadCn#1617]
**需求描述**
第一次登录新注册账号时弹出的新手教程很好，但是关闭之后就必须到官网查看文档个人觉得第一次登录新注册账号时弹出的教程比官网的教程看着简洁，操作方便

希望作者能开发出手动按钮在软件里，在需要的时候可以手动调用出来，而不是弹出官网的网站

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/160224164-9f000ac5-2450-49ff-b25e-ee330b5001f9.png)
可以在这里打开试试。

**Comment by yunayj** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/160224164-9f000ac5-2450-49ff-b25e-ee330b5001f9.png) 可以在这里打开试试。

原来作者早就弄好了啊😂，非常感谢
