### ISSUE TITLE
软件自启动时，任务管理器显示为“启动影响-高”

### ISSUE THREAD

**Issue by kelukeka** [cuiliang/QuickPadCn#1618]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个目前没有什么办法，启动的时候做的操作比较多，需要加载数据，需要联网同步，而且本身.Net的程序启动就会慢一点，需要系统加载相关的库。

**Comment by cuiliang** [comment]
归档
