### ISSUE TITLE
点击没响应

### ISSUE THREAD

**Issue by 3020574863** [cuiliang/QuickPadCn#1619]
**描述BUG**
鼠标点击中建的时候没反应在右下角点击也没反应不知道是什么问题
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/76427713/160736709-3d6c4ec1-8fa1-40c8-a5c2-0799c8d2c3ef.png)

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.32.3

**附加信息**

**Comment by cuiliang** [comment]
你好，之前正常么？ 重启软件之后正常么？
使用了WallpaperEngine了么？可以先尝试彻底退出WE看看会不会好转。
也可以加qq 197906 详聊。

**Comment by cuiliang** [comment]
解决了么？
https://getquicker.net/QA/Question/10204 后来发现这些线索可以参考一下。

**Comment by Zhangtiande** [comment]
刚打开软件可以用，过一会鼠标中键点击没反应，手动点击图标打开面板，然后随便点个设置直接卡死，win11

**Comment by cuiliang** [comment]
@Zhangtiande 试试这里的线索 https://getquicker.net/QA/Question/10204  如果仍然出现，远程一下，加qq 197906

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
