### ISSUE TITLE
不显示图标

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1620]
最近打开Quicker后，经常不显示图标，需要重启Quicker，如图
![image](https://user-images.githubusercontent.com/34650487/160737028-861ad14a-98cc-4737-9306-c36efbe17483.png)

**Comment by cuiliang** [comment]
可能原因：1，网络问题，下载不来图标。 2. 系统缓存目录问题，图片没法写入到缓存目录中。 
如果有安全软件，可以尝试先退出安全软件后启动quicker看看会不会发生。

**Comment by DogeFlow** [comment]
> 可能原因：1，网络问题，下载不来图标。 2. 系统缓存目录问题，图片没法写入到缓存目录中。 如果有安全软件，可以尝试先退出安全软件后启动quicker看看会不会发生。

安全软件只有windows defender，不显示图片的应用是windows自带的计算器和笔记本，不知道是否与windows 11有关？

**Comment by cuiliang** [comment]
如果之前显示了，图片就会是一个链接，而且会在本地缓存，感觉应该和系统没关系。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
