### ISSUE TITLE
部分可交互UI不能正常显示

### ISSUE THREAD

**Issue by YBYCS** [cuiliang/QuickPadCn#1621]
**描述BUG**
对于可以交互的UI如 按钮 输入框等 鼠标指上去后可能会导致无法正常显示

**相关截图**
![image](https://user-images.githubusercontent.com/87234506/160861636-23dd45b9-fbf8-4b70-882b-b2bd6b0bb077.png)
![image](https://user-images.githubusercontent.com/87234506/160861718-6910633d-6d8b-4deb-8d5b-43bcd462a1bf.png)

**环境信息:**
 - 操作系统版本：windows10 戴尔G15笔记本 
 - Quicker版本：1.32.3

**Comment by cuiliang** [comment]
https://getquicker.net/KC/Kb/Article/973 参考这里
