### ISSUE TITLE
没有鼠标拖动模块 可参考其他国内外各rpa增加一些模块

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1622]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
虽然有一些例子动作，但是拖动的动作也太少了吧，连1页都不到，可以参考下其他的rpa，我最近把国内主流的rpa机器人流程自动化都下载，尝试了1遍
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
这个是影刀rpa的，可以看看哪些模块quicker还没有，对比下，加一些，国外的我还没有尝试，英语不够熟练
![天若_20220831100840](https://user-images.githubusercontent.com/44609485/160962027-ca30f6fd-33da-454a-9e6d-51c16b4b033c.png)

下载uipath的时候不知道为啥老是下载不了社区版，老是报错！
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
2021年RPA行业报告10篇
链接：[百度网盘 请输入提取码](https://pan.baidu.com/s/16K7L2UqyI0fof5SMRFqh5Q) 
提取码：homh 
最近收集的rpa相关的，可供参考
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20220431100411](https://user-images.githubusercontent.com/44609485/160961607-4c9f8d16-3f5d-4107-8c86-88cfb30e1f4e.png)
-

![天若_20220531100523](https://user-images.githubusercontent.com/44609485/160961724-9b5ed077-ccfb-45ee-b12a-69acafc42de8.png)

**Comment by cuiliang** [comment]
拖动本身不是很很好操作的，可以试试按下鼠标，移动，抬起鼠标。
