### ISSUE TITLE
鼠标手势在 ToDesk 窗口上不工作

### ISSUE THREAD

**Issue by richex-cn** [cuiliang/QuickPadCn#1623]
**描述BUG**

在 ToDesk 窗口上，鼠标手势不工作，具体表现为按下鼠标移动时，并没有出现鼠标手势轨迹。

**重现步骤**

1. 启用鼠标手势，并打开 ToDesk 窗口。
2. 按住鼠标右键并移动。

**环境信息:**
 - 操作系统版本：Windows 10 21H1 (19043.1586)
 - Quicker版本：1.30.18

**Comment by cuiliang** [comment]
本地实测没问题。
是在本地设置的手势还是远程电脑？ 远程电脑可能是不支持的，todesk不能正确还原鼠标消息。

**Comment by richex-cn** [comment]
在主窗口和远程窗口都没有正常工作，ToDesk 版本是 4.1.0

![Snipaste_2022-04-06_10-01-59](https://user-images.githubusercontent.com/25103518/161880948-efd6d435-5347-42f1-9a57-2c9af5554c72.png)

**Comment by cuiliang** [comment]
有没有移动quicker的安装路径？如果移动了可能提权不了权限不足。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/161883360-0ce0a463-876d-4833-8226-503f4cd1154e.png)

**Comment by richex-cn** [comment]
> 有没有移动quicker的安装路径？如果移动了可能提权不了权限不足。

Quicker 和 ToDesk 都是通过安装包安装的，没有移动过，具体安装路径：
Quicker `C:\Program Files\Quicker\Quicker.exe`
ToDesk `C:\Program Files (x86)\ToDesk`

下面是录屏演示：

https://user-images.githubusercontent.com/25103518/161884001-36f18f08-c9b1-4c8e-95c2-22cd5b7e6188.mp4

和权限有关我能想到的是 ToDesk 是由服务开机自启的（权限可能高一些？），Quicker 不是，但两者都是开机自启，我尝试了重启 ToDesk 和 Quicker 还是不能正常工作。

**Comment by richex-cn** [comment]
并且我尝试了关闭 Quicker 后，右键以管理员运行，但在 ToDesk 窗口上还是不能工作。

**Comment by cuiliang** [comment]
有加黑名单么？
以及这里的选项
![image](https://user-images.githubusercontent.com/1972649/161884886-c70dd2f7-606f-4db5-a531-a249604570b0.png)

![image](https://user-images.githubusercontent.com/1972649/161885114-9f39ef56-483d-4b22-ab93-9efe949148a1.png)

**Comment by richex-cn** [comment]
目前只有全局手势，还没有对单独的程序设置手势。

![Snipaste_2022-04-06_11-31-42](https://user-images.githubusercontent.com/25103518/161890454-47de3350-f811-4d0a-a0eb-50d27f09b8d2.png)

**Comment by cuiliang** [comment]
如果黑名单里也没有添加，可能就是那个窗口权限太高了
![image](https://user-images.githubusercontent.com/1972649/161905297-b34fe4c0-d2f6-4487-98b8-e9dec330ec1a.png)

**Comment by richex-cn** [comment]
@cuiliang 非常感谢，是我忘记这个黑名单和鼠标手势功能有关联了，之前因为远程桌面和 Quicker 有冲突所以加了黑名单。从黑名单删除之后就正常了。问题已解决，不是 BUG，谢谢~
