### ISSUE TITLE
动作运行中提示

### ISSUE THREAD

**Issue by calmhot** [cuiliang/QuickPadCn#1624]
希望加入动作运行中的提示图标啥的，让人可以一眼看见，哪个动作目前在执行中

**Comment by cuiliang** [comment]
目前可以右键点击托盘图标，在菜单里查看。

**Comment by calmhot** [comment]
> 

那个太不明显，能不能加入托盘图标角标提示，再加个托盘图标鼠标tip详细提示等等，这样比较明显

**Comment by calmhot** [comment]
> 目前可以右键点击托盘图标，在菜单里查看。

那个太不明显，能不能加入托盘图标角标提示，再加个托盘图标鼠标tip详细提示等等，这样比较明显

**Comment by 4285f4** [comment]
同样需要此功能。我尝试过使用徽标当作动作运行状态指示，但当动作内部出现错误停止以及外部手动停止时没办法清除徽标，导致动作停止了徽标却依然显示着。也试过等待窗口，这个倒是在外部手动停止动作的时候会自动关闭，但是也没办法在动作出错停止时关闭

**Comment by cuiliang** [comment]
最新版在托盘里增加了一个运行中数量显示（在设置中开启）。 动作上更新会有额外的性能损坏，不增加了。
关闭古老issue中，感谢！
