### ISSUE TITLE
quicker能否用于文档翻译？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1625]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
目前在用百度网页的文档翻译，结果失败非常多，稍微多翻译几个文档就会提示忙中！失败
翻译个三五个就不行了
彩云小译太贵了，不够用。
目前quicker搜不到文档翻译，当然识别动作是很多，图片→文字，
能否PDF翻译→word或者其他格式也行啊，加个进度条啥的，翻译完了，来个提示
尝试python调用来搞文档翻译，没成功，文章没看懂，用百度api或者其他的api都行
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可以使用厂商付费的文档翻译服务，免费的估计都有限制。Quicker目前没有提供这方面的接口，有的话也是走厂商的付费通道，成本会很高。
