### ISSUE TITLE
Quicker安卓遥控器旋转至横屏会闪退

### ISSUE THREAD

**Issue by DustHeart2022** [cuiliang/QuickPadCn#1626]
**描述BUG**
手机开启自动旋转功能，竖屏使用遥控器时体验正常，横置屏幕时app旋转画面会瞬间闪退。在我的华为手机和一加手机上测试都有相同的闪退问题。老版本的app可以正常横屏使用动作页面，更新至最新版本才出现这一bug。

**重现步骤**
1.手机开启自动旋转功能
2.APP连接电脑进入动作页面
3.横置手机屏幕，在画面自动旋转之前APP就会闪退
4.重新启动APP后仍然能重现这一BUG，只能竖屏遥控

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Android
 - Quicker版本：1.0.1-2

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
目前没能力维护安卓客户端了。
源代码在这里 https://github.com/cuiliang/QuickerAndroid 有兴趣可以本地调试一下。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
