### ISSUE TITLE
quicker自带ocr用不了，报错502（bad gateway）

### ISSUE THREAD

**Issue by ByeBsi** [cuiliang/QuickPadCn#1627]
**描述BUG**
quicker自带ocr用不了，报错502（bad gateway）

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 专业
 - Quicker版本：1.29.3

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
动作和quicker都更新到最新版试试。

**Comment by ByeBsi** [comment]
好的

**Comment by ByeBsi** [comment]
还是不行，现写的都不行

**Comment by cuiliang** [comment]
调试文件发一下，502是服务器端返回的错误。

**Comment by ByeBsi** [comment]
[识别错误.txt](https://github.com/cuiliang/Quicker/files/8458841/default.txt)

**Comment by cuiliang** [comment]
现在试下看看

**Comment by ByeBsi** [comment]
6666666
