### ISSUE TITLE
手势管理不能自定义路径添加管理

### ISSUE THREAD

**Issue by 1005091604** [cuiliang/QuickPadCn#1628]
**描述BUG**
手势管理不能自定义路径添加管理，
LOL游戏的时候，进入游戏运行的是LeagueClient.exe，但是无法添加手势禁用。
选择框里没有，又无法自定义路径。
错误添加的手势管理程序，删除不掉。

只能在玩游戏的时候把全局手势禁用，不玩了在启动。
**重现步骤**
1.手势触发设置为鼠标右键
2.进入LOL游戏，右键左下滑最小化游戏了
3、无法添加手势禁用。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.32.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
鼠标触发可以在这里添加黑名单 
![image](https://user-images.githubusercontent.com/1972649/162644666-838e06b2-43e1-47f1-9f0d-b7e7d9437fb5.png)
