### ISSUE TITLE
每次第二次调出Quicker会直接导致程序崩溃

### ISSUE THREAD

**Issue by flZeroQAQ** [cuiliang/QuickPadCn#1629]
**描述BUG**
对bug的清晰简洁描述。
每次第二次调出Quicker时，窗口会直接卡死并且进程崩溃

**重现步骤**
每次第二次调出Quicker时，窗口会直接卡死并且进程崩溃，同时系统报AppHangB1事件

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/94091036/162682026-469ea931-8a0f-4183-80e4-1b06a98fc5c9.png)
![image](https://user-images.githubusercontent.com/94091036/162682168-baab6e07-6255-4a6b-8bb8-3ce5f9292604.png)
![image](https://user-images.githubusercontent.com/94091036/162682205-8d56d250-52e1-419d-9509-44bd78da2479.png)

**环境信息:**
 - 操作系统版本：WIndows 10 Professional 内部版本19044.1620
 - Quicker版本：1.32.8.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果用了百度网盘，卸载百度网盘通常可以解决。 
可以参考这里：https://getquicker.net/QA/Question/10204 
百度网盘在系统里注入了一个奇怪dll。
