### ISSUE TITLE
开机不能自启程序

### ISSUE THREAD

**Issue by V1stone** [cuiliang/QuickPadCn#1630]
版本号：1.30.18
已做检查：1.杀毒软件没有关闭quicker自启2.quicker开机自启已打开
出现问题的节点：升级到1.30.18后。之前是正确自启的

**Comment by cuiliang** [comment]
设置里的自动启动选项还在选中状态么？
如果变取消了，说明被拦截了，可能是某个“管家”软件拦截的。
参考：https://getquicker.net/KC/Kb/Article/401

**Comment by V1stone** [comment]
> 设置里的自动启动选项还在选中状态么？ 如果变取消了，说明被拦截了，可能是某个“管家”软件拦截的。 参考：https://getquicker.net/KC/Kb/Article/401

没有关闭自启，设置还在。之前都正常。开机后手动启动会弹出已经启动的提示，但是实际没有自启。

**Comment by cuiliang** [comment]
那可能是卡死了。 最近有一个百度网盘卡死quicker的问题，如果安装了百度网盘，可以先卸载一下测试看看。如果仍然出的话，找时间远程一下看看， 我qq 197906

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
