### ISSUE TITLE
经常需要重新加载键鼠挂钩，每天开机后用 1-2 次轮盘菜单后就失效了，必须重新加载

### ISSUE THREAD

**Issue by XinLi0111** [cuiliang/QuickPadCn#1631]
Win 11

**Comment by cuiliang** [comment]
如果使用了其它手势软件，确保不要在它们里面不要使用相同的鼠标键。
如果仍然出现，在配置里开启自动检测挂钩丢失选项。
![image](https://user-images.githubusercontent.com/1972649/163293259-ad34a5d4-b6ac-4e38-bd18-cb51e9768bc4.png)

**Comment by XinLi0111** [comment]
> 如果使用了其它手势软件，确保不要在它们里面不要使用相同的鼠标键。 如果仍然出现，在配置里开启自动检测挂钩丢失选项。 ![image](https://user-images.githubusercontent.com/1972649/163293259-ad34a5d4-b6ac-4e38-bd18-cb51e9768bc4.png)

已经设置自动检测鼠标挂钩丢失，也没有使用其他手势软件，问题依旧出现。

**Comment by cuiliang** [comment]
下次出现的时候可以向日葵远程一下，我qq 197906

**Comment by eliaszon** [comment]
我的办法是，用快捷键绑定键鼠挂钩，然后用手势绑定这个快捷键来实现键鼠挂钩

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
