### ISSUE TITLE
安卓APP提供横屏

### ISSUE THREAD

**Issue by MaxZH42** [cuiliang/QuickPadCn#1632]
**需求描述**
希望安卓APP能够提供旋转功能，方便在平板上使用。我有一个小平板用来做一些辅助事件，比如智能家居管理、蓝牙音箱放歌、电脑性能信息监控等，希望能在平板上直接横屏使用Quicker的App。

**描述你想要的解决方案**
设计兼容安卓App横屏模式

**描述您考虑过的替代方案**
暂无

 **其他上下文**
考虑过使用第三方旋转管理软件来强制旋转Quicker，其他大部分不支持旋转的软件都可以使用（例如手机QQ），但是唯独Quicker强制旋转后会闪退，所以还是需要开发支持。

**Comment by cuiliang** [comment]
目前没有能力维护，已开源 https://github.com/cuiliang/QuickerAndroid ，可以尝试自行修复一下。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
