### ISSUE TITLE
希望显示菜单模块能支持文件路径

### ISSUE THREAD

**Issue by cotagxrdhy** [cuiliang/QuickPadCn#1633]
很多软件会有拖入文件的需要，如果能把常用的文件用菜单分类整理出来，还可以直接拖拽的话会极大提高效率。

目前动作-剪贴板已经支持文件拖拽了，希望能菜单也能加上这个功能！

感谢作者大大~

**Comment by cuiliang** [comment]
不是很明白

**Comment by cotagxrdhy** [comment]
![01](https://user-images.githubusercontent.com/80959178/163335600-0e2b73c1-b0c9-40a5-ba3e-64f849cbd7f7.gif)

如图，希望显示菜单能放文件，拖拽

**Comment by cuiliang** [comment]
菜单控件本身不支持拖拽操作的

**Comment by cotagxrdhy** [comment]
> 菜单控件本身不支持拖拽操作的

好吧，感谢回复！
