### ISSUE TITLE
点击侧键能从keydown改成keyup吗

### ISSUE THREAD

**Issue by zz541843** [cuiliang/QuickPadCn#1635]
**需求描述**
已知侧键能控制 面板和轮盘，我想一个键就能控制两个东西

**描述你想要的解决方案**
我说的函数可能和你们的语言不一致，但功能应该有吧
面板的显示从keydown换成keyup，并且两个坐标要一致才显示面板
这样这个侧键就能通过滑动控制轮盘也不会显示面板了
鼠标侧键实在是太宝贵了！而且g502有额外的侧键并不支持，所以我觉得这样子做是最优解了

**Comment by cuiliang** [comment]
可以按键长按，滑动兼容的。 在高级鼠标触发里设置。

**Comment by zz541843** [comment]
> 可以按键长按，滑动兼容的。 在高级鼠标触发里设置。

你可能没理解到位，不是侧键去控制动作，而是去控制面板和轮盘啊！

**Comment by cuiliang** [comment]
高级鼠标触发不只是能触发动作，也能触发很多功能的。 建议详细了解一下。
![image](https://user-images.githubusercontent.com/1972649/163515412-d751d247-3fa7-4945-a5e0-efd0efa4515d.png)

**Comment by zz541843** [comment]
> 高级鼠标触发不只是能触发动作，也能触发很多功能的。 建议详细了解一下。 ![image](https://user-images.githubusercontent.com/1972649/163515412-d751d247-3fa7-4945-a5e0-efd0efa4515d.png)

好吧，在快速操作这里有面板和轮盘，短按的操作确实能满足我的需求，感谢
