### ISSUE TITLE
导致电脑蓝屏

### ISSUE THREAD

**Issue by 2019yangxiao** [cuiliang/QuickPadCn#1636]
当电脑外接显示器的时候，我在主屏幕使用quicker的截图功能后，把所截图片拖动到另一个屏幕时，电脑会蓝屏，试了很多次都是，当所截图片跨越的另一屏幕，电脑立马蓝屏。
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：window10
 - Quicker版本：1.32.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
你好，把两个显示器的分辨率、缩放比例，和摆放布局截图一下我这里试试。
早期版本存在一个这样的问题，后来应该修复过了。

**Comment by 2019yangxiao** [comment]
暂时不好弄，疫情被隔离了，显示屏在实验室，这个问题是之前发现的，等过段时间解封了在发您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月15日(周五) 中午12:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiliang/Quicker] 导致电脑蓝屏 (Issue #1636)




 
你好，把两个显示器的分辨率、缩放比例，和摆放布局截图一下我这里试试。
 早期版本存在一个这样的问题，后来应该修复过了。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
