### ISSUE TITLE
quicker自带文字识别又不行了

### ISSUE THREAD

**Issue by ByeBsi** [cuiliang/QuickPadCn#1637]
[新建文本文档 (2).txt](https://github.com/cuiliang/Quicker/files/8499503/2.txt)
**描述BUG**
发送请求错误

**重现步骤**
1.
2.

**相关截图**
![image](https://user-images.githubusercontent.com/98044789/163666910-429a4a49-c6e3-4454-99a5-2927b58bdc4e.png)

**环境信息:**
 - 操作系统版本：win10专业
 - Quicker版本：1.32.8

[新建文本文档 (2).txt](https://github.com/cuiliang/Quicker/files/8499504/2.txt)

**附加信息**

**Comment by cuiliang** [comment]
😂 今天公司所在园区电力维修意外断电了。

**Comment by ByeBsi** [comment]
OK
