### ISSUE TITLE
微软晓晓语音朗读

### ISSUE THREAD

**Issue by B664577** [cuiliang/QuickPadCn#1638]
**需求描述**
导入微软语音朗读模块。

**描述你想要的解决方案**
选择复制文本后自动利用微软插件朗读，朗读完后自动关闭。

**描述您考虑过的替代方案**
有利用第三方软件，但是第三方软件需要手动关闭窗口。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
建议直接在浏览器里朗读，控制起来比较方便。
quicker的话目前可以通过浏览器控制运行后台脚本使用浏览器的tts引擎，不过我没时间仔细研究了，有兴趣可以自行尝试一下。

**Comment by cuiliang** [comment]
参考动作： https://getquicker.net/Sharedaction?code=a14014c4-4946-4e7e-5e93-08da1f2ef538
