### ISSUE TITLE
Total Commander有时候无法获取选中的文件(夹)

### ISSUE THREAD

**Issue by nickear** [cuiliang/QuickPadCn#1640]
![Snipaste_2022-04-20_12-17-20](https://user-images.githubusercontent.com/38856879/164149482-78f76233-b586-4fcc-b2e4-1be95e0dbd7e.png)

文件和文件夹都不行。有时候会这样，有时候正常。最近才出现这个问题，之前不会。

**Comment by cuiliang** [comment]
检查一下有没有什么使用剪贴板的动作或其它软件，先退出测试一下。 
另外tc有没有修改过程序名称？目前的进程名是什么？

**Comment by nickear** [comment]
我刚刚把等待剪贴板时间从默认值200增大到1000就解决了。我估计是tc写入剪贴板的速度很慢，200ms有点太短了

![image](https://user-images.githubusercontent.com/38856879/164164574-088fb868-6218-45fd-b035-3d3bc72ea0b4.png)

**Comment by cuiliang** [comment]
好的
