### ISSUE TITLE
缩放125%界面不全

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1641]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
![QQ截图20220421213656](https://user-images.githubusercontent.com/38199371/164469935-e20f9851-d11c-439c-bb37-4a24e918bdd1.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
quicker版本和windows版本多少？

**Comment by ghost** [comment]
> quicker版本和windows版本多少？

哦我知道了，是因为我玩红警，要选这个“以多少分辨率运行”，然后启动玩游戏，quicker才那样的，正常没问题
![image](https://user-images.githubusercontent.com/38199371/164966690-e76b801f-3171-4754-8432-06522ff926e6.png)

**Comment by cuiliang** [comment]
好的。
