### ISSUE TITLE
启动windows自带软件失败

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1644]
win11，启动windows自带软件（记事本、计算器等）失败，如图
![image](https://user-images.githubusercontent.com/34650487/165040197-8a004d71-ee0d-4619-a4d2-43a70c0968d6.png)
好像是每次锁屏，隔一段时间就会出错？
重启Quicker后，就可以了

**Comment by cuiliang** [comment]
目前没有收到其它类似反馈。
系统内存和Quicker进程内存占用多少？CPU占用高么？有没有安装百度网盘？
动作里是什么样的设置？提供尽量多的信息以便发现线索。或者下次遇到时联系qq 197906 用向日葵远程一下。

**Comment by DogeFlow** [comment]
系统内存：32GB
Quicker进程内存占用：250.6MB
CPU占用不高
安装了百度网盘，但很少使用
动作设置如下：


出现频率：大概一周两三次
经常是电脑熄屏，但不睡眠，一段时间后，再点亮屏幕，就无法使用计算器或记事本，需要重启Quicker后，问题修复
在2022年4月25日 ***@***.***> 写道：

目前没有收到其它类似反馈。
系统内存和Quicker进程内存占用多少？CPU占用高么？有没有安装百度网盘？
动作里是什么样的设置？提供尽量多的信息以便发现线索。或者下次遇到时联系qq 197906 用向日葵远程一下。

**Comment by DogeFlow** [comment]
![image](https://user-images.githubusercontent.com/34650487/165197523-d097814b-2062-4603-8210-bc750e14dcd9.png)
![image](https://user-images.githubusercontent.com/34650487/165197535-8b104248-76d9-4291-ac66-53ea193af586.png)

**Comment by cuiliang** [comment]
Quicker和windows的详细版本号是多少？ 
这个估计比较难定位，等有更多反馈看看有没有什么共通点，再分析一下线索。

**Comment by DogeFlow** [comment]
> Quicker和windows的详细版本号是多少？ 这个估计比较难定位，等有更多反馈看看有没有什么共通点，再分析一下线索。

Quicker：1.32.8
windows：windows 11 21H2 22000.613

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
