### ISSUE TITLE
Win11环境下Quicker频发卡死

### ISSUE THREAD

**Issue by 785227331** [cuiliang/QuickPadCn#1645]
**描述BUG**
Win11环境下Quicker经常无法唤起，使用快捷键以及点击桌面右下角的Quicker图标都无法唤出操作界面

**重现步骤**
随机出现的，一天时间内基本会出现1-2次

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win11
 - Quicker版本：1.32.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
最近出现的卡死现象通常是百度网盘引起的。如果您安装了百度网盘，可以尝试卸载或想办法删掉它的一个dll文件。
参考：https://getquicker.net/QA/Question/10204

**Comment by cuiliang** [comment]
解决了么？ @785227331

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by 785227331** [comment]
目前看是因为启动需要管理员权限的应用（vsCode）导致的卡死




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] Win11环境下Quicker频发卡死 (Issue #1645)





 
解决了么？ @785227331

**Comment by cuiliang** [comment]
@785227331 参考上面的链接处理一下百度网盘的文件试试。
