### ISSUE TITLE
可以使用quicker用于文档翻译吗？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1647]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
之前忘记说了文档翻译有免费的调用量的。
[百度智能云-管理中心](https://console.bce.baidu.com/ai/#/ai/machinetranslation/overview/index)
目前的翻译多数是扫描 扫描识别图片来翻译
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
不是百度的文档翻译其他的文档翻译也可以，前阵子百度文档翻译开始收费了，再不能随便用了，api100万字还没有用过，
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/44609485/166151832-abbd8c75-7646-4f51-a966-e1b2637442a2.png)

![天若_20220501230519](https://user-images.githubusercontent.com/44609485/166151955-154402bc-59e5-43b8-a6a0-9f39da926369.png)

![天若_20220501230550](https://user-images.githubusercontent.com/44609485/166151970-afb52521-783d-4669-9bcb-2bf0bf57a694.png)

**Comment by cuiliang** [comment]
可以，不过比较复杂，要自己根据百度的接口使用http模块设计动作，调用它的接口。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
