### ISSUE TITLE
搜索框的热键冲突

### ISSUE THREAD

**Issue by mytens** [cuiliang/QuickPadCn#1648]
**需求描述**
可否把搜索框的热键设置成可以调整哈，目前它和jupyter notebook的注释按钮冲突了，且点了暂停quicker依然会占用，要使用注释必须要彻底关闭quick。

**Comment by cuiliang** [comment]
这个快捷键本身就是自定义的，在 设置 -》 功能快捷键 里。
另外也可以用新增的按键双击方式触发。
https://getquicker.net/kc/manual/doc/settings-keyactionmanagepage

**Comment by mytens** [comment]
谢谢，找到了，困扰了好久，终于~
