### ISSUE TITLE
为什么有关计时的功能，经常运行的时候卡住？

### ISSUE THREAD

**Issue by JURAN2020** [cuiliang/QuickPadCn#1649]
**描述BUG**
有关计时的脚本都会卡住，点击停止了的计时窗口中的选项，计时窗口就会关闭。不是脚本的问题，是有计时功能的脚本都有这种情况。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不是很明白你说的现象，请录个屏看下。
