### ISSUE TITLE
动作页滚轮切换不准确。

### ISSUE THREAD

**Issue by tongfeicsc** [cuiliang/QuickPadCn#1650]
滚轮切换动作页面老是滑过中间页

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.33.2

**Comment by cuiliang** [comment]
什么品牌的鼠标？
如果罗技鼠标，尝试关闭平滑滚动之类的设置。
如果有其他手势、ahk之类的软件，尝试先彻底退出这些软件排查一下。

**Comment by tongfeicsc** [comment]
罗技m720鼠标。谢谢。


| |
佟飞
|
|
***@***.***
|
在2022年5月6日 ***@***.***> 写道：

什么品牌的鼠标？
如果罗技鼠标，尝试关闭平滑滚动之类的设置。
如果有其他手势、ahk之类的软件，尝试先彻底退出这些软件排查一下。

**Comment by cuiliang** [comment]
解决了么？

**Comment by tongfeicsc** [comment]
暂时是解决了。我把手势wgesture给关了，目前没有问题。谢谢！~


| |
佟飞
|
|
***@***.***
|
在2022年5月6日 ***@***.***> 写道：

解决了么？

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
