### ISSUE TITLE
问题摘要:两个显示器缩放百分比不同，主面板的显示有空白

### ISSUE THREAD

**Issue by tluy** [cuiliang/QuickPadCn#1651]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.两个显示器，左边1080p缩放125%，右边显示器1080p缩放100%
2.左边弹出主面板正常，右边弹出有空白部分，面板窗口的按钮大小为76

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10      专业版本     版本号21H2
 - Quicker版本：1.33.1

![20220506185946](https://user-images.githubusercontent.com/39296974/167119720-557aeb59-b67c-423e-bf2d-18761ba74a27.png)
![20220506185905](https://user-images.githubusercontent.com/39296974/167119739-31560ebf-941b-423a-a4fb-4b20d41a6b9a.png)

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个是一个windows或.net底层的bug，试一下关掉背景模糊看看有没有效果（重启一下quicker）。
![image](https://user-images.githubusercontent.com/1972649/167120072-c6105857-8f87-4e30-8401-f5ddbbe68587.png)

**Comment by tluy** [comment]
重启后可以了，谢谢！
