### ISSUE TITLE
双语混合引擎朗读

### ISSUE THREAD

**Issue by B664577** [cuiliang/QuickPadCn#1652]
**需求描述**
利用edge实现中英双语混合引擎朗读

**描述你想要的解决方案**
对中英文分别调用不同的引擎

**描述您考虑过的替代方案**
手动选择英文调用英文引擎，或中文引擎，希望能自动对文字内不同语种调用不同的朗读引擎。
 **其他上下文**
得益于上次的的指导，能调用晓晓阅读单引擎朗读，但因为涉及较多中英混合的文字，所以才有这个想法
![image](https://user-images.githubusercontent.com/51772818/167170802-6dfcf313-59b7-414f-8d00-a4cb896f4395.png)
在网上搜索到一些相关脚本，限于没有编程基础，无法实现。谢谢

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
