### ISSUE TITLE
调出面板：增加双击右键

### ISSUE THREAD

**Issue by huyin01** [cuiliang/QuickPadCn#1653]
**需求描述**
调出面板：增加双击右键→优势：这样与系统操作不冲突！

**描述你想要的解决方案**
调出面板：增加双击右键

**描述您考虑过的替代方案**
调出面板：增加双击右键

 **其他上下文**
调出面板：增加双击右键

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.42.4 版本增加了。
