### ISSUE TITLE
开机会启动两次

### ISSUE THREAD

**Issue by wow2014-github** [cuiliang/QuickPadCn#1655]
**描述BUG**
对bug的清晰简洁描述。
我设置了开机自启动，但是当我打开电脑quicker已经启动后，过一会它会提示我程序已经运行不能启动多个实例。
**重现步骤**
1.开机软件自启
2.过一会弹出提示“Quickeri已经在运行，不能启动多个实例”

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
https://pic.rmb.bdstatic.com/bjh/315e40ed5d07c2bc475078444d7d3da3.png

**环境信息:**
 - 操作系统版本：
 - Quicker版本：
操作系统win11
quicker版本1.32.8
**附加信息**
在此添加有关此问题的任何其他上下文。
在启动quicker后只设置了一个叫“剪库”的动作自启

**Comment by cuiliang** [comment]
把这里的选项去掉，然后重启一下电脑看看是不是会自动启动。
如果仍然自动启动，说明在其他途径手动添加了自动启动的规则了。可以检查一下系统设置（或者找自动启动管理工具看一下）
![image](https://user-images.githubusercontent.com/1972649/168022235-3c71965f-21f1-44c7-a470-34f11a43e716.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
