### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by pshengcode** [cuiliang/QuickPadCn#1656]
**描述BUG**
新建 启动软件的动作，在选择应用程序的搜索框里 输入  re 就会崩溃

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.331

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by pshengcode** [comment]
不是输入特定字符的问题，  滚动程序列表 也会崩溃

**Comment by cuiliang** [comment]
怎么崩溃，是突然消失还是弹出报错对话框？ 
是突然出现的这个现象么？以前正常么？
win11是多少版，最近又安装补丁么？ 试试卸载补丁看看。 
用的哪种输入法？ 切换到另外的输入法试试呢？

**Comment by pshengcode** [comment]
![image](https://user-images.githubusercontent.com/50767444/168322134-42bdcd8a-a534-442f-bb99-94adf5fe92a0.png)
![录制_2022_05_13_23_56_34_794](https://user-images.githubusercontent.com/50767444/168322245-8abc8476-a722-43a0-aebd-39d3cf859c89.gif)

**Comment by cuiliang** [comment]
@ersanre 看起来可能是获取某个程序的图标出错了，不过这个在本地没有复现不好判断。 
可以看下quicker.log文件、windows事件查看器里有没有什么报错信息可以找下线索。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
