### ISSUE TITLE
关于使用动作的统计数据

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1657]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
能不能把动作数量以及使用动作的统计数据放到其他地方
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
目前放在这里离面板太远了，查看的比较少
![天若_20220513121955](https://user-images.githubusercontent.com/44609485/168210538-14657744-1a9b-490b-9459-f2b2b54d9415.png)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
![天若_20220513122020](https://user-images.githubusercontent.com/44609485/168210581-719e6693-7ac9-4b3a-b403-8e932de4badd.png)
能不能把某软件对应面板里的动作的总使用次数放到左边这里
然后把某软件面板的总动作数量放到第1页上面，有多少个动作页还有动作列出来，目前加的动作有点多了
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20220513122302](https://user-images.githubusercontent.com/44609485/168210805-27135525-ce3d-46fd-9790-6280c330026a.png)
目前这里这么大一块空白使用的比较少，可以把软件对应的面板的动作使用次数排序放到这里

**Comment by cuiliang** [comment]
统计动作需要比较多的服务器资源，所以让用户尽量少使用到这个功能，特意藏的比较深的。
