### ISSUE TITLE
能不能粘贴动作直接安装

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1658]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
不要弹出窗口
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
quicker更新之后一般要不了多久我就会更新，版本不会落后太多，加个提示多个流程
尝试了很多很多动作，每次都要点次安装，积累下来多花了好多时间
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20220513131217](https://user-images.githubusercontent.com/44609485/168215399-b88b1a73-5cab-4016-9a0f-8b1063c14152.png)

**Comment by cuiliang** [comment]
动作都是他人编写的，最好看一下动作内容，确认安全了再安装使用。

**Comment by kunpeng9** [comment]
我一般都是在网页看过然后复制然后粘贴安装的，已经看过了，提示增加了流程
我怎么确认是安全的？机械电子专业的，不是计算机专业的，目前的安全机制是？企业有几个人开发？个人开发吗？只有1个人？

**Comment by cuiliang** [comment]
没办法判断用户是不是看过了。 
有的人看不懂，有的人能看懂，这样在发布危险动作的时候就会有顾虑。 
有的人想看，有的人不想看，但是不可能每个功能都增加选项控制的，增加了也不会几个人选择，只是徒增复杂度。

quicker只有一个人开发，所以才需要更多的使用者对动作进行审查。

> 目前的安全机制是？企业有几个人开发？个人开发吗？只有1个人？

反馈需求，建议只描述需求。 我不清楚这样几个问号是什么意思。
