### ISSUE TITLE
是否可以增加随机显示某些动作？+显示quicker所有动作的数量

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1660]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
目前总的动作数量是多少来着？我记得以前好像还显示在主页来着，现在好像没有了
![天若_20220513135511](https://user-images.githubusercontent.com/44609485/168220035-67e8881a-3459-44b9-beab-ca85d67fef31.png)
以前好像会在这里显示目前总的动作数量，总的使用次数，不知道啥时候被去掉了
是否实时显示，或者可以加个折线图或者数字啥的来展示1下动作的总数量以及增加动作的数量
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
之前发了一些邮件给calibre的开发者， 更新版本之后转换速度快了很多，而且还加了个随机功能！
![天若_20220513135726](https://user-images.githubusercontent.com/44609485/168220354-e557bf3a-66b9-4f1f-ac0d-a0f919a4478e.png)
我来wolai里面的笔记数量多了之后随机访问文章速度就很慢，半天不显示笔记，不知道什么原因导致的，更新了好几次版本之后好了很多
![天若_20220513135809](https://user-images.githubusercontent.com/44609485/168220441-ea2d6d95-7d96-46d3-824d-d1dbdf9db5af.png)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20220513135607](https://user-images.githubusercontent.com/44609485/168220159-f2312c47-3035-4e9e-acf1-dee54eae57b2.png)
可在新动作右边加个随机显示某些动作，
显示目前随机显示的动作的数量/总动作数量  显示%的动作
![天若_20220513140337](https://user-images.githubusercontent.com/44609485/168221094-ba0e37d4-a225-4258-8c6b-ad4f61c74970.png)

**Comment by cuiliang** [comment]
目前感觉产品本身还有很多需要完善的地方，显示那个数字没有什么意义。等产品更完善了了之后再完善网页端了。
