### ISSUE TITLE
数据开放问题

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1661]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
是否可以方便的导出某些数据，例如我自己可以导出自己的quicker使用数据，用量统计 面板只显示1小部分动作的使用数据
网页可以导出 关于安装量等数据的excel，这样我就不用爬虫工具再爬1遍了
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
爬虫软件爬了之后我会导入vika再另外安排动作使用问题，做备注等
以前安装了很多很多动作 尝试，但是随着时间流逝中断了，比如我本来想明天尝试或者编辑某动作，第2天坚持编辑 尝试，后面忘记了，很多动作不够完善，不同的动作分别发挥1部分功能组成1个流程【我不太好编辑，动作太复杂 对我来说就像黑盒 只能等作者优化更新】，中断了，流程没有组装好 运行不成功，面板动作多，很散乱
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
[小程序预览问题 - vika维格社区](https://bbs.vika.cn/question/484) 
![天若_20220513164834](https://user-images.githubusercontent.com/44609485/168247058-621a514b-bf70-42a2-bfdb-60c0866aba78.png)
![天若_20220513164849](https://user-images.githubusercontent.com/44609485/168247129-21bd634c-0675-43d9-9619-13b3432f15ce.png)
预览效果不好 公开链接 https://vika.cn/share/shrV7jND3ZeXlUC0iRUqr 【维格表】- kunpeng9给你分享了《点击-Quicker动作2022‎年‎3‎月‎30‎日》，为了更好的体验，建议通过电脑浏览器访问
vika里面最爽的1点就是不用点击翻页

**Comment by cuiliang** [comment]
在场景和动作管理里，上面右键菜单可以开启使用数量的统计，作为删除动作的参考。 
其实哪些常用哪些不常用自己也基本清楚的。
导出短期不会有时间开发。
