### ISSUE TITLE
能否增加设置阻断动作更新+可视化动作树

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1662]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
对一些比较复杂的动作进行编辑 运行 理解，没有坚持每天编辑，断断续续 时间比较长，更新动作的时候搞忘记了，全选 批量更新动作 源作者的更新把我尝试编辑的内容给覆盖了！之前白搞了！
一般会复制1个，1个继续运行，1个用来编辑 理解，有时候会复制多个，散到不同的软件面板里，原本想接着编辑，但是时间长了之后 我搞忘记了，不知道有哪些重复动作，能否自动列出呢？这些重复动作挤占了面板空间，加上之前尝试了一大堆 太满了，搞的软件面板不好调整
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
1个动作复制2次，共3个，能否增加设置 阻断其中1个动作更新，并且在动作上做个标识 
1个动作接着接受源作者的更新，1个用来编辑 调试理解，另外1个 个人提交作为源作者的分叉优化版，有些类似于github的代码库 克隆 分支
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
目前有多少动作来着？有10万吗？目前产生动作分支了之后只能在说明里记录来自哪些动作，原作者不知道。
要是可以实时查看 可视化就好了
[纪念nautre创刊150年=随机漫游《自然》论文网络_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1of4y1u7ws?spm_id_from=333.999.0.0) 这个是静态的，产生论文分支不能实时显示出来
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
动作选项里选择检查更新时忽略就可以了。
![image](https://user-images.githubusercontent.com/1972649/168280512-c9592dec-23d0-4001-b573-2cb01e5e0d1e.png)
