### ISSUE TITLE
搜索动作 删除动作后为啥窗口没了？动作好添加 不好删除 好+ 不好-

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1663]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
必收是我以前用过的1个稍后读软件，和开发者反馈了很多内容，完全不听，没有几个被采纳，后来公司倒闭了，最近突然想起来之前把软件卸载了但是配套的动作还没删除，我搜索动作进行删除发现删除1个之后动作框窗口就消失了，这样我就又得点击 +搜索 +删除，这样循环重复好几次

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
添加动作的流程=网页查看+点击绿色的 复制到剪贴板+粘贴+点击确认=5个步骤
总感觉删掉动作的流程比添加的多，总之就是麻烦一些，添加动作可以从网页复制粘贴安装，可以从工具箱里拖动安装，内部编辑搜索子程序添加，3个来源

一直不知道总安装动作数量 总运行次数，好+，不好- 导致 动作数量太多 ，能不能把窗口一直保持着？删除1次之后窗口就自动消失掉，好麻烦
动作数量太多！太多！加上断断续续使用，面板一团糟，有些是要持续使用的，有些是以前编辑调试的，有些是搜索时候 发现有意思就安装一大堆，但是有的实际没运行过1次，断断续续还没尝试到那个动作，结果后面完全搞忘记了
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。
能否使用网页上来多选来批量添加或删除动作？目前每次安装都得点击1次确认真的很麻烦，我已经在网页上看过了！
**使用网页而不是面板来删除动作**有巨大意义！面板上的说明只能看1部分还是得跳转网页查看，以前动作不多，复杂度也不高简单看下还可以，现在很多动作巨复杂，说明也很长
以前提过面板归档，感觉好像不行，和稍后读逻辑不一样。
 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20220513180333](https://user-images.githubusercontent.com/44609485/168261275-804c69bb-0242-40fc-a2df-bb1985614ec1.png)

**Comment by cuiliang** [comment]
搜索是用来查找和运行动作的，删除和管理在场景设置窗口里操作。
![image](https://user-images.githubusercontent.com/1972649/168279969-f166960e-f334-4b00-8eb4-a482a5f6c0da.png)

**Comment by kunpeng9** [comment]
可是场景管理只能删1个软件对应面板的内容啊，不能跨软件面板

**Comment by cuiliang** [comment]
不是要删除某个软件的动作页么，这里应该很合适的
