### ISSUE TITLE
“左键辅助”功能偶尔失效

### ISSUE THREAD

**Issue by dkpress** [cuiliang/QuickPadCn#1664]
**描述BUG**
“左键辅助”功能偶尔失效，频繁的时候一天可能遇到几次，有时候几天也不会遇到。重启软件也不能解决，关闭”左键辅助“，关闭软件，重启软件，再打开”左键辅助“，也不行。这种状况持续有一段时间了，可能这一个月隔几天会出现一次。

**重现步骤**
不知道什么原因引起的，无法重现。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 专业版 19041.804
 - Quicker版本：1.32.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
大部分情况下是有按键的状态不正确（变成了按下状态）。
可以参考这里排查一下 https://getquicker.net/kc/manual/doc/leftbuttonplus#J8syQ

**Comment by dkpress** [comment]
霍！检测键盘状态，发现是”F22“键是按下的状态，我去，键盘上都没有这个键。
重置后好了，非常感谢！

**Comment by cuiliang** [comment]
F22是一个存在的键码，可能是某个设备使用了它，可以观察一下它什么时候会按下，定位一下原因。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！ F22是微信按下的。
