### ISSUE TITLE
重复安装动作怎么找出来删除

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1665]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
之前安装很多动作，搜索的时候发现重复了，不好删除，我之前也记录过的，那个忽略动作更新之后没有明显标识，标记出来，比如图标左上角加个符号啥的
[固定区域OCR截图 - 统计数据 - Quicker](https://getquicker.net/Share/Actions/Stat?code=0aaf7f17-5538-419c-c35d-08d9a89feebe)
最近尝试这个动作的时候发现运行不了，它调用了1个其他的动作，但是那个动作重复安装了好几次，在不同的软件面板里，我搜索删除之后才可以调用，按了好几次搜框，为啥那个搜索动作的框不能保持住呢？让我一直搜一直删

之前记录过，动作好安装但是不好删减
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
是否可以自动标记出来呢？或者加清理功能？还是怎么弄，我也不知道有多少重复动作，面板有点满，以前尝试太多了，半途而废的动作太多，没有搞明白就放弃了
调出不同的软件面板，显示各个重复动作所在软件面板的位置
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
就是这个框，一直保持住
![天若_20220520202047](https://user-images.githubusercontent.com/44609485/169526902-60967d6d-3786-49e0-bf05-91f68513d892.png)

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
