### ISSUE TITLE
鼠标中键同时作为快速截图的引导键和截图鼠标键，可用性不稳定

### ISSUE THREAD

**Issue by WongYuetYee** [cuiliang/QuickPadCn#1666]
**描述BUG**
启动了快速截图功能，引导键设置为鼠标中键，截图鼠标键也设置为鼠标中键，有时能用，有时用不了，不能用的时候，按下中键为原本的功能，使页面快速滚动。

**重现步骤**
1. 启动快速截图功能
2. 设置引导键为鼠标中键
3. 设置截图鼠标键为鼠标中键
4. 应用设置
5. 按下中键并移动，试图截图

**环境信息:**
 - 操作系统版本：Windows10 专业版 21H1 操作系统内部版本19043.1706
 - Quicker版本：1.33.15

**Comment by cuiliang** [comment]
这里引导键不能用鼠标键

**Comment by WongYuetYee** [comment]
噢…好的
