### ISSUE TITLE
STMP增加显示发件人名称

### ISSUE THREAD

**Issue by mingjinglyh** [cuiliang/QuickPadCn#1667]
STMP动作里面，只能添加发件人邮箱，不能显示发件人名称，收件后是这样显示的
![image](https://user-images.githubusercontent.com/45187089/170416357-042a5abc-976c-450e-951e-854f9773b985.png)

如果我通过网页版发送，收件后是这样显示的
![image](https://user-images.githubusercontent.com/45187089/170416448-0a93c83a-449d-4582-8777-f67b785e3162.png)

**Comment by cuiliang** [comment]
已增加，下个版本更新。
