### ISSUE TITLE
将Chrome和Cent Browser识别为了同一个软件

### ISSUE THREAD

**Issue by ChaXxl** [cuiliang/QuickPadCn#1668]
**描述BUG**
在添加鼠标手势时，在添加场景选择应用时，将Google Chrome和百分浏览器识别为了同一个软件，百分浏览器自带了鼠标手势不需要设置，我想单独设置Chrome的手势，结果它们识别为同一个软件了不给我设置。

**重现步骤**
0.先设置百分浏览器禁用手势
1.鼠标手势
2.添加场景
3.点击识别按钮
4.选择Chrome

**相关截图**
![image](https://user-images.githubusercontent.com/40326898/170435942-8d3d2cdb-e893-4781-a407-90c12cd6a961.png)

**环境信息:**
 - 操作系统版本：Win 11 DEV 25126.1000
 - Quicker版本：1.33.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
按进程名字识别的，cent浏览器也是用的chrome.exe，识别会出错，可以手动修改更换一个。

**Comment by ChaXxl** [comment]
好的👌

**Comment by ChaXxl** [comment]
> 别

好的👌
