### ISSUE TITLE
英文Windows系统， 中文字符显示编码问题

### ISSUE THREAD

**Issue by tshuangteng** [cuiliang/QuickPadCn#1669]
### 系统说明
![image](https://user-images.githubusercontent.com/62510752/170553125-cac0f960-fbdb-4c26-82d1-bc5cbc0fb1b2.png)

### 显示目录下文件结构的问题

、、、

C:\USERS\HT\DOWNLOADS
Γöé   58260B2E91E8E64EE2A9F040D23479A63E26DD01.png
Γöé   
Γö£ΓöÇΓöÇΓöÇCompressed
Γöé       barrier-2.4.0.zip
Γöé       igfx_win_100.9684.zip
Γöé       
ΓööΓöÇΓöÇΓöÇPrograms
        BarrierSetup-2.4.0-release.exe
        OBS-Studio-27.2.4-Full-Installer-x64.exe
        Obsidian.0.14.6.exe
        OfficeSetup.exe
        pycharm-community-2021.3.3.exe
        pycharm-community-2022.1.1.exe
        Quicker.x64.1.33.15.0.msi
        vcxsrv-64.1.20.14.0.installer.exe
、、、

**Comment by cuiliang** [comment]
这个是哪个动作的输出么？可以试试修改一下脚本控制台编码看看

**Comment by tshuangteng** [comment]
#### 修改该动作的所有脚本 控制台输出编码， 解决了问题， 如下
![image](https://user-images.githubusercontent.com/62510752/170638158-d8e6fa6a-b67b-4ffe-ab02-a0f4ff5f95e5.png)


不过 作者大大可以全局兼容吗考虑下UTF-8的全局设置，不太清楚这个OEM使用原理，微软官网文档说明：
https://docs.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.2

**Comment by cuiliang** [comment]
可能英文和中文系统的编码不太一样。等有空再研究下了。

**Comment by tu10ng** [comment]
不是quicker的问题。windows默认gbk编码，启用beta的unicode编码后，很多文字会乱码。请不要勾选beta选项。
