### ISSUE TITLE
调整轮盘尺寸后，轮盘显示异常

### ISSUE THREAD

**Issue by csjuXYZ** [cuiliang/QuickPadCn#1670]
**描述BUG**
将轮盘尺寸由300调整至150之后，轮盘显示不全，具体情况见图。

**相关截图**
![image](https://user-images.githubusercontent.com/25047688/170903875-d22a12ee-bbc6-4c0d-9dba-14cb96fe8bb1.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.32.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
本地测试没有复现。可能和系统或显卡驱动有关，如果手头有其他电脑的话可以测试一下看看能不能复现。
