### ISSUE TITLE
关于任务栏通知区域的icon建议

### ISSUE THREAD

**Issue by tshuangteng** [cuiliang/QuickPadCn#1671]
**需求描述**
希望这里的icon可以是简约后的黑白配色，看起来会和Windows系统融合的更美观

**描述你想要的解决方案**
解决方案参考其他软件的icon，如下图
![image](https://user-images.githubusercontent.com/62510752/171280212-de57ab27-6855-4f9d-843a-27f29d6fcc79.png)

**Comment by cuiliang** [comment]
专业版用户可以在这里选择托盘图标 
![image](https://user-images.githubusercontent.com/1972649/171300392-52073eeb-1e17-4aaf-b39f-f0f370488a59.png)

**Comment by tshuangteng** [comment]
牛皮  厉害了  软件也太好用了 !!!
(因为Quicker的存在，折腾完善Windows电脑好几天了，打算主力机换Windows电脑了)

**Comment by tshuangteng** [comment]
已修改托盘icon，顺带更新了新版本，舒服了
![image](https://user-images.githubusercontent.com/62510752/171302055-1290f750-2b16-42b9-8f5e-4dee324dfa4d.png)

**Comment by cuiliang** [comment]
> 牛皮 厉害了 软件也太好用了 !!! (因为Quicker的存在，折腾完善Windows电脑好几天了，打算主力机换Windows电脑了)

谢谢~
