### ISSUE TITLE
想要portable版本

### ISSUE THREAD

**Issue by okhaibo** [cuiliang/QuickPadCn#1672]
**需求描述**
由于公司电脑限制软件安装, 且quicker不在白名单内, 所以目前的安装包安装时会被拦截.

**描述你想要的解决方案**
提供portable版本, 可以直接运行软件

**描述您考虑过的替代方案**
暂时没有

 **其他上下文**

**Comment by cuiliang** [comment]
可以直接复制其他电脑上安装的目录过去。
不过有些功能会无法实现，比如从外部启动动作之类，这些要在安装的时候写注册表。

**Comment by okhaibo** [comment]
好的,这样感觉也不错,大部分功能都可以用
