### ISSUE TITLE
基础动作转换成组合动作 浏览器路径丢失

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1673]
**描述BUG**
对bug的清晰简洁描述。
我之前已经记录哪个路径啊，转成组合后 打开网址模块里的路径没了
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![天若_20220606125803](https://user-images.githubusercontent.com/44609485/172097539-c7678d28-30a4-453d-b29f-a0f3cbc0bd2b.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈，已处理。
