### ISSUE TITLE
请问如何模拟鼠标真实移动，有些移动采用直接跳动的方式不起作用，请教如何模拟真实鼠标移动

### ISSUE THREAD

**Issue by szlnadn** [cuiliang/QuickPadCn#1674]
请问如何模拟鼠标真实移动，有些移动采用直接跳动的方式不起作用，请教如何模拟真实鼠标移动

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：最新版本

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.33.22 增加了选项。
