### ISSUE TITLE
当前组件发生异常后弹出提示无法取消

### ISSUE THREAD

**Issue by youngwy258** [cuiliang/QuickPadCn#1675]
**描述BUG**
当前 安装了 “毒鸡汤” 动作组件 ，设置了快捷键，频繁触发快捷键，程序没有响应过来自动触发异常，提示已终止动作 ，但是该动作没法取消；

**重现步骤**
1. 当前安装了   “毒鸡汤” 动作 ， 设置快捷键 ctrl+F
2. 在文档中频繁按下 快捷键触发该动作   ，见相关截图
**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/35211547/172285784-e726ef68-a2ec-42a6-8a8a-00e2bd5f9a11.png)

**环境信息:**
 - 操作系统版本： win10
 - Quicker版本：  1.33.1

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
动作是在每个步骤执行完的时候判断要不要停止，所以有些情况没法停止住，比如动作在正在显示界面，要等界面关闭才会真正停止。
另外尽量避免把快捷键设置到常用的按键组合上。
