### ISSUE TITLE
求开发【数据抓取】抓取网页相同元素的数据，能抓取多页（自动下一页），并写入表格

### ISSUE THREAD

**Issue by welcome2025** [cuiliang/QuickPadCn#1676]
大佬们，求开发一个类似影刀的，数据抓取功能，
使用教程：https://www.winrobot360.com/yddoc/language/zh-cn/%E5%8A%9F%E8%83%BD%E6%96%87%E6%A1%A3/%E5%BA%94%E7%94%A8%E7%BC%96%E8%BE%91%E7%9B%B8%E5%85%B3/%E9%A1%B6%E9%83%A8%E8%8F%9C%E5%8D%95%E6%A0%8F/%E6%89%B9%E9%87%8F%E6%95%B0%E6%8D%AE%E6%8A%93%E5%8F%96.html?

希望quicker也有这样的功能，抓取网页相同元素的数据，能抓取多页（自动下一页），并写入表格

只需要5步，就能抓取绝大部分网页元素，希望Quicker能针对技术小白，增加一些简单易用的功能。

![image](https://user-images.githubusercontent.com/51198068/172549456-0756b922-f4dd-4522-af13-deb2fbd0ca5b.png)

如图这样抓取

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
