### ISSUE TITLE
打开网易云后，所有设定的动作就失效啦，比如，靠近上下边缘调节音量无法使用，面板无法打开，除非把进程杀掉重新打开才能恢复正常

### ISSUE THREAD

**Issue by Future-W** [cuiliang/QuickPadCn#1677]
![image](https://user-images.githubusercontent.com/53927526/172741034-f38a3694-7dbb-4451-8e3f-095401f8a7e3.png)

**Comment by cuiliang** [comment]
哦，这个可能是百度云造成的，参考这个
https://getquicker.net/KC/Kb/Article/1018

**Comment by Future-W** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cuiliang** [comment]
解决了么？

**Comment by Future-W** [comment]
时好时坏，不过不影响使用😹发自我的荣耀手机-------- 原始邮件 --------发件人： CuiLiang ***@***.***>日期： 2022年6月9日周四 晚上9:20收件人： cuiliang/Quicker ***@***.***>抄送： Future-W ***@***.***>, Author ***@***.***>主    题： Re: [cuiliang/Quicker] 打开网易云后，所有设定的动作就失效啦，比如，靠近上下边缘调节音量无法使用，面板无法打开，除非把进程杀掉重新打开才能恢复正常 (Issue #1677)

解决了么？

**Comment by cuiliang** [comment]
有卸载百度网盘试过么？ 需要的话加QQ 197906 远程看一下。

**Comment by Future-W** [comment]
回头我看看，谢谢啦发自我的荣耀手机-------- 原始邮件 --------发件人： CuiLiang ***@***.***>日期： 2022年6月18日周六 下午3:58收件人： cuiliang/Quicker ***@***.***>抄送： Future-W ***@***.***>, Author ***@***.***>主    题： Re: [cuiliang/Quicker] 打开网易云后，所有设定的动作就失效啦，比如，靠近上下边缘调节音量无法使用，面板无法打开，除非把进程杀掉重新打开才能恢复正常 (Issue #1677)

有卸载百度网盘试过么？ 需要的话加QQ 197906 远程看一下。
