### ISSUE TITLE
关于轮盘菜单模式的建议

### ISSUE THREAD

**Issue by junyuwsda** [cuiliang/QuickPadCn#1678]
感谢您的软件，真的很棒
私以为轮盘菜单模式比默认的矩形好看，因为右键被占用，设置鼠标中键唤出
但是在使用过程中，鼠标中键似乎按下自动滚屏，加上唤出轮盘菜单需要拖动选中图标，体验并不好
能不能可以设置像矩形菜单一样，按下只显示轮盘菜单，然后鼠标单击选中图标

**Comment by cuiliang** [comment]
是用的鼠标操作的么？鼠标的话会拦截按下消息，所以应该不会出现滚屏才对的。
而且常规的轮盘菜单是一次操作完成触发的，如果点击之后再选图标就会多一步。
如果确实需要，可以参考这个动作 https://getquicker.net/Sharedaction?code=7efc668c-a749-4a8c-fc16-08d978b0ec35

**Comment by junyuwsda** [comment]
好的，非常感谢
一番折腾下来，我又觉得其实默认矩形还挺好看（手动狗头）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 关于轮盘菜单模式的建议 (Issue #1678)





 
是用的鼠标操作的么？鼠标的话会拦截按下消息，所以应该不会出现滚屏才对的。
 而且常规的轮盘菜单是一次操作完成触发的，如果点击之后再选图标就会多一步。
 如果确实需要，可以参考这个动作 https://getquicker.net/Sharedaction?code=7efc668c-a749-4a8c-fc16-08d978b0ec35
