### ISSUE TITLE
用户输入的筛选搜索过于模糊

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1680]
![image](https://user-images.githubusercontent.com/48246272/173027298-ac21b384-ebbd-4c84-a099-cec22de65559.png)
这种搜索完全不管关键字是否有组合成关键词，直接对每个关键字进行搜索，效果等同于把每个关键字都当作关键词
![image](https://user-images.githubusercontent.com/48246272/173027658-9c714063-28ce-4c2d-b76c-77f52467c3bf.png)

另外，在用户选择窗口弹出且存在筛选输入框时可以直接输入数字和字母进行搜索，但无法输入符号例如“-”，必须点击输入框后才能输入

**环境信息:**
 - 操作系统版本：win10 20H2 19042.1645
 - Quicker版本：1.33.22

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
作为一个通用的算法，可能不是很好舍弃对低匹配的处理。 这里比较理想的方式是按匹配度排序一下，不过因为选择这个需要保留序号，排序不是太可行。后期再考虑下看看了。 
建议不要输入选项里都有的内容，输入更独特的单词来筛选。

**Comment by cuiliang** [comment]
后来改成了按匹配程度排序，改善了此问题。
