### ISSUE TITLE
部分软件的手势操作是用不了

### ISSUE THREAD

**Issue by Raysmee** [cuiliang/QuickPadCn#1681]
**描述BUG**
酷狗和部分APP 手势用不了

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本win10：
 - Quicker版本 1.328：

**附加信息**
在此添加有关此问题的任何其他上下文。

<img width="960" alt="1128" src="https://user-images.githubusercontent.com/88378318/173193700-b079633c-4393-4a6a-a8bf-caae772f9d1b.png">

<img width="801" alt="1133" src="https://user-images.githubusercontent.com/88378318/173193701-b0b028d4-d05b-46fa-ad79-a24e7743123d.png">

**Comment by cuiliang** [comment]
画不出线还是触发不了动作？ 
有没有加黑名单，有没有设置默认禁用手势？
如果用罗技鼠标，卸载掉它的驱动测试一下。

![image](https://user-images.githubusercontent.com/1972649/173210220-568eddf1-cc54-4669-82b8-9b7e4364e1b0.png)

**Comment by Raysmee** [comment]
好了  好像是我鼠标问题  感谢
