### ISSUE TITLE
无法搜索Windows软件

### ISSUE THREAD

**Issue by U2tzJTNE** [cuiliang/QuickPadCn#1682]
**描述BUG**
无法搜索Windows软件

**重现步骤**
1.快捷键唤出搜索框
2.输入触发词+关键字

**相关截图**
![微信截图_20220613011127](https://user-images.githubusercontent.com/20137053/173245068-9aa2e59b-aded-461c-81f5-f00e10bd3fd8.png)
![微信截图_20220613011032](https://user-images.githubusercontent.com/20137053/173245079-12883f43-bff9-457b-88b7-bf81b48b237b.png)

**环境信息:**
 - 操作系统版本：Windows 11 专业版  22000.708
 - Quicker版本：1.33.22

**Comment by cuiliang** [comment]
hi，把quicker.log文件发送到197906 qq邮箱我看下有没有什么报错。

**Comment by U2tzJTNE** [comment]
> 你好，把quicker.log文件发送到197906 qq邮箱我看下没有什么报错。

已发送

**Comment by cuiliang** [comment]
似乎是权限问题导致索引出错了。 这个现象目前还没有在其它电脑上遇到过。
这个系统是全新安装的还是win10升级的呢？有做过什么安全设置么？ 另外有没有360之类的安全软件可以关闭之后重启一下quicker看看能否正常索引成功。

```
2022-06-13 01:03:29,945 [175] ERROR dVqNkRy0CGK6lXjuepM.S3TRh7yqEwq6wKNJuyA - 索引应用程序出错：发生一个或多个错误。
System.AggregateException: 发生一个或多个错误。 ---> System.UnauthorizedAccessException: 对路径“c:\program files\windowsapps”的访问被拒绝。
```

**Comment by cuiliang** [comment]
另外我等加一个判断了，避免这个出错造成其它索引也不成功。

**Comment by U2tzJTNE** [comment]
> 似乎是权限问题导致索引出错了。 这个现象目前还没有在其它电脑上遇到过。 这个系统是全新安装的还是win10升级的呢？有做过什么安全设置么？ 另外有没有360之类的安全软件可以关闭之后重启一下quicker看看能否正常索引成功。
> 
> ```
> 2022-06-13 01:03:29,945 [175] ERROR dVqNkRy0CGK6lXjuepM.S3TRh7yqEwq6wKNJuyA - 索引应用程序出错：发生一个或多个错误。
> System.AggregateException: 发生一个或多个错误。 ---> System.UnauthorizedAccessException: 对路径“c:\program files\windowsapps”的访问被拒绝。
> ```

全新安装的win11，电脑没有第三方的安全软件  只有  Windows Defender，尝试了重启Quicker 无效

**Comment by cuiliang** [comment]
> > 似乎是权限问题导致索引出错了。 这个现象目前还没有在其它电脑上遇到过。 这个系统是全新安装的还是win10升级的呢？有做过什么安全设置么？ 另外有没有360之类的安全软件可以关闭之后重启一下quicker看看能否正常索引成功。
> > ```
> > 2022-06-13 01:03:29,945 [175] ERROR dVqNkRy0CGK6lXjuepM.S3TRh7yqEwq6wKNJuyA - 索引应用程序出错：发生一个或多个错误。
> > System.AggregateException: 发生一个或多个错误。 ---> System.UnauthorizedAccessException: 对路径“c:\program files\windowsapps”的访问被拒绝。
> > ```
> 
> 全新安装的win11，电脑没有第三方的安全软件 只有 Windows Defender，尝试了重启Quicker 无效

已增加异常处理，待下个版本更新看看。

**Comment by U2tzJTNE** [comment]
> > > 似乎是权限问题导致索引出错了。 这个现象目前还没有在其它电脑上遇到过。 这个系统是全新安装的还是win10升级的呢？有做过什么安全设置么？ 另外有没有360之类的安全软件可以关闭之后重启一下quicker看看能否正常索引成功。
> > > ```
> > > 2022-06-13 01:03:29,945 [175] ERROR dVqNkRy0CGK6lXjuepM.S3TRh7yqEwq6wKNJuyA - 索引应用程序出错：发生一个或多个错误。
> > > System.AggregateException: 发生一个或多个错误。 ---> System.UnauthorizedAccessException: 对路径“c:\program files\windowsapps”的访问被拒绝。
> > > ```
> > 
> > 
> > 全新安装的win11，电脑没有第三方的安全软件 只有 Windows Defender，尝试了重启Quicker 无效
> 
> 已增加异常处理，待下个版本更新看看。

ok

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions/Version?version=1.33.25.0 
 更新了一版，方便的时候试一下看看有没有解决。

**Comment by U2tzJTNE** [comment]
> https://getquicker.net/Help/Versions/Version?version=1.33.25.0 更新了一版，方便的时候试一下看看有没有解决。

已解决，棒棒哒~
