### ISSUE TITLE
office套件无法使用手势操作

### ISSUE THREAD

**Issue by Mark-Libetter** [cuiliang/QuickPadCn#1684]
**描述BUG**
手势按键在别的程序都能用，但是word，ppt，excel都不能激活

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win
 - Quicker版本：1.33.19

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
录个屏看下。
quicker有没有移动到别的目录运行？
检查一下黑名单、全屏禁用之类的选项看看？
还有看下没有在各场景下禁用手势
![image](https://user-images.githubusercontent.com/1972649/173705243-8c9734e5-7bfc-49b1-bc79-1ed558dda130.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
