### ISSUE TITLE
请问您在苏州麦软网络（思杰马克丁）上售卖订阅版吗？

### ISSUE THREAD

**Issue by MC-dusk** [cuiliang/QuickPadCn#1685]
https://www.mairuan.com/quicker/1635926361284.html

![图片](https://user-images.githubusercontent.com/52311860/173731719-33a1c8da-2a7b-45a3-98a4-365d3cb81c33.png)

**Comment by cuiliang** [comment]
没有，不太清楚这个是怎么回事。

**Comment by MC-dusk** [comment]
> 没有，不太清楚这个是怎么回事。

老生常谈的问题了，简单地说就是官方盗版。之前Listary、Vegas都被拿去卖，现在好像没了，但Mathtype、FL Studio等等都还在卖。我没记错的话，两年前Quicker是不在上面的。

很多链接已经被打掉了，剩下几个，暂时还能访问。

https://bbs.kafan.cn/thread-2091302-1-1.html

https://www.zhihu.com/question/46746200

https://github.com/18796299507/Corl-Product-KeyGen2018-CorelDRAWX6X4

**Comment by cuiliang** [comment]
哦，这个卖软就是思杰马克丁呀。早期有在我这里购买过几个兑换码倒是，可能这个链接是给它自己的用户下单准备的。
Quicker的兑换码它应该是没办法生成的，这个是我这里后台生成写数据库的，假的用不了。

**Comment by MC-dusk** [comment]
好的，没问题了
