### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by xiaochun-chen** [cuiliang/QuickPadCn#1686]
**描述BUG**
对bug的清晰简洁描述。
程序的快速启动功能对.net framework开发的程序不起作用
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 专业版21H2
 - Quicker版本：1.32.8

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不是很明白，请详细描述一下问题

**Comment by xiaochun-chen** [comment]
用quicker打开“百度营销”，还有自己用C#开发的一个WinForm程序不起作用

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月16日 7:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cuiliang/Quicker] 问题摘要 (Issue #1686)


不是很明白，请详细描述一下问题

―

**Comment by cuiliang** [comment]
@xiaochun-chen 截图、录屏一下。

**Comment by xiaochun-chen** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月2日 21:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cuiliang/Quicker] 问题摘要 (Issue #1686)


@xiaochun-chen<https://github.com/xiaochun-chen> 截图、录屏一下。

―
