### ISSUE TITLE
资源管理器中无法获取当前路径

### ISSUE THREAD

**Issue by w6lc** [cuiliang/QuickPadCn#1687]
问题：在资源管理器中运行动作无法获取当前路径
环境：win11 最新版（最近一次windows更新给资源管理器添加了多标签页功能）
![image](https://user-images.githubusercontent.com/49556918/174055821-fc1d13da-8537-4090-8f5e-a10d7527f311.png)

**Comment by cuiliang** [comment]
是报错么？
我这里测试是没有报错，获得的是第一个标签页里的路径。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.33.28已兼容多标签资源管理器获取当前路径，可以试下看看。
