### ISSUE TITLE
界面乱码

### ISSUE THREAD

**Issue by CloudBright1997** [cuiliang/QuickPadCn#1688]
**描述BUG**
界面乱码

**重现步骤**
1.
2.

**相关截图**
![image](https://user-images.githubusercontent.com/74401366/174421937-4f077466-c91b-4b1f-b7e0-95561f072635.png)

**环境信息:**
 - 操作系统版本：Windows 10 家庭中文版21H2
 - Quicker版本：1.33.27

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
参考这里 https://getquicker.net/KC/Kb/Article/973

**Comment by CloudBright1997** [comment]
真效率，解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月18日(星期六) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cuiliang/Quicker] 界面乱码 (Issue #1688)





 
参考这里 https://getquicker.net/KC/Kb/Article/973
