### ISSUE TITLE
希望开发者也能获取动作版本号

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1689]
为了方便用户，我在动作中添加了一些对版本号的判定和操作，现版本号是通过 获取系统或动作信息 —— 动作版本号获取的。经我测试，我安装下来的动作是可以获取版本号的，但我自己的源动作是无法获取版本号的，只会输出 0。这影响了我的正常使用，我要么不用这个源动作改为使用下载的，要么禁用掉相关判断等下次更新时再开启。我希望能获取动作页中的最新版本或手动设置的版本号。

quicker 版本：1.33.27

**Comment by cuiliang** [comment]
这个版本号是对应的动作库的版本号，是在安装动作的时候获取的。 对本地动作来说，并不存在这个号。
另外还会有一种情况，从动作库安装的动作A，版本号a，然后分享出去以后，得到动作B，版本号b。 这时候本地动作获取到的版本仍然是版本号a，获得到的动作库ID，仍然是A。但是其他人安装的，得到的动作库ID是B，版本号是b。

对于你说的情况，动作本身可以弄一个变量，在默认值里填写一个自定义的版本号。如果从获取系统信息得到的版本号是0，那么就读取那个变量的值。

**Comment by ghost** [comment]
> 对于你说的情况，动作本身可以弄一个变量，在默认值里填写一个自定义的版本号。如果从获取系统信息得到的版本号是0，那么就读取那个变量的值。

这确实是个办法，解决了我的问题，感谢提醒！
