### ISSUE TITLE
Quicker启动后严重影响对文件以及文件夹的操作

### ISSUE THREAD

**Issue by tshuangteng** [cuiliang/QuickPadCn#1690]
**描述BUG**
１.　quicker启动后使用delete按键删除文件或者目录没有反应，需要刷新后确认是否已经删除。
２.　quicker启动后使用鼠标右击新建文件夹或者文件也没有反应，需要刷新后确认是否已经创建。

补充：该现象已经出现比较长的时间了，刚开始还以为是电脑开的软件多了 性能问题。
这几天反复测试，关闭quicker软件后一切就都正常了，希望作者大大，再验证下是否是quicker软件的影响。

**环境信息:**
 - 操作系统版本：
![image](https://user-images.githubusercontent.com/62510752/174497522-809d75f4-a3a6-499e-887f-5eff331f2c99.png)

 - Quicker版本：
![image](https://user-images.githubusercontent.com/62510752/174497585-9b1e368c-091e-4d79-8d61-a97cb5068b02.png)

**附加信息**
感觉比较严重，影响电脑的性能以及正常使用。

**Comment by cuiliang** [comment]
目前没有遇到过类似情况和反馈。 请加qq 197906，然后通过向日葵远程看一下。

**Comment by cuiliang** [comment]
解决了么？

**Comment by tshuangteng** [comment]
还没有　可能与我使用的en-win10pro英文系统有关? 
目前不敢折腾系统

**Comment by cuiliang** [comment]
需要远程看下么？需要的话加 qq 197906，然后通过向日葵远程看一下。

**Comment by tshuangteng** [comment]
不太方便　
看样子　这个问题我是个例　那就和quicker没有关系　还是我自己折腾吧　后续有问题我再反馈吧
辛苦作者大大了

**Comment by cuiliang** [comment]
好的，需要的时候随时联系
