### ISSUE TITLE
未设置X1键激活时，占用了其它鼠标动作定义软件对X1键动作的定义

### ISSUE THREAD

**Issue by yyysuo** [cuiliang/QuickPadCn#1691]
**环境信息:**
 - 操作系统版本：Windows 11 专业版 21H2 22000.739
 - Quicker版本：1.33.27

**Comment by cuiliang** [comment]
检查各个设置里哪里使用了x1.
- 轮盘菜单
- 鼠标手势
- 高级鼠标触发
- 快速截图

如果找不到的话，加qq 197906，使用向日葵远程一下。

**Comment by yyysuo** [comment]
感谢回复，是鼠标手势占用了，问题已经解决。
