### ISSUE TITLE
在edge中左键辅助失效

### ISSUE THREAD

**Issue by zlxuan** [cuiliang/QuickPadCn#1693]
**描述BUG**
在edge中左键辅助功能不能用了，按住左键没效果了。

**环境信息:**
 - 操作系统版本：win10  21H2
 - Quicker版本：1.32.8
 - edge版本：102.0.1245.44 (正式版本) (64 位)

**附加信息**
在其他软件中正常。

**Comment by cuiliang** [comment]
关闭Edge的微型菜单试一下 https://getquicker.net/KC/Kb/Article/1000

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
