### ISSUE TITLE
希望步骤组添加“停止运行中的动作时等待此步骤组运行完成”选项

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1694]
有些连续的操作需要分多个步骤进行，如果中途打断可能会产生一些负面影响，希望能把它们放在一个步骤组里在用户终止动作时先运行完此步骤组再终止，类似运行脚本的等待进程结束。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！ 此功能无法实现。
