### ISSUE TITLE
多设备备份路径运行找不到文件或驱动器

### ISSUE THREAD

**Issue by wuhensoft** [cuiliang/QuickPadCn#1695]
**描述BUG**
打开EXE找不到驱动器或找不到路径

**重现步骤**
1、按图片说明设置。
2、运行动作

**相关截图**
![设置](https://user-images.githubusercontent.com/25846916/176587656-074acf68-3b44-4657-a48f-c98769864d28.png)
![2](https://user-images.githubusercontent.com/25846916/176587853-2be0fd86-fe2d-4abe-9102-f05d2e8b5f0a.png)

**环境信息:**
 - 操作系统版本：WIN10 22H2
 - Quicker版本：1.33.38

**附加信息**
这个备份路径运行，不是判断文件是否存在，不存在就检测运行下一个路径，直到文件存在的路径？

**Comment by cuiliang** [comment]
是会判断的。 这个是判断通过之后在后续启动进程的时候报的错。这个路径是从哪里复制的呢？试一下从H那里按三次退格，再输入H，看看会不会还报错（清除可能存在的不可见字符）

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
