### ISSUE TITLE
cpu 占用高且性能差时捕获控制台输出可能导致脚本卡死

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1696]
**描述BUG**
我有一个在软件运行时备份数据的动作，会先通过 Shadow Copy 获取副本，然后调用软件备份。这一过程会消耗大量 cpu 资源，我的 i7 8700k cpu 占用会直接拉到 99.9%，但捕获控制台输出并不会导致问题

我有一个用户，cpu 是 ryzen 5 4500u，捕获控制台输出大概率会让他卡在运行脚本那一步，关闭动作都不会弹出调试文件的那种，只要关掉捕获就能正常运行，且其他占用 cpu 不高时进行捕获控制台输出的脚本也可以正常运行。

我们的 Quicker 版本都是 1.33.38

**Comment by cuiliang** [comment]
控制台缓冲区有一个容量限制，超过那个大小就会卡住。可以考虑先写到文件里，后期再读取文件处理。
