### ISSUE TITLE
文本提取

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1698]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
如何把(Christophe Guilluy)里的文本提取出来？
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
在用quicker批量提交英文PDF到阿里翻译进行翻译，但是翻译下载的word名字的全部都是字符，需要进行重命名
Twilight of the Elites Prosperity, the Periphery, and the Future of France (Christophe Guilluy)
变成
精英的黄昏=繁荣、边缘和法国的未来=Christophe Guilluy克里斯托弗·吉卢伊
把括号里面的英文名字提取出来
目前不知道怎么提取，只能手动剪切出来
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20220703163548](https://user-images.githubusercontent.com/44609485/177031913-9c0f903d-02d2-4b11-b81f-71831a63eb96.png)

![天若_20220703163602](https://user-images.githubusercontent.com/44609485/177031924-37f43887-22a1-46f8-8bee-06a5103a9918.png)

**Comment by cuiliang** [comment]
不太懂。似乎文本提取一般用正则表达式，你可以研究一下试试
