### ISSUE TITLE
quicker公司内网版本使用

### ISSUE THREAD

**Issue by Soumns777** [cuiliang/QuickPadCn#1699]
**需求描述**
本人需要在公司内网开发,同时希望在内网使用quicker,不知道能否开发一套适合在内网使用的流程呢。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
内网使用请参考这里：
https://getquicker.net/KC/Manual/Doc/install#O3Rpu
