### ISSUE TITLE
希望能通过链接动作快速定位源动作

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1700]
**需求描述**
能通过链接动作来编辑、使用源动作很舒服，但不能通过链接动作发布或更新动作，编辑完后还是要找到源动作才能发布更新。希望能通过链接动作快速定位源动作，或直接通过链接动作发布、更新分享？反正链接动作本身也没有分享的价值

**Comment by ghost** [comment]
或许还能增加一个该链接动作与源动作位置互换的选项？

**Comment by cuiliang** [comment]
1.34.13 同步一下分享菜单。
