### ISSUE TITLE
100%复现，pin图最大化崩溃

### ISSUE THREAD

**Issue by Faith-Mian** [cuiliang/QuickPadCn#1701]
使用“摘取”和“ever截图”两个动作多次尝试，pin了截图后立即按下其他ahk脚本的热键最大化此图，数秒后quicker100%崩溃。

操作系统版本：WIN10 X64
Quicker版本：1.33.38

**Comment by cuiliang** [comment]
感谢反馈，等研究下看看。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.34.7里应该解决了。
