### ISSUE TITLE
无法激活Win+V,  窗口异常置顶

### ISSUE THREAD

**Issue by xibidix** [cuiliang/QuickPadCn#1702]
**描述BUG**

近期发现两个问题
用户484363352703580
感觉Quicker软件为日常工作带来了便利；

一、使用win自带的【剪切板历史记录】问题
1、如果开机默认开始Quicker，则Win+V 系统的【剪切板历史记录】，无法激活使用
2、必须要退掉Quicker，后按Win+V后，激活【剪切板历史记录】
3、再运行Quicker，才能使用 【剪切板历史记录】

二、经常性窗口被强制置顶
WPS，Chrome、钉钉等，几乎所有开启的界面
鼠标点击其它非激活窗口时，无法前置，总补当前操作的窗口给置顶在前面；
只有退到Quicker后，才得以回复正常

**环境信息:**
 - 操作系统版本：win10 企业版 LTSC 
 - Quicker版本：Quicker 1.33.38，升级前一个版本也不行

**Comment by cuiliang** [comment]
这两个问题都没有遇到过，也没有其他人反馈过，感觉有点奇怪。

请找一个别的电脑登录一下账号测试看看有没有这样的现象。

win+v应该没有影响的。无法激活使用时Win+V不弹出windows的剪贴板历史？
可以在设置里检查一下quicker里有没有设置Win+V的快捷键。 不过Quicker应该本身注册不了这个快捷键的。
![image](https://user-images.githubusercontent.com/1972649/178891696-2bd4ea5c-3e25-418d-92d4-52ba03c7d36a.png)


第二个最好录屏看一下

**Comment by xibidix** [comment]
> 这两个问题都没有遇到过，也没有其他人反映过，感觉有点一般。
> 
> 请找一个其他的电脑登录一下测试看看有没有这样的现象。
> 
> win+v 应该没有的。激活时应该没有 。的。 ![图片](https://user-images.githubusercontent.com/1972649/178891696-2bd4ea5c-3e25-418d-92d4-52ba03c7d36a.png)
> 
> 第二个最好的录屏看一下

第一个问题不大，也是近期出现，可以临时处理
第二个问题他也不是时常出现，偶尔会，如果再次出现，我录下，再来反馈
