### ISSUE TITLE
切换用户选择窗口的置顶状态会导致界面元素变为空白

### ISSUE THREAD

**Issue by 4285f4** [cuiliang/QuickPadCn#1703]
**描述BUG**
切换用户选择窗口的置顶状态会导致界面元素变为空白

**重现步骤**
1.弹出一个用户选择窗口，单选多选不限
2.等待一段时间或鼠标逐个划过选项，点击置顶按钮，界面元素必定变为空白。重复多次点击置顶按钮大概率触发
3.鼠标划过界面元素所在的位置或者再次点击置顶按钮，元素恢复

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
正常显示
![image](https://user-images.githubusercontent.com/36158676/178980083-5396bf09-6e63-4407-95bd-a379585ed7e9.png)
触发Bug
![image](https://user-images.githubusercontent.com/36158676/178980165-bbbd1b31-ec0b-4d0d-8cc3-2ae4c9ff3cd8.png)

**环境信息:**
 - 操作系统版本：Windows11 22H2 22622.290 专业版
 - Quicker版本：1.34.3

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
本地测试未能重现。如果有别的电脑，可以测试一下看看

**Comment by cuiliang** [comment]
这个应该是WPF底层的渲染bug，我也遇到过。 不过没有什么办法稳定重现和解决。
关闭古老issue中，感谢！
