### ISSUE TITLE
通过Quicker浏览器插件运行 JS 脚本提示操作超时，没有获得插件响应，但实际上脚本被重复执行了。

### ISSUE THREAD

**Issue by zj1123581321** [cuiliang/QuickPadCn#1704]
**描述BUG**
通过Quicker浏览器插件运行 JS 脚本提示操作超时，没有获得插件响应，但通过网页 log 发现脚本被多次重复执行。
![image](https://user-images.githubusercontent.com/33171229/179026068-b1e7236c-bb15-45f8-a88a-1ccf3d0a17be.png)
![image](https://user-images.githubusercontent.com/33171229/179026634-946e51b9-4b8d-4de8-82ab-6db184d7060c.png)

- 插件已开启全部权限，提示连接正常。
![image](https://user-images.githubusercontent.com/33171229/179025777-ee42f847-10d5-4f56-be98-344eb503184c.png)
- 脚本可以直接粘贴进 console 页面，运行是正常的。
- 切换 Microsoft Edge 浏览器尝试也有同样的问题。

**重现步骤**
1. 安装 https://getquicker.net/Sharedaction?code=eb2ef401-0031-4fae-a15d-08da64ce4f50 动作
2. 在 [2021 New Kids Wholesale Toddler Push 2 In 1 Foldable Musical Wheels Activity Walker Toys Baby Walker - Buy Foldable Baby Walker,Toy Helicopter For Toddler,Baby Toy Product on Alibaba.com](https://www.alibaba.com/product-detail/2021-New-Kids-Wholesale-Toddler-Push_1600176861071.html) 页面运行此动作
3. 会发现 console 页面有多次脚本记录，并且 Quicker 会提示操作超时。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win-10.0.19044.0 
 - Quicker版本：Quicker-1.34.3.0

**附加信息**
调试运行的日志如下：
[提取商品主图 Url 2022-07-14 23:51:22](https://temp.getquicker.net/2923/8a75a39d8c7244c8b36d2207cc5392b4.htm)

**Comment by cuiliang** [comment]
可能页面框架比较多。 试一下改成只在主框架运行看看有没有效果。
![image](https://user-images.githubusercontent.com/1972649/179117647-881a51af-d677-49f6-84d1-0d71960940ae.png)

**Comment by zj1123581321** [comment]
可以了，感谢：)

**Comment by cuiliang** [comment]
好
