### ISSUE TITLE
调试输出会将变量值中的多个空格合并为一个

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1705]
![image](https://user-images.githubusercontent.com/48246272/179175129-e158b2b2-813e-4789-a181-c743975ae8d1.png)
我以为调试文件中的控制台输出会和内部判断的一样，就通过这种方法来获取关键字符串进行判断，但发现无论是 .contians() 还是正则判断都无法成功，最后通过文本窗口展示该值后发现有一处应是多个空格，而在调试文件中被合并成了一个，麻了
quicker 版本 1.34.3

**Comment by cuiliang** [comment]
调试输出为HTML格式，HTML会把多个空格合并在一起显示。 特定内容可以使用文本窗口显示一下以准确判定。

**Comment by cuiliang** [comment]
想办法处理成和上面一样了，待1.34.13版本更新。
