### ISSUE TITLE
Http 请求模块-Multipart表单格式-总是得到错误码

### ISSUE THREAD

**Issue by zj1123581321** [cuiliang/QuickPadCn#1706]
**描述BUG**
我在编写一个中文图片直接翻译成英文图片的动作，使用了 [百度图片翻译的  API](https://ai.baidu.com/ai-doc/MT/mki483xpu)。参照百度文档的设置，在 Postman 测试一切正常。

但把相同的参数用 Quicker 的 Http 模块发送，则会一直报错：
> 58001 | INVALID_TO_PARAM | 译文语言方向不支持，或译文语言字段有误 | 请检查译文语言是否在语言列表里

但我检查了自己的参数配置，确认是符合文档要求的。

拿 Fidder 抓了 Postman 和 Quicker 发请求的包，能找到的差异是在 Header 里：
![image](https://user-images.githubusercontent.com/33171229/179246493-e5ebd248-08dd-4984-b36d-dbe8444d81a8.png)
![image](https://user-images.githubusercontent.com/33171229/179246555-2776706e-e8eb-4b26-aa7b-fa84491e3866.png)

不知道这个问题该怎么解决？感谢：)

**重现步骤**
1. 安装 [图片翻译 - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=2fc100f7-e4ce-4e7d-dc0a-08da65fa167e) 动作
2. 修改图片的本地位置，调试运行发一次请求。
![image](https://user-images.githubusercontent.com/33171229/179246913-d9b9046e-ba47-4f2c-ad80-247851f31e7d.png)

**相关截图**

**环境信息:**
 - 操作系统版本：Win-10.0.19044.0
 - Quicker版本：Quicker-1.34.3.0

**附加信息**
[HTTP请求 - Quicker](https://getquicker.net/KC/Help/Doc/http#koJnr)

**Comment by qsgy-edge** [comment]
![image](https://user-images.githubusercontent.com/60124215/179346062-95dd91a0-0aad-4d1e-a137-b4668a6e436c.png)
变量要用插值
![image](https://user-images.githubusercontent.com/60124215/179346120-b8431561-b950-4f6a-82a2-75263d4d84dd.png)

**Comment by cuiliang** [comment]
@qsgy-edge 这里确实是不用插值的。  @zj1123581321 我试下看看。

**Comment by cuiliang** [comment]
百度的服务器有点兼容性问题：
1）不能有上面的ContentType
2）name的值要加引号
![image](https://user-images.githubusercontent.com/1972649/179348121-12849f0e-ffa3-4893-a108-7ac245ead48b.png)

我处理一下，待下个版本。

**Comment by cuiliang** [comment]
试下 1.34.11 版 https://getquicker.net/Help/Versions

**Comment by zj1123581321** [comment]
谢谢崔老师，已经可以了。
