### ISSUE TITLE
运行Python函数作为子动作

### ISSUE THREAD

**Issue by huweiATgithub** [cuiliang/QuickPadCn#1707]
**需求描述**
Python是一个功能强大并且简单入门的程序语言，用户量很大。如果可以将运行python程序作为动作的一部分，那对很多熟悉python的用户而言将会特别方便。
用户也可以自行安装所需的python包，扩展性好。

**描述你想要的解决方案**
可以直接在quicker中给出python函数的定义。
从quicker的context中获取变量作为函数的传入参数，再获取函数运行的结果输出到quicker的context中去。

**描述您考虑过的替代方案**
现有的一个动作：https://getquicker.net/Sharedaction?code=762fac38-addb-4bf1-95ae-08d697dd918b
的解决方案是把一段python的代码写入到一个临时脚本文件中去执行，有些烦琐了，另外输出也受限于console output。

 **其他上下文**
功能类似Ultisnips中与Python的交互：
https://github.com/SirVer/ultisnips 
http://vimcasts.org/episodes/ultisnips-python-interpolation/

**Comment by cuiliang** [comment]
python 就是版本问题有点麻烦。 一般电脑里会安装几个python版本？平时是怎么避免冲突的呢

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 试下12版。

**Comment by huweiATgithub** [comment]
我了解的python的版本管理有：
- 使用conda，pipenv，pyenv等等来创建虚拟环境，可以管理python的版本和packages的版本，一般是一个项目一个环境。
- 一些基于python的软件可以把它的环境一块打包起来运行，比如pipx
我觉得是否可以把python的版本管理以及包管理交由用户自己来搞？添加一个设置让用户设置python的目录？
或者干脆quicker内置一个版本的python，我想基础的python功能已经很够用了，暂时不考虑通过包扩展？

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
