### ISSUE TITLE
想要更快速显示面板动作的提示

### ISSUE THREAD

**Issue by moroal** [cuiliang/QuickPadCn#1708]
**需求描述**
现在鼠标悬停在面板上很久才能出现功能/用途说明，太久了，不愿意等

**描述你想要的解决方案**
想要鼠标停在动作上时，快速显示功能/用途说明

**描述您考虑过的替代方案**
自定义“功能/用途说明”在鼠标放置多久后出现

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
通常应该很少会使用到显示提示的情况，所以这个设置的比较常，避免经常出现影响视线。
你那边是什么样的具体情况需要尽早显示呢？

**Comment by moroal** [comment]
最近没太关注，用的还挺好的
