### ISSUE TITLE
多字段表单无法通过纵向拉长展示更多内容

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1709]
![image](https://user-images.githubusercontent.com/48246272/179890848-66a67351-8b35-48cd-af14-4618af81d24e.png)
![image](https://user-images.githubusercontent.com/48246272/179890954-3a189de9-54a8-4b30-b02d-d6c4e76ee9ff.png)
横向倒是可以把一行没展示完的字展示完

**Comment by cuiliang** [comment]
感谢反馈~

**Comment by cuiliang** [comment]
已修复，待1.34.13版本更新。
