### ISSUE TITLE
子程序最后更改时间时区错误

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1711]
最后更改时间是 UTC +0，而已分享时间是 UTC+8
![image](https://user-images.githubusercontent.com/48246272/179913727-34a11fcd-9697-4a23-8577-e1252a0d6382.png)

**Comment by cuiliang** [comment]
感谢反馈，我研究下

**Comment by cuiliang** [comment]
测试了一下，没有复现。
![image](https://user-images.githubusercontent.com/1972649/180118754-6c2a8e76-7abf-4d16-9faa-8b153f43e0f6.png)

你的电脑时区设置时多少呢？ 如果方便请提供一下可复现问题的步骤

**Comment by ghost** [comment]
时区是 UTC+8 
![image](https://user-images.githubusercontent.com/48246272/180120212-857754b6-803a-47a4-abff-cac9c98291bf.png)
我测试了一下，只有**公共子程序**会这样，未分享过的也有问题，动作内子程序是正常的
随便右键一个 quicker 动作编辑，右键公共子程序点分享，弹出的最后更改时间就是UTC+0，进行一次更改后也是
![image](https://user-images.githubusercontent.com/48246272/180120142-bf1cc126-ddba-4d1c-9a05-99be459b688c.png)
版本 1.34.10

**Comment by cuiliang** [comment]
已修复，待1.34.13版本更新。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 已更新1.34.13 版。
