### ISSUE TITLE
能否为一个动作设置多个适用软件？

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1712]
我有一个备份动作[智能备份](https://getquicker.net/Sharedaction?code=8dfe1e68-33f0-4329-14ae-08da4a84097c&fromMyShare=true)，最先是为 sm18 备份，经过了一次次更新，现在还能为 Obsidian、思源、Logseq 等笔记软件备份，没有软件其实也可以。这些都是知识管理相关软件，若设置为通用，就无法在其中任何一个软件分区下找到，反而无法精确命中对此有需求的目标群体。若只放在其中一个软件下，就无法方便到其他适用软件的用户。希望能设置多个适用软件。

**Comment by cuiliang** [comment]
计划近期开发

**Comment by cuiliang** [comment]
已增加 https://getquicker.net/QA/Question/12605  开发能力比较弱，效果只能凑合😂
