### ISSUE TITLE
希望“左键辅助”和“高级鼠标触发”能增加“滚动”的功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1713]
我希望按住鼠标左键后滚动鼠标滚轮能够发送“Ctrl + Tab”和“Ctrl + Shift + Tab”

这就需要左键辅助中增加“上下滚动滚轮”的选项，但是现在并没有这个选项

而右键手势软件“MouseInc”中有一项功能叫做“滚轮快切”，其用法就是把滚动也当做了右键手势的一种，，希望quicker也能增加这一功能

下图为quicker中的“左键辅助”功能

![image](https://user-images.githubusercontent.com/36830343/180287284-a043febb-07c5-4083-a989-cc3e4142b6af.png)

下面两图为MouseInc中的“滚轮快切”功能的开关与具体手势设置
![image](https://user-images.githubusercontent.com/36830343/180287749-fb091ffc-ee39-499f-89ad-0560d9c5821c.png)

![image](https://user-images.githubusercontent.com/36830343/180287789-ebd4e56f-00b9-4f0d-84b9-365ce7ef3b89.png)

**Comment by cuiliang** [comment]
在高级鼠标触发中设置滚轮触发。
![image](https://user-images.githubusercontent.com/1972649/180334284-323c8e35-cd14-4c68-94ac-ad15d690f513.png)
