### ISSUE TITLE
希望可以复制粘贴多字段表单中的项

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1714]
我有个动作的设置内容有些多，就分成了三张设置面板，昨晚发现有分组功能能以标签页的形式显示不同设置，就又把三张面板合到了一起，就是过程有些……欲哭无泪
![image](https://user-images.githubusercontent.com/48246272/180366646-de742bf5-6e76-4e01-ace4-61a4075ab12b.png)

**Comment by cuiliang** [comment]
可以按Ctrl多选后右键批量调整分组一下

**Comment by ghost** [comment]
> 可以按Ctrl多选后右键批量调整分组一下

你误会了，这是三个不同的多字段表单模块，我无法将其中一个表单的字段移动到另一个表单，只能全部重建一次

**Comment by cuiliang** [comment]
大概明白了

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  方便的时候试下1.34.14看看

**Comment by ghost** [comment]
测试了下，挺好的
