### ISSUE TITLE
多字段表单切换到内容较多的分组时会使内容超出屏幕

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1715]
**描述BUG**
![image](https://user-images.githubusercontent.com/48246272/180367700-6d96b877-bcdf-418b-98ca-5be04d2cf75d.png)

**重现步骤**
1.打开多字段表单
2.切换到内容较多的分组（直接打开内容较多的分组不会这样）

 - Quicker版本：1.34.13
 
此问题应是在修复了 https://github.com/cuiliang/Quicker/issues/1709 问题后出现

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
好的，我试试调整后就固定大小一下。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  方便的时候试下1.34.14看看

**Comment by ghost** [comment]
测试了下，此 bug 已修复
