### ISSUE TITLE
希望多字段表单的分组选项卡能保持在顶端

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1716]
![image](https://user-images.githubusercontent.com/48246272/180371461-bc535bfb-a686-4227-b6e9-46a1013ed78c.png)

往下滑动之后分组选项卡消失

![image](https://user-images.githubusercontent.com/48246272/180371571-5b838071-84a1-43fe-a337-9658632acac1.png)

quicker 版本： 1.34.10 、1.34.13

**Comment by cuiliang** [comment]
后来的版本已实现。
