### ISSUE TITLE
希望提取文件路径信息/生成路径 中的文件名也能输出文件夹名

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1717]
![image](https://user-images.githubusercontent.com/48246272/180374049-ba41f763-8b52-458b-9c76-5e6f291145b9.png)

如果是末尾没有反斜杠的文件夹路径，是可以获取的

![image](https://user-images.githubusercontent.com/48246272/180373538-0317bad2-547f-43ec-9d04-18232b1195f7.png)

如果带上反斜杠，则不能

![image](https://user-images.githubusercontent.com/48246272/180373604-72f91e7a-3597-43d6-92d9-2ff38c741d2b.png)

如果该项实际上是正则匹配的话，可以通过该正则匹配准确输出：
`(?<=\\(?!$)(?=([^\\]|\\$)+$)).*?(?=$|\\$)` 
![image](https://user-images.githubusercontent.com/48246272/180373882-c6962773-810b-4e98-be13-1e9607f96158.png)

**Comment by cuiliang** [comment]
这个是.Net Path.GetFileName()的默认处理。我感觉也是合理的，与实际匹配。
如果需要处理带斜杠的，可以在前面增加一个滤除。 $= {path}.TrimEnd('\\');

**Comment by ghost** [comment]
> 这个是.Net Path.GetFileName()的默认处理。我感觉也是合理的，与实际匹配。 如果需要处理带斜杠的，可以在前面增加一个滤除。 $= {path}.TrimEnd('\');

受教了，没学过计算机语言，我一直用正则去末尾斜杠的
![捂脸](https://user-images.githubusercontent.com/48246272/180375192-c0c9922d-c8e8-4837-83f1-831b6c5a89f5.jpg)
不过你写的应该是`$= {path}.TrimEnd('\\')`吧，markdown 语法里连续两个 \ 只会展示出来一个除非两端加上 ` 变成代码块样式，只有一个的话就表达试解析错误了，

**Comment by cuiliang** [comment]
Quicker表达式里可以写简单的c#脚本。在C#里\是特殊字符，需要转义。 转义字符是\，所以就是两个\\表示一个\字符了。
https://getquicker.net/KC/Help/Doc/expression
