### ISSUE TITLE
希望可以通过代码编辑器窗口编辑表单字段

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1719]
![image](https://user-images.githubusercontent.com/48246272/180635668-79f41a65-0e5f-4ace-bfb6-8c4e99c5bd2f.png)

没有代码编辑器选项

![image](https://user-images.githubusercontent.com/48246272/180635488-be19a2de-c831-45f6-9d7e-27b33a998958.png)
![image](https://user-images.githubusercontent.com/48246272/180635500-cce62639-d960-462d-a400-49fc4d051960.png)

**Comment by cuiliang** [comment]
主要是这个帮助提示的框吧？

**Comment by ghost** [comment]
是的，字段标题一般不会写长，但有的时候比较复杂的选项帮助提示会写上两三行，手动换行可能会增加行数更不利于排版，直接写就会因为太长显示不全比较难受

**Comment by cuiliang** [comment]
1.34.16 增加了。 https://getquicker.net/Help/Versions
