### ISSUE TITLE
设置动作自启动出现黑框

### ISSUE THREAD

**Issue by lingjianjun** [cuiliang/QuickPadCn#1720]
**描述BUG**
设置了一个ps中键变手的动作，希望quiker启动后这个动作会自动运行，但是屏幕顶部会出现一个框框

**重现步骤**
1.动作地址：https://getquicker.net/Sharedaction?code=79db57d8-c11f-4e14-ced3-08da52542005
2.设置动作随软件启动

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/40479923/180682369-2a4df622-f888-4a50-ae3c-e6e2b9e243eb.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
动作里可能有等待按键的步骤。为安全考虑，这个步骤会显示一个提示窗口，如果没有设定提示文字就会显示成这样的一个条。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
