### ISSUE TITLE
在一个动作中启动另一个动作,不应该被归类为“从外部启动Quicker动作”

### ISSUE THREAD

**Issue by kkxg** [cuiliang/QuickPadCn#1721]
**需求描述**
在一个动作中启动另一个动作不应该被归类为“从外部启动Quicker动作”

 **其他上下文**
![image](https://user-images.githubusercontent.com/20535377/180726763-60713e1d-06e4-4453-876e-94350d12eac1.png)
![image](https://user-images.githubusercontent.com/20535377/180727062-57fd6506-0a83-4de3-abb3-b9f16b8f87de.png)
![image](https://user-images.githubusercontent.com/20535377/180727186-cc316b3d-168c-4240-a541-aaf75a26b152.png)
quicker内部启动另一个动作也算？我麻了...

**Comment by cuiliang** [comment]
用运行其它动作模块，而不是通过uri启动。
![image](https://user-images.githubusercontent.com/1972649/180731601-b1aaad61-c55d-4731-b57f-94b802aa3dc7.png)

另外请理性讨论，不要发“我麻了”这类语气词，看起来不是很爽。

**Comment by kkxg** [comment]
抱歉。。我找这个功能的时候是动作里面作者如此备注的：
![截屏_2022-07-25_16-22-19](https://user-images.githubusercontent.com/20535377/180733594-ac473da1-700b-434a-aaef-b8aa0757b66f.png)
实际上 运行或停止动作 确实没有问题。问题出在 运行指定动作的二级选项 :“quicker:runaction:xxxxx?二级动作选项名“ 这类的没办法使用。
所以我转而尝试编辑器中的运行或打开，查看教程正写明quicker:runaction:xxxxx。所以才来提issue.
对我不当的表达方式再次表示抱歉。

**Comment by cuiliang** [comment]
uri方式本身是为外部启动方式，也就是第三方环境来启动quicker动作提供的。在quicker内部应该直接使用模块，避免windows中转，效率更高。 我等在文档里增加一个说明。

**Comment by kkxg** [comment]
抱歉。。我找这个功能的时候是动作里面作者如此备注的：

实际上 运行或停止动作 确实没有问题。问题出在 运行指定动作的二级选项 :“quicker:runaction:xxxxx?二级动作选项名“ 这类的没办法使用。
所以我转而尝试编辑器中的运行或打开，查看教程正写明quicker:runaction:xxxxx。所以才来提issue.
对我不当的表达方式再次表示抱歉。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 在一个动作中启动另一个动作,不应该被归类为“从外部启动Quicker动作” (Issue #1721)





 
用运行其它动作模块，而不是通过uri启动。
 
 
另外请理性讨论，不要发“我麻了”这类语气词，看起来不是很爽。

**Comment by cuiliang** [comment]
> 抱歉。。我找这个功能的时候是动作里面作者如此备注的： ![截屏_2022-07-25_16-22-19](https://user-images.githubusercontent.com/20535377/180733594-ac473da1-700b-434a-aaef-b8aa0757b66f.png) 实际上 运行或停止动作 确实没有问题。问题出在 运行指定动作的二级选项 :“quicker:runaction:xxxxx?二级动作选项名“ 这类的没办法使用。 所以我转而尝试编辑器中的运行或打开，查看教程正写明quicker:runaction:xxxxx。所以才来提issue. 对我不当的表达方式再次表示抱歉。

其他人分享的动作可能确实会输出这样的uri，毕竟生成起来比较方便一些，也可以方便在其他位置使用。 不过也没办法要求别人分享什么样的动作，都是免费分享给大家用的，已经非常感谢了。
