### ISSUE TITLE
搜索框打开后，拦截第一个输入字符

### ISSUE THREAD

**Issue by teteko233** [cuiliang/QuickPadCn#1722]
**描述BUG**
打开搜索框后输入，会拦截第一个输入的字符，同时系统会发出提示声，之后的第二个字符可以正常输入

**重现步骤**
1.使用快捷键打开搜索，默认是 ctrl+/ ，自己设置为 alt+space
2.快速输入一个字符

**环境信息:**
 - 操作系统版本：Win11 Home 21H2
 - Quicker版本：1.33.38

**Comment by cuiliang** [comment]
请升级到快速通道最新版试下。 https://getquicker.net/Help/Versions

**Comment by teteko233** [comment]
@cuiliang 已解决，thanks
