### ISSUE TITLE
quicker面板的翻页支持

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1723]
我使用的是ThinkPad的键盘，其上自带了鼠标的“三键”，因此可以直接触发面板，也就没有单独设置键盘快捷键触发面板了

现在的问题是，我使用鼠标中键打开面板之后，没有办法进行翻页，看了其他的issue发现只有使用键盘快捷键触发的时候才可以使用方向键翻页，能否为鼠标触发的时候也加上方向键翻页的选项？

或者更进一步，可以用方向键“导航”，移动一个选择框在面板的各个动作上移动，然后按空格键或者回车键触发；再用pageUp pageDown按钮来翻页，实现完全的键盘操作

---

另外有个问题就是，我设置了键盘快捷键指向quicker动作来翻页，具体定义见下图，在使用“多步骤输入”模拟滚动的情况下，同样没办法对鼠标触发的quicker面板进行翻页
![image](https://user-images.githubusercontent.com/36830343/181507892-fac87aff-7f2f-4621-baaf-058bc3c29302.png)

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/181512544-920d17d7-b8a0-477d-b3d8-c4da2a74e551.png)
选中这个就可以了。

模拟的鼠标消息不支持触发quicker的

**Comment by ilcpm** [comment]
好使！“上下”可以对上半部分翻页，“左右”可以对下半部分翻页！
