### ISSUE TITLE
鼠标手势无法在某些面板触发

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1724]
测试了管理员权限的程序发现都可以正常触发，但是发现在quicker的一个界面下无法触发鼠标手势，有点奇怪😂 

在这个搜索功能的设置页面里的时候鼠标手势无法画出

![image](https://user-images.githubusercontent.com/36830343/181508526-af180808-17bd-45be-93ed-5fe428f39403.png)

**Comment by cuiliang** [comment]
为了避免窗口叠加，quicker自带窗口需要特殊处理才能使用收拾。 我给这个窗口处理一下

**Comment by cuiliang** [comment]
已处理此窗口 1.34.17
