### ISSUE TITLE
鼠标手势希望增加“触发距离”和“超时”选项

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1725]
（刚写了十几分钟的issue发现没点提交就关了……😥）

在尝试从MouseInc迁移到quicker，发现没有“触发距离”和“超时”两个 设定

![image](https://user-images.githubusercontent.com/36830343/181512574-11d3b251-60a2-4ac8-be1e-ddb7acdae98b.png)

“功能性”上quicker支持按键传参，确实很强大，这两个设置更像是“人性化”的角度提出的，都是为了防止“误操作”

- 按住右键的短距离移动很可能只是“手抖了”，并不是希望触发鼠标手势，所以需要“触发距离”做为门槛
- 有时候手势画错了，或者中途发现不需要了需要取消，所以需要“超时”设定来结束手势（好像quicker的鼠标手势除了按Esc键没有啥别的办法可以取消）
- 另外右键手势完全阻断了原本的“右键拖动”这一操作，我个人会低频使用这个功能，如果有“超时”功能的话，MouseInc会在超时之后还原原本的“右键拖动”操作，也就解决了偶尔用用又不想取消鼠标手势的尴尬场景

谢谢，送你们花花🌺

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/181515839-b130691a-4730-49a5-8b19-75999fb5b5e6.png)

**Comment by cuiliang** [comment]
默认设置下，可以直接按左键取消手势和轮盘

**Comment by ilcpm** [comment]
这可真是，尴了个大尬……可以考虑在对应位置做个提示文本😂
