### ISSUE TITLE
鼠标手势UI优化

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1726]
修改鼠标手势的颜色之后，对应的提示颜色和弹出的提示框颜色没有变化（最好字体也可以修改）
![image](https://user-images.githubusercontent.com/36830343/181615978-69a38dd1-01eb-4c05-88c4-50204cf7ea67.png)

![image](https://user-images.githubusercontent.com/36830343/181615477-3dc8a7a4-4489-4e77-a20a-cc7d24eba6f4.png)

![image](https://user-images.githubusercontent.com/36830343/181615488-6c76eab3-4fb5-401c-a863-a1cec9a7517e.png)

另外希望能有个开关关掉这个“备选提示”，难看死了……
![image](https://user-images.githubusercontent.com/36830343/181615585-5fda292a-cbd3-44be-bf45-e7de14592882.png)

**Comment by ilcpm** [comment]
![image](https://user-images.githubusercontent.com/36830343/181618279-38cecee5-03e7-4269-b2e8-a27e5538da68.png)

我就画一根线，至于弹出这么多吗😥

**Comment by cuiliang** [comment]
提示列表只有停住一段时间才会显示，如果要停止手势直接按左键就可以了。 一般不会触发到这个。
文字颜色可能有点bug，没有立即生效，我等看下。

**Comment by ilcpm** [comment]
![image](https://user-images.githubusercontent.com/36830343/184585942-7a18170a-6e8a-46b6-b209-669a9e2130a3.png)

我看修复 了这个bug，不如把下面的那个手势颜色也同步修改一下？😂

> ![image](https://user-images.githubusercontent.com/36830343/181618279-38cecee5-03e7-4269-b2e8-a27e5538da68.png)

**Comment by cuiliang** [comment]
下面列表里这个颜色本身是蓝色的，不会变色。

**Comment by ilcpm** [comment]
那好吧，我的意思是可以统一一下都跟设置的颜色一样😂

**Comment by cuiliang** [comment]
这里是和设置界面里统一的😁

ilcpm ***@***.***> 于2022年8月15日周一 14:21写道：

**Comment by ilcpm** [comment]
![image](https://user-images.githubusercontent.com/36830343/184586705-6303ad1b-090a-4097-986c-d38a3d8f0c5b.png)

![image](https://user-images.githubusercontent.com/36830343/184586738-30ace34f-cf10-4c9b-a8b9-5f9d7db1eefd.png)

看起来我们说的是一个意思，但是现在这个弹出的“可能手势”中的颜色就是默认的蓝色，没有按我的设置来，用的是刚刚更新的最新版快速通道

**Comment by cuiliang** [comment]
这个其实主要是修改了这个问题 
![image](https://user-images.githubusercontent.com/1972649/184587031-346da663-b85b-410e-97c5-b4c1dd555efa.png)

至于提示列表里的，我等再考虑一下了。
