### ISSUE TITLE
轮盘菜单增加

### ISSUE THREAD

**Issue by L6HV** [cuiliang/QuickPadCn#1727]
你好 我买了quicker的三年会员 最新的这个版本我这里总需要重新挂钩 老版本的就没此问题 还有就是轮盘工具能添加的太少了 因为我是做设计的 能不能多几页 然后鼠标滚动翻页

**Comment by cuiliang** [comment]
更新版本到快速通道最新版试下是否还需要经常重新挂钩。有个内部机制修改了一下，造成了一些影响。

轮盘扩展有考虑，不过具体实施的时间可能比较久。

**Comment by L6HV** [comment]
感谢回复 我更新到快速 通道试一下 非常。期待轮盘的扩展


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月29日 18:36:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiliang/Quicker] 轮盘菜单增加 (Issue #1727)




 
更新版本到快速通道最新版试下是否还需要经常重新挂钩。有个内部机制修改了一下，造成了一些影响。
 
轮盘扩展有考虑，不过具体实施的时间可能比较久。

**Comment by cuiliang** [comment]
你好，触发问题有改善不？

**Comment by L6HV** [comment]
您好 触发已经好了 感谢关心



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月1日(星期一) 晚上7:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cuiliang/Quicker] 轮盘菜单增加 (Issue #1727)





 
你好，触发问题有改善不？
