### ISSUE TITLE
全屏时自动禁用⌈滚轮调节系统音量⌋

### ISSUE THREAD

**Issue by BenjiaH** [cuiliang/QuickPadCn#1728]
**需求描述**
全屏时自动禁用⌈滚轮调节系统音量⌋

**描述你想要的解决方案**
在进行全屏任务时，如游戏。常常会因为移动鼠标将指针置于屏幕底端或顶端，从而在滚轮时音量大小被修改，希望能自动禁用这项功能。
![image](https://user-images.githubusercontent.com/46958476/181674522-e42af6b2-4d11-49ff-9dc4-8c71ef890091.png)

**描述您考虑过的替代方案**
目前已经可以在全屏时禁用Quicker功能，但对禁用⌈滚轮调节系统音量⌋没有较好的支持。希望完善。
![image](https://user-images.githubusercontent.com/46958476/181674752-9041fa26-9e7b-4da1-9a92-20aa2fe1514b.png)

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![image](https://user-images.githubusercontent.com/46958476/181674522-e42af6b2-4d11-49ff-9dc4-8c71ef890091.png)

**Comment by ilcpm** [comment]
可以改成高级鼠标触发，在动作中设置全屏禁用

![image](https://user-images.githubusercontent.com/36830343/181691483-cf9a66a8-1ecd-44c2-b1ef-0fc04e9e4bd5.png)

**Comment by cuiliang** [comment]
是的，去掉默认设置，然后在高级鼠标触发中设置自定义规则即可。 很多时候全屏也需要调节音量，比如看视频什么的。
