### ISSUE TITLE
download目录下无当前版本安装包时升级失败

### ISSUE THREAD

**Issue by xhm12345abcde** [cuiliang/QuickPadCn#1729]
**描述BUG**
1.34.3版本升级至1.34.15版本时安装程序提示找不到1.34.3版本安装包，升级失败
在C:/Users/xxx/downloads中添加1.34.3版本安装包后正常升级

**重现步骤**
1.在C:/Users/xxx/downloads没有当前版本quicker安装包时安装新版本
2..在C:/Users/xxx/downloads添加当前版本quicker安装包，再安装新版本

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows 10
 - Quicker版本：1.34.3

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
是因为使用优化工具清理掉了windows的缓存文件造成的。 从官网下载旧版，卸载提示的时候选择旧版安装包
