### ISSUE TITLE
quicker chrome插件与主程序链接失效的问题。

### ISSUE THREAD

**Issue by pelico** [cuiliang/QuickPadCn#1731]
**描述BUG**
chrome 插件显示已连接。
![image](https://user-images.githubusercontent.com/50446355/182270111-6faa491a-d080-4060-8963-5fe2951e8f93.png)
运行需要用到插件时，反馈未连接。
![image](https://user-images.githubusercontent.com/50446355/182270187-102e8046-6634-470a-b7de-330795771fab.png)

**环境信息:**
应该不是系统和版本问题。使用环境你看下能不能找出问题：我的电脑建了两个用户。A,B用户都开启了quicker。尝试过启用，禁用插件，和重启quicker后，有时会正常连接可以使用。目前还没有摸清规律。 不知道是不是插件识别的已连接quicker是A用户打开的（进程id）。实际上我是想在B用户上运行软件并试图连接插件。

**Comment by pelico** [comment]
![image](https://user-images.githubusercontent.com/50446355/182271205-c2be4a93-05ae-4b0a-81a5-3108d233ad2a.png)
这里可以看到些问题，B用户已经关闭了 quicker软件，但是 禁用再启用 插件，插件会显示为已连接。

**Comment by pelico** [comment]
![image](https://user-images.githubusercontent.com/50446355/182271424-fed250e0-fbbe-4af0-9901-b98e558653c7.png)
我是在用户2上 使用插件。 用户1应该也开启着quicker软件的。

**Comment by cuiliang** [comment]
请把quicker升级到最新版后测试，如果仍有问题请提供下复现步骤。
