### ISSUE TITLE
编写组合动作时开发效率低，增加一些批量处理功能提高开发效率

### ISSUE THREAD

**Issue by hclwsyw** [cuiliang/QuickPadCn#1732]
**需求描述**
编写组合动作时开发效率太低。
1. 有时候我需要很多个步骤组或者其他动作，每一个都需要先点开才能添加注释，比较麻烦。
2. 变量定义模块：每次只能打开、添加、删除、处理一个变量，变量太多的时候不好管理。
3. 有时候也需要批量修改动作延迟。

**描述你想要的解决方案**
1. 希望批量添加步骤组或者动作，在批量添加时可以按行添加注释。同时后期出现向进行注释改动也能批量修改。
2. 希望变量添加批量管理功能，增加一个分组功能，以及变量在主程序中进行定位。
4. 能不能进行动作隐藏，可以暂时忽略掉不需要关注的部分。

**描述您考虑过的替代方案**

 **其他上下文**
总之，就是希望有一些便捷的操作，能够提升开发脚本时候的效率。在整个软件的使用过程中更加流畅。
包括后续的维护和修改希望可以更便利轻松。
在某些环节能够加入一些键盘操作更好。
感谢大佬，给大佬加鸡腿

**Comment by cuiliang** [comment]
目前的模式批量修改比较困难。 复杂的动作建议使用脚本方式实现，bat、powershell、ahk等。另外也可以使用子程序来进行一些逻辑复用，减少重复。
添加变量可以把已有变量拖放到+按钮快速添加。
延迟可以ctrl+滚轮快速调节。

**Comment by hclwsyw** [comment]
好的，谢谢大佬
