### ISSUE TITLE
“全屏禁用quicker”设置错误生效

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1733]
使用双显示器时，若禁用Windows中的“在所有显示器上显示任务栏”设置，只在一个显示器上显示任务栏
这时若在另一显示器上最大化窗口，quicker会将该窗口视为“全屏运行”，进而在勾选“全屏禁用quicker”之后无法使用quicker

示意图：
只在一个显示器上显示任务栏
![image](https://user-images.githubusercontent.com/36830343/182663988-cbd6d2cc-9655-4316-b5bf-596a3a0bc51b.png)

 双显示器下，没有任务栏的屏幕上最大化程序之后无法使用quicker，因为被视为了“全屏”，去掉该设置之后quicker可以正常调出
![image](https://user-images.githubusercontent.com/36830343/182664490-074ec7d2-f84b-426d-8fa2-0b1302f1354a.png)

**Comment by cuiliang** [comment]
目前全屏时按窗口大小和屏幕大小对比判断的。 （似乎也没有更好的判断方法，所以在下面可以添加一些白名单）
这种情况下符合全屏的判断逻辑。有些用户会在副屏进行游戏。

**Comment by ilcpm** [comment]
能不能在现在的条件下增加一个“窗口是否存在标题栏”的检测，我试了单屏幕的情况，只要任务栏不存在，且窗口最大化就被认为是全屏，感觉很奇怪……

试了一下MouseInc在这样的情况下也是可以正常识别的，应该就是quicker没有做标题栏的检测

**Comment by ilcpm** [comment]
查了一下，这个应该是正确的做法，系统的API
https://stackoverflow.com/a/58755620

**Comment by cuiliang** [comment]
@ilcpm 感谢分享，我试一下。不过这个似乎没有办法判断副屏全屏的情况

**Comment by cuiliang** [comment]
后来更新了一下代码，可以试试有没有改善 https://getquicker.net/Help/Versions

**Comment by ilcpm** [comment]
我放弃了，这个情况实在是太复杂了，我测试都不知道该如何下手

目前粗略测试的几个情况是，副屏上面没有任务栏的时候，Windows设置放大之后判断为全屏，QQ判断为全屏，Chrome正常识别全屏和普通放大

主屏上没有任务栏的时候，浏览器F11全屏的时候仍然可以使用quicker，播放器全屏的时候也可以使用，就是说没有被判断成全屏

测试的时候没有区分“自动隐藏任务栏”和“移走当前屏幕的任务栏”两个操作，就是说不清楚这两个操作会不会带来实际区别😥

MouseInc似乎在各个情况下的表现都是正常的，不清楚它是怎么做的判断

**Comment by cuiliang** [comment]
😂 等后期有空再研究下

**Comment by ilcpm** [comment]
辛苦辛苦，这东西是真的麻烦
