### ISSUE TITLE
Quicker运行出现字体错误，主窗口打不开

### ISSUE THREAD

**Issue by i2worker** [cuiliang/QuickPadCn#1734]
**描述BUG**
Quicker第一次运行的时候，会在下面出现【字体错误，请修复Windows中损坏的字体】提示信息(见图1)，然后显示不出主窗口。点击设置时，在弹出的窗口中点击【常规】【弹出面板】等设置时，会提示错误信息，具体见图2。

**相关截图**
![字体错误](https://user-images.githubusercontent.com/11516760/182790370-d1992464-a12a-45dc-ab88-63aa4230ed70.png)
![错误信息](https://user-images.githubusercontent.com/11516760/182790371-536501b3-c8c9-4d31-bfe9-8a94f088c8ef.png)

**环境信息:**
 - 操作系统版本：Win10_LTSC_2019_x64
 - Quicker版本：1.34.15

**Comment by cuiliang** [comment]
将Windows主题恢复为默认主题；检查Windows设置-字体设置窗口里有没有显示不正常的字体，删掉，然后再试下看看。

**Comment by i2worker** [comment]
好的，我试试看，谢谢。
