### ISSUE TITLE
弹出面板鼠标及键盘触发问题

### ISSUE THREAD

**Issue by hw1020** [cuiliang/QuickPadCn#1735]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.设置了下打开方式用鼠标中键左，现在取消不掉了，同时键盘上方向键左也会触发，导致开启软件就没办法使用键盘上的左方向键（上下左右那个箭头）

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：最新稳定版

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by hw1020** [comment]
显示没有勾选，但是一直可以用，无法取消。

**Comment by cuiliang** [comment]
怎么个取消不掉？ 是点不掉选项？保存不了？ 左键触发，看看下面快捷键那里是不是设置了。
截图一下吧。

**Comment by hw1020** [comment]
![image](https://user-images.githubusercontent.com/43195286/182798270-7fb0f73d-e605-4578-9878-d7aa2dc51157.png)
可以取消勾选，但是还是会触发

**Comment by cuiliang** [comment]
去掉这个 
![image](https://user-images.githubusercontent.com/1972649/182800172-717f2158-f478-4aaf-9cef-587f68dd4d3f.png)

**Comment by hw1020** [comment]
可以了，谢谢啦
