### ISSUE TITLE
偶发性的拖动窗口,窗口移动会很卡问题摘要

### ISSUE THREAD

**Issue by shaco-go** [cuiliang/QuickPadCn#1737]
**描述BUG**
偶发性的拖动窗口,窗口移动会很卡

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.34.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
在外观设置里关闭背景模糊选项。 Win11有时候有这个bug。
![image](https://user-images.githubusercontent.com/1972649/184575111-9f7af6c6-d87e-4f86-be0d-f83c5966f3b1.png)
