### ISSUE TITLE
Quicker的动作触发在快捷键上是否可以实现Vimium C一样的多键匹配动作

### ISSUE THREAD

**Issue by yudeye** [cuiliang/QuickPadCn#1739]
**需求描述**
(quicker是一个很不错的产品，在windows效率软件方面我觉得排第一当之无愧。现在每天我都大量依赖使用quicker，尤其喜欢通过quicker面板的快捷键触发动作。)

- **快捷键不够用：**对于常用动作我已经习惯为其绑定一个quicker面板的快捷键触发，但是当常用动作越来越多的时候，quicker面板的快捷键就明显不够用了。如图：
一个面板中一次性只能显示4*7=28个动作，我也映射了28个不同的快捷键。
![image](https://user-images.githubusercontent.com/89843952/184281693-024b75ab-4a3c-4015-8301-e5d6907e327a.png)

- **quicker面板的快捷键只能设置单一的按键：**了方便记忆快捷键对应的是哪个动作，我常常用动作的首字母和快捷键绑定，比如果“打开visual studio code”这个动作和字母“v”键进行绑定，但是如果我再有个动作是“打开visual studio”的动作我就不能再用"v"键进行绑定了，或许使用“s”键进行绑定，但这样就难以记忆了。

**描述你想要的解决方案**
我想用按"vc"键触发“打开visual studio code”动作，按"vs"键触发“打开visual studio”动作，这就类似于chrome 浏览器的Vimium C 插件：
![image](https://user-images.githubusercontent.com/89843952/184282517-fbdd7ae7-9a6d-4b6a-b325-66283007c751.png)
这样可以为quicker的所有动作绑定多按键匹配触发：
（quicker仪表盘展示的所有动作：）
![image](https://user-images.githubusercontent.com/89843952/184289532-59f192c4-7fa5-4e0f-bc6b-f6604080597f.png)
既能解决快捷键不够用的问题，又能让用户自定义快速触发想要的动作。

**描述您考虑过的替代方案**
- 为单个的动作绑定全局按键（而不是通过唤醒quicker面板再通过快捷键触发），但是这样很容易和其他软件有按键冲突...
- quicker有许多动作页，可以为一个“跳转到其他动作页”的动作绑定按键，借助这个动作作为跳板然后实现多按键匹配触发指定动作... 这样一来在下次触发quicker面板的时候还得手动回退到初始页面，稍显麻烦。
- 通过quicker的全局搜索动作快速匹配和触发指定动作，这样的话也相对麻烦一点。

 **其他上下文**
这是我目前的quicker按键设置：
![image](https://user-images.githubusercontent.com/89843952/184283740-c96aba7b-8792-48df-a755-7f8bb9a2bf60.png)
可以看到：
我用“G”键绑定出发“打开Google”动作，但是“打开GitHub”却不能用“G”键触发了，所以我设置了一个“Y”键然逼迫自己习惯它...

**Comment by cuiliang** [comment]
在动作比较多的时候，如果希望使用键盘，建议使用搜索方式，更快速一些。
如果希望直接触发某个动作，可以试试扩展热键、文本指令这些方式。
