### ISSUE TITLE
希望分享动作的更新说明文本框可以拖大或在代码编辑器中编辑

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1740]
无法拖大，三行就会超出显示范围
![image](https://user-images.githubusercontent.com/48246272/184467701-afd27eaa-f5af-466e-a5ff-f6e86cf2febb.png)

没有在代码编辑器窗口中编辑的选项
![image](https://user-images.githubusercontent.com/48246272/184467584-08d5e8a0-5822-46d7-996e-d43136c67014.png)

**Comment by cuiliang** [comment]
ok

**Comment by cuiliang** [comment]
这个后来加上了。 关闭古老issue中，感谢！
