### ISSUE TITLE
希望分享动作窗口能有任务栏图标

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1741]
该窗口目前是没有任务栏图标的，如果被其他窗口覆盖想找回来只能通过 alt+tab 或 win+tab，需要切换窗口对照内容时略微有些不便

![image](https://user-images.githubusercontent.com/48246272/184467862-439a3863-16c6-470a-900a-49a572a85381.png)

**Comment by cuiliang** [comment]
好
