### ISSUE TITLE
希望可以支持设置图标时调用轮盘和鼠标手势

### ISSUE THREAD

**Issue by gakaks** [cuiliang/QuickPadCn#1742]
目前在quicker设置动作图标时无法呼出轮盘和使用鼠标手势 只有面板可以正常呼出
![Snipaste_2022-08-14_15-52-51](https://user-images.githubusercontent.com/43461224/184527688-cb4d59ae-2103-426c-8d09-2f36556e60eb.jpg)

**Comment by cuiliang** [comment]
目前为了避免一些问题，对于quicker里的窗口都有一个白名单来控制手势和轮盘是否生效。这个窗口虽然是quicker进程，但是是系统窗口，没法给他加白名单。 有点麻烦，等后期看看有没有别的办法

**Comment by cuiliang** [comment]
1.42.0 版本解决了这个问题。

**Comment by gakaks** [comment]
时间过得好快 没想到22年的遗留问题还能得到解决 谢谢大佬

**Comment by cuiliang** [comment]
😂是啊，古人说的太形象了，时间如白驹过隙，仿佛一直在忙，又仿佛啥也没干。。。
