### ISSUE TITLE
希望增加屏幕数量和分辨率等信息的获取功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1743]
quicker的组合动作中目前没有获取屏幕信息的功能，比如多屏幕的时候显示图片，可以指定图片出现的位置和大小，但是不能指定图片出现在哪块屏幕上（现在是会自动在当前激活的屏幕上显示）

另一个问题是，因为不能获取屏幕的信息，所以不知道当前使用的屏幕有多大（比如希望拉伸图片到整个屏幕那么大，形成一个全屏提醒的时候，获取不到屏幕大小，就很尴尬了）

（搜索了一下，在截图的时候反倒是可以指定截图主屏幕和所有屏幕的功能）

所以希望
1. 增加一个动作来获取屏幕信息，返回屏幕的数量，分辨率，坐标范围等信息
2. 在显示图片的动作中，增加显示在哪块屏幕上的功能

**Comment by cuiliang** [comment]
可以试试这些子程序 https://getquicker.net/Share/SubPrograms?tag=&filter=%E5%B1%8F%E5%B9%95%E4%BF%A1%E6%81%AF 
另外也可以在表达式或c#里使用 Screen.AllScreens 得到所有屏幕对象。
参考 https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.screen.allscreens?view=windowsdesktop-6.0

**Comment by ilcpm** [comment]
emmm，这个确实没想到……
可以考虑一下把这个子程序变成内置功能或者增加到文档中吗，这要是不来问根本就想不到能这样用😥

**Comment by cuiliang** [comment]
这个用的比较少，而且数据结构比较复杂，不太好封装，直接在表达式里使用其实更方便一些。
