### ISSUE TITLE
问题摘要：无法连接网络，无法更新与同步

### ISSUE THREAD

**Issue by Daxuans-Growth-Garden** [cuiliang/QuickPadCn#1744]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/99644524/185142071-38c3b435-6bc6-4f89-be05-b01ce58d1bc0.png)
![image](https://user-images.githubusercontent.com/99644524/185142139-abae6a1d-ef53-4a13-ba49-8c6ed4d067c9.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
超过100天没有同步导致本地身份凭据过期了。 
参考这里 https://getquicker.net/QA/Question/1493 
如果有比较重要的动作，可以在动作上右键，信息，导出一下。 然后退出账号重新登录就可以了。
