### ISSUE TITLE
扩展热键功能建议增加任意按键做为触发键的功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1746]
鼠标手势的时候都可以设置接收任意按键做为参数然后用单独的动作去设置输出

但是扩展热键功能就只能一个一个手动的添加和修改，真的烦死人😭

我之前弄了一个输入希腊字母的扩展热键，只能一个个的去设置去复制字母，结果现在因为换了键盘，想修改“修饰键”，只能一个个改，然后也只做了小写希腊字母，大写希腊字母没做……

真的太憋屈了

可以设置成那种“低优先级匹配”的操作，比如某个触发键没有被任何已有规则匹配上，就触发最后的通用动作，像鼠标手势里面的“任意键”一样，把触发键做为参数传递给最后的动作

**Comment by cuiliang** [comment]
理解，等研究下

**Comment by cuiliang** [comment]
终于实现了，将会在下个版本1.42.1里增加。另外这个也可以通过导出后再导入方式修改。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 更新了。
