### ISSUE TITLE
latex无法使用

### ISSUE THREAD

**Issue by zhenzhen824123762** [cuiliang/QuickPadCn#1747]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。
因为没有打开的文档，所以这一命令无效。
   在 Microsoft.Office.Interop.Word._Application.get_ActiveDocument()
   在 Cesar.Office.Interop.FunctionWord.转换当前文档中选中的LaTeX公式() 位置 G:\笔记本\04-Code\CSharp\01-Office\Cesar.Office.Interop\Cesar.Office.Interop\FunctionWord.cs:行号 69
   在 Cesar.Office.Interop.Program.RunMethod(String method, IList`1 param, String app) 位置 G:\笔记本\04-Code\CSharp\01-Office\Cesar.Office.Interop\Cesar.Office.Interop\Program.cs:行号 273
   在 Cesar.Office.Interop.Program.GetOutputFromCommandLineOption(Options opts) 位置 G:\笔记本\04-Code\CSharp\01-Office\Cesar.Office.Interop\Cesar.Office.Interop\Program.cs:行号 123

--------------------------------------------

请在反馈时将上述信息粘贴给我，谢谢！

**Comment by cuiliang** [comment]
1. 完整安装office。 2. 至少打开一个word文档。
