### ISSUE TITLE
请问必须要office吗  wps可以吗

### ISSUE THREAD

**Issue by zhenzhen824123762** [cuiliang/QuickPadCn#1748]
**描述BUG**
对bug的清晰简洁描述。
因为没有打开的文档，所以这一命令无效。
在 Microsoft.Office.Interop.Word._Application.get_ActiveDocument()
在 Cesar.Office.Interop.FunctionWord.转换当前文档中选中的LaTeX公式() 位置 G:\笔记本\04-Code\CSharp\01-Office\Cesar.Office.Interop\Cesar.Office.Interop\FunctionWord.cs:行号 69
在 Cesar.Office.Interop.Program.RunMethod(String method, IList`1 param, String app) 位置 G:\笔记本\04-Code\CSharp\01-Office\Cesar.Office.Interop\Cesar.Office.Interop\Program.cs:行号 273
在 Cesar.Office.Interop.Program.GetOutputFromCommandLineOption(Options opts) 位置 G:\笔记本\04-Code\CSharp\01-Office\Cesar.Office.Interop\Cesar.Office.Interop\Program.cs:行号 123
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

请问必须要office吗  wps可以吗
**附加信息**
请问必须要office吗  wps可以吗
请问必须要office吗  wps可以吗
请问必须要office吗  wps可以吗

**Comment by cuiliang** [comment]
wps有许多兼容性问题，只有个别版本支持接口。
动作都是网友工作学习之余分享的，一般没有精力考虑那么多兼容性问题的。

**Comment by cuiliang** [comment]
另外动作可以自行修改，如果有兴趣可以尝试修改成支持wps的。
