### ISSUE TITLE
切换软件后，无法读取当前软件的特有动作

### ISSUE THREAD

**Issue by CNGaiLiuZi** [cuiliang/QuickPadCn#1749]
**描述BUG**
比如我从浏览器窗口切换到资源管理器窗口，按中键唤出quicker，动作库显示的还是浏览器的动作。

**重现步骤**
1.
2.

**相关截图**
https://github.com/CNGaiLiuZi/-/blob/9f98eeb0c48870d3cfc206eb6da32b94e9e0f3a1/QQ%E6%88%AA%E5%9B%BE20220823105859.png

**环境信息:**
 - 操作系统版本：Windows10企业版LTsC
 - Quicker版本：1.34.22

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
你好，之前版本有一个bug可能会卡主切换。 请升级到最新版试试
https://getquicker.net/Help/Versions
