### ISSUE TITLE
自动运行动作项目残留

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1750]
我曾经给一个通过网络分享安装的动作设置过开机自启，后来我安装了该动作通过本地文件分享的版本，然后删除了网络分享的版本。之后就出现了开机启动 quicker **几分钟后**该动作自启的现象。
我不记得是否、何时删除了此动作的开机自启，但现在自动运行动作里并没有该动作，旧版本数据里也没有。我尝试过开机自启 quicker 后立刻关掉 quicker，几分钟后弹出了该窗口：
![image](https://user-images.githubusercontent.com/48246272/186084284-1a0a6a26-72a6-4def-917c-727a81feefb3.png)
我该如何彻底清除该动作的自动运行设定？我考虑过退出账号，但这似乎会删除很多本地数据
另外，我曾经卸载过 quicker 转为使用 scoop 安装，然后发现 Quicker更新 动作更好用就又换了回来，不清楚是否会产生影响

**Comment by cuiliang** [comment]
检查一下是不是在windows计划任务里创建了任务？

**Comment by ghost** [comment]
> 检查一下是不是在windows计划任务里创建了任务？

的确！删除后就好了
