### ISSUE TITLE
可否鼠标悬停在任务栏区域鼠标滚轮调节音量

### ISSUE THREAD

**Issue by PandaFang** [cuiliang/QuickPadCn#1751]
**需求描述**
可否鼠标悬停在任务栏区域鼠标滚轮调节音量？ 我知道现在底部边缘可以用鼠标滚轮调节音量，且往下看

**描述你想要的解决方案**
现在quicker 非要在底部或顶部边缘， 感觉上一点容错范围都没有，但是手扶在鼠标上推动滚动 不小心多少会偏移几个像素坐标，这样心智负担太大了。 就算不是要适配整个任务栏的高度， 也希望增加容错高度。

**描述您考虑过的替代方案**
可以在github 搜  volume2 这个软件，目前我在用这个，它就是鼠标悬在任务栏上鼠标滚轮调节音量，我希望quicker能改进，这样我可以少装个软件占用内存和托盘

谢谢您为我们带来佳作！

**Comment by cuiliang** [comment]
在高级鼠标触发功能里自己添加规则就可以了。触发位置选任务栏。
https://getquicker.net/kc/manual/doc/adv-mouse-actions

**Comment by PandaFang** [comment]
谢谢 已解决

> 在高级鼠标触发功能里自己添加规则就可以了。触发位置选任务栏。 https://getquicker.net/kc/manual/doc/adv-mouse-actions

截图设置方法，供其他人参考
<img width="648" alt="Snipaste_2022-08-26_15-43-00" src="https://user-images.githubusercontent.com/4337419/186850252-f883ddb2-0497-49d4-9e0a-01f8bc7dfffa.png">
