### ISSUE TITLE
115浏览器或星愿浏览器打开网址会跳到系统默认的edge浏览器

### ISSUE THREAD

**Issue by PandaFang** [cuiliang/QuickPadCn#1752]
**描述BUG**
115浏览器打开网址会跳到系统默认的edge浏览器，我已经设置了使用前台浏览器，在用chrome时 则是正常的直接用chrome打开。
浏览器已经安装扩展，并成功连接。
希望能正确识别我正在使用的浏览器

**重现步骤**
1. 随便新建一个打开网址的动作，或者使用现有的，如果使用的系统默认浏览器则编辑修改为使用前台浏览器
2.在 115浏览器或星愿浏览器中激活quicker 使用打开网址

在使用动作库中别人的组合动作，使用了系统默认浏览器， 我编辑修改成使用前台浏览器，也是这个问题

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
1.
<img width="238" alt="Snipaste_2022-08-26_18-40-06" src="https://user-images.githubusercontent.com/4337419/186887759-7471e81e-dbfe-4d71-b495-884a19a2b260.png">

2.
<img width="399" alt="Snipaste_2022-08-26_18-41-37" src="https://user-images.githubusercontent.com/4337419/186887813-9d48d7db-c0a8-4e5a-b60b-09a687c5126e.png">

3.
<img width="515" alt="Snipaste_2022-08-26_18-43-00" src="https://user-images.githubusercontent.com/4337419/186887840-19ae497b-28bf-406a-9dd0-e8b5abaf377c.png">

**环境信息:**
 - 操作系统版本：Windows 10
 - Quicker版本：1.34.26

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个是根据进程名白名单确定的，这个两个浏览器不在白名单里。 可以把它们的程序名发给我，我加进去试试。
这里没用到浏览器扩展，是直接用程序名命令打开网址的。

**Comment by PandaFang** [comment]
> 这个是根据进程名白名单确定的，这个两个浏览器不在白名单里。 可以把它们的程序名发给我，我加进去试试。 这里没用到浏览器扩展，是直接用程序名命令打开网址的。

115chrome.exe
twinkstar.exe

**Comment by PandaFang** [comment]
感觉这个名单还可以扩一下，除了我上面说的两个，国内应该还有人用opera ， 百分浏览器，还有以前风靡一时的傲游浏览器
![网页捕获_26-8-2022_20741_getquicker net](https://user-images.githubusercontent.com/4337419/186900672-b20d5abd-3b23-47c3-80fa-202582511a0b.jpeg)
