### ISSUE TITLE
浏览器控制-增加『在当前窗口后台打开新标签页，保持活动窗口不变』

### ISSUE THREAD

**Issue by zj1123581321** [cuiliang/QuickPadCn#1754]
**需求描述**
现实的业务场景里，经常是在一个网页上批量打开其他一堆网页进行查询(比如批量打开 Google 前十个搜索结果)。

这种场景下，Chrome 原生可以通过按住 Ctrl 然后再点击链接就能实现该网址在后台打开，先让它加载。

但同样的需求我在 Quicker 上还不知道该怎么实现。

**描述你想要的解决方案**
原生支持『保持活动 tab 不变，在当前窗口的后台打开标签页』

**描述您考虑过的替代方案**
提供一个根据窗口 id、标签页 id 切换活动 Tab 的功能接口。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

![image](https://user-images.githubusercontent.com/33171229/187392211-477ee4a5-6c65-4585-aca7-e92735c03888.png)
![后台批量打开新标签页](https://user-images.githubusercontent.com/33171229/187394405-cfebc3a7-b5df-4063-9bf8-7f30a73ebd13.gif)

**Comment by cuiliang** [comment]
可以参考chrome接口文档：https://developer.chrome.com/docs/extensions/reference/tabs/#method-create
具体就是加上active为false的参数。
![image](https://user-images.githubusercontent.com/1972649/187405529-2ae07512-b73d-4040-84fd-011c835f8b41.png)

**Comment by zj1123581321** [comment]
谢谢崔老师指点：)
