### ISSUE TITLE
不支持 UWP 应用

### ISSUE THREAD

**Issue by seflerZ** [cuiliang/QuickPadCn#1755]
**描述BUG**
不支持 UWP 应用

**重现步骤**
1. OneNote for Windows 10 无法唤出 Quicker 菜单

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win10
 - Quicker版本：1.34.15

**Comment by cuiliang** [comment]
测试没有这个现象。
检查一下有没有设置黑名单什么的。

**Comment by seflerZ** [comment]
搞定了，不小心搞了个全屏禁用，多谢
