### ISSUE TITLE
quicker设置外观里的毛玻璃特效，与win11系统的窗口透明特效冲突！

### ISSUE THREAD

**Issue by jmonz** [cuiliang/QuickPadCn#1756]
quicker设置外观里的毛玻璃特效，与win11系统的窗口透明特效冲突！
升级win11后 一直有拖动窗口卡顿的问题，查找了很多办法无果！
今天居然发现是和毛玻璃特效冲突！
望能解决！

**Comment by cuiliang** [comment]
目前没有什么办法，只能等win11修复bug。
你用的win11多少版？
