### ISSUE TITLE
能否增加一个让动作页隐藏起来不在任何程序上出现的功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1759]
比如很多动作一定只会使用快捷键来触发，或者只会在Ctrl C的菜单中触发
我就希望把这些动作单独做一个动作页然后隐藏起来不在任何程序中出现该动作页
这样动作页中只显示会使用到的有用动作，来避免干扰

（顺便想问问quicker是不是不能做到把任意程序像QQ一样贴边隐藏起来的功能，Windows应该没有这样的API吧）

**Comment by cuiliang** [comment]
可以创建自定义应用场景 
![image](https://user-images.githubusercontent.com/1972649/188783814-e2cc9eb3-aaac-474a-8df6-3ad77bd6c3c0.png)


贴边可以参考网友分享的动作 
https://getquicker.net/Sharedaction?code=220cf915-8c6b-44f5-a311-08d8c0cb1b0a
