### ISSUE TITLE
单击ctrl弹出面板功能失效

### ISSUE THREAD

**Issue by Lyn6969** [cuiliang/QuickPadCn#1760]
**描述BUG**
最新的测试版，设置了单击ctrl弹出面板功能失效，按下Ctrl键无法唤出面板

**重现步骤**
1. 单击Ctrl,无反应
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win11 22H2 22622.590
 - Quicker版本：1.34.32

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈，我研究一下。

**Comment by Lyn6969** [comment]
> 感谢反馈，我研究一下。

好的，辛苦了！

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.34.33 已修复
