### ISSUE TITLE
启动quicker后，鼠标拖动窗口，会出现漂移或延迟

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1761]
**描述BUG**
启动quicker后，鼠标拖动窗口，会出现漂移或延迟

**重现步骤**
1.启动quicker
2.鼠标拖动窗口

**环境信息:**
 - 操作系统版本：win11 21H2 22000.918
 - Quicker版本：普通通道和快速通道的最新版都试了，都存在此问题

**附加信息**
启动quicker后，即使暂停quicker，也会有此问题。只有完全退出quicker，问题才会消失，希望尽快修复！

**Comment by cuiliang** [comment]
外观设置里关闭背景模糊选项 
![image](https://user-images.githubusercontent.com/1972649/189012022-d3a6a440-7dc8-4a36-87c8-6414a9595874.png)

**Comment by DogeFlow** [comment]
> 外观设置里关闭背景模糊选项 ![image](https://user-images.githubusercontent.com/1972649/189012022-d3a6a440-7dc8-4a36-87c8-6414a9595874.png)

感谢，已经修复
