### ISSUE TITLE
我的软件同步功能不能使用，同步异常

### ISSUE THREAD

**Issue by wasdwang** [cuiliang/QuickPadCn#1762]
**描述BUG**
点击软件数据同步后显示同步异常
20220911 22:44:29 失败
更新 1 项数据到服务器。
  CommonData:user_settings  (常规数据)
同步异常：发生一个或多个错误。错误：您的电脑时间不正确，无法同步！请同步您的电脑时间。当前时间差(s)：234.0066383 最大允许差值(s)：180

**重现步骤**
1.
2.

**相关截图**
![image](https://user-images.githubusercontent.com/113275665/189565218-3d406d60-1dea-4069-9579-14a6af9d6670.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.34.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
电脑时间不准，百度下如何校准windows时间哦。
或者参考这里 https://getquicker.net/KC/Kb/Article/331
