### ISSUE TITLE
建议增加 设置键盘按键弹出轮盘

### ISSUE THREAD

**Issue by WYaoLing** [cuiliang/QuickPadCn#1763]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
https://getquicker.net/Sharedaction?code=7efc668c-a749-4a8c-fc16-08d978b0ec35 
使用这个动作，然后设置个快捷键或用扩展热键之类的方式触发。

**Comment by WYaoLing** [comment]
> https://getquicker.net/Sharedaction?code=7efc668c-a749-4a8c-fc16-08d978b0ec35 使用这个动作，然后设置个快捷键或用扩展热键之类的方式触发。

感谢！
