### ISSUE TITLE
原神无法加入quicker快捷键启动黑名单

### ISSUE THREAD

**Issue by ADarkDream** [cuiliang/QuickPadCn#1765]
**描述BUG**
将原神加入quicker的Ctrl键快捷启动黑名单之后，窗口化运行原神，在原神界面按Ctrl依旧会打开quicker面板

**重现步骤**
1.将原神加入quicker的Ctrl键快捷启动黑名单
2.将原神调整为窗口化启动
3.点击Ctrl键，quicker面板依旧弹出

**相关截图**
<img width="962" alt="20220918002822299" src="https://user-images.githubusercontent.com/98243293/190866934-2e55108c-26b1-428e-81dd-e13d155d3125.png">

**环境信息:**
 - 操作系统版本：Microsoft Windows11家庭中文版10.0.22000版本22000
 - Quicker版本：版本1.34.15

**附加信息**
暂无

**Comment by cuiliang** [comment]
黑名单仅用于鼠标触发。 建议这时候禁用Quicker。设置一个快捷键，或双击托盘图标
