### ISSUE TITLE
能不能给一个动作分配多个可以触发的快捷键

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1766]
如题，我有个独立的小键盘，通过自定义快捷键比如F13到F24，再对他们分配不同的动作来实现在不同的功能
但是在不使用它的时候，我希望使用另一种快捷键触发同一个动作，比如ctrl + XX
也就是说两种不同的情境下希望有两种不同的快捷键触发同一个动作

**Comment by cuiliang** [comment]
设置 - 动作快捷键，可以在这里添加规则。

**Comment by ilcpm** [comment]
好主意！
