### ISSUE TITLE
quicker启动时部分热键无法使用

### ISSUE THREAD

**Issue by guilin007** [cuiliang/QuickPadCn#1767]
**描述BUG**
quicker启动时部分热键无法使用
1在同时使用quicklook时无法通过空格键进行预览
2在游戏dnf中鼠标右键失灵

**重现步骤**
1.在同时使用quicklook时无法使用空格键
2.在游戏dnf中鼠标左键失灵

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.34.15

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by guilin007** [comment]
quicker退出后按键功能正常

**Comment by cuiliang** [comment]
空格预览失效：检查是不是在扩展热键里使用了空格作为引导键，删除这条规则；
游戏中左键还是右键失效？尝试增加黑名单，如果还不行就只能先禁用quicker了。
