### ISSUE TITLE
开启百度网盘后换出面板会出现卡顿的问题

### ISSUE THREAD

**Issue by 3020574863** [cuiliang/QuickPadCn#1768]
录视频了,看看吧
https://user-images.githubusercontent.com/76427713/190949727-e44d3ab1-e4d5-4f16-b2ea-65eeef7ecfb0.mp4

**Comment by cuiliang** [comment]
意思是面板窗口不会自动隐藏么？
有点看不太出来，还请详细解释一下操作过程和具体表现。 另外那个动作也请分享一下我这里好测试看看。

**Comment by 3020574863** [comment]
可以远程吗,直接远程试一试,加个qq3020574863

**Comment by cuiliang** [comment]
近期在外出差做项目。 可以加qq 197906, 等有空的时候向日葵远程一下。

**Comment by cuiliang** [comment]
百度网盘问题
![_FTUHI7QDKXOK@FM34TO8(5](https://user-images.githubusercontent.com/1972649/191504579-0eaa3a16-9ee5-4c98-b4dd-ef74714cf30b.png)
