### ISSUE TITLE
经常出现打不开软件的问题，如下图

### ISSUE THREAD

**Issue by DogeFlow** [cuiliang/QuickPadCn#1769]
如题
![image](https://user-images.githubusercontent.com/34650487/191480679-97513a0a-93eb-4947-8621-7208e52ee946.png)

**环境信息:**
 - 操作系统版本：win11 21H2
 - Quicker版本：1.34.30

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
动作里怎么定义的？

**Comment by DogeFlow** [comment]
好几个软件都是一样的，就是直接打开软件




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月21日 19:09 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [cuiliang/Quicker] 经常出现打不开软件的问题，如下图 (Issue #1769) |

动作里怎么定义的？

**Comment by DogeFlow** [comment]
![image](https://user-images.githubusercontent.com/34650487/191502857-dedb5632-e927-4f44-9c94-88843635ca6e.png)

**Comment by cuiliang** [comment]
这里测试没问题。
1) 升级一下quicker到最新版。
2) 确认一下程序在本地已经被安装，可以从开始菜单启动。
3) 如果电脑做过什么优化，撤销一下优化。如果关闭过一些系统服务，恢复启动这些服务。

![image](https://user-images.githubusercontent.com/1972649/191504087-26206ea6-4392-4a86-b00f-1845c2adcb16.png)

**Comment by DogeFlow** [comment]
> 这里测试没问题。
> 
> 1. 升级一下quicker到最新版。
> 2. 确认一下程序在本地已经被安装，可以从开始菜单启动。
> 3. 如果电脑做过什么优化，撤销一下优化。如果关闭过一些系统服务，恢复启动这些服务。
> 
> ![image](https://user-images.githubusercontent.com/1972649/191504087-26206ea6-4392-4a86-b00f-1845c2adcb16.png)

您好，出现问题的软件都是从Microsoft Store中安装的，“路径/命令”就是直接选择的。出现问题时，重启quicker可以恢复。不太确定是什么问题引起的。

**Comment by cuiliang** [comment]
@DogeFlow 方便的话观察一下通常什么操作之后会出现这个现象，看看有没有什么规律。

**Comment by naier007** [comment]
![image](https://user-images.githubusercontent.com/34355229/194437666-1801edcf-19f6-49cf-89d7-f975724f5135.png)
请问一下左键辅助-常用功能(快捷操作)-禁用quicker,  这里是否可以修改为暂停/恢复,或者新增一个这个选项?

**Comment by cuiliang** [comment]
@naier007 暂停之后没有鼠标和键盘消息了，没法触发。
