### ISSUE TITLE
连接不上推送服务

### ISSUE THREAD

**Issue by eamooooon** [cuiliang/QuickPadCn#1770]
连接不上推送服务
今天突然发现连接不上推送服务
没有进行任何操作 就是一直连不上
后来重启了一次 显示连接成功了 
结果后面发现并没有成功推送 再看发现又要重连
![tmp3906](https://user-images.githubusercontent.com/51506762/191885217-191ef12a-97bc-453b-9172-d47ba966c026.png)

**Comment by cuiliang** [comment]
可能网络有点问题，现在好了么？我这里目前是正常的。 
如果是公司的网络，可以问下网关有没有屏蔽网址和端口。

**Comment by eamooooon** [comment]
> 可能网络有点问题，现在好了么？我这里目前是正常的。 如果是公司的网络，可以问下网关有没有屏蔽网址和端口。

后面重启了一下电脑就好了

**Comment by cuiliang** [comment]
好的
