### ISSUE TITLE
无法自启动

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1772]
**描述BUG**
升级了最新版windows11系统，Quicker无法自启动了，每次开机后都要手动启动一下，就算在设置里面设置了随系统启动，也不行，请问这个要怎样解决？

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows11 22H2 22621.521
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
一般是管家拦截了自启。
如果安装了管家类软件，包括联想管家，先卸载它们，再试试自启能不能生效。

**Comment by Beurling** [comment]
建议重新安装
