### ISSUE TITLE
[BUG] 高级鼠标触发与滚轮相关动作全部失效

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#1773]
# 描述BUG

在高级鼠标触发这个动作里，所有**鼠标动作**设为“向前滚动（远离用户）”、“向后滚动（朝向用户）”的规则，全部都无法触发。

在今天前它们都是正常的，今天开机后突然就这样了，将 Quicker 重启后它又好了。

# 重现步骤

未知，现在已经好了，试半天也没再出现。

# 相关截图

以下是部分出问题的规则：

![](https://s3.bmp.ovh/imgs/2022/09/27/5ea57fa1bebcc1e9.png)

![](https://s3.bmp.ovh/imgs/2022/09/27/c03d5436c3d0258a.png)

# 环境信息

- 操作系统版本：Windows 11 22000.1042；
- Quicker版本：1.34.15

**Comment by cuiliang** [comment]
是操作没有成功触发，还是模拟的滚动没有生效？ 可以在触发后提示里加个消息看看有没有消息显示。
不能触发可能是某个按键状态不正确。可以在工具菜单中打开按键状态窗口查看。
![image](https://user-images.githubusercontent.com/1972649/192523670-310ed7d9-c046-4a9c-85e5-f5c79c9bdb8f.png)

**Comment by Immortal-Sty** [comment]
@cuiliang 

我一开始就试了，没有消息提示，是没有触发。

按键状态不清楚，重启 Quicker 后就没问题了，现在也看不了了。但大概率是没问题的，原因如下：

- 所有按键单独使用都是正常的；
- 在没有 Quicker 拦截按键后，软件本身与按键对应的功能开始正常运行，如果按键状态不正确，这两个就都不应该出现才对。

**Comment by cuiliang** [comment]
个别情况下会有识别不到按键抬起的情况，造成quicker中识别的按键状态是按下，实际按键已经抬起的的状态。这时候就触发不了了。托盘菜单里可以重新加载一下挂钩或重置一下键盘状态。
