### ISSUE TITLE
能不能出一个按键直接触发动作，不必调出快捷面板

### ISSUE THREAD

**Issue by iKing255** [cuiliang/QuickPadCn#1774]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
触发方式很多，请参考使用文档，或打开设置窗口探索一下。
如果用快捷键，可以在动作右键，信息，设置快捷键。
