### ISSUE TITLE
选中很长的文本，弹出上下文菜单会使quicker卡死

### ISSUE THREAD

**Issue by zw-95** [cuiliang/QuickPadCn#1775]
**描述BUG**
选中很长的文本，试图弹出上下文菜单，但quicker卡死，只能用任务管理器关闭、重启。

**重现步骤**
1.选中某图片的base64文本（长度67995，测试其他文本相似长度也会复现）
2.长按Ctrl+C试图弹出上下文菜单
3.quciker卡死，cpu 10%占用不变（正常情况不到1%）

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/35022819/192473339-1b119811-b680-4698-a428-7858bdb3eacc.png)
![image](https://user-images.githubusercontent.com/35022819/192473771-95f27f67-de33-47fa-b9b9-4c7cbeada74d.png)

**环境信息:**
 - 操作系统版本：Windows 10 专业版 21H2 19044.1586
 - Quicker版本：1.34.15

**Comment by cuiliang** [comment]
这里测试正常，大概1M多的文件。
有没有使用剪贴板类动作或软件？可以尝试先关闭这样的动作和软件看看会不会复现。
