### ISSUE TITLE
你好，无法重置手机号。

### ISSUE THREAD

**Issue by 94Angrysumai** [cuiliang/QuickPadCn#1776]
你好，由于手机号更换，需要更改手机验证。

希望可以后台重置我的账户手机号。
账户昵称：小黄鸭吃土豆

![Quicker_20220927_200520](https://user-images.githubusercontent.com/114489392/192520698-c1ac08e6-6b62-4d43-8cfb-a69f1554095c.png)

**Comment by cuiliang** [comment]
重置了，现在可以重新绑定。
