### ISSUE TITLE
[需求] 希望 `[icon:文件路径]` 的语法能在“用户选择”模块里使用。

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#1777]
# 需求描述

在某些动作里，我需要使用“用户选择”模块来让用户选择安装在电脑的软件。我想给它加上软件对应的图标。

# 描述你想要的解决方案

我在语雀的文档里看到了 `[icon:文件路径]` 的语法，希望在“用户选择”模块里能支持这种语法，这样我就能用 `[icon:软件路径]软件进程名` 来让用户更直观的选择他们安装的软件了。

# 其他上下文

我看到的语雀文档在[这里](https://www.yuque.com/quicker/help/use-icon-in-actions#:~:text=%E4%BD%BF%E7%94%A8Windows%E7%B3%BB%E7%BB%9F,dll%2C%2D3017%5D)。

**Comment by cuiliang** [comment]
是支持的。

**Comment by Immortal-Sty** [comment]
@cuiliang 

不支持啊？

![](https://s3.bmp.ovh/imgs/2022/09/28/c60f0fc6197cc5ca.png)

**Comment by cuiliang** [comment]
[icon:xxx]标题|value， 少value部分。
