### ISSUE TITLE
窗口界面控制（FlaUI）似乎无法获取对应控件的状态信息

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1778]
比如我这个CheckBox控件，图上框选的所有信息都无法获知其到底有没有被选中，但是设置它的状态的时候，即可以选中和取消选中，也可以改变选中状态，看起来是可以知道它的状态的

我想做一个二元状态切换的动作，因此想自动切换完成之后输出当前的切换状态，但是发现无法获取到控件的状态
![image](https://user-images.githubusercontent.com/36830343/192762042-bb5b8275-dce4-4a54-84ff-b4a14a2e2813.png)

**Comment by cuiliang** [comment]
试一下文件属性对话框，我这里测试正常，返回的“值”是“Off”和“On”。
![image](https://user-images.githubusercontent.com/1972649/192795088-026f8d55-45ad-45cb-beb9-0e741992a1b9.png)

可能的原因：
1）被控制软件对UIAutomation支持的不好
2）控件on、off的时候，对应的xpath不同

**Comment by ilcpm** [comment]
看起来是的……那就只能这样了
