### ISSUE TITLE
图标如果能支持GIF动图就更完美了

### ISSUE THREAD

**Issue by Beurling** [cuiliang/QuickPadCn#1779]
**需求描述**
动作图标支持GIF，动图对于动作选择更加直观

**描述你想要的解决方案**
如果可以把GIF图片直接拖动到图标位置生效就更加方便了

类似此类动图

![icons8-notification](https://user-images.githubusercontent.com/48503044/193009484-e5e9582a-32bc-4c3e-b2ab-2c5d59dea894.gif)

**Comment by cuiliang** [comment]
一个gif相当于很多张图片，比较有点耗费性能和资源，暂时不考虑了。
