### ISSUE TITLE
安装了360文件夹后，在文件夹里面的全局手势操作失效。

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#1780]
**描述BUG**
安装了360文件夹，是文件夹的多标签工具，之后再打开文件夹就不能用手势操作后退或者前进到某一文件夹了。

**环境信息:**
 - 操作系统版本：windows11 家庭中文版 22H2
 - Quicker版本：1.35.17

**Comment by cuiliang** [comment]
是手势无法触发，还是触发之后不能生效？ 方便的话请录个屏看一下
