### ISSUE TITLE
企业微信的窗口置顶总是失败

### ISSUE THREAD

**Issue by bobbyt510** [cuiliang/QuickPadCn#1781]
**描述BUG**
对window窗口进行相关操作
类型为：切换置顶状态
同样操作命令，
对于记事本，资源管理器，微信窗口等都可以进行置顶及取消置顶的操作
但对于**企业微信**的窗口，就会出现有时候成功置顶，有时候不能置顶的现象
并且经常出现在将企业微信的窗口置顶成功后，切换过其他活动窗口后，企业微信的
窗口的置顶状态就会消失
但其他程序的置顶在切换窗口后是仍然存在的

**重现步骤**
1.将企业微信的窗口进行置顶操作
2.切换几次其他窗口，比如资源管理器
3.再次检查企业微信的窗口的置顶状态

**相关截图**
这是窗口操作置顶的设置
![image](https://user-images.githubusercontent.com/115074217/194030325-6d204312-47e4-4719-b1bb-49815a455db3.png)

**环境信息:**
 - 操作系统版本： 
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22000 暂缺 Build 22000
 - Quicker版本：1.34.26 

**附加信息**
感谢作者开发如此便利的软件
请大大帮忙看看是什么原因造成的，因为企业微信使用非常频繁，置顶操作也是使用非常频繁，不能正常使用非常痛苦。

**Comment by cuiliang** [comment]
试了powertoys和strokeplus，置顶这个窗口都不成功。可能它自己内部控制了置顶状态了。

**Comment by bobbyt510** [comment]
感谢大大的回复

希望后面的版本可以像windowtop一样能够置顶窗口，这样就更便利了，谢谢

Best  Regards

**Comment by cuiliang** [comment]
@bobbyt510 windowtop 我这里测试也没法置顶，你那里可以么？

**Comment by bobbyt510** [comment]
我这里使用是正常的

请查看附件视频演示








Microsoft Windows [版本 10.0.22000.1042]


OS 名称:          Microsoft Windows 11 专业版



OS 版本:          10.0.22000 暂缺 Build 22000


OS 制造商:        Microsoft Corporation


OS 配置:          独立工作站


OS 构建类型:      Multiprocessor Free


初始安装日期:     2021/9/5, 8:58:45



系统启动时间:     2022/10/5, 18:37:55


系统制造商:       LENOVO


系统型号:         20QRS00100


系统类型:         x64-based PC


处理器:           安装了 1 个处理器。


                  [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz


Message ID: ***@***.***>


BIOS 版本:        LENOVO N2NET51W (1.36 ), 2022/2/18
