### ISSUE TITLE
常用功能(快速操作)需求建议

### ISSUE THREAD

**Issue by naier007** [cuiliang/QuickPadCn#1782]
**需求描述**
请问一下左键辅助-常用功能(快捷操作)-禁用quicker, 这里是否可以修改为暂停/恢复,或者新增一个这个选项?
 **其他上下文**
![image](https://user-images.githubusercontent.com/34355229/194437905-eeff533b-fb53-4df7-bb88-0121c8e13c3b.png)

**Comment by cuiliang** [comment]
暂停之后鼠标和键盘事件不再触发了。没办法的。

**Comment by naier007** [comment]
![image](https://user-images.githubusercontent.com/34355229/194439280-679bafcc-24b1-4153-b891-dd704a6dde56.png)
在功能快捷键不是可以实现这个功能?

**Comment by cuiliang** [comment]
快捷键是走的系统功能，不需要挂钩的。 停止之后挂钩就停止工作了，依赖 挂钩的触发方式都会失效。

**Comment by naier007** [comment]
好的 感谢!
