### ISSUE TITLE
安装360安全卫士并开启其驱动防护后大概率出现右键点击失败

### ISSUE THREAD

**Issue by TsYa69** [cuiliang/QuickPadCn#1783]
**描述BUG**
安装360安全卫士并开启其驱动防护后，大概率出现右键点击失败，但偶尔能够点击右键弹出菜单。quicker已经加入信任名单。只有关闭360驱动防护才能正常使用。360显示的阻止原因是模拟按键自动阻止，但是之前也没有出现这种情况。

**重现步骤**
1.安装360安全卫士并开启其驱动防护
2.点击右键

**相关截图**
![屏幕截图 2022-10-08 005315](https://user-images.githubusercontent.com/77046424/194611085-cd9708d0-9e4c-4a0f-bf33-ca3e337e21b3.png)
![屏幕截图 2022-10-08 005331](https://user-images.githubusercontent.com/77046424/194611189-2099395a-5291-4142-bb44-ad9f63db6176.png)

**环境信息:**
 - 操作系统版本：Windows 10 家庭中文版 21H2
 - Quicker版本：1.35.37

**附加信息**

**Comment by cuiliang** [comment]
对，360有bug，添加信任仍然会拦截模拟按键，必须关闭驱动防护才可以。 请向360报告

**Comment by TsYa69** [comment]
> 对，360 有 bug，添加信任仍然会拦截模拟按键，必须关闭驱动防护才可以。 请向 360 报告

好的，原来是360更新导致的问题，谢谢。

**Comment by cuiliang** [comment]
@TsYa69 Quicker更新也会导致360的内部规则混乱，比如前一个版本正常，更新qk后360就拦截，虽然加过白名单。这里quicker没有什么能做的。
