### ISSUE TITLE
如果有可能，动作图标可以根据不同状态进行改变

### ISSUE THREAD

**Issue by pzcn** [cuiliang/QuickPadCn#1785]
**需求描述**
比如读取某个状态，开启时为一个图标，关闭时为一个图标

**描述你想要的解决方案**
编辑动作时，根据某个变量指定不同图标，比如变量1时为开启的图标，0是关闭的图标，甚至可以指定更多状态，然后设置一个默认图标进行兜底。个人设想是每次打开面板的时候进行刷新，但是不知道这个时机是否合适，以及是否对性能产生一定的影响。

**Comment by cuiliang** [comment]
感觉会影响可识别性，所以目前使用徽标图标或徽标文字来做这种标记的。
