### ISSUE TITLE
提示的显示时间不可调

### ISSUE THREAD

**Issue by GLWB** [cuiliang/QuickPadCn#1787]
经常用复制粘贴功能，很智能，喜欢用，提示是必须的，有的地方想复制，但是会成为粘贴（不是Quicker的错，很早以前就遇到过这样的失灵了，键盘直接输入Ctrl+C都不顶用），提示是防止出错用的。

但是这个提示有3秒左右，太长了，挡住屏幕那里的一块，没法马上复制。

**Comment by cuiliang** [comment]
这里考虑换一种提示方式。
