### ISSUE TITLE
quicker文件夹选择对话框一直置顶，类似永久置顶，点击其他窗口，它一直在最上面

### ISSUE THREAD

**Issue by rwvse** [cuiliang/QuickPadCn#1788]
quicker文件夹选择对话框一直置顶，类似永久置顶，点击其他窗口，它一直在最上面
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
使得quicker内置对话框，不限于文件夹选择对话框，增加代码实现非永久置顶，可以被其他窗口覆盖

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
什么功能触发的对话框？如果是动作，请截图一下步骤看看哦。

因为quicker的面板窗口是置顶的，所以这类在它基础上的对话框也会置顶显示。 
不过这类窗口应该只是临时显示，然后就关掉了吧？
