### ISSUE TITLE
望手机app与电脑连接之后可以传输文本以及小文件

### ISSUE THREAD

**Issue by shawnyuan-cn** [cuiliang/QuickPadCn#1793]
现阶段APP与电脑端连接之后可以进行图片传输，但找不到文本以及文件传输的途径，而现阶段动作库中一些动作也大多采用QQ或微信传输的方式来实现问题，希望软件本身可以支持这些功能

**Comment by cuiliang** [comment]
直接用QQ和微信比较方便一点，移动端目前弃坑了。
