### ISSUE TITLE
无法删除只在子程序中使用的变量

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1794]
**描述BUG**
![image](https://user-images.githubusercontent.com/48246272/197152080-83cb0f73-bc14-416a-9089-db9a640b9ca6.png)
该变量只在此动作内子程序中使用，选项中也并没有调用，但却无法删除

**重现步骤**
1.安装动作 https://getquicker.net/Sharedaction?code=8dfe1e68-33f0-4329-14ae-08da4a84097c
2.尝试删除此变量

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.36.0

**Comment by cuiliang** [comment]
在截图这个编辑步骤的界面，点“保存”按钮应该就可以了。 保存的时候会检查，去掉不使用的参数传递。

**Comment by ghost** [comment]
> 在截图这个编辑步骤的界面，点“保存”按钮应该就可以了。 保存的时候会检查，去掉不使用的参数传递。

的确如此，点击保存后就可以删除了
