### ISSUE TITLE
能否对套娃传变量的操作进行优化

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1795]
**需求描述**
我今天子程序套子程序，把十几个变量从主程序往下传了三层，还整了两次，人快点傻了，能不能对此进行一些优化？

**描述你想要的解决方案**
- 可以直接指定变量传入的层
- 将子程序粘贴至子程序内时可以将带入的变量设置为与子程序内同样的输入输出状态
- 可以批量将变量设为输入或输出参数
- 可以使用输入输出参数对动作进行排序，并在复制到子程序内时保留该顺序
- - 顺便能加个按状态变量的优先排序吗？

**描述您考虑过的替代方案**
不用子程序……这太浪费了

**Comment by cuiliang** [comment]
这个，是不是搞得太复杂了？😂 
一般封装好以后，不应该传递太多数据到子程序的。
如果太复杂了，可以考虑用脚本或直接写个程序了，应该会简单一些。

**Comment by ghost** [comment]
> 这个，是不是搞得太复杂了？😂 一般封装好以后，不应该传递太多数据到子程序的。 如果太复杂了，可以考虑用脚本或直接写个程序了，应该会简单一些。

一次次更新下来，就变成这样了
本来只有一层子程序，后来要往里加些新功能，正好也是通用代码，就往里继续塞子程序了，要是不用子程序动作体积恐怕要大上一圈
我主要是把重复调用的代码给封装成子程序，有时候他们也要调用一些重复代码。想了想这好像是写双链笔记的思路 ![捂脸](https://user-images.githubusercontent.com/48246272/197310001-b4a71865-73be-4e40-9ec5-90457505c4c7.jpg)

用脚本或直接写程序这种，我也想过，但我不会。![自闭](https://user-images.githubusercontent.com/48246272/197310128-cb7d37d4-a43f-4a10-be02-510fac198a69.jpg) 我没有学过计算机语言，离了 quicker 编程能力肯定大幅下降，虽然也有计划学，但目前优先级不高。很感谢 quicker 这种可视化代码编辑器，降低了编程的门槛，只要有逻辑能力就能写代码

**Comment by cuiliang** [comment]
归档
