### ISSUE TITLE
为动作自定义右键菜单设置快捷键

### ISSUE THREAD

**Issue by zigazigahaha** [cuiliang/QuickPadCn#1797]
**需求描述**
为动作自定义右键菜单设置快捷键

**描述你想要的解决方案**
--------------------------
示例
--------------------------
右键菜单定义：
--------------------------
导出(&E)|export
设置(&S)|settings
--------------------------
在动作上点右键后，键盘按E，执行导出；按S，执行设置。免去移动鼠标点击菜单项的步骤，用起来更便捷。

![image](https://user-images.githubusercontent.com/116444197/197346288-751bb3ad-d717-4c05-a2b1-364ed896f25c.png)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
快捷键设置里，动作参数设置成和右键菜单一样的参数值就可以了。本质都是给动作传递参数。
![image](https://user-images.githubusercontent.com/1972649/197345202-00cc0ebf-5094-47ec-b1af-7fe401583f64.png)

**Comment by zigazigahaha** [comment]
此和我的描述功能完全不是一回事。
假设用下图方法，我在记事本程序中设置了快捷键s来实现某个功能。那么，我在记事本中就无法输入字符s了。
而如我所描述的实现，是在动作按钮上点右键后，键盘输入s，执行动作，完全不影响s键原来的输入字符s的功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 为动作自定义右键菜单设置快捷键 (Issue #1797)





 
快捷键设置里，动作参数设置成和右键菜单一样的参数值就可以了。本质都是给动作传递参数。

**Comment by cuiliang** [comment]
眼花看错了。
实现不了这样的功能，目前动作和菜单是不占用焦点的，不能通过按键触发菜单。
如果每次都需要选择，可以在动作开始的时候加一个“用户选择”步骤，或者“显示菜单”步骤（启用焦点选项）。菜单标题中使用`_字母`的方式设定。

**Comment by zigazigahaha** [comment]
无法实现吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 为动作自定义右键菜单设置快捷键 (Issue #1797)





 
眼花看错了。
 实现不了这样的功能，目前动作和菜单是不占用焦点的，不能通过按键触发菜单。
 如果每次都需要选择，可以在动作开始的时候加一个“用户选择”步骤，或者“显示菜单”步骤（启用焦点选项）。菜单标题中使用_字母的方式设定。
