### ISSUE TITLE
动作无法调用lisyary

### ISSUE THREAD

**Issue by toxicbug** [cuiliang/QuickPadCn#1798]
**描述BUG**
对bug的清晰简洁描述。
![image](https://user-images.githubusercontent.com/22049724/197443385-9ee8b8b5-a095-4e6f-abcd-52ebcd3ebc04.png)
非常简单的动作，通过调用listary，搜索文件名，并打开。
我常用软件都是这么启动的，而且一直以来也都是这么使用的，正常且好用。
最近更新后无法调用listary（也就是说点击动作，无法唤醒listary）。
重启quicker后，又能正常使用这些动作，一次或几次正常使用后（没有具体统计次数，又无法唤醒listary，再重启又可以。。。）
以下为录屏：(2.3M 百度盘)
------------------------------------
链接: https://pan.baidu.com/s/16F1_Y7tfNOmy7hLW-WDrZg?pwd=cs29 提取码: cs29 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v6的分享
------------------------------------
**环境信息:**
 - 操作系统版本：win11 22h2
 - Quicker版本：1.35.42

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by toxicbug** [comment]
谢谢！

**Comment by cuiliang** [comment]
动作里模拟的什么按键唤醒listary？

**Comment by toxicbug** [comment]
两个ctrl，谢谢

**Comment by cuiliang** [comment]
截图里只看到一个步骤。 分两个步骤模拟ctrl，然后中间加一点延迟时间，如100ms，再试下看看。如果lis里可以设置其他快捷键，也可以试试换一个普通的组合快捷键来触发。

**Comment by toxicbug** [comment]
![image](https://user-images.githubusercontent.com/22049724/197907778-e3b55876-4f9b-4b31-acd7-fd9e794ae3d7.png)
![image](https://user-images.githubusercontent.com/22049724/197907809-0a798eea-9e59-4d9b-8037-1ed2b792c0af.png)
重复了两次，这些动作用了很久，一直都正常，应该就是这一两次升级后出现的问题，我尝试一下将50ms修改为100ms试试吧，因为软件名都带了后缀，基本上是唯一，为了达到快速启动，经过几次修改最终确定为50，低于50如果有概率出现找不准（应该是lisyary搜索需要时间的问题）

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/197941251-9ceea20f-3734-4c5b-93a4-65fa3e22810a.png)
试了一下这样可以

**Comment by cuiliang** [comment]
在一个步骤里循环两次有一个bug，已修改，待下个版本更新。

**Comment by cuiliang** [comment]
后续版本已修复。
