### ISSUE TITLE
”场景与动作管理“里面添加分组

### ISSUE THREAD

**Issue by GH184683673** [cuiliang/QuickPadCn#1799]
**需求描述**
我有一些软件需要共用一些动作页，该动作页需要挨个添加到这些软件中，当有软件和动作页改动时操作极度麻烦（手动挨个处理）。

**描述你想要的解决方案**
我想设置一个分组，当该分组里面的软件被删除，或者动作页被删除时能自动做出调整

**描述您考虑过的替代方案**
无

 **其他上下文**
无

**Comment by cuiliang** [comment]
添加到“通用”场景中，然后在程序的场景附加这些动作页。
![image](https://user-images.githubusercontent.com/1972649/197693789-0447cb20-3b0d-4c35-ba39-c00717328923.png)

**Comment by GH184683673** [comment]
![image](https://user-images.githubusercontent.com/32435882/197695179-fc33aa10-23fc-4eba-bb46-fbfac06d0d69.png)

**Comment by GH184683673** [comment]
如果我下次有新动作页想添加时，又要挨个设置一次 @cuiliang

**Comment by cuiliang** [comment]
这里的“分组”具体是什么样的功能？有点不是很明白

**Comment by GH184683673** [comment]
动作太多一个动作页放不下，这就形成了一组动作页。我用虚拟软件模拟分组每次页面增加或者删除都要将这些软件全部操作一次才可以。

**Comment by cuiliang** [comment]
当前的设计无法方便实现此功能。后期重新设计时考虑。
目前除了附加动作页，也可以考虑使用快捷键触发一个动作，在这个动作中加载特定的动作页。
