### ISSUE TITLE
封闭并逐渐淘汰基本组合动作

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#180]
禁止新建基本组合动作；
共享库中的基本类型逐渐修改为高级组合动作；

**Comment by i5151** [comment]
告诉你一个好消息，SuMo今天开始已经能提醒Quicker的升级了。

**Comment by cuiliang** [comment]
@i5151 哈哈，666，现在在做离线，有点难，这次更新时间会比较长

**Comment by i5151** [comment]
没关系，也不一定每周都要更新，你不烦，我们还烦呢😂

SuMo能提醒，说明Quicker已经有一定的知名度了，已经引起SuMo的注意。这个公司软件挺专业，就是界面太差，有Quicker界面的20%的美观方便就好了。

**Comment by i5151** [comment]
淘汰基本动作，不让用户自己建基本动作了？这个没必要吧，人家想建什么就建什么呗，你只要限制分享就行了。

**Comment by cuiliang** [comment]
@i5151  基本组合动作，不是其他的那些基本动作。 里面功能在高级组合动作里都可以实现，而且编辑器更容易使用一些。 所以我感觉基本组合动作似乎没有太大必要了，也容易让用户产生疑惑。

**Comment by i5151** [comment]
那明白了，完全应该淘汰。
