### ISSUE TITLE
quicker重启后多个悬浮按钮布局保持上次设置 

### ISSUE THREAD

**Issue by ninalibeite** [cuiliang/QuickPadCn#1800]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
可以试下这个选项：
![image](https://user-images.githubusercontent.com/1972649/198026672-d622b921-2b96-4d74-b375-fe22d6a77f48.png)
