### ISSUE TITLE
每次设置“开机自启”保存后，关掉设置界面再打开设置界面的时候勾勾就没了

### ISSUE THREAD

**Issue by TerenceWu718** [cuiliang/QuickPadCn#1801]
每次设置“开机自启”保存后，关掉设置界面再打开设置界面的时候勾勾就没了

**Comment by cuiliang** [comment]
这个现象都是各类管家的开机启动管理导致的，请检查管家里的设置，包括联想电脑管家。

**Comment by TerenceWu718** [comment]
已经检查过各类管家 里面没有quicker的开机启动项，应该不是这个问题，不是电脑后那个勾勾没了，是关闭quicker的设置界面再打开就没了，所以不是那个的问题......很像bug 










在 2022-10-28 08:54:14，"CuiLiang" ***@***.***> 写道：

这个现象都是各类管家的开机启动管理导致的，请检查管家里的设置，包括联想电脑管家。

**Comment by cuiliang** [comment]
有安装任何管家软件么？ 可以尝试卸载掉它们，然后再看看有没有这个现象。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by TerenceWu718** [comment]
已解决了 感谢！
















在 2022-11-11 22:36:19，"CuiLiang" ***@***.***> 写道：

先关了，如果还有问题，请再reopen
