### ISSUE TITLE
基础设置-> 弹出面板 -> 长按右键  和 vmware的linux虚拟机冲突

### ISSUE THREAD

**Issue by gdbhub** [cuiliang/QuickPadCn#1802]
**描述BUG**

1. 在 基础设置-> 弹出面板 -> 长按右键，把这个选项勾选上。
2. 打开vmware虚拟机，而且是安装的Centos，带桌面，且安装了VM tools（vm-tools-desktop,open-vm-tools 均安装），会100% 无法使用右键菜单。表现是：在linux虚拟机中右键后，虚拟机的右键菜单在弹出后，又马上自动消失。 
3. 在关闭【长按右键】的选项后， vmware的Centos虚拟机的右键菜单恢复正常。

**相关截图**
![image](https://user-images.githubusercontent.com/102715209/199027672-0d123c0c-436a-4306-9499-2c64171c0dc3.png)
上图中的这种右键菜单，在整个系统维度都无法使用。

**环境信息:**
 - 物理机操作系统版本：Windows 10 企业版  22H2 19045.2130
 - Quicker版本：1.36.9
 - vmware版本：16.1.1 build-17801498
 - 虚拟机的版本：centOS Linux release 7.9.2009 (Core)

**附加信息**
经过其他测试， 如果虚拟机中运行的是Windows Server 2016， 则 弹出面板 -> 长按右键， 不管打开还是关闭， 均可正常召唤虚拟机的右键菜单。

**Comment by cuiliang** [comment]
参考这里试试： https://github.com/cuiliang/Quicker/issues/1567
