### ISSUE TITLE
快捷方式ctrl+/ 无法取消

### ISSUE THREAD

**Issue by y-mk-yc** [cuiliang/QuickPadCn#1804]
**需求描述**
ctrl+/ 这个快捷方式是会员才能使用，但是非会员不使用，也无法取消。作为一个程序员，很多时候都会使用这个快捷键进行注释，所以我每次都不得不关掉Quicker。

**描述你想要的解决方案**
希望非会员能够修改快捷方式，或者取消。

**Comment by cuiliang** [comment]
这里应该没有限制免费版设置的。现在没法修改么？请截图一下看看。

取消方法：
![image](https://user-images.githubusercontent.com/1972649/200168181-f6b366ca-a53e-48cc-8c48-b7842abc595b.png)

**Comment by y-mk-yc** [comment]
谢谢，现在没有了。因为我一直没更新的缘故。
