### ISSUE TITLE
搜索框崩溃

### ISSUE THREAD

**Issue by 00zzh** [cuiliang/QuickPadCn#1805]
把搜索框的所有历史记录关闭，会显示“无可用历史记录”对吧，这个时候搜索框空的情况下，右键“无可用历史记录”或按下方向右键，quicker会直接崩掉

**Comment by cuiliang** [comment]
感谢反馈，我研究下。

**Comment by cuiliang** [comment]
1.36.5 已修复 https://getquicker.net/Help/Versions
