### ISSUE TITLE
文本指令使用正则表达式匹配输入内容中，无法排除空格

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1807]
比如我希望把 斜杠开头的任意最多3个字符 作为匹配对象，比如匹配\int, \yw, \sy
因此我采用这样的正则表达式来进行匹配：`\\(.{1,3})`，效果就是以\开头，其后的任意1到3个字符作为参数，而后识别是否按下了触发按键
但是我没有把空格作为默认的激活文本指令的按键，也就导致上述的正则表达式会匹配到空格字符
![image](https://user-images.githubusercontent.com/36830343/201627790-4b42cf50-fc44-4890-b73a-3393b3b35c03.png)

但是正常情况来说，我们肯定是不希望在这里匹配到空格的，还有包括\字符本身也是不能匹配的，比如`\a b`和`\\a`这样都是不能匹配的，因此我采用正则表达式的排除写法来排除这样的字符，大概有4个：空格，\斜杠，\t制表符，\n换行符
**经测试，这4个符号除了换行符之外，另外3个都可以被识别为参数**，这里通过`[^\n\t\\]`这样的方式排除这3个字符都没有问题：`\\([^\n\t\\]{1,3})`

但是当我想用`[^ ]`或者`[^\ ]`排除空格时，返回了这样的错误

![image](https://user-images.githubusercontent.com/36830343/201629984-e8312e2b-d21c-4b8e-b7cb-491d4f05fa2b.png)

（看起来这个逻辑修改起来会比较麻烦）

**Comment by cuiliang** [comment]
可以利用“取第一个正则匹配组的值作为动作参数”选项，只取匹配内容的一部分。
另外，既然不用来触发，也不需要作为参数传入，为什么要输入空格呢？

**Comment by ilcpm** [comment]
>可以利用“取第一个正则匹配组的值作为动作参数”选项，只取匹配内容的一部分。

我现在就是这样设定的，但是会把空格匹配出来

![image](https://user-images.githubusercontent.com/36830343/201665164-e80ecdec-9f7a-442d-83a1-2ebce0392828.png)

> 既然不用来触发，也不需要作为参数传入，为什么要输入空格呢？

万一正好这里需要一个空格，然后空格完了又正好是触发字符，就很尴尬了……

比如我现在的触发字符就是\，输入`\a \b`的时候就第2个\就会把`\a `匹配到

当然，我这里的前缀引导和触发字符是同一个字符这当然不太好，但意思就是这个意思，用其他按键触发的话都不太方便


（狗逼数学符号敲起来真的麻烦，比如 $α_1,α_2,α_3,…,α_n$ ，在我已经用`\a\`来实现输入α之后敲出来是这样的`\a\_1,\a\_2,\a\_3,\dots,\a\_n`真的很酸爽……）

**Comment by cuiliang** [comment]
等下发个版本，启用正则时不限制缩写词内容。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 试下看看。

**Comment by ilcpm** [comment]
好像没用啊……
![image](https://user-images.githubusercontent.com/36830343/201679410-48c343fd-2808-4041-a585-d4a1e926331a.png)

包括这个功能好像也没用……浏览器里用右键+滚轮切换标签，还是会出现右键菜单，其他程序倒是没用触发右键菜单
![image](https://user-images.githubusercontent.com/36830343/201679463-e3f57f33-2132-47b2-9cba-fcea3e6ed05b.png)

**Comment by cuiliang** [comment]
失误🤦‍♂️ 文件更新错了。 等一下

**Comment by cuiliang** [comment]
现在试下看看
