### ISSUE TITLE
打开记事本然后切换其他窗口比如crt复制东西在切换会记事本窗口时会直接卡死什么都动不了,

### ISSUE THREAD

**Issue by 3020574863** [cuiliang/QuickPadCn#1808]
记事本是windows自带的用的是quiker启动软件添加上去的系统是windows11比较新的版本
![image](https://user-images.githubusercontent.com/76427713/202183265-cdafc6b1-53f9-45e3-8953-206ee289846b.png)
但是我不用quiker打开记事本用windows打开然后操作就没问题 用quiker就出现问题了(试过4次)
这导致我花了一个多小时弄得拓扑图全没了😭

**Comment by cuiliang** [comment]
这似乎是搜狗输入造成的，具体可参考这里： https://getquicker.net/QA/Question/14272 

目前的解决方法：
1）修改动作为脚本类型
2）脚本内容为 start notepad

**Comment by 3020574863** [comment]
ok了解




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月16日(星期三) 晚上8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cuiliang/Quicker] 打开记事本然后切换其他窗口比如crt复制东西在切换会记事本窗口时会直接卡死什么都动不了, (Issue #1808)





 
这似乎是搜狗输入造成的，具体可参考这里： https://getquicker.net/QA/Question/14272
 
目前的解决方法：
 1）修改动作为脚本类型
 2）脚本内容为 start notepad
