### ISSUE TITLE
在Windows锁屏休眠状态下，Quicker会和coodesker联合产生bug,导致桌面所有窗口集中在左上方

### ISSUE THREAD

**Issue by anonymous12357** [cuiliang/QuickPadCn#1809]
**描述BUG**
对bug的清晰简洁描述。
在Windows锁屏休眠状态下，Quicker会和coodesker（www.coodesker.com，酷呆桌面）后台同时运行时会联合产生bug,导致桌面所有窗口集中在左上方

**重现步骤**
1. 同时运行Quicker会和Todesk最新版
2. 等待锁屏睡眠，解锁后发现所有窗口缩小并集中在左上方

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：latest

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
quicker应该不会自动修改其它窗口的位置，似乎也没有什么可以做的。 todesk不是个远程桌面的程序么？

**Comment by anonymous12357** [comment]
> quicker应该不会自动修改其它窗口的位置，似乎也没有什么可以做的。 todesk不是个远程桌面的程序么？

写错了，是coodesker，桌面图标整理软件

**Comment by cuiliang** [comment]
具体怎么复现呢？我安装和运行了这个软件，锁定后解锁，窗口似乎没有什么变化。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
