### ISSUE TITLE
虚拟键V1的一些建议

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1810]
能不能把V1键做成可以一直按住的“状态”？就是不设置按下的时间长短，一直按下去
以及能不能把V1加入到扩展热键里？

运行一个动作的时候把V1按下去，然后按某些按键执行动作，再运行一下把V1弹起来，按键就正常工作

比如我经常对着教材看视频学习，所以我希望能够在PDF软件里实现对视频进度的调整和播放暂停
但是视频的来源可能是来自网页上，也可能是来自播放器，所以我希望通过V1的按下与否这个“状态”来让相同的手势或者快捷键控制播放器和网页这两个程序

具体就是：
通过动作触发V1的按下和抬起
- V1抬起时，鼠标的水平滚动通过高级鼠标触发调整播放器的播放进度
- V1按下时，鼠标的水平滚动触发“V1+水平滚动”来调整网页播放器的播放进度
- V1抬起时，鼠标侧键的“暂停/播放”按键直接发送按键本身，不进行处理，由此对播放器进行播放和暂停
- V1按下时，鼠标侧键的“暂停/播放”按键激活“V1+暂停/播放”的组合键，触发动作来让网页播放器播放和暂停

---

这样把V1做成状态之后，很多动作只需要增加一个检测V1是否按下的条件，就可以根据需要实现两种功能，更加灵活
像鼠标收拾或者轮盘菜单，也可以设置成V1按下的时候触发轮盘菜单，没按下的时候触发鼠标手势，实现在某些软件里使用鼠标手势，某些软件里使用轮盘菜单的功能了

**Comment by cuiliang** [comment]
可以设置超时秒数到比较大的数。
不过我感觉这样不是合适的，它会影响所有的鼠标触发，所以应该只合适临时使用一下切换状态。

**Comment by ilcpm** [comment]
那可以让V1适配键盘的按键吗，我在鼠标上做了个播放暂停的按钮，只有配合V1之后才能同时适配浏览器和播放器

（其实我也觉得长时间的V1启用会不合适，比如鼠标键盘完全被架空了自己还不知道怎么回事）

**Comment by cuiliang** [comment]
> 那可以让V1适配键盘的按键吗，我在鼠标上做了个播放暂停的按钮，只有配合V1之后才能同时适配浏览器和播放器
> 
> （其实我也觉得长时间的V1启用会不合适，比如鼠标键盘完全被架空了自己还不知道怎么回事）

没太懂。 键盘本身可以作为引导键的，在扩展热键里可以设置。

**Comment by ilcpm** [comment]
![image](https://user-images.githubusercontent.com/36830343/204757810-e2abdb65-7af5-4b33-aae4-a3da28cf8f23.png)
就是说这里没有办法用V1作为引导建

比如我设置调整播放进度的快捷键，没有V1的时候直接触发播放器的进度调整，`V1+快捷键`就触发浏览器的进度调整

**Comment by cuiliang** [comment]
这里v1本身也要使用某个键触发，为什么不直接用那个键呢？

**Comment by ilcpm** [comment]
我本来想的是，在鼠标上做3个动作，一个触发`播放/暂停`这个按键，另外两个来调整播放进度
如果没有按下V1按键，这3个键就会对播放器进行操作
如果按下了V1按键，这3个键就对网页播放器进行操作

但是现在V1只能和鼠标交互，我就没办法实现`V1+播放/暂停`这个键盘按键来触发网页播放器的暂停了

整个过程中实际上并没有按键盘的操作

---

另外想问下，如果我设置某个动作按下V1 10秒钟，那t=5的时候我再触发一次这个动作，这个时候V1是会在t=10的时候弹起，还是叠加到t=15的时候弹起呢
