### ISSUE TITLE
表单字段太多时下方按钮超出屏幕

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1811]
![image](https://user-images.githubusercontent.com/48246272/203072248-d7b8a312-34a7-4088-90fa-5886999ab6b7.png)

quicker 版本 1.36.5

**Comment by cuiliang** [comment]
这么多？我等看下了
![erinnnmrYI](https://user-images.githubusercontent.com/1972649/203072702-fdb0e99c-ad4a-46e9-8f42-fbba28ed2e88.gif)

**Comment by cuiliang** [comment]
这个应该已经修改好，改成固定尺寸了。
