### ISSUE TITLE
优化捕获控制台输出的性能

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1812]
**需求描述**
我开发了一个需要经常通过命令行调用第三方软件的动作，因此大量使用了捕获控制台输出的功能，结果用户和我反馈的 bug 中有一小半都是捕获控制台输出导致的卡死
https://github.com/cuiliang/Quicker/issues/1696#issuecomment-1170829655
一部分命令我通过 `>` 写入到文件后读取，但不是所有命令都支持；一部分命令我通过绕弯子的方法来检查是否成功。可以说我已经和捕获控制台输出可能卡死这点进行了长久的斗智斗勇，今天我终于遇到了一个绕不过去的槛，替代方法无法保证 100% 安全，我只能再来问一次，捕获控制台输出的性能有没有优化的空间

**Comment by cuiliang** [comment]
是用的“运行和打开”模块么？

刚又找到了一些帖子，我再试试看看，如果能解决，会在下一版里更新。

https://stackoverflow.com/questions/43204624/what-are-buffer-sizes-of-process-start-for-stdout-and-stderr
https://stackoverflow.com/questions/139593/processstartinfo-hanging-on-waitforexit-why

**Comment by ghost** [comment]
> 是用的“运行和打开”模块么？

是 运行脚本 模块

**Comment by cuiliang** [comment]
这个脚本调用的是什么程序？ 我测试了一下，如果只有StandardOuptput的时候不会卡死，但是如果程序有StandardError输出，超过buffer就会卡死了。 如果程序的stderror输出没有什么用，可能直接丢弃就行

**Comment by ghost** [comment]
> 这个脚本调用的是什么程序？ 

kopia 和 git，比方说 `git add .` 和 `git commit` 都有可能卡死，后者可以用 `>` 输出，但前者不行，我尝试过先不捕获运行一次再捕获运行来提高成功率，结果还是不行于是改用 `git status` 和 `>` 来判断是否成功

kopia 的这三个命令都有用户卡死过
```
C:\Users\11040>kopia snapshot list D:\工作与学习\ObsidianBackup
11040@wind_stop:D:\工作与学习\ObsidianBackup
  2022-10-24 11:57:58 CST kf56411eacd971f8004179f839e77cd5b 9.9 MB drwxrwxrwx files:151 dirs:28 (latest-2,weekly-2)
  2022-11-03 20:55:20 CST ka1b9e1d344fba52997bc0b4d81ed7fc3 9.9 MB drwxrwxrwx files:151 dirs:28 (latest-1,hourly-1,daily-1,weekly-1)
```
我挑了一个较短的输出。该命令下去后全部内容会一起出来，我需要全部的输出内容。好在该命令可以用 `>` 输出


```
C:\Users\11040>kopia snapshot create C:\App\SuperMemoBackup --force-enable-actions
Snapshotting 11040@wind_stop:C:\App\SuperMemoBackup ...
 * 0 hashing, 32 hashed (397 KB), 6155 cached (59.8 MB), uploaded 198 B, estimated 60.2 MB (100.0%) 0s left
Created snapshot with root k2c37d52839ba2f2ea9762048cd82d817 and ID 2b3509bcab6644f47a772c348a67f8b2 in 5s
```
这里的输出是一行行逐渐出来的，并且 * 开头的那行会实时更新，我只需要最后一行来判断成功或出错

```
C:\Users\11040>kopia restore k8258e9b6c90d26c0bbaa2e7551a42cd5 "C:\App\quickertemp60e7e9a7-ffab-4f04-9725-7f7e41a3389e"
Restoring to local filesystem (C:\App\quickertemp60e7e9a7-ffab-4f04-9725-7f7e41a3389e) with parallelism=8...
Processed 1043 (48.9 MB) of 6773 (60.2 MB) 48.9 MB/s (81.2%) remaining 0s.
Processed 1500 (49.4 MB) of 6773 (60.2 MB) 24.6 MB/s (82.0%) remaining 0s.
Processed 2027 (50 MB) of 6773 (60.2 MB) 16.6 MB/s (83.0%) remaining 0s.
Processed 2582 (51.3 MB) of 6773 (60.2 MB) 12.8 MB/s (85.1%) remaining 0s.
Processed 3091 (52.6 MB) of 6773 (60.2 MB) 10.5 MB/s (87.3%) remaining 0s.
Processed 3624 (53.2 MB) of 6773 (60.2 MB) 8.8 MB/s (88.2%) remaining 0s.
Processed 4172 (54.9 MB) of 6773 (60.2 MB) 7.8 MB/s (91.2%) remaining 0s.
Processed 4689 (55.7 MB) of 6773 (60.2 MB) 6.9 MB/s (92.5%) remaining 0s.
Processed 5195 (56.2 MB) of 6773 (60.2 MB) 6 MB/s (93.3%) remaining 0s.
Processed 5738 (58 MB) of 6773 (60.2 MB) 5.6 MB/s (96.3%) remaining 0s.
Processed 6270 (58.8 MB) of 6773 (60.2 MB) 5.2 MB/s (97.5%) remaining 0s.
Processed 6753 (60.2 MB) of 6773 (60.2 MB) 4.9 MB/s (100.0%) remaining 0s.
Processed 6774 (60.2 MB) of 6773 (60.2 MB) 4.9 MB/s (100.0%) remaining 0s.
Restored 6187 files, 587 directories and 0 symbolic links (60.2 MB).
```
这里的输出也是一行行逐渐出来的，我也只需要最后一行来判断成功或出错

**Comment by cuiliang** [comment]
我改了一版，等晚点发一下试试

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 
更新了一版，试下看看。

**Comment by ghost** [comment]
> https://getquicker.net/Help/Versions 更新了一版，试下看看。

全丢了
![image](https://user-images.githubusercontent.com/48246272/203346170-448c1eb7-ca87-44c7-a20f-9fef3e53835f.png)

**Comment by cuiliang** [comment]
@fwzuw 现在区分了控制台输出和控制台错误的输出，是不是这个程序是通过控制台错误（stderr）输出的？
![image](https://user-images.githubusercontent.com/1972649/203445191-63860692-15db-4890-84a1-1b220679b118.png)

**Comment by ghost** [comment]
这一段的确是通过 stderr 输出的
这样的话我得花一些时间做适配才能更新动作给用户去试

**Comment by cuiliang** [comment]
需要一个合并后的输出么？

**Comment by ghost** [comment]
能合并就太好了
我动作里有很多运行脚本模块，一个个试出出来做适配我得头秃
能否将原先的控制台输出直接更新为合并输出？这样就不用修改动作了

**Comment by cuiliang** [comment]
嗯，我研究下

**Comment by ghost** [comment]
1.36.10 不知为何推送到了 快速分支，已经开始有用户向我反馈动作出错，请问合并输出还打算做吗？不做我就针对 1.36.10 修改动作了

**Comment by cuiliang** [comment]
@fwzuw 已经做了，还有点问题，今天发个版本。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions/Version?version=1.36.11.0 @fwzuw 更新了一版，等试下看看能不能正常工作

**Comment by ghost** [comment]
有个问题
![image](https://user-images.githubusercontent.com/48246272/204739444-1ccd5605-67bd-47d0-85db-a6b899f14797.png)
这个 \r 是怎么回事，以前的控制台输出换行只有 \n，这十分影响正则提取。1.36.10 也有这个问题

**Comment by cuiliang** [comment]
以前是整体读取输出的，估计原始程序没有输出\r，造成了那个buffer满了就会卡死的现象。 
现在的解决方法是按行接收和保存，会使用windows的标准换行输出，每个换行包含\r\n两个字符。（这种情况下也没法知道程序本身输出的是\n还是\r\n）。
估计只能正则调整一下去除\r了。

**Comment by ghost** [comment]
> 估计只能正则调整一下去除 \r 了。

调整指的是 quicker 会调整正则匹配模块直接去除还是让用户在写正则的时候额外匹配一下？

**Comment by cuiliang** [comment]
需求在动作里修改正则提取，或者使用文本处理去除一下两侧的空白
![image](https://user-images.githubusercontent.com/1972649/204751412-7621887f-76f9-4437-938a-cb4b3e70f9b7.png)

**Comment by ghost** [comment]
之前出问题的用户在更新 1.36.11 后没有卡死了，可以初步认为这个 bug 已经修复了
我与这个 bug 的斗智斗勇终于告一段落 
![流泪](https://user-images.githubusercontent.com/48246272/204782257-f9274e70-a6f7-4839-b8da-b5951551ce02.jpg)

**Comment by cuiliang** [comment]
😂

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
