### ISSUE TITLE
在子程序中删除输出变量之后，主程序中对应的变量还处于被占用状态，无法删除

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1813]
比如在子程序中定义了输出变量A，在主程序中用变量AA接受输出

而后在子程序中删除变量A，此时主程序中调用子程序的动作里已经不见了接受输出的AA变量

但是在主程序中删除变量AA时，变量AA仍然处于被子程序使用的状态无法删除

![image](https://user-images.githubusercontent.com/36830343/203368645-87d74d8d-45d5-4d9f-b333-7d5130673a28.png)

**Comment by cuiliang** [comment]
编辑这个“运行子程序”的步骤，点击“保存”，就会去除不使用变量的引用了。

**Comment by ilcpm** [comment]
哦哦，原来如此
