### ISSUE TITLE
激活进程主窗口启动程序时未识别 storeapp

### ISSUE THREAD

**Issue by Clouder0** [cuiliang/QuickPadCn#1814]
**描述BUG**

在调用激活进程主窗口函数时，若进程不存在则根据程序路径启动。从已安装程序中选择从 MS Store 安装的 App 后无法启动。

**重现步骤**
1.新建一个激活进程主窗口的动作
2.程序路径从已安装软件中选择一个从 Store 安装的 app
3.运行动作

**相关截图**

![image](https://user-images.githubusercontent.com/41664195/203787182-706845c0-b5ad-494b-9fea-09961623feec.png)

![image](https://user-images.githubusercontent.com/41664195/203787228-bcd84aa8-148d-4f9f-9100-7d8c7734c5e7.png)

**环境信息:**
 - 操作系统版本：Windows 11 22H2
 - Quicker版本：1.36.0

**附加信息**

值得一提的是，使用【运行和打开】执行则一切正常。

**Comment by cuiliang** [comment]
程序路径是exe文件的路径，对于商店应用不适用。商店应用直接运行和打开即可，通常他会自己激活窗口。

**Comment by Clouder0** [comment]
> 程序路径是exe文件的路径，对于商店应用不适用。商店应用直接运行和打开即可，通常他会自己激活窗口。

确实是这样的，但这里【激活进程主窗口】的 fallback 也采用【运行和打开】的逻辑会好一点吧。直接使用【运行和打开】勾选尝试激活窗口后在此时的目的是一样的，都是“激活窗口，如果没有窗口则先运行”，但前者不支持 storeapp 而后者支持，容易造成困惑。

**Comment by cuiliang** [comment]
有道理，我等试下看看。
谢谢~

**Comment by cuiliang** [comment]
已修改，待 1.38.10 更新。
