### ISSUE TITLE
增加“向指定窗口发送快捷键”的功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1815]
有的程序在程序内有快捷键，但是需要先激活窗口快捷键才能生效

我看有个向窗口发送消息的功能(sendMessage)，对开发不了解，这个看起来应该是可以支持发送快捷键的消息进去的对吧？
我试着检索了一下，在这里发现了对应的例子 https://learn.microsoft.com/en-us/answers/questions/580330/c-sendmessage-send-shortcut.html

可不可以把这个功能封装一下，直接向指定的窗口发送快捷键信息？
这样就可以在不激活程序的情况下对程序进行操作了

**Comment by ilcpm** [comment]
上面的网站搞错了，那个好像是用keybd_event实现的，不是sendMessage

我用这里的方式实现了向窗口发送ctrl tab的功能，但是只对前台窗口成功了，窗口在后台不行
https://stackoverflow.com/a/7732675

![image](https://user-images.githubusercontent.com/36830343/203939401-630ec66a-0c90-41da-8fa9-b9720de3217e.png)

**Comment by cuiliang** [comment]
不太可行的。键盘都是发送到活动窗口。
