### ISSUE TITLE
关于变更悬浮动作的按钮大小的修改方式

### ISSUE THREAD

**Issue by jqrjqr** [cuiliang/QuickPadCn#1816]
**需求描述**
- 本人是悬浮动作的重度使用用户，非常喜欢这个功能，很多窗口都会设置常用悬浮动作。很感谢作者给我带来的便捷体验，已购买会员支持。
- 个人认为，悬浮动作的按钮大小的修改方式需要变更。有以下几点原因：
    1、当前修改按钮大小的方式为鼠标拖动修改，优点是简单直观。但目前使用中发现按钮大小基本只会在悬浮后修改一次，然而以后每次点击该悬浮按钮，鼠标在移动到该按钮的过程中，都会出现修改按钮大小的鼠标样式。这种样式的出现过于频繁，且大多数时候都是无用的，强迫症看了很难受。
     2、每次都出现修改鼠标的样式，容易造成误修改，我已经遇到好几次这种情况，特别是当多个按钮悬浮成一排或一列时，为了点击某个动作，鼠标可能会经过多个按钮。这期间如果不小心点击了鼠标左键，就可能误修改，导致按钮大小变样。且鼠标在经过多个动作时，会不停变更样式，造成视觉干扰。
    3、拖动鼠标修改大小的方式并不精确。实际使用中，往往会将多个动作悬浮成一排或者一列，这要求每个悬浮动作的按钮大小一 致。当前因为悬浮时会自动设置按钮大小为上一个悬浮的按钮大小，这个问题并不严重，但希望提供直接修改按钮边框长度的数值的选项。

**描述你想要的解决方案**
我的建议：
- 悬浮动作的鼠标右键菜单-->悬浮，添加一个子菜单：修改按钮大小，弹出输入框，输入框初始值为当前按钮的边框长度值，用户可直接修改数值。输入框的旁边可以加个当前数值下悬浮动作的按钮大小示例，不加也行，设置完直接看效果也不麻烦。
- 取消鼠标位于悬浮按钮边框时的样式变更。因为并不会经常修改悬浮按钮大小，将此功能放在入口更深的右键菜单中就足够了。也可以在Quicker设置-->基础设置-->常规-->悬浮功能，添加一个可选项，在保留现有悬浮按钮大小修改方式的前提下，增加右键菜单的修改方式，让用户自己选择以哪种方式修改悬浮按钮的大小。

 **其他上下文**
相关截图
![image](https://user-images.githubusercontent.com/42792946/204666697-7cf1631a-8d01-4a3a-8340-4c4b683d1896.png)
![image](https://user-images.githubusercontent.com/42792946/204673550-1aa44192-efac-4d13-ae7c-b312eadec19a.png)
![image](https://user-images.githubusercontent.com/42792946/204666802-912976e0-e0f5-489c-8903-e9d7fff946ee.png)
![image](https://user-images.githubusercontent.com/42792946/204666997-dacc4df4-a2ac-4804-8ee8-658cce53ef90.png)

**Comment by cuiliang** [comment]
感谢反馈，等研究下。

**Comment by cuiliang** [comment]
后来增加了设置项可以禁止调整悬浮按钮大小。
