### ISSUE TITLE
高级鼠标触发中涉及右键的操作会触发右键菜单

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1817]
比如鼠标右键+滚动这样的操作，滚动完之后释放鼠标右键仍然会触发右键菜单

之前看好像有个更新修复了这个问题，但是好像没用

**Comment by cuiliang** [comment]
这里设置的时间长一点，确保这个时间到期之前触发了操作。
如果仍然出现，提供一下详细设置我这里测试看看。
![image](https://user-images.githubusercontent.com/1972649/205176543-ca9d05a4-1cdb-47ed-977a-01d83b742ae5.png)

**Comment by ilcpm** [comment]
问题解决，谢谢
