### ISSUE TITLE
移动窗口参数出问题

### ISSUE THREAD

**Issue by cao198** [cuiliang/QuickPadCn#1818]
**描述BUG**
因需要同一程序运行4开，在编辑步骤时，设置“窗口操作”选择“移动窗口（增强）”时，如目标位置参数为“0%,33%,50%,100%”时，窗口会跳到“1%,0%,51%,67%”，而把参数改为“0%,33%,50%,99%”就可以，同时设置为“50%,33%,100%,100%”也不会有问题

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.36

**Comment by cuiliang** [comment]
在一处提交即可。
