### ISSUE TITLE
内存不够提示

### ISSUE THREAD

**Issue by ZiyuanZui** [cuiliang/QuickPadCn#1819]
电脑使用其他软件占用满后,再使用Quicker弹出内存不足提示,内存恢复后,还是会弹出提示,而且提示提示框没有限制,能够弹出多个

**重现步骤**
1.使内存占满
2.使用Quicker功能

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：Quicker.x64.1.34.15.0,目前使用的版本,其他版本也会出现

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 最新版应该没有重复弹窗的问题了，可以这里下载更新一下。

**Comment by ZiyuanZui** [comment]
简单测试了一下,没有这个问题了,我再使用几天,看看会不会出现

**Comment by cuiliang** [comment]
@ZiyuanZui 如果出现了这个提示，说明程序已经遇到了不能正常处理的情况，必须要重启软件才行了。如果有没保存的内容就赶紧保存一下。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
