### ISSUE TITLE
弹出面板鼠标方式不识别按键

### ISSUE THREAD

**Issue by FDeer** [cuiliang/QuickPadCn#1820]
**BUG简述**
在设置鼠标方式弹出面板时，案件测试区无法识别侧边按键，但侧边按键实际测试可用
**重现步骤**
1.侧边按键功能设置为无功能。
2.在quicker中进行“按键测试”无法识别，三处快捷键均测试。

**相关截图**
![image](https://user-images.githubusercontent.com/60988915/207814948-22306a4e-9df6-4cb9-afcd-ca02f5a07a78.png)

**环境信息:**
 - 操作系统版本：Win11 22621.963
 - Quicker版本：1.35.42
 - 设备：罗技 MX Master3
 - 设备驱动：logi Options+ 1.30.7349

**Comment by cuiliang** [comment]
x1 = 后退， x2 = 前进。

**Comment by FDeer** [comment]
感谢
