### ISSUE TITLE
自己分享的动作没有更新分享的选项了

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1821]
如图，我自己分享的动作（分享时用的名字和自己用的动作名字不同），在自己修改之后，右键看不到更新分享的选项了

![image](https://user-images.githubusercontent.com/36830343/208755604-eed1ecfd-76e6-4982-adb9-1fce9a59b393.png)

**Comment by ilcpm** [comment]
https://getquicker.net/Sharedaction?code=94a32c0d-bc5f-44c3-140f-08dabfe512ee

这是动作的网址

**Comment by cuiliang** [comment]
修改一下动作步骤定义，应该就会出现更新分享了。

**Comment by ilcpm** [comment]
可以了，谢谢
