### ISSUE TITLE
鼠标手势与罗技鼠标侧键配合时，似乎是对侧键的判定有问题，导致无法触发动作

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1822]
我用了quicker的鼠标手势，希望在原有最小化窗口的手势上增加“如果按住Ctrl，就最小化到托盘”的功能
所以我找了个把前台程序最小化到托盘的动作，并如图设置
![image](https://user-images.githubusercontent.com/36830343/209446021-885907f0-d4cd-4b8b-8a9b-ec5b35652291.png)

其中的LeftCtrl是设置的鼠标侧键，且直接从鼠标上读取出来的按键，这样我就可以用鼠标右键画手势，然后按下侧键Ctrl激活“最小化到托盘”的功能

但是设置完成之后我发现画完笔画之后用侧键无法激活动作，侧键的Ctrl无效，而使用键盘左边的Ctrl键是可以生效的
我本来以为是鼠标的控制程序的问题，按下右键之后侧键无法生效，但是我发现右键画出手势之后实际上侧键是可以生效的
下面的视频里面我用软件监控了键盘的状态，可以看到每次Ctrl都是生效了的，但是无法触发动作，最后一次的时候我用的键盘上的leftCtrl就成功激活了动作，并弹出了提示“1”
而且我用powertoy设置的按两次Ctrl触发鼠标聚焦功能也可以在画手势的过程中触发，视频里也有出现
（鼠标手势中，不论是设置成LeftCtrl，还是Ctrl，都无法用鼠标触发，设置成Ctrl之后键盘也无法触发了）

鼠标是用的MX Master 3s，软件是目前最新的logiOption+

https://user-images.githubusercontent.com/36830343/209446314-4235165c-528e-494d-b903-d0bcd6835e22.mp4

**Comment by ilcpm** [comment]
我用quicker的“键盘状态”功能看了一下，硬件键盘的Ctrl按下的时候是这样的
![image](https://user-images.githubusercontent.com/36830343/209447252-15b416ea-c5c1-4feb-8e5f-96f48f4abb2d.png)

 用鼠标上的侧键Ctrl时是这样的， 只有系统按键状态而没有键盘挂钩，不知道是不是因为这个导致的无法触发
![image](https://user-images.githubusercontent.com/36830343/209447263-0c7efdbe-afe3-4e6d-8ae9-e01149b751d1.png)

另外还有一个和媒体按键有关的问题，我再单独开一个issue吧

**Comment by cuiliang** [comment]
罗技软件里怎么设置的ctrl？截个图看下

**Comment by cuiliang** [comment]
经过确认，这个是因为罗技驱动里模拟的键盘按键有一个“模拟”标记。 这个标记用来区分模拟的按键还是物理按键。 通常模拟按键不应该再触发操作，因为动作里也可能会模拟按键从而造成一些循环和混乱。

可以在这里取消这个选项试试：
![image](https://user-images.githubusercontent.com/1972649/209816758-7c09e274-6366-4fbd-92d3-0b6e7f92fcdc.png)

**Comment by ilcpm** [comment]
取消那个选项之后确实可以生效，但是也确实在特殊场景下出现了问题

- 添加CapsLock为扩展热键的引导键
- **全屏**使用RDP远程桌面
- 在quicker中排除RDP程序
- 在全屏的RDP程序中按下CapsLock键
- quicker反复报错
![image](https://user-images.githubusercontent.com/36830343/209928304-f2cc399b-8a6c-4296-b1ae-b0d618c0537b.png)

我也不知道这种情况该怎么办，就如实反馈一下吧😂

**Comment by cuiliang** [comment]
重启一下quicker试试 @ilcpm

**Comment by ilcpm** [comment]
重启之后再按CapsLock会继续弹出这个，除非暂停quicker或者勾上那个选项
（上面反馈的意思是说，遇到了这个特殊的情况，不是说不知道该如何跳出那个报错😂）

**Comment by cuiliang** [comment]
扩展热键 ，Caps引导键里面添加什么规则了没？截图看下

**Comment by ilcpm** [comment]
自然是有 一大堆规则的，但是这里仅仅只是在RDP全屏状态下“按下了CapsLock”，没有按别的键就会这样
A电脑使用RDP操控B电脑，A电脑上全屏使用RDP程序，A电脑上的quicker报错，RDP程序窗口化运行时不报错

![image](https://user-images.githubusercontent.com/36830343/209930411-397cef16-cdda-4f05-a7c8-f9c2b8c40d43.png)

![image](https://user-images.githubusercontent.com/36830343/209930565-896b439e-74a1-4283-8fcf-4b63994f8442.png)

**Comment by cuiliang** [comment]
好的，我研究下这个问题

**Comment by cuiliang** [comment]
黑名单默认只对鼠标触发方式生效，
可以开启一下这个选项试试。
![image](https://user-images.githubusercontent.com/1972649/209957289-0317384a-6f2c-451c-8ec5-6cba9a00269f.png)

**Comment by ilcpm** [comment]
好使😂辛苦了
这些设置看的时候容易看漏或者忽略，或者干脆就不知道是干什么用的，需要的时候又不知道有这么个设置，添麻烦了🙏

**Comment by cuiliang** [comment]
没事没事，那个提示报错的我等再处理一下。 现实各种情况比较多，所以也比较复杂容易出现一些边界问题。
https://github.com/cuiliang/Quicker/issues/1824 这个你等有空再查下看看哪里用到中键了，我测试如果没有用到就不会拦截的。

**Comment by ilcpm** [comment]
好的，这两天在赶论文，我空了测试一下

**Comment by cuiliang** [comment]
不急，正事要紧，我先关掉这个issue了。
