### ISSUE TITLE
quicker导致鼠标中键拖动无法实时生效

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1824]
在例如VSC这样的软件中，可以用鼠标中键拖动来进行跨行的多列选择，使用quicker后按下中键无法实时拖动，以下是测试条件：

- 没有激活任何打开quicker主面板的方式（中键或Ctrl+中键）
- 扩展热键中没有添加中键
- 没有使用中键作为鼠标手势
- 没有使用轮盘菜单
- 高级鼠标触发中没有**启用**任何和中键相关的操作

总之就是没有在quicker中用中键做任何事情，然后在用鼠标中键拖动的时候无法实时生效，需要按下一定时间后，才可以拖动

一旦暂停quicker，就可以实时触发了

**Comment by ilcpm** [comment]
测试了一下，应该也是受图上这个时间控制的，把这个时间调小，就可以得到近似实时的效果了
但是如果这个时间调小，那么鼠标手势的触发和右键+滚动一类的高级鼠标触发也会收到影响，导致触发完毕弹出右键菜单……

所以为什么要多此一举在没有使用的情况下对中键做个判断呢
![image](https://user-images.githubusercontent.com/36830343/209449649-02f70591-2ea5-4c9e-9159-6b35b18dfbc5.png)

**Comment by cuiliang** [comment]
检查一下有没有设置中键为引导键？ 
如果所有地方都没有用到中键，应该不会拦截的。

![image](https://user-images.githubusercontent.com/1972649/209813896-141f4f72-84d7-4079-a2a0-98c585636d76.png)

**Comment by ilcpm** [comment]
完整测试见视频，确实很奇怪

没有任何地方使用到了鼠标中键，甚至我都完全删掉了之前几个和鼠标中键相关的高级鼠标触发
通过查看“键盘状态”，鼠标中键按下之后“鼠标挂钩”实时出现，但是需要等一段时间“系统按键状态”中才有中键出现
暂停quicker之后，鼠标中键实时响应

而且中键的延迟和扩展热键的超时时间无关

另：在扩展热键中删除鼠标中键作为引导键之后，重新打开设置界面仍然会出现鼠标中键

https://user-images.githubusercontent.com/36830343/210154355-76fd15a6-e5c2-4ce1-baa3-33734e8d6de2.mp4

**Comment by cuiliang** [comment]
@ilcpm  确实有点奇怪，什么时候方便远程看看？ 加qq 197906 之后使用向日葵远程。

**Comment by ilcpm** [comment]
![image](https://user-images.githubusercontent.com/36830343/211834933-dba918d2-56f8-4b2d-8490-c156df4dfbef.png)

 经检查，是快速截图功能中使用了鼠标中键，导致中键被错误的占用了

**Comment by cuiliang** [comment]
整理issues
