### ISSUE TITLE
在装了Mactype的环境下UI很多字体渲染不全

### ISSUE THREAD

**Issue by JiaChen-Zeng** [cuiliang/QuickPadCn#1825]
**描述BUG**
在装了Mactype的环境下UI很多字体渲染不全

**重现步骤**
1. 装好 Mactype
2. 随便打开设置界面

**相关截图**
![image](https://user-images.githubusercontent.com/3676278/209801609-0d6d9651-f269-44b7-8f9f-6d8658fc75a6.png)

**环境信息:**
 - 操作系统版本：Windows 10
 - Quicker版本：1.36.13

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个quicker这边没有什么能做的。看看那个软件里能不能设置黑名单，避免对quicker生效？或者到mactype的讨论区咨询一下看看。

**Comment by JiaChen-Zeng** [comment]
有白名单，不过我感觉可能调节下什么设置就会变正常，毕竟中键右键窗口和搜索框字体都是正常的

**Comment by cuiliang** [comment]
Microsoft YaHei UI  这个看起来不完整的是这种字体，可能mactype软件影响了这些字体的渲染。
目前没有什么可以修改的。

**Comment by JiaChen-Zeng** [comment]
我可能知道了，MacType有个字体（font family）热替换的功能，我设置了这个字体自动替换成其它字体，所以渲染不全
