### ISSUE TITLE
组合动作的快捷键不要响应模拟按键

### ISSUE THREAD

**Issue by tswwe** [cuiliang/QuickPadCn#1828]
**需求描述**
1. 在**组合动作**（注意不是基础动作）里，用“按键操作”或者“模拟按键”模拟一个或一些按键，例如 ABC。
2. 从第 1 步模拟的按键中选一个，例如 C，将其设为该组合动作的**快捷键**。
3. 在记事本里按下 C 键触发该组合动作，会发现组合动作能够顺利按出 AB，但是在模拟 C 键的时候，因为第 2 步的设置，导致 C 键被截获而按不出来。

**描述你想要的解决方案**
钩子捕获到组合动作的快捷键时，判断其是否为模拟的按键，如果是，就直接放行，而不是吞掉或者触发组合动作。

**Comment by cuiliang** [comment]
快捷键触发是windows机制，需要自己避免这种情况的出现。
避免冲突可以尝试扩展热键，这种是使用挂钩的。
