### ISSUE TITLE
轮盘菜单存在一个错误的空白轮盘页面

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1829]
添加鼠标高级手势：右键+滚轮 → Ctrl+Tab
轮盘菜单选用鼠标右键激活

用右键触发轮盘菜单，滚动鼠标，会得到一个完全空白的轮盘，没有任何动作
如果给鼠标反方向滚轮添加一个Ctrl+Shift+Tab的动作，还可以返回之前的有动作的页面

**Comment by cuiliang** [comment]
参考这里：
https://getquicker.net/KC/Manual/Doc/circle-menu#40adbfe3680967e041f28fc08a1a75d9_h1_3:~:text=%EF%BC%887%EF%BC%89%E5%88%87%E6%8D%A2%E5%88%B0,%E5%8A%A8%E4%BD%9C%E7%9A%84%E6%A8%A1%E5%BC%8F%E3%80%82
