### ISSUE TITLE
希望quicker出个显示鼠标键盘的按键的功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1830]
就是那种按下键盘按键之后在屏幕上显示出来的功能
市面上的几款按键回显软件感觉都不好用
正好quicker也有个检测键盘状态的功能，可以做个更加专业的显示功能嘛

比如可以选择响应键盘挂钩还是响应系统按键状态，还可以加上对鼠标按键的显示功能
而且试过的软件里面还会出现比如某个按键是quicker的扩展热键，然后就会按一次显示两次，quicker来做的话正好可以避开这点

**Comment by suka233333** [comment]
https://getquicker.net/Sharedaction?code=36a7c9f2-7f29-449f-5f11-08d6cebc3090
这个将就能用

**Comment by cuiliang** [comment]
这个和quicker的功能关系不大，感觉在单独的程序里实现比较好。 后期考虑以插件方式提供支持。

**Comment by suka233333** [comment]
> 这个和quicker的功能关系不大，感觉在单独的程序里实现比较好。 后期考虑以插件方式提供支持。

插件可以，支持支持！！ 啥时候把electron也做成插件支持呀，想写点UI啥的。。。
