### ISSUE TITLE
给“快捷键（动作）”增加可以使用“常用功能”的功能

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1831]
下图是鼠标手势和轮盘菜单上可以使用的功能，有的常用操作可以直接调用，比如窗口置顶
但是反过来如果想用键盘把窗口置顶，就只能直接去做一个窗口置顶的动作，然后用“快捷键（动作）”的功能添加快捷键，就感觉挺离谱的，一模一样的功能，鼠标可以直接用，但是键盘就得占用一个全局程序的动作去自己做😂

我觉得要不就直接给“快捷键（动作）”用上鼠标的功能菜单（去掉那个发送快捷键的功能）
要不就给鼠标手势的动作增加一个分配快捷键的功能，相当于把鼠标手势的那个动作菜单当成一个“小动作”来看待

![image](https://user-images.githubusercontent.com/36830343/210157966-aca97e91-8aec-4c42-adee-5d934b355a3f.png)

**Comment by cuiliang** [comment]
快捷键功能设计的比较早，数据结构不支持存储触发动作以外的功能，后期重构时再考虑了。
