### ISSUE TITLE
左键辅助的显示提示bug

### ISSUE THREAD

**Issue by eamooooon** [cuiliang/QuickPadCn#1834]
在左键辅助上设置了快捷的复制粘贴 并且会有显示提示
平时当我只用一块屏幕时 显示功能正常
今天我用笔记本和外接屏两块屏幕时 发现没有显示提示
且试了很多次都没有

**Comment by cuiliang** [comment]
我这里3个屏幕目前没有发现异常。 
有完成复制么？ 如果也没有复制，检查一下黑名单里的全屏禁用，取消一下。
如果有复制，只是没有显示提示，再核对一下设置。
如果设置没问题：
试试重启一下quicker，如果还不行，可以试试这个动作，看看能否正常显示提示：
https://getquicker.net/Sharedaction?code=44a7c5a8-48ba-4c11-c18b-08daef64fc0b

**Comment by eamooooon** [comment]
重启了之后可以了 我刚刚先用双屏发现没显示 再改成单屏发现有显示 就以为是bug了

**Comment by cuiliang** [comment]
可以升级到最新版本，https://getquicker.net/Help/Versions 
增加了一个自动检测屏幕变化后更新位置的功能。
