### ISSUE TITLE
其他软件中的发送文本和模拟按键动作，经常出现发送的文本串先后顺序错乱或丢失

### ISSUE THREAD

**Issue by gust-a11y** [cuiliang/QuickPadCn#1835]
**描述BUG**
对bug的清晰简洁描述。
创建其他软件中的发送文本和模拟按键动作，经常出现发送的文本串先后顺序错乱或丢失。
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10专业版
 - Quicker版本：1.36.13

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能是输入法影响，试试关掉输入法看看能不能复现。
也可以尝试这里的方法 https://getquicker.net/KC/Kb/Article/1045

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
