### ISSUE TITLE
quicker内置搜索命令已一旦使用整个软件就卡

### ISSUE THREAD

**Issue by smlhd1993** [cuiliang/QuickPadCn#1836]
**描述BUG**
quicker内置搜索命令已一旦使用整个软件就卡，需要重新启动软件，但是搜索命令依旧不能使用。

**重现步骤**
1.
2.

**相关截图**
![image](https://user-images.githubusercontent.com/30895092/211202562-65468575-120c-422d-ad10-2abe395c75c7.png)

**环境信息:**
 - 操作系统版本：windows
 - Quicker版本：1.36.22

**附加信息**

**Comment by cuiliang** [comment]
似乎有某个/类文件的缩略图不能正常返回造成的。
有使用什么在资源管理器里预览pdf文件的功能么？ 可以关掉试试

**Comment by cuiliang** [comment]
也可以在这里彻底关掉缩略图显示试试：
![image](https://user-images.githubusercontent.com/1972649/211202993-a2578a66-03da-4ced-a2f8-9b3debb99d25.png)

**Comment by smlhd1993** [comment]
崔总晚安啊，取消选择缩略图后就可以使用了。
应该我今天做了一个设置，就是在acrobat中勾选了这个选项。应该是这个导致的~
![Snipaste_2023-01-08_22-59-04](https://user-images.githubusercontent.com/30895092/211203382-b67de520-202d-438f-8dbd-317c39f7975c.png)
