### ISSUE TITLE
可能存在内存泄漏

### ISSUE THREAD

**Issue by ytf4425** [cuiliang/QuickPadCn#1837]
**描述BUG**
内存占用过大

**重现步骤**
复现方式未知，可能与 #1376 有关

**相关截图**

![image](https://user-images.githubusercontent.com/4819825/211205639-fa36c4e5-3347-4d0c-8343-753f65fae03d.png)

![QQ截图20230108233718](https://user-images.githubusercontent.com/4819825/211205467-011b4310-b769-4562-9a8c-93be91ec76b3.png)

**环境信息:**
 - 操作系统版本：Windows 11 22H2 22621.963
 - Quicker版本：1.34.30

**附加信息**

在任务管理器里看不出来，但是任务管理器性能页的已提交中内存占用非常高，重启 Quicker 之后已提交能减少 Process Hacker 中所对应的内存占用量。

使用过的动作仅 截图、截图OCR、文本/截图翻译（沙拉查词）

**Comment by cuiliang** [comment]
如果方便的话，
1）软件和动作都升级到最新的版本。https://getquicker.net/Help/Versions
2）复现问题，创建一个进程转储文件，然后压缩一下传个网盘，我这里找工具分析看看。
![image](https://user-images.githubusercontent.com/1972649/211224387-6fec0539-6c61-453c-a1dd-0ec61f389feb.png)

**Comment by ytf4425** [comment]
https://t.wss.ink/f/aifrsi88cqm 复制链接到浏览器打开
并且我发现只要打开一次quicker面板就能自动降回去到100多M的水平

**Comment by cuiliang** [comment]
这个看起来似乎也没有什么问题🤦‍♂️
![image](https://user-images.githubusercontent.com/1972649/219224139-18ff6847-087f-4b37-a3ea-71cd1239b718.png)

**Comment by ytf4425** [comment]
emmm但就是占用很大鸭
只要打开一次quicker面板就能自动降回去到100多M的水平，要不检查一下打开面板的时候是不是释放了什么资源？

**Comment by LECHIENG** [comment]
也有同样的问题，16G内存每次提示内存不足都是quicker进程引起的，下次我出问题了 也能提供转存储文件帮忙查看一下吗 谢谢

**Comment by cuiliang** [comment]
@LECHIENG 好的， 有后台持续运行的动作么？“提示内存不足都是quicker进程引起的” 这个是通过什么判断的呢

**Comment by ytf4425** [comment]
> @LECHIENG 好的， 有后台持续运行的动作么？“提示内存不足都是quicker进程引起的” 这个是通过什么判断的呢

我的情况是开机之后 Quicker 自动启动但我长期不使用（甚至没有点开过）。

**Comment by cuiliang** [comment]
@ytf4425 也没有设置自动启动动作么？
![image](https://user-images.githubusercontent.com/1972649/220027727-494f0fc3-036e-4637-a66b-9e1a38079828.png)

**Comment by ytf4425** [comment]
> @ytf4425 也没有设置自动启动动作么？ ![image](https://user-images.githubusercontent.com/1972649/220027727-494f0fc3-036e-4637-a66b-9e1a38079828.png)

无

**Comment by cuiliang** [comment]
整理issues
