### ISSUE TITLE
之前写的利用FlaUI操作窗口界面的动作，最近用不了。

### ISSUE THREAD

**Issue by smlhd1993** [cuiliang/QuickPadCn#1838]
**描述BUG**
崔总好，之前写的利用FlaUI操作窗口界面的动作，最近用不了。利用xpath的路径，左键单击，反馈结果没有问题，但是并没有单击动作。

**重现步骤**
测试结果没有问题，但是确实没有双击或者单击后的菜单出来。很久之前我这个动作还是可以用的，最近一个多月不能用。

**相关截图**
![Snipaste_2023-01-09_13-31-26](https://user-images.githubusercontent.com/30895092/211246125-5b195cb7-5dae-466f-b806-48c915e903ca.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
窗口句柄是写死的么？ 窗口每次启动都是有新的句柄，不能使用一个固定的数字的。

**Comment by smlhd1993** [comment]
> 

不是写死的，我只是为了测试用了我测试窗口的定值。之前这个动作没有问题，是不是quicker内置FlaUI被更改过。

**Comment by cuiliang** [comment]
更新不应该影响功能。 重新获取一下xpath试试？ 这个软件有下载的地方么？

**Comment by smlhd1993** [comment]
https://cloud.tsinghua.edu.cn/f/53abb4fcab7941158878/
这个软件比较原生态~~~

**Comment by cuiliang** [comment]
这里为什么使用”双击“呢？ 我试了一下这几个都可以打开替换对话框
![image](https://user-images.githubusercontent.com/1972649/211252994-531793ce-7d7f-473e-8265-18f07c4cd1b5.png)

**Comment by smlhd1993** [comment]
我之前用的单击，我以为力度不够，截图的时候刚改成双击~😀我再试试吧，难道我最近改用了双屏，就有问题？不知道啥原因~

**Comment by smlhd1993** [comment]
崔总您看，在我的电脑上根本选不到button12.
![bandicam 2023-01-09 14-51-49-989~2](https://user-images.githubusercontent.com/30895092/211254993-87818622-5514-435f-a8e2-ccae8329f27f.gif)

**Comment by cuiliang** [comment]
电脑分辨率/文字缩放之类的参数修改过么？  我这里是可以正常选的，win11， 缩放150%
![image](https://user-images.githubusercontent.com/1972649/211255687-b082ad63-2542-476f-8f1d-d2f912106de3.png)

**Comment by smlhd1993** [comment]
我这是2*4k的高分屏，可能是这个的问题吧，我回家的时候用这个动作是没有问题的，一来办公室就不行~~~
![image](https://user-images.githubusercontent.com/30895092/211256006-18cefcd5-2288-49b7-8c9e-2b8100e42515.png)

**Comment by cuiliang** [comment]
一共有几个屏幕？这个兼容性有做过什么设置没？ 
![image](https://user-images.githubusercontent.com/1972649/211256494-5334ca85-9f3d-4670-92ea-209ede5ae2f8.png)

**Comment by smlhd1993** [comment]
一共2个 4k的屏幕，没有做过设置~

**Comment by cuiliang** [comment]
看起来没有什么特别异常的地方😂 win10 版本是多少？ 可以等有空的时候把分辨率改到100%，看看能不能选到按钮

**Comment by smlhd1993** [comment]
好的。感谢崔总的解答。

**Comment by smlhd1993** [comment]
已解决

**Comment by cuiliang** [comment]
@smlhd1993 怎么解决的？ 是修改分辨率后正常了么？

**Comment by smlhd1993** [comment]
> @smlhd1993 怎么解决的？ 是修改分辨率后正常了么？
正常屏幕下选择/ToolBar/Button[12]，高分屏幕下冒出来一个/ToolBar/Button[24]就可以了。不知道为啥~凑活用吧，先。
