### ISSUE TITLE
在功能快捷键设置页面中，增加轮盘菜单的快捷键

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1839]
![image](https://user-images.githubusercontent.com/36830343/212285436-dbd60629-7751-4475-91b1-bf16181b9702.png)

希望在这里增加打开轮盘菜单的快捷键
用触控屏的时候希望用触控板打开轮盘菜单，发现轮盘菜单没有URI也没有快捷键，只能创建一个组合动作然后分配快捷键或者调用URI，挺麻烦的

**Comment by cuiliang** [comment]
每个功能都可能有人会用到，不可能都添加快捷键，太多了。
做个动作运行这个命令，quicker://settings:CircleMenuManagePage
