### ISSUE TITLE
自定义窗口中，通过C#运行子程序异常卡顿

### ISSUE THREAD

**Issue by mdzz2048** [cuiliang/QuickPadCn#1840]
**描述BUG**
希望可以用自定义窗口实现点击按钮截图等功能，在实际调用子程序时发现使用 C# 代码调用会导致程序卡死，用“事件”调用不存在该问题。

**重现步骤**
以下为最小化的复现步骤：
1. 使用自定义窗口默认 XAML
![image](https://user-images.githubusercontent.com/86549958/213748675-2ecc722e-9ca0-4001-b80a-2e4b06ff810b.png)

3. 在自定义窗口调用一个无需输入参数的子程序“我不理解”
![image](https://user-images.githubusercontent.com/86549958/213747574-22d4d198-5c18-439f-8714-b1fa0b320c53.png)

4. 子程序内包含“屏幕截图”模块
![](https://files.getquicker.net/_sitefiles/kc/kb/2023/01/20/235927_412835_mceclip1.png)

5. 点击按钮后程序卡死
[视频链接](https://mdzz2048.oss-cn-hangzhou.aliyuncs.com/Y7000P202301210001726.mp4)

**环境信息:**
 - 操作系统版本：
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎8/‎4
操作系统内部版本	19044.2486
 - Quicker版本：
1.36.22

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
UI 线程死锁了。 
试一下用Task.Run(()=>{....}); 包围一下。

**Comment by mdzz2048** [comment]
包围后正常
