### ISSUE TITLE
玩星际争霸2 轮盘不够用

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1841]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
在国服星际争霸2关服之前赶紧玩了好些把，之前没免费的时候买的，花了不少钱。
要考虑的方面太多再+个 快捷键太多，就算玩的稍微多了 记得这些快捷键 但是还是很影响操作。矿够多但是补兵速度跟不上，打个人机难度稍微高点我就输！
不同种族对应的快捷键不同。使用悬浮不行，不够快，使用轮盘减少键盘操作之后，玩星际争霸2轻松了很多很多
之前玩特别容易累！坚持玩了没几个月就弃了很久，中间看了好些视频又陆续尝试了一些次还是弃了，太累了=折腾自己，一直输
拖拉了好些天，今天总算提交了反馈
目前主要用轮盘+少量的悬浮动作来操作神族，其他2个种族体验过但是3种不同的快捷方式方案靠人记忆很容易出现冲突、混乱
之前想尝试下 体验下决策人工智能，下载那个包之后发现显卡最低要求1060，我的1050的不行
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
使用神族轮盘方案1，虫族轮盘2，人族轮盘3
发现这个轮盘有3层，但是第3层怎么从来没出现过，是被什么禁用了或者什么设置没打开？
就算第3层轮盘可以用也没用，轮盘只够1个种族
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20230123210458](https://user-images.githubusercontent.com/44609485/214046787-c2e5f88f-1852-4f51-b4ed-15022697b452.png)

**Comment by Clouder0** [comment]
第三层是滑出轮盘的，比如你这图里设置，右键一直上划就会触发「基地间切换」。

**Comment by cuiliang** [comment]
触发额外的轮盘菜单：https://getquicker.net/kc/manual/doc/circle-menu#bwi3X
