### ISSUE TITLE
从Python中返回列表变量导致程序崩溃退出

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1842]
使用的是最新的快速通道，Python是3.10，如果从Python代码中返回列表变量，运行的时候会在几秒钟后鼠标移动卡顿，最后程序崩溃退出

如图，从Python中返回字符串列表，如果返回到quicker的列表类型中，就会出现该情况
如果返回到字符串变量中，就不会出问题
如果返回空列表到列表变量中，也不会出问题

![image](https://user-images.githubusercontent.com/36830343/215266549-ea53bd00-5d11-4b26-8c80-149ec3d2ffa1.png)

`quicker.context.SetVarValue('files', ['1667318865', '1667376447', '1667386381', '1667393008', '1674811731', '1674813111', '1674829211', '1674905505'])`
如果写成`quicker.context.SetVarValue('files', [])`这样一个空列表就不会有问题

**Comment by cuiliang** [comment]
这个是底层库的问题，没有什么办法，建议序列化成json之后传回再根据需要解析。

**Comment by ilcpm** [comment]
好的，我以为这么简单的结构应该不会出问题来着，希望可以在帮助文档上写一下，找bug找了半天😂
