### ISSUE TITLE
[Bug] 中英文状态在 Quicker 下识别有问题

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#1843]
#### 环境

- Windows 11 最新
- Rime 输入法（小狼亳）
  - 正常会被识别为中文
- 美式键盘
  - 正常会被识别为英文
- Quicker 快速通道最新版

#### 问题

“获取输入法状态”这个模块中的“是否为中文状态”功能，当焦点在 Quicker 上时，会识别不到正确输入法状态。焦点在其他软件上时正常。

#### 表现

无论目前是 Rime 输入法还是美式键盘，识别结果要么总是为英文，要么总是为中文。

**Comment by cuiliang** [comment]
感谢反馈。 这个问题有点难，等有空再深入研究一下。

**Comment by cuiliang** [comment]
1.42.6 測試正常，注意不能使用懸浮動作，會搶焦點影響輸入法狀態，使用快捷鍵等方式觸發。

![test_小狼毫測試](https://github.com/cuiliang/Quicker/assets/1972649/410f4324-12cd-4725-85f4-b168bdc34fcf)

**Comment by Immortal-Sty** [comment]
好像还是不行，试了一下，能切换小狼毫的中英文状态，但识别中英文还是有点问题。

https://github.com/cuiliang/Quicker/assets/94347641/8cc8a8a7-2b1e-4814-84dc-c7fc94209eef
