### ISSUE TITLE
同步冲突的提示能不能显示对应的动作的名称

### ISSUE THREAD

**Issue by hamson1026** [cuiliang/QuickPadCn#1844]
**需求描述**
每次同步出现冲突的时候，提示页只有动作id，很难查找对应的动作，希望能够加上对应的名称，方便查看。

 **其他上下文**

![snipaste_20230205_091937](https://user-images.githubusercontent.com/67315180/216796658-6e4429cb-9c5f-411d-b73d-a083cf5e6852.png)

**Comment by cuiliang** [comment]
目前的设计方式是按整页同步的，所以出现冲突的时候没法判断具体动作。
如果有大量编辑，可以先将近期编辑过的动作导出以便在必要的时候恢复。
