### ISSUE TITLE
[bug]开启quicker时，鼠标在 intellij idea 中会变得卡顿

### ISSUE THREAD

**Issue by DawnHuoYu** [cuiliang/QuickPadCn#1845]
**描述BUG**
开启quicker时，鼠标在 intellij idea 中会变得卡顿

**重现步骤**
1.开启quicker
2.打开 intellij idea 写代码
3.一段时间后，鼠标变得明显卡顿；关闭 quicker 后立马恢复正常

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.36.22
 - intellij idea 2021.2.2

**附加信息**
一段时间后鼠标出现卡顿，但关闭 quicker 后立马恢复正常，因此确定是 quicker 的问题。一定会出现卡顿的问题，不是偶发

**Comment by cuiliang** [comment]
看一下任务管理器，里面的内存和cpu占用有没有啥异常。
如果系统CPU/内存压力比较大，可能会出现类似现象。
