### ISSUE TITLE
建议轮盘区分主机

### ISSUE THREAD

**Issue by Joseph4tec** [cuiliang/QuickPadCn#1846]
**需求描述**
如题，建议轮盘也能区分主机。
（或更进一层，先区分使用环境，一个使用环境可对应不同主机。）

**描述你想要的解决方案**
看到讨论里已经有类似的多个话题了，但都被拒绝了。
但轮盘比菜单其实更方便，所以希望轮盘也能像菜单一样能针对不同主机进行设置。

**描述您考虑过的替代方案**
1. 功能页：但功能页的触发没有轮盘方便；
2. 组合动作：不符合要求。因为工作和个人电脑上要实现的是不同的操作，而不是同一个操作路径不同的问题。
PS：我所有的软件配置都分两套，工作一套、个人一套。包括VIM、GIT配置都是区分的。

 **其他上下文**
数据不和服务器同步也可以。但强制同步的话也就算了。

**Comment by cuiliang** [comment]
如果差别比较大，通过2个账号可以比较容易解决这个问题。

**Comment by Joseph4tec** [comment]
补充：我工作和个人电脑分辨率不同，会导致轮盘大小有区别，触发行程不一样……不过这不影响核心功能，不是多大的问题了。

回复，2个帐号都购买专业版的话，确实有点吃力。

**Comment by Joseph4tec** [comment]
感谢作者的软件 和 快速的回复！
