### ISSUE TITLE
json提取文本(时间格式)会自动变格式

### ISSUE THREAD

**Issue by mingjinglyh** [cuiliang/QuickPadCn#1847]
json提取文本内容，**"纪念日期":"1989-09-11T00:00:00+09:00"**
提取后变成了 1989-09-10 23:00:00
提取的变量类型为文本
如何在提取时保持原有内容和原有格式

**相关截图**
![Snipaste_2023-02-09_22-00-41](https://user-images.githubusercontent.com/45187089/217834401-0b173dbe-b634-4a8c-8c88-53c8fd213fd8.jpg)

**环境信息:**
 - win10 
 - Quicker版本：1.35

**Comment by cuiliang** [comment]
底层库会自动把这个内容作为时间处理，得到本地时间。
参考：https://stackoverflow.com/questions/11856694/json-net-disable-the-deserialization-on-datetime 
我试试后面版本增加一个选项。

**Comment by cuiliang** [comment]
后来增加了选项。
![image](https://github.com/cuiliang/Quicker/assets/1972649/049d2584-8e5c-49ee-90a5-3269d8375769)
