### ISSUE TITLE
quicker暂停弹出后，搜索框依然会被唤出

### ISSUE THREAD

**Issue by zlxuan** [cuiliang/QuickPadCn#1849]
**需求描述**
希望设置quicker暂停后，搜索框也禁了，否则打游戏时容易误触切屏。

**描述你想要的解决方案**
希望设置quicker暂停后，搜索框也禁了，或则做个单独的暂停选项。

 **其他上下文**
![Snipaste_2023-02-12_13-05-13](https://user-images.githubusercontent.com/58515531/218294022-d6d3eef6-2667-498a-9ccf-c053d4e5f795.png)

**Comment by cuiliang** [comment]
暂停只针对鼠标触发。如果快捷键也要暂停，修改这里的选项
![image](https://user-images.githubusercontent.com/1972649/218296294-6d3954d5-d78c-45e0-9c96-dd6059fc4354.png)

**Comment by zlxuan** [comment]
> 暂停只针对鼠标触发。如果快捷键也要暂停，修改这里的选项 ![image](https://user-images.githubusercontent.com/1972649/218296294-6d3954d5-d78c-45e0-9c96-dd6059fc4354.png)

哦哦，感谢，是我功能理解不到位了，哈哈

**Comment by cuiliang** [comment]
主要是涉及的情况太多了，很难用简单的规则一刀切，确实有点麻烦
