### ISSUE TITLE
通过quicker打开的txt文档保存时会导致整个电脑卡死，而单独打开txt文档则没事，win11的电脑

### ISSUE THREAD

**Issue by wangshilei1105** [cuiliang/QuickPadCn#1851]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能是搜狗输入法造成的，
参考这里试一下：https://getquicker.net/QA/Question/14272
