### ISSUE TITLE
用量统计=能否统计动作总个数或者使用分布？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1852]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
粘贴动作到轮盘这个功能出现之前重复安装了不少动作
总使用次数270987
常用动作或操作动作使用次数操作：轮盘菜单118459
左键30933
操作：悬浮按钮26961
以前安装了好些，最近查看使用总次数发现使用非常集中，很不分布式
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
能否从网页查看然后多选批量安装？动作面板查看说明那个空间太小了！
网页复制粘贴到面板或者面板里面拖动都没有网页多选好
经常想到不同的词语，然后搜索+批量安装动作进行尝试，网页查看 安装动作要点好多次复制粘贴到面板
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20230215234405](https://user-images.githubusercontent.com/44609485/219077334-c0063185-13ac-4097-89ca-29c941b5bb45.png)

![天若_20230215234429](https://user-images.githubusercontent.com/44609485/219077462-368ef993-73db-4d8e-84d3-0e942cf5555c.png)

**Comment by cuiliang** [comment]
无法实现哦，很多位置没有id也就没法统计。
