### ISSUE TITLE
最外侧轮盘没有显示

### ISSUE THREAD

**Issue by mingenmomo** [cuiliang/QuickPadCn#1854]
**轮盘操作时，最外侧轮盘没有显示**
用鼠标触发轮盘，但是最外层的轮盘菜单没有显示，也没有选择最外层可以显示。

**重现步骤**
1.按动鼠标触发按键触发轮盘菜单
2.出现轮盘菜单，但不显示最外层菜单

**相关截图**
![image](https://user-images.githubusercontent.com/82462180/219604990-bda2a9e9-177b-4e4c-a353-0fda5a5973b6.png)
**环境信息:**
 - 操作系统版本：Windows 10 专业版 22H2
 - Quicker版本：1.36.32

**附加信息**
从免费版升级到专业版，并且进行了一次更新

**Comment by cuiliang** [comment]
本身就是不显示的。请参考轮盘文档：https://getquicker.net/kc/manual/doc/circle-menu
