### ISSUE TITLE
切换日语输入法之后，无法按ctrl键调出quicker主界面

### ISSUE THREAD

**Issue by 425833137** [cuiliang/QuickPadCn#1855]
**描述BUG**
原本可以用ctrl键调出quicker的主界面，但是电脑切换成微软自带的日语输入法之后，就不能了，哪怕再切换回中文输入法也不行，除非重启电脑。

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.36.32

**Comment by cuiliang** [comment]
我在win11上装了一个，似乎没有影响。Win10暂时没有条件测试。
![CTRL弹出](https://user-images.githubusercontent.com/1972649/219869473-f09e3c51-2f96-4174-913e-ef0349bc09aa.gif)

**Comment by cuiliang** [comment]
在Win10下也没能复现这个问题。
![image](https://github.com/cuiliang/Quicker/assets/1972649/4e7f7976-55d0-46d5-bdec-d670b1439e9f)
