### ISSUE TITLE
用量统计=左键30933 怎么好像没变？

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1856]
**描述BUG**
对bug的清晰简洁描述。
左键30933之前记录的就是这个数字，怎么几十天过去了还是这个数字？
quicker软件是什么时候正式发布的？之前网页找了好些次没找到，我要计算下平均每天用了多少次
记录次数功能是什么时候出的？可能没功能之前的点击都没有记录
左键点击次数太多+时间碎片化有点严重，这个任务没搞完就切换到另外的任务，窗口换来换去=很不专注搞的大脑很容易累，目前尽量多使用滴答清单番茄钟
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/44609485/220101569-67024e64-c5d2-4ef2-b5dc-21fbdd42197b.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。
它可以让你在windows上自定义一个包含多操作的动作，为常用操作建立捷径，仅仅只有10M大小，拥有超过8000个共享动作，集翻译、查询跟下载为一体的应用，下载量超1.2亿次。
https://getquicker.net  现在首页又没有这个下载量了。
不好计算动作总量，无法计算每个动作的平均量=注册时间    2018-12-25→2023年02月08日=1506
总使用次数=269534     269534/1506=178.97
178.97/12=14.91   178.97/10=17.9   平均每天每小时=10→20次
通过非面板方式触发动作时，操作方式与动作本身会分别计数。
常用动作或操作=动作、使用次数操作2023年02月08日
轮盘菜单117722
左键30933
悬浮按钮26385
轮盘菜单起作用了，远远大于其他2个之和。
---
2023年02月20日=总使用次数271780=50个月=记录次数功能是什么时候出的？可能没功能之前的点击都没有记录
通过正主非面板方式触发动作时，操作方式与动作本身会分别计数。
常用动作或操作
轮盘菜单118899
左键30933 怎么好像没变？
悬浮按钮27173
移动到10690
8到20号=13天=
轮盘菜单=118899-117722=1177   1177/13=90.54次/天
悬浮按钮=27173-26385=788    788/13=60.62次/天

**Comment by cuiliang** [comment]
检查一下数据同步正常么？ 这个通常每天报告一次，如果网络请求有问题可能就会没有数据。 另外统计本身也不是很精确，仅供参考使用。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
