### ISSUE TITLE
文本OCR增加识别为表格

### ISSUE THREAD

**Issue by tanziow** [cuiliang/QuickPadCn#1857]
**需求描述**
文本OCR增加识别为表格

**描述你想要的解决方案**
文本OCR增加识别为表格

**描述您考虑过的替代方案**
文本OCR增加识别为表格

 **其他上下文**
![image](https://user-images.githubusercontent.com/47211568/220525523-00840986-6499-4773-8886-e5a5e59e267b.png)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 新版已增加
https://getquicker.net/Sharedaction?code=3fc97b7e-7be1-4a23-3d64-08db3e27302e
