### ISSUE TITLE
希望排序文件列表的功能支持文件夹

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1858]
这些排序文件列表对文件夹无效
![image](https://user-images.githubusercontent.com/48246272/220831653-027d08a8-f2b8-4a42-96b7-cd9c964313d1.png)

**Comment by cuiliang** [comment]
文件夹没有尺寸信息的，要遍历所有文件才能得到。

**Comment by ghost** [comment]
那能支持时间的排序吗？

**Comment by cuiliang** [comment]
可以用表达式，实现各种方式比较灵活：

```c#
$= {listFilesPath}
	.Select(x => new DirectoryInfo(x))
	.OrderBy(x => x.LastWriteTime)
	.Select(x =>x.FullName)
	.ToList();
```

**Comment by ghost** [comment]
感谢，这解决了我的问题。
不懂计算机语言果然还是不方便……
![心情简单](https://user-images.githubusercontent.com/48246272/220898252-7cf8b246-4437-4a67-8950-bb91a7a038bc.jpg)
