### ISSUE TITLE
“提示消息”后立刻休眠电脑，重新打开电脑之后“提示”的“界面框架”还在

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1859]
很奇葩的触发方式

我做了个动作，动作的最后一步是通过命令行休眠电脑，休眠之前用“提示消息”功能弹出提示
就是说使用“提示消息”功能之后，立刻对电脑进行休眠
再次打开电脑之后，通过截图软件可以发现，“提示消息”功能留下的“界面框架”还在

下图是我的动作定义
![image](https://user-images.githubusercontent.com/36830343/220949829-e851c9b8-3e73-40b4-830c-2ed43da97850.png)

下图是休眠电脑之后再次打开电脑，通过截图软件可以发现“提示消息”功能残留的“框架”
![image](https://user-images.githubusercontent.com/36830343/220950187-973b5e6a-956e-4ce3-8d78-aa5a552b045b.png)

通过其他方式再次触发“提示消息”之后，这个残留的框架就消失了

**Comment by ilcpm** [comment]
注：最后一步“休眠电脑”使用的命令行命令是`shutdown /h`
![image](https://user-images.githubusercontent.com/36830343/220952358-4da1d12f-6556-4967-91a0-6887098eb8c5.png)

**Comment by cuiliang** [comment]
还没来得及隐藏系统就关掉了。 这个属于正常现象
