### ISSUE TITLE
弹出面板-鼠标方式 建议适配多宏健鼠标（eg. G903）

### ISSUE THREAD

**Issue by Indexeon** [cuiliang/QuickPadCn#1860]
**需求描述**
    使用G903，设置中 “鼠标方式” 【按下X1键、按下X2键】无法触发面板。
**描述你想要的解决方案**
   “鼠标方式”可以对热门多宏鼠标适配，如G903,G502等

**Comment by Indexeon** [comment]
现阶段如果需要同时启用“quiker面板”、“轮盘”、“鼠标手势”功能，  常见的“中间”与“长按右键”两个触发方式 无法满足  三个需要的功能。建议对使用者较多的鼠标适配对应宏键。

**Comment by cuiliang** [comment]
参考这里 https://getquicker.net/KC/Kb/Article/927 
在鼠标驱动里将侧键修改成windows的默认按键，quicker里才能识别到。

**Comment by Indexeon** [comment]
> 参考这里 https://getquicker.net/KC/Kb/Article/927 在鼠标驱动里将侧键修改成windows的默认按键，quicker里才能识别到。

嗯了解，另一个建议是可以增加宏键适配，比如【按下X1键、按下X2键……按下X8键】

**Comment by cuiliang** [comment]
除了鼠标自带驱动，其它软件是识别不到鼠标的自定义按键的。
