### ISSUE TITLE
希望提高截图操作的优先级

### ISSUE THREAD

**Issue by li1008611** [cuiliang/QuickPadCn#1861]
**需求描述**
quicker自带的截图和贴图，无法截出忽略护眼软件的效果，
Win+Shift+S就可以
这个有方法达到吗？

**描述您考虑过的替代方案**
提高截屏软件的优先级，或者运行截图之前禁掉护眼软件，之后再启动...

**Comment by cuiliang** [comment]
找一下护眼软件里有没有选项可以在截图的时候自动关闭。
参考这里：
https://support.techsmith.com/hc/en-us/articles/360027625811-Snagit-Windows-Yellow-Tint-in-Captures-from-f-lux

**Comment by li1008611** [comment]
＞︿＜，看来是我的护眼软件太low了，我换个别的试试



在 2023-02-24 17:58:56，"CuiLiang" ***@***.***> 写道：

找一下护眼软件里有没有选项可以在截图的时候自动关闭。
参考这里：
https://support.techsmith.com/hc/en-us/articles/360027625811-Snagit-Windows-Yellow-Tint-in-Captures-from-f-lux

**Comment by li1008611** [comment]
谢谢大佬



在 2023-02-24 17:58:56，"CuiLiang" ***@***.***> 写道：

找一下护眼软件里有没有选项可以在截图的时候自动关闭。
参考这里：
https://support.techsmith.com/hc/en-us/articles/360027625811-Snagit-Windows-Yellow-Tint-in-Captures-from-f-lux
