### ISSUE TITLE
提问：一个账号两台电脑数据不同步怎么操作

### ISSUE THREAD

**Issue by Ludovic-777** [cuiliang/QuickPadCn#1864]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
我有一个问题，就是我现在在两台电脑上用同一个账号登录了quicker，由于设置不同，所以我在两台电脑想要的快捷键（打开文件夹等操作）是不同的，但我在其中一台电脑删除我不需要的快捷键时，另外一台上的也随之删除了，这个怎么解决？

**Comment by cuiliang** [comment]
可以参考这里 https://getquicker.net/KC/Manual/Doc/data-sync#ThGPb 
如果数据都不要相同，请使用两个账号。

**Comment by SaintChangeTheWorld** [comment]
那就两台电脑的文件安装路径保持一致
