### ISSUE TITLE
win11更新后打不开快捷txt

### ISSUE THREAD

**Issue by dltbb** [cuiliang/QuickPadCn#1865]
一直正常使用，中间只有更新win11的操作，源文件可以打开，但是quicker快捷打开会找不到文件，其他类型文件快捷打开正常。
![Quicker_20230302_095702](https://user-images.githubusercontent.com/33507189/222311254-8d0a02bf-7b3b-4cfc-80b8-ad1b01fab29a.png)

**Comment by cuiliang** [comment]
Windows 11 更新导致的，正在研究...

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions hi，更新了一版测试看看。

**Comment by dltbb** [comment]
![tmp8B4F](https://user-images.githubusercontent.com/33507189/222611310-45fa5da0-dbf2-468c-a2c3-a9ba225ab0e9.png)
![Quicker版本更新提示 2023_3_3 9_48_30](https://user-images.githubusercontent.com/33507189/222611327-b3a1e338-9c4d-4b45-afad-3b5ec507b3e7.png)
更新了依旧不行

**Comment by cuiliang** [comment]
动作是怎么样定义的？截图看下 @dltbb

**Comment by dltbb** [comment]
![tmp2A63](https://user-images.githubusercontent.com/33507189/222612434-11f4a6ab-719e-44d1-9a02-4a66644b1d95.png)

**Comment by cuiliang** [comment]
@dltbb 确实，我再处理一下。 目前这样修改：
文件路径，放到“参数”这个后面，路径/命令里改为 notepad

**Comment by dltbb** [comment]
好的，多谢

**Comment by dltbb** [comment]
现在可以了

**Comment by xinxin-169** [comment]
我也是

**Comment by cuiliang** [comment]
@1459244936 更新quicker到最新版
