### ISSUE TITLE
无法删除图标

### ISSUE THREAD

**Issue by SaintChangeTheWorld** [cuiliang/QuickPadCn#1866]
新建动作的时候会自动上传图标，上传后就无法删除了 同样的图标太多

**Comment by cuiliang** [comment]
所有上传的图标都是不会删除文件的，不然分享的动作就有可能图标没法显示，只能从那个窗口里删除条目。

专业版，图标上右键可以删除。
免费版限制上传50个，所以是不能删除的，删除了就没法限制了。

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/222399279-35210353-bfc0-4480-a771-a47652a4d229.png)
如果是专业版，也可以不用管这里，直接存在目录里，需要的时候复制文件往动作上粘贴就可以了。

**Comment by SaintChangeTheWorld** [comment]
哦，是这个样子啊。
图标里全是浏览器。
也是啊只要用户50个图标够用，能删除相当于没限制。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月2日 18:13
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cuiliang/Quicker] 无法删除图标 (Issue #1866)


所有上传的图标都是不会删除文件的，不然分享的动作就有可能图标没法显示，只能从那个窗口里删除条目。

专业版，图标上右键可以删除。
免费版限制上传50个，所以是不能删除的，删除了就没法限制了。

―

**Comment by SUGARYeUNGG** [comment]
能不能少收点费用把这个删除图标的功能给打开，
