### ISSUE TITLE
临时禁用轮盘菜单

### ISSUE THREAD

**Issue by WsRfi** [cuiliang/QuickPadCn#1867]
我是用鼠标右键来触发轮盘菜单的。在Obsidian的白板或者Xmind中，鼠标右键通常用来移动画布，但我又希望使用轮盘菜单中的复制、粘贴等动作。
希望能在场景与动作管理界面增加设置项，在针对某个应用的轮盘菜单设置中增设自定义按键来临时禁用与启用轮盘菜单。

**Comment by cuiliang** [comment]
设置一个暂停和恢复quicker的快捷键。 或者试一下附加ctrl、shift、alt的时候，画布能不能移动。
![image](https://user-images.githubusercontent.com/1972649/222447235-de7727a2-9e95-48ee-9ccf-cac02792200c.png)

**Comment by WsRfi** [comment]
> 设置一个暂停和恢复quicker的快捷键。 或者试一下附加ctrl、shift、alt的时候，画布能不能移动。 ![image](https://user-images.githubusercontent.com/1972649/222447235-de7727a2-9e95-48ee-9ccf-cac02792200c.png)

这样是可以。但我想设置成鼠标侧键，感觉这样更方便，不知道好不好实现？

**Comment by cuiliang** [comment]
用鼠标键触发暂停是可以的，但是暂停之后因为没有鼠标挂钩了没法恢复。 还有一个办法是双击托盘图标。

**Comment by WsRfi** [comment]
那就不把Quicker整个暂停掉，只禁用轮盘嘛，现在也有禁用这个设置，感觉只是加个快捷键的事，可能我想得简单了。

**Comment by cuiliang** [comment]
确实想简单了😁
