### ISSUE TITLE
两块不同尺寸的显示器上，quicker外观会有bug

### ISSUE THREAD

**Issue by tanziow** [cuiliang/QuickPadCn#1868]
**描述BUG**
两块不同尺寸的显示器上，quicker外观会有bug

**重现步骤**
1.在2k屏调出quicker
2.在4k屏调出quicker

**相关截图**
![tmpB016](https://user-images.githubusercontent.com/47211568/222585104-a1abcc33-2520-4759-a13f-58e5505634fa.png)
![tmp18E3](https://user-images.githubusercontent.com/47211568/222585229-23dc89a2-3b02-44ac-b40c-4884fe169de0.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
外观代码：456e14a2-a215-429a-70f8-08db1b743a7b

**Comment by tanziow** [comment]
模糊模式是毛玻璃的时候就会出现

**Comment by cuiliang** [comment]
重启quicker之后仍然有这个现象么？windows 详细版本是多少？
两个屏幕的分辨率和缩放比例设置的多少？

**Comment by tanziow** [comment]
> 重启更快之后仍然有这个现象么？Windows 详细版本是多少？ 两个屏幕的分辨率和缩放比例设置的多少？

 很好，重启后问题得到了解决
