### ISSUE TITLE
场景进程不支持不区分大小写

### ISSUE THREAD

**Issue by Vstory** [cuiliang/QuickPadCn#1869]
**描述BUG**
原文件名称：BitComet.exe、BitComet_x64.exe
在场景进程里添加进程为 BitComet.exe 场景，之后在关联其他程序里填上 BitComet_x64.exe。

运行 BitComet_x64.exe 不会触发 BitComet.exe 进程场景，且 BitComet.exe -> bitcomet.exe 变为了小写。
尝试手动填入 BitComet_x64.exe 该场景不会触发。必须将 BitComet_x64.exe -> bitcomet_x64.exe 才可以。

**相关截图**
![image](https://user-images.githubusercontent.com/20795557/222959433-021a2e7f-62e0-40b4-a179-99f0a62248c9.png)

**环境信息:**
 - 操作系统版本：Windows 版本: 22H2 (OS 内部版本 22621.1344)
 - Quicker版本：1.37.9

**预期目标**
1. 不动文件名，即 BitComet_x64.exe -> BitComet_x64.exe ，正常触发。
2. 自动转化文件名，即 BitComet_x64.exe -> bitcomet_x64.exe，确保正常触发。

**Comment by cuiliang** [comment]
感谢反馈，我等检查一下。 可以点按住右边识别窗口的按钮拖动到目标窗口，也可以自动填入程序名。

**Comment by Vstory** [comment]
> 感谢反馈，我等检查一下。 可以点按住右边识别窗口的按钮拖动到目标窗口，也可以自动填入程序名。

这个我知道，这个是需要软件运行中，且有窗口的时候。我填写时是直接编辑的，没必要特地运行程序选择窗口。

**Comment by cuiliang** [comment]
已修复，待1.38.10更新。
