### ISSUE TITLE
更新quick后，截图OCR、成对符号等动作不能使用了。

### ISSUE THREAD

**Issue by 407733489** [cuiliang/QuickPadCn#1871]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
![4SM81_@2G_Q~@59OU@5SO6](https://user-images.githubusercontent.com/1972649/223931653-89193d44-41ca-4874-8732-2cd37865de3c.jpg)
