### ISSUE TITLE
多张本地图片批量识别为表格没反映

### ISSUE THREAD

**Issue by lovecomic** [cuiliang/QuickPadCn#1872]
本地图片批量识别为表格，有问题。。一次选了7张图片，显示正在识别7张图片，然后就没反映了！
一开始以为是单张图片尺寸太大了，将图片尺寸改小后，还是选7张，只成功识别出了1张！

**重现步骤**
1.截图ORC-切换识别-本地图片-表格
2.上传7张表格图片，显示正在识别
3、然后没有任何反映或提示

**相关截图**
![image](https://user-images.githubusercontent.com/25029053/224658955-cbafd873-e3fe-400f-9542-4cb9e49eff46.png)

**环境信息:**
 - 操作系统版本：Windows 10 家庭版 21H2
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不好意思哦，不支持这种组合。 因为动作里很难对每种做很特殊的设置界面，这里会有一些歧义。
