### ISSUE TITLE
设置了自动返回第一页，但未能生效 

### ISSUE THREAD

**Issue by faxble** [cuiliang/QuickPadCn#1873]
**描述BUG**
无论是全局还是通用面板，我均设置了自动返回第一页，但是实际中点击非首页的应用后仍然停留在当前页

**重现步骤**
无论是全局还是通用面板，我均设置了自动返回第一页，但是实际中点击非首页的应用后仍然停留在当前页

**相关截图**
![image](https://user-images.githubusercontent.com/51730117/225490413-68a85f41-b5eb-4bd9-b694-b05905eb6241.png)

**环境信息:**
Windows 10 专业版 22H2
Quicker 1.36.32

**Comment by cuiliang** [comment]
方便录个屏么？或加qq 197906 向日葵远程一下。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
