### ISSUE TITLE
左键辅助与获取选中文本组件

### ISSUE THREAD

**Issue by zlxuan** [cuiliang/QuickPadCn#1874]
**描述BUG**
本人一个工作网站，使用左键辅助无法复制文本，但使用动作组件中的“获取选中文本“组件却可以获取到文本，我不清楚这两者功能间用到的技术是不是不一样，就来反馈一下。

**重现步骤**
1.左键+右键无法复制选中文本；
2.”获取文本组件“可以获取到文本；

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
版本	Windows 11 家庭中文版 Insider Preview
版本	22H2
安装日期	‎2023/‎3/‎9
操作系统版本	25314.1010
体验	Windows Feature Experience Pack 1000.25314.1010.0

**Comment by cuiliang** [comment]
在其它软件中正常么？ 比如记事本
可能有这样的几个因素：
1. 左键是按下状态的
2. 获取剪贴板的等待超时时间有限制

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
