### ISSUE TITLE
键鼠控制-无法指定鼠标位置

### ISSUE THREAD

**Issue by sherehs** [cuiliang/QuickPadCn#1876]
我的设置意图是，想在CAD中，使用触控板方便的按住中键拖动图纸。使用的是左键辅助功能，我按照键鼠控制的格式，希望触发功能后鼠标不做任何移动。
但是无论我在“Mbutton,”后面留空，还是“-99999,-99999”，或者是屏幕上的某个位置比如“1200,800”，都无法改变触发后鼠标的位置，直接会默认到屏幕左上角的“0,0”位置。并且教程中按键后是需要三个参数的，实际输入“0,0,0”三个参数时会报格式错误。

我以为是教程文档过时了，但我又测试了输出了键鼠录屏操作的文本结果，发现和教程的参数格式一致。
本人水平有限不知道是我参数设置有问题还是bug
![image](https://user-images.githubusercontent.com/128406701/226406951-3e4c3d18-a2a9-4637-88e9-24ad029cb9c1.png)

**Comment by cuiliang** [comment]
格式类似这样：
```
202;	MD;	Middle,100,100,0;
100;	MV;	None,300,300,0;
202;	MU;	Middle,100,100,0;
```
托盘菜单里有一个录制工具，可以在那录制后查看数据

**Comment by sherehs** [comment]
感谢大大，是按键写错导致的，已经可以了T-T，感谢感谢！
