### ISSUE TITLE
任意窗口移动时卡顿，退出quicker后正常

### ISSUE THREAD

**Issue by joincomcn** [cuiliang/QuickPadCn#1877]
**描述BUG**
任意窗口移动时卡顿，漂移，退出quicker后正常
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
使用的windows版本有bug，可以在这里关闭背景模糊测试看看：
![image](https://user-images.githubusercontent.com/1972649/227678232-95577fa2-477f-47de-8a27-e85f7fafcf90.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
