### ISSUE TITLE
错误提示bug

### ISSUE THREAD

**Issue by AugustTuan** [cuiliang/QuickPadCn#1878]
**重现步骤**
1.自从我一个月前，设置快捷键时，设置了一个系统自带的快捷键，弹出这个警告以后。 我在设置里面后面无论做任何操作都会弹出这个警告，
2.即使我卸载重装也没有用，而且在我重新安装的一瞬间，就会弹出这个警告

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/37429029/227703263-94938a30-31ce-4887-b84d-54f133ba5fc1.png)

https://user-images.githubusercontent.com/37429029/227703422-58957be3-5cc2-4be9-9d12-d3ba51d9ef41.mp4

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：最新版

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
检查这里的设置，去掉一下：
![image](https://user-images.githubusercontent.com/1972649/227707084-e20134ee-c615-4ab3-9f49-d23acbda0cfd.png)

**Comment by AugustTuan** [comment]
> 检查这里的设置，去掉一下： ![image](https://user-images.githubusercontent.com/1972649/227707084-e20134ee-c615-4ab3-9f49-d23acbda0cfd.png)

可以了，谢谢
我说怎么不断地报错，原来是扩展热键和快捷键 有重复的地方。
