### ISSUE TITLE
扩展热键有时失灵

### ISSUE THREAD

**Issue by BennyXie** [cuiliang/QuickPadCn#1879]
我用扩展热键当做capslock+，就是用capslock当做扩展热键，然后sdfe这四个键当做方向键。有时这个就会失灵，重启也没用，但是过一会什么也不干就好了。

不太好提供使用截图，因为没法展现这个bug。

**Comment by cuiliang** [comment]
可能的原因：
1) 有按键状态不正确。 可以打开键盘状态窗口查看一下。
![image](https://user-images.githubusercontent.com/1972649/227756402-6034e335-e979-41ea-a6bb-def8d1cce96f.png)

2）挂钩丢失，尝试重新加载一下挂钩。

3）其它使用键盘挂钩的软件或ahk脚本影响

另外，如果只用来触发扩展热键，这里取消一下保持原有功能的选项。
![image](https://user-images.githubusercontent.com/1972649/227756438-1fab32a8-546c-453c-8502-7d33d01c366a.png)

**Comment by cuiliang** [comment]
微信登录后会自动按下F22键，很多情况是这个影响。 请升级到最新版，对这个情况做了处理。
https://getquicker.net/Help/Versions
