### ISSUE TITLE
Quicker 搜索 命令行执行 全部小写了

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [cuiliang/QuickPadCn#1880]
**描述BUG**
Quicker 搜索中默认行为的 命令行执行 将命令全部小写了

**相关截图**

![image](https://user-images.githubusercontent.com/40897360/227917739-fedf2526-3acb-4693-a498-fd4afca4a07a.png)

需要正确的大小写才能正常运行命令。

**环境信息:**
 - 操作系统版本：window10
 - Quicker版本：1.37.19

**Comment by cuiliang** [comment]
搜索中为提升性能会提前对搜索词进行小写处理。可以在这里开启一下选项避免此问题：
![image](https://user-images.githubusercontent.com/1972649/227936463-e80cbe3e-5340-4ed8-8cf6-4677e0dcddb4.png)
