### ISSUE TITLE
建议在动作快捷键里增加排序功能，比如多个软件定义了同一个快捷键的情况下，可以对软件的先后显示循序进行排序。

### ISSUE THREAD

**Issue by elviszz-zz** [cuiliang/QuickPadCn#1881]
建议在动作快捷键里增加排序功能，比如多个软件定义了同一个快捷键的情况下，可以对软件的先后显示循序进行排序。

**Comment by cuiliang** [comment]
比较复杂不考虑了。 
可以在快捷键里设置进程绑定，让每个进程下只有一个动作生效，更直接一点。还有一个办法是用一个动作，在里面根据前台进程执行不同的操作。
