### ISSUE TITLE
动作快捷键不生效

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1884]
**描述BUG**
设置动作快捷键后, 取消勾选等待抬起后触发后, 快捷键无法生效
- 如果选中抬起触发可正常生效
**重现步骤**
1. 添加快捷键
2. 取消抬起触发
3. 保存后使用快捷键

**相关截图**
![image](https://user-images.githubusercontent.com/116153891/229094007-9abb7b9b-b58c-4c4c-8cee-a1cb0b139367.png)

**环境信息:**
 - 操作系统版本：win10 21H1
 - Quicker版本：1.37.23

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
动作模拟的按键，和当前手按下的按键组成了新的组合。 这正是这个选项存在的原因。
