### ISSUE TITLE
在某些游戏里面鼠标点击无效

### ISSUE THREAD

**Issue by ilcpm** [cuiliang/QuickPadCn#1886]
![image](https://user-images.githubusercontent.com/36830343/229287703-f74a1b3b-a26c-4e08-bdc1-5e6f8ec8a914.png)

 不管是多步骤输入还是直接的鼠标输入，都没有用
我觉得可能quicker的点击是“虚拟的”？而游戏调用的是更底层一些的直接读取硬件的东西？

**Comment by cuiliang** [comment]
是的，有的游戏里是模拟不了的，要用更底层的驱动级模拟才行，quicker里实现不了。
