### ISSUE TITLE
“选择图标”里的白图标看不到

### ISSUE THREAD

**Issue by hzinchengdu** [cuiliang/QuickPadCn#1887]
“选择图标”里的白图标看不到，能否把背景颜色给换下或自动识别图标颜色换上合适的背景。

![image](https://user-images.githubusercontent.com/126546789/229403373-44011f46-13f9-4bb8-96d4-3f6f5a717daf.png)

**Comment by cuiliang** [comment]
后期研究下。
目前可以在计算机里管理图标文件，然后需要的时候复制文件后在动作上右键粘贴图标。

**Comment by cuiliang** [comment]
增加了一点底色，待1.38.10版本更新。 
![image](https://github.com/cuiliang/Quicker/assets/1972649/61051581-81c2-4f5c-a7c1-89ff47056a7f)
