### ISSUE TITLE
轮盘菜单

### ISSUE THREAD

**Issue by hzy921** [cuiliang/QuickPadCn#1888]
轮盘处罚按键  能不能 设置组合键？？？十分需要这个功能

我是一个使用maya的用户，鼠标的右键，中间都有用，不能设置成 触发按键，希望能解决这个问题，非常感谢！！！

(https://user-images.githubusercontent.com/96275945/230086449-98e5c48a-58a7-4562-aa91-a039676549d2.png)

**Comment by cuiliang** [comment]
用这个动作 https://getquicker.net/Sharedaction?code=7efc668c-a749-4a8c-fc16-08d978b0ec35 
绑定一个快捷键使用。
不过你也可以考虑购买一个5个键的鼠标。另外也可以在高级鼠标触发中，通过附加引导键+鼠标移动的方式触发。

**Comment by hzy921** [comment]
好的，非常感谢！
我去试试看，能不能满足我的要求的



在 2023-04-05 21:06:46，"CuiLiang" ***@***.***> 写道：

用这个动作 https://getquicker.net/Sharedaction?code=7efc668c-a749-4a8c-fc16-08d978b0ec35
绑定一个快捷键使用。
不过你也可以考虑购买一个5个键的鼠标。另外也可以在高级鼠标触发中，通过附加引导键+鼠标移动的方式触发。
