### ISSUE TITLE
使用高精度截图或者截图ocr时，会频繁的卡一下。

### ISSUE THREAD

**Issue by dashu96** [cuiliang/QuickPadCn#1889]
**描述BUG**
使用高精度截图或者截图ocr时，会频繁的卡一下。一会又恢复正常，但是频率很高。两台电脑，同样的win11，同样的软件版本，同样的动作，笔记本不卡，台式电脑卡。

**重现步骤**
正常使用，按键ctrl，鼠标点击动作使用。

**环境信息:**
 - 操作系统版本：win11 22H2 03
 - Quicker版本：1.37.23

**Comment by cuiliang** [comment]
建议录个屏，也许和电脑配置有关，内存不足或显卡不行，也许是系统环境问题。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by dashu96** [comment]
好的，系统升级了以后没有发现这种情况。









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年4月10日(周一) 上午7:33写道:

  

 
先关了，如果还有问题，请再reopen
