### ISSUE TITLE
请求滚轮右击触发方式和左击下放给手势与轮盘

### ISSUE THREAD

**Issue by Jerry-FaGe** [cuiliang/QuickPadCn#1890]
**需求描述**
我在想，既然 Quicker 都作出滚轮左击触发主面板的方式了，为什么不能加个滚轮右击并且下放到鼠标手势和轮盘中呢，这样像 G502 这种滚轮能左右击的鼠标就能只靠一个中键实现绝大部分操作了

**描述你想要的解决方案**
实现滚轮右击触发，并与左击一起下放给手势与轮盘

**描述您考虑过的替代方案**
无

 **其他上下文**
无

**Comment by cuiliang** [comment]
没太懂。 这些本身是下放到高级鼠标触发里的。

**Comment by Jerry-FaGe** [comment]
> 没太懂。 这些本身是下放到高级鼠标触发里的。

啊，我懂您的意思了，不好意思我刚开始用这个软件。我其实说的是手势和滚轮的触发键设置中只看到了4个按键并没有看到鼠标左击右击的按键，我想实现的是用鼠标左击或者右击触发手势或轮盘，不过用您提到的高级鼠标触发应该可以满足我的需求，感谢指点！

**Comment by cuiliang** [comment]
轮盘和手势都通过按下某个键之后立即移动的方式触发的。 这可能和普通手势软件不太一样。可以先了解一下。

**Comment by Jerry-FaGe** [comment]
> 轮盘和手势都通过按下某个键之后立即移动的方式触发的。 这可能和普通手势软件不太一样。可以先了解一下。

这个我是知道的，我用X1键做了测试是正常的，但是不知道怎么实现滚轮右击并立即移动触发轮盘。我刚用高级鼠标触发试了一下，发现像下面这样设置只是唤出了轮盘菜单，并不能像正常轮盘一样松手触发动作。。

![image](https://user-images.githubusercontent.com/40235071/230589689-647d7dfe-0728-40aa-84ce-0c55208c9c2e.png)

**Comment by cuiliang** [comment]
是的，只有按住滑动方式可以一次性触发轮盘动作，其他方式只是弹出轮盘，要点击一下才知道执行哪个动作。 滚轮右击，这个实际上是对应的水平滚动消息。

**Comment by Jerry-FaGe** [comment]
所以本 issue 请求的功能就是在手势和轮盘的 `触发按键` 中希望可以加入 `滚轮左击` 和 `滚轮右击` 的触发方式😂

![image](https://user-images.githubusercontent.com/40235071/230785893-74ed1f0e-99e1-4b5d-96cb-43d2ab96faea.png)

**Comment by cuiliang** [comment]
实现不了哦。 它们不是真实存在的按键

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
