### ISSUE TITLE
弹出面板中“在按钮上松开后执行动作”选项失效

### ISSUE THREAD

**Issue by wuenna** [cuiliang/QuickPadCn#1891]
**描述BUG**
弹出面板中的“在按钮上松开后执行动作”选项，勾选后不生效，仍然是在按钮按下、而不是松开时弹出面板，和不勾选该选项时效果一样。

**环境信息:**
 - 操作系统版本：Windows 11
 - Quicker版本：1.37.23

**Comment by cuiliang** [comment]
这个选项的意思是，比如使用中键按下的方式弹出面板，那么按下中键--弹出面板--移动鼠标到动作上--松开鼠标，执行这个位置的动作。 并不是抬起鼠标的时候才显示面板。

**Comment by wuenna** [comment]
啊，这样啊，是我误会了，多谢解答。
