### ISSUE TITLE
使用wacom数位笔代替鼠标在浏览器弹出的面板不会主动消失

### ISSUE THREAD

**Issue by daowaidao** [cuiliang/QuickPadCn#1892]
在360 chromex 浏览器 弹出面板，如果不去点击上面的功能或者主动点击右上的关闭的话，面板不会自动消失，会一直停留，在桌面就没问题，如果换成鼠标就都没问题，有些奇怪

**Comment by cuiliang** [comment]
需要鼠标点击消息才能检测到，然后才能关闭，数位笔在不同的软件里所产生的消息不一样，会导致这个现象。
有的软件里，数位笔=鼠标，生成的鼠标消息
有的软件里，数位笔=触摸，触摸消息没法挂钩，无法检测。

**Comment by daowaidao** [comment]
感谢回复，在windows的wacom属性设置里面设置了数位笔的按键等于鼠标的按键，也不知道浏览器是不是当成触摸了，只能习惯下了

**Comment by cuiliang** [comment]
嗯，浏览器用笔按住左右滑动，他就是相当于前进后退了，鼠标就没这个效果。

**Comment by daowaidao** [comment]
好的感谢
