### ISSUE TITLE
quicker.exe阻止惠普开启独显直连

### ISSUE THREAD

**Issue by guanlisir** [cuiliang/QuickPadCn#1893]
**描述BUG**
惠普笔记本的ogh在游戏时会自动打开独显直连，但是quicker.exe阻止切换。

**重现步骤**
1. 使用惠普笔记本的ogh，设置为“打开游戏时，自动切换为独显直连”
2. 打开一个游戏

**相关截图**
<img width="1282" alt="20230412230946627" src="https://user-images.githubusercontent.com/53703733/231503540-70bfd5fe-0624-4798-982e-7875d096682d.png">

**环境信息:**
 - 操作系统版本：Windows 11 家庭中文版   22H2   22621.1555
 - Quicker版本：1.37.26

**Comment by cuiliang** [comment]
这可能是wpf技术的限制，可能没有什么办法。 先退出quicker吧

**Comment by cuiliang** [comment]
无法解决
