### ISSUE TITLE
Quicker 搜索功能，文本指令建议

### ISSUE THREAD

**Issue by sd362318** [cuiliang/QuickPadCn#1894]
**需求描述**
希望可以右键编辑文本指令的搜索结果进行快速的编辑，不用每次都要到文本指令设置里修改。

**Comment by cuiliang** [comment]
好的，我研究下。 目前排队的坑比较多

**Comment by cuiliang** [comment]
后来的版本增加了编辑功能。
![image](https://user-images.githubusercontent.com/1972649/236738943-09e34c87-39a6-490b-92f1-ef4af2263842.png)
