### ISSUE TITLE
不知道你们是否用过微软的snipaste这个产品，这个产品可以对截图进行编辑，我个人觉得这是一个很有用的功能，因此现在我的电脑上同时保留你们两个软件

### ISSUE THREAD

**Issue by Wei-Peng-fei** [cuiliang/QuickPadCn#1895]
不知道你们是否用过微软的snipaste这个产品，这个产品可以对截图进行编辑，我个人觉得这是一个很有用的功能，因此现在我的电脑上同时保留你们两个软件
![image](https://user-images.githubusercontent.com/100499444/234272393-8e7a08df-3b99-4994-a969-70302d621d74.png)

**Comment by cuiliang** [comment]
我也有买这个软件的。 quicker里的截图主要是方便后续做ocr或自动保存等处理的，比较简单。 开发这样的一个截图软件也要很多年。。。

**Comment by Wei-Peng-fei** [comment]
十分能够理解你们，毕竟国内的生态还不是太好，小公司开发遇到的问题还是很多，做的太好一来是要钱二来是怕大公司直接照抄，做的不好东西又要凉



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 晚上9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cuiliang/Quicker] 不知道你们是否用过微软的snipaste这个产品，这个产品可以对截图进行编辑，我个人觉得这是一个很有用的功能，因此现在我的电脑上同时保留你们两个软件 (Issue #1895)





 
我也有买这个软件的。 quicker里的截图主要是方便后续做ocr或自动保存等处理的，比较简单。 开发这样的一个截图软件也要很多年。。。
