### ISSUE TITLE
[鼠标手势]在开启 激活轨迹开始位置窗口 选项后一段时间失灵

### ISSUE THREAD

**Issue by lvsanmu** [cuiliang/QuickPadCn#1896]
**描述BUG**
[鼠标手势]在开启 激活轨迹开始位置窗口 选项后一段时间失灵
在开启该功能之后的一段时间（具体没有记录过）可以在开始位置进行控制
但是在一段时间之后就变成了对选中的窗口进行操作了
但是在设置页面中重新点击应用设置（此时该功能是选中状态，并没有开启和关闭操作）之后又功能恢复

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/81674474/234463946-05cf564e-abf6-4240-aab2-e4cabab8b2ce.png)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
意思是过一段时间之后，就没法激活鼠标开始位置的窗口么？ 
Quicker是在默认安装目录下运行的吧？其它还有没有什么异常现象呢？ 比如用鼠标弹出面板的时候，会激活弹出位置的窗口么？

**Comment by cuiliang** [comment]
@lvsanmu 你好，这个现象还存在么？
希望可以有更详细的信息以便于判断问题。

**Comment by lvsanmu** [comment]
目前没有再发现这个现象，正在使用的版本为1.37.37
之前的问题在于：同时打开两个窗口1、窗口2，并列显示
在点击窗口1之后，鼠标移动到窗口2进行鼠标手势操作（最小化窗口，动作：下拉），最终的结果是窗口1发生了最小化
















在 2023-06-28 22:38:00，"CuiLiang" ***@***.***> 写道：

@lvsanmu 你好，这个现象还存在么？
希望可以有更详细的信息以便于判断问题。
