### ISSUE TITLE
百度文心的字数限制=1024字太少了

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1897]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
[工业革命=全球工程前沿2022 - 知乎](https://zhuanlan.zhihu.com/p/625824256?)
全球工程前沿2022的PDF先转成txt【想暂时去掉图片，只看文字】再转html，导出后发现html格式全乱了

全部都在1行里，而且不同行很混乱的拼接到1起

文心的字数限制=1024字，限制太大了！能不能把849kb的txt用quicker分割成多份，然后自动发送到文心，暂时不要回答结果，先把数据输入进去，后面再想，再选些问题
源文件大小16.7mb转成txt只有849kb，文件大大缩小！
txt大致是这样的，右边空白的，1行的空间没用就到下1行了，怎么处理好

3  发展路线图
在前面形成的专利家族数据基础上，针对 9 个
领域 53 个学科组被引频次位于前 10 000 的高影响
技术路线图是描绘技术未来发展趋势的重要工
力专利家族，开展专利文本语义相似度分析，基于
具。为强化工程前沿的学术引领作用，在本年度研
DWPI 标题和 DWPI 摘要字段进行主题聚类，获得
究中，各领域深入分析重点工程研究前沿和重点工
53 张能快速直观呈现工程开发技术分布的 Theme
程开发前沿的发展方向、发展重点和发展趋势，以
Scape 专利地图，以关键词的形式展现所聚集专利
可视化的方式绘制该前沿未来 5~10 年的发展路线
的总体技术信息。
html拼错了，例子=广义上，泛在操作系统既 的技术。常用的特征信息包括到达时间、到达时 包括面向服务器、计算机、智能移动设备、传感器 间差、到达角及接收信号强度等。对这些特征信 等不同规模计算设备的操作系统，也包括面向物联 息建立相应的数学模型，再根据参数估计准则构 网、机器人、智慧城市、智慧家居等不同应用场景 建非线性估计问题，最后通过求解该非线性估计 的操作系统。狭义上，泛在操作系统特指秉承泛在 问题获得目标位置估计。目标定位的技术方向主 计算思想，面向泛在化计算资源管理，支持泛在应 要有：① 精确性，定位精度通常为这一技术所考 用开发运行，具有泛在感知、泛在互联、轻量计算、 虑的首要目标；② 鲁棒性，复杂传输环境下的测 轻量认知、反馈控制、自然交互等新特征的新形态 量值存在大量不确定因素，因此定位技术的鲁棒 操作系统。国际上，泛在操作系统在物联网、智能 性也成为必须考虑的重要因素之一；③ 高速性， 机器人、智慧城市等领域已有相关的系统实现与应 定位技术的计算复杂度以及工程易实现性是工程 用，但是并没有统一的研发部署，也没有形成大规 应用中的关键因素。 模研发成果、技术体系和标准规范。在中国，泛在 未来多源信息融合的定位技术有以下发展趋 操作系统得到学术界和产业界广泛关注，获得国家 势： 自然科学基金专项项目支持，并且被写入工业和信 1）融合多类型传感器和多类型测量，解决异 息化部“十四五”软件与信息服务业发展规划。在 构异步异质多源信息融合难题。例如，毫米波系 产业界，腾讯、海尔等一批企业在物联网、云计算、 统能够提供高精度的测距和测向信息，使厘米级 智慧城市、智慧交通、智慧建筑、智能家居等领域 定位成为可能；图像信息与电磁波信息的结合将 的新型操作系统研发上也开展了积极探索和实践， 提供更丰富的信息，全面覆盖可见和不可见环境 为不同行业用户的数字化转型提供了重要的系统软 的定位需求。 件平台支撑。 2）复杂场景下的多 / 群目标与弱目标定位。 （5）量子微波测量技术 例如混合近远场多点目标、刚体 / 集群目标定位， 量子微波测量技术是基于量子力学特性——特 以及深空、水下等弱探测目标精准定位等。 别是量子纠缠、量子叠加和量子隧穿等效应—— 3）数据驱动的智能定位技术。机器学习等理 在量子系统中产生、操控、传输和测量微波的技 论方法的快速发展为复杂定位问题提供新的求解 术。量子微波测量技术将量子技术的高关联、高 手段。 复用、强鲁棒与微波的灵活性、全天候、易调控

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
和quicker无关
