### ISSUE TITLE
单击CTRL弹出无法关闭

### ISSUE THREAD

**Issue by sinlatansen** [cuiliang/QuickPadCn#1898]
**描述BUG**
我关闭了单击ctrl弹出，但是偶尔我碰到ctrl键他依旧会弹出

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 22H2
 - Quicker版本：1.37.37

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
测试了一下没能复现。 有能复现此问题的步骤么？

另外检查一下有没有开双击ctrl？
![image](https://user-images.githubusercontent.com/1972649/235555331-1738f0bd-21cb-4be2-ab8d-37613a7cca77.png)

**Comment by sinlatansen** [comment]
因为我使用了比较久的listary是双击ctrl触发，已经习惯。所以我下载quicker后就把单击ctrl弹出关闭了。
        但是偶尔我在打算双击呼出listary的时候第一下ctrl就把quicker呼出了，我当时去检查了quicker设置，单击ctrl呼出是关着的。所以我想可能有bug。目前只是偶尔出现，一两天一次的频率吧，我应该总共碰见过三次，目前我也没有稳定复现的办法，下次碰到了我再琢磨一下，谢谢。
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月2日 08:38
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [cuiliang/Quicker] 单击CTRL弹出无法关闭 (Issue #1898)
        
      
    
  

测试了一下没能复现。 有能复现此问题的步骤么？
另外检查一下有没有开双击ctrl？

**Comment by cuiliang** [comment]
查了一下，这里代码使用if包围，感觉应该不会产生意外。可能是其它规则（或bug）触发了。

**Comment by sinlatansen** [comment]
我发现了在我的电脑上稳定复现的情况，我同时设置了quicker和listary开机自启，quicker单击CTRL弹出确定是关的。每次电脑开机第一次，我双击CTRL唤醒listary时，就会因为单击CTRL唤醒quicker，而之后就基本不会再出现这个bug。我尝试了在电脑开机的状态下关闭quicker再启动，bug不会出现，所以只有电脑开机才会出现一次，我是win10 22H2版本。
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月2日 22:00
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [cuiliang/Quicker] 单击CTRL弹出无法关闭 (Issue #1898)
        
      
    
  

查了一下，这里代码使用if包围，感觉应该不会产生意外。可能是其它规则（或bug）触发了。

**Comment by cuiliang** [comment]
不开list的情况下会出现这个问题么？

**Comment by cuiliang** [comment]
本地安装了list，未能复现此问题。 
先关了，如果还有问题，请再reopen
