### ISSUE TITLE
启动软件无法添加webApp

### ISSUE THREAD

**Issue by hsopen** [cuiliang/QuickPadCn#1899]
**描述BUG**
新建启动软件的动作，无法添加edge上安装的网页app

**重现步骤**
1.打开网页https://www.geogebra.org/calculator
2.edge浏览器菜单-应用-将此站点作为应用安装
3.打开场景与动作，添加动作启动软件，找不到软件，通过路径找也无法显示，将图标创建快捷方式后可以选中，但出现警告“灾难性故障”

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/61812401/235596945-5638711d-7b17-434f-908f-d36ec8258109.png)

**环境信息:**
 - 操作系统版本：windows11 22h2
 - Quicker版本：1.37.37

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个不清楚什么原因，本地没有复现。 
可以试试赋值快捷方式文件后在空白按钮右键：
![image](https://user-images.githubusercontent.com/1972649/236736712-510a4bd9-c01a-48bb-b47a-e34e57eccb83.png)

另外通过这个，选择程序本地测试也是没问题的
![image](https://user-images.githubusercontent.com/1972649/236736755-131306e5-3490-4bcd-9195-bfa7d837c5b4.png)

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
