### ISSUE TITLE
SMTP 发邮件动作的发件人参数无效

### ISSUE THREAD

**Issue by JiaChen-Zeng** [cuiliang/QuickPadCn#1900]
**描述BUG**
设置了发件人，但是收到邮件的发件人为空（默认显示邮箱）。

**重现步骤**
1. 发件人随便填个
2. 执行动作发邮件

**相关截图**
![image](https://user-images.githubusercontent.com/3676278/235852759-923a5fc3-94b7-46a3-b851-3feb099fec35.png)
![image](https://user-images.githubusercontent.com/3676278/235853141-d337178d-c06e-4f1e-bd94-5683ba571a9a.png)

**环境信息:**
 - 操作系统版本：Windows 10
 - Quicker版本：1.37.37

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
里面不要加奇怪的字符，然后发一个到 197906@qq.com 试试。

**Comment by JiaChen-Zeng** [comment]
![image](https://user-images.githubusercontent.com/3676278/235855852-2c03d647-80b1-4bbc-9bac-de487eb0bd76.png)
改成最简单的，还是不行

**Comment by cuiliang** [comment]
发一个到 197906@qq.com 我看下啥效果。 这个显示很多时候依赖于邮箱系统或客户端。

**Comment by JiaChen-Zeng** [comment]
我发了，帮忙看看，谢了

**Comment by cuiliang** [comment]
确实没有了，我用qq邮箱做了一些测试，也是没有了。 代码看起来没问题，不清楚是不是现在邮件服务商、右键客户端都会做额外的处理。

**Comment by cuiliang** [comment]
导出eml文件，里面也是正常的。

![image](https://user-images.githubusercontent.com/1972649/235861126-8e1ff1eb-d9d7-400b-baa9-053d35870d46.png)

**Comment by cuiliang** [comment]
暂无解决方案。
