### ISSUE TITLE
使用miniconda3的python dll会闪退

### ISSUE THREAD

**Issue by OxYancy** [cuiliang/QuickPadCn#1901]
**描述BUG**
使用miniconda3的python dll会闪退

**重现步骤**
选择miniconda3的python dll
使用python测试脚本

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.37.37

**Comment by cuiliang** [comment]
是的，这个底层pythonnet只支持 https://www.python.org/downloads/ 这里下载的

**Comment by OxYancy** [comment]
有没有办法支持一下

**Comment by cuiliang** [comment]
pythonnet这个库发了一个preview版本，可能近期会更新一个版本，到时候试下新版。 我对python不太了解，miniconda3这个要怎么做个测试环境？

**Comment by cuiliang** [comment]
后续版本已更新pythonnet，可以试试 https://getquicker.net/Help/Versions
