### ISSUE TITLE
轮盘右键触发可以增加延时吗？

### ISSUE THREAD

**Issue by wittyMing** [cuiliang/QuickPadCn#1902]
比如在PS用手绘板的时候，习惯笔上的按键是右键，按得时候容易触发轮盘，其实是为了调出画笔选择工具，如果增加延时的设置，可以避免这个问题

**Comment by cuiliang** [comment]
轮盘是滑动触发的，将滑动触发距离调大一些以避免误触。
![image](https://user-images.githubusercontent.com/1972649/236649960-eb536584-7955-4dcf-aed0-55521f8f0a89.png)
