### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by katastrophe92** [cuiliang/QuickPadCn#1903]
Hello y'all. This software does look nice and cool. Can it be used in other language also? Thanks

**Comment by cuiliang** [comment]
Sorry, still no time to make multi language version.

**Comment by katastrophe92** [comment]
> Sorry, still no time to make multi language version.

It is completely chinese? (sorry if I got the language wrong)

**Comment by cuiliang** [comment]
> > Sorry, still no time to make multi language version.
> 
> It is completely chinese? (sorry if I got the language wrong)

yes. Thanks for you interest.
