### ISSUE TITLE
错误的“升级到专业版”的提示弹框

### ISSUE THREAD

**Issue by abuwillbebest** [cuiliang/QuickPadCn#1904]
**描述BUG**
错误的“升级到专业版”的提示弹框

**重现步骤**
免费版
1.悬浮一个动作或者动作页
2.激活面板右键或者两次右键任意动作，直接弹出“升级到专业版”的提示

**相关截图**
![录制_2023_05_08_10_04_25_688](https://user-images.githubusercontent.com/43464856/236718044-3159c32a-d11b-45cb-a085-0db336b3987e.gif)

**环境信息:**
 - 操作系统版本：Windows 11 10.0.22621
 - Quicker版本：1.37.37

**Comment by cuiliang** [comment]
感谢反馈，我等处理一下。

**Comment by cuiliang** [comment]
后续版本已经修复
