### ISSUE TITLE
鼠标放置屏幕边缘调节亮度出现BUG

### ISSUE THREAD

**Issue by TerenceWu718** [cuiliang/QuickPadCn#1905]
现在将鼠标放于屏幕边缘  按住CTRL滑动鼠标滚轮   不管是正方向还是反方向都是将亮度调低，无法调高亮度

**Comment by cuiliang** [comment]
这个估计是硬件不支持的情况了，和设备有关的本地也没法调试。有用过其它软件测试过么？

**Comment by TerenceWu718** [comment]
> 这个估计是硬件不支持的情况了，和设备有关的本地也没法调试。有用过其它软件测试过么？

您好 应该是硬件出现问题了 因为之前是能用的 突然不行了，我刚刚重启了一下电脑就可以了 谢谢
