### ISSUE TITLE
步骤组是否执行成功返回值不对

### ISSUE THREAD

**Issue by JiaChen-Zeng** [cuiliang/QuickPadCn#1907]
**描述BUG**
步骤组（忽略错误）里使用返回动作（不标记为错误）时，是否执行成功返回的是错误，但是按理应该是执行成功，或者说以下都不执行？

**重现步骤**
执行下面程序

**相关截图**
![F0A321XHXD$SZ$QSJ7P JH2](https://user-images.githubusercontent.com/3676278/236963984-6642b0f4-e556-4095-98dc-c83b636a8b52.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.37.37

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这里停止动作，后面就不会执行了。 忽略错误主要是用来忽略预料不到的错误，比如打开的文件不存在之类的。
