### ISSUE TITLE
组合动作里的右键菜单, 为什么只有 "转换成子程序" 而没有 "转换成公共子程序"

### ISSUE THREAD

**Issue by omymenzies** [cuiliang/QuickPadCn#1908]
**需求描述**
![image](https://github.com/cuiliang/Quicker/assets/115856305/e5bbb379-90e6-4c07-a895-1616f3621aaa)

**描述你想要的解决方案**
右键菜单里有 "转换成动作内子程序" 和 "转换成公共子程序"

**描述您考虑过的替代方案**
先转换成动作内子程序, 再转换成公共子程序; 创建公共子程序, 然后将动作复制粘贴到公共子程序里

**Comment by cuiliang** [comment]
尽量避免污染公共子程序，仅把特别通用的放到共用的里面。 
另外，转换不是一次性就成功的，在转换之后还需要根据需要调整输入输出参数。
