### ISSUE TITLE
关于高级鼠标触发中滚轮的检测

### ISSUE THREAD

**Issue by Harca-Yita** [cuiliang/QuickPadCn#1909]
**需求描述**
    建议在高级鼠标触发的鼠标动作中，添加一项不区分滚轮滚动方向的触发方式。在引导键+滚轮触发后，滚轮方向的判断与具体的动作执行交给动作脚本自己去完成。

    需要滚轮参与的动作多数都将判断集成在了脚本内，而且动作较为简单，都可以归为对某值的加减操作。所以建议在保留滚轮单方向触发的基础上，增加一个不区分滚轮方向的触发动作。

**Comment by cuiliang** [comment]
调用同一个动作，并给动作传递不同的参数，然后在动作里做判断就可以了。
![image](https://github.com/cuiliang/Quicker/assets/1972649/2ae89527-6392-4d0c-97ea-e6919187ec9c)
