### ISSUE TITLE
开启quicker时，NVIDIA自动切换功能失效

### ISSUE THREAD

**Issue by RicheyHg** [cuiliang/QuickPadCn#1910]
<img width="1280" alt="微信图片_20230518150621" src="https://github.com/cuiliang/Quicker/assets/133950262/4c123919-3099-45a0-82d4-c366d8d9d3c8">
<img width="286" alt="微信图片_20230518150649" src="https://github.com/cuiliang/Quicker/assets/133950262/56c5d44b-9fe1-4e70-b645-b9de67495ca1">
NVIDIA因一个叫backgroundwindow的无法自动切换显卡，关闭quicker后可正常自动切换（暂停运行无效）

**Comment by cuiliang** [comment]
虽然quicker也可能有这个现象（基于WPF开发的可能都会这样），但是这个截图里没有Quicker的进程，是微信和quicklook的，quicklook不是quicker。
这个估计也没有其它办法，需要微软才能解决。

**Comment by RicheyHg** [comment]
> 虽然quicker也可能有这个现象（基于WPF开发的可能都会这样），但是这个截图里没有Quicker的进程，是微信和quicklook的，quicklook不是quicker。 这个估计也没有其它办法，需要微软才能解决。
<img width="1280" alt="微信截图_20230518231503" src="https://github.com/cuiliang/Quicker/assets/133950262/ac726723-265e-4f4a-86a4-6d93d3465c0c">
<img width="1280" alt="微信截图_20230518231527" src="https://github.com/cuiliang/Quicker/assets/133950262/9cafb496-3e65-4f9f-9d63-059cf56ca996">
我今天排除过，这真是quicker的问题，所以现在这个情况只能通过关闭quicker来解决了是吗？

**Comment by cuiliang** [comment]
是的，参考：
https://www.nvidia.com/content/Control-Panel-Help/vLatest/zh-cn/mergedProjects/nv3dCHS/Closing_Blocking_Programs.htm
估计主要原因是WPF是通过显卡渲染，有些数据在显存里，没法切换到另一个显卡。

**Comment by cuiliang** [comment]
群友给出了解决方法，将Quicker设置为使用核显渲染：

![c753a951c83611a17059403bc64ec92e](https://github.com/cuiliang/Quicker/assets/1972649/cdb44d9b-8e3b-45cb-8e19-f70a2267a752)

**Comment by RicheyHg** [comment]
感谢分享，如果单在设置里改可能没有用，还要在NVIDIA的软件里改才行

**Comment by RicheyHg** [comment]
> 群友给出了解决方法，将Quicker设置为使用核显渲染：
> 
> ![c753a951c83611a17059403bc64ec92e](https://private-user-images.githubusercontent.com/1972649/298429918-cdb44d9b-8e3b-45cb-8e19-f70a2267a752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTM2MTUsIm5iZiI6MTcwNTkxMzMxNSwicGF0aCI6Ii8xOTcyNjQ5LzI5ODQyOTkxOC1jZGI0NGQ5Yi04ZTNiLTQ1Y2ItOGUxOS1mNzBhMjI2N2E3NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDg0ODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyYzg1YThjMjUxNGExOTQwY2U1YWU1ZWJiMzJjZDczNDliMTgyNTBhY2I1ZTAyZTUwMzhjZWRiYWQxZGEwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vyQ4R6gjMIrDQX1CVPOWz-FxAPcVM7eaJkJ9RvHWz4g)

我也试了一下，单纯改Windows里面的好像还是不行，后来在NVIDIA的软件里也改了之后就可以了。感谢。
