### ISSUE TITLE
quicker什么时候有每月、年度报告或者年度记忆

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1912]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
好多APP或者网站都有了！
希望每月、年度报告的统计数据方便保存，
知乎等好多APP都只能保存图片，而且之前的图片没保存好，现在找不到了，再访问以前的年度链接发现无法访问，数据无法读取
---
我手机保存→发送到电脑→文字识别→稍微编辑、删减下→保存到某个程度中，进行分析
流程太长了！

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
quicker目前没有计划开发这样的功能。
