### ISSUE TITLE
调试运行，鼠标移上去、再移走页面会上下抖

### ISSUE THREAD

**Issue by moroal** [cuiliang/QuickPadCn#1913]
**需求描述**
场景：调试运行；
问题：调试后，web中呈现的某一步内容如果过长（变量 sheet），鼠标移上去、再移走页面会上下抖，眼睛看花了忘记刚刚看的哪儿了

**描述你想要的解决方案**
避免页面上下抖

**描述您考虑过的替代方案**
手动展开收起，其他的还没想

 **其他上下文**
网页中内容很长，没滑到底的时候，页面下半部分展开收起；滑到底的时候，页面上半部分展开收起；尤其快滑到底的时候，有时候往上抖有时候往下抖，所以感觉比较奇怪。

**Comment by cuiliang** [comment]
遇到自动折叠的地方，可以点一下，让它保持持续展开状态。

**Comment by moroal** [comment]
好的多谢

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
