### ISSUE TITLE
多线程解析表达式出错：集合已修改可能无法执行枚举操作

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#1914]
**描述BUG**
解析表达式出错。
内部错误：集合已修改；可能无法执行枚举操作。
原始表达式："Kopia " + Math.Floor({微标更新}/10) + "s"
(----智能备份:状态存取----)
![image](https://github.com/cuiliang/Quicker/assets/48246272/caa1931b-cfb5-4a13-a77b-7ce86e6ea036)

**重现步骤**
这一模块偶尔会报错导致动作终止，但大部分时候都没问题，上面有处使用了相同的写法，每分钟都会执行一次，也有人出现过报错
不是很理解“集合已修改；可能无法执行枚举操作”是什么问题，不知道是我使用多线程不规范还是 quicker 的问题

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.38.3

**附加信息**
动作链接：https://getquicker.net/Sharedaction?code=8dfe1e68-33f0-4329-14ae-08da4a84097c

**Comment by cuiliang** [comment]
这个大概意思是在枚举列表的过程中修改了列表。 
非必要不使用多线程，使用多线程的时候避免访问相同的变量。

**Comment by ghost** [comment]
意思是一条线程更新，另一条线程读取这样也可能有问题吗？

我希望通过微标来显示动作的运行状态，但由于动作终止后微标会保持在之前的状态，为了区分出这一情况我必须要让微标不断更新，有些步骤耗时很长，无法在单线程中对微标进行更新，所以我就使用了多线程。

我打算先试试换一下访问/更新形式，如果还是不能规避这个问题的话我会考虑用多实例来替代多线程。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
