### ISSUE TITLE
扩充quicker app的功能，实现手柄，键盘鼠标应急，多屏协同等功能

### ISSUE THREAD

**Issue by 33moren33** [cuiliang/QuickPadCn#1915]
**需求描述**
app功能有点单调了，完全没将手机优势发挥，可以参考一下华为的多屏协同以及steam link将手机在电脑使用时，扩展成一个重要配件。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
app已经没有维护了。暂时没有这方面的计划了
（手机操作需要目光切换，效率一般）
