### ISSUE TITLE
更新中，去除了 “工具箱” 按钮；个人觉得这个功能挺好用

### ISSUE THREAD

**Issue by abcqwerzxcv** [cuiliang/QuickPadCn#1916]
**需求描述**
例如可以在word中，直接添加word对应的插件
省去到网页中再去找

**描述你想要的解决方案**
希望恢复

**Comment by cuiliang** [comment]
它显示的内容比较简单，可能会忽略网页里的重要内容。 所以决定暂时去掉了。
