### ISSUE TITLE
现有搜索框功能效果较差，建议参考flow-launcher

### ISSUE THREAD

**Issue by Cx330-502** [cuiliang/QuickPadCn#1917]
建议参考 [Flow-launcher](https://www.flowlauncher.com/)
这样的搜索框或许更符合我理想中的搜索框
![image](https://github.com/cuiliang/Quicker/assets/105686930/e9b00c13-c4c7-4e12-9843-cda0ff34b331)

**Comment by cuiliang** [comment]
功能还是样式？ 希望可以更明确一些。
目前搜索功能只是quicker里的一个辅助功能，可能没有很多精力做太多优化。也可以同时使用这两个软件来满足不同的需求。

**Comment by Cx330-502** [comment]
主要是功能，它的快捷启动功能我觉得很香。 
我主要是不想开太多软件在后台

**Comment by cuiliang** [comment]
有什么程序用quicker的搜索框搜不到么？

**Comment by Cx330-502** [comment]
很多都搜索不到，这是quicker的搜索结果：
![image](https://github.com/cuiliang/Quicker/assets/105686930/35d2b2a1-9e58-4504-b123-4a0a1746ea66)
![image](https://github.com/cuiliang/Quicker/assets/105686930/85461404-3331-45ed-a027-49708a3be787)
下面是[Microsoft PowerToys](https://github.com/microsoft/PowerToys)中 `Powertoys Run` 功能的搜索结果（flow-launcher暂时没有下载）
![image](https://github.com/cuiliang/Quicker/assets/105686930/cbd34eae-e8f5-4bad-ab4f-2e25b471ee00)
![image](https://github.com/cuiliang/Quicker/assets/105686930/ca471da4-c2d4-4708-9c5e-dce1467fb433)

经过我的尝试，好像用quicker搜索框绝大多数应用都搜索不到

**Comment by cuiliang** [comment]
程序搜索默认要加触发词#，
详细请参考下文档：https://getquicker.net/kc/manual/doc/searching

**Comment by Cx330-502** [comment]
好的，我忘记这个了😂😂😂
