### ISSUE TITLE
参考键盘鼠标点击统计WhatPulse 尽可能的减少点击次数

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1918]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
https://github.com/Planshit/Tai/issues/197
https://github.com/Planshit/Tai/issues/198
之前记录了1次，但是作者说最近在重构，不会搞这个

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
下面这个图很宝贵，后面会员尝试期过了，无法查看统计数据了。之前干别的去了，导致这个数据都没怎么看
天若_20230522140140

还可以参考
有好些想不起来了所以没记录
手机上APP使用过的有=潮汐、小睡眠、forest、

我用过的谷歌浏览器插件=进行时间或历史记录统计
Clockify Time Tracker 2.9.9
Day.io-Time Tracker 1.8.2
Everhour-Time Tracking,Budgets,Ex..
ManicTime Url Tracker 1.1.13
Otto -Pomodoro timer and website bloc...1.0.15
RescueTime for Chrome and Chrome OS 3.2.10
Roam ShowTime 1.1
TMetric Time Tracker Productivity App 4.7.0
Toggl Track:Productivity Time Tracker 3.0.2
Tracking Time Time Tracker Button 3.3
Web Activity Time Tracker 1.7.2
Webtime Tracker 1.7.8
Better History 4.0.3
Clipboard History Pro:best productivity t...3.17.2
History Manager 1.0
History Trends Unlimited 1.6.2
Recent History 23.2.27
应用列表导出不方便=非常刚需

之前是1个个手打的、电脑上导出应用列表方便但是没有统计使用日期，从安装到今天有多少天？设置里查看有哪些应用=更新后时间就变了
目前用滴答清单追踪。
迟迟不更新的+功能太少=卸载
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
发现github无法复制图片，只复制到了个名字

键盘鼠标点击统计软件目前在用的WhatPulse、KMCounter.exe 、WinOMeter.exe，
以前好像还用过其他的但是其他的更简陋，频率太低，不记得了

WhatPulse=最完善，但是会员版本 1年要200多！
天若_20230522141155

目前在近可能减少鼠标点击次数，或者同样的输入量=更少的点击次数，之前买的语音鼠标老是出问题，语音输入法不太好用。

减少碎片时间，碎片多，我太容易分心了！频繁切换任务=大脑很容易累，键鼠空白点击太多次，明明没做多少事情就累的不行

天若_20230522141036

天若_20230522141102

天若_20230522141124

天若_20230522141508

天若_20230522141536

**Comment by cuiliang** [comment]
没看懂，这个似乎和quicker没太有关系？
