### ISSUE TITLE
高级鼠标触发 的生效位置建议增加 标题栏

### ISSUE THREAD

**Issue by Harca-Yita** [cuiliang/QuickPadCn#1919]
**需求描述**
高级鼠标触发的生效位置建议增加标题栏

**描述你想要的解决方案**
如果触发位置增加标题栏，对某些窗口，比如chrome等多标签页窗口，标题栏触发switch tab会更加直观。
标题栏触发也会比屏幕特定位置触发更加明确清晰。

**Comment by cuiliang** [comment]
感谢建议。 
目前似乎没有很准确的判断标题栏的方法，只能根据大概的像素位置猜测一下。

**Comment by cuiliang** [comment]
1.42.4 版本增加了。
