### ISSUE TITLE
数据同步总是失败，开机总是弹窗未同步成功页面

### ISSUE THREAD

**Issue by Legend-Han** [cuiliang/QuickPadCn#1920]
**描述BUG**数据同步总是失败，开机总是弹窗未同步成功页面
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/cuiliang/Quicker/assets/91818731/b6911c99-58fa-45aa-8656-0b33c58c692a)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
太长时间没有同步（100天），身份凭据过期了。 
这时候需要退出账号重新登录一下。 如果有重要的动作，导出备份一下，因为退出账号会让数据恢复到上次成功同步的时候。
![image](https://github.com/cuiliang/Quicker/assets/1972649/e902743d-5cc0-47bb-bb3d-d2aa5988f97e)

**Comment by Legend-Han** [comment]
如何导出备份呢

**Comment by cuiliang** [comment]
![image](https://github.com/cuiliang/Quicker/assets/1972649/36142bf1-b2bf-4340-b4d7-65beb3c22150)

**Comment by Legend-Han** [comment]
谢谢，我尝试一下
