### ISSUE TITLE
免费账号填了讯飞 Key 也用不了语音识别

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#1922]
# 免费账号填了讯飞 Key 也用不了语音识别

## 具体问题

**Win 系统操作相关模块**里的**录制声音/语音识别**操作类型设为**短语音输入**，按 Quicker 官方文档里的格式把讯飞的 Key 填上后，普通非会员用户依旧无法使用。

## 复现方法

我写的[讯飞语识](https://getquicker.net/Sharedaction?code=41fe20a5-483d-4f5b-a9c1-08db5f197f60&fromMyShare=true)里面用到了这个模块，我另注册了一个非会员账户测试这个动作时发现了这个问题，可用此动作复现。

## 系统等信息

- 操作系统版本：Windows 11 22H2 22621.1778
- Quicker版本：1.38.8

**Comment by cuiliang** [comment]
升级到最新版 https://getquicker.net/Help/Versions

**Comment by Immortal-Sty** [comment]
> 升级到最新版 https://getquicker.net/Help/Versions

@cuiliang 

依旧不行。

**Comment by cuiliang** [comment]
升级到1.38.14版本了么？ 右键调试运行一下，然后发下调试文件网址到 197906 qq邮箱。

**Comment by cuiliang** [comment]
这次应该可以了 https://getquicker.net/Help/Versions

**Comment by Immortal-Sty** [comment]
可以了，谢谢。
