### ISSUE TITLE
Arctime字幕制作软件创建面板

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1923]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
适用于javaw.exe OpenJDK Platform binary=无法创建软件所属的quicker面板的动作
2个名字不一样，怎么搞，还有遇到过所谓的客户端其实就是用的edge，搞的无法创建面板
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
Arctime是一款全新概念的跨平台字幕制作软件，可以运行在Mac、Windows、Linux系统上。独创字幕块和多轨道概念，在时间线上拖动鼠标、调整字幕块即可轻松完成字幕创建工作。 Arctime支持导入SRT、ASS、LRC等常用格式字幕，可导出多种常用字幕格式，并且可以导出适用于FCP7、FCPX、PR、Edius、AVID、达芬奇的软字幕格式。 另外，ArcTime还支持将视频片段输出为GIF动图、批量截图以及多张截图拼接的功能，可大大加速碎片化内容的生产效率。
最新的自动断句和语音识别功能配合，可以快速将音频转换（听写）为文本，大大减少打字时间，提高字幕的制作效率，是影视工作者、自媒体人、在线教育从业者的一大利器。
面向译者，Arctime还提供了强大的翻译辅助模块，以及批量机器翻译功能，可以迅速完成语言的转换，只需少量人工校对即可交付。
如需交付视频，仅需从菜单中选择“视频转码”，即可轻松完成字幕压制工作。支持输出标准MP4、HEVC/H.265编码的MP4。Pro版可输出ProRes、DNxHD等专业格式。还可导出内嵌CC的MP4视频、带有透明通道的纯字幕MOV等。

**Comment by cuiliang** [comment]
场景按进程名判断。 java的程序可以编译成独立的exe，之后应该就可以正常识别了。 
网页可以动作页关联网址，参考这里：https://getquicker.net/QA/Question/13461
