### ISSUE TITLE
如何用quicker自动化动作复制彩云的网页翻译

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1924]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
复制彩云翻译之前手动重复太累了=如何用quicker自动化动作复制
有网页的解析的动作好像不行，搞不定，怎么结合
彩云翻译翻译出网页名之后点击动作自动复制网页信息，比如这个图里的，命名=现代帝国的兴衰，第三卷: 经济与政治=Saul Dubow 2017
要复制3个地方，书名下面的译文，作者名、下面的出版年份
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20230606203959](https://github.com/cuiliang/Quicker/assets/44609485/7d4886d3-118b-4115-810d-13df9a986df2)

**Comment by cuiliang** [comment]
可以在组合动作中使用“机器翻译” 模块实现自动化。
https://getquicker.net/kc/help/doc/translation
