### ISSUE TITLE
quicker 第1版的创立 发布时间 搜索搜好多次没搜到

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1925]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
到处找没找到，比如阿里会有2009→
Copyright © 北京立迩合讯科技有限公司 • 京ICP备09022189号-8
生活中重要的经常用的APP或者网站都会记录创立日期到滴答清单里
---
怎么现在没有显示了，我记得以前主业有运行次数来着，说是亿次，几亿来着
目前总动作有多少了？
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
18年。这些不重要的，建议关注真正重要的事情。
