### ISSUE TITLE
安装动作报错

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1928]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
此动作需要Quicker1.38.15.0或以上版本，您的Quicker版本为1.38.8.0.请升级Quicker后再安装此动作。

https://getquicker.net/Sharedaction?code=c272d951-277b-4fce-a622-08db29c171e2 在安装这个动作的时候发现无法安装，是最新版的
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20230614213731](https://github.com/cuiliang/Quicker/assets/44609485/4c5224c1-c90a-4c4e-bd5f-192b05a739a4)

**Comment by cuiliang** [comment]
测试版不会立即推送，请从这里下载：https://getquicker.net/Help/Versions
