### ISSUE TITLE
能显示我的quicker动作安装总数量吗

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1929]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
能显示目前我的quicker动作安装总数量吗
还有以前没有粘贴链接动作之前安装了好多动作，有不少重复了，怎么搞，怎么找出来重新安排
以前没有检查 [这动作安装过没 - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=83779484-e44d-49eb-4a20-08d9c10181e6) 我是前几天才发现的，太迟了！不知道有没有重复，搞的少安装了好多动作，今天又多安装了不少动作，好多个月没怎么安装新动作了。
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
建议不使用的动作可以导出到文件，然后删掉。如果很长时间都没用到，后面大概率也用不到的。
![image](https://github.com/cuiliang/Quicker/assets/1972649/8d9d3740-25f4-499b-9f6f-8d1144d8e2f2)
