### ISSUE TITLE
Quicker 大数据 近几年没有了

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1930]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
[Quicker 大数据2019年7月到2020年7月=文字版 - Quicker](https://getquicker.net/QA/Question/18744)

不知道为啥记录的图片非常歪
![天若_20230615120838](https://github.com/cuiliang/Quicker/assets/44609485/602e4e19-3701-463f-93d6-e737731824d5)

![天若_20230615120905](https://github.com/cuiliang/Quicker/assets/44609485/a11b1839-4e6b-4acc-abfb-54aa01f3e3ef)
把大数据统计发到3个大模型了，星火、文心、通义
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
请只反馈和讨论有关软件的问题。
