### ISSUE TITLE
“用户选择”的“最大尺寸”失效。

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#1931]
# 问题

## 描述

在同一个动作中，多次调用“用户选择”，会导致“最大尺寸”这个参数失效。

## 重现步骤

以下是我试过的会导致参数失效的操作：

- 调用好几次“用户选择”，“最大尺寸”全相同；
- 调用好几次“用户选择”，“最大尺寸”全不同；
- 用循环调用“用户选择”；
- 用子程序递归调用“用户选择”。

## 环境信息

- 操作系统版本：Windows 11 22H2 22621.1778
- Quicker版本：1.38.20

**Comment by cuiliang** [comment]
是不是保持位置了？

![image](https://github.com/cuiliang/Quicker/assets/1972649/1b6e5f77-c512-4259-80f6-2f067589a9df)

**Comment by Immortal-Sty** [comment]
> 是不是保持位置了？
> 
> ![image](https://user-images.githubusercontent.com/1972649/246332884-1b6e5f77-c512-4259-80f6-2f067589a9df.png)

@cuiliang 

是的，谢谢。
