### ISSUE TITLE
打开网址动作失效

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1933]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
这个动作很简单，没有搞啥其他的，打开网页，程序的在线网页版，类似这样的动作还有不少，都打不开了

可能是这个原因，之前为了尝试bing新版本的，安装=edge实验版，
现在打开动作点击无法运行，就是没反应，系统设置里默认浏览器是谷歌浏览器
![天若_20230620104516](https://github.com/cuiliang/Quicker/assets/44609485/3bb5aadf-fc63-440c-8bef-b94d655a0502)

动作点击调试运行，打开了edge
![天若_20230620104541](https://github.com/cuiliang/Quicker/assets/44609485/53b715f5-3343-4963-9690-0fde87c5a347)

编辑换成前台浏览器也没用，换成自定义 C:\Program Files (x86)\Google\Chrome\Application\chrome.exe 也没用 

Win-10.0.19045.0  Quicker-1.38.8.0 动作ID:e75ff7fa-2b60-4004-94c1-2aea8d4b96cf  来源动作: v0
Log文件路径：C:\Users\YEDONG\AppData\Local\Temp\quicker_数据统计_104252-262_log.html 定位文件 复制文件 上传并复制网址
开始执行动作：数据统计  2023-06-20 10:42:52
7动作初始化
- +
120打开网址((系统默认浏览器)) http://localhost:7026/database/statistics
[in]失败后停止【无输入】True
[in]网址【值/表达式】http://localhost:7026/database/statistics
[in]浏览器【值/表达式】default
[in]浏览器程序路径【无输入】
耗时：274ms
2831等待时间等待 100 ms
[in]等待时间【值/表达式】100
[in]等待窗口关闭时取消【无输入】False
耗时：119ms
4022提示消息啥内容也没有
[in]消息内容【值/表达式】啥内容也没有
[in]类型【值/表达式】Info
[in]最大行数【值/表达式】0
[in]风格【值/表达式】Default
[in]点击命令【值/表达式】
耗时：94ms
动作结束
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
尝试这些方法：1）重启电脑  2）修复windows 的默认浏览器设置， 3）在要使用的浏览器设置里找“设置为默认浏览器”的功能。
