### ISSUE TITLE
高级鼠标触发-移动指针到某一悬浮按钮上，此时右键点击悬浮按钮没有反应

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1934]
**描述BUG**
右键点击悬浮按钮没有反应

再次右键点击悬浮按钮才有反应

**重现步骤**
1.高级鼠标触发-鼠标移动到屏幕右上角触发动作
2.动作内容：自动定位鼠标指针到一个悬浮按钮上
3.成功移动，但此时右键点击悬浮按钮无反应

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win10 19044
 - Quicker版本：1.38.21

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
你好，需要更详细的信息才能判断。
1）高级鼠标触发里的设置。
2）触发的动作的设置。
以上内容截图一下。
