### ISSUE TITLE
搜索框偶尔不展示出内容

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1935]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1. 轮盘->Quicker：打开搜索
2.

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/27837566/f60df0cc-291b-4993-8ec8-71e9ec17ee4f)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.38.21

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
通过快捷键方式打开的有这个现象么？

**Comment by heloook** [comment]
> 通过快捷键方式打开的有这个现象么？

似乎没有，轮盘也是在刚开机的时候，

极少见

**Comment by heloook** [comment]
@cuiliang 

 似乎没有，轮盘也是在刚开机的时候，

极少见




> 通过快捷键方式打开的有这个现象么？

**Comment by cuiliang** [comment]
刚开机的时候可能磁盘比较忙，数据库文件读写来不及加载历史数据

**Comment by heloook** [comment]
@cuiliang 

用快捷键也出现了
我本来不用快捷键的，刚才有意识的多用了几次快捷键，
结果也出现了，而且是在正常使用电脑，不是刚开机
![image](https://github.com/cuiliang/Quicker/assets/27837566/73acc487-76a1-4c34-965a-c2be3fb973b6)

这个时候，用轮盘也是没有内容。

然后再试几次就有了

不清楚是不是我电脑和系统的原因：
![image](https://github.com/cuiliang/Quicker/assets/27837566/f948ded2-466f-4256-8074-6407afd15b1f)

quicker 1.38.21

**Comment by heloook** [comment]
奇怪的是，我之前一直用的是动作中的实时搜索，从来没有这个问题

**Comment by cuiliang** [comment]
是搜不出来内容，还是打开搜索框的时候没有显示历史记录？

**Comment by heloook** [comment]
@cuiliang 

是没有显示历史记录

不知道是不是memclean这个软件影响的？
不用这个软件我的Quicker占用内存在500M左右，edge差不多也是500M

不知道这正不正常

我必须开启这个软件，不然电脑内存不够用，然后每5min清理一下内存
quicker占用内存会瞬间从500M降到50M，然后慢慢回升，稳定到200M左右
edge也是会瞬间下降到50M

效果显著！不开这个软件，我笔记本几乎没法用

https://www.koshyjohn.com/software/memclean/

**Comment by heloook** [comment]
话说，quicker能出一个自动清理内存的功能么，太必要了

**Comment by cuiliang** [comment]
内存并不能真正的被压缩，只是被放入了磁盘里。 这反而会影响性能，因为在需要使用的时候还要从磁盘读出，在这个时候软件就会卡住。

**Comment by cuiliang** [comment]
尽量避免长期循环或长期在后台运行动作

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
