### ISSUE TITLE
使用滚轮连续触发

### ISSUE THREAD

**Issue by peilonia** [cuiliang/QuickPadCn#1936]
似乎对win7系统无效

win10，win11都能用
在一台win7系统的电脑上用不了

https://getquicker.net/kc/help/doc/scroll-trigger

**Comment by cuiliang** [comment]
Win7 不支持，用高级鼠标触发实现下试试。

**Comment by cuiliang** [comment]
因为win7 需要窗口具有焦点才能接收到滚动消息，此功能无法支持。
