### ISSUE TITLE
quicker自带的搜索问题

### ISSUE THREAD

**Issue by AugustTuan** [cuiliang/QuickPadCn#1937]
**描述BUG**
对bug的清晰简洁描述。

quicker自带的这个搜索不是设置的值越大，排序越靠前吗？但是我把默认操作的值设置得最大，但是却排到很后面去了
![image](https://github.com/cuiliang/Quicker/assets/37429029/ee55625e-865e-4000-a7e0-690ab50a0578)

**重现步骤**
1.在搜索设置中，将默认操作的值设置为最高优先级
2.在搜索框输入 xss，发现没有显示最高优先级的 chrome搜索
![image](https://github.com/cuiliang/Quicker/assets/37429029/2930b1ec-c325-437f-b5f5-531445366e80)

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：最新版

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个优先级是在文字匹配分数的基础省乘以的数。 对于默认的那些条目，它们的基础分数是0，所以不会排在前面的。

**Comment by AugustTuan** [comment]
> 这个优先级是在文字匹配分数的基础省乘以的数。 对于默认的那些条目，它们的基础分数是0，所以不会排在前面的。

我能自己调这个基础分数吗

**Comment by cuiliang** [comment]
目前没有办法。 
我有点不是很理解，为什么想要把默认放前面呢？ 这里默认的设计目的，是在没有搜索结果的时候出现一些选项，如果有比较多结果，就不会出现的。

如果希望直接使用默认搜索的功能，也可以给他一个触发词，然后用触发词直接触发。
![image](https://github.com/cuiliang/Quicker/assets/1972649/24863f31-9826-47ae-abde-f4179ee24147)

![image](https://github.com/cuiliang/Quicker/assets/1972649/93a807e9-b326-41a5-9e1a-6aa95ed7d7ee)

**Comment by AugustTuan** [comment]
> 目前没有办法。 我有点不是很理解，为什么想要把默认放前面呢？ 这里默认的设计目的，是在没有搜索结果的时候出现一些选项，如果有比较多结果，就不会出现的。
> 
> 如果希望直接使用默认搜索的功能，也可以给他一个触发词，然后用触发词直接触发。 ![image](https://user-images.githubusercontent.com/1972649/249333784-24863f31-9826-47ae-abde-f4179ee24147.png)
> 
> ![image](https://user-images.githubusercontent.com/1972649/249333835-93a807e9-b326-41a5-9e1a-6aa95ed7d7ee.png)

我主要的目的就是希望输入我想查的内容，然后第一行默认就是google搜索
所以默认操作不是置顶的话，会出现一些搜索词没有网络搜素这个选项。

至于输入触发词。真的没有复制要搜的内容，直接回车来得爽
![image](https://github.com/cuiliang/Quicker/assets/37429029/6ed965f5-c619-4cb7-b38e-bd7a44253006)

**Comment by AugustTuan** [comment]
不过目前使用起来问题不大，大部分情况都能达到我想要的效果

**Comment by cuiliang** [comment]
有个触发词后置功能。 可以在末尾加上 空格@gg 
![image](https://github.com/cuiliang/Quicker/assets/1972649/7df3ab84-8e45-4b56-b4b8-07ef18da3af6)
