### ISSUE TITLE
quicker自带搜索建议

### ISSUE THREAD

**Issue by AugustTuan** [cuiliang/QuickPadCn#1938]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

quicker自带的网络搜索，可以输入关键词+空格， 进入特定网站的搜索

例如下面， 我用bb+ 空格 ，进入bilibili搜索
![image](https://github.com/cuiliang/Quicker/assets/37429029/de6e37ae-fb98-4111-b3fd-48b7d573e48b)

在我键入空格以后，底下的一推搜索提示没有消失，继续显示在这里，影响搜索的视觉体验，纯粹是干扰项
最上面的在B站内部的搜索提示反而消失了
![image](https://github.com/cuiliang/Quicker/assets/37429029/ee3722eb-12b9-4243-a17c-cb96323d8fb3)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

键入关键词+空格以后，显示效果如下，更加简洁、美观
因为我输入空格，代表我只想在这个网站下搜索，下面那一堆就没有必要继续显示了
![image](https://github.com/cuiliang/Quicker/assets/37429029/077ee83b-c71c-46db-baaa-80f448afa1ca)

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
感谢反馈，我研究下。 输入空格后第一条确实不应该消失。

**Comment by AugustTuan** [comment]
> 感谢反馈，我研究下。 输入空格后第一条确实不应该消失。

除了第一条不该消失以外，下面那一堆希望可以隐藏掉。

因为我都输出 关键词+空格了 ，就是只关心在这个网站内部搜索，底下那堆文件啥的，纯纯的干扰。🥹

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 更新了一版，但是只解决了第一个问题。
目前无法隐藏其他搜索结果，这是因为 他们在此刻都是全局搜索的一部分，所有被允许在全局使用的插件具有相同的地位。

除非为插件本身设置独立的触发词，并通过独立触发词触发搜索（如网页搜索的独立触发词为web，那么`web bd 关键词` 就只会显示百度搜索的候选项） ，无法排除其它搜索插件的结果，只能通过优先级进行控制显示顺序。

![image](https://github.com/cuiliang/Quicker/assets/1972649/dedf32f2-094a-408f-9b83-6edb275a05bd)
