### ISSUE TITLE
自定义操作窗点击标题会跳动，

### ISSUE THREAD

**Issue by peilonia** [cuiliang/QuickPadCn#1939]
![4](https://github.com/cuiliang/Quicker/assets/136886254/ebc4b221-f9f6-4c65-b57d-ccf5e4a516c4)

跳动很难定位到想要的分类

希望能不跳动

**Comment by cuiliang** [comment]
这个可能没有办法，底层控件是这样工作的。 等有空研究下。

**Comment by peilonia** [comment]
@cuiliang 好的！

**Comment by cuiliang** [comment]
研究了一下，虽然理论上有办法实现，但是会需要修改底层，产生一些不好的影响。所以目前不考虑修改了。 建议减少分类的数量。
什么情况下会用到这么多分组呀？

**Comment by peilonia** [comment]
@cuiliang 呃 主要是放了很多网址在里面，当书签用
不过东西多了，启动的时候，自定义操作窗加载的时候也有些卡顿了，
我先用别的分组方式吧，不会跳
