### ISSUE TITLE
搜索框被“另存为”窗口挡住

### ISSUE THREAD

**Issue by peilonia** [cuiliang/QuickPadCn#1940]
![image](https://github.com/cuiliang/Quicker/assets/136886254/b1ce5bf0-4d55-46e1-a0ae-b34813ebdb92)

感觉将搜索框置于所有窗口（包括另存为）前面更好些

**Comment by cuiliang** [comment]
这些窗口都是置顶的，在都置顶的情况下，没有办法控制谁在上面。 通常是后显示的在上面。
这个另存为窗口是从哪里打开的呢？如果是图片窗口的另存，可以先将图片窗口取消置顶后另存。
