### ISSUE TITLE
应用“开机自启”后依然不能自动启动

### ISSUE THREAD

**Issue by nianmommy** [cuiliang/QuickPadCn#1941]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.点击设置-开机自动启动
2.应用设置
3.重启电脑后依然不能自动启动
**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：windows 11 家庭中文版
 - Quicker版本：1.38.20

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果装了任何“管家”类产品，先卸载掉，然后设置自启选项之后重启电脑测试。

**Comment by nianmommy** [comment]
已解决，谢谢，效率很高，为你点赞
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月28日 09:40
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [cuiliang/Quicker] 应用“开机自启”后依然不能自动启动 (Issue #1941)
        
      
    
  

如果装了任何“管家”类产品，先卸载掉，然后设置自启选项之后重启电脑测试。
