### ISSUE TITLE
”已复制图片到剪贴板“的提示，会产生干扰

### ISSUE THREAD

**Issue by peilonia** [cuiliang/QuickPadCn#1942]
![image](https://github.com/cuiliang/Quicker/assets/136886254/1257e965-dfe0-4af4-879e-831e2c6481da)

有时正在专注，突然跳出一个提示，挺受影响的

**Comment by cuiliang** [comment]
这个是某个动作里的提示，可能是“剪贴板”动作，里面应该可以找到是否显示提示的选项。

**Comment by peilonia** [comment]
好的，我找找！

**Comment by cuiliang** [comment]
![image](https://github.com/cuiliang/Quicker/assets/1972649/0e603170-a708-413b-a512-20a18fbc5b9e)

**Comment by peilonia** [comment]
@cuiliang 好像不是，我暂时删除了相关动作，还是有这个提示。在“显示图片“上按ctrl+c就有

有时不想复制图片，但是焦点在显示图片上，就会产生干扰了

**Comment by cuiliang** [comment]
剪贴板动作是后台运行的，可以重启quicker之后看看还不会提示。

**Comment by cuiliang** [comment]
这个还有么？ 没有的话先close了。

**Comment by zhl111** [comment]
> ![image](https://user-images.githubusercontent.com/1972649/249368595-0e603170-a708-413b-a512-20a18fbc5b9e.png)

这个界面我怎么找不到？我也想关闭提示。我是用鼠标控制的复制粘贴，总是干扰我的下一次操作

**Comment by cuiliang** [comment]
@zhl111 截图一下什么触发方式的什么提示

**Comment by zhl111** [comment]
![image](https://github.com/cuiliang/Quicker/assets/29135984/392f1d5c-e88b-40ce-8485-25d43cf2cee5)
![image](https://github.com/cuiliang/Quicker/assets/29135984/fd44461f-ff10-4ab5-b944-f3f43fd9bc33)

**Comment by cuiliang** [comment]
修改这一条规则，改成不显示提示的那个操作。
![image](https://github.com/cuiliang/Quicker/assets/1972649/7f25ccc9-6b4f-49a7-8d0e-cae89de62f31)

**Comment by zhl111** [comment]
我不是会员，是不是就不能修改？

**Comment by cuiliang** [comment]
是的 @zhl111
