### ISSUE TITLE
“管理和排序列表”中帮助里的链接无法点击

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#1944]
# “管理和排序列表”中帮助里的链接无法点击

## 描述BUG

“计算”分类中的“管理和排序列表”可以设置“帮助按钮内容”，且支持 Markdown 语法。

我用 Markdown 语法在里面写了一个链接，但在实际运行时这个链接无法点击，而且颜色也是暗的。

请问这是 Bug，还是本来就是这样设计的呢？

## 重现步骤

我写的“帮助按钮内容”中包括以下内容：

```markdown
如果有更复杂的图标需求，可以看[这个网址](https://www.yuque.com/quicker/help/use-icon-in-actions)。
```

但当我运行时，我发现其中的链接部分是无法点击且颜色暗淡的。

[这](https://getquicker.net/Sharedaction?code=cf347820-acf5-4ef1-bc75-08db7774b6d6)是动作网址。

## 相关截图

![d792bd677d77aa32.png](https://s3.bmp.ovh/imgs/2023/06/28/d792bd677d77aa32.png)

![a708c23770388dfa.png](https://s3.bmp.ovh/imgs/2023/06/28/a708c23770388dfa.png)

## 环境信息

- 操作系统版本：Windows 11 22H2 22621.1848
- Quicker版本：1.38.20

**Comment by cuiliang** [comment]
感谢反馈，我研究下。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  已更新版本，试下看看。
