### ISSUE TITLE
取消Quicker搜索框的自动复制

### ISSUE THREAD

**Issue by peilonia** [cuiliang/QuickPadCn#1946]
Quicker搜索框在未选中搜索词时，按ctrl+c会自动复制搜索结果的某动作id，请求取消此便利，

我的实时搜索动作，会复制一些奇怪的东西，
![tmp4909](https://github.com/cuiliang/Quicker/assets/136886254/44773fc7-ae52-4e2c-ad0e-3c3a4a83e327)
编写一些选中文本相关动作，遇到搜索框也会受到影响，

请求取消此自动复制功能，或者可以在quicker搜索设置中加一个取消自动复制的按钮吗？

感激不尽！

**Comment by cuiliang** [comment]
这个应该是动作里的问题，搜索框本身没有这个处理的。

**Comment by peilonia** [comment]
@cuiliang 可是我关掉了所有事件触发，停止了所有后台动作，

在原quicker搜索窗口按ctrl+c还是复制出来了，

![image](https://github.com/cuiliang/Quicker/assets/136886254/f1d5b53b-c936-41ed-b78f-13668c0206ac)

**Comment by cuiliang** [comment]
@peilonia 按一次ctrl+c就出来这么多？

**Comment by peilonia** [comment]
@cuiliang 不是，按一次出来一次，我一直在按为了截图能截到。就是这按一次出来一次，希望能自定义关闭掉

**Comment by cuiliang** [comment]
这里会带来什么影响么？
如果搜索框选择了文字，就不会复制选项的信息。 这里的目的是为了复制文件、路径之类的信息。

**Comment by peilonia** [comment]
@cuiliang 需要判断当前没有选中文字的状态，遇到文字为空时，还能复制出内容就无法判断了

而且其他实时搜索类动作的值是多样的，复制出来没有意义

虽然可以给开发带来便利，但大部分普通用户也用不到复制出来路径这个功能

**Comment by cuiliang** [comment]
没太明白。 这时候按ctrl+c的目的是什么呢？ 
这个功能也是用户提出的，和开发没有关系的。

**Comment by peilonia** [comment]
@cuiliang 说ctrl+c是为了方便描述，我要运行选中文本模块，判断当前内容是否为空，是否选中了内容

虽然是某个用户提出的，但我认为这种便利很小，带来的干扰却不小

可以折衷方案给个按钮关掉吗？

我真的不需要这个功能，我想复制右键菜单就能复制

这种方法获取id还要刚好是排在第一位，不改变输入条件还获取不到，实在用处不大

**Comment by cuiliang** [comment]
每个人情况都不一样，但是也没办法增加太多选项，所以还是要综合考虑的或者寻找能兼容两个需求的方法。这也是我想尽量详细了解实际场景和产生的具体困扰的原因。

这里是一个通用的复制功能，比如在词典状态，就是复制的单词解释。
所复制的内容是当前选择的选项的data数据。


![image](https://github.com/cuiliang/Quicker/assets/1972649/dbdfc3b8-5d71-4d08-bb97-e689c400dad4)

**Comment by peilonia** [comment]
@cuiliang 感觉这是有用的。可是要自动纠正输入该怎么办呢？要模拟shift+方向键，判断是否选中了内容，选中了内容则执行下一步，并处理选中的内容。可是在遇到搜索框内容为空时，却依然获取到了内容，就没办法判断了。这有解决方法吗？

**Comment by peilonia** [comment]
@cuiliang 哦，我要判断的是光标是否选中了内容，既然搜索框出了自动复制的功能，说明是可以判断的，请问是怎么做到的？

**Comment by peilonia** [comment]
能给个子程序吗？多谢！

**Comment by cuiliang** [comment]
ctrl+c的时候，判断文本框里是否选择内容，如果没有选择内容就复制搜索结果的数据。 在动作里可能难以判断，我想想有没有别的办法。

**Comment by peilonia** [comment]
@cuiliang 嗯，有劳啦！

**Comment by cuiliang** [comment]
考虑到一个方案：根据ctrl+c时候键盘的物理状态，判断是模拟的还是手按的。如果是模拟的，就不去复制结果。

不过我又有一个新的疑惑。

如果输入框里没有内容，必然不会去触发 “输入纠正” 。
如果触发了“输入纠正”，那么说明必然选择了文字，或者在动作里通过shift+home之类的方式向前选择了文字，这时候也不会复制到选项的内容。
所以理论上都不应该能复制到选项的内容。

上面这个推理是什么地方存在问题呢？

**Comment by peilonia** [comment]
@cuiliang 您说的是对的！！！是我代码出错了！误以为是自动复制影响的，现在弄好了

那搜索框的自动复制对我没有不良的影响了，

就是能给个关闭“复制成功提示”的按钮吗，我做判断的时候，没选中内容时去获取文本就会触发这个提示。
此时，是不需要提示的。

如果能关闭提示就更好了！

**Comment by peilonia** [comment]
@cuiliang 还有一点就是，“用户输入模块” ，在选中了文本时，触发“显示菜单”会失去焦点，
比如下面我想把选中的ao替换为AO，却把nihao都替换了
![4](https://github.com/cuiliang/Quicker/assets/136886254/99b7e541-9691-4a54-9bcf-aa4605ca909f)

而使用“用户选择”来替换，就没有这个问题
希望也能支持下“显示菜单”

**Comment by cuiliang** [comment]
用户输入里有一个特性，是在获得焦点的时候自动选中全部内容以便于用户整个修改替换。
从录屏看，显示菜单捕获了焦点，输入框丢失了焦点，所以在菜单关闭后会重新获得焦点的时候整个选中。 
目前显示菜单模块里开启了占用焦点的选项了么？如果开启了可以尝试关闭一下。

**Comment by peilonia** [comment]
@cuiliang 您好 没有开启 我确定
![image](https://github.com/cuiliang/Quicker/assets/136886254/508f1140-e06b-40e9-9d43-ad3994691812)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  更新了一版等试下看看。

**Comment by peilonia** [comment]
@cuiliang 太赞啦！
