### ISSUE TITLE
Windows11下，“提示消息”命令无法显示消息

### ISSUE THREAD

**Issue by lkrrpd** [cuiliang/QuickPadCn#1949]
Quicker版本：1.38.20
Windows11下，“提示消息”命令
![image](https://github.com/cuiliang/Quicker/assets/32787814/7cc6edeb-6193-401f-94fb-cbb528d6bdea)
执行后无提示消息显示。

Windows10下执行正常。

**Comment by cuiliang** [comment]
重启一下电脑试试。

**Comment by lkrrpd** [comment]
后来程序崩掉了，重启程序后已恢复。

**Comment by cuiliang** [comment]
如果设置了自动运行动作，可以增加一定的延迟启动时间，或者这里下载最新版本试试，会自动增加一点延迟：
https://getquicker.net/Help/Versions
