### ISSUE TITLE
时不时快捷键被挤占

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1951]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
上大学时候体验各种新软件比较多，时不时遇到快捷键被挤占，不知道哪里出了问题，以下可供参考
是谁抢了我的快捷键？用 ctrl-alt-m 在 #WorkFlowy# 中移动条目无效，关闭了几个嫌疑 app 仍然无效，
只好安装了 OpenArk 来检查，马到成功。这是第一次使用 OpenArk，开源、免费、功能多、使用简单、全程顺利，让系统热键无所遁形😊 
来自[@善用佳软 的个人主页 - 微博](https://weibo.com/u/1188742767)
登录后查看更多内容=无语，微博非要扫码登录，或者短信验证，频繁要验证，隔了一天没登录好像都不行，老要验证，是我哪个设置没关还是？
不知道为啥短信延迟，等收到短信已经过期，后来充电接口出了问题，现在无法开机了

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
手机还没修好+喜欢账号密码登录，有什么办法不用拿起手机，用quicker扫码功能登录吗，
或者quicker出个啥脚本，绕过微博的验证，非要登录才能查看更多内容
微博APP太难用了，非官方的版本各种限制=时不时登录状态就失效
后来弃用微博了
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
老弟，看不太懂你发的内容额。 微博肯定没法用quicker扫码登录的。
