### ISSUE TITLE
“自定义操作窗”在win7可以继续往上移动吗？

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1952]
系统是WIN7  32位，quicker版本是1.38.25，

问题详情：

更新Quicker到最新版后，今天发现这个框框位置不能再往上移动了，如下图箭头示，和我的应用程序图标有干涉，会误操作，没更新Quicker前，这个框框可以随意往上移，只留一小条边，即能触发动作，也不会和应用程序图标有干涉，还请帮忙看看，谢谢 ！
之前能继续往上移动，新版本不行了
![image](https://github.com/cuiliang/Quicker/assets/27837566/837f4170-5d59-4090-9eaa-37b05dec695b)

**Comment by heloook** [comment]
记住位置等状态，希望自动判断位置是否超出屏幕边界，如果超出了，就自动往屏幕内挪挪


今天我有一个操作窗，不小心挪到屏幕外了，结果一直找不到，它记住在屏幕外的位置了

**Comment by heloook** [comment]
可能还要考虑双屏的位置问题，感觉不好弄

**Comment by cuiliang** [comment]
之前用的多少版本号？ 
这个修改是因为有一些win7下面会无法移动操作窗。WPF默认会把拖放到屏幕外面的窗口给移动回来，要想避免被移动回来，就需要加一个防止自动移动的处理；增加这个处理又会导致Win7完全无法移动窗口。 所以目前在win7下禁用了这个防止回来的处理。

**Comment by heloook** [comment]
@cuiliang 好像是1.38.21

**Comment by heloook** [comment]
因为干涉对该用户来说非常不便，他又装回1.38.21了

**Comment by heloook** [comment]
我的是win10系统，可以移动，但是却容易移到屏幕外面，记忆位置的操作窗移动外面就回不来了

**Comment by cuiliang** [comment]
我在虚拟机里又测试了半天，无论咋设置windows，1.38.21版本都没法移动操作窗。有点难办了

**Comment by heloook** [comment]
@cuiliang  他现在装的是1.38.21 电脑win7 确实是可以随意移动的

**Comment by cuiliang** [comment]
1.38.27 应该可以了。
