### ISSUE TITLE
如何把quicker的结构复制到思维导图

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1954]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
[quicker的结构复制到幕布+thebrain大脑思维导图_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1bL4y1a7uG/?spm_id_from=333.999.top_right_bar_window_history.content.click&vd_source=5218c91d17fb6c4742363001f8a1c3a3)
以前复制的结构怎么搞，搞了上面视频里面的操作之后quicker更新频率下降了，以前时不时更新尝试新功能，比较少更新了，最近更新动作更新不了，不得不更新了一些次quicker
更新后多了了一些结构，一些模块组件，怎么处理

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

有哪些模块，能不能导出文本到本地，我好导入搞到思维导图里面，具体应该怎么搞，我只有个模糊的想法
quicker比较复杂了=模块、功能、动作超级多=正适合用thebrain大脑思维导图对如何用功能模块进行规划处理，节点越多=thebrain、炬图智能图谱，有规模效应=这类的优势越大
幕布只能应对节点比较少、比较简单的情况

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
感觉整理这些没有什么意义。 
建议先浏览一遍大概有哪些模块，大概是什么功能，
然后在写动作的时候，根据需要去找模块，再详细阅读模块的文档。
