### ISSUE TITLE
“自定义窗口” 窗口面板动作在win10移动不了了

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1955]
崔大帮忙看看

窗口面板 https://getquicker.net/Sharedaction?code=e04ed4ad-f4b2-4609-ac92-08da5b516573

我在win11里是可以移动的，但是在win10里却移动不了，但这个动作我之前一直在win10里用的，一直是可以移动的
是用 https://handyorg.github.io/handycontrol 来移动的，加在关闭按钮上 hc:WindowAttach.IsDragElement="True" 

请问该怎么办呢？

加上这段辅助c#代码
`using System.Text;
using System.Windows;
using System.Windows.Input;
using System.Windows.Forms;
using System.Collections.Generic;
using MessageBox = System.Windows.Forms.MessageBox;
using Quicker.Public;

public static void OnWindowLoaded(Window win, IDictionary<string, object> dataContext,
    ICustomWindowContext winContext){
    
    win.PreviewMouseMove += (sender, e)=>{
        if (System.Windows.Input.Mouse.LeftButton == MouseButtonState.Pressed)
        {
                    win.DragMove();
           }
    };
    
    //MessageBox.Show("WinodwLoaded");
}
`

这样在win10里可以移动了，但是点击按钮却没有反应，请问如果使用这段代码，怎么让点击按钮有反馈呢？

这是哪里出了问题，两个方案哪个还是有效的，求指点！

**Comment by cuiliang** [comment]
hc:WindowAttach.IsDragElement="True"  这个应该加在Window上，然后代码里就不需要了。
![image](https://github.com/cuiliang/Quicker/assets/1972649/f0303c65-5694-424c-aaf5-c4efe15c6501)

**Comment by heloook** [comment]
@cuiliang 奇怪了。“hc:WindowAttach.IsDragElement="True" 这个应该加在Window上”

我用 https://getquicker.net/Sharedaction?code=ad87d373-43e3-4e13-c186-08daef64fc0b 测试了一下

确实可以移动，点击关闭也有反应

但是窗口面板就是不行，😂

**Comment by heloook** [comment]
@cuiliang 
![4](https://github.com/cuiliang/Quicker/assets/27837566/4bcccfbb-d0ec-4493-8ece-ef3d83ba9f93)
好像是这个hc不支持按钮的移动？用旁边的区域是可以移动的


可是之前是可以的啊

**Comment by heloook** [comment]
那就这样移动吧！不折腾了！

**Comment by heloook** [comment]
多谢！

**Comment by cuiliang** [comment]
按钮上应该是不行的，在按钮上点击不会触发窗口的 MouseLeftButtonDown 事件， WindowAttach.IsDragElement 是在窗口的左键按下事件里添加的拖动处理。  
可以试试WindowAttach.IsDragElement也添加到按钮上，不清楚这样会不会影响点击事件的触发。

**Comment by heloook** [comment]
@cuiliang 好的！
