### ISSUE TITLE
以插值的方式输入列表，不能成功进行列表操作

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1956]
如下图：
![4](https://github.com/cuiliang/Quicker/assets/27837566/f67fa787-7bbb-47b4-b954-5d1b31ee4ba8)

**Comment by cuiliang** [comment]
只能选变量。
这样的话是对一个临时列表做了操作。

**Comment by heloook** [comment]
@cuiliang 好的，还是希望能够直接处理插值进来的列表，有时会忘记，不知道的话就不知道哪里出bug了
或者限定一下这里的输入？不能插值
