### ISSUE TITLE
发送文本到窗口，无法发送空文本

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1957]
有时候需要使用发送空文本到窗口，达到删除选中文本的效果。

给个不能发送空文本的错误提示，也可以

还是希望能支持发送空文本

**Comment by cuiliang** [comment]
这时候直接模拟delete是更合适的方法。


Hosea Plyler ***@***.***>于2023年7月8日 周六05:36写道：

**Comment by heloook** [comment]
好的，或许补充一个不能发送空文本的提示更好一些，有的时候变量可能变成空值，发送不了，就不清楚哪里出bug了

**Comment by cuiliang** [comment]
我考虑了一下，这里确实也不能修改成自动发送delete。 如果文字在插入模式，会意外的删掉后面的字符。
对复制粘贴模式，应该可以修改一下试试。
