### ISSUE TITLE
动作中使用公共子程序，公共子程序中使用本地子程序

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1961]
分享出来的动作，其他用户会找不到此本地子程序

不清楚是不是确切如此，但我把该本地子程序也转化为公共子程序，再分享出来，其他用户确实是能找到了

**Comment by cuiliang** [comment]
这个有点复杂，没有考虑过这种情况，所以具体什么表现我也不是很确定。😂
可以把这个出错的动作网址发来我试下看看。
一般建议分享的子程序是独立和完整的。

**Comment by heloook** [comment]
@cuiliang  奇怪了。我又专门新建个动作测试了一下，是可以的

但我不清楚是不是因为我在原账号执行过一次，有缓存了？您试一下，如果也是可以的，那分享后调用子程序就没问题

https://getquicker.net/Sharedaction?code=ad87d373-43e3-4e13-c186-08daef64fc0b

**Comment by cuiliang** [comment]
这两个子程序应该都是嵌入到公共子程序里的。
![image](https://github.com/cuiliang/Quicker/assets/1972649/f0ea0ae0-5594-4430-8b87-9c71bb94abe7)

**Comment by heloook** [comment]
@cuiliang 嗯，我之前知道会不显示，但可以执行成功。这次我遇到问题是执行的时候提示找不到子程序，但测试这次又执行成功了，

如果您那里也执行成功了，那估计不是这个问题

**Comment by cuiliang** [comment]
这个动作是可以执行成功的。 
之前有一种情况，就是公共子程序和动作本身里面都使用到了另一个公共子程序，可能会造成错误。

**Comment by heloook** [comment]
嗯，
其他账号运行我一个动作遇到了一个找不到子程序的提示，然后我把找不到的子程序转成公共子程序重新发布，就找到了。
既然测试通过，就没问题了。多谢！

**Comment by heloook** [comment]
@cuiliang 我刚想到可以把出问题的版本找出来，是这个，崔大看下，这个版本，在我电脑上运行成功，但是分享出来后提示找不到子程序

https://getquicker.net/Sharedaction?code=93acdb4b-a10e-4347-71ed-08db80e64bee



https://github.com/cuiliang/Quicker/assets/27837566/356a1392-81f4-4dbb-ace0-c60da4f636be

**Comment by heloook** [comment]
还有一点比较奇怪，我明明在截图，却提示运行子程序“截图并保存”失败，这个子程序中还有一个公共子程序，不知是否有关

**Comment by cuiliang** [comment]
嗯，“截图并保存” 引用了另外一个公共子程序。这个子程序没有成功嵌入。

**Comment by heloook** [comment]
好的，原来如此
