### ISSUE TITLE
真心希望“已复制图片到剪贴板”的提示能给个开关

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1962]
模拟了ctrl+c就会冒出来，
突然冒出消息有点干扰思路了
我确定是quicker内置的，其他动作确定已排除

https://github.com/cuiliang/Quicker/assets/27837566/68ee06ad-a2ba-4de4-8dc8-4d6771129ddb

**Comment by cuiliang** [comment]
图片窗口有焦点的时候，ctrl+c 复制图片会有这个提示。如果这时候不是要复制图片窗口的图片，需要将焦点移开。

**Comment by heloook** [comment]
@cuiliang 崔大！ 我是是要运行动作，主动复制这张贴图，来对贴图进行图片处理，

不要这个提示就完美了！

**Comment by cuiliang** [comment]
显示之前先复制是不是可行呢？

**Comment by heloook** [comment]
@cuiliang 如果是仅处理一张电脑里的图片是可以做出动作的，但如果屏幕上有很多待处理的贴图，就只能从贴图复制了

而且有些图想先贴出来看看，再决定是否处理

**Comment by heloook** [comment]
还比如截图动作，我想再调用第三方软件处理截图，也最好是直接从贴图上复制，方便

**Comment by cuiliang** [comment]
好的，等去掉这个提示。

**Comment by heloook** [comment]
多谢！！！
帅！！！！！！

**Comment by cuiliang** [comment]
已更新1.38.30版本。
