### ISSUE TITLE
文本窗口，我有时也会遇到这个问题

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1964]
![image](https://github.com/cuiliang/Quicker/assets/27837566/609ed501-c42f-4fbd-b356-fc31d273cf32)

https://getquicker.net/Common/Topics/ViewTopic/19168

崔大看看

**Comment by cuiliang** [comment]
这个可能是windows或输入法的bug，我偶尔也会遇到，不是在quicker里。
另外Quicker的窗口本身权限会高一点，也可能也有一定的关联。

**Comment by heloook** [comment]
好的！
