### ISSUE TITLE
鼠标移至quicker仪表盘导致仪表盘消失

### ISSUE THREAD

**Issue by SuFu123** [cuiliang/QuickPadCn#1965]
**描述BUG**
鼠标移至quicker仪表盘时会自动触发模糊，导致quicker仪表盘直接消失；双击图标和快捷键呼出都存在上述问题

**重现步骤**
1.
2.

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/77719946/b94a8693-11d3-4267-8dc6-8db94686b49f)
👆这是正常的界面
![image](https://github.com/cuiliang/Quicker/assets/77719946/f08f54f7-0958-4fa7-ac0a-f40ea5b16e76)
👆鼠标选中某一动作其他动作会触发模糊，且无法启动动作

**环境信息:**
 - 操作系统版本：Windows
 - Quicker版本：latest

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
仪表盘上点击动作它就会自动消失的。 如果要触发什么动作，直接在动作里使用 运行其他动作的模块。https://getquicker.net/kc/help/doc/runaction
