### ISSUE TITLE
为什么使用多线程的耗时比正常执行还要长呢？

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1966]
有几个与运行顺序无关的步骤
想着多线程可以节省时间

但是竟然耗时更长

**Comment by cuiliang** [comment]
多线程只有在需要外部IO，比如网络请求之类的场景下才是合适的。不然其引入的额外负担反而会有负面的影响。

**Comment by heloook** [comment]
@cuiliang 原来如此！好的！
