### ISSUE TITLE
如何判断两个词典相同？

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1967]
![image](https://github.com/cuiliang/Quicker/assets/27837566/b723dbe3-46ad-4ec3-8a80-48613df3c60f)

我把一个词典赋值给另一个词典

然后判断两个词典是否相同
结果竟然是两个词典不同？

**Comment by heloook** [comment]
用toString()可以判断成功了

但词典也应该正常判断，请求支持下词典是否相同的判断

**Comment by heloook** [comment]
还是不行，
两个不同的文本，竟然判断出是相同的

不知道是不是我弄错了
还是文本太长了

**Comment by cuiliang** [comment]
对比 ToJson() 的结果试一下。  什么情况下需要对比词典呢？

**Comment by heloook** [comment]
@cuiliang 确实不常见，

我的情况是这样的

一个本地数据词典，一个云状态数据词典 

有一个控制是否云同步的按钮，

之前一直是不自动云同步的，今天想打开自动云同步
这个时候对云同步数据和本地数据进行比较。

如果不同，则解析词典数据，使其中各变量相同，达到同步效果

然后以后就不用判断了，这是时候，如果直接能判断词典是否相同，如果相同，后面的合并就不再需要了
可以减少启动时间


我初步试了一下，ToJson()确实是可以，成功了
toString()没有发现的不同 ToJson()发现了

**Comment by heloook** [comment]
效果不太显著，没减少多少时间


判断出相同后略去了后面的步骤，几乎没有节省时间，相当于白弄了
时间基本还是消耗在云同步取值上

**Comment by cuiliang** [comment]
ToString() ，对于复杂类型会得到 类型名称，所以不能用来比较对象。
本地的处理步骤通常都是挺快的，这类一般也不需要过多优化，只要动作能正常运行，就是最理想的。😂

**Comment by heloook** [comment]
@cuiliang  哦哦 好的好的
