### ISSUE TITLE
这个提示不太对，我子程序都在啊

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1968]
我也不知道怎么会出来这个提示，

https://github.com/cuiliang/Quicker/assets/27837566/104b2895-fed1-4b22-b1cf-db970acd1184

**Comment by cuiliang** [comment]
奇怪，这个是怎么出现的呢？我这里没能复现
这个提示是这个位置的控件找不到对应的子程序了，有一种可能是电脑内存压力比较大，释放了一个子程序的内存引用。
![image](https://github.com/cuiliang/Quicker/assets/1972649/90c6c48c-817c-405b-98a4-61d35bcc6350)

**Comment by heloook** [comment]
就是编辑完一个子程序准备保存的时候，我遇到了好几次了，您应该也会遇到，没有大影响，您留意下应该就行

**Comment by cuiliang** [comment]
好的。
下次如果遇到，可以看下windows和quicker的内存占用情况， 我看下是否和内存情况有关，还是别的原因。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 更新了一版，把这个提示隐藏掉了。
这个的主要目的是为了在修改子程序名称的时候找到对应的标签进行更新。里面存的引用在内存比较紧张的时候会被.net释放，如果释放了就会提示。

**Comment by heloook** [comment]
赞！
