### ISSUE TITLE
悬浮动作后=无法还原点击悬浮前的鼠标位置

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1969]
**描述BUG**
对bug的清晰简洁描述。
最近正在把为知笔记、evernote回收站的、大量的乱七八糟的文章、各种碎片发送到通义千问、星火、百度文心，废物利用，搞的星火被永久禁用了，好在通义没问题
部分回收站内容以前误删了，进行恢复，我发现悬浮动作后=还原鼠标位置有问题=点击没有打开evernote的删除，把quicker悬浮动作的设置打开了

以前也发现了这个问题=但是搞忘记记录 发送了，动作很简单的就是替代人的点击，如果没有quicker要多点3次
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

![天若_20230715115640](https://github.com/cuiliang/Quicker/assets/44609485/5a35bbb9-bbe7-4546-a467-6e51db9ccb92)

![天若_20230715120031](https://github.com/cuiliang/Quicker/assets/44609485/55dbd9fb-bb73-45e7-b5ad-2f97111e574c)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
悬浮的按钮是不支持的，因为无法确定触发位置。 
悬浮的情况下，触发位置就是悬浮按钮上点击的位置。所以无法恢复鼠标
