### ISSUE TITLE
置顶的文本窗口会遮挡新版微软拼音输入法的技术难题，是不是要攻关一下了

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1970]
这个太困扰人了

**Comment by heloook** [comment]
跪求啊

**Comment by cuiliang** [comment]
这个层级是windows控制的，程序里没有可以控制的地方。
目前似乎搜狗输入法没有这个现象。

**Comment by heloook** [comment]
好的，

对于置顶的文本窗口，可不可以加个选项？

一旦文本窗口获得焦点，就自动取消置顶，一旦失去焦点，就自动置顶？

这样就能保证打字的时候不会遮挡输入法，也可以保证窗口一直在最前

**Comment by cuiliang** [comment]
这会产生别的问题，如果还有别的置顶窗口，文本窗就会被盖住造成无法输入了。

**Comment by heloook** [comment]
@cuiliang 确实
