### ISSUE TITLE
文本窗口贴边收纳再弹出，经常出现顶栏显示不全的现象

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1971]
![image](https://github.com/cuiliang/Quicker/assets/27837566/9e250c38-b821-4fa0-85ca-9bf97fb744fc)

往屏幕上端收纳出现了这个问题，其他三条边没有好像遇到这个问题

系统是win10

**Comment by cuiliang** [comment]
这是WPF的固有特性，而且很难去除。 通过过滤win32消息强制去除还会导致在win7下无法拖动窗口。

**Comment by heloook** [comment]
@cuiliang 好的

**Comment by cuiliang** [comment]
有点看错了😂，那个固有特性是移动出屏幕顶端之外自动回弹到屏幕里的现象。 
显示不全不是很清楚什么原因，可能是渲染没有更新，我刚试了一下win11下似乎没有这个现象。
