### ISSUE TITLE
在动作库里搜索“关闭其他”，却搜不出来这个动作

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1972]
https://getquicker.net/Sharedaction?code=e9cbe08a-a84f-4057-2818-08d82ceb710a

**Comment by cuiliang** [comment]
可以啊 
![image](https://github.com/cuiliang/Quicker/assets/1972649/82f2eb25-dfc2-45aa-beda-a43adc9fed5e)

![image](https://github.com/cuiliang/Quicker/assets/1972649/bb9e9aa7-d7fe-4ade-9de7-979e035472eb)

**Comment by heloook** [comment]
![image](https://github.com/cuiliang/Quicker/assets/27837566/1fec759e-20d7-44be-b6e3-536572757f35)

我喜欢在这里搜

没有

@cuiliang

**Comment by cuiliang** [comment]
因为写错字了，它 != 他

**Comment by heloook** [comment]
@cuiliang 哦哦哦哦哦哦哦
