### ISSUE TITLE
运行或打开 无法激活微信窗口

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1974]
仅在有微信窗口打开时，才可以激活，
微信窗口关掉，但在托盘上，却激活不了。

同样的情况，飞书却没有问题。

我记得以前没这个问题的

![图片_20230722182846](https://github.com/cuiliang/Quicker/assets/27837566/a2b07fa9-176d-4e89-892b-b4087175963d)

**Comment by cuiliang** [comment]
我刚测试没问题。 你的quicker和微信是多少版？
![image](https://github.com/cuiliang/Quicker/assets/1972649/ed5840ab-c3bc-48d3-ad96-e4d9f1900e38)

**Comment by heloook** [comment]
![image](https://github.com/cuiliang/Quicker/assets/27837566/efd01dc3-512f-4eb6-946a-8fdfe8782a8d)

quicker 分别试了1.38.35 1.38.31 

系统是win10

我再录个屏

**Comment by heloook** [comment]
@cuiliang

我这边又可以了！不明白刚才是怎么回事，
打扰了！

**Comment by cuiliang** [comment]
刚才有报错么？ 还是说重新启动了微信？还是没反应？

**Comment by heloook** [comment]
我刚才确确实实是激活不了，

我试了几个动作，两个quicker版本都不行，

没有报错

我也没有做什么特别的举动，它自己就好了！

@cuiliang

**Comment by heloook** [comment]
@cuiliang

我记得我之前好像用句柄激活过一个微信窗口，
我以为是微信主窗口，
结果是一个只在任务栏有图标的窗口，却没有界面

然后我右键把它关闭了

可能是这个影响的？

我再观察观察，如果再没遇到问题就说明quicker没问题

**Comment by cuiliang** [comment]
如果没有报错，可能是因为找到了某些奇怪的窗口。 
之前有遇到过输入法的窗口。 另外微信也可能会有透明窗口在桌面上，如果主窗口找到了这些，会误以为主窗口进行激活。
微信、QQNT，的窗口都有些奇怪了，用的很多奇怪的非标准win32的窗口方式。
如果下次遇到，可以使用“激活进程主窗口”这个模块调试运行一下，会显示窗口句柄。 然后可以使用spy++工具查找句柄，看下这个窗口倒是什么。

**Comment by heloook** [comment]
@cuiliang 好的，我留意一下

**Comment by heloook** [comment]
https://github.com/cuiliang/Quicker/assets/27837566/7e197bb8-8115-4bca-a614-421a0b7ac50c



@cuiliang 

这次开机后，又出现了！

过了一会又好了！

不能激活的视频我录了

**Comment by heloook** [comment]
https://github.com/cuiliang/Quicker/assets/27837566/25197039-0be4-4b51-bd5f-656493fa6690

**Comment by heloook** [comment]
现在又好了，输出的主窗口句柄还是0，但是能激活

**Comment by heloook** [comment]
还没来得及用“激活进程主窗口”模块，它自己就好了

**Comment by cuiliang** [comment]
😂

**Comment by heloook** [comment]
@cuiliang 

有报错了！（之前也应该是这个，我没勾选“失败后停止”）

![image](https://github.com/cuiliang/Quicker/assets/27837566/4fab886e-37c5-4a87-987f-e3dd02b979ab)



----

我接着运行“激活进程主窗口”，却可以激活！就是微信窗口！

但是用“运行或打开”，却不行！
![image](https://github.com/cuiliang/Quicker/assets/27837566/ca801fe4-8483-4cdb-9d76-3744ed669bd3)

**Comment by heloook** [comment]
我不会用spy++

“激活进程主窗口”获得的句柄是
66558

“获取窗口信息”确认是WeChat

但spy++里面微信却找不到这个句柄（不知道是不是因为我没有对）

![image](https://github.com/cuiliang/Quicker/assets/27837566/d7011793-c8c6-4a9e-9717-a3dd6c6626f3)

**Comment by heloook** [comment]
![image](https://github.com/cuiliang/Quicker/assets/27837566/3b370a71-f129-4de5-a965-432412114629)

**Comment by heloook** [comment]
我用“激活进程主窗口”模块了

**Comment by cuiliang** [comment]
spyxx里需要写16进制查找

Hosea Plyler ***@***.***>于2023年7月23日 周日14:48写道：
