### ISSUE TITLE
希望增加 在线病毒查杀功能 的 动作。

### ISSUE THREAD

**Issue by 1tonsilla** [cuiliang/QuickPadCn#1975]
**需求描述**

对于单个文件可疑是病毒，目前可以使用在线杀毒软件工具（汇总几十种杀毒工具），但是目前需要打开网址（https://www.virscan.org/ 之类的），然后上传文件。很麻烦。

**描述你想要的解决方案**
希望能增加，选中某个文件，调用quicker动作，自动上传该文件到 https://www.virscan.org/    这种网站分析，减少操作步骤。

**描述您考虑过的替代方案**
目前未考虑有其他快捷方案（可考虑多增加几个在线杀毒引擎，例如这篇文章讲的几个https://zhuanlan.zhihu.com/p/129890374）

 **其他上下文**
![image](https://github.com/cuiliang/Quicker/assets/33661246/b7e708db-9603-4395-93b6-7babaac0bc03)

**Comment by cuiliang** [comment]
这个应该是在动作里实现的功能，不是软件本身所提供的功能。
这个建议看下杀毒网站有没有提供API，如果提供API，可以使用http模块上传文件并得到结果。

**Comment by 1tonsilla** [comment]
> 这个应该是在动作里实现的功能，不是软件本身所提供的功能。 这个建议看下杀毒网站有没有提供API，如果提供API，可以使用http模块上传文件并得到结果。

好的，我找了下，他们网站不提供私人使用api，只对接公司，算啦，谢谢老哥

**Comment by cuiliang** [comment]
https://developers.virustotal.com/reference/overview  可以试试这个网站
