### ISSUE TITLE
在Sticky Notes（便笺）中快捷键添加白名单后无法使用快捷键

### ISSUE THREAD

**Issue by xuanran-z** [cuiliang/QuickPadCn#1976]
**描述BUG**
在Sticky Notes（便笺）中快捷键添加白名单后无法使用快捷键

**重现步骤**
1.设置某个动作
2.然后在quicker的便笺“上下文面板”中进行设置快捷键，对便笺程序设置白名单，无法使用，但全局使用不会这样

**相关截图**
![Snipaste_2023-07-25_12-20-27](https://github.com/cuiliang/Quicker/assets/139668677/091f51d5-da04-438c-a909-f589c7a1d31e)
已尝试多种可能的程序，还是这样
![Snipaste_2023-07-25_12-21-06](https://github.com/cuiliang/Quicker/assets/139668677/a7c67db8-39d9-41cf-a897-8564d1e89870)
只是一个简单的加粗快捷键

**环境信息:**
 - 操作系统版本：Windows 10 专业版   19045.3208
 - Quicker版本：1.38.31

**附加信息**
在其他软件正常

**Comment by cuiliang** [comment]
UWP程序很难检测到实际进程名。 可以试试写 microsoft.notes
