### ISSUE TITLE
希望新增：高亮修改此变量的步骤

### ISSUE THREAD

**Issue by moroal** [cuiliang/QuickPadCn#1977]
**需求描述**
场景：编写quicker脚本，定义了变量，并且后面有做修改。
需求：我想知道哪些步骤修改过这个变量，免得一步步往回找。

**描述你想要的解决方案**
高亮修改此变量的步骤（目前有高亮【使用】此变量的步骤）

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  
1.38.37版本增加了高亮赋值给变量的步骤功能。
这不包含表单等可能直接修改变量内容的情况。
