### ISSUE TITLE
能统计场景数量吗+火狐浏览器插件

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1978]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
以前安装尝试了好多软件，搞了好多场景和面板，最近卸载了一些软件，不小心把谷歌浏览器也给强删了。onetab1个多月的信息没了，连带插件里还有好多、谷歌浏览器里面保存的好多信息都没了。
好多软件包括官方的谷歌浏览器老是默认安装在C盘，快被撑爆炸了。虽然后来有绿色版本的谷歌浏览器，但是官方版本里面保存了好多信息，转移不方便，所以之前没搬

目前在用火狐浏览器=https://addons.mozilla.org/zh-CN/firefox/search/?q=quicker 搜了下还没有火狐的插件

目前场景数量有多少能自动统计吗
![图片](https://github.com/cuiliang/Quicker/assets/44609485/d50c6a98-4e16-4636-8478-500cfc715a40)

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
看不太懂。

**Comment by Immortal-Sty** [comment]
火狐有扩展的。

![2023-12-03 12-38-04](https://github.com/cuiliang/Quicker/assets/94347641/aac14cee-36b0-43b0-b4df-d32adf6a3670)

在[这里](https://getquicker.net/KC/Help/Doc/chromecontrol#ws96y)。
