### ISSUE TITLE
问题摘要 内存泄漏啦

### ISSUE THREAD

**Issue by LbGit628** [cuiliang/QuickPadCn#1979]
**描述BUG**
对bug的清晰简洁描述。
风扇狂转，任务管理器查看，处理占用几乎没有，但内存占用2993mb，显然是内存溢出了。正常是89mb

**重现步骤**
1.我笔记本电脑一直是没有关机的，第二天打开屏幕的系统唤醒，然后我进入工作，一会后，电脑风扇呼呼的，打开管理器一看Quicker的内存占用达到了2993mb，原因不详，环境：win10 22h2 磁盘快满了，电脑使用睡眠
2.我强制退出它后，内存恢复至正常状态，电脑风扇还在狂转。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
奇怪，截图不能上传提示 Something went really wrong,and we can't process that file.Try again

**环境信息:**
 - 操作系统版本：window10 22h2
 - Quicker版本：1.38.31

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
是否有在运行动作？有没有设置启动quicker的时候自动运行动作？
如果有需要长时间循环的动作，可能会产生类似现象。如果没有运行动作，仍然出现的话，可以尝试复现一下，
如果可以复现，请在内存比较大的时候，在任务管理器中创建一个转储文件，压缩一下放个网盘，我这里找工具分析一下。

**Comment by LbGit628** [comment]
quicker就挂在后台运行，没有设置自动运行动作，就那天发生了一次。没有再次复现

**Comment by LbGit628** [comment]
当时出现的，quicker的任务管理器查看的截图
![内存泄漏了](https://github.com/cuiliang/Quicker/assets/106576712/8f10c29d-ed4f-413f-9c66-371b8639898b)

**Comment by cuiliang** [comment]
确实不是很正常，下次遇到点这里：
![image](https://github.com/cuiliang/Quicker/assets/1972649/56f80082-1dc2-47f5-b1de-74916e251920)

**Comment by cuiliang** [comment]
后来的版本修改了线程模型，应该解决了此问题。 如果使用新版仍然出现，请再reopen
