### ISSUE TITLE
鼠标键盘录制后以倍速播放

### ISSUE THREAD

**Issue by sjhsbhqf** [cuiliang/QuickPadCn#1981]
提供一个倍速按钮，在播放录制的动作时，以更快速度进行。

因为人手操作的时候速度肯定比较慢，跟不上需求。

**Comment by cuiliang** [comment]
如果是自己写动作，可以通过参数控制。
![image](https://github.com/cuiliang/Quicker/assets/1972649/493ebc87-4fb7-4bd6-b3dc-ebc017ac0c35)

**Comment by sjhsbhqf** [comment]
> 如果是自己写动作，可以通过参数控制。 ![image](https://user-images.githubusercontent.com/1972649/257126276-493ebc87-4fb7-4bd6-b3dc-ebc017ac0c35.png)

你好，我用的是软件自带的那个录制。
![image](https://github.com/cuiliang/Quicker/assets/41407099/7f3d3b07-0a22-48db-9ddc-283efef56b9c)

**Comment by cuiliang** [comment]
录制的动作，可以编辑，在里面修改参数。

sjhsbhqf ***@***.***> 于2023年7月31日周一 13:48写道：

**Comment by sjhsbhqf** [comment]
有时候我不想专门创建一个动作设置录制重放的参数，而是直接用软件自带的那个录制和播放小窗口。

毕竟创建动作还需要考虑到空间够不够

**Comment by cuiliang** [comment]
找动作，或自己写动作。 
https://getquicker.net/Sharedaction?code=40205740-6c06-45c6-b583-08d79c85436d
