### ISSUE TITLE
能够给每天电脑保存当前设置的功能

### ISSUE THREAD

**Issue by zhangwd1985** [cuiliang/QuickPadCn#1982]
**需求描述**
登录不同的电脑 里面的软件文件的路径都不同 软件版本也不同，硬件也不同 ，这样每次都同步导致很多都用不了

**描述你想要的解决方案**
希望登录每台电脑做得设置都可以保存，登录不同的电脑调用不同的设置

**Comment by cuiliang** [comment]
如果数据完全不同，请使用不同的账号。
如果部分不同，可以参考 https://getquicker.net/KC/Manual/Doc/data-sync#ThGPb

**Comment by Vstory** [comment]
> 希望登录每台电脑做得设置都可以保存，登录不同的电脑调用不同的设置

不想多账号。宁愿单独买个槽位。😊
