### ISSUE TITLE
问题摘要 Quicker可用内存不足或内存碎片过多

### ISSUE THREAD

**Issue by LbGit628** [cuiliang/QuickPadCn#1983]
**描述BUG**
对bug的清晰简洁描述。
我的笔记本突然弹窗：Quicker 可用内存不足或内存碎片过多，请重启Quicker或Windows
我的笔记本是16g的内存，后台挂了两个vs2022 ，一个eage浏览器大概挂着20个网页。Apple Music ,微信 扣扣 ，内存使用任务管理器约80%。点击Quicker的弹窗确认按钮后，使用Ctrl 键呼出 quicker操作板一片空灰白。重启系统后正常。但不久后，我的另一台台式机也出现改弹窗(弹窗有三个)。

**重现步骤**
1. 不知
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![quicker警告](https://github.com/cuiliang/Quicker/assets/106576712/c6158c2e-cae2-495c-9ac5-27e4f71e4e7c)

**环境信息:**
 - 操作系统版本：window10 2022
 - Quicker版本：1.38.35

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
底层报OutOfMemory 异常了，分配内存失败。

如果修改过windows虚拟内存设置，恢复一下默认。其它也没有什么解决办法
