### ISSUE TITLE
打开网页的默认浏览器无法修改

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1984]
**描述BUG**
对bug的清晰简洁描述。
尝试这些方法：1）重启电脑 2）修复windows 的默认浏览器设置， 3）在要使用的浏览器设置里找“设置为默认浏览器”的功能。
[打开网址动作失效 · Issue #1933 · cuiliang/Quicker — Mozilla Firefox](https://github.com/cuiliang/Quicker/issues/1933)
不行，这个我早就试过一些次，不知道为啥就是不显示火狐浏览器的，目前在用火狐，设置项被其他的浏览器霸占了，但是那些浏览器早就卸载了，不知道为啥默认设置里还有位置
好多软件老是默认安装在C盘，挤爆了，前阵子清理不小心把谷歌浏览器也连带删除了，
好多浏览器插件里面本地保存的数据都没了
损失巨大=好些个月、年的数据没了、没有云账户进行同步的都没了、有的同步没设置好，发现无法从云端同步到插件=根本没用
谷歌浏览器老是默认C盘，所以现在在用火狐浏览器，quicker没有火狐的插件
使用人数最多的浏览器，谷歌、火狐firefox、还有一些其他的很多浏览器我都安装尝试过，不过主要的还是这2个
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
不太懂在说的啥内容，请截图标注一下。 另外这个和quicker似乎也没有关系。

**Comment by kunpeng9** [comment]
> 不太懂在说的啥内容，请截图标注一下。 另外这个和quicker似乎也没有关系。

![图片](https://github.com/cuiliang/Quicker/assets/44609485/c713d307-fe56-415e-a998-db729739e087)
没有火狐firefox的图标，
以前的一些动作打开网址老是用的谷歌的，这个叫没有关系？目前改用火狐浏览器了

**Comment by cuiliang** [comment]
重装一下火狐试试，安装的过程可能会有提示让设置默认浏览器的界面。
