### ISSUE TITLE
如何用quicker减少键盘鼠标点击次数、手指移动距离 里程

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1985]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
由于过去的一些年应试教育=小学到高中非常忽视体育课，原来课就非常少还各种删减，或者说课表有体育课但实际被其他课老师霸占了
身体比较差=很容易疲劳、所以产生了迫切的精力管理的需求=我非常非常希望尽可能的减少键盘鼠标点击次数+移动距离
目前国内的运动健康、精力管理等各领域和国外比=非常弱、之前花了几百块买的小米手表损坏了充不进去电+统计的数据信息维度也太少了，之前看了下苹果的手表发现也不太行，数据较少
quicker的快捷键功能模块、悬浮动作减少了大脑记忆、回忆的次数、≈起到了类似于工业机器人的作用

之前记录过几次=最近一直在用WhatPulse
https://github.com/cuiliang/Quicker/issues/1918
https://github.com/cuiliang/Quicker/issues/1856
怎么能说是无关呢
WhatPulse、KMCounter.exe 、WinOMeter.exe下载下来=用一些天=体会下就知道了
WhatPulse最完善=会员才能使用更多的功能=400多还是多少来着搞忘记了 太贵了、其他的几个各有特色但是都比较简陋好些年都不更新了、quicker的动作点击统计功能好久都没优化过了=能不能更细分一些

![图片](https://github.com/cuiliang/Quicker/assets/44609485/1f2cbfed-7d81-4eec-8879-6b18f93f3ab5)
WhatPulse的网页视图显示更多的数据，但是要会员才能无限制使用

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。
在知乎还有搜索引擎搜下才发现早就有了，国内有一些写过体验文章，但是我的视野没有扩张、没有注意到这个地方，之前记录了一些精力管理的任务到滴答清单=实践效果不太好
知道这几个软件太迟太迟了=多浪费了好多好多的精力、希望quicker可以吸收这几个软件的部分功能
https://www.bilibili.com/video/BV1a54y1s72k?p=2 之前搬运的视频，也可以参考，之前体验了一些国外的软件还有网站服务=发现可视化程度、效果领先国内好多好多

2004-2023 WhatPulse. Made with ❤️ by @smitmartijn=还有另外2个软件没有查发布的日期，
国内没这类软件或者很不完善，04年就有了，算下来19年快20年了
美国进入信息化比中国早的多、80年代就开始大规模普及电脑，我是15年后才有个人电脑的，比美国那边晚了20到30年
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

![图片](https://github.com/cuiliang/Quicker/assets/44609485/88bf7c46-f34d-4c2f-9d21-bca51f2741e4)
![图片](https://github.com/cuiliang/Quicker/assets/44609485/ed9f0370-a588-4200-8c6e-8b0c8d308392)

昨天的鼠标点击次数

**Comment by cuiliang** [comment]
暂无这方面的计划哦。
