### ISSUE TITLE
问题Issues的模版

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1986]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
问题Issues的模版什么时候能更新下=用了几年来着，都没什么变化，要不修改下模版
**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
模板只是一个示例，目的是让提交人详细描述问题。 
比如现在这个帖子，就没有详细描述问题，里面不适用的内容也没有移除。
