### ISSUE TITLE
希望搜索框默认不显示历史的搜索结果

### ISSUE THREAD

**Issue by HeMOua** [cuiliang/QuickPadCn#1987]
**需求描述**
（1）希望换出搜索框默认不显示历史的搜索结果，而只是一个干净的搜索框界面。
（2）搜索根据历史的关键字匹配程度展示结果

**描述你想要的解决方案**
（1）使用Everything搜索时，它默认显示一些历史的搜索结果，而有时搜索的东西不希望它展示在这个结果界面上，希望设计界面能提供一个按钮可以切换是否展示历史搜索结果
（2）假设我第一次搜索关键字为 `keepass*` ，并选中了 `keepassxc.exe` 这个软件，我希望我第二次搜索时我输入关键字 `kee` ，此时搜索结果就能展示出 `keepassxc.exe` 这个软件。就是优先展示与历史搜索关键字匹配程度最高的结果

 **其他上下文**
当前的搜索功能设置如下：
![image](https://github.com/cuiliang/Quicker/assets/38286650/6cac8c86-5cd1-4594-a397-fc38fb3b63fb)
![image](https://github.com/cuiliang/Quicker/assets/38286650/1aa425a9-bdeb-4fff-957a-b04eb2d83a90)
希望不要展示历史结果，而是一个光秃秃的搜索框
![image](https://github.com/cuiliang/Quicker/assets/38286650/34da0e7f-85ec-4900-981f-20a0d7d4c9e6)

**Comment by cuiliang** [comment]
![image](https://github.com/cuiliang/Quicker/assets/1972649/a06c74d4-f62f-46ec-80ff-c929698455e1)

**Comment by HeMOua** [comment]
哦哦，好的，不显示搜索历史的我真没注意到

**Comment by HeMOua** [comment]
第二点有解决方案吗，每次搜索东西时必须搜的特别全才能显示结果，之前用的火萤酱只要第一次输入关键词并选中，第二搜索时输入一个**更短**的关键词就能显示结果，这个感觉还是很好用的
