### ISSUE TITLE
希望事件触发的动作不出现在搜索框最近动作中

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1988]
理由：事件触发的动作在后台触发，而搜索框的最近动作是方便用户最近的主动操作的，

随着事件触发动作的增多，搜索框中最近动作，用户主动触发的动作几乎不能置顶显示了，

对Quicker搜索框便利性的产生了较大的干扰

**Comment by cuiliang** [comment]
有时候会需要从历史记录里查看自动触发了啥动作，所以暂时也不准备去除这个了。 
后期考虑增加选项吧。

**Comment by heloook** [comment]
@cuiliang 可是，根据我的理解，最近使用的动作是方便再次触发的，而不是用来看的

**Comment by cuiliang** [comment]
永远都有人在同一个功能上发掘不同的用途😂
