### ISSUE TITLE
搜索框里全是事件触发的动作，老大不拯救一下吗？

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1989]
[图片](https://files.getquicker.net/_sitefiles/kb/sharedaction/ad87d373-43e3-4e13-c186-08daef64fc0b/2023/08/19/094407_36130_%E5%9B%BE%E7%89%87_20230819094223.jpg)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.39.5 里处理了一下，试试看看还会不会记录。

**Comment by heloook** [comment]
@cuiliang  太棒啦！
