### ISSUE TITLE
轮盘暗色了，编辑动作界面还是白色的

### ISSUE THREAD

**Issue by kunpeng9** [cuiliang/QuickPadCn#1990]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。
总算有黑夜模式了
之前在设置里面搜索暗或者黑夜之类的都没有搜到
 暗色模式（限专业版）功能预览。 目前可通过托盘菜单（有轻微bug刚开始需要切换两次才能变成暗色），或在组合动作中使用Quicker操作模块切换。哪个模块，到处找没有找到

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![天若_20230821191145](https://github.com/cuiliang/Quicker/assets/44609485/85ab217e-2c02-4536-b6ab-6fea41ad5a5a)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  这里下载最新版安装，托盘菜单改为暗色模式即可。
