### ISSUE TITLE
获取窗口信息/查找窗口 所有顶层窗口 结果为空时

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1991]
![图片](https://files.getquicker.net/_sitefiles/kb/sharedaction/ad87d373-43e3-4e13-c186-08daef64fc0b/2023/08/24/061106_36130_%E5%9B%BE%E7%89%87_20230824055718.jpg)

发现如果把输出topLevelWindows设为状态变量，
当获取结果为空{}时，
不能更新此变量：获得的不是{}，而是上一次的值。

**Comment by cuiliang** [comment]
图看不到。
本地测试没有发现有问题：

![image](https://github.com/cuiliang/Quicker/assets/1972649/3dab2792-e02b-4152-9dd6-6d98b2ecb7cd)

![image](https://github.com/cuiliang/Quicker/assets/1972649/c992a925-ea0b-492a-ba61-d7cf8db2513f)


给词典设置默认值
在第二次运行动作的时候显示的结果已经是空了。

**Comment by heloook** [comment]
@cuiliang 我使用的是进程名查找的，


[图片](https://files.getquicker.net/_actionDemos/ad87d373-43e3-4e13-c186-08daef64fc0b/20230824081521_Quicker_20230824_081333.png)


我比较确定：结果为空时，不更新。

**Comment by cuiliang** [comment]
进程名判断的时候，找不到进程步骤会报失败，这时候不会更新变量，所以导致了这个现象。

![image](https://github.com/cuiliang/Quicker/assets/1972649/0145b3f9-1540-466e-8c9a-31ec6c7abad9)

目前的解决办法是在步骤前面使用赋值给变量先清空一下。 

在大部分情况下，如果步骤失败了，都不会更新输出变量，可能会产生类似的问题。

**Comment by heloook** [comment]
@cuiliang 好的！
