### ISSUE TITLE
更新到 1.39.5 文本窗口报错

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1992]
测试动作：https://getquicker.net/Sharedaction?code=ad87d373-43e3-4e13-c186-08daef64fc0b

我找不到原因

**Comment by cuiliang** [comment]
应该是一个和语法高亮功能有关的bug，Coco这个没有暗色设置引起的，我处理一下

**Comment by heloook** [comment]
@cuiliang 回退到1.39.3正常

**Comment by cuiliang** [comment]
找到原因了，下一版修复下

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 更了一版试下看看

**Comment by heloook** [comment]
@cuiliang 已解决👍
