### ISSUE TITLE
电脑解锁后报了一个这个错

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1993]
消息执行出错, 消息类型:Quicker.Domain.Messages.ActiveProcessChangedMessage,错误:无法访问已释放的对象。
对象名:“Timer”。

不知道为什么，

好几次解锁时报错了。

**Comment by cuiliang** [comment]
看下 quicker.log 文件中是否有相关的记录条目

**Comment by heloook** [comment]
@cuiliang 没有记录

**Comment by cuiliang** [comment]
看起来只能用排除法了，这个可能是事件触发里“活动进程改变”的触发规则引起的，看一下设置里有没有这样的规则，然后关掉之后观察下会不会再出现。 如果不再出现，可以判断是这个地方的问题，再截图一下目前的配置，我这里试试复现一下。

**Comment by heloook** [comment]
@cuiliang 我事件触发里有一个重复执行的，应该是这个导致的：

[图片](https://files.getquicker.net/_sitefiles/kb/sharedaction/ad87d373-43e3-4e13-c186-08daef64fc0b/2023/08/25/121811_36130_image.png)

请问该怎么办呢？

**Comment by cuiliang** [comment]
等我研究修复一下，你也继续观察看看是不是确实是它导致的。

**Comment by heloook** [comment]
@cuiliang 好的👌

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
