### ISSUE TITLE
绑定到FSCapture的自定义操作窗的大小，会发生变化

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1994]
[图片](https://files.getquicker.net/_sitefiles/kb/sharedaction/ad87d373-43e3-4e13-c186-08daef64fc0b/2023/08/27/080105_36130_image.png)

操作窗选择了记忆位置和大小，
理想大小是图中的竖条状，

但faststone capture 启动时是一个状态栏，每次启动，
操作窗就自动把宽度变大，和fs的状态栏宽度差不多？

但位置是保持上一次的，

这样导致我每次还要再手动调整一下，

求助。

**Comment by cuiliang** [comment]
现在这个窗口有点复杂了，我有点搞不清原因😂，等找时间再详细研究一下

**Comment by cuiliang** [comment]
这个录个屏看一下吧

**Comment by heloook** [comment]
@cuiliang 

录屏来了。只要重启quicker，记忆FSCapture的大小就失效了，位置还在记忆


[视频](https://files.getquicker.net/_actionDemos/ad87d373-43e3-4e13-c186-08daef64fc0b/20230829030833_2.mp4)

**Comment by heloook** [comment]
或许和FSCapture有多种大小的窗口有关

**Comment by cuiliang** [comment]
动作分享一下，如果不是公开的，发一下网址到197906 QQ邮箱。 直接关闭操作窗以后，使用动作再开不会出现是么？

**Comment by heloook** [comment]
@cuiliang 最新版quicker好像没这个问题了，感谢！
