### ISSUE TITLE
表格 报错

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#1997]
[图片](https://files.getquicker.net/_sitefiles/kb/sharedaction/ad87d373-43e3-4e13-c186-08daef64fc0b/2023/08/29/162726_36130_image.png)

我日期时间已经设置为允许null
但如果不改动这个时间，保存时就会报错

改动一下，就不会

**Comment by heloook** [comment]
@cuiliang 正在写动作，急

**Comment by cuiliang** [comment]
确实有这个问题，不过最快也要等夜里发版本了😂 我先研究下

**Comment by heloook** [comment]
@cuiliang 好的

**Comment by cuiliang** [comment]
已更新，试下看看

**Comment by heloook** [comment]
@cuiliang 

我还没更新，现在遇到了 表格异常

ArgumentException
   在 System.Data.DataRow.GetDataColumn(String columnName)
   在 Quicker.Modules.Tables.TableRecordEditWindow..ctor(RecordEditMode mode, DataTable table, String title, TableDef tableDefDef, Double titleColumnWidth, DataRow row, Boolean isReadonly)
   在 Quicker.Modules.Tables.TableManageWindow.<BtnAdd_Click>d__18.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

版本1.39.10

[图片](https://files.getquicker.net/_sitefiles/kb/sharedaction/ad87d373-43e3-4e13-c186-08daef64fc0b/2023/08/29/192649_36130_%E5%9B%BE%E7%89%87_20230829192352.jpg)

**Comment by heloook** [comment]
起因：表格为空，点击添加行。

没有通过云同步获取数据时，正常。

通过云同步获取数据，此时数据为空，赋值给表格后。然后点击添加行，报错

**Comment by heloook** [comment]
两种情况下，表格数据都是空的，但通过云同步获取到空表格后，就触发异常

**Comment by heloook** [comment]
我做了一个临时的判断，我这里不会引发异常了，不着急处理

**Comment by heloook** [comment]
@cuiliang 1.39.12 已解决“日期时间为null”的问题

**Comment by cuiliang** [comment]
云同步如何加载数据到表格？ 
云同步应该只是文本格式的，没有办法保存表格。

**Comment by heloook** [comment]
@cuiliang 那就是云同步没办法同步表格数据吗？

**Comment by cuiliang** [comment]
需要导出文本数据为json或csv之后同步文本数据，恢复的时候从json或csv加载一下。

**Comment by heloook** [comment]
@cuiliang 哦哦，明白了！
