### ISSUE TITLE
个别时候，无法用鼠标滚轮对面板进行翻页操作

### ISSUE THREAD

**Issue by NF-001** [cuiliang/QuickPadCn#1998]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果使用了第三方鼠标增强软件，先退出测试；
如果使用了logi鼠标，在驱动里关闭“平滑滚动”测试；

**Comment by NF-001** [comment]
试了一下是开了鼠标控制软件的问题，软件为X-mouse，请问怎么设置可以使翻页不受影响

**Comment by cuiliang** [comment]
不太了解这个软件，需要咨询这个软件的开发者问问。
在此之前，可以尝试把quicker加入到它的黑名单，或以管理员身份运行这个软件看看有没有效果。

**Comment by tanziow** [comment]
> 试了一下是开了鼠标控制软件的问题，软件为X-mouse，请问怎么设置可以使翻页不受影响

我也是同样的问题，而且我几乎无法滚动动作页

**Comment by NF-001** [comment]
发现解决办法，就是在x-mouse软件里改一下滚动行数设置，原本设置的行数是6无法翻页，改成8或者其他就可以了，这个可能需要自己调试
