### ISSUE TITLE
能否在鼠标手势中添加切换窗口的功能

### ISSUE THREAD

**Issue by gurain** [cuiliang/QuickPadCn#2000]
**需求描述**
能否在鼠标手势中添加切换窗口的功能，我在常用功能（快速操作）的功能（操作）中没找到切换窗口的功能。

**描述你想要的解决方案**
例如，向左划切换到上一个窗口，向右滑，切换到下一个窗口。

**描述您考虑过的替代方案**
无

 **其他上下文**
是否有其他方法实现前后切换窗口呢？

**Comment by cuiliang** [comment]
什么是上一个窗口和下一个窗口呢？ 
可以试试分别模拟Alt+Tab，Alt+Shift+Tab

**Comment by gurain** [comment]
> 什么是上一个窗口和下一个窗口呢？ 可以试试分别模拟Alt+Tab，Alt+Shift+Tab

对，差不多就是这样，但目前设置Alt+Tab，Alt+Shift+Tab快捷键，除了会闪一下window切换窗口的界面，不会切换窗口，所以希望作者能添加一个左右滑动切换窗口的指令，同时能加个黑名单，切换窗口时候哪些不会窗口不会切进去。

**Comment by cuiliang** [comment]
为什么不会切换窗口呢？本地测试是正常的。 Alt+Tab是在两个窗口之间切换。
更复杂的，可能需要通过自己设计组合动作来实现了。

**Comment by definemax** [comment]
> 
我就是手势触发 Alt+Tab快捷键切换窗口，一直都正常。

**Comment by cuiliang** [comment]
[双窗口切换 - by CL - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=0ac49df5-509b-433b-9ed9-08dc18bbd5b2 )   使用这个动作。
