### ISSUE TITLE
使用驱动人生的百叶窗工具后无法使用获取资源管理器当前路径的动作

### ISSUE THREAD

**Issue by wqwdec** [cuiliang/QuickPadCn#2001]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
它替换掉了资源管理器，而不是资源管理器本身了，没有接口可以获取。
类似的情况还有360文件夹。
建议使用QTTabBar插件
