### ISSUE TITLE
多显示器，关闭非主屏任务栏，其他软件最大化窗口后，无法显示Quicker

### ISSUE THREAD

**Issue by foreverkenan** [cuiliang/QuickPadCn#2002]
**描述BUG**
多显示器，任务栏关闭“在所有显示器上显示任务栏”后（即 副屏不显示任务栏），最大化某个软件，Quicker无法显示出来
不一定算是bug

**重现步骤**
1.关闭“在所有显示器上显示任务栏”
![image](https://github.com/cuiliang/Quicker/assets/41415508/70e9623e-c4bf-4134-bb82-64443dfcf700)
2.在副屏打开某个软件，最大化。例如 TIM 和 Visual Studio 2019 会出现无法打开Quicker，而 Chrome浏览器 仍然可以打开Quicker。此处打开Quicker是使用全局快捷键
![image](https://github.com/cuiliang/Quicker/assets/41415508/b5dc8632-0c52-4ada-9c3b-e2c0ba1a131c)

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本： Windows 10 家庭中文版 22H2
 - Quicker版本：1.38.31

**附加信息**
其他情况：
开启“在所有显示器上显示任务栏”（即 副屏显示任务栏），其他操作不变，Quicker正常使用。
关闭“在所有显示器上显示任务栏”（即 副屏不显示任务栏），不最大化软件，Quicker正常使用。

**Comment by foreverkenan** [comment]
以上所有描述，均在副屏中。。。。主屏无论任何情况，Quicker 正常

**Comment by cuiliang** [comment]
黑名单设置界面里关闭"全屏禁用“选项。
![image](https://github.com/cuiliang/Quicker/assets/1972649/58a74835-7f53-48f9-bba5-f3cfb5807200)

**Comment by cuiliang** [comment]
另外也可以检查一下这里的设置
![image](https://github.com/cuiliang/Quicker/assets/1972649/5c1b858f-7b99-43f1-9222-7a27a1a89038)

**Comment by foreverkenan** [comment]
已解决 感谢
