### ISSUE TITLE
【需求】显示图片模块能否做到“不出现在alt+tab得窗口列表”中？

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#2003]
因为有不少“Quicker图片查看器”的存在，我按alt+tab后出现的窗口挺杂乱的，

[如图](https://tmpimg.getquicker.cn/2023/9/1/4c6103e7-63e5-4115-aba0-5d3e6404eae7_988a559f-8c5c-449e-b429-4b43e9575d32.jpg)

如果“显示图片”能加一个“是否出现在alt+tab窗口列表”的选项中，就好了。

**Comment by cuiliang** [comment]
下一版加一个根据置顶状态设置是否出现的处理。 如果不置顶又不出现在这里就找不到窗口了。

**Comment by heloook** [comment]
@cuiliang 感谢！
（如果能置顶的时候也不出现，就更好了。）

**Comment by cuiliang** [comment]
更了，试下

**Comment by heloook** [comment]
@cuiliang 超赞！！！
