### ISSUE TITLE
与部分软件冲突

### ISSUE THREAD

**Issue by everfeng** [cuiliang/QuickPadCn#2006]
**描述BUG**
目前发现互相冲突的软件及功能
软件：spacedesk（一个扩展副屏的软件），raylink（一个远程控制软件）
功能：发送文本

**重现步骤**
1.开启软件
2.使用发送文本功能会出现错乱

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
如：ps -ef|grep 这样的发送文本 如果开启了软件 就会变成这样
 p  -ef|grep 
p  -ef|grep 
-s -ef|grep 
p  -ef|grep 
p  -ef|grep
 ps -ef|grep 
pe -ef|grep 
p   ef|grep 

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.39.24（注，之前的版本也有这个问题）

**附加信息**
最早的时候是我测试spacedesk副屏的时候发现的这个问题，当时的解决方案是直接放弃了这个软件，因为quicker对我来说使用频率更高，当时也在QQ群里反馈过，不过最近远程控制软件也出现了这个问题就很难受了，俩都得用（之前用todesk时没问题，但后续收费了就换了raylink）希望大佬看看能否解决下

**Comment by cuiliang** [comment]
发送到远端还是在本地使用的时候会出现？ 
如果你使用的是搜狗输入法，升级输入法到最新版，旧版搜狗有类似现象。
如果还没解决，就在发送文本的步骤里增加一点延迟试试。
![image](https://github.com/cuiliang/Quicker/assets/1972649/007887a9-10c0-45c9-9ec0-31d5ae313383)

**Comment by everfeng** [comment]
升级输入法：无效
修改字符延迟：可以了！！！
注：本地使用
