### ISSUE TITLE
运行或打开 不影响窗口当前的风格

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#2007]
运行或打开 窗口风格处为空时 希望不影响当前窗口的风格

现在的情况是：当我最大化了一个窗口，运行一下，会把最大化的窗口，还原成普通的样子

https://github.com/cuiliang/Quicker/assets/27837566/e88ad83b-1fcb-4ffe-9770-5ef0f9962953

而我依然需要它是最大化的，还要手动再调回去

**Comment by cuiliang** [comment]
这个是windows自己处理的。 窗口风格这些只对启动exe程序有效，资源管理器不会开启新的程序。

**Comment by heloook** [comment]
好的👌
