### ISSUE TITLE
反馈一下

### ISSUE THREAD

**Issue by heloook** [cuiliang/QuickPadCn#2008]
第一次遇到这种情况，原因不明
![图片_20230919233417](https://github.com/cuiliang/Quicker/assets/27837566/ddb8cc9f-0ed5-48a7-b10d-9bc5aed40cd0)

**Comment by cuiliang** [comment]
这个通常是某个动作持续循环造成资源无法释放引起的。 
这时候试试在任务管理器里右键创建一个转储文件压缩一下发给我看看。
![image](https://github.com/cuiliang/Quicker/assets/1972649/59e3b436-4581-46f9-9d16-64349dcb9db8)

**Comment by heloook** [comment]
👌
