### ISSUE TITLE
搜索文件时设置优先显示文件夹

### ISSUE THREAD

**Issue by ypa957** [cuiliang/QuickPadCn#2009]
**需求描述**
对需求的描述。如需求的场景、解决的问题等。

**描述你想要的解决方案**
对你想要发生的事情进行清晰简洁的描述。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by cuiliang** [comment]
无法设置，不过你可以给搜索文件夹设置单独的触发词，默认是fd空格。
![image](https://github.com/cuiliang/Quicker/assets/1972649/19bd00d6-4085-403b-a679-c313a36f799c)

**Comment by ypa957** [comment]
好的，因为平时我也使用Listary所以想在Quicker中也实现就好了
