### ISSUE TITLE
移动文件：值不在预期的范围内。

### ISSUE THREAD

**Issue by EaglePPP** [cuiliang/QuickPadCn#2010]
**描述BUG**
 - 使用“文件和目录”的“移动到指定目录下(Windows) ”的时候，显示**值不在预期的范围内。**
 - 尝试了非中文字符文件夹，结果不变
 - 尝试了使用apk(没有.)，结果不变
 - 尝试了使用$= {file_path}.Contains(".apk")，结果不变
 - 尝试了使用“移动到指定目录下 ” 提示 异常：复制出错。源路径不存在：
 
**重现步骤**
1. 使用“文件和目录”的“移动到指定目录下(Windows) ” 移动文件。
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Win11 22621.2361
 - Quicker版本：1.39.39

**附加信息**
**Debug结果**
18第 0 次循环，项的值：E:\Downloads\chatgpt-android.apk
[out]项=>file_pathE:\Downloads\chatgpt-android.apk

181.0如果判断条件：$= {file_path}.ToLower().EndsWith(".apk") 
[in]如果【值/表达式】True
执行 True 分支, 共 3 步骤

191.0.0等待时间等待 100 ms
[in]等待时间【值/表达式】100
[in]等待窗口关闭时取消【值/表达式】False
耗时：115ms
1341.0.1文件和目录操作移动到指定目录下(Windows)
[in]失败后中止动作【值/表达式】True
[in]操作类型【值/表达式】moveIntoWithShell
[in]路径【变量 output_file_path】
[in]目标路径/名称【值/表达式】E:\安装包\apk
[in]覆盖已有【无输入】False
异常：值不在预期的范围内。
   在 CW.Win32.Shell.FileOperations.Move(String[] files, String to, FileOperationOptions options, IntPtr hwnd, String progressTitle)
   在 CW.Win32.Shell.FileOperations.Move(String[] files, String to, FileOperationOptions options)
   在 Quicker.Domain.Actions.X.BuiltinRunners.File.FileOperationStep.<>c__DisplayClass61_0.bGQSpi5CvW3()
   在 Quicker.Domain.Actions.X.XActionHelper.ExecuteCommonAction(ActionExecuteContext context, ActionStep step, XAction action, Func`1 actionFunc, Action successAction, Action failAction, StepInParamDef stopIfErrorParam, StepOutParamDef isSuccessOutputParam)
步骤(sys:fileOperation)执行失败，原因：值不在预期的范围内。
停止动作：值不在预期的范围内。
耗时：6ms
检测到了中止标志(OperationFailed)，停止后续步骤执行。

**Comment by cuiliang** [comment]
![image](https://github.com/cuiliang/Quicker/assets/1972649/4b93e4d0-f2fe-4db8-bc8d-597b1e0d43fa)
