### ISSUE TITLE
双节来临，不考虑来个限时的永久会员么？

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#2011]
我看隔壁uTool都来了个限时会员，Quicker也来一个呗，就喜欢买断的，哈哈。

**Comment by huiliu-overleaf** [comment]
强烈支持永久会员

**Comment by cuiliang** [comment]
980一个，我自己都觉得不适合购买，所以就不卖了。 目前作为赠品赠送给有突出贡献的网友。

**Comment by baileichao** [comment]
980这么贵的么？便宜点，我觉得还是值得买的。
