### ISSUE TITLE
全屏游戏时高级鼠标触发不能触发 

### ISSUE THREAD

**Issue by tanziow** [cuiliang/QuickPadCn#2013]
**描述BUG**
在打开某些全屏游戏时使用高级鼠标触发动作没有反应，已确认全屏下禁用是未勾选的状态；而使用键盘快捷键是可以正常触发动作的

**重现步骤**
1.为某动作如https://getquicker.net/Sharedaction?code=9653e1df-18ed-49bf-209b-08dbc3b90ceb 或者ID为2d61e5cd-0ac5-40bf-99f1-a3652d9cf55b 的鼠标连点动作，设置键盘快捷键和鼠标高级触发，比如为alt+F2和alt+鼠标侧键X2
2.打开一个全屏游戏，比如Wolcen，调整窗口为全屏
3.分别使用键盘快捷键、鼠标高级触发

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.39.39

**Comment by cuiliang** [comment]
游戏可能有防作弊机制影响触发。 
在其它软件下测试触发规则看看是否正常。
在规则里增加提示确认是否是没有触发还是触发后没有实现功能。 
![image](https://github.com/cuiliang/Quicker/assets/1972649/8890df23-51ac-4b8e-a0aa-d12e509496f2)

**Comment by tanziow** [comment]
> 游戏可能有防作弊机制影响触发。 在其它软件下测试触发规则看看是否正常。 在规则里增加提示确认是否是没有触发还是触发后没有实现功能。 ![image](https://user-images.githubusercontent.com/1972649/272207007-8890df23-51ac-4b8e-a0aa-d12e509496f2.png)

 但是用键盘快捷键是可以正常触发的

**Comment by cuiliang** [comment]
无法复现和判断此问题。
