### ISSUE TITLE
同步异常

### ISSUE THREAD

**Issue by jgzboy** [cuiliang/QuickPadCn#2014]
20231005 12:10:24 失败
更新 1 项数据到服务器。
  CommonData:user_settings  (常规数据)
同步异常：发生一个或多个错误。发送请求时出错。无法连接到远程服务器由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 47.102.47.205:443

**环境信息:**
 - 操作系统版本：Windows 10 专业工作站版 22h2
 - Quicker版本：1.39.43

**Comment by cuiliang** [comment]
目前正常了么？ 看起来是网络问题。
如果开启了代理，尝试关闭代理；尝试切换到手机热点；如果有安全软件，尝试关闭安全软件；如果旁边有其它电脑，尝试在这些电脑上登录；
目前服务都是正常的。

**Comment by Vstory** [comment]
目前我也遇到了

**Comment by cuiliang** [comment]
@Vstory 应该好了
