### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by manshappy** [cuiliang/QuickPadCn#2015]
![image](https://github.com/cuiliang/Quicker/assets/147174319/9a0f6fae-3c01-4d51-8db1-035f0bbbb7cf)
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
hi，看起来和这个问题是同一个原因，请参考试一下，如果仍然没有解决，请联系qq 197906
https://getquicker.net/KC/Kb/Article/1092

**Comment by cuiliang** [comment]
解决了么？ @manshappy
