### ISSUE TITLE
增加指定位置搜索设置条目

### ISSUE THREAD

**Issue by witolion** [cuiliang/QuickPadCn#2017]
**需求描述**
增加指定位置搜索设置条目。
我希望能够设置不同的触发词来实现在不同的目录中搜索。目前设置只能在一个目录组中进行搜索。

![image](https://github.com/cuiliang/Quicker/assets/147264241/df97634c-3cbc-4c71-8736-ec7f88a07c77)

**Comment by cuiliang** [comment]
这个插件无法实现，可以用everything那个，可以在触发词条件里设置路径等其他everything支持的参数
