### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by Aliyuo** [cuiliang/QuickPadCn#2018]
**描述BUG**
对bug的清晰简洁描述。
发送文本到窗口失效
**重现步骤**
1.cmd命令窗口
2.发送命令文本（末尾添加回车）

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
https://temp.getquicker.net/525791/92b0cf790f084927bf2216489ad38661.html

**环境信息:**
 - 操作系统版本：WIN10
 - Quicker版本：1.39.43

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
1） 确认发送文本的时候，目标窗口有焦点。 如果刚显示完弹窗，增加200ms等待时间等目标有焦点。
2） 有些窗口不支持ctrl+v，改成模拟输入方式发送。

另外脚本内容看起来多了 = 。 插值符号是`$$` 表达式是`$=` 没有 `$$=` 
![image](https://github.com/cuiliang/Quicker/assets/1972649/3efd3c99-dfaf-491b-bfb6-ade125d9389b)

**Comment by Aliyuo** [comment]
> 1） 确认发送文本的时候，目标窗口有焦点。 如果刚显示完弹窗，增加200ms等待时间等目标有焦点。 2） 有些窗口不支持ctrl+v，改成模拟输入方式发送。
> 
> 另外脚本内容看起来多了 = 。 插值符号是`$$` 表达式是`$=` 没有 `$$=` ![image](https://user-images.githubusercontent.com/1972649/274273424-3efd3c99-dfaf-491b-bfb6-ade125d9389b.png)



> 1） 确认发送文本的时候，目标窗口有焦点。 如果刚显示完弹窗，增加200ms等待时间等目标有焦点。 2） 有些窗口不支持ctrl+v，改成模拟输入方式发送。
> 
> 另外脚本内容看起来多了 = 。 插值符号是`$$` 表达式是`$=` 没有 `$$=` ![image](https://user-images.githubusercontent.com/1972649/274273424-3efd3c99-dfaf-491b-bfb6-ade125d9389b.png)

这个组合动作我之前用是OK的，昨天突然就不行了。执行到最后提示：“无法对windows窗口操作”
然后那个插值符号使用$===是报错的（如下图），我直接插入的变量自动用的就是$$==
![image](https://github.com/cuiliang/Quicker/assets/147463585/ce7be417-daba-4af3-891c-81312074eb06)

**Comment by cuiliang** [comment]
自动添加的可能不是实际需要的，请看一下这里的文档，确保最终生成的脚本内容是合法的。这两个对组合动作编写比较重要。
![image](https://github.com/cuiliang/Quicker/assets/1972649/29df7479-7b2d-41bd-b049-9c1ff77c1f35)
