### ISSUE TITLE
单击ctrl键触发弹出面板失效

### ISSUE THREAD

**Issue by nangua316** [cuiliang/QuickPadCn#2019]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.弹出面板，设置了暗下中建触发，，和单击ctrl键触发，不知道什么原因，有时候ctrl键就会失效，重启app也不行，需要重启电脑才会好。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/cuiliang/Quicker/assets/32589491/39fe7d02-2694-459c-a791-43a062e9972b)

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.39.43

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能有其它使用键盘挂钩的程序。
可以尝试退出其它所有软件排查一下。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
