### ISSUE TITLE
希望在quicker设置界面可以设置“重置键盘状态”的快捷键

### ISSUE THREAD

**Issue by zhch25** [cuiliang/QuickPadCn#2020]
**需求描述**
希望在quicker设置界面可以设置“重置键盘状态”的快捷键

**描述你想要的解决方案**
运行quicker后经常导致我的键盘响应时间滞后，比如按ctrl+c要比正常延迟，我也不知道是什么原因。但是这个问题我重置键盘状态就好了，这就导致我经常要重置键盘状态，希望在quicker设置界面可以设置“重置键盘状态”的快捷键

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能进行简明扼要的描述。

 **其他上下文**
![image](https://github.com/cuiliang/Quicker/assets/147697355/ef2cc323-eabd-4e5b-a327-73d9d82989db)
![image](https://github.com/cuiliang/Quicker/assets/147697355/e115acc1-d9ec-4368-b6c1-10d0386ed39f)

**Comment by cuiliang** [comment]
可以直接用 重新加载挂钩 那个快捷键，也会同时重置键盘状态。

目前还没有遇到过ctrl+c会出现响应时间滞后的现象，具体是什么表现呢？
有使用ctrl+c作为动作的快捷键么？ 扩展热键中有使用Ctrl作为引导键么？有没有其它可能使用键盘挂钩的程序？
另外可以通过这个功能观察一下键盘状态是否正常：
![image](https://github.com/cuiliang/Quicker/assets/1972649/061f6cf7-01a2-43de-938b-689fb4c92424)

**Comment by zhch25** [comment]
键盘状态显示按下的是F22键；另外重新加载键鼠挂钩不能重置键盘状态，依然显示按下了F22键，只能靠重置键盘状态按钮，暂时没有排查出怎么会按下这个键
![20231013_110153](https://github.com/cuiliang/Quicker/assets/147697355/680b3058-0e8d-4560-a277-ee7c92539920)

**Comment by cuiliang** [comment]
@zhch25 F22是微信登录的时候它自动按下的。也可以做个动作模拟按键F22一下
