### ISSUE TITLE
希望可以通过变量设置是否启用多线程

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#2021]
**需求描述**
为了在动作执行过程中对微标实时更新而使用了多线程，但这导致了大量步骤都不会输出日志，用户反馈时还需手动修改动作将多线程关闭再调试
希望能够以变量的形式来控制多线程是否启用，这样用户就能简单的在设置中取消这一功能后进行调试

![image](https://github.com/cuiliang/Quicker/assets/48246272/ef28dc6d-3adf-4619-aee6-7eaa512b4ebc)
修改为这种形式，可以用变量传入
![image](https://github.com/cuiliang/Quicker/assets/48246272/288b1b7c-5db8-425c-9c70-198008c81c08)

**描述您考虑过的替代方案**
如果徽标可以自己设置计时或闪烁状态，那就不需要用多线程来实时更新了

**Comment by cuiliang** [comment]
研究了一下，这里没法使用变量控制。 🤦‍♂️
这个是一个控制变量，有一些其它字段依赖这个选择之后控制是否显示，如果修改了会影响这里的功能。
