### ISSUE TITLE
webview2窗口置顶后，右键不能使用

### ISSUE THREAD

**Issue by pisceswb** [cuiliang/QuickPadCn#2022]
**描述BUG**
webview2窗口置顶后，右键不能使用。

**重现步骤**
1. 直接使用webview2中的置顶选项，弹出的webview2置顶后的窗口，右键不能使用，取消置顶后，右键可以使用。
2.不使用webview2中的置顶选项，弹出的webview2未置顶的窗口，可以使用右键，使用窗口操作动作置顶窗口，或使用弹出窗口右上角按钮置顶窗口后，不再能使用右键，且偶尔弹出打印窗口。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.39.43

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
Ref： https://getquicker.net/Common/Topics/ViewTopic/21388

**Comment by cuiliang** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4087 要等微软修了，有可能不会被修复，另一个已经提交了一两年还没有进展。
