### ISSUE TITLE
非专业版Quicker，无法对已经设置的快捷键做修改。

### ISSUE THREAD

**Issue by RICARDOAIYUAN** [cuiliang/QuickPadCn#2023]
**描述BUG**
非专业版Quicker，快捷键设置满3次后，无法对已经设置的快捷键做修改。再次点击已经设置快捷键动作的快捷键准备修改快捷键时，一直弹窗提示升级专业版。

**重现步骤**
1.
2.

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/94746324/492f71a3-3d66-49e9-a4ef-cc510ec1b632)

**环境信息:**
 - 操作系统版本：Windows 10 专业版 22H2
 - Quicker版本：1.37.37

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
请在这里移除规则
![image](https://github.com/cuiliang/Quicker/assets/1972649/fd712e8f-c714-4f20-a72d-6e4d9e3c4975)
