### ISSUE TITLE
Caps大小写切换不起作用

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#2024]
我才试出来，运行了Quicker后，Caps切换大小写的时候，就不起作用了，但是在设置里面找了一圈，好像也没有设置关于Caps按键的相关操作，请问这个需要怎样把这个问题给排查出来呢？

**Comment by cuiliang** [comment]
1：
![image](https://github.com/cuiliang/Quicker/assets/1972649/8bb7ec34-7129-497c-ba6b-dfb112a2fddf)


2：
![image](https://github.com/cuiliang/Quicker/assets/1972649/95cfaa59-a113-4460-a233-96bfa3f458b6)

**Comment by baileichao** [comment]
原来是第二个引起的，感谢感谢，我当时排查的时候，并没有选择到CapsLock，原来是要在上面选择那个引导键，再设置的，已成功解决，用了好几年Quicker了，一直导致大写用不了，尴尬，现在终于找到原因了😃。
