### ISSUE TITLE
链接动作标识优化

### ISSUE THREAD

**Issue by Qpp0** [cuiliang/QuickPadCn#2025]
**需求描述**
现在的用时表示链接动作，是在动作名称前面加上一个*号，但是这样不美观，并且影响动作名字的显示

**描述你想要的解决方案**
建议是将此标识移动到动作块的其他部位。例如在动作块右上角加上一个小三角（手撸的😂，表达下意思）
![image](https://github.com/cuiliang/Quicker/assets/93501907/9c386ec2-0992-4342-a852-f05c6d9136c5)

 **其他上下文**
![image](https://github.com/cuiliang/Quicker/assets/93501907/4b6dc4ea-5785-47ad-bb2f-91ecba6002da)

**Comment by cuiliang** [comment]
其它方式需要在控件里增加新的子控件，会有一定的消耗，暂时不考虑了。
后期可能会重新设计链接的方式，到时候再说。
