### ISSUE TITLE
搜索框能否显示并选中上次键入的内容？

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#2026]
# 需求描述

每次打开搜索框都是空的，有时想用搜索框自带的浏览器书签打开多个网址，这时要多次输入 `ll`，有点讨厌。

此外还有其它类似情况。

# 描述你想要的解决方案

每次打开搜索框，上次输入的内容都还在，并处于选中状态。

因为上次的内容还在，下方的选项还是和上次一样；因为处于选中状态，只要开始输入，上次的内容就会直接消失。

# 描述您考虑过的替代方案

没有。

**Comment by cuiliang** [comment]
等试下看看

**Comment by Immortal-Sty** [comment]
谢谢。
