### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by rryain** [cuiliang/QuickPadCn#2027]
**描述BUG**
使用HTTP解析 
GET指令
对于bilibili直播间获取总得到"服务器失败"

**重现步骤**
1.使用任何具有HTTP请求的程序(这里是https://getquicker.net/Sharedaction?code=527484f4-f9be-49f9-30b7-08db280dd146(我将地址改成bilibili的(https://live.bilibili.com/{房间号})(我的一个房间号26872684)(调试后发现HTTP请求出现 <span>Σ(oﾟдﾟoﾉ) 服务器正在休息 zZ</span>\n))
2.调试运行.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/cuiliang/Quicker/assets/144131189/464de210-5b0d-44fd-928a-bb08bfe47fc2)
错误
![image](https://github.com/cuiliang/Quicker/assets/144131189/3ac499e1-3389-4330-b8db-8e81c9a51ff7)
![image](https://github.com/cuiliang/Quicker/assets/144131189/cc919b56-8f17-464f-a793-ca8cf0201738)
![image](https://github.com/cuiliang/Quicker/assets/144131189/52470fc5-4fe0-43a7-ba74-5e01c8c69ecd)
PS.我使用其他获取cookie的方式失败了,但请求在其他网站仍能正常运行如(https://stackoverflow.com/)

**环境信息:**
 - 操作系统版本：
![image](https://github.com/cuiliang/Quicker/assets/144131189/28cedc24-302f-4900-9c27-aae416d185d6)
 - Quicker版本：
 - ![image](https://github.com/cuiliang/Quicker/assets/144131189/4cac72fb-8295-4f2a-b155-4ae1e044c256)

**附加信息**
其他程序使用同样使用HTTP解析 
GET指令
对于bilibili直播间获取也失败,正常使用URL可以进入房间
PS.我使用其他获取cookie的方式失败了,但请求在其他网站仍能正常运行如(https://stackoverflow.com/)

**Comment by cuiliang** [comment]
这种网站一般都会有反爬机制，可能需要有足够深的了解，把所有服务端验证都pass了才能请求到。

**Comment by rryain** [comment]
懂了
