### ISSUE TITLE
打开网址时，可否不要把英文字母全小写。

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#2028]
# 需求描述

我在用 Quicker 搜索框打开一些网址时，他会把所有英文字母变成小写，结果有些网址打开就会出错，比如某些网盘的分享网址。

# 描述你想要的解决方案

希望可以不要在打开网址时改变英文字母大小写。

**Comment by cuiliang** [comment]
截个屏看看是哪里的？

**Comment by Immortal-Sty** [comment]
刚试了一下，直接输入网址已经不会变小写了，但用搜索框的“网络搜索”功能还是会变小写，但这个当前影响不大。

我加了一个快速打开 github 库的网络搜索，可以用 `ghk Immortal-Sty/我的库` 打开我的库的网址，但它依旧会变小写，不过 github 影响不大，大小写不影响我进入我的库。

设置如图：

![](https://picst.sunbangyan.cn/2023/10/30/4f3419e6251c4aba71fac9b27d184edd.png)

**Comment by Immortal-Sty** [comment]
又发现一个小问题，当我使用搜索类的动作时（比如[这个](https://getquicker.net/Sharedaction?code=23f6327b-9953-4766-4b58-08d9c1f3456f)），Quicker 记录的是搜索动作内部的关键字，而不是外部的。比如：

![](https://picdm.sunbangyan.cn/2023/10/31/2092da638768ae9444b86286ba21fc16.png)

1. 第一次唤出搜索框；
2. 输入 `em` 后按下空格，进入动作搜索；
3. 输入 `笑` 后回车，运行结束；
4. 第二次唤出搜索框；
5. 期望结果：搜索框中出现 `em`，并处于选中状态；
6. 实际结果：搜索框中出现 `笑`，并处于选中状态。
