### ISSUE TITLE
建议在鼠标手势中增加添加黑名单选项

### ISSUE THREAD

**Issue by xzhsnh** [cuiliang/QuickPadCn#2029]
如题，建议在鼠标手势中增加可以将当前软件添加到黑名单的功能，
设置了中键触发轮盘菜单，对于一些用到中键的软件，由于需要频繁切换别的软件，能添加黑名单是最方便的。

**Comment by cuiliang** [comment]
在这里添加黑名单
![image](https://github.com/cuiliang/Quicker/assets/1972649/6e2d2491-c3a8-479a-936c-3307765fb3a9)

**Comment by ygr2333** [comment]
![屏幕截图 2023-11-22 225525](https://github.com/cuiliang/Quicker/assets/47142656/36cd177d-dc63-4525-9869-360cafd1f9be)
你说的是这个吗？
