### ISSUE TITLE
安装向导无法关闭Quicker

### ISSUE THREAD

**Issue by Vstory** [cuiliang/QuickPadCn#2030]
**描述BUG**
安装程序无法关闭正在运行的Quicker，安装失败。

**重现步骤**

https://github.com/cuiliang/Quicker/assets/20795557/b48dff43-e716-4c21-923c-fdb68b9d1bf0

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/20795557/8c12d4d4-0283-4b42-bc34-a5302ede6659)

**环境信息:**
 - 操作系统版本：23H2
 - Quicker版本：1.40.7.0 

**附加信息**
每次安装都得手动退出Quicker。

**Comment by cuiliang** [comment]
这个好像没有什么办法，安装程序关闭不了quicker，只能手动关了。 
可以使用这个动作来解决： https://getquicker.net/Sharedaction?code=8801304b-0c52-42d8-2b99-08d8c37c25c6

**Comment by Vstory** [comment]
还是手动吧。
这个问题在你发布版本更新时，点击安装好像是不存在这个问题的。
手动下载测试版，好像会存在。
