### ISSUE TITLE
希望同一软件可以创建绑定多个轮盘菜单，用快捷键配合驱动

### ISSUE THREAD

**Issue by XHLY17001** [cuiliang/QuickPadCn#2031]
**需求描述**
一个软件对应一个轮盘菜单有些不够用，希望能绑定多个轮盘菜单

**描述你想要的解决方案**
用快捷键配合驱动多个轮盘菜单

**Comment by cuiliang** [comment]
参考这里， 触发额外的轮盘菜单：https://getquicker.net/kc/manual/doc/circle-menu#bwi3X

**Comment by XHLY17001** [comment]
> 参考这里， 触发额外的轮盘菜单：https://getquicker.net/kc/manual/doc/circle-menu#bwi3X

成功解决了，非常感谢
