### ISSUE TITLE
小数计算错误

### ISSUE THREAD

**Issue by ghost** [cuiliang/QuickPadCn#2032]
**描述BUG**
45492.67-45146.87=345.799999999996

![image](https://github.com/cuiliang/Quicker/assets/149399053/46bfb27b-c495-4f1a-a606-c0f8a249d472)

计算模块也会出错
![image](https://github.com/cuiliang/Quicker/assets/149399053/6d550b2c-99c4-4f95-9a8c-cf7131edda5a)

Win-10.0.19045.0  Quicker-1.40.9.0

**Comment by cuiliang** [comment]
这是计算机里的浮点数的特征。  参考这个保留特定位小数 https://getquicker.net/KC/Kb/Article/953
