### ISSUE TITLE
能加上带多选的文本框吗？

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#2033]
# 需求描述

在**多字段表单**和**表格数据操作**中，有下拉选择、带选择的文本框、多选下拉框这几个，但没有带多选的文本框。

这个功能是想用在“标签”上的，用多选的文本框给表格变量每行打标签，既可以快速找到自己曾打过的标签，又能方便的添加新标签。

# 描述你想要的解决方案

给多字段表单和表格数据操作中加上**多选的文本框**功能，最好是带筛选的那种。

在文本框中输入后，按“;”添加新标签，按“回车”选择下方第一个候选项。

# 描述您考虑过的替代方案

实在不方便，不加筛选也行啦。

**Comment by cuiliang** [comment]
实现起来过于复杂。 目前可以试试通过最新版的自定义文本选择工具功能实现。
https://getquicker.net/KC/Help/Doc/custom_texttool

**Comment by Immortal-Sty** [comment]
> 实现起来过于复杂。 目前可以试试通过最新版的自定义文本选择工具功能实现。 https://getquicker.net/KC/Help/Doc/custom_texttool

谢谢，已经在多字段表单中实现了，但表格数据操作中还没有，是还没加入吗？

**Comment by Immortal-Sty** [comment]
感谢老大，太爱老大了！！！
