### ISSUE TITLE
以下python代码无法运行

### ISSUE THREAD

**Issue by wsyzff** [cuiliang/QuickPadCn#2036]
import photoshop.api as ps

app = ps.Application()
doc = app.activeDocument
layer = doc.layers[0]
layer.translate(10, 10)
![Quicker_20231122_195035](https://github.com/cuiliang/Quicker/assets/137078800/f5ac54a1-5d87-43b8-a3f0-9a2b244f6bd9)

**Comment by cuiliang** [comment]
quicker多少版本？

**Comment by wsyzff** [comment]
1.40.12   ，代码在PyCharm上是可以正常运行的

**Comment by cuiliang** [comment]
换1.40.11 或 1.40.13 试一下，12的动作线程模型改成了MTA，可能不太兼容。

**Comment by wsyzff** [comment]
谢谢，更换版本后可以正常运行了

**Comment by cuiliang** [comment]
好的
