### ISSUE TITLE
关于动作的疑问

### ISSUE THREAD

**Issue by Vstory** [cuiliang/QuickPadCn#2040]
**需求您的问题**
假设有一个动作记作A，场景有a,b,2个场景。
我将动作A分别粘贴到a,b场景，之后动作A有了更新。更新列表里有2个动作A。
这里为什么会出现两个A？

**Comment by cuiliang** [comment]
每个动作页里的动作都是独立的动作，可以修改它们的标题/图标或里面的步骤，可以把动作库里的动作理解成模板，动作页里每个格子的动作都是独立的个体“实例”

**Comment by Vstory** [comment]
> 每个动作页里的动作都是独立的动作，可以修改它们的标题/图标或里面的步骤，可以把动作库里的动作理解成模板，动作页里每个格子的动作都是独立的个体“实例”

明白了，谢谢
