### ISSUE TITLE
无法使用开机自启动

### ISSUE THREAD

**Issue by skdyocxfs** [cuiliang/QuickPadCn#2041]
**描述BUG**
对bug的清晰简洁描述。
开机自启动无法应用设置
**重现步骤**
1.打开设置
2.勾选开机自启动
3.点击应用设置
4.关闭界面
5.打开设置
6.发现开机自启动未勾选

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/cuiliang/Quicker/assets/152377781/81caa0b4-aaa7-4029-a9c1-2ea087bf8686)
![image](https://github.com/cuiliang/Quicker/assets/152377781/417ca3bf-d5a6-421e-84fc-c6ab7b1c5ce7)

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个情况99%为各类官家软件的原因，找到设置或者卸载它们。 
参考 https://getquicker.net/KC/Kb/Article/401
