### ISSUE TITLE
在表格数据操作模块中，使用查看或编辑数据时，点击继续添加会导致文本选择工具失效。

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#2042]
# 描述BUG

这是[小布丁的大布丁](https://getquicker.net/User/723/%E5%B0%8F%E5%B8%83%E4%B8%81%E7%9A%84%E5%A4%A7%E5%B8%83%E4%B8%81)在使用动作[窗口工作区](https://getquicker.net/Sharedaction?code=7b98be75-f041-4b1e-7c82-08dbeef8975e)时发现的问题，[贴子在此](https://getquicker.net/Common/Topics/ViewTopic/22264)。

我新建了一个动作，把该模块单独使用进行测试时，重现出了同样的问题。

# 重现步骤

1. 新建一个动作：
    1. 建一个**表格变量**，随便搞几列，注意要用上**文本选择工具**；
    2. 使用**表格数据操作**模块中的**查看或编辑数据**功能，用于编辑上面的表格变量；
2. 运行动作：
    1. 新建第一行，新建完成后点击**继续添加**；
    2. 点击**文本选择工具**；
    3. 预期结果：文本选择工具开始运行；
    4. 实际结果：什么也没发生。

# 相关截图

![](https://files.getquicker.net/_sitefiles/kc/kb/2023/11/29/183336_723_actionIssue.gif)

# 环境信息

- 操作系统版本：Windows 11 23H2；
- Quicker版本：1.40.15。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  试下1.40.19版本，应该可以了。

**Comment by Immortal-Sty** [comment]
成功了，谢谢老大。
