### ISSUE TITLE
浏览器的右键菜单和网页动作按钮没了

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#2044]
# 描述BUG

在 Firefox 里，Quicker 的扩展的右键菜单和网页动作按钮没了，使用修复工具也不行。

右键菜单只剩下开发工具了，网页动作按钮直接消失了。

补充：我又用 Chrome 和 360 测试了一下，发现都不行。

# 重现步骤

1. 安装 Firefox 和对应的浏览器扩展；
2. 把某些动作加到浏览器右键菜单上或网页动作按钮上；
3. 在浏览器中右键，或打开存在网页动作按钮的网页；
4. 右键中只存在开发工具，网页动作按钮直接不见了。

# 相关截图

![2023-12-03 02-44-25](https://github.com/cuiliang/Quicker/assets/94347641/37d033e8-eda1-4b1a-bddc-17cb4ac34fc6)

![20231203_024318_306_copy](https://github.com/cuiliang/Quicker/assets/94347641/4e9bae93-d00d-40b3-8428-9cd36400c441)

# 环境信息
- 操作系统版本：Windows 11 23H2；
- Quicker 版本：1.40.17；
- Quicker Connector 版本：0.7.3；
- Firefox 版本：120.0.1。

**Comment by cuiliang** [comment]
以前可以么？ 因为时间比较久，我也不记得firefox是否支持这个功能了。 相对于chrome，firefox的API支持会有一定限制。

**Comment by Immortal-Sty** [comment]
以前可以的，chrome 和 firefox 都可以，而且现在是好几个浏览器都不行了，chrome、firefox、360 都没了。

**Comment by cuiliang** [comment]
哦，应该是匹配网址限制了。 
以前匹配网址可以为空，导致无法清掉不需要的动作。 现在需要按chrome规则写匹配网址
https://developer.chrome.com/docs/extensions/mv3/match_patterns/

例如匹配所有的： `https://*/*`

**Comment by Immortal-Sty** [comment]
右键菜单成功解决了，但网页动作按钮还是不行。

**Comment by cuiliang** [comment]
网页动作按钮的匹配语法和右键菜单不同。 右键菜单是给浏览器去匹配的，网页按钮是qk自己匹配的。

匹配网址支持如下格式：
- regex:正则表达式
- 网址的一部分 （会根据此内容按如下规则生成正则表达式：将.替换为\.，将?替换为\?，将*替换为.*）

**Comment by Immortal-Sty** [comment]
我知道咋用，但是用了没效果。

**Comment by cuiliang** [comment]
重启quicker一下试试。 目前是怎么设置的？

**Comment by Immortal-Sty** [comment]
还是不行。

```
regex:.+getquicker\.net\/Sharedaction\?code=.+
```

**Comment by cuiliang** [comment]
我这里测试没问题。 你可以看看扩展背景页里的匹配记录。如果是true，就表示正常匹配，如果没有xi显示，可能因为悬浮按钮被移动到网页外面了。
![image](https://github.com/cuiliang/Quicker/assets/1972649/4958a175-cca0-47f7-8fc7-91036fbfc466)

这里恢复悬浮按钮默认位置。
![image](https://github.com/cuiliang/Quicker/assets/1972649/5c1fa785-c7a9-49b3-ac11-3ccecbb32c64)

**Comment by Immortal-Sty** [comment]
![2023-12-03 02-51-27](https://github.com/cuiliang/Quicker/assets/94347641/1b088cb9-407d-4bee-8968-59cfca52b13e)

我不会看这个，我这个咋这样啊？

**Comment by cuiliang** [comment]
![image](https://github.com/cuiliang/Quicker/assets/1972649/a4277539-034c-4fdb-8cac-95a7e84f0387)

**Comment by Immortal-Sty** [comment]
![2023-12-03 02-59-24](https://github.com/cuiliang/Quicker/assets/94347641/6aec5308-dc9a-43f4-af96-7f367d11d787)

不行啊。

**Comment by cuiliang** [comment]
这个正则有问题吧，浏览器不支持
![image](https://github.com/cuiliang/Quicker/assets/1972649/c8a85a45-ab6f-4c51-b5a8-7c88e1897aed)

**Comment by Immortal-Sty** [comment]
有啥法子能找到是哪个动作搞的这个吗？这不是我设的，头秃。

**Comment by cuiliang** [comment]
展开这些从quicker发来的消息，有一条是发送的推送动作信息的，里面应该可以查到
![image](https://github.com/cuiliang/Quicker/assets/1972649/39836272-f633-45ee-9df8-e19b0b8320d2)
展开这个actions应该也可以看
![image](https://github.com/cuiliang/Quicker/assets/1972649/6aa4b5dc-5efe-4939-bc5b-35d2a792c37f)

**Comment by Immortal-Sty** [comment]
成功了，感谢老大！！！
