### ISSUE TITLE
黑屏后，再次点亮屏幕，邮件手势没有轨迹显示。

### ISSUE THREAD

**Issue by DrSeraph** [cuiliang/QuickPadCn#2045]
**描述BUG**
电脑长时间闲置自动关闭屏幕，再次点亮屏幕，鼠标右键手势没有轨迹显示。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11  23H2
 - Quicker版本：1.39.43及之前版本均有以上bug

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个估计是底层bug，轮盘菜单有时候也会在恢复显示之后界面冻住，但是底层事件可以正常触发。 
暂时没有什么解决办法，请重启一下qk了。

**Comment by cuiliang** [comment]
你的windows详细版本号是多少？我似乎很久没有遇到过界面冻住的情况了
![image](https://github.com/cuiliang/Quicker/assets/1972649/9fe97fef-72f5-4ed1-b2af-4fa384c8ccda)

**Comment by DrSeraph** [comment]
手势轨迹不显示，但是可以用。
另外，新发现的，黑屏后截图，好像截的图也不能显示，应该是有截好（因为第二次截取的时候，会自动识别出第一次截图并可以吸附框选）


王凯龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 黑屏后，再次点亮屏幕，邮件手势没有轨迹显示。 (Issue #2045)





 
你的windows详细版本号是多少？我似乎很久没有遇到过界面冻住的情况了
 image.png (view on web)

**Comment by cuiliang** [comment]
截图没显示倒是没有遇到过。 可以尝试更新一下显卡驱动。 
下个版本增加一个处理，显示器电源关闭的时候销毁一下手势窗口，等下次使用的时候重新建立，可能可以避免手势不显示的问题。

**Comment by DrSeraph** [comment]
好的好的，辛苦您啦！总体来说软件还是很好用的！感谢您的付出！




王凯龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuiliang/Quicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 晚上8:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuiliang/Quicker] 黑屏后，再次点亮屏幕，邮件手势没有轨迹显示。 (Issue #2045)





 
截图没显示倒是没有遇到过。 可以尝试更新一下显卡驱动。
 下个版本增加一个处理，显示器电源关闭的时候销毁一下手势窗口，等下次使用的时候重新建立，可能可以避免手势不显示的问题。

**Comment by cuiliang** [comment]
1.40.19 之后的版本在显示器关闭后会自动销毁手势窗口对象，应该已经解决了此问题。 如果使用新版仍有遇到请随时反馈，这个先关了。
