### ISSUE TITLE
无法获取到某些网页的 URL

### ISSUE THREAD

**Issue by TCOTC** [cuiliang/QuickPadCn#2047]
**描述BUG**
无法获取到某些网页的 URL

**重现步骤**
1. 使用动作「[发送到flomo](https://getquicker.net/Sharedaction?code=a039da82-103a-4e46-ad3a-08dbb89e3001)」
2. 在 [CSDN](https://blog.csdn.net/maokexu123/article/details/42773599) 的网页选中文字后运行动作，无法获取到网页的 URL
3. 但在 [百度知道](https://zhidao.baidu.com/question/1894050159402631948.html) 可以

**相关截图**

![image](https://github.com/cuiliang/Quicker/assets/78434827/3220471e-db61-49b4-9fd8-38dc855a1810)

![image](https://github.com/cuiliang/Quicker/assets/78434827/fc9aa666-1155-4d9e-a6b0-3bdbc9127d30)

![image](https://github.com/cuiliang/Quicker/assets/78434827/a45d98ea-6a70-44d5-a335-8986ab66756d)

**环境信息:**
 - 操作系统版本：Windows 10 家庭中文版 22H2
 - Quicker版本：1.40.17

**附加信息**
我是该动作的作者，本来在想办法解决无法获取网页标题的问题，结果发现有时 URL 也获取不到

**Comment by TCOTC** [comment]
关联：https://github.com/cuiliang/Quicker/issues/2048

**Comment by cuiliang** [comment]
根据所使用的浏览器，安装扩展。如果已安装扩展，参考文档里排查连接情况。 
参考：https://getquicker.net/kc/help/doc/chromecontrol
谷歌浏览器扩展地址：https://chromewebstore.google.com/detail/quicker-connector/klggbkjfmbonefdcfkiidhcmfjdfnepa?hl=zh-CN&pli=1

**Comment by cuiliang** [comment]
类似问题创建一条issue即可。

**Comment by TCOTC** [comment]
无法获取到某些网页的 URL 的问题似乎与浏览器拓展无关，我开启了拓展后仍然存在这个问题。

这个问题目前已知存在于 [CSDN](https://blog.csdn.net/maokexu123/article/details/42773599) 的网页。

**Comment by cuiliang** [comment]
使用这个方式获取。 有的网页是动态加载的，你的方式不一定能取到。

![image](https://github.com/cuiliang/Quicker/assets/1972649/12c0783c-e064-42c7-8888-ff82475ffc4d)

参考动作：
[当前网址Markdown - by CL - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=669e37d1-0f42-4369-849e-08daf13f5a77)

**Comment by TCOTC** [comment]
使用这个方式后，即使选中的文本不是在浏览器上，也会获取已经在浏览器上打开的网页的 URL 。

我希望实现的是：只有在浏览器中选中文本时才获取 URL

**Comment by cuiliang** [comment]
那你可以试试用模拟ctrl+c后读取剪贴板文本，如果是浏览器里复制的，会有网址信息
![image](https://github.com/cuiliang/Quicker/assets/1972649/a61b4709-c70c-4398-937e-25354a47ad4c)

**Comment by TCOTC** [comment]
还是「即使选中的文本不是在浏览器上，也会获取已经在浏览器上打开的网页的 URL」，我尝试了两种动作流程：

**其一：**
1. 获取选中的文本（这个应该是模拟 Ctrl+C ）
2. 获取剪贴板文本

![image](https://github.com/cuiliang/Quicker/assets/78434827/05b06eb6-a52e-4c5d-aff8-ddb72c673246)

![image](https://github.com/cuiliang/Quicker/assets/78434827/ecb9ea0b-9c93-4c2c-8bbc-82cd7e07e59d)

**其二：**
1. 模拟按键B（参数）
2. 获取剪贴板文本

![image](https://github.com/cuiliang/Quicker/assets/78434827/18a75cdd-f205-44ef-9d45-abb33e8f88c3)

![image](https://github.com/cuiliang/Quicker/assets/78434827/ecb9ea0b-9c93-4c2c-8bbc-82cd7e07e59d)

**Comment by cuiliang** [comment]
不可能，没有浏览器扩展，不可能在其它位置获得浏览器网址。 
检查一下有没有停掉浏览器扩展获得网址的步骤，然后调试运行看看。

**Comment by TCOTC** [comment]
太尴尬了，忘记了停用[刚才加上的「浏览器控制」](https://github.com/cuiliang/Quicker/issues/2047#issuecomment-1837461304)

~~但现在上述[两种动作流程](https://github.com/cuiliang/Quicker/issues/2047#issuecomment-1837466876)在网页上选中文字也无法获取到 URL 了~~

**Comment by cuiliang** [comment]
调试运行试试

**Comment by TCOTC** [comment]
不对，这个方式跟提 issue 时的表现是一样的，其他的网页能获取到 URL ，就是 [CSDN](https://blog.csdn.net/maokexu123/article/details/42773599) 的这个不行：https://blog.csdn.net/maokexu123/article/details/42773599

这个是获取不到的：https://temp.getquicker.net/915255/4fd48b39c8b14f09ae9167de13513833.html

这个是能获取到的：https://temp.getquicker.net/915255/e4a24d2597304a6691c4ae19fa616852.html

**Comment by cuiliang** [comment]
那就没办法了，可能csdn做了屏蔽，毕竟复制都是要登录的。
还有一个办法，根据你所使用的浏览器，判断一下前台窗口的进程名称是不是浏览器，如果是的话，就用上面浏览器扩展的方式来获取网址。

**Comment by TCOTC** [comment]
好吧只能这样了，感谢❤

p.s. 在网页上是能够直接 Ctrl+C 复制文本的，就是不知道为什么不能获取到 URL

**Comment by TCOTC** [comment]
另外，请问 Quicker 的浏览器扩展大概在什么时候会升级到 Manifest V3 ？

**Comment by cuiliang** [comment]
不太确定，看时间和谷歌的最终要求，尽量往后放了。
