### ISSUE TITLE
无法获取网页标题

### ISSUE THREAD

**Issue by TCOTC** [cuiliang/QuickPadCn#2048]
**描述BUG**
无法获取网页标题

**重现步骤**
1. 使用动作「[发送到flomo](https://getquicker.net/Sharedaction?code=a039da82-103a-4e46-ad3a-08dbb89e3001)」
2. 打开 [某一个网页](https://zhidao.baidu.com/question/1894050159402631948.html) ，选中文本后运行动作
3. 没有获取到网页标题

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/78434827/fc9aa666-1155-4d9e-a6b0-3bdbc9127d30)

![image](https://github.com/cuiliang/Quicker/assets/78434827/5700a7fa-eaba-44ab-8d59-0c1e7a75ed6d)

**环境信息:**
 - 操作系统版本：Windows 10 家庭中文版 22H2
 - Quicker版本：1.40.17

**附加信息**
1. 我是该动作的作者

2. [调试文件](https://temp.getquicker.net/915255/452b52a5971840d39a2d4b8f3798a4b0.html) → 在 「4.5.0.1.2 浏览器控制 获取网页标题」出现了异常：

```
异常：浏览器 chrome 未连接。
   在 WyrGuIqzOi04VXiCp9l.GfUKrrqVY1rbUTtege9.u9peGyCTMu2(String  , Int32  )
   在 WyrGuIqzOi04VXiCp9l.GfUKrrqVY1rbUTtege9.h8HeGIt4eHU[pKloioTxf51ETSSGCsJ](ChromeCommandMessage`1  , Boolean  , String  , Int32  )
   在 WyrGuIqzOi04VXiCp9l.GfUKrrqVY1rbUTtege9.QTKeGr5eYNM[ul5SPVTsD1QOP5eXoy7](ChromeCommandMessage`1  , String  , Boolean  , Int32  , Int32  )
   在 Quicker.Utilities._3rd.Chrome.ChromeControl.SendMessageToBrowser[T](ChromeCommandMessage`1 msg, String browser, Boolean waitResponse, Int32 timeoutMs, Int32 procId)
   在 Quicker.Utilities._3rd.Chrome.ChromeControl.ExecuteTabScript(String browser, Nullable`1 tabId, String script, Boolean waitResponse, Int32 timeoutMs, Boolean allFrames, Int32 frameId, Boolean waitManualReturn)
   在 fny7SLq8RlRWO0cXHPy.EbtQ1sqixBtXmyZnkSm.GetElementInfo(Nullable`1 tabId, ActionStep step, ActionExecuteContext context, XAction action, Int32 timeoutMs, Boolean allFrame, Int32 frameId)
   在 fny7SLq8RlRWO0cXHPy.EbtQ1sqixBtXmyZnkSm.<>c__DisplayClass91_0.nNJGqZyhF7I()
   在 Quicker.Domain.Actions.X.XActionHelper.ExecuteCommonAction(ActionExecuteContext context, ActionStep step, XAction action, Func`1 actionFunc, Action successAction, Action failAction, StepInParamDef stopIfErrorParam, StepOutParamDef isSuccessOutputParam)
步骤(sys:chromecontrol)执行失败，原因：浏览器 chrome 未连接。
```

**Comment by TCOTC** [comment]
关联：https://github.com/cuiliang/Quicker/issues/2047

**Comment by TCOTC** [comment]
我对这个不了解，请问是否有解决方法？

**Comment by cuiliang** [comment]
根据所使用的浏览器，安装扩展。如果已安装扩展，参考文档里排查连接情况。 
参考：https://getquicker.net/kc/help/doc/chromecontrol
谷歌浏览器扩展地址：https://chromewebstore.google.com/detail/quicker-connector/klggbkjfmbonefdcfkiidhcmfjdfnepa?hl=zh-CN&pli=1

**Comment by cuiliang** [comment]
浏览器控制可以直接获得当前标签页的标题和网址：
![image](https://github.com/cuiliang/Quicker/assets/1972649/6745fb4f-bed6-4bd5-833f-6c143f3fcb71)

参考动作：
[当前网址Markdown - by CL - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=669e37d1-0f42-4369-849e-08daf13f5a77 )

**Comment by TCOTC** [comment]
感谢，「无法获取网页标题」是我无意中关掉了浏览器拓展导致的
