### ISSUE TITLE
高级鼠标触发有一定延迟并吞操作

### ISSUE THREAD

**Issue by Ezioabcd** [cuiliang/QuickPadCn#2049]
**描述BUG**
高级鼠标触发用于切换标签页和直接快捷键切换相比有延迟

**重现步骤**
1. 高级鼠标触发中右键为引导键，滚动滚轮触发ctrl+page up/down快捷键
2. 白名单程序msedge
3. 右键按下滚动滚轮，可以明显感受到鼠标操作完成后半秒左右后标签页才切换；甚至快速连续滚动滚轮（**非**无级滚轮）出现卡顿（在第一或二个标签页处卡住滚完才直接切换至应到的标签页）、吞操作的情况（比如滚了5下却只切换了4次）
4. 尝试直接用ctrl+page up/down切换标签页，发现没有任何延迟与卡顿，按下按键秒切，

**环境信息:**
 - 操作系统版本：Win11最新专业版+Edge最新版
 - Quicker版本：1.40.17

**附加信息**
应该和性能无关吧，CPU AMD R9

**Comment by Ezioabcd** [comment]
刚快速滚了两圈，直接把鼠标卡住了，鼠标有一秒钟动不了了直接

**Comment by cuiliang** [comment]
本地测试没有这样的现象，请把设置截图一下看看。
![image](https://github.com/cuiliang/Quicker/assets/1972649/b9ce20d5-6ccc-42e0-9754-19a38288b1e8)

https://github.com/cuiliang/Quicker/assets/1972649/dda900d7-3633-45ac-951a-e777a52de0aa

另外
1）检查一下这里是不是设置了较长的时间
![image](https://github.com/cuiliang/Quicker/assets/1972649/ccdc1f11-9d7f-4153-8dfb-172cd94cac25)

2）高级鼠标触发的任务是队列化执行的，检查一下前面有没有需要较长时间完成的任务还没有结束。

**Comment by Ezioabcd** [comment]
![image](https://github.com/cuiliang/Quicker/assets/88655701/7e96e908-3162-4b02-b970-e2b1f974ef89)
<img width="900" alt="20231205_090117_558_copy" src="https://github.com/cuiliang/Quicker/assets/88655701/d88c041f-6c29-40a8-9246-451d281471fd">
另外我发现不止是这样的问题，就像我上条说的经常出现鼠标无法移动的现象，具体表现就是执行一个需要发送快捷键的动作后鼠标直接卡死不动一两秒钟，重启软件和电脑还会复现……

**Comment by cuiliang** [comment]
没有遇到过类似卡住鼠标的现象，暂时也没有其它类似的反馈。 
建议排查：
1）退出所有其它无关程序，测试一下看看是否仍然有这个现象。
2）如果有别的电脑，换一个电脑试试。
3）如果有其它品牌的鼠标，换一个鼠标试试。 如果鼠标带驱动，卸载驱动软件试试。

**Comment by Ezioabcd** [comment]
终于找到了，是LenovoLegionToolkit的bug影响了所有和ctrl相关的快捷键，和quicker无关，主要是我基本上所有快捷键都是在Quicker中的动作，一时以为是quicker的问题🙇‍♂️🙇‍♂️🙇‍♂️
