### ISSUE TITLE
在参考图 PureRef 中无法使用 Quicker

### ISSUE THREAD

**Issue by dkpress** [cuiliang/QuickPadCn#2051]
**描述BUG**
在软件“PureRef”中无法使用

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 10 22H2
 - Quicker版本：1.40.11

**附加信息**
做 3D 设计会经常使用 PureRef 这个软件来存放各种参考图，我想使用左键辅助来提升效率，结果发现在这个软件中 Quicker 无法使用。无论是常规动作、左键辅助都不行。

**Comment by cuiliang** [comment]
激活不了面板窗口么？ 还是能激活，但是设置的动作没有效果？

**Comment by dkpress** [comment]
> 激活不了面板窗口么？ 还是能激活，但是设置的动作没有效果？

可以激活面板的，包括轮盘或者鼠标手势都可以激活，但是都无法生效。激活面板点击动作也不行，左键辅助也无效。

**Comment by cuiliang** [comment]
如果是在里面模拟按键，有的软件实现快捷键的机制不是windows标准机制，而是类似于键盘检测的方式，这时候通常一个键需要按住保持一会儿才能被它检测到。 
可以试试使用按键输入分别按下和抬起按键，或用多步骤输入，然后在按下和抬起之间增加一些延迟。 https://getquicker.net/KC/Help/Doc/inputscript

**Comment by dkpress** [comment]
> 如果是在里面模拟按键，有的软件实现快捷键的机制不是windows标准机制，而是类似于键盘检测的方式，这时候通常一个键需要按住保持一会儿才能被它检测到。 可以试试使用按键输入分别按下和抬起按键，或用多步骤输入，然后在按下和抬起之间增加一些延迟。 https://getquicker.net/KC/Help/Doc/inputscript

嗯嗯，我挨个试了一下，多步骤输入里面按下抬起分开也不行，但是能识别“模拟按键 B”的语法，我就用这个方式来创建动作好了。感谢~
