### ISSUE TITLE
点击右键时，偶现提示发送模拟按键失败

### ISSUE THREAD

**Issue by HZFeng666** [cuiliang/QuickPadCn#2052]
**描述BUG**
从1.39升级到1.40版本后，电价右键时提示：“发送模拟按键失败了，有可能被360拦截”。但是360的信任和驱动防护没有更改，在1.39的时候就没出现过这个问题，重新添加信任也不好使，只有关闭驱动防护才可以。为什么在1.39版本的时候同样的设置没有这个bug啊。

**重现步骤**
1.
2.

**相关截图**
![Quicker_20231217_171530](https://github.com/cuiliang/Quicker/assets/58537693/1ba16caa-a1fe-42e9-93f9-9d1d4925e44b)

如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.40.23

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这是360的问题，可以彻底退出它测试。 要彻底关闭驱动防护功能，具体可以向360反馈一下

**Comment by HZFeng666** [comment]
我刚才回溯旧版本试了一下，只有最新的1.40.23会出现这个问题，我回退到1.40.22还有之前的几个版本都不会出现这个问题

**Comment by cuiliang** [comment]
这个请去咨询360。

**Comment by cuiliang** [comment]
1） 这是360的老问题。
2） Quicker没有问题，我这里没有什么可以做的。该提示的已经提示了。
3） 如果相信Quicker**有问题**，就请卸载Quicker，或者去用第三方病毒检测平台检测。
4） 如果相信Quicker**没问题**，就请参考文档里的说明，卸载360或者禁用驱动防护，或者请360解决此问题。
