### ISSUE TITLE
弹出面板黑名单

### ISSUE THREAD

**Issue by Ailwin** [cuiliang/QuickPadCn#2053]
在有些软件中只想要用鼠标手势功能，弹出面板快捷键跟软件冲突，不使用弹出面板的话鼠标手势也用不了，能不能增加弹出面板黑名单选项或者解决这个问题的其它办法？

**Comment by cuiliang** [comment]
1）设置-弹出面板，取消里面的设置。
2）在高级鼠标触发中添加自定义的弹出面板设置，并且在这里设置黑名单程序。
