### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by jocxhk** [cuiliang/QuickPadCn#2054]
![Snipaste_2023-12-26_00-12-06](https://github.com/cuiliang/Quicker/assets/101846697/026a9638-3641-4318-ad8a-613cb5d6e283)

**描述BUG**
对bug的清晰简洁描述。
鼠标移动X坐标参数：749,954，并点击，测试这个会，关闭当前软件。
建议获取屏幕坐标后，自动输入到x:749,y:954

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win10 企业版
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个要自己在动作里实现。 
我不清楚您的目的，无法给出建议。 
另外提交issue，请在问题摘要中概要描述问题，以便于从列表中区分问题，而不是保留“问题摘要”作为标题。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
