### ISSUE TITLE
询问广告是否可信。

### ISSUE THREAD

**Issue by hikehood** [cuiliang/QuickPadCn#2055]
我在安装沙拉查词动作的时候，发现在其[使用说明页面](https://saladict.crimx.com/manual.html)左侧挂了一个西柚广告，请问有人用过这个吗？靠谱吗？是插件作者自己挂的广告吗？

**Comment by hikehood** [comment]
还有这个“bug label”怎么去掉，我不是想提bug，怎么编辑也去不掉这个bug标签

**Comment by cuiliang** [comment]
那个网页是沙拉扩展的，和quicker没有关系，需要自行判断。
不过我打开这个网页没有看到什么广告的。
