### ISSUE TITLE
在没有运行动作的情况下，quicker软件的CPU占用持续保持在10%~40%，为什么会出现这个情况呢？

### ISSUE THREAD

**Issue by hamson1026** [cuiliang/QuickPadCn#2056]
**描述BUG**
在没有运行动作的情况下，quicker软件的CPU占用保持在10%~40%

**重现步骤**
未运行任何动作，quicker软件的CPU占用持续保持在10%~40%

**相关截图**
![snipaste_20240103_181233](https://github.com/cuiliang/Quicker/assets/67315180/3778173d-01bd-421b-9d75-1038b1f0a192)

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.40.23

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
看起来遇到bug了， 试下这里下载安装最新版 https://getquicker.net/Help/Versions  然后观察是否还出现问题。

如果仍然出现，请告诉我如何复现，或者我提供一个调试工具抓取一些dump文件来分析一下。

**Comment by cuiliang** [comment]
你好，问题还存在么？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
