### ISSUE TITLE
设置界面，鼠标悬停在【用户中心图标】上时，图标异常。

### ISSUE THREAD

**Issue by CWZ7605** [cuiliang/QuickPadCn#2059]
**描述BUG**
设置界面，鼠标悬停在【用户中心图标】上时，图标异常。

**重现步骤**
1.打开设置界面
2.把鼠标悬停在左上角的【用户中心】图标上。

**相关截图**
![图片](https://github.com/cuiliang/Quicker/assets/4016785/ad8241c0-699a-4c39-a682-e479309ab379)

**环境信息:**
 - 操作系统版本：Win11
 - Quicker版本：1.41.3

**附加信息**
旧版本也有这个情况

**Comment by cuiliang** [comment]
感谢反馈

**Comment by cuiliang** [comment]
你好，请问显示器是多少缩放比例？

**Comment by CWZ7605** [comment]
> 你好，请问显示器是多少缩放比例？

100%，1080P

**Comment by cuiliang** [comment]
更新了一下 1.41.5  https://getquicker.net/Help/Versions  试一下看看

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen

**Comment by CWZ7605** [comment]
> 先关了，如果还有问题，请再reopen
好，已测试，已经没问题了！
