### ISSUE TITLE
轮盘菜单不好使

### ISSUE THREAD

**Issue by Lngman** [cuiliang/QuickPadCn#2060]
**描述BUG**
我不知道是我环境问题还是啥，轮盘菜单不太好打开，反复验证之后发现必须猛地摁下触发键才能打开

**重现步骤**
1.我的轮盘菜单设置键位是X1
2.其他啥也没动

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.41.3

https://github.com/cuiliang/Quicker/assets/105780272/ae04c18d-53b7-4edb-985d-0908eb6c044b

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果之前是正常的，可能你的鼠标坏了，换个鼠标试试。 也可以换成其他按键来触发试试。

**Comment by Lngman** [comment]
> 如果之前都正常的话，可能你的鼠标坏了，换个鼠标试试。也可以换成其他按键来触发试用。

我的鼠标没坏，打游戏啥的都正常，这个软件我今天才下载，这是我第一次用

**Comment by cuiliang** [comment]
游戏里用x1么？ 可以改成别的键测试一下。 另外要注意触发方式是按下立即移动。 如果还有问题，可能是其它使用挂钩的软件影响了，退出其它所有软件测试排查一下。

**Comment by Lngman** [comment]
> 游戏里用x1么？可以改成其他键测试一下。另外要注意触发方式是按立即移动。如果还有问题，可能是其他使用挂钩的软件影响了，退出其他所有软件测试排查一下。

我可以确定我的外设是没有问题的，我所有键位都试了一遍，都是必须猛地摁下去才能出来轮盘。软件冲突我倒是没想到，我晚点测试一下给您回复

**Comment by Lngman** [comment]
> 游戏里用x1么？可以改成其他键测试一下。另外要注意触发方式是按立即移动。如果还有问题，可能是其他使用挂钩的软件影响了，退出其他所有软件测试排查一下。

我可以确定我的外设是没有问题的，我把所有的键位都测试了一遍，都是必须猛地摁下去才能出来轮盘菜单。软件冲突我倒是没想到，晚点测试一下给您回复

**Comment by Lngman** [comment]
作者你好，经过多次验证我发现没有跟别的软件冲突，并且我在win7、win10、Win11都进行了测试，win7与Win10都是什么软件都没装。但都存在相同的问题

**Comment by cuiliang** [comment]
是按下立即移动了么？
我也不了解你那边具体什么情况，不过这个功能目前应该是没什么问题的，用的人很多，我自己也天天用。 
如果需要可以加我qq 197906，然后用向日葵远程测试一下。

**Comment by cuiliang** [comment]
原因：没有按下立即移动😂
