### ISSUE TITLE
动作的图标库能不能加个分类标签

### ISSUE THREAD

**Issue by NightmareZero** [cuiliang/QuickPadCn#2061]
**需求描述**
希望可以给图标库加个分类，这样一坨一坨的太难找了

**描述你想要的解决方案**
加一个标签页，或者类似于第二张图里面的"粗细"选择那种，但是不能仅限于粗细，最好能分个类

**描述您考虑过的替代方案**

 **其他上下文**
![Screenshot 2024-01-15 160040](https://github.com/cuiliang/Quicker/assets/17422155/641aa577-5072-4ff0-8e9e-a878136362cf)
![Screenshot 2024-01-15 160058](https://github.com/cuiliang/Quicker/assets/17422155/0dc37654-9b89-449a-9364-5ae6d5b504b0)

**Comment by cuiliang** [comment]
可以从图标官网找，然后在动作里按对应格式写。
https://fontawesome.com/v5/search
没有这方面的时间来做整理了。
