### ISSUE TITLE
能否在动作的右键菜单添加设置直达词

### ISSUE THREAD

**Issue by NightmareZero** [cuiliang/QuickPadCn#2062]
**需求描述**
今天研究设置的时候发现了 "搜索" 这个功能， 发现可以给动作设置直达词，但是这个功能支持的动作不太多，估计很多人都不知道quicker也有类似于utools的那种输入框式的搜索功能
另外，如果想从动作中获取用户输入的东西，应该读哪个参数？ (就像获取用户的菜单，就要用quicker_in_param一样)

**描述你想要的解决方案**
1. 可以在右键设置选中动作的直达词
2. 有无在动作中获取搜索框输入值的方法
3. 

**描述您考虑过的替代方案**

 **其他上下文**

**Comment by cuiliang** [comment]
直达词是早期设计的功能，后来不建议用了。直接搜索后按tab就可以选择动作。
为动作传递参数，如果一次性的可以参考这个帖子： https://getquicker.net/QA/Question/23135
如果想实时返回结果，参考：https://getquicker.net/kc/help/doc/search-adv

**Comment by NightmareZero** [comment]
> 直达词是早期设计的功能，后来不建议用了。直接搜索后按tab就可以选择动作。 为动作传递参数，如果一次性的可以参考这个帖子： https://getquicker.net/QA/Question/23135 如果想实时返回结果，参考：https://getquicker.net/kc/help/doc/search-adv

好叭，多好的功能啊
不会去掉吧话说
