### ISSUE TITLE
將窗口设为前台後，顯示狀態會從原本的最大化變為普通

### ISSUE THREAD

**Issue by Louie997** [cuiliang/QuickPadCn#2064]
**描述BUG**
不確定是 bug 還是 Windows 的特性，
使用「窗口操作」模塊中的「设置为前台窗口」，將窗口设为前台後，顯示狀態會從原本的最大化變為普通。
只有在重啟 Quicker 後第一次執行「设置为前台窗口」才會有這個問題。

**重现步骤**
1. 重啟 Quicker 
2. 把焦點移到其他窗口
3. 執行如下動作，這邊以 VScode 為例，將 VScode 设置为前台窗口
![image](https://github.com/cuiliang/Quicker/assets/88768177/6e4ea8c4-e36d-4731-855e-4e039507124e)

影片示範如下

https://github.com/cuiliang/Quicker/assets/88768177/eaffd109-cbbb-42d7-949e-d8174f7fc5f5

**相关截图**
如上

**环境信息:**
 - 操作系统版本：Win 11
 - Quicker版本：
![image](https://github.com/cuiliang/Quicker/assets/88768177/f15e697a-7237-4867-b2be-d6bbd51f954a)

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 试下这里最新版，我这里测试是正常的。

**Comment by Louie997** [comment]
更新到1.42.0還是會有這個情況

**Comment by cuiliang** [comment]
动作分享一下我试试你的动作。
我是直接设置的窗口句柄 
![image](https://github.com/cuiliang/Quicker/assets/1972649/f458d58a-f89f-4060-8fdd-3dc8c943d8ab)
![image](https://github.com/cuiliang/Quicker/assets/1972649/1c06fa5c-dca1-44cf-b04b-5e8d809c0d63)

**Comment by cuiliang** [comment]
另外也可以重启一下电脑试试

**Comment by Louie997** [comment]
https://getquicker.net/Sharedaction?code=002b1f96-3df0-463c-5369-08dc15e737a9

**Comment by cuiliang** [comment]
测试正常
https://github.com/cuiliang/Quicker/assets/1972649/c55493c7-f78a-4664-bd8b-e1b3e2b04b27

**Comment by Louie997** [comment]
我這邊重启电脑後還是一樣

**Comment by cuiliang** [comment]
不清楚了，也许是系统原因，如果有其它可能影响的软件也可以关闭测试看看，如果有其它电脑，也可以换一个电脑试一下。 我明天到单位用单位电脑试试。

**Comment by cuiliang** [comment]
试一下其它程序的窗口有类似的现象么？比如记事本

**Comment by Louie997** [comment]
> 试一下其它程序的窗口有类似的现象么？比如记事本

记事本也會有這種現象


https://github.com/cuiliang/Quicker/assets/88768177/774f3592-bbb2-4a1d-9cc8-2dd957eb8101


基本上我這邊所有程序都會這樣，因為只要是涉及到「设置为前台窗口」的動作都會有這個問題，
今天把「设置为前台窗口」單獨拎出來測試才發現好像是它的問題。

> 也许是系统原因，如果有其它可能影响的软件也可以关闭测试看看，如果有其它电脑，也可以换一个电脑试一下

我把可能影響的其他應用關了，剩下一些系統的應用，還是一樣。

另外，我在另一臺電腦（Win 10、Quicker 1.42.0）上做相同的測試也是會有這個問題。

**Comment by Louie997** [comment]
之所以發現這個問題是因為每次重新開機後，Quicker 第一次執行「设置为前台窗口」就會觸發這個問題，但是接下來執行第二次、第三次……，就不會發生最大化變為普通，會正常的維持最大化。

**Comment by cuiliang** [comment]
哦哦，重启quicker之后第一次使用确实有这个现象，可以复现。 
这个有点难以理解，都是调用相同的API，可能系统做了什么特殊处理，我等研究下。

**Comment by Louie997** [comment]
剛剛發現一個不會觸發這個問題的方法：
1. 讓 VScode 在前台
2. 重啟 Quicker
3. 最小化 VScode
4. 執行測試動作

這時候就能維持最大化
影片示範：

https://github.com/cuiliang/Quicker/assets/88768177/c75fd21e-3927-4d7f-826f-d09e0fa82c00


如果是直接點擊任務欄切換到其他窗口，而不是最小化 VScode，就會有問題。

**Comment by cuiliang** [comment]
可能找到原因了，第一次调用ShowWindow，Windows会忽略传递的参数，可能是这个原因造成的。 我试试增加个判断，等下个版本看看。

**Comment by cuiliang** [comment]
更新了一下，可以再试试，同时也注意下看看会不会产生新的问题 
https://getquicker.net/Help/Versions

**Comment by Louie997** [comment]
這兩天用感覺沒問題了，感謝
