### ISSUE TITLE
运行脚本这个动作, 能否添加接收返回结果(exitcode)的方法

### ISSUE THREAD

**Issue by NightmareZero** [cuiliang/QuickPadCn#2065]
**需求描述**
现在没法判断脚本执行是否成功，只能通过监听stderr，但是这个分析stderr太麻烦了

**描述你想要的解决方案**
可以获取到退出的返回码，exit 0  exit  1 和 exit  255还是有区别的

**描述您考虑过的替代方案**
或者已经提供了方案，但是我没找到文档？？我就是想执行一条命令，然后接收返回结果 (exitcode)， 甚至不是int是bool都行啊

 **其他上下文**

**Comment by NightmareZero** [comment]
我现在只能通过添加
if ($?) {
    Write-Output "ok"
}
然后判断最后一行的方式来判断成功与否

**Comment by cuiliang** [comment]
运行脚本不支持，如果是exe程序，用运行和打开  
https://getquicker.net/Common/Topics/ViewTopic/23237
