### ISSUE TITLE
副屏悬浮动作问题，在副屏悬浮动作失效

### ISSUE THREAD

**Issue by sun-25** [cuiliang/QuickPadCn#2066]
**描述BUG**
在副屏悬浮动作时 ，无法悬浮

**重现步骤**
1.电脑连接副屏
2.右键quicker动作--悬浮--悬浮此动作

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：1.40.7

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  使用这里的最新版测试一下看看

**Comment by sun-25** [comment]
更新后已解决，谢谢

> https://getquicker.net/Help/Versions 使用这里的最新版测试一下看看
