### ISSUE TITLE
具有自动补全功能 窗口中不存在选中文本时，"获取选中的文本"会默认获取窗口中文本的状况

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#2070]
**描述BUG**
对bug的清晰简洁描述。
可自动补全窗口中不存在选中文本时，"获取选中的文本"会默认获取窗口中文本，其它文本窗口未见

**重现步骤**
![VeryCapture_20240209144124](https://github.com/cuiliang/Quicker/assets/63462588/3e9eb9fa-4bdf-491f-aad5-6718bead7710)

**相关截图**
![2](https://github.com/cuiliang/Quicker/assets/63462588/d84c4343-23fa-4dc9-9551-028ddf96c864)
![1](https://github.com/cuiliang/Quicker/assets/63462588/165febeb-a716-46d2-97f2-eda0819f32bd)

**环境信息:**
 - 操作系统版本：win 10
 - Quicker版本： 专业版 1.42.8

**Comment by cuiliang** [comment]
可以在文本窗口的步骤里设置。
![image](https://github.com/cuiliang/Quicker/assets/1972649/33a88bcb-fb52-4ea5-90e1-70e627063e96)

**Comment by Hefang2000** [comment]
> 可以在文本窗口的步骤里设置。 ![image](https://private-user-images.githubusercontent.com/1972649/303629279-33a88bcb-fb52-4ea5-90e1-70e627063e96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODAyMzgsIm5iZiI6MTcwNzQ3OTkzOCwicGF0aCI6Ii8xOTcyNjQ5LzMwMzYyOTI3OS0zM2E4OGJjYi1mYjUyLTRlYTUtOTBlMS03MGU2MjcwNjNlOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMTE1ODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcwZjY4NzVkMGZkZTQ4YjBjMjljN2U0MjE3ZDY4NDFiODBmNmEwN2UyZjg4ZGVlZGJiZDFjZDMwYzMzOTc4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z-XEFk9ZI4ZtzLQc5LctJd8IwiiafJ4Zl5CWflhhVNE)

1.不好意思，你错意了，你说的我知道，那个也是个大问题--当存在两个动作时其中一个提供窗口，另一个根据是否先选中决定接下来的流程，两者形式与自身设定不统一的话，就会出现不正确的结果，简而言之两个动作之间数据密闭性不够，容易存在意料之外的交互，导致结果出现误差。
2.二实际上这个issue中，我反馈的是像代码编辑器这样的窗口，在没有选中文本的时候，“获取选中的文本”也会自动获取，即使非quicker提供的窗口如 Notepad3 也会有这样的状况。

**Comment by cuiliang** [comment]
2） 这是编辑器的功能，没有选中的时候ctrl+c会复制整行，有的可以设置，有的没法设置。
1）没看懂，

**Comment by Hefang2000** [comment]
额 ……那能不能确定获取的文本为选中文本呢（o_o）"

**Comment by cuiliang** [comment]
有一个变通的办法，如果选中文本，其背景颜色为特定值，可以先尝试找色判断一下。
其它就是要请编辑器的开发商来修改增加设置支持了。

**Comment by Hefang2000** [comment]
不好意思，有些不现实吧

**Comment by Hefang2000** [comment]
WindowsOCR无法使用且的大部分只能通过剪贴板获取文本，我没办法了，只能通过获取两侧文本进行复合校验的保守/妥协策略使选中文本为选中文本来满足个人的多种应用场景了。一种笨重且保守的策略如下：
[保守&妥协策略](https://getquicker.net/subprogram?id=80dc5aaa-524d-4a9c-9b70-08dc2bcaf829)
