### ISSUE TITLE
quicker 提供的文本框中选中文本对"←→"按键响应与常见办公软件不同

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#2071]
**需求描述**
##对选中文本希望“←→”可以如常见软件一样使光标致选中文本两端

**描述你想要的解决方案**
##更改或提供个性化选项

**不同之处**
![VeryCapture_20240209155332](https://github.com/cuiliang/Quicker/assets/63462588/b3e51c57-6a4c-4969-b3b5-b22b6ec7f193)

**Comment by cuiliang** [comment]
这个是底层控件的功能，等有空研究下有没有办法修改。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions 1.42.11版本中实现了。
