### ISSUE TITLE
动作检索相关

### ISSUE THREAD

**Issue by Vstory** [cuiliang/QuickPadCn#2074]
**描述BUG**
如图所示，搜索该动作时，我只有输入完所有的动作名 `吾爱自动签到` 该动作才会显示

**重现步骤**
事件触发里添加动作，搜索时输入“吾爱自动签到”

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/20795557/83466c5b-14d5-47fb-8809-9c831d9bb174)

**环境信息:**
 - 操作系统版本：23H2
 - Quicker版本：1.42.9

**附加信息**
暂无

**Comment by cuiliang** [comment]
这里本身设计的就是完整匹配，和实际运行的时候匹配效果是一样的。 可以点右边...打开搜索界面。

**Comment by Vstory** [comment]
> 这里本身设计的就是完整匹配，和实际运行的时候匹配效果是一样的。 可以点右边...打开搜索界面。

收到，谢谢
