### ISSUE TITLE
资源管理器获取地址失败

### ISSUE THREAD

**Issue by AustinZhang1024** [cuiliang/QuickPadCn#2075]
**描述BUG**
获取资源管理器路径/跳转路径 在资源管理器中执行时报错

**重现步骤**
1. 执行脚本
2. 报错

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/25601078/1eccc4fd-e70d-4683-99b6-69c97021d665)

**环境信息:**
 - 操作系统版本：Windows 11
 - Quicker版本：1.42.8，1.42.15

**附加信息**
无

**Comment by cuiliang** [comment]
如果资源管理器安装了第三方插件，尝试卸载插件（如clover）后重启系统；
其它情况尝试直接重启系统，然后观察一下是否可以立即复现。

**Comment by AustinZhang1024** [comment]
> 如果资源管理器安装了第三方插件，尝试卸载插件（如clover）后重启系统； 其它情况尝试直接重启系统，然后观察一下是否可以立即复现。

发现是dopus启用了替代资源管理器造成的

**Comment by cuiliang** [comment]
用do的话可以这里选一下来兼容。

![image](https://github.com/cuiliang/Quicker/assets/1972649/a2024dfd-6003-47b7-8613-5d2b7e87d499)

**Comment by AustinZhang1024** [comment]
> 用do的话可以这里选一下来兼容。
> 
> ![image](https://private-user-images.githubusercontent.com/1972649/308433833-a2024dfd-6003-47b7-8613-5d2b7e87d499.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTkyNzYsIm5iZiI6MTcwOTA5ODk3NiwicGF0aCI6Ii8xOTcyNjQ5LzMwODQzMzgzMy1hMjAyNGRmZC02MDAzLTQ3YjctODYxMy01ZDJiN2U4N2Q0OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDU0MjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYyZDYxOTVhM2U2MTMzMmFmZWI0YWY4MmE4YWY4MDM1YmY3ZDBlMWY0ZjkzZTc3OTVlZDVjNmMzMzQ1M2ZlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K2XENmCqHmL_lus_ESOxQ4YvcF5FBt_5cYdhLkMu8aE)

解决了，感谢
