### ISSUE TITLE
“激活进程主窗口”模块运行似乎有点不合逻辑

### ISSUE THREAD

**Issue by Immortal-Sty** [cuiliang/QuickPadCn#2076]
# 需求描述

1. 在该模块的“窗口类名”或“窗口标题”设置好条件；
2. 运行；
3. 如果匹配失败，不会按“程序路径”中设定的运行，而是直接算运行失败。

# 描述你想要的解决方案

希望在“窗口类名”和“窗口标题”都匹配失败后，也按照“程序路径”中设定的运行，而不是直接算运行失败。

**Comment by cuiliang** [comment]
如果进程已经存在，就不能再去启动了，只能按窗口条件匹配。

**Comment by Immortal-Sty** [comment]
我的理解是：

进程名或进程 ID 以及窗口标题和窗口类名都是筛选条件，其中进程名或进程 ID 是必须条件，另外两个是可选条件。

如果筛选成功就激活窗口，筛选失败就重新再启动。

**Comment by cuiliang** [comment]
不是的，激活窗口的目的是激活进程的已有窗口。 所以如果进程还没有启动，就启动进程，如果已经启动，就查找那个符合条件的窗口将其激活的。

**Comment by Immortal-Sty** [comment]
好吧，谢谢。
