### ISSUE TITLE
评论输入框问题

### ISSUE THREAD

**Issue by Vstory** [cuiliang/QuickPadCn#2078]
**描述BUG**
主题下回复他人不能使用如图所示的输入框。

**重现步骤**
主题下回复他人不能使用如图所示的输入框。

**相关截图**
![image](https://github.com/cuiliang/Quicker/assets/20795557/aa3ee27e-80fc-4851-9e81-c829a9250eb3)

**环境信息:**
 - 操作系统版本：23H2
 - Quicker版本：1.42.15

**附加信息**

**Comment by cuiliang** [comment]
先把上面回复评论的框取消掉，才能使用下面的回复主贴的框。

**Comment by Vstory** [comment]
> 先把上面回复评论的框取消掉，才能使用下面的回复主贴的框。

![image](https://github.com/cuiliang/Quicker/assets/20795557/640bd404-b3ff-4cac-b95b-e1e80335cad1)
不一样，我的意思是楼中楼回复，能不能使用下面的输入框。

按你说的，那是直接回复帖子

**Comment by cuiliang** [comment]
哦哦，那个不行，为了节约空间使用的精简版控件。 另外这里预期的也是比较简单的评论或回复内容。

**Comment by Vstory** [comment]
> 哦哦，那个不行，为了节约空间使用的精简版控件。 另外这里预期的也是比较简单的评论或回复内容。

好吧
