### ISSUE TITLE
能不能提升开机启动优先级

### ISSUE THREAD

**Issue by sgrn666** [cuiliang/QuickPadCn#2082]
**需求描述**
可能是电脑问题，每次开机要等好久才能启动quicker，看网上说提升启动优先级要调用Windows接口，所以希望增加一个这个功能

**描述你想要的解决方案**
增加一个提升开机启动优先级的设置选项，可以满足不同人的需求

**描述您考虑过的替代方案**
酷呆桌面就有这样一个选项，选择后它开机启动就没有延迟

 **其他上下文**
试了网上的一些方案，都没用
![image](https://github.com/cuiliang/Quicker/assets/92671338/0cfe7315-a3b5-4e22-b58a-cffb57cebf1b)

**Comment by cuiliang** [comment]
没有控制优先级的办法。
优先启动一般是要做成windows服务，不是一个合理的选择。而且都想快了，就都快不了，目前慢有可能就是因为类似酷呆这种优先启动影响的。建议提升系统自身的性能，去除不必要的启动项，使用性能较好的固态硬盘作为系统盘。

**Comment by sgrn666** [comment]
好的，感谢
