### ISSUE TITLE
截图界面可扫描二维码

### ISSUE THREAD

**Issue by jeffzhou315** [cuiliang/QuickPadCn#2090]
在使用截图后右键菜单加入二维码识别选项

**Comment by cuiliang** [comment]
找一个识别二维码的动作，设置关联，然后就可以出现在菜单里了。 

[识别二维码/条形码 - by CL - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=17d74f99-a4df-40c3-0066-08da6ab12139 )

![image](https://github.com/cuiliang/Quicker/assets/1972649/35b23bf5-31ee-4030-988f-851cb3edb704)

![image](https://github.com/cuiliang/Quicker/assets/1972649/7cc447b9-ea75-4724-96e1-7a31b4d7e879)
