### ISSUE TITLE
新建组合动作界面，布局建议回复老版本的收藏常用项

### ISSUE THREAD

**Issue by ssf1992** [cuiliang/QuickPadCn#2092]
**需求描述**
目前的新建组合动作界面，左侧的命令树是固定的，用起来有点难受，老版本的收藏常用命令项就很好用，强留建议恢复！！！

因为每个人常用的命令都不一样，可能分散在好多个类别里，需要点开一个个找，还是很繁琐的，希望大佬们考虑一下下！！！

万分感谢！！！

**Comment by cuiliang** [comment]
![image](https://github.com/cuiliang/Quicker/assets/1972649/6b774d53-9cc9-4f1d-8e38-91ad0e6ac913)

**Comment by ssf1992** [comment]
> ![image](https://private-user-images.githubusercontent.com/1972649/323457988-6b774d53-9cc9-4f1d-8e38-91ad0e6ac913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTc1NzcsIm5iZiI6MTcxMzQxNzI3NywicGF0aCI6Ii8xOTcyNjQ5LzMyMzQ1Nzk4OC02Yjc3NGQ1My05Y2M5LTRmMWQtOGUzOC05MWFkMGU2YWM5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMDUxNDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU4MTQzZTE2MDNmODhhNWE4MDRiNTViMjBmMDliZDBhNjY1ZmI1YzQxZDQxNTEzYjU4NTRkOTJjY2NhYTgzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GXIoJtGc3BP_qHDadwMeogfAda8unlMhXNBdaVOGWAE)

非常感谢提醒！！！祝身体健康
