### ISSUE TITLE
取消数据同步对时间差3分钟的要求

### ISSUE THREAD

**Issue by Lamont191** [cuiliang/QuickPadCn#2101]
**需求描述**
取消数据同步对是时间差3分钟的要求，因为我的计算机时间被公司锁定无法修改，且时间误差是4分钟。

**Comment by cuiliang** [comment]
登录网页后，在会员中心页面右边点个人设置，里面可以设置最多允许的误差秒数。

**Comment by Lamont191** [comment]
问题已解决，谢谢！
