### ISSUE TITLE
在远程桌面上点击鼠标中键唤醒的是本机的面板而非远程的

### ISSUE THREAD

**Issue by daysmark** [cuiliang/QuickPadCn#2102]
**描述BUG**
MSTC远程桌面连接，在远程机器上点击鼠标中键，唤醒的是本机的面板而非远程的。鼠标手势在远程下也不起作用

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：WIN10
 - Quicker版本：1.42.32

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
将mstsc加入黑名单中。 或者试试全屏模式。

**Comment by daysmark** [comment]
感谢。加入黑名单后确实可以正常唤起远程的quicker了。
