### ISSUE TITLE
腾讯电脑管家自动升级之后Quicker Connect又不能用了

### ISSUE THREAD

**Issue by pythonlouvre** [cuiliang/QuickPadCn#2110]
**描述BUG**
腾讯电脑管家自动升级之后Quicker Connect又不能用了，之前是安装了电脑管家的体验版，换回正式版之后可以了，现在正式版自动升级了，也就是之前的体验版，这咋整？每次都要手工装老版本的电脑管家？

**重现步骤**

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by pythonlouvre** [comment]
![image](https://github.com/cuiliang/Quicker/assets/651199/30654ead-cb98-46cb-bd01-a3d1155868ba)

**Comment by cuiliang** [comment]
管家的详细版本号发一下

**Comment by pythonlouvre** [comment]
16.12.25248.212

**Comment by cuiliang** [comment]
从这里下载管家的新版 http://dlied6.qq.com/invc/xfspeed/qqpcmgr/versetup/portal/portal/PCMgr_Setup_17_0_25541_203_bcfcff.exe
