### ISSUE TITLE
搜索功能无法出现“网络搜索”结果

### ISSUE THREAD

**Issue by Ezioabcd** [cuiliang/QuickPadCn#2113]
**描述BUG**
Quicker的搜索功能无法在全局结果中出现“网络搜索”，已经打开了“包含在全局搜索中”，然而还是只能使用关键词触发

**重现步骤**
- 我想无需输入web这几个字母就可以触发“网络搜索”，为此我把搜索中其他功能全部关闭了，然而全局中无法出现相应结果
- 测试下其他搜索如“Quicker动作“、”文件(Everything)“等均可以无需触发词使用；只有”网络搜索“不行

**相关截图**
![image](https://github.com/user-attachments/assets/45dd8396-b240-40d6-8d57-11f4d249b1ee)
![image](https://github.com/user-attachments/assets/6580e451-3d9a-480d-88fb-726c022701ce)
![image](https://github.com/user-attachments/assets/75ca8bb8-3f2b-458e-8883-24c877630827)
![image](https://github.com/user-attachments/assets/52723d15-ee57-4bad-963e-ae9910f76ed7)

**环境信息:**
 - 操作系统版本：Win11 22631.3880
 - Quicker版本：1.43.11

**Comment by cuiliang** [comment]
应该是限制了。 因为这个主要目的是通过二级触发词来搜索关键词的，比较特殊一些。

**Comment by cuiliang** [comment]
你可以通过触发方式直接触发一下web搜索
![image](https://github.com/user-attachments/assets/e27aad7d-e5f1-451e-a705-15aeb2c905db)
