### ISSUE TITLE
英文输入法下，发送快捷键无效

### ISSUE THREAD

**Issue by Ti-M-E** [cuiliang/QuickPadCn#2114]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
请详细描述您的问题：
- 如果是动作问题，请发动作网址
- 完整的说明想实现什么目的。
- 目前是怎么做的（配上截图、录屏）
- 期望的结果
- 实际的结果（配上截图、录屏）
- 调试运行并提供调试文件网址 （参考https://getquicker.net/KC/Kb/Article/1044）

**Comment by Ti-M-E** [comment]
https://github.com/user-attachments/assets/f2357e43-1ee6-4155-8fd4-f2e2e0110a5b

**Comment by cuiliang** [comment]
本地测试没有发现类似现象。
试试手动按Alt+F4快捷键看看有没有效果，或许存在快捷键冲突。
如果有其它电脑，也可测试一下看看。

**Comment by Ti-M-E** [comment]
手动按Alt+F4可以正常触发,未发现快捷键占用

**Comment by Ti-M-E** [comment]
![tmp4799](https://github.com/user-attachments/assets/8dbb0997-eea1-44e7-907f-58cf43057273)
将输入法从“英语[英国]”切换到“英语[美国]”后解决此问题

**Comment by cuiliang** [comment]
> ![tmp4799](https://private-user-images.githubusercontent.com/178578945/358620251-8dbb0997-eea1-44e7-907f-58cf43057273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjAxMDQsIm5iZiI6MTcyMzg1OTgwNCwicGF0aCI6Ii8xNzg1Nzg5NDUvMzU4NjIwMjUxLThkYmIwOTk3LWVlYTEtNDRlNy05MDdmLTU4Y2Y0MzA1NzI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMTU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODFlZjdhZmIwMzRjNDljNDYyNzExNGNlZjU1MjhmZGY0NzU4ZDU1MjhkMDk1YTExMmJlNTUzYjNlNjNiMGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7H5PRwTydX7ib5QkxV0Yet2ovblU4pxwqkavwz7DIIg) 将输入法从“英语[英国]”切换到“英语[美国]”后解决此问题

感谢分享，什么奇怪的事情都会发生😂
