### ISSUE TITLE
选择颜色：初始值不支持Alpha

### ISSUE THREAD

**Issue by xunup** [cuiliang/QuickPadCn#2115]
**描述BUG**
选择颜色窗口无法根据输入的字符串调整透明值

**重现步骤**
1.输入字符串#00FFFFFF
2.当跳出编辑颜色窗口时Alpah值仍然时255

**相关截图**
1.
![image](https://github.com/user-attachments/assets/6e1a73f7-4408-44da-8ee8-6848df92a6a2)
2.
![image](https://github.com/user-attachments/assets/721fc3c2-eb9f-4c7d-b3be-d70f67407ca2)

**环境信息:**
 - 操作系统版本：windows11 23h2 内部版本：22631.4037
 - Quicker版本：1.43.17

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈，我研究下。

**Comment by cuiliang** [comment]
已更新版本 https://getquicker.net/Help/Versions ，方便的时候测试一下看看。

**Comment by xunup** [comment]
感谢，已经正常了
