### ISSUE TITLE
问题摘要现在鼠标轨迹基本上用不了了

### ISSUE THREAD

**Issue by dayuanzi112** [cuiliang/QuickPadCn#2117]
**描述BUG**
对bug的清晰简洁描述。鼠标右键画鼠标轨迹只有画的特别准才会使用，这个很难用了。之前用着不错一直在用现在用不了了。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
检查一下这里的设置
![image](https://github.com/user-attachments/assets/6324cc8d-d491-48f6-95ee-77727bbb42e6)
