### ISSUE TITLE
希望有更方便的在多个页签中转移动作的方法

### ISSUE THREAD

**Issue by wonder13579** [cuiliang/QuickPadCn#2120]
![image](https://github.com/user-attachments/assets/e1b29237-41a8-4ad3-8934-79f8eb16b3b2)
如图，当想要将下面的页签中动作拖动到其他页签中时，似乎只能放到上面固定位置后再转移，不太方便。拖动动作时不能通过滚轮切换页签，如果能在拖动同时切换应该会方便很多。

**Comment by cuiliang** [comment]
可以试试右键剪切后，在目标位置粘贴。 另外也可以直接在场景与动作管理设置窗口里移动，获结合场景与设置管理窗口、面板窗口（钉住+锁定）来拖动。
