### ISSUE TITLE
长按右键弹出面板问题

### ISSUE THREAD

**Issue by baileichao** [cuiliang/QuickPadCn#2123]
在弹出面板的鼠标方式里面选择长按右键，但是按下右键就会弹出面板，而不是长按，以前好像是可以的，好久没有用了，今天用的时候，突然就是这样子了。

**Comment by cuiliang** [comment]
截图看看设置。
另外看看这里的参数
![image](https://github.com/user-attachments/assets/1e46934c-a39e-4c77-b5b4-3f61a5999c3d)

**Comment by baileichao** [comment]
应该是这个触发时间问题，改长了点就好了，感谢感谢。
很奇怪，从来没有动过这里，突然就变小了，尴尬。
