### ISSUE TITLE
点击quicker面板窗口外面的位置不能自动关闭面板窗口

### ISSUE THREAD

**Issue by nameamtf** [cuiliang/QuickPadCn#2124]
**描述BUG**
点击quicker面板窗口外面的位置不能自动关闭面板窗口。

**重现步骤**
1.在任意界面调出quicker界面。
2.如果点击使用了quicker上的任何一个动作，quicker界面会自动消失。
但是如果不点击quicker上的任何一个动作，而是点击面板之外的任意位置，那么quicker界面不会自动消失！

**环境信息:**
 - 操作系统版本：Windows 10 企业版 LTSC，具体版本号：21H2
 - Quicker版本：版本1.43.30

**附加信息**
以前也是使用这个操作系统，也是使用quicker，没有这个问题。最近重装了这个系统，就出现这个问题。更新了quicker的版本，还是出现这个问题。不知什么原因。该怎么解决呢？

**Comment by cuiliang** [comment]
重启一下quicker之后正常么？ 录个屏看看。

**Comment by nameamtf** [comment]
我录制了一个问题复现的视频，请指教！[quicker面板不能自动关闭的问题](https://www.bilibili.com/video/BV13c4cejEUH/?vd_source=e2a1a0592269ceb2d8eaf696de86835f  "target=_blank")

**Comment by cuiliang** [comment]
你的鼠标有设置左右交换按键了没有呢，或其它类似的和鼠标有关的设置？
另外还可以从这些方面排查一下：
1）退出所有其它软件，包括鼠标的驱动程序（如果有的话），排查一下有没有干扰。
2）更换一个其它品牌的鼠标测试一下。
