### ISSUE TITLE
开机后第一次打开“搜索”功能，如果马上输入内容，一定会闪退

### ISSUE THREAD

**Issue by QtHamster** [cuiliang/QuickPadCn#2125]
**描述BUG**
开机后第一次使用“搜索”（通过设置快捷键 alt+空格 打开）功能，如果在搜索框显示的瞬间快速输入内容，那软件就一定会闪退。

**环境信息:**
 - 操作系统版本：Windows 11（专业版） 24H2  26100.1591 
 - Quicker版本：1.43.29
 - 内存：16GB
 - 处理器：AMD Ryzen 5 PRO 2500U（核显）

**出现时间:**
好像很长时间了

**Comment by cuiliang** [comment]
参考这里抓取dump压缩一下发到197906 QQ邮箱看看 https://getquicker.net/KC/Kb/Article/1119

**Comment by QtHamster** [comment]
> 参考这里抓取dump压缩一下发到197906 QQ邮箱看看 https://getquicker.net/KC/Kb/Article/1119

不行，只要复现闪退。打开的抓取工具窗口也会一起闪退。目录下也没有生成 dmp 文件（完全按照压缩包的使用说明，中文路径，管理员权限打开），但是我发现，这种情况只有软件打开的一段时间内，会出现。过了几分钟以后就没有了。不懂计算机，但直观感受像是，quicker的功能启动加载像是有顺序的，我可能在quicker还没加载到“搜索”或者没加载完的情况下，提前使用了该功能，然后就会出现上边陈述的闪退情况

**Comment by cuiliang** [comment]
“中文路径”是不是错了？  存在这种可能，因为索引是需要一些时间的，可能几秒或几十秒，但是闪退可能是某个bug。

**Comment by QtHamster** [comment]
> “中文路径”是不是错了？ 存在这种可能，因为索引是需要一些时间的，可能几秒或几十秒，但是闪退可能是某个bug。

是非中文路径，非字误删了。我在尝试看看能不能抓到吧，还有没有其他方法可以获取到这个dmp文件，quicker 有日志么？日志有用么？

**Comment by cuiliang** [comment]
可以看看windows时间查看器--应用程序里有没有什么日志消息。 另外有些输入法可能也有影响，试试将默认输入法改成另外一种。

**Comment by QtHamster** [comment]
> 可以看看windows时间查看器--应用程序里有没有什么日志消息。 另外有些输入法可能也有影响，试试将默认输入法改成另外一种。

好像真是输入法的问题，把第三方输入法删除后，重启两次测试：第一次，没闪退很流畅。第二次，搜索框卡了一下（好像是我鼠标点了一下其他地方，搜索框消失了）但是依然没出现 quicker 闪退的情况
