### ISSUE TITLE
启动时提示"您的凭据即将到期，请尽快同步数据"

### ISSUE THREAD

**Issue by starx007** [cuiliang/QuickPadCn#2126]
我之前买了会员，拷了一份到单机使用，最近单机启动时出现提示"您的凭据即将到期，请尽快同步数据"，重新从外网拷贝覆盖单机的安装文件夹，也不能解决问题。请问大神怎么办？

**Comment by cuiliang** [comment]
可能：
1）外网的数据本身很久没有同步。
2）拷贝的数据不正确，确保data目录里所有文件，至少有quicker.db，都拷贝了。
3）拷贝的目标位置不正确。
检查下看看。
