### ISSUE TITLE
微软中文输入法导致文件搜索异常

### ISSUE THREAD

**Issue by huqzc** [cuiliang/QuickPadCn#2127]
**描述BUG**
使用搜索工具配合Everything进行文件搜索时，如果使用的是微软中文输入法，会导致搜索结果出现异常。
具体表现为 Everything 中包含“档案”字样的文件有188份，但在 quicker 中显示的文件数量是随机变化的。

**重现步骤**
1. 打开搜索框
2. 用微软中文输入法输入查询条件（中文）

**相关截图**
![image](https://github.com/user-attachments/assets/f325e003-20f5-4ccb-a157-4a2e240f11c6)

**环境信息:**
 - 操作系统版本：Win10 22H2
 - Quicker版本： 1.43.29

**附加信息**
关键属性：componsitonstart和componsitonend。
应该是微软中文输入字符触发问题，导致异步查询结果被顶替

**Comment by cuiliang** [comment]
我也观察到这个现象，可能是因为连续的everything接口调用，有时候会导致某个查询返回的结果不正确。不过目前还没有找到很好的办法

**Comment by cuiliang** [comment]
试一下 1.43.32版本有没有改善 https://getquicker.net/Help/Versions

**Comment by cuiliang** [comment]
1.43.33 应该解决了。 https://getquicker.net/Help/Versions

**Comment by huqzc** [comment]
大佬nb，1.43.33已经正常使用了。
这效率没得说，必须上专业版支持。
