### ISSUE TITLE
添加启动软件的时候报错

### ISSUE THREAD

**Issue by a448900879** [cuiliang/QuickPadCn#2128]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
[2.](url)

**相关截图**
如果适用
![微信图片_20241017095830](https://github.com/user-attachments/assets/085f0e95-02d3-4703-9555-41f9583536f1)
，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：WIN10
 - Quicker版本：最新

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
可能win10版本太老，试试更新一下。 目前是多少版？

**Comment by a448900879** [comment]
10.0.17763.253

**Comment by cuiliang** [comment]
这个功能需要win10 19041。 后续版本考虑兼容一下

**Comment by a448900879** [comment]
行，我尽快升级

**Comment by jzeb** [comment]
版主，只有在10.0.17763.253版本下有这样的问题吗？

**Comment by cuiliang** [comment]
@jzeb 10.0.19041 以下的都会有，这个API是 10.0.19041.0 引入的。 https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinfo.getfromappusermodelid?view=winrt-26100 
你们的win10为啥不升级呢？

**Comment by cuiliang** [comment]
@jzeb @a448900879 更新了1.43.35版本，可以试下是不是还报错 https://getquicker.net/Help/Versions

**Comment by jzeb** [comment]
我看到文章写的是安装KB5011048这个补丁会报错，新版本是否已经修复了这个BUG，还是需要我卸载这个补丁？

**Comment by cuiliang** [comment]
@jzeb 不了解补丁的情况。如果已经不报错就不需要做什么了，如果还报错可以升级到这个版本试试。

**Comment by jzeb** [comment]
也就是这个文章，你看一下   https://getquicker.net/KC/Kb/Article/1092

**Comment by cuiliang** [comment]
@jzeb 和本帖问题无关。

**Comment by cuiliang** [comment]
https://getquicker.net/Help/Versions  已更新1.43.38 修复了此问题。
