### ISSUE TITLE
反馈 Translator 动作问题

### ISSUE THREAD

**Issue by Louie997** [cuiliang/QuickPadCn#2129]
你好：
由于我无法绑定手机号，所以无法在动作网页反馈问题。
请问是否可以帮我反馈或联络 Translator 动作（[Translator - by zryan - 动作信息 - Quicker](https://getquicker.net/Sharedaction?code=04393db9-f4bc-4871-7fb6-08db2506d1ed)）的作者？
想反馈的问题如下，感谢。

### 想反馈的问题
Translator 的作者你好，想反馈的问题如下：
**描述BUG**
调用 Claude API 报错：认证失败

**重现步骤**
1. 添加 OpenAI 类服务
2. 模型：`claude-3-5-sonnet-20240620`
3. 自定义 API：`https://api.anthropic.com/v1/messages`（没有添加默认后缀）
4. 试过这样填写在其他软件可以使用

**相关截图**
![image](https://github.com/user-attachments/assets/82781bd8-3e62-4bd2-89e1-ba60c3f63e55)

请教一下出现这种情况的可能原因是什么？
感谢！

**Comment by cuiliang** [comment]
这个接口和openAI的接口不兼容吧。

**Comment by Louie997** [comment]
原来是这样，那可以请作者新增支持 Claude API 吗？感谢。

**Comment by Louie997** [comment]
@cuiliang 您好，我没有大陆的手机号码，也没有其他管道可以联系动作的作者了。
方便的话可以请您帮我联系 Translator 动作的作者，或在动作网页的讨论区贴上这个 GitHub 网页的链接，让作者看一下，看能不能支持 Claude API 吗？

不方便的话也没关系，我就关闭这个 issue 了。

**Comment by cuiliang** [comment]
联系了一下作者，目前确实不支持，等他有空再看看能不能增加支持。
![image](https://github.com/user-attachments/assets/de7ea23c-be13-4a74-83c5-da3f01e044b2)

**Comment by Louie997** [comment]
> 联系了一下作者，目前确实不支持，等他有空再看看能不能增加支持。 ![image](https://private-user-images.githubusercontent.com/1972649/377790307-de7ea23c-be13-4a74-83c5-da3f01e044b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDA4MjAsIm5iZiI6MTcyOTI0MDUyMCwicGF0aCI6Ii8xOTcyNjQ5LzM3Nzc5MDMwNy1kZTdlYTIzYy1iZTEzLTRhNzQtODNjNS1kYTNmMDFlMDQ0YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDgzNTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY1ODBhMzQ2MmJmZDU5YzA0ZWJjYTg4MDcwNTFhYzk5MGMwMWE4M2RiYWUzZGIzOTVkMGM2OWNkNGQzNWEyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.w4T2-p-9VVoNAhbJia8wGt9HxxmdRWJTEDU4MXMiL-M)

非常感谢！也感谢 Translator 作者！这个动作大大提升了我阅读论文的效率～

**Comment by ZzzzRyan** [comment]
前段时间比较忙，鸽了很久。刚刚更新的版本已添加支持，可以更新测试一下。

间隔了比较久的时间更新动作，可能会有不稳定的地方，如果有什么 bug 也欢迎继续反馈。

**Comment by Louie997** [comment]
> 前段时间比较忙，鸽了很久。刚刚更新的版本已添加支持，可以更新测试一下。
> 
> 间隔了比较久的时间更新动作，可能会有不稳定的地方，如果有什么 bug 也欢迎继续反馈。

感谢！
