### ISSUE TITLE
问题摘要

### ISSUE THREAD

**Issue by zlxuan** [cuiliang/QuickPadCn#2130]
**描述BUG**
动作库的网址不对了，请更新一下最新网址。

**重现步骤**
1.
2.

**相关截图**
![Snipaste_2024-10-23_14-44-04](https://github.com/user-attachments/assets/0158ada7-8612-45e9-957d-a21d8530026f)

**环境信息:**
 - 操作系统版本：win11
 - Quicker版本：正式版1.43.29和快速通道1.43.33都不行

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
感谢反馈，现在应该可以了。
