### ISSUE TITLE
能否为任务或者为单位时间（临时）创建场景？

### ISSUE THREAD

**Issue by zhaoyundi** [cuiliang/QuickPadCn#2131]
目前主要是基于软件进行的场景唤起，能否开发基于任务的场景？
即在某项特定的任务下，可能要唤起不同的软件和文件，能否支持此类工作流？

**Comment by cuiliang** [comment]
可以添加自定义场景，然后弄个动作加载此场景的动作页。

**Comment by zhaoyundi** [comment]
懂了，感谢
