### ISSUE TITLE
重置键盘状态希望加入快捷键控制和重置成功的提示

### ISSUE THREAD

**Issue by calmhot** [cuiliang/QuickPadCn#2132]
目前由于鼠标手势等等各种劫持键盘的工具安装及应用，导致很容易键盘某些按键无法被释放，需要经常性的手动重置键盘状态。
所以，如题！希望加入这个功能，右下角点击太罗嗦了

**Comment by ZzzzRyan** [comment]
做一个动作来重置，在动作里加提示消息，再给动作设置快捷键就可以了。

![image](https://github.com/user-attachments/assets/bd22216c-a2b1-429e-b081-ed070e213b73)

**Comment by calmhot** [comment]
收到，之前没找到相应动作的指令
