### ISSUE TITLE
弹出面板能否添加“按住移动”呼出功能

### ISSUE THREAD

**Issue by huasheng666** [cuiliang/QuickPadCn#2133]
1.实现类似轮盘菜单/鼠标手势的呼出方式
高级鼠标触发能实现类似效果，但不能“在按钮上松开后执行动作”

2.打开quicker后运行第一个动作短暂初始化

3.动作运行概率报错

4.运行模拟鼠标点击动作，后续鼠标指针漂移

5.请教如何实现用好压实现，自动输入记住密码并解压
无法解决解压窗口勾选3个复选框问题

以上是最近使用的一些情况，感谢！

**Comment by cuiliang** [comment]
1） 可以在高级鼠标触发里自定义规则。
2）可以在quicker里设置启动后自动运行一个动作。
3）xpath可能会变。用其它方式。
4）信息不足，无法判断。
5）可以找一下动作库里分享的解压缩类动作，使用7zip的。
