### ISSUE TITLE
问题摘要 火绒安全刚刚报毒了，系统卡住无法截图

### ISSUE THREAD

**Issue by nihao101813** [cuiliang/QuickPadCn#2135]
**描述BUG**
对bug的清晰简洁描述。

**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
干什么的时候报毒了？

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
