### ISSUE TITLE
quicker启动后立即报错

### ISSUE THREAD

**Issue by c12h180** [cuiliang/QuickPadCn#2136]
**描述BUG**
启动quicker后立即弹出报错提示

**重现步骤**
1.启动quicker
2.等待2秒quicker启动，报错了
3.双击报错弹窗后quicker卡死

**相关截图**
启动quicker后
![image](https://github.com/user-attachments/assets/6eb25728-ed13-4f64-b304-4674f8e33f86)
双击消息弹窗后
![image](https://github.com/user-attachments/assets/4f25c22c-991d-4fc3-bba8-274c1e525a84)

**环境信息:**
 - 操作系统版本：windows 10 专业版 22H2
 - Quicker版本：v1.43.46

**附加信息**
无

**Comment by cuiliang** [comment]
https://getquicker.net/kc/manual/doc/settings-autorunactions 
参考这里，强制禁止自动运行动作，启动后设置里删掉自动运行动作的规则。

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
