### ISSUE TITLE
显示菜单这个动作经常表现为弹出框闪现一下就没了

### ISSUE THREAD

**Issue by moroal** [cuiliang/QuickPadCn#2137]
**描述BUG**
显示菜单这个动作经常表现为弹出框闪现一下就没了

**重现步骤**
1.触发显示菜单
2.不选择
3.触发其他弹框如用户选择
4.触发显示菜单，会发现这一步应该出现的弹框出现不到1s就没了

**相关截图**

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.43.29

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
菜单是不会保持着屏幕上的，点其他地方会自动关掉。 要不关的话用自定义操作窗。

**Comment by moroal** [comment]
谢谢  我照文档加了个延迟50ms 解决了这个问题
