### ISSUE TITLE
问题摘要 点击《打开用户中心网页后》提示：找不到应用程序

### ISSUE THREAD

**Issue by NuclearKAI** [cuiliang/QuickPadCn#2139]
**描述BUG**
点击《打开用户中心网页后》提示：找不到应用程序

**重现步骤**
1.在呼出的快捷方式中点击用户头像，点击《用户中心》后
2.或者在设置中点击《打开用户中心网页》后

**相关截图**
![tmpEB78](https://github.com/user-attachments/assets/e7125b75-c0fb-4893-b49c-ae2b56a10c2b)

**环境信息:**
 - 操作系统版本：win10专业工作站版22h2
 - Quicker版本：1.43.47

**Comment by cuiliang** [comment]
你的windows里系统默认浏览器设置有问题。 可以试试修复一下，或重装一下浏览器，然后重启quicker。

**Comment by NuclearKAI** [comment]
就是系统默认浏览器没设置 好了谢谢
