### ISSUE TITLE
Quicker 与 PowerToys 同时运行产生的恶性 Bug

### ISSUE THREAD

**Issue by SunSeaLucky** [cuiliang/QuickPadCn#2142]
**描述BUG**
该 Bug 会导致 Alt 键一直被按下，即使用户关闭 Quicker 和 PowerToys。这会导致整个键盘几乎不可用。只有关机重启才能恢复正常。

我是 Quicker 的专业版用户，非常迫切地希望您尽快解决该问题。

**重现步骤**
1. 在 PowerToys 中设置按键重映射，Right Alt -> Esc。
2. 打开 Quicker 的搜索。
3. 随便搜索一个东西，按下 Right Alt + 1（加哪个数字都行）。
4. 随后就可以发现键盘上的 A-Z 以及数字键都失效了，这是因为 Right Alt 键一直处于被按下的状态。

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 11 22631.4460
 - Quicker版本：1.42.24

**附加信息**
- 为什么要设置 Right Alt -> Esc？
我是 Vim 的忠实用户，但苦于按下 Esc 需要移出 A-Z 的区域，因此设置 Right Alt -> Esc。
- 为什么我认为这是 Quicker 的 Bug 而不是 PowerToys 的Bug？
在 Quicker 中的搜索框中按下 Right Alt + Num 后，会立即导致此 Bug。即便 PowerToys 也有错，Quicker 也应当避免这种情况发生。至少不能使得用户在使用 Quicker 时，每做出这样的操作，就需要重启电脑一次。

**Comment by cuiliang** [comment]
可以打开这个重置几下键盘状态。
![image](https://github.com/user-attachments/assets/0e05b09c-8d4e-456a-b8fa-bf69517d81f9)

你遇到的问题是，RAlt的抬起消息被PowerToys拦截了。
这个不能算Quicker的问题，只有在没有其它程序影响的情况下出问题才能算Quicker的问题。
用程序映射按键都是基于键盘挂钩的，会导致按键错乱，特别是多个程序都使用键盘挂钩的时候，挂钩顺序是不确定的，会导致一系列难以预测的问题。

建议购买可以在底层修改按键的键盘来实现映射需求。

**Comment by SunSeaLucky** [comment]
谢谢，不过还是希望后期可以增加一个提示，至少提示用户不要尝试这么做...以免更多的人遇到同样的问题
