### ISSUE TITLE
很多动作会提示报错，但不影响动作正常执行

### ISSUE THREAD

**Issue by Bjorne1** [cuiliang/QuickPadCn#2144]
**描述BUG**
很多动作会提示报错，但不影响动作正常执行

**重现步骤**
1.智搜最新版本动作
2.执行就马上报错

**相关截图**
![PixPin_2024-12-06_16-22-42](https://github.com/user-attachments/assets/90922030-0c6a-42cb-80e7-0023b7fa8893)

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.43.47

**附加信息**
前几个版本更新后开始出现

**Comment by cuiliang** [comment]
很多动作都是一样的报错么？ 
试试下载最新版 https://getquicker.net/Help/Versions

**Comment by Bjorne1** [comment]
刚试了下，现在就这一个动作会这样。
更新了最新版本，还是会。
刚把该动作删了重新安装，不会了。
