### ISSUE TITLE
鼠标快捷键无法唤起quicker中的快捷键

### ISSUE THREAD

**Issue by wangzaohang** [cuiliang/QuickPadCn#2145]
**描述BUG**
在quicker中设置了动作触发按键，也在logi option+中设置了对应的快捷键，实际使用时发现鼠标快捷键无法唤起quicker中设置的动作

**重现步骤**
1.在quicker中设置x1键为鼠标方式弹出面板，1为动作触发按键（规范粘贴）
![image](https://github.com/user-attachments/assets/b43d9e7b-3de4-4bfe-a9db-69496989fcdf)
![image](https://github.com/user-attachments/assets/d0007d0d-bd4f-4fb0-974d-272ce9edf7bf)

2.在logi option+中设置x2键为quicker中的1
![image](https://github.com/user-attachments/assets/8e5b4607-9693-4d5a-b237-c559cd0efea2)

3.实际操作中，x1可唤起quicker，但按下x2后无反应（且quicker界面的快捷键无显示）
![image](https://github.com/user-attachments/assets/bd4e604d-3f3f-4cf5-801c-98bdda8c8fb7)
对比：正常情况下设置了动作触发按键之后quicker界面应显示快捷键
![image](https://github.com/user-attachments/assets/d4455c9c-cd53-4abd-8de3-e5554aac9f5a)

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows 11 家庭中文版 21H2 22000.2538
 - Quicker版本：1.43.29

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
必须上面显示按键的时候，按键才有效。
弹出面板改成中键或右键试试。 
这个鼠标的x键比较特殊，可能有影响。 [什么是鼠标X键（X1键、X2键、侧键） - Quicker](https://getquicker.net/KC/Kb/Article/927 )

**Comment by wangzaohang** [comment]
> 必须上面显示按键的时候，按键才有效。 弹出面板改成中键或右键试试。 这个鼠标的x键比较特殊，可能有影响。 [什么是鼠标X键（X1键、X2键、侧键） - Quicker](https://getquicker.net/KC/Kb/Article/927)

按照您的方法改设置了，还是没办法

**Comment by cuiliang** [comment]
按中键出来的面板也没有这个字符？
![image](https://github.com/user-attachments/assets/28ca45cd-cbc8-41be-bb9c-641233234831)

**Comment by wangzaohang** [comment]
有这个字符，但按鼠标上快捷键还是唤起不了

**Comment by cuiliang** [comment]
那就是另外的问题，可能是
1）键盘上有2个‘1’，数字区和小键盘区域是不同的字符。 
2）Quicker通常不支持模拟的按键用来触发功能。

**Comment by wangzaohang** [comment]
谢谢您，我尝试把‘1’换成其他字母也不能成功，应该是原因2，感谢您的解答！
