### ISSUE TITLE
创建自定义菜单的耗时建议

### ISSUE THREAD

**Issue by moroal** [cuiliang/QuickPadCn#2146]
**描述BUG**
创建自定义菜单的耗时建议优化一下，缩短响应时间；特别简单的3级菜单项共90多个显示菜单步骤花费了接近3s多
![image](https://github.com/user-attachments/assets/66837633-b70b-43f9-bbb0-80dc08f2f8e3)

**重现步骤**
1.创建自定义菜单
2.菜单数据
菜单|operation=&data=1
 菜单|operation=&data=1
  菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
  菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
  菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
   菜单|operation=&data=1
菜单|operation=&data=1
 菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
 菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
 菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1
  菜单|operation=&data=1

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：
 - Quicker版本：

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
这个时间不是创建的时间，而是从开始到最后选择完菜单的时间。要想统计精确的创建时间，可以用手机录屏一下慢动作试试。

**Comment by moroal** [comment]
原来是这样
