### ISSUE TITLE
手势操作

### ISSUE THREAD

**Issue by CharMingF** [cuiliang/QuickPadCn#958]
**需求描述**
WGestures 1.8.3.0
这是一个免费且开源的软件，这个软件的屏幕边角辅助已经被quiker吸收了。

**描述你想要的解决方案**
手势也可以融合一些，融合在鼠标辅助中，比如简单的手势

**Comment by cuiliang** [comment]
专业版有手势功能，如有需要可以试试。一遍建议使用轮盘，可视化操作更简单。
