### ISSUE TITLE
希望在显示文本模块中对扩展操作增加自定义快捷键

### ISSUE THREAD

**Issue by MisterZakary** [cuiliang/QuickPadCn#960]
**需求描述**
显示文本模块中拓展操作只能使用鼠标点击方案。

自行设计了一个计算页面板，计算每一行的结果，我可以使用快捷键快捷调用出计算页面板，但是必须使用鼠标点击我的扩展操作，实在是很不方便，希望可以增加拓展操作的自定义快捷键，实现全键盘操作。

**Comment by cuiliang** [comment]
扩展按钮名字中可以使用快捷字符_c  表示alt+c。只支持这样的。

**Comment by MisterZakary** [comment]
收到，谢谢



在 2020-05-11 14:48:22，"CuiLiang" <notifications@github.com> 写道：

扩展按钮名字中可以使用快捷字符_c 表示alt+c。只支持这样的。
