### ISSUE TITLE
更新安装错误

### ISSUE THREAD

**Issue by zhzhenhua** [cuiliang/QuickPadCn#961]
**更新软件安装报错**

**相关截图**
![20200511_2202121](https://user-images.githubusercontent.com/41117067/81572358-b3ad0800-93d5-11ea-8f96-7f35e5eb6d46.png)
![20200511_2206082](https://user-images.githubusercontent.com/41117067/81572408-c293ba80-93d5-11ea-863e-550d6c020e7d.png)

**环境信息:**
 - 操作系统版本：win10
 - Quicker版本：1.5.2.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
https://www.yuque.com/quicker/help/install#EL8DU
