### ISSUE TITLE
如果设置了特殊控制键，偶尔会出现打字不顺畅的情况

### ISSUE THREAD

**Issue by github-lxf** [cuiliang/QuickPadCn#962]
**描述BUG**
如果设置了特殊控制键，偶尔会出现打字不顺畅的情况，win7和win10都存在这种情况

![bug](https://user-images.githubusercontent.com/64951877/81647608-e0a5fd00-945f-11ea-8c2b-12dc669b4b8e.gif)

**Comment by cuiliang** [comment]
扩展热键依据其实现原理，会先拦截控制键。如果这时候按了第二个键但是又先抬起了第二个键（通常在输入内容的时候时不能确定实际抬起按键的顺序的），就会识别成一个组合按键，从而影响输入。
目前做的一个优化时在快速输入的时候，按键距离上一个按键时间比较短的情况下，会把控制键作为普通键处理。
这个后期再看看有没有别的优化方式。

另外可以试试换个输入法看看会不会好点。

**Comment by guoranjun2** [comment]
关于扩展按键的使用采用区分原则可不可行呢？
对于频繁用于打字输入的按键，如回车、空格键等，短时间内的连续输入不启用扩展按键的设置，仅在设定的时间超时后才启用；
但是对于很少用于打字的按键，比如Capslock这样的按键则设定按键松开后才启用原功能，松开前进入扩展按键的等待操作。
之所以提出上面的设想是因为，目前的扩展按键经常出现误操作，如果是在打字速度比较快的情况下，用扩展按键移动光标极其容易出现失误，频繁的纠正反而得不偿失。

**Comment by cuiliang** [comment]
@guoranjun2 求详细误触发的过程。 目前如果引导键启用了原有功能（如空格回车这类），在连续输入的情况下是不会识别为引导键的。

**Comment by guoranjun2** [comment]
> @guoranjun2 求详细误触发的过程。 目前如果引导键启用了原有功能（如空格回车这类），在连续输入的情况下是不会识别为引导键的。

您说的对，我没有表达清楚，我的意思刚好相反，我想让连续输入时让按键仍然启用引导键的功能，因为现在稍微打字快一点，接着马上用扩展按键移动个光标啊啥的，这时由于停顿的时间较短，按键没有激活引导作用，屏幕就会打出一串字母，然后清理这些字符就挺费时间的。（现在又想了一下，这样也有不妥的地方，像空格或者回车这样的按键长按可能就失去作用了）
可能还是建立起使用习惯才是最佳的方案吧。

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
