### ISSUE TITLE
手机APP上传目录不支持系统变量定义路径

### ISSUE THREAD

**Issue by EX-XD** [cuiliang/QuickPadCn#966]
**描述BUG**
我在设置中对APP的保存位置使用了 %OneDrive%\Software\Quicker\SendbyPhone  这样的路径，实际使用中APP显示上传成功，但是文件夹中并未看到相关图片。

**环境信息:**
 - 操作系统版本：Win 10 Pro 1909.18363.778
 - Quicker版本：1.6.7.0

**附加信息**
其实我印象中之前某个版本我刚设置为系统变量时，是能正常使用的，有段时间没用这功能了，今天发现用不了。而且我是先发现用不了，才检查软件更新更新到1.6.7.0的，更新后依然不行。

**Comment by cuiliang** [comment]
这个应该是一直没有的。 等下个版本加一个。

**Comment by cuiliang** [comment]
快速通道已更新1.7.3版本，可以试试是否可以。
