### ISSUE TITLE
占用右键

### ISSUE THREAD

**Issue by FX603** [cuiliang/QuickPadCn#968]
**描述BUG**
对bug的清晰简洁描述。
有些时候点击鼠标右键也会调用Quicker软件
**重现步骤**
1.
2.

**相关截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境信息:**
 - 操作系统版本：Windows10
 - Quicker版本：1.6.7.0

**附加信息**
在此添加有关此问题的任何其他上下文。

**Comment by cuiliang** [comment]
如果有360，请先卸载360. 
如果没有，请参考文档设置弹出方式。
