### ISSUE TITLE
在这里写需求摘要：希望能够优化一下内存占用

### ISSUE THREAD

**Issue by Hefang2000** [cuiliang/QuickPadCn#970]
quicker是目前少数几个不时能食用我机150M以上内存的乖乖

**Comment by cuiliang** [comment]
.NET 编写的软件相对会耗费内存一些。 Quicker又会有很多图片显示、显卡渲染。
通常占用在100-200M左右吧，如果编辑动作，会占用比较多一些。
趁现在内存比较便宜，可以加一条试试。

**Comment by Hefang2000** [comment]
抱歉啊，不是内存不够，可能是自己有些强迫症的*v*

**Comment by cuiliang** [comment]
关闭古老issue中，感谢！
