### ISSUE TITLE
步骤组里支持多线程试试，步骤组里的每个步骤同步执行

### ISSUE THREAD

**Issue by cuiliang** [cuiliang/QuickPadCn#972]
步骤组加个选项

**Comment by kanglade** [comment]
我感觉一个大步骤组中的多个小步骤组同步执行更常见，而不是步骤组中的每个步骤同步执行，大多数一个步骤的执行还是要基于上个步骤的

**Comment by cuiliang** [comment]
这个步骤组的下一级应该是步骤组或如果这样的组合模块。
每个组合模块作为一个线程执行。

**Comment by cuiliang** [comment]
1.7.4
