### ISSUE TITLE
全屏游戏时，弹出面板黑名单无效，只能设置全屏禁止弹出

### ISSUE THREAD

**Issue by WangYH195** [cuiliang/QuickPadCn#975]
但是有些时候还需要在其他全屏软件弹出面板，很不方便，游戏是坦克世界，游戏在全屏和窗口模式下黑名单都无效，edge浏览器测试也无效

**Comment by cuiliang** [comment]
有些软件会有多个进程组成。 游戏这类还会有一些干扰无法判断进程。需要的时候用快捷键暂停quicker吧。
