### ISSUE TITLE
建议：1.表单模块增加置顶选项  2.运行其他动作模块支持弹出调试信息

### ISSUE THREAD

**Issue by guoranjun2** [cuiliang/QuickPadCn#980]
1.表单模块增加置顶选项  
有时填写表单需要往返复制粘贴内容，如果将表单置顶不易被其他窗口遮挡。

2.运行其他动作模块支持弹出调试信息
如果动作中有运用其他动作的情况下，调试运行时不会弹出引用的动作的调试信息，这个一定程度上折损调试的效率，希望能够也弹出引用的动作的调试信息。

**Comment by cuiliang** [comment]
表单不适合置顶操作，会遮盖其他部分，建议调整屏幕布局。
运行其他模块无法指示使用调试。需要调试可以用“运行或打开”，使用uri方式
quicker:debugaction:动作名称或id

**Comment by guoranjun2** [comment]
好的，我明白了
