### ISSUE TITLE
“按键操作”如果选择“按下按键”可以勾选稍后是否自动抬起

### ISSUE THREAD

**Issue by NewbieToEverything** [cuiliang/QuickPadCn#983]
“按键操作”模块中，如果选择“按下按键”操作，一般都会在后面跟上一个“抬起按键”的操作，但反过来则不需要。可以考虑提供按下后自动抬起的功能作为选择。
比如，选择“按下按键”以后窗口内自动新增选项
![image](https://user-images.githubusercontent.com/36309469/82302357-12810b80-99ec-11ea-89d9-65cf7feee1fa.png)
如果有必要可以增加调整等待时间，如XX毫秒后自动抬起，提供一个默认等待时间。

**Comment by cuiliang** [comment]
这个可以直接用模拟按键实现。按键操作只是用于需要将两者分开的情况。

**Comment by NewbieToEverything** [comment]
模拟按键B也可以么？
模拟按键A我知道肯定可以，但是我碰过模拟按键A失效的情况，自此之后我都是尽量避免使用模拟按键A。而模拟按键B从用户手册上看，支持的按键是有限的，比如数字就不行，所以我才用的按键操作。

**Comment by cuiliang** [comment]
嗯，模拟按键就是模拟按键点击的功能，除了win之外，其他应该都是可以的，而且可以一串一起。参见模块说明。
