### ISSUE TITLE
可选择取消部分进程屏幕边缘调节音量

### ISSUE THREAD

**Issue by YangB0502** [cuiliang/QuickPadCn#995]
**需求描述**
对屏幕边缘滚轮调节系统音量的功能，在玩如GTA5等锁定鼠标指针的游戏时，因为不知道鼠标的实际位置，经常会无意间改变系统音量。

**描述你想要的解决方案**
增加选择对部分进程禁用该功能的设置。

**描述您考虑过的替代方案**
无

 **其他上下文**
无

**Comment by cuiliang** [comment]
建议使用快捷键暂停Quicker。
因为播放视频的时候会经常调整音量，所以不能自动进行全屏应用禁用。
增加额外的配置又会导致额外的配置复杂程度。

**Comment by cuiliang** [comment]
归档
