### ISSUE TITLE
动作名换行显示

### ISSUE THREAD

**Issue by cesaryuan** [cuiliang/QuickPadCn#997]
**需求描述**
当动作名比较长的时候，字太小根本看不清，建议可以换行显示

**描述你想要的解决方案**
动作名换行显示

**描述您考虑过的替代方案**
动作名换行显示

 **其他上下文**
![image](https://user-images.githubusercontent.com/35998162/82748534-27d3ac80-9dd5-11ea-922d-72d0a66b6712.png)

**Comment by cuiliang** [comment]
不要用很长的名字。
如果需要换行，可以在文字中间插入\n
