### ISSUE TITLE
OCR只复制内容，不需要弹出编辑窗口

### ISSUE THREAD

**Issue by WangYH195** [cuiliang/QuickPadCn#999]
OCR功能只复制内容，不需要弹出编辑窗口
截图，OCR，复制内容到剪贴板，不要弹出编辑窗口

**Comment by cuiliang** [comment]
不需要弹窗的可以使用截图OCR无弹窗版：https://getquicker.net/Sharedaction?code=0310465e-18f7-45bb-e065-08d70f398a04



需要一键搜索的可以使用OCR搜索动作：https://getquicker.net/sharedaction?code=ea21ba4e-6685-4e06-da4d-08d7880f80dc
